### ISSUE TITLE
is:issue is:open Can't using VLC player to view rtsp streaming

### ISSUE THREAD

**Issue by anhlt309** [ant-media/Ant-Media-Server#1]
I have some video .mp4 at /webapps/vod/streams/. The server started successful, but when using VLC player to view streaming, I had got debug:
 [DEBUG] [pool-11-thread-4] com.antstreaming.rtsp.RtspMinaIoHandler - sent message: RTSP/1.0 461 Unsupported transport

And Vlc player inform Your input can't be opened.

So, how can i use vlc player to view streaming and how to enable unicast stream from server or enable TCP stream.?
Thank you!

**Comment by mekya** [comment]
Hi @anhlt309 ,
There may be a couple of issues you need to check. Could you please write down to full address that you plan to play?

Secondly, ant Media Server supports UDP transportation, please uncheck TCP in RTSP streaming if it is checked. Do you know where to change this settings? I can send a screenshot if you need.

**Comment by anhlt309** [comment]
Here my local address: rtsp://192.168.0.3:5554/vod/mu-mc-icc.mp4
I just paste this link to VLC Player and get error output at ant media server:
[DEBUG] [pool-11-thread-6] com.antstreaming.rtsp.RtspMinaIoHandler - RTSP Server Receive Message: 
SETUP rtsp://192.168.0.3:5554/vod/mu-mc-icc.mp4/streamid=1 RTSP/1.0
CSeq: 7
User-Agent: LibVLC/2.2.6 (LIVE555 Streaming Media v2016.02.22)
Transport: RTP/AVP;unicast;client_port=55476-55477


[DEBUG] [pool-11-thread-6] com.antstreaming.rtsp.RtspMinaIoHandler - sent message: RTSP/1.0 461 Unsupported transport
CSeq: 7

How to change TCP to UDP in RTSP streaming? Thank you!

**Comment by anhlt309** [comment]
Another problem: When I was playing rtsp url at client, ant server output error and video was paused:
[WARN] [RTMPConnectionScheduler-13] com.antstreaming.rtsp.PacketSenderRunnable - Error muxing packet with error: -22

**Comment by mekya** [comment]
Hi,
I have just sent a commit (https://github.com/ant-media/Ant-Media-Server/commit/88139878eabc3b0d01c52b4d8235267f745dd666) to the repo, you can clone repo and compile project or 
you can download and extract the attached file to Ant Media Server folder and then try again. Please let me know if you encounter any problem.

[ant-media-server.jar.zip](https://github.com/ant-media/Ant-Media-Server/files/1191591/ant-media-server.jar.zip)

**Comment by anhlt309** [comment]
Thank you, now I can play by VLC player but when I was playing rtsp url at client, ant server output error and video was paused:

[rtp @ 0x7fd00c0180c0] Packet with invalid duration -9223372036854775808 in stream 0
[rtp @ 0x7fd00c0180c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 12635460 >= NOPTS
[WARN] [RTMPConnectionScheduler-13] com.antstreaming.rtsp.PacketSenderRunnable - Error muxing packet with error: -22

**Comment by anhlt309** [comment]
I attach a log file from ant media server when start to play an url on VLC player. You can read for more details.
[ant-rtsp-log.txt](https://github.com/ant-media/Ant-Media-Server/files/1192410/ant-rtsp-log.txt)

**Comment by mekya** [comment]
Hi @anhlt309 ,

Yeah "[rtp @ 0x7fd00c0180c0] Packet with invalid duration -9223372036854775808 in stream 0" is an issue on ffmpeg library. It gives this error when it does not find timestamp for the packet. Especially  in rtsp streaming, it always gives this error for some initial packets even if you use ffmpeg in command prompt. Fourtunately, it is not a problem for streaming.

**Comment by anhlt309** [comment]
Thank you. And Can I change path to local video files for rtsp streaming, not only /webapps/vod/streams ?

**Comment by mekya** [comment]
You may need to create soft link on webapps/vod/streams directory to point to local video files.

It is a simple issue with a shell script. I can write a shell script for you ;) That you can give directory names as parameter.

**Comment by mekya** [comment]
Closing issue. If you have any problem, please let know.

**Comment by dattt01** [comment]
@anhlt309 ơi, anh liên hệ lại giúp em gấp nha anh, em cám ơn anh. phongtt1925@gmail.com.
