### ISSUE TITLE
rtmp playback error with webrtc app

### ISSUE THREAD

**Issue by quickstreamingmedia** [ant-media/Ant-Media-Server#10]
i have installed on ubuntu 16.04 with java 8 jdk streaming going fine but playback rtmp not working you can add me on whats app +85599974703

# Issue

### Short description
__Brief description of what happened__

### Environment

[] Operating system and version:
[] Java version:
[] Red5 version:

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mekya** [comment]
I've added on whatsapp. Let's continue there.

**Comment by mekya** [comment]
Closing this issue. Please reopen or send a comment it if you have still problem
