### ISSUE TITLE
View logs on web panel 1

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#100]

**Comment by SelimEmre** [comment]
![logview.JPG](https://images.zenhubusercontent.com/5b06ddb64b5806bc2bd47c91/d8773140-4d2e-4428-8e3b-c0efeb9327cf)

![logchange.JPG](https://images.zenhubusercontent.com/5b06ddb64b5806bc2bd47c91/41cdd05a-3b54-4cc2-9de7-4e19904be397)
