### ISSUE TITLE
Doc: FAQ

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#1003]
- [ ] Talk with Khan
- [ ] Load test results
- [ ] Pixelating of frames in WebRTC
- [ ] Frame freezing
- [ ] WebRTC Bitrate limitations (Quality of WebRTC is good but priority is the latency over quality)
- [x] ICE failed, add a STUN server and see about:webrtc for more details

**Comment by SelimEmre** [comment]
http://docs.antmedia.io/en/latest/FAQ.html
