### ISSUE TITLE
Add a rest method that accept user assigned stream id 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1007]

**Comment by maydin** [comment]
Customer requirement:
 Our final solution will assign an unique stream ID/key for each OBS installation, that means one stream ID/key will be re-used many times.    The uses-case is as below for illustration: 1) End user (broadcaster)'s OBS installation has uniquely assigned stream ID/key preset by the system software 2) When there is live broadcast, the system will create a stream with its dedicated stream ID/key, and the broadcaster will start streaming RTMP via the OBS 3) When the live broadcast is ended, the system will delete this dedicated stream ID/key from the webRTC server 4) And may be, say 4 hours later the broadcaster do live broadcast again, the system will create stream of the same unique stream ID/key 5) And similarly, when the live broadcast is end, the system will delete this dedicated stream ID/key
