### ISSUE TITLE
Not Getting Audio

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1027]
# Issue

### Short description
__Brief description of what happened__

So im using `http://localhost:5080/WebRTCApp/` to stream and i have given it access to video and audio yet the audio does not come through on either the hls stream or the stored mp4 file.

### Environment

* Operating system and version: macosx lastest as of (Tuesday 12 march 2019)
* Java version: latest
* Ant Media Server version: latest community edition
* Browser name and version: chrome latest

### Expected behavior
__Put as much detail here as possible__

audio should come through with the video. also video quality is low

### Actual behavior
__Put as much detail here as possible__

video and audio should come through

### Steps to reproduce
1. start server
2. broadcast
3. play

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey 

Thanks for the feedback. We fixed in new release this situation.

If you have any question, please feel free to let us know. 

Best Regards,
Selim

**Comment by The-Code-Monkey** [comment]
@selimemre when will the new release be out?

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

We are planning to release a new version this week.

**Comment by The-Code-Monkey** [comment]
thank you this package is a great help

**Comment by The-Code-Monkey** [comment]
@SelimEmre Do you have a more specific time and date for the next release??

**Comment by The-Code-Monkey** [comment]
@SelimEmre You said there would be a fix for the audio what does this fix actually do and how do i replicate it to get it to work??
