### ISSUE TITLE
Latency Too High 10s +

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1028]
# Issue

### Short description

The latency is more than 10s all the time way too high

### Expected behavior

Latency should be 5s max if not less

### Actual behavior

Latency is too high

### Steps to reproduce
1. run default package

i have tried the solution in the previous issues and it did not change a thing.

**Comment by The-Code-Monkey** [comment]
I understand this could be because im running it locally on my mac but even still its quite slow.

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,
HLS streaming may not be a convenient method for low latency. To reduce the HLS latency there are some parameters and it can be reduced to 8-10 secs for now. WebRTC streaming can be a convenient solution for Low Latency.

**Comment by The-Code-Monkey** [comment]
How do I turn on webrtc one to many??

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Ultra Low Latency Adaptive One to Many WebRTC Live Streaming in Enterprise Edition. 
Thanks.
