### ISSUE TITLE
Video Resolution and FPS

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1034]
# Issue

### Short description

Can't find any docs saying how to change the video resolution as its currently coming out at 640x480@8fps how do i change this and force a 720p or 1080p at a specific frame rate

### Environment

* Operating system and version: latest macos
* Java version: latest
* Ant Media Server version: latest
* Browser name and version: latest chrome

### Expected behavior

Should be able to change the encoding settings even if its just a dropdown.

maybe the possibility to choose different encoding formats too, e.g. h264, h265

### Actual behavior

output video is 640x480@8fps

### Steps to reproduce
1. default package

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Thank you for your interest. Unfortunately, Transcoding feature is in Enterprise Edition. Also, FPS feature can be set in WebRTC Enterprise Edition.

Best Regards,
Selim

**Comment by The-Code-Monkey** [comment]
So I can't up the resolution in the non enterprise edition at all. Seems strange to limit me to 480p maybe you should up it to 720p and if you want over that you will need enterprise edition it's 2019 nothing should be playing in 480p

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Sorry for the misunderstood. You can change Video Resolution in OBS. Please review this video tutorial: https://www.youtube.com/watch?v=w8c7w5DxZ5k

Best Regards,
Selim

**Comment by The-Code-Monkey** [comment]
Oh I know about OBS I need to know how I can change the whole encoding settings the MP4 is coming out at 480p

**Comment by The-Code-Monkey** [comment]
What can I do about setting the FPS to 60 rather than it being random like it currently is

**Comment by JonathanBristow** [comment]
@The-Code-Monkey  Did you work out how to change the res in the Ant Media server?

**Comment by The-Code-Monkey** [comment]
I think I did it's been a while but I had to use the source code find where there were references to 480 and change them and their counter parts to the resolution that I wanted

**Comment by mekya** [comment]
We've provided a solution. It's available in the 2.2.0-SNAPSHOT
You can give add a property 

```
settings.heightRtmpForwarding=720
```
Its default value is 360
https://github.com/ant-media/Ant-Media-Server-Common/blob/master/src/main/java/io/antmedia/AppSettings.java#L877

**Comment by JonathanBristow** [comment]
@mekya  Do you have a link to any docs showing where and how to set these values?

**Comment by JonathanBristow** [comment]
@mekya  Also - we can I get the SNAPSHOT releases?

**Comment by mekya** [comment]
TBH, I've provided a simple instructions for that. 

We've provided a solution. It's available in the 2.2.0-SNAPSHOT
You can give add a property

> settings.heightRtmpForwarding=720
> Its default value is 360
> https://github.com/ant-media/Ant-Media-Server-Common/blob/master/src/main/java/io/antmedia/AppSettings.java#L877

The App Configuration settings are also documented here. 
https://github.com/ant-media/Ant-Media-Server/wiki/Application-Configuration-Documentation

**Comment by mekya** [comment]
Lastly, community snapshots are deployed the sonatype automatically

https://oss.sonatype.org/#nexus-search;gav~io.antmedia~ant-media-server~~~~kw,versionexpand

**Comment by anuragtb** [comment]
@mekya , we are facing same issue on ams 2.2.1 EE, can let me know the file, we we have to sepcify "settings.heightRtmpForwarding=720"

**Comment by mekya** [comment]
It's app's properties file. 

For **LiveApp** -> /usr/local/antmedia/webapps/**LiveApp**/WEB-INF/red5-web.properties

**Comment by Vegas10128** [comment]
> It's app's properties file.
> 
> For **LiveApp** -> /usr/local/antmedia/webapps/**LiveApp**/WEB-INF/red5-web.properties

Tried that, does not work on newest community release.

**Comment by mekya** [comment]
Hi @Vegas10128 ,

I would like to answer and help you. But I'm not sure if you are going to complain about me and mad at me again :)
I'm just trying to do my best under high load and pressure. If you have any advice or help, it's highly appreciated.
I don't take any thing personal. No problem at all. 
 
Anyway, let me share my test result. 

1. I've downloaded the latest version. 
https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.3.0/ant-media-server-2.3.0-community-2.3.0-20210301_0825.zip
2. I've installed it to our test server. 
3. Add following property to

> settings.heightRtmpForwarding=720

/usr/local/antmedia/webapps/LiveApp/WEB-INF/red5-web.properties

4. Save the file and restart the service
> sudo service antmedia restart

5. Enable MP4 recording on the web panel 
6. Publish stream to https://domain:5443/LiveApp/
7. Stop publishing
8. Check the recording resolution with ffmpeg and it shows 720p for me. 
<img width="1163" alt="Screen Shot 2021-04-07 at 13 52 39" src="https://user-images.githubusercontent.com/3456251/113855296-8c5ae880-97a8-11eb-9cf1-ae16c7f9892e.png">


I'm sorry but I could not reproduce your report. If you mean something else, please let me know.

**Comment by bgatienRoss** [comment]
I'm still seeing videos come out at a max of 640x360.   

I have this version of AMS 
![image](https://user-images.githubusercontent.com/91631151/135330510-048ea0cd-e4a3-40d9-b069-7185fdd648cc.png)

1. I created a brand new App.
2. I added settings.heightRtmpForwarding=720  to the red5-web.properties file.
3. I restarted the AMS.
4. I changed the publish_with_timestamp.html so it has the following constraints:

![image](https://user-images.githubusercontent.com/91631151/135330981-95223692-8975-4892-bd18-fe458efdd605.png)

5. I enable recording.
6. After I stream and stop, I use ffmep so see the settings, and it says it's at  640x360  

![image](https://user-images.githubusercontent.com/91631151/135331156-4464a9aa-4a9e-4d61-bdba-42d77a685bb8.png)


I can't seem to get any stream to stream out at a higher quality than 640x360.    What am I doing wrong?

**Comment by mekya** [comment]
Hi @bgatienRoss ,

>I added settings.heightRtmpForwarding=720 to the red5-web.properties file.
Are you sure that you've changed the correct  `red5-web.properties` ?

Is it possible to just change the parameter and try in one of the default applications?

**Comment by bgatienRoss** [comment]
As far as I can tell, the default applications do not have that parameter.    

I added it in this file:
![image](https://user-images.githubusercontent.com/91631151/135459940-2a3ce29e-3089-45f3-a470-c5dfdadbed24.png)

The VanilaAppCreatedByAMS is a brand new App I created using the "New Application" button in the DashBoard app.

I'm going to this page in order to publish a stream:
![image](https://user-images.githubusercontent.com/91631151/135460240-b04377ec-1f05-43ae-895c-d08e358821b6.png)


The only thing I changed in that page's html is the media constraints.

I then go to the streams folder in the VanilaAppCreatedByAMS folder to see the recorded streams.

**Comment by mekya** [comment]
Hi @bgatienRoss ,

I think the problem is about `settings.hashControlPublishEnabled=true` . 
Is it possible to make all security stuff to false and try to stream?

I think there is a bug in Ant Media Server. It likely does not accept stream through WebRTC to RTMP when the settings.hashControlPublishEnabled=true
