### ISSUE TITLE
CORS error across ports

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1035]
# Issue

### Short description

Im trying to access localhost:5080/streams/test.m3u8 from localhost:3000/stream/test and im getting a cors error

### Environment

* Operating system and version: latest
* Java version: latest
* Ant Media Server version: latest
* Browser name and version: latest chrome

### Expected behavior

shouldn't be cors blocked across ports

### Actual behavior

get cors block across 2 ports on the same server

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Thank you for your interest. Could you please change Cors Filter in server-folder / webapps / root / web.xml as below ?

<filter>
		<filter-name>CorsFilter</filter-name>
		<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
		<init-param>
		  <param-name>cors.allowed.origins</param-name>
		  <param-value>http://localhost:3000</param-value>
		</init-param>
		<init-param>
		  <param-name>cors.support.credentials</param-name>
		  <param-value>true</param-value>
		</init-param>
	</filter>

I hope that I was able to answer your queries. If you have any question, please feel free to let us know.

**Comment by The-Code-Monkey** [comment]
I will try it tomorrow when I'm in work

**Comment by SelimEmre** [comment]
Ok. Please inform me, if you have any problem or question.
Good Luck!

**Comment by The-Code-Monkey** [comment]
its not throwing a cors error any more but it is throwing a 403 forbidden error @SelimEmre

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Did you logged in to Ant Media Server ? This may be related to unauthorized access issues.

Please inform me if you have any problem. Thanks.
