### ISSUE TITLE
Disable Flowplayer Share Settings

### ISSUE THREAD

**Issue by LiamKenyon** [ant-media/Ant-Media-Server#1037]
# Issue
Everything works great but it would be handy to disable settings/options within flowplyer. 

For example data-share etc... as it means people can auto take/embed your content.

I can’t see or find anywhere to amend/configure the play.html page.

**Comment by SelimEmre** [comment]
Hi @LiamKenyon,
Thank you for interest. You can disable share function with  `share : false; ` definiton in play.html like below image.

![asd123asdasd](https://user-images.githubusercontent.com/9084130/54479066-01f26580-482a-11e9-9f4c-17f2f3b51c71.JPG)


Good Luck!
Selim

**Comment by LiamKenyon** [comment]
Hi @selim 

I’ve got this installed on a Ubuntu server for testing, can you recommend the path I’d find the html pages or possibly consider adding these functions to be edited in future updates?

**Comment by SelimEmre** [comment]
Hi @LiamKenyon,
Thank you for your feedback. I will consider this notice. If you install normally you can find here play.html: /usr/local/antmedia/webapps/<USİNG-APP>/play.html.  Thanks.

**Comment by mekya** [comment]
We don't support flowplayer anymore. We use videojs. 

So that I'm closing this issue
