### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1061]
I still have this issue on the community version even when building  the project from the raw GitHub code how do I fix this

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,
Sorry for the delay, We have focused some other scalability features. Could you try please this release. We fixed and improved some feature. Also fixed your problem. 
https://oss.sonatype.org/service/local/repositories/releases/content/io/antmedia/ant-media-server/1.6.2/ant-media-server-1.6.2-community-1.6.2-20190323_0616.zip
Please inform me, If you have any problem. 
Selim.

**Comment by The-Code-Monkey** [comment]
I will test this tomorrow will this work if I try and compile the server myself from the GitHub code as I that is what I would prefer to do.

**Comment by The-Code-Monkey** [comment]
@selimemre see #1066

**Comment by The-Code-Monkey** [comment]
@SelimEmre So i got version 1.6.2 working but my issue now is that audio isn't working still

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Could you please test in test server below links.

https://test2.antmedia.io:5443/WebRTCAppEE/index.html?name=testAudioCheck
https://test2.antmedia.io:5443/WebRTCAppEE/play.html?name=testAudioCheck

Looking forwarding to hearing from you soon.

Best Regards,
Selim.

**Comment by The-Code-Monkey** [comment]
Hi @SelimEmre,

Sorry to keep bothering you guys with so many questions but im not getting any audio on that test server either my mic is working as i can see it within my sound settings, i can see its picking up audio do you have any idea what this could be as it is really strange.

**Comment by The-Code-Monkey** [comment]
hmm strange seems to be my mac everyone else at my work the audio works for which is very strange.

**Comment by The-Code-Monkey** [comment]
So i found the issue even though chrome had asked for permission to use my microphone in the security settings in my mac it wasn't ticked sorry for wasting your time i would have thought that would have been ticked.

**Comment by x011** [comment]
More than 1 year passed and the problem remains. No AUDIO.

**Comment by mekya** [comment]
Hi @x011 ,


Could you help me understand your problem? Because this issue is already closed by its author. Your problem should be something different.
