### ISSUE TITLE
Protocol missing from embedded link

### ISSUE THREAD

**Issue by hoos** [ant-media/Ant-Media-Server#1062]
# Issue
The embedded link src attribute is missing the protocol (https://). Ideally there should be an option to include this in the embedded link as a number of paywalls require it and it can be a pain to have to edit the embedded code for multiple videos.
### Short description
__Brief description of what happened__
When clicking the embedded link icon the link the is generated is in the format:

`<iframe width="560" height="315" src="//domain:/LiveApp/play.html?name=/dir/filename" frameborder="0" allowfullscreen></iframe>`

For a number of paywalls the link is broken in several ways mostly the lack of protocol, ideally there should be an option to add the protocol, full path and file extension to the embedded link i.e:

`<iframe width="560" height="315" src="https://domain:/LiveApp/play.html?name=/full path/filename.extension" frameborder="0" allowfullscreen></iframe>`

### Environment

* Operating system and version:
Linux version 4.15.0-1028-gcp (buildd@lgw01-amd64-036) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #29~16.04.1-Ubuntu SMP Tue Feb 12 16:31:10 UTC 2019
* Java version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
* Ant Media Server version:
1.6.1 Community Edition
* Browser name and version:
Chrome 
Version 73.0.3683.86 (Official Build) (64-bit)
### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
We don't use protocol to match the protocol of the location automatically.

Because if location is https and embed code is http, browsers throw exception.
