### ISSUE TITLE
Error with frame recorder

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1063]
# Issue

### Short description

io.antmedia.webrtc.adaptor.RTMPAdaptor - io.antmedia.recorder.FrameRecorder$Exception: No audio output stream (Is audioChannels > 0 and has start() been called?)

### Environment

* Operating system and version: latest macos
* Java version: latest
* Ant Media Server version: 1.6.2
* Browser name and version: chrome latest

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by The-Code-Monkey** [comment]
not an issue my bad

**Comment by NovalisKernel** [comment]
@The-Code-Monkey Could you please provide a solution of this issue?

**Comment by mekya** [comment]
Hi @NovalisKernel ,

We also have some improvements for this issue. You can use the latest community edition.
