### ISSUE TITLE
Stops after onIceCandidate

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1064]
# Issue

### Short description

So i started version 1.6.2 up and connected like i have been doing with version 1.6.1 and it gets to `onIceCandidate` then it waits for ages because `avformat_find_stream_info takes 101052ms`

then it says `[mp4 @ 0x7f9558007e00] dimensions not set` how do i fix this

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

We test the server with both test automations and manually. Now we've just tested it again for you. Everythings work as expected. There may be some networking issue on your side. If it's OK for you, let us your server information, and we can check your problem. You can send in contact@antmedia.io.

Best Regards,
Selim.

**Comment by The-Code-Monkey** [comment]
This is all local hosted so there shouldn't be any server issues

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

Which operating system do you use ? Which Browser do you use in WebRTC Publishing ? Are you using Virtual Machine ? Is browser access your audio&video device ? Could you please answer these questions ? We want to help you. But we need some details in your environment.

Best Regards,
Selim.

**Comment by The-Code-Monkey** [comment]
Oops sorry, macosx, chrome latest, no VM, audio and video allowed through Mac facetime webcam,

**Comment by The-Code-Monkey** [comment]
That is the same for all the issues I make

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,

One of our testing computers is macosx 10.14. Chrome version 73. Could there be a problem with device permissions ? If you want, we can check your problem with teamviewer ?

Best Regards,
Selim

**Comment by The-Code-Monkey** [comment]
I'll try today and if it still exists I'll see if you guys can team viewer in

**Comment by The-Code-Monkey** [comment]
seemed to be an issue with outdated webrtc_adapter.js i updated that in the project i was trying to connect to the server with and it fixed it
