### ISSUE TITLE
Apache-commons-daemon-jsvc does not support centos6.5

### ISSUE THREAD

**Issue by mrzxy** [ant-media/Ant-Media-Server#1079]
# Issue
Apache-commons-daemon-jsvc does not support centos6.5

#detail
![image](https://user-images.githubusercontent.com/11501927/54970589-abb9bb00-4fbd-11e9-84fc-e675631496e3.png)

**Comment by SelimEmre** [comment]
Hi @mrzxy,

Yes, we know Centos 6.5 doesn't support apache-commons-daemon-jsvc. We recommend that you upgrade to centos 7.

Best Regards,
Selim.

**Comment by mrzxy** [comment]
thanks @SelimEmre
