### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1080]
Hey guys,

Wanted to thank you for all your help debugging, I have one last question what would be the nginx config for this as I am deploying this on a forge server via bitbucket.

Thanks Andy

**Comment by jaggerestep** [comment]
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

You can use a reverse proxy to direct a web endpoint to the port that this runs on

**Comment by The-Code-Monkey** [comment]
And that will make it so that I can hit it from just the root URL without ports

**Comment by The-Code-Monkey** [comment]
I really struggle with nginx probably should learn it better

**Comment by The-Code-Monkey** [comment]
@jaggerestep I tried to add my reverse proxy but i get a 502 error my nginx is.

```
// this at the top of the nginx file

upstream websocket {
    server 127.0.0.1:5080/WebRTCApp/websocket/;
}

// this in the server block

location /ws-stream {
    proxy_pass https://websocket;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

**Comment by ApoRes1337** [comment]
Is there an accidental update regarding an example config for Nginx?

**Comment by mekya** [comment]
Closing this issue for the inactivity.
