### ISSUE TITLE
audio off

### ISSUE THREAD

**Issue by dksush** [ant-media/Ant-Media-Server#1085]
# Issue

when i receive video(webrtc sdk MODE_PLAY),
i want to audio off.
could i get some advice?

### Short description
__Brief description of what happened__

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Closing this issue for the inactivity. If you're still having the same problem, please reopen it.
