### ISSUE TITLE
Message content improvement on Live Demo

### ISSUE THREAD

**Issue by khanhonney** [ant-media/Ant-Media-Server#1086]
![live-demo-message1.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/a7979223-dcfe-40e3-9493-f4afe8902c50)![live-demo-message2.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/ca992546-9ede-40f5-bf26-b640fd27a04c)

**Comment by SelimEmre** [comment]
solved
