### ISSUE TITLE
REST API IP Whitelist

### ISSUE THREAD

**Issue by franzwarning** [ant-media/Ant-Media-Server#1095]
Hi,

In the documentation [here](https://github.com/ant-media/Ant-Media-Server/wiki/The-Steps-of-One-Time-Token-Operations) you specify "calling this rest service from remote is restricted due to the security reasons". 

Is there a way to whitelist IPs? So only my servers can hit it?

Thanks!

**Comment by mekya** [comment]
Yeah this feature is supported for the recent versions. You can enter white list ip address on the web management panel. 

I'm closing this issue. If it's still a problem, please reopen it.
