### ISSUE TITLE
2 channel (stereo) Audio

### ISSUE THREAD

**Issue by zsaraf** [ant-media/Ant-Media-Server#1097]
Hello,

I am trying to enable 2 channel (stereo) audio WebRTC streams using my AntMediaServer. The audio stream is currently stereo for the generated HLS stream, but is mono on the embeddable Ant Media WebRTC player. Any idea why this? And any ideas on how I can fix it?

Thanks
Zach

**Comment by zsaraf** [comment]
@mekya

**Comment by davidjmaxey** [comment]
I also have this same issue. Any chance you found a fix yet?

**Comment by mekya** [comment]
I've just checked that. We send stereo audio with WebRTC. On the other hand, mono stream is more compatible in WebRTC so that it's being converted to mono in playing.

We're working on WebRTC upgrade to m79. I think we can take a look at this issue again.

**Comment by davidjmaxey** [comment]
I must have stereo audio since I'm am often streaming live band music. Has this issue been resolved yet?

**Comment by alanstott** [comment]
I've noticed this issue for both HLS and WebRTC. At first, I thought it was a possible bitrate issue. This is really disappointing as there are so many positive points about AntMedia, as a music streaming business we can't use it in mono :(

**Comment by mekya** [comment]
Yeah I know. Generally we choose mono for the webrtc compatibility in different browsers at first. Fortunately, I think we can implement this feature.

Btw, this issues is for WebRTC not for HLS.

**Comment by lnogueir** [comment]
Why was this closed? Has this been fixed? I am facing the same issue.

**Comment by mekya** [comment]
Hi @lnogueir ,

Yeah we support stereo in WebRTC on the server side(v2.3.1). 

You should also enable channel count on the client side by specifying channelCount in the media constraints. 
```
	var mediaConstraints = {
		video : true,
		audio: {
                  channelCount: 2,
              },
	};
```

Btw, latest snapshot is always downloadable at user's subscription page and change log is published here
https://antmedia.io/latest-snapshot/

Lastly, we're going to release v2.3.2 in this week.

**Comment by lnogueir** [comment]
@mekya Thank you so much for your response.

I will have to update the version I'm using, currently on v2.1.0.

Will post here if I have any other issues.

Regards

**Comment by mekya** [comment]
Sure. Thank you.

**Comment by vasilis-dragonfruit** [comment]
Hey guys!
I was working on something related.
The case here is that 2 channel audio is being streamed.. but it seems these two channels are being mixed in server side by ffmpeg?
I would like to have these 2 channels intact as they sent. Is it possible?

**Comment by aybb** [comment]
It seems like it's not fixed yet. Audio quality with webrtc publishing is really poor

**Comment by mekya** [comment]
Hi @aybb ,

Yes you are right. Our approach to fix this issue has caused some audio/video synch issues and we just revert back the developments.  We'll revisit this issue with #3076
