### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by blcktqq** [ant-media/Ant-Media-Server#11]
Just searching for any documentation.
Where i can read it?

**Comment by mekya** [comment]
Ant Media Server is based on Red5.

Documentation is'nt sufficient just there is a simple Getting_Started.md
file on doc folder.

Please let me know the exact thing you want to learn so that I can write
and publish it on doc folder.

Regards,
A. Oguz

**Comment by mekya** [comment]
Closing this issue now. Please let me know if you need more documentation. I can provide them somehow sooner or later.
