### ISSUE TITLE
What version of Java is needed to run server

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1113]
I put it on a ubuntu server and i keep getting this error.

SystemUtils: java.lang.reflect.InaccessibleObjectException: Unable to make public double com.sun.management.internal.OperatingSystemImpl.getSystemCpuLoad() accessible: module jdk.management does not “opens com.sun.management.internal” to unnamed module @3c7cfcbb

how do i fix this??

**Comment by mekya** [comment]
Java-8 is needed. 

Sorry for late reply.
