### ISSUE TITLE
Missing link in community edition panel

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1120]
There is no link in below message.

![Screen Shot 2019-04-08 at 12.38.37.png](https://images.zenhubusercontent.com/5b0554504b5806bc2bd44cd0/a1ea790e-dc97-42e6-a6e0-7c066b7f396f)

In addition change the message like this
"Get Enterprise Edition to use Adaptive Streaming" 
link should be something that it adds the license to user card directly.

**Comment by SelimEmre** [comment]
![asdasd1aaasss.png](https://images.zenhubusercontent.com/5b06ddb64b5806bc2bd47c91/545b3dfb-6b22-4533-a1f3-ff01c3d6ac32)

**Comment by SelimEmre** [comment]
https://github.com/ant-media/ManagementConsole_AngularApp/pull/32
