### ISSUE TITLE
Websocket disconnects digital ocean

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1124]
# Issue

### Short description

the websocket will disconnect after a random amount of time on our digital ocean server.

### Environment

* Operating system and version: ubuntu 16.0.4
* Java version: 8
* Ant Media Server version: 1.6.2
* Browser name and version: chrome latest

### Expected behavior

the websocket shouldn't disconnect

### Actual behavior

websocket disconnects

### Steps to reproduce
1. blank digital ocean server
2. install ubuntu then install the repo using the install wiki page
3. open up ports

im guessing there is a setting like max connection time or something?

**Comment by mekya** [comment]
Please try with new version and re-open this issue if it still exists.
