### ISSUE TITLE
Control the "Disk Quota Exceed" state

### ISSUE THREAD

**Issue by hakanbali68** [ant-media/Ant-Media-Server#1153]
Setting in Conf: quota-warning-limit : 90
Setting in Conf: quota-error-limit : 95

Control the "Disk Quota Exceed" state on a minute basis according to the attached flow chart.

![disk-quota-exceed-control.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/0730b60e-3e2e-431f-a183-f6a38ace6539)

**Comment by SelimEmre** [comment]
![Untitled Diagram (1).png](https://images.zenhubusercontent.com/5b06ddb64b5806bc2bd47c91/97667a86-4281-4915-ab11-72a8df83409f)
