### ISSUE TITLE
streamId and all row attributes null in Management Console Angular App

### ISSUE THREAD

**Issue by shadabk92** [ant-media/Ant-Media-Server#1159]
# Issue

### Short description
All the row elements were working in 1.6.1 and now they are all null

### Environment

* Operating system and version: Ubuntu 18.04 localhost and GCP same OS
* Java version:  1.8
* Ant Media Server version: 1.6.2 community
* Browser name and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

### Expected behavior
all the details must get on console.log (outputs) atleast or run on the normally installed app, they are not working on directly installed applications also from LiveApp

### Actual behavior
The LiveApp is not showing streamId and streamName

### Steps to reproduce
1. Open App Livebroadcaster, start stream with any name
2. Name and streamid is always null on the LiveApp Grid
`[{"streamId":"null","status":"broadcasting","type":"liveStream","name":null,"description":null,"publish":true,"date":1555271404222,"plannedStartDate":null,"duration":null,"endPointList":null,"publicStream":true,"is360":false,"listenerHookURL":null,"category":null,"ipAddr":null,"username":null,"password":null,"quality":null,"speed":0.0,"streamUrl":null,"originAdress":null,"mp4Enabled":0,"expireDurationMS":0,"rtmpURL":"rtmp://127.0.1.1/LiveApp/null","zombi":true,"pendingPacketSize":0,"hlsViewerCount":0,"webRTCViewerCount":0,"rtmpViewerCount":0}]
`
### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by shadabk92** [comment]
My entire demo is stopped due to this

**Comment by shadabk92** [comment]
Is there a way to debug the Management Console without always building it over a million times and deploying and testing it always.

**Comment by shadabk92** [comment]
This is a genuine issue, please look into it.
The app livebroadcaster sdk doesn't work with the new versions of ManagementConsole Angular and 1.6.2 Community editions.

**Comment by SelimEmre** [comment]
> Is there a way to debug the Management Console without always building it over a million times and deploying and testing it always.

Hi @shadabk92,

You can work with your localhost:4200 port in Angular project. You don't have to Build every time and copy the server/root folder.  We are working in Angular side. AMS works in your localhost:4200

**Comment by SelimEmre** [comment]
> This is a genuine issue, please look into it.
> The app livebroadcaster sdk doesn't work with the new versions of ManagementConsole Angular and 1.6.2 Community editions.

Could you please check your RTMP URL is true. Could you validate that streamID is coming correctly?

Looking forwarding to hearing from you soon

May the Live Streaming be with you!

Selim.

**Comment by shadabk92** [comment]
> > This is a genuine issue, please look into it.
> > The app livebroadcaster sdk doesn't work with the new versions of ManagementConsole Angular and 1.6.2 Community editions.
> 
> Could you please check your RTMP URL is true. Could you validate that streamID is coming correctly?
> 
> Looking forwarding to hearing from you soon
> 
> May the Live Streaming be with you!
> 
> Selim.

It was working fine with 1.6.1 no changes have been done in the app, as soon as it was moved to 1.6.2 it stopped.

**Comment by shadabk92** [comment]
> > > This is a genuine issue, please look into it.
> > > The app livebroadcaster sdk doesn't work with the new versions of ManagementConsole Angular and 1.6.2 Community editions.
> > 
> > 
> > Could you please check your RTMP URL is true. Could you validate that streamID is coming correctly?
> > Looking forwarding to hearing from you soon
> > May the Live Streaming be with you!
> > Selim.
> 
> It was working fine with 1.6.1 no changes have been done in the app, as soon as it was moved to 1.6.2 it stopped.

It is running from LiveBroadcaster app as LiveApp on the ant-media-server

**Comment by shadabk92** [comment]
Is it a Androidx issue?

**Comment by shadabk92** [comment]
> Is it a Androidx issue?
> @SelimEmre

It was an AndroidX issue.
Now the applications are working fine

**Comment by SelimEmre** [comment]
I'm so glad the problem is solved.
