### ISSUE TITLE
Cannot read property 'getUserMedia' of undefined

### ISSUE THREAD

**Issue by yoloSwagSEO** [ant-media/Ant-Media-Server#1200]
hello i have js error on chrome 74
on url => http://vps676372.ovh.net:5080/WebRTCApp/

error => 
webrtc_adaptor.js:85
 Uncaught TypeError: Cannot read property 'getUserMedia' of undefined
    at new WebRTCAdaptor (webrtc_adaptor.js:85)
    at (index):202

**Comment by yoloSwagSEO** [comment]
Work on edge

**Comment by SelimEmre** [comment]
Hi @yoloSwagSEO,

Thank you for the feedback!

It's about Google Chrome and Security. Google Chrome force the SSL in WebSocket Connection. But Mozilla Firefox allows insecure WebSocket Connections. You can use in Mozilla Firefox in WebRTC Playing and Publishing. But Google Chrome using clients will get an error in the WebRTC playing side.

Ref: https://github.com/ant-media/Ant-Media-Server/wiki/How-to-fix-%E2%80%9CNotSupportedError%E2%80%9D-in-publishing-WebRTC-stream-in-Ant-Media-Server-%3F

**Comment by yoloSwagSEO** [comment]
Good!

**Comment by eujinn** [comment]
Is there any solution to solve this on Chrome?

**Comment by JerryHanZD** [comment]
Same problem here. Any solutions to this? Most users use chrome to access the website....

**Comment by mekya** [comment]
Absolutely there is a solution 
install SSL to your instance and access the server via https

https://antmedia.io/enable-ssl-on-ant-media-server/

**Comment by JerryHanZD** [comment]
> Absolutely there is a solution
> install SSL to your instance
> 
> https://antmedia.io/enable-ssl-on-ant-media-server/
> 
> After you install the ssl, then go to the same url via https(5443)
> 
> https://SERVER_FQDN:5443/WebRTCAppEE/

Hey man thx for replying, but do I have to use Ant Media to install the SSL to solve the problem?
I'm currently using a server I built myself and I think the problem should be that the api requires the https access and chrome just blocks any non-https access. I'm still a bit confused about how to solve this.

**Comment by borhanreo** [comment]
You need to use mozilla firefox browser. It's a permission issue for chrome

**Comment by biranchi2018** [comment]
> You need to use mozilla firefox browser. It's a permission issue for chrome

Tried, but not working either.

**Comment by JasonOldWoo** [comment]
> Hi @yoloSwagSEO,
> 
> Thank you for the feedback!
> 
> It's about Google Chrome and Security. Google Chrome force the SSL in WebSocket Connection. But Mozilla Firefox allows insecure WebSocket Connections. You can use in Mozilla Firefox in WebRTC Playing and Publishing. But Google Chrome using clients will get an error in the WebRTC playing side.
> 
> Ref: https://github.com/ant-media/Ant-Media-Server/wiki/How-to-fix-%E2%80%9CNotSupportedError%E2%80%9D-in-publishing-WebRTC-stream-in-Ant-Media-Server-%3F

thks, it helps me a lot.

**Comment by ziadasem** [comment]
this error is due to chrome and other browsers block microphone access to not https sites
so try to install SSL 
you can get your free one from here
https://www.sslforfree.com/
and follow the toutrial

**Comment by borhanreo** [comment]
> > You need to use mozilla firefox browser. It's a permission issue for chrome
> 
> Tried, but not working either.

@biranchi2018 You need to add ssl certificate with your server. if you use local server then you can create a certificate https://www.rosehosting.com/blog/how-to-generate-a-self-signed-ssl-certificate-on-linux/ then start your server

**Comment by prasenjit014** [comment]
I followed all the steps in https://codelabs.developers.google.com/codelabs/webrtc-web/  to learn and make a webRTC call
I want to access the server using my IP address instead of localhost.
I am getting the error   "Uncaught TypeError: Cannot read property 'getUserMedia' of undefined"
Should I add ssl certificate with my server. Can anyone help with a related link to get over this problem on Windows

**Comment by chemiu** [comment]
hello all what worked for me is using an app (I am not connected to them) called ngrok it creates a web link that redirects to your pc and it also has https

**Comment by dapsterai** [comment]
In addition to @chemiu 's suggestion, serverless.social is a similar service. Works nicely.

**Comment by mensenvau** [comment]
http://  -No undefined  ,  https://  -Yes

**Comment by socratesone** [comment]
> http:// -No undefined , https:// -Yes

I wish this was at the top of this thread.

**Comment by Santa116** [comment]
I am developing an app called VoiceTecApp, but the following error is displayed.
'''''''Uncaught TypeError: Cannot read property 'getUserMedia' of undefined'''''''''''
I set SSL as you suggested, but it doesn't work.
I would appreciate it if you could tell me a lot of experience whether there is an error in my operation or if there are other problems.
