### ISSUE TITLE
When attempting to stream with no audio

### ISSUE THREAD

**Issue by The-Code-Monkey** [ant-media/Ant-Media-Server#1201]
# Issue

### Short description

I want to stream with no audio but it seems to never make a .m3u8 file how is this.

also ping does not return a ping on the docs it says this. This is needed to be fixed as websocket will timeout after an amount of time.

### Environment

* Operating system and version: ubuntu 16.0.4
* Java version: latest
* Ant Media Server version: 1.6.0
* Browser name and version: chrome latest

### Expected behavior

should be a video only stream

### Actual behavior

No file is created

### Steps to reproduce
1. create stream with media constraints audio set to false.

**Comment by The-Code-Monkey** [comment]
@SelimEmre any news on the reason why the ping isn't working

**Comment by mekya** [comment]
Closing this issue for the inactivity.

Please re-open if it still exists.
