### ISSUE TITLE
TCP ice candidates for playback do not include a publicly accessible ip

### ISSUE THREAD

**Issue by vtsatskin** [ant-media/Ant-Media-Server#1249]
# Issue

### Short description
TCP ice candidates do not include publicly accessible IPs

### Environment

* Operating system and version: Ubuntu 5.4.0-6ubuntu1~16.04.10
* Java version: openjdk version "1.8.0_212"
* Ant Media Server version: Enterprise Edition 1.6.2 20190323_0908
* Browser name and version: Google Chrome Version 74.0.3729.131 

### Expected behavior
We are looking to use a TCP connection during WebRTC playback. We try to accomplish this by filtering out any UDP ice candidates. However, we are unable to establish a connection because TCP candidates do not include a publicly accessible ip. UDP candidates include these. 

### Actual behavior
UDP candidates include public IPs but TCP candidates do not. This causes us unable establish a connection over TCP.
<img width="962" alt="Screen Shot 2019-05-15 at 1 36 51 PM" src="https://user-images.githubusercontent.com/1301625/57797199-e7e4de80-7717-11e9-955e-9fba47ae8c56.png">

### Steps to reproduce
Our security groups on AWS:

#### Incoming
<img width="513" alt="Screen Shot 2019-05-15 at 1 39 21 PM" src="https://user-images.githubusercontent.com/1301625/57797805-48285000-7719-11e9-903c-4ab5820851f5.png">

#### Outgoing
<img width="512" alt="Screen Shot 2019-05-15 at 1 39 29 PM" src="https://user-images.githubusercontent.com/1301625/57797823-51192180-7719-11e9-9ab3-0ff15b4fc3b3.png">

**Comment by vtsatskin** [comment]
Might be related to #869

**Comment by mekya** [comment]
Added to backlog for 1.8.0

**Comment by ccantos** [comment]
Same problem with AWS.

**Comment by mekya** [comment]
May I learn the reason why you've closed this issue @vtsatskin ? It was our roadmap for 1.8.0.

**Comment by vtsatskin** [comment]
@mekya sorry! This was an accident due to a PR in a private repo referencing this issue somehow automatically closing this issue. It's still an issue.

**Comment by mekya** [comment]
Thank you @vtsatskin ,

I'll re-schedule it for 1.8.0 version

**Comment by CodeSteele** [comment]
![image](https://user-images.githubusercontent.com/31152835/80331929-69ddf280-8817-11ea-959f-a2fc1a8f64eb.png)

We're having the same problem -- TCP candidates are resolving to the IP address used by docker, don't know if there is a way to override this.

**Comment by CodeSteele** [comment]
Also: tried to use `settings.webrtc.tcpCandidateEnabled=false` to get around this, no go, does nothing, client is still trying to connect over TCP.

**Comment by XPOL555** [comment]
Having the same problem too with Enterprise

**Comment by mekya** [comment]
Let me help about that. 

Set the following properties in apps  properties( `webapps/WebRTCAppEE/WEB-INF/red5-web.properties`) file. 
`settings.replaceCandidateAddrWithServerAddr=true`

Set the server name in conf/red5.properties. Use public ip address for server.name 
`server.name=`

I hope it helps.
