### ISSUE TITLE
Cannot publish an audio-only WebRTC Stream

### ISSUE THREAD

**Issue by vtsatskin** [ant-media/Ant-Media-Server#1253]
# Issue

### Short description
Publishing an audio-only WebRTC stream does not work.

### Environment

* Operating system and version: Ubuntu 5.4.0-6ubuntu1~16.04.10
* Java version: openjdk version "1.8.0_212"
* Ant Media Server version: Enterprise Edition 1.6.2 20190323_0908
* Browser name and version: Google Chrome Version 74.0.3729.131

### Expected behavior
Publishing an audio-only stream creates a stream that can be played back by a WebRTC player.

### Actual behavior
The stream never starts and is not created in the management UI. An offer and answer are exchanged by the media server and publishing peer and ice candidates are exchanged. However, the "publish_started" notification is not sent by the server.

### Steps to reproduce
1. Use the WebRTCAdaptor library without a video stream:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Ant Media Outbound Publish</title>
  <script src="./adapter.js"></script>
  <script src="./webrtc_adapter.js"></script>
</head>
<body>
  <video id="localVideo" autoplay muted width="480" height="720"></video>
  <script>
  var pc_config = null;

  var sdpConstraints = {
    OfferToReceiveAudio: true,
    OfferToReceiveVideo: true

  };
  var mediaConstraints = {
    video: false, // setting this to true works properly
    audio: true
  };

  var webRTCAdaptor = new WebRTCAdaptor({
    websocket_url: "WEBSOCKET_URL_HERE",
    mediaConstraints: mediaConstraints,
    peerconnection_config: pc_config,
    sdp_constraints: sdpConstraints,
    localVideoId: "localVideo",
    callback: function (info) {
      if (info == "initialized") {
        console.log("initialized");
        webRTCAdaptor.publish("audio-only-stream");
      }
      else if (info == "publish_started") {
        //stream is being published
        console.log("publish started");
        signalToSeleniumConnected();
      }
      else if (info == "publish_finished") {
        //stream is finished
        console.log("publish finished");
      }
      else if (info == "screen_share_extension_available") {
        //screen share extension is avaiable
        console.log("screen share extension available");
      }
      else if (info == "screen_share_stopped") {
        //"Stop Sharing" is clicked in chrome screen share dialog
        console.log("screen share stopped");
      }

    },
    callbackError: function (error) {
      //some of the possible errors, NotFoundError, SecurityError,PermissionDeniedError

      console.log("error callback: " + error);
      alert(error);
    }
  });
  </script>
</body>
</html>
```

2. Observe that the media stream does not start

**Comment by mekya** [comment]
Hi @vtsatskin ,

Have you tried to publish WebRTCAppEE/audio_publish.html to publish
and WebRTCAppEE/audio_player.html to play

I've just checked and it's working for me. 

Regards,

**Comment by vtsatskin** [comment]
@mekya thanks for the response. Using the audio publisher and player worked.

I didn't realize there were separate examples for audio publishing and playback. You might want to document that somewhere.

We use internally libraries and components for audio/video publishing and playback. We've been following the [WebRTC signalling documentation](http://docs.antmedia.io/en/latest/WebRTC-Developers.html#webrtc-websocket-messaging-details). One detail that was missing was that the publish command takes optional `video` and `audio` parameters which are required to be set when using audio playback.

So for anyone who runs into this issue, we got it working by explicitly specifying the audio and video parameters:

```
{
    command : "publish",
    streamId : "stream1",
    audio: true,
    video: false
}
```

@mekya please consider updating the documentation for the developers guide to include information about audio streams
