### ISSUE TITLE
Fix the errors dependency-check-maven produces

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1254]
When creating a release,

"dependency-check-maven" module reports several vulnerabilities like in tomcat or some other libraries.

List all the vulnerabilities and write a possible solution to resolve it like upgrading or something else. 
If there is no resolution method, just write there is no known resolution founded.

**Comment by maydin** [comment]
Created a PR to update dependency versions. Document for vulnerability analysis:
https://docs.google.com/spreadsheets/d/1nJIXaVKs_UuNI30vtncF2wyJ7lTQxQo6NoGZCavbJXY/edit?usp=sharing
