### ISSUE TITLE
webrtc audio stream disconnects after few minutes or less in background (screen off)

### ISSUE THREAD

**Issue by ikakey** [ant-media/Ant-Media-Server#1269]
Steps to reproduce the problem:
1. establish webrtc audio (or video) call
2. turn off screen
3. wait few minutes

What is the expected behavior?
webrtc audio stream will continue in background

What went wrong?
audio stream stopped after minutes or seconds, sometimes can be renewed by unlocking the phone

Did this work before? N/A 

Chrome version: 73.0.3683.90  Channel: stable
OS Version: 8.1.0
Flash Version: 

Bug present most phones with android version above 6

https://bugs.chromium.org/p/chromium/issues/detail?id=951418#c33

**Comment by a-di-ez** [comment]
I have the same problem!

**Comment by mekya** [comment]
Sorry for late reply. 

We've released several versions since that date. Can you check if this problem still exists?

If exists, please re-open this issue.

**Comment by ikakey** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1196422

**Comment by mekya** [comment]
Thank you for letting us know.  Is there anything you expect from our side? @ikakey
