### ISSUE TITLE
Stream Sources Deleting

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#1272]
# Issue
When we restart the server, Stream Sources are deleting.

### Environment

* Operating system and version: Ubuntu 16.04 LTS
* Java version: 1.8
* Ant Media Server version: EE 1.7.0
* Browser name and version: Chrome

**Comment by gruntz12** [comment]
Same problem here... 
Any ideas how to resolve it?

**Comment by mekya** [comment]
This issue has been fixed. Right now releasing the 1.7.1 version
