### ISSUE TITLE
WebRTC Very Wrong

### ISSUE THREAD

**Issue by gtk2k** [ant-media/Ant-Media-Server#1277]
version: Enterprise Edition 1.6.2 20190323_0908

Capture Video
[2019-05-24 10-19-14.zip](https://github.com/ant-media/Ant-Media-Server/files/3214663/2019-05-24.10-19-14.zip)

**Comment by mekya** [comment]
This issue generally happens when video bitrate is high and network bandwidth is not good enough. 
So that packet loss happens. 

Decrease fps and video bitrate may provide a solution. 

Closing this issue for now. Please re-open if it still exists for you.
