### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by hakanbali68** [ant-media/Ant-Media-Server#128]
3-4 saattir çalışmakta olan 4 GB RAM'e sahip sunucuda alınmaya başlanan hata.

![image.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/a619519c-eb45-4a9d-a73b-320950ddc6cc)![ant-media-index-out-of-bounds-error.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/db5b94ed-ee38-48f5-a28e-e9db907a6f06)

**Comment by davutcavdar** [comment]
As seen in the screenshot, instance indicates that computer has only 0 bytes left.

Also, memory usage is more than the required amount.

Because of these, memory and index out of bounds exceptions are thrown.

Tracing this issue.
