### ISSUE TITLE
Run multiple service on server

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#1295]
# Issue

### Short description
I want to run multiple service separated on difference ports.
How to do that?
### Environment
* Ant Media Server version: 1.7.1 EE

**Comment by mekya** [comment]
You may use docker for having isolated separated services.

**Comment by ntnahn** [comment]
Thank you, but have any decrease of performance when use docker instead of use native service?

**Comment by mekya** [comment]
this is the containerization cost. On the other hand, isolation of services let you manage resources(CPU, RAM) for services which may give you better QoS

**Comment by ntnahn** [comment]
Thank for your answer

**Comment by mekya** [comment]
You're welcome. Its my pleasure and closing this issue. Please let me know if you have any further questions
