### ISSUE TITLE
Where is the Doc? Guide?

### ISSUE THREAD

**Issue by haomengjie** [ant-media/Ant-Media-Server#13]
# Issue

### Short description
Where is the Doc? Guide? 

### Environment

[] Operating system and version: Windows 10 1703
[] Java version: jdk180_44
[] Red5 version: 1.0.1

**Comment by mekya** [comment]
Hi @haomengjie ,

There is a simple [Getting_Started](https://github.com/ant-media/Ant-Media-Server/blob/master/doc/Getting_Started.md) guide in doc folder of the repo

Secondly, there are blog posts about using Ant Media Server on http://antmedia.io/blog

To be honest, there is not much documentation yet. Fortunately, we can prepare quickly If you need something specific.

**Comment by mekya** [comment]
Closing this issue. Please let me know if you have something to say or feel free to open this issue.
