### ISSUE TITLE
Errors on stream parameters check

### ISSUE THREAD

**Issue by hakanbali68** [ant-media/Ant-Media-Server#130]
"Stream Source" için verilen "Stream URL" parametresindeki kontrollerde karşılaşılan hatalar
- Yeni kayıt girişinde ve güncellemede url olarak Mrtsp ve Zhttp verilse dahi doğru kabul ediliyor.
- "Stream Name" için 4 karakter boşluk girildiğinde kabul ediyor
- port kısmına 50115001 girildiğinde kabul ediyor
- Yeni girişte IP kısmında >255 girildiğinde hata veriyor ama güncelleme yaparken hata vermiyor
- @ işareti yerine başka bir karakter girince de URL kabul ediliyor
- Port için iki tane :: yazılınca da kabul ediliyor.
- REGEX benzeri bir mekanizma ile TRUE PATTERN tanımlanabilir mi?

**Comment by davutcavdar** [comment]
a) streamUrl is checked as not only contains but also startswih url identifiers (rtsp, http etc)
b) empty check of stream name is performed for not only stream source but also for all operations (first create and edit)
c) IP regex check also for update

**Comment by mekya** [comment]
What about on server side? If I send a wrong format url to server programmatically via rest service, will it return true or false?

**Comment by davutcavdar** [comment]
Now server side also creates a false response to invalid URL.
