### ISSUE TITLE
Add switch camera method to iOS WebRTC framework

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1304]
Camera switch functionality during Calls for IOS SDK#2119

**Comment by ElKnarzo** [comment]
Hello,

has anyone found a solution for this?

For a project that uses the AntmediaSDK, the camera is needed on the back for streaming. We want to use the SDK for a baby camera for smartphones. For this, the rear camera is better suited than the front camera.

**Comment by mekya** [comment]
Hi @ElKnarzo ,

Right now, you can choose the which camera to open at first and camera switch's not implemented yet. If you're an enterprise user, then we can share the latest iOS SDK with you 

Regards,
A. Oguz
