### ISSUE TITLE
Publishing stops after 10 secs

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1318]
# Issue

### Short description
On Firefox, Publishing stops after 10 seconds or so.  Implemented the ports suggestion.  It does not work.

### Environment
Local only on my LAN.

* Operating system and version: Ubuntu 16.04.4 on Vbox VM 

* Java version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

* Ant Media Server version: ant-media-server-community-1.7.2-20190602_1447.zip

* Browser name and version: Firefox 67.0.2

ray@AntMediaServer:~$ sudo ufw status
[sudo] password for ray:
Status: active
To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
1935/tcp                   ALLOW       Anywhere
5080/tcp                   ALLOW       Anywhere
5443/tcp                   ALLOW       Anywhere
5554/tcp                   ALLOW       Anywhere
3000:65535/udp             ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
1935/tcp (v6)              ALLOW       Anywhere (v6)
5080/tcp (v6)              ALLOW       Anywhere (v6)
5443/tcp (v6)              ALLOW       Anywhere (v6)
5554/tcp (v6)              ALLOW       Anywhere (v6)
3000:65535/udp (v6)        ALLOW       Anywhere (v6)

### Expected behavior
Publishing should remain active throughout the broadcast.

### Actual behavior
.ts and .m3u8 are located in the streams/ directory, but after 10 seconds or so, Publisher goes inactive and .ts and .m3u8 files are deleted.

FF Console:  **ICE failed, add a STUN server and see about:webrtc for more details**

### Steps to reproduce
1. Browse to 192.168.0.51:5080/WebRTCApp/
2. Click the "Start Publishing" button
3. "Start Publishing button is greyed out
4. Publishing indicator green pops in
5. streams/  directory is populated with .ts and .m3u8
6. After 10 secs or so, the Start Publishing button is available again.
7. .ts and .m3u8 are deleted

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

received ice candidate for stream id stream1 webrtc_adaptor.js:636:14
Candidate is added for stream stream1 webrtc_adaptor.js:566:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:0 1 UDP 2122187007 192.168.0.5 65135 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:1 1 UDP 2122252543 192.168.56.1 65136 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:2 1 UDP 2122121471 192.168.92.1 65137 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:3 1 TCP 2105458943 192.168.0.5 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:4 1 TCP 2105524479 192.168.56.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:5 1 TCP 2105393407 192.168.92.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:0 2 UDP 2122187006 192.168.0.5 65138 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:1 2 UDP 2122252542 192.168.56.1 65139 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:2 2 UDP 2122121470 192.168.92.1 65140 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:3 2 TCP 2105458942 192.168.0.5 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:4 2 TCP 2105524478 192.168.56.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
sending ice candiate for stream Id stream1 webrtc_adaptor.js:376:13
{"candidate":"candidate:5 2 TCP 2105393406 192.168.92.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":null} webrtc_adaptor.js:377:13
received ice candidate for stream id stream1 webrtc_adaptor.js:636:14
Candidate is added for stream stream1 webrtc_adaptor.js:566:13
received ice candidate for stream id stream1 webrtc_adaptor.js:636:14
Candidate is added for stream stream1 webrtc_adaptor.js:566:13
received ice candidate for stream id stream1 webrtc_adaptor.js:636:14
Candidate is added for stream stream1

ICE failed, add a STUN server and see about:webrtc for more details
publish finished

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi @rayj00 ,

This issue actually seems a kind of firewall issue. 

I've just tested again 1.7.2 community on firefox and it works for me. 

I think some network settings should be tuned for Vbox VM.

Regards,

**Comment by rayj00** [comment]
> 
> 
> Hi @rayj00 ,
> 
> This issue actually seems a kind of firewall issue.
> 
> I've just tested again 1.7.2 community on firefox and it works for me.
> 
> I think some network settings should be tuned for Vbox VM.
> 
> Regards,

My UFW settings are included above.  Any idea what I need to do for a VM?

**Comment by mekya** [comment]
I think it may have some issues in bridge between VM and host.
Just a question, do you open the firefox on ubuntu machine which has the community edition running?

Regards

**Comment by rayj00** [comment]
> 
> 
> I think it may have some issues in bridge between VM and host.
> Just a question, do you open the firefox on ubuntu machine which has the community edition running?
> 
> Regards
No.  I am running Ubuntu Server on a VM.

**Comment by rayj00** [comment]
I use FF on my local Windows 7 machine.

**Comment by mekya** [comment]
Could you please try FF on ubuntu(VM)?

**Comment by rayj00** [comment]
> 
> 
> Could you please try FF on ubuntu(VM)?

Do you mean from a different VM?   I only have the Ubuntu Server rightup right now.   I would have to spin up a Ubuntu desktop.  But what would that prove?

**Comment by rayj00** [comment]
I installed a new VM with Ubuntu Desktop.  It prompts to allow the camera and mic,  I allow it but I do not get any video or audio?  Also I don't see anything in the Dev console?

**Comment by mekya** [comment]
I mean in the same VM. 

Alternatively, you can install Ant Media Server to a real machine and test it.

**Comment by mekya** [comment]
Closing this issue for the inactivity.
