### ISSUE TITLE
Can't login to console!

### ISSUE THREAD

**Issue by sjauld** [ant-media/Ant-Media-Server#1336]
# Issue

### Short description
__Brief description of what happened__

I have an Ant Media Server cluster with a MongoDB backend that was working nicely on v1.6.1. After upgrading to v1.7.2, I can't log in anymore (403 error).

### Environment

* Operating system and version: AMS Enterprise v1.7.2 AMI
* Java version: AMS Enterprise v1.7.2 AMI
* Ant Media Server version: AMS Enterprise v1.7.2 AMI
* Browser name and version: AMS Enterprise v1.7.2 AMI

### Expected behavior
__Put as much detail here as possible__
I can log in

### Actual behavior
__Put as much detail here as possible__
I can't log in

### Steps to reproduce
1. Deploy a working cluster using AMS v1.6.1 with a MongoDB backend
2. Set an admin password
3. Upgrade the cluster to v1.7.2
4. Try to log in

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Are you sure you set the correct parameters for MongoDB access while
running change_server_mode.sh?

Regards,
A. Oguz

**Comment by sjauld** [comment]
Hi @mekya,

Yes, we haven't changed this, we're running all of the same userdata, just on the new AMI.

Cheers,
Stuart

**Comment by mekya** [comment]
Is it possible to send me log file of the server you're trying to login?

I can check what's wrong with it.

Thank you

**Comment by sjauld** [comment]
I'll sent them via email now!

**Comment by mekya** [comment]
Thank you. I'm just letting the same answer be here as well.


It seems that this issue is about Chrome caching or something. There is no
special error for this in logs.
Could you please try to login with firefox?

If you could succeed to login with firefox, I'll create an issue about
what's wrong with Chrome.

Thank you
Regards,
A. Oguz

**Comment by sjauld** [comment]
Hi Oguz,

I have tried in Safari and also in Chrome (private mode) but still getting
403 errors - I don't think it's a caching issue.

Cheers,
Stuart

**Comment by mekya** [comment]
Can you provide me to access your server temporarily and check what's going
on?
ssh and web panel credentials.

Regards,
A. Oguz

**Comment by mekya** [comment]
This issues for CORS related and it's fixed in 1.8.0

In order to make it work for https in 1.7.2, you should open the file /usr/local/antmedia/webapps/root/WEB-INF/web.xml
and replace the lines below
<filter>
        <filter-name>CorsFilter</filter-name>
        <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
        <init-param>
          <param-name>cors.allowed.origins</param-name>
          <param-value>http://localhost:4200</param-value>
        </init-param>
        <init-param>
          <param-name>cors.support.credentials</param-name>
          <param-value>true</param-value>
        </init-param>
    </filter>

with these ones
<filter>
        <filter-name>CorsFilter</filter-name>
        <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
        <init-param>
          <param-name>cors.allowed.origins</param-name>
          <param-value>*</param-value>
        </init-param>
    </filter>

restart the servers
