### ISSUE TITLE
Create conference room security based on room tokens

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1337]
- [ ] When a user have publish token for room, s/he can publish stream to the room. 
- [ ] When a user have play token for room, s/he can play any stream in that room. There should be no separate token for playing each streams.

**Comment by MaZZly** [comment]
Is there some documentation on how to achieve this? (i.e. how to create a token for a room?)

**Comment by mekya** [comment]
I've added to the documentation issue for this release. If you are a enterprise user and need some personalized support, please reach out to support@antmedia.io for your standart support.
