### ISSUE TITLE
License Expired even though subscription auto renewed

### ISSUE THREAD

**Issue by vinceaar0n** [ant-media/Ant-Media-Server#1379]
# Issue

### Short description
i noticed i was getting invalid license error on my ant media panel. so i  logged in to ant media site to check my account. upon checking my account it says that my license has been expired since july 2 even though it was auto renewed

### Expected behavior
automatic renewal of license
download available

### Actual behavior
license subscription not renewing
download not available

**Comment by davutcavdar** [comment]
@vinceaar0n please send an email to contact@antmedia.io or david@antmedia.io including the email address used in the purchasing.
