### ISSUE TITLE
Can Anyone Confirm Using AJAX?

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1384]
# Issue

I am running antmedia using ssl and port 5443. It works fine.

Now I want to be able to have an AJAX session.
Can anyone advise me on how to execute an AJAX call from the antmedia index.html?

What do I need to configure in the server as far as the apache-tomcat server goes?

Thanks,

Ray

**Comment by burak-58** [comment]
Hi Ray,
Did you solve it? Is this entry yours?
https://groups.google.com/forum/#!topic/ant-media-server/uTwWynRK4o8

**Comment by mekya** [comment]
No need to do any specific things. You can consume REST API with Ajax. 

https://antmedia.io/rest

Closing this issue and please re-open if you have any issue.
