### ISSUE TITLE
how to handle reconnectivity issue

### ISSUE THREAD

**Issue by syedMSohaib** [ant-media/Ant-Media-Server#1389]
# how to handle reconnectivity issue

### Short description
How to handle the situation when the stream disconnects and should reconnect. Basically, what I want to do is wait 20 seconds after the initial disconnect, if the stream reconnects then it will resume as it is else it will stop and prompt user to create a new one.

So basically i need pause or resume functionality

**Comment by qasim483** [comment]
you can keep listening to notifications. So when you receive response like : {"streamId":"test123","definition":"play_finished","command":"notification"} 
you can call some function and try to reconnect again.

**Comment by syedMSohaib** [comment]
Yeah i was actually searching about that functions but can't find so, would you help me a bit
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Publish-&-Play-JavaScript-SDK
can this link help me in my case ?

**Comment by qasim483** [comment]
yes, so you can do something like:

**Comment by syedMSohaib** [comment]
Nice @qasim483  thanks buddy

**Comment by burak-58** [comment]
thanks @qasim483
