### ISSUE TITLE
WebRTC 1 to Many?

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#14]
# Issue 
Sending WebRTC to RTMP?

### Short description
I already have a WebRTC  "1 to Many" server that works, but of course bandwidth is an issue.
Can AMS be used to send my "1 to many" video to RTMP?

I am involved with an effort for a distributed streaming video platform that would accept RTMP.

**Comment by mekya** [comment]
Hi @rayj00 ,

Yeah sure Ant Media Server can be used to send "1 to Many" video. In the next release, we are really reducing the latency in switching rtmp to webrtc, webrtc to rtmp conversions. 

I can help you in doing this project. 

Regards,
A. Oguz

**Comment by mekya** [comment]
Closing this issue
