### ISSUE TITLE
Custom access filtering

### ISSUE THREAD

**Issue by Keyreach** [ant-media/Ant-Media-Server#1417]
Is there any way to develop custom or extend existing access control logic for stream playback/publish on my own? There are some related interfaces, but it's not clear enough from code how it can be done.
Just using EE doesn't suit, as its options don't fit all my cases and also have to be extended.

**Comment by burak-58** [comment]
Hi @Keyreach 
We have token control in enterprise edition. If you want to develop your own, you can implement ITokenService and replace it with MockITokenService.

**Comment by mekya** [comment]
Closing this issue for the inactivity.
