### ISSUE TITLE
Video from HLS stream inconsistent with published video length

### ISSUE THREAD

**Issue by vtsatskin** [ant-media/Ant-Media-Server#1419]
# Issue

### Short description
When publishing a stream through WebRTC, the HLS stream length is inconsistent with the actual published video length. This is especially apparent with videos longer than 10 minutes. This difference increases with video length leading to long videos having long inconsistencies. For example a stream of length 13:42 will have an HLS stream length of 13:10.

After thorough investigation, we've determined that there are segments missing in the `.m3u8` manifest. When multiplying the number of segments in the playlist file by the time length of the segments this length of time does not correspond with actual length of the recording. When looking at the length of the generated mp4 file, the length is correct.

This bug is major blocker for us because in our product we use the length of the HLS stream for VOD. This also affects HLS players like [hls.js](https://github.com/video-dev/hls.js/) which calculate the length of a stream based on the information in the manifest. Note that Safari and VLC will eventually correct the length of the HLS stream. I'm not entirely sure why this is. One hypothesis is that they download all the segments and concatenate the times by looking at the video segments lengths. This could indicate that the segment lengths being saved by Ant Media Server are longer than advertised by the manifest file. (e.g. 2.01s rather than 2.0s).

The following image demonstrates the adverse affects of this issue. We have an HLS stream in our internal video player where the time in the video does not line up with the time reported by the player.

<img width="478" alt="Screen Shot 2019-08-02 at 4 28 34 PM" src="https://user-images.githubusercontent.com/1301625/62398183-fb009100-b545-11e9-83c7-d5b296f9b061.png">

### Environment

* Operating system and version: Linux version 4.4.0-1084-aws (buildd@lcy01-amd64-009) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #94-Ubuntu SMP Fri May 17 13:10:20 UTC 2019
* Java version:  OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
* Ant Media Server version: Enterprise Edition 1.7.2 20190602_1617
* Browser name and version: Google Chrome 75.0.3770.100

### Expected behavior
In an HLS manifest file for a stream the number of segments multiplied by their length is equal to the total elapsed time of the stream.

### Actual behavior
The HLS manifest does not have enough segments to equal the length of the elapsed time of the stream.

### Steps to reproduce
The following configuration is required:

```
settings.hlsListSize=0
settings.hlsTime=2
settings.mp4MuxingEnabled=true
settings.deleteHLSFilesOnEnded=false
```

1. Publish a WebRTC Stream
2. Keep publishing for ~15 minutes
3. End the stream
4. Download the mp4 for the stream
5. Open the manifest in an HLS player. [This chrome extension](https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof) is pretty good.
6. Compare the video time lengths

### Logs

https://gist.github.com/vtsatskin/e86fe2f9ca7d5fc1aef2ca57f578b83f

**Comment by burak-58** [comment]
@Vtsatskin Thank you for your feedback. I'll try and give an explanation as soon as possible.

**Comment by vtsatskin** [comment]
@burak-58 thanks for taking the time to look into this. Please let me know what you find.

**Comment by vtsatskin** [comment]
@burak-58 @mekya is there any update on this?

**Comment by burak-58** [comment]
@vtsatskin it was planned for our weekly sprint and I am working on it.

**Comment by burak-58** [comment]
@vtsatskin I have checked the length of HLS segments and they are longer than the value set with settings.hlsTime. This is because a segment file (.ts) is ended with the first key frame after the settings.hlsTime.

Therefore your calculation (file size x hlsTime) is different from the correct length of the stream.

**Comment by vtsatskin** [comment]
@burak-58 thanks for taking the time to look into this. I'm under the impression that having the actual segment length be longer than the length indicated by `EXTINF` is an error. Are we in agreement of this?

If so, do you have an expected timeline for a fix?
