### ISSUE TITLE
Is it possible to add program date time to the stream?

### ISSUE THREAD

**Issue by mehmetalpsumer** [ant-media/Ant-Media-Server#1433]
Hello,
I am wondering if it is possible to extract programDateTime from an Antmedia stream?

**Comment by burak-58** [comment]
Hello @mehmetalpsumer, 
Could you please ask your question at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server)?
