### ISSUE TITLE
Server crash at 00h/00h15

### ISSUE THREAD

**Issue by yoloSwagSEO** [ant-media/Ant-Media-Server#1434]
# Issue

### Short description
The server crash 
Hello
Very often at the same time (00h\00h15) the server ant edition company has problems and "spits".

Ongoing streams are cut and cannot be restarted (stream in use)
I have to go to the ant back office to remove the streams by hand so that people can start streaming again

### Environment

* Operating system and version: Ubuntu 16.04
* Java version: Openjdk 1.8.0
* Ant Media Server version: 1.7.2

### Logs
https://pastebin.com/Db5EgSSu

**Comment by yoloSwagSEO** [comment]
New crash new log
https://pastebin.com/uB7vD6em

**Comment by mekya** [comment]
Please re-open this issue if you still get this problem in latest version
