### ISSUE TITLE
Rtmps url is not working. 

### ISSUE THREAD

**Issue by Yesha052** [ant-media/Ant-Media-Server#1436]
# Issue

I am not able to play **rtmps** URL with this. Please let me know how can I play this URL using this library.

**Comment by burak-58** [comment]
@Yesha052 can you share the URL which is not working? Let me check.

**Comment by Yesha052** [comment]
@burak-58 
"rtmps://live-api-a.facebook.com:80/rtmp/143521800?ds=1&a=PEtMa1Ul0W3Rpa"

**Comment by burak-58** [comment]
@Yesha052,
Could you please write a step by step scenario to reproduce the issue.

**Comment by mekya** [comment]
Closing this issue for the inactivity
