### ISSUE TITLE
Custom endpoint s3

### ISSUE THREAD

**Issue by Laityned** [ant-media/Ant-Media-Server#1437]
Is there a possibility to use custom endpoints using amazon api integrated in Antmedia?

**Comment by burak-58** [comment]
Dear @Laityned,
We are intended to discuss bugs and feature requests in github and others in our community channels. We will be glad if you share your question at  [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).

**Comment by Laityned** [comment]
Right now it is not implemented in antmedia, so I would like to make it as feature request

**Comment by burak-58** [comment]
Hi @Laityned ,
Please give us some details about this feature request. We already have some S3 support but don't know whether it meets your needs. Please tell more about custom endpoint s3. What do you mean with it?

**Comment by Laityned** [comment]
You are not able to connect to third party s3 protocol based storages like minio s3 storage due to the lack of changing the endpoint url of the s3 storage. Storages like minio are compatible with the AWS library used in your software. 

I made a merge request but it failed the test in the other git.

**Comment by burak-58** [comment]
Hi @Laityned,
We will check and merger your PR soon. Thanks for your contribution.
