### ISSUE TITLE
Does it possible to choose WebRTC stream encoding whatever for EE or Community version of AntMedia?

### ISSUE THREAD

**Issue by loversandcode** [ant-media/Ant-Media-Server#1442]
Hello, I'm implementing one of my project using Ant Media Javascript SDK. Can you please tell me, can force using, for example H264 encoding for client publish if it's available? Whatever if it's in EE or Community version of the Ant Media Server

How does SDK choose, what codec to use in current WebRTC publish on client?

How can i check which codec are using in my current WebRTC published stream?

**Comment by burak-58** [comment]
Dear @loversandcode,
We are intended to discuss bugs and feature requests in github and others in our community channels. We will be glad if you share your question at  [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).

**Comment by loversandcode** [comment]
Ok, no problem
