### ISSUE TITLE
The support is no longer responding?

### ISSUE THREAD

**Issue by yoloSwagSEO** [ant-media/Ant-Media-Server#1448]
I have made support requests for the paid version of your products 4 times and I have no answer.
Is there anyone on board?

**Comment by davutcavdar** [comment]
Hi @yoloSwagSEO , generally support requests are responded in 24 hours. Could you please indicate the nail address that you have used in the support requests so that I control it?

**Comment by yoloSwagSEO** [comment]
erosdevfr@gmail.com
For the customer claudine.tricoire@hotmail.fr

**Comment by yoloSwagSEO** [comment]
I'm putting the problem back here in case


Hi, I'm your claudine tricoitre client's technician.
We wanted to use your solution, but today we are facing several problems.

We started by taking a self hosted license on a very solid ovh machine. All this goes well but more and more often type errors 
"Aug 16, 2019 11:09:09:50 PM org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer doClose
INFO: Failed to close the ServletOutputStream connection cleanly
java.io.IOE Exception: Broken pipe"

which results in cutting all webrtc streams in court, but prevents the broadcaster from resuming broadcasting, the stream being always present on the server backoffice, the brodcaster are confronted with a streamIdEarlyInUse error.

And can't reconnect again until I delete all the streams by hand.

We therefore took in addition to verify any configuration problems on our server, an instance hosted by you.
It's a little more stable but the error is still there.

Did you have any idea? I've already called you several times it's becoming urgent.

Sincerely

**Comment by davutcavdar** [comment]
Thanks for the information. You have sent 2 support requests including the above case approximately **1 hour** ago. Your request will be evaluated and replied today. Thanks again. Closing this, please send email to contact [at] antmedia [dot] io, if you have new issues.
