### ISSUE TITLE
Enable_ssl.sh bug

### ISSUE THREAD

**Issue by Clickbaitcake** [ant-media/Ant-Media-Server#1461]
**Describe the bug**
When using `sudo ./enable_ssl.sh -f {FULL_CHAIN_FILE} -p {PRIVATE_KEY_FILE} -d {DOMAIN_NAME}` from [here](http://docs.antmedia.io/en/latest/FAQ.html?highlight=ssl#id3) to import custom SSL certificates the script errors out because it looks for the certificates in the LetsEncrypt directory which we are not using because we are providing our own certificate.
Therefore the admin then has to manually create the certs in the LetsEncrypt location. 
```

user@stream:/usr/local/antmedia$ sudo ./enable_ssl.sh -f cert.pem -p server.key -d example.com
domain: example.com
creating new certificate

Can't open /etc/letsencrypt/live/example.com/privkey.pem for reading, No such file or directory
140359861613696:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('/etc/letsencrypt/live/example.com/privkey.pem','r')
140359861613696:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
unable to load private key
There is a problem in installing SSL to Ant Media Server.
 Please take a look at the logs above and try to fix.
 If you do not have any idea, contact@antmedia.io
```

**To Reproduce**
Run `sudo ./enable_ssl.sh -f {FULL_CHAIN_FILE} -p {PRIVATE_KEY_FILE} -d {DOMAIN_NAME}`
See error codes

**Expected behavior**
The system uses the custom certs provided and installs them and does not even cosider the LetsEncrypt directory.

**Extra notes**

Found in version: Community Edition 1.7.2 20190602_1447
To workaround I had to manually create the missing files and drop in my certs.

**Comment by burak-58** [comment]
Hi @Clickbaitcake ,
We have a fresh update. Can you try with this:
https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/server/enable_ssl.sh
