### ISSUE TITLE
Streaming taking up all disk space after a while.

### ISSUE THREAD

**Issue by cod3pix** [ant-media/Ant-Media-Server#1483]
I'm running Antmedia Server on docker container, converting 16 rstp streams to Liveapp, with m3u list link.
The problem is that after a while the antmedia server takes up all the host space.
Is there any way to clear the cache generated by the conversion? Below is the Dockerfile that generates the application.

`FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y libx11-dev

ADD ./install_ant-media-server.sh /home
ADD ./ant-media-server-community-1.7.2-20190602_1447.zip /home

RUN cd home \
    && pwd \
    && chmod 755 install_ant-media-server.sh

RUN cd home \
    && pwd \
    && ./install_ant-media-server.sh ant-media-server-community-1.7.2-20190602_1447.zip

WORKDIR /usr/local/antmedia/

ENTRYPOINT ./start.sh`

**Comment by burak-58** [comment]
Do you record mp4? What is hls list size? What is the size of log files?
After you stop container you can run:
$ docker system prune -a --volumes
