### ISSUE TITLE
Issue with ports/ssl

### ISSUE THREAD

**Issue by SAMYEL06** [ant-media/Ant-Media-Server#1484]
Hello,

I need to know how to change HTTP and HTTPS ports back to 80 and 443, instead of 5080 and 5443. Can you help me ?

Reasons : 

- Getting errors when trying to enable SSL : I tried EVERYTHING.
- Tried to embed the code you give us into my webpage : as it's not HTTPS (5080), it doesn't load and is blocked by the browser.....

I would very much appreciate understanding how to change these default ports for good... 

I tried to change the ports in red5.properties : 

> # HTTP

> http.host=0.0.0.0
> http.port=5080
> https.port=5443
> http.URIEncoding=UTF-8
> http.max_keep_alive_requests=-1
> http.max_threads=20
> http.acceptor_thread_count=10
> http.processor_cache=20

But it didn't work... 

Thanks !

**Comment by SAMYEL06** [comment]
Up ? No one can help me with this ? :/

**Comment by burak-58** [comment]
Hi @SAMYEL06 ,
What is the problem with the enabling SSL?
Did you try port forwarding with iptables as an alternative solution to port changing?

**Comment by SAMYEL06** [comment]
> Hi @SAMYEL06 ,
> What is the problem with the enabling SSL?
> Did you try port forwarding with iptables as an alternative solution to port changing?

Hello, sorry for the delay I was in vacations .. ! 

The reason it's not working is that I installed ant media on "Ubuntu for Windows" (in bash) so iptable command lines doesn't work, and ssl gives me errors ... 

Isn't it possible to just change port 5080 to 80 ? :/ (and keep http) ?

**Comment by SAMYEL06** [comment]
It says : 

> System has not been booted with systemd as init system (PID 1). Can't operate.
> There is a problem in installing SSL to Ant Media Server.
>  Please take a look at the logs above and try to fix.
>  If you do not have any idea, contact@antmedia.io

**Comment by burak-58** [comment]
Sorry for the late response. Ant Media Server doesn't support port configuration for now. Please try a solution on a different level such as port forwarding etc. 
I will close the issue, you can still discuss the issue at community channels:
[stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).
