### ISSUE TITLE
Time latence on starting the stream

### ISSUE THREAD

**Issue by ElKnarzo** [ant-media/Ant-Media-Server#1487]
Hi,

I am using the Antmedia SDK for iOS for project. When opening a stream, it sometimes takes several seconds (about 7 - 20) sometimes only up to 5 seconds to start it.

How can this time difference occur when starting the stream? How can this be fixed?

**Comment by burak-58** [comment]
Did you try it for consecutive streams? Is the problem continues after the first stream?
It takes long to get IP for the first stream.

**Comment by ElKnarzo** [comment]
I was able to determine when this latency occurs.

The time latency occurs only after closing the first stream and opening a new one. The reason for this is that the previous AVCaptureSession will not stop when the stream is ended.

**Comment by mekya** [comment]
Closing this issue for now. Please re-open if this issue still exists for you
