### ISSUE TITLE
WebRTC stream hangs if it wasn't properly closed

### ISSUE THREAD

**Issue by Keyreach** [ant-media/Ant-Media-Server#1497]
**Describe the bug**
Stream published via WebRTC often "hangs" when it wasn't stopped properly - signalling connection or video stream interrupted, camera detached.

Effects:
* it's displayed in dashboard as "broadcasting"
* it's unable to publish stream with same name
* it's seems to be available via HLS/RTMP, but cannot be watched (connects without errors, but doesn't show any video)

On server:
* there's internal connection to server's RTMP port visible using netstat
* there's errors in logs related to ffmpeg/av_* functions

**To Reproduce**
1. Publish stream via WebRTC publisher
2. Disconnect camera or close tab/browser
3. One or multiple of aforementioned effects are appearing

**Expected behavior**
Stop stream completely after streamer both stopped to send video stream and disconnected from signalling endpoint or some timeout was occurred.

**Comment by burak-58** [comment]
It will be fixed in 1.9.0

**Comment by mekya** [comment]
Closing this issue. Please re-open if problem still exists

**Comment by sivsushruth** [comment]
@mekya this issue still persists. Every few streams, if connection does not close server hangs, all apis timeout
Only option is restarting the instance. service antmedia restart also does not work
