### ISSUE TITLE
Reduce latency for HLS stream?

### ISSUE THREAD

**Issue by LeBlaaanc** [ant-media/Ant-Media-Server#15]
Hi, I'm noticing that the method that HLS is broadcast is by providing a single playlist file and continually updating it. This makes live streaming sort of work but the delay is something like 1 minute as it seems to always buffer 5 10 second stream .ts files. I tried playing around with these settings, anything else to look into?

```
fileconsumer.delayed.write=false
fileconsumer.queue.size=0
```

**Comment by mekya** [comment]
You may set below properties in app's red5-web.properties file. 

```
# size of the list
settings.hlsListSize=10   
# duration of the segment in seconds
settings.hlsTime=5  
``` 

Another issue is that broadcast should have key frames less than or equal to the segment duration setting above

**Comment by LeBlaaanc** [comment]
@mekya oh I'm excited to try! Thank you.

**Comment by LeBlaaanc** [comment]
@mekya I added those two settings, do I need to do anything to the xml itself?

**Comment by mekya** [comment]
I remember now, WebRTCApp does not have app.settings bundle in the release. Please use the below file. Remove the .txt in the name. Put the WebRTCApp.war file in webapps folder and delete the toher "WebRTCApp" in the webapps. 

Your changes in red5-web.properties file will be effective then. 

[WebRTCApp.war.txt](https://github.com/ant-media/Ant-Media-Server/files/1460250/WebRTCApp.war.txt)

**Comment by LeBlaaanc** [comment]
This looks like what I am after? https://github.com/Red5/red5-hls-plugin/blob/master/example/src/main/webapp/WEB-INF/red5-web.xml#L29

**Comment by mekya** [comment]
No, we do not use red5-hls-plugin. 

We use ffmpeg and javacpp for producing HLS stream. Secondly, you need to use Ant Media Server not Red5.

**Comment by LeBlaaanc** [comment]
Okay, I see, if I delete the WebRTCApp folder where do I edit the properties?

**Comment by mekya** [comment]
Start the server and WebRTCApp folder will be created and war file will be deleted. Then change theproperties and restart the server again.

**Comment by LeBlaaanc** [comment]
Worked perfect, thanks @mekya I'll close this out :)
