### ISSUE TITLE
Finishing WebRTC iOS Sample App

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#150]

**Comment by mekya** [comment]
@mekya review

**Comment by ogulcan** [comment]
@mekya 

Here are two repos that contain SDK and Reference Application.
SDK: https://gitlab.com/Ant-Media/WebRTCiOSSDK
App: https://gitlab.com/ogulcan/WebRTCiOSReferenceProject

We may talk about privacy issues in the office, tomorrow.

**Comment by mekya** [comment]
Testing remote test server and find out the delay in connection establishment
