### ISSUE TITLE
is this a bug? 

### ISSUE THREAD

**Issue by HyoGeunGit** [ant-media/Ant-Media-Server#1509]
i am trying to use Ant-Media-Server but when i enter sudo ./install_ant-media-server.sh [ANT_MEDIA_SERVER_INSTALLATION_FILE] true the terminal say There is a problem in installing the ant media server. Please send the log of this console to contact@antmedia.io TT 
ps:// i am using macos

**Comment by burak-58** [comment]
Hi @HyoGeunGit,
Did you write the name of ant -media-server...zip file instead of [ANT_MEDIA_SERVER_INSTALLATION_FILE]?
