### ISSUE TITLE
Cross Domain on IE11 for HLS with JWplayer 8

### ISSUE THREAD

**Issue by jobpalmero** [ant-media/Ant-Media-Server#1511]
Hi, today i see a problem while running an HLS stream with Internet Explorer 11 using JWplayer 8.

I can see a request that return 404 with developer tools of my browser. The request are;

"**https://...mydomain.../crossdomain.xml**" but doesn't exist and the result is a black page or black screen.

**SOLUTION**

Is Easy.... You can go to your ANT server with SSH (per example) and **create a new file "crossdomain.xml"** in your web root folder, example => "**/usr/local/antmedia/webapps/root/crossdomain.xml**".

The valid content of the file for me was this;

```
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
  <allow-access-from domain="*" to-ports="*" secure="true" /> 
  <allow-http-request-headers-from domain="*" headers="*" secure="true" /> 
</cross-domain-policy>
```

An alternative, is integrate this feature in future on the webpanel as option for personalize it. Thank's

**Comment by burak-58** [comment]
Thank you for your contribution. We will consider your suggestions.
