### ISSUE TITLE
EncoderBlocked cases

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1513]
Process hungs sometimes

**Comment by themitigater** [comment]
Hey Mekya,
Can you please explain why this happens and what can we do to fix it?

**Comment by ntnahn** [comment]
Hi Mekya,
I have same error too.
I'm using Ant Media Enterprise Edition 1.9.1 20200112_1830
I want to know how to fix it too.
Thanks

**Comment by ntnahn** [comment]
Hi @mekya , is this issue fixed?
I facing it too many times

**Comment by aatb-ch** [comment]
seeing the same issue on Enterprise Edition 2.0.0-SNAPSHOT 20200427_1317. Publishing a stream via the default stream page, getting a "encoderBlocked" alert after a few hours, have to manually stop/start republishing.. breaking the whole project.

**Comment by skyEnrique** [comment]
Was there an update on this?
We also encounter this error. When using webrtc test publish page.
AMS version:Enterprise Edition 2.8.2 20240201_1145

**Comment by mekya** [comment]
hi @skyEnrique,
This issue has been fixed for a long time. I think you're encountering another issue.

Could you create a new issue by explaining what you encounter?

Regards
Oguz
