### ISSUE TITLE
Signal channel closed with code server error

### ISSUE THREAD

**Issue by eriol726** [ant-media/Ant-Media-Server#1541]
Hi, I tried to run the webrtc-android-sample-app but when i push the "start streaming" button I receive the message "Signal channel closed with code server error".

The server im connecting to is: `SERVER_URL = "ws://test.antmedia.io:5443/WebRTCAppEE";`
I'm using an Android SM-G950F and running the app from Android studio on a windows computer.

![Screenshot_58](https://user-images.githubusercontent.com/2978902/65523770-0be9d500-deed-11e9-9408-80e491e3b969.png)

**Comment by dimpleagola** [comment]
I  also getting signal channel error. If any solution Please tell me.

**Comment by davutcavdar** [comment]
Please use wss: instead of ws: in the URL.

**Comment by dimpleagola** [comment]
Yes , I am using wss://http://ant.abcded.org.    But still I ma getting  same error.

**Comment by mekya** [comment]
You should not use "wss://http" together. Just wss://ant.abcded.org. 

I think you can also use the latest SDK as well. 

Closing this issue. Feel free to open if you need
