### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0.1 compiler Error

### ISSUE THREAD

**Issue by keyurtristate** [ant-media/Ant-Media-Server#1554]
I added your framework as per your comment but I got the error like this way, please help

Simulator
Could not find module 'AntMediaSDK' for architecture 'x86_64'; found: arm64, arm

Device
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0.1 compiler: /ThirdParty/Framework/AntMediaSDK.framework/Modules/AntMediaSDK.swiftmodule/arm64.swiftmodule

**Comment by mekya** [comment]
Hi @keyurtristate ,

I think you're using and older version of our iOS SDK. It's now fully working with iOS13 and swiftt 5.1

Please contact support through your email used in subscription then you will get updated framework.

So that closing this issue.
