### ISSUE TITLE
Solution for local SSL and ip based SSL 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#1560]

**Comment by MinhHungTrinh** [comment]
I have the same issue. Following

**Comment by SelimEmre** [comment]
Hi @mekya and @MinhHungTrinh,

Let me give you some details about this issue. `enable_ssl.sh` script supports this solution. You can use SSL for IP address and local network domain. Please check [our guide](https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-to-use-self-signed-certificate-on-ant-media-server).
