### ISSUE TITLE
noStreamNameSpecified error received when ping command is sent to websocket

### ISSUE THREAD

**Issue by rhengles** [ant-media/Ant-Media-Server#1564]
***Attention:*** *For your support questions, ask at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).*

***PLEASE FILL THE FOLLOWINGS AS MUCH AS POSSIBLE FOR FASTER SOLUTION***

**Describe the bug**
I searched the issues here, but I didn't found this one. I'm implementing Ant Media Server on my server and the websocket connects normally and publishes the stream. But after publishing a stream, the ping requests on the websocket return with the message `{"definition":"noStreamNameSpecified","command":"error"}`.

**To Reproduce**
1. Use webrtc adaptor javascript file
2. Connect the websocket
3. Publish a stream with a streamId
4. Stop the stream
5. The script sends ping requests that return error messages.

**Expected behavior**
A `{"command": "pong"}` response on the websocket.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90

**Additional context**
AMS Community Edition 1.7.2 20190602_1447
Default version preinstalled by DigitalOcean last week.

**Comment by burak-58** [comment]
We will update the version on DigitalOcean. It will be fixed with the new version.

**Comment by mekya** [comment]
Closing this issue. DigitalOcean image will be update in these weeks.

**Comment by rhengles** [comment]
I see that the image was updated on DigitalOcean marketplace, but can I update my existing instance from 1.7.2 to 1.9.0 ?

Thanks!
