### ISSUE TITLE
How to config record stream (VoD) file about 10 minutes per file

### ISSUE THREAD

**Issue by lecong** [ant-media/Ant-Media-Server#1598]
Hi everyone,

I using Ant Media Server. But record stream (VoD) file very large.
I want config record stream file about 10 minutes per file.

Please help me config or implement it.

**Comment by moragab1993** [comment]
any update regarding this ? as i am also trying to do the same thing

**Comment by mekya** [comment]
Sorry for late reply. We're going to assign this ticket to someone in our team in this week. Thank you for comment @moragab1993

**Comment by golgetahir** [comment]
Hi,

To solve this problem, we have the opportunity to change the recording status with REST API. You can find the REST APIs in https://antmedia.io/rest/#/

The API name you probably want is: /v2/broadcasts/{id}/recording/{recording-status} 

Also, if you are pulling stream from an external source to the server, you can use the restart configuration from application configurations `settings.streamFetcherRestartPeriod` as a work around solution.

I hope this will help you.
