### ISSUE TITLE
Saved file with extension .mp4.tmp_extension

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#1599]
**Describe the bug**
Sometimes i got the saved file name with extension .mp4.tmp_extension instead of .mp4
When i change the file extension from .mp4.tmp_extension to .mp4, i cannot play it.
So, have any ways to fix this file?

**Comment by burak-58** [comment]
After the stream finishes it is changed automatically. Actually, this is not only renaming but also remuxing done by the server. You can check related [code](https://github.com/ant-media/Ant-Media-Server-Common/blob/0e1e490bdc8f4fb69183b3081044d3ad42371494/src/main/java/io/antmedia/muxer/Mp4Muxer.java#L362).

**Comment by ntnahn** [comment]
Thank you, but can you guide me how to run this [code](https://github.com/ant-media/Ant-Media-Server-Common/blob/0e1e490bdc8f4fb69183b3081044d3ad42371494/src/main/java/io/antmedia/muxer/Mp4Muxer.java#L362) to fix my file directly

**Comment by burak-58** [comment]
@ntnahn 
Please check the wiki pages. You will find how you can build from the source. For more help please ask at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).
