### ISSUE TITLE
Vod count error 

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#166]
Vod count shows wrong numbers. 

![screenshot from 2018-06-08 04-48-30](https://user-images.githubusercontent.com/9084130/41209044-59447276-6d31-11e8-9265-ad170592d312.png)
![screenshot from 2018-06-08 04-48-52](https://user-images.githubusercontent.com/9084130/41209045-5964eaba-6d31-11e8-8235-ec83be079395.png)
![screenshot from 2018-06-08 04-49-50](https://user-images.githubusercontent.com/9084130/41209046-5986abf0-6d31-11e8-9ed2-d4f22887affb.png)

Delete all VoD in different stream bitrate and in different formats(dash, mp4, etc.) 

Write test code about it

**Comment by davutcavdar** [comment]
Also live stream count at the bottom of the page is invalid, fix that
