### ISSUE TITLE
Fresh installation on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by patoberli** [ant-media/Ant-Media-Server#1707]
***Attention:*** *For your support questions, ask at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).*

***PLEASE FILL THE FOLLOWINGS AS MUCH AS POSSIBLE FOR FASTER SOLUTION***

**Describe the bug**
A fresh installation on latest Ubuntu 16.04 LTS, updated to today, fails to run. The installation itself is successful, but the antmedia service doesn't start.

Syslog shows:
Dec  4 02:33:29 ubuntu systemd[1]: Started AntMedia.
Dec  4 02:33:29 ubuntu systemd[50498]: antmedia.service: Failed at step EXEC spawning /etc/init.d/antmedia: No such file or directory
Dec  4 02:33:29 ubuntu systemd[1]: antmedia.service: Main process exited, code=exited, status=203/EXEC
Dec  4 02:33:29 ubuntu systemd[1]: antmedia.service: Unit entered failed state.
Dec  4 02:33:29 ubuntu systemd[1]: antmedia.service: Failed with result 'exit-code'.
Dec  4 02:33:31 ubuntu systemd[1]: antmedia.service: Service hold-off time over, scheduling restart.
Dec  4 02:33:31 ubuntu systemd[1]: Stopped AntMedia.

**To Reproduce**
Make a brand new Ubuntu 16.04 Server installation (ubuntu-16.04.6-server-amd64.iso).
apt-get update && apt-get dist-upgrade -y
reboot
Follow the manual here: https://github.com/ant-media/Ant-Media-Server/wiki/Getting-Started
Installation is successful, but doesn't work.

There is no 'antmedia' file added to /etc/init.d/. 
Also the installation script has installed java-8-openjdk and not the oracle version, not sure if that is another problem.

**Expected behavior**
I would expect the service to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.06 LTS

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here such as server logs, etc...

**Comment by patoberli** [comment]
Small update, I think the one of the issues was caused because of the changes in the install script.
My first download was this version: https://github.com/ant-media/Scripts/commit/22c01760690fd86053e8cc55e6e10ff329aa9e96#diff-2efc75b6e1689b17bc14027e3d8ec95b
That has been reverted now and I removed those files from my installation (first disabled it). 
The installation still doesn't run, but at least the service seems to start now.

**Comment by patoberli** [comment]
Last problem was the enabled IPv6. After I manually disabled IPv6 on my Ubuntu installation, the service finally bound to ipv4 (before it only bound to ipv6) and was accessible.

**Comment by mekya** [comment]
Thank you for the report. 

After reverting the last 2 commits, I've made an installation in ubuntu 16.04 and it's working for me now. 

Right now, is it ok for you when you have fresh install?

**Comment by patoberli** [comment]
Yes it is, although jsvc only bound to the IPv6 interface and not to IPv4. Not sure if that was/is a VMware issue or not. After I disabled IPv6 globally on Ubuntu it bound correctly to IPv4.
Please note, I had to manually remove the service file that was created in the first try, otherwise it would not start, not even with the reverted changes.

**Comment by mekya** [comment]
We've not encounter any IPv6 issue perviously.  
Fortunately, we start to work with IPv6 soon. 

Yeah you're right about manually removing the service file. Right now we reverted that commits. 

Closing this issue now. If you think there is still problem, please feel free to re-open
