### ISSUE TITLE
SSL certificate renewals don't update certificate served to clients

### ISSUE THREAD

**Issue by vtsatskin** [ant-media/Ant-Media-Server#1710]
**Describe the bug**
When `./enable_ssl.sh -d <DOMAIN>` is run, it sets up a crontab for renewing SSL certificates. This will run correctly. However, the certificate served to clients is not updated. This eventually leads to an expired certificate on deployed systems.

**To Reproduce**
1. Run `./enable_ssl.sh -d <DOMAIN>`
2. Wait one month
3. Check the syslog to confirm renewals occur: `journalctl | grep enable_ssl`
4. Inspect certificate served

Alternatively, running `./enable_ssl.sh -d <DOMAIN>` directly and choosing to renew the certificate leads to the same problem.

**Expected behavior**
Certificates served to clients are renewed.

**Desktop**
 - OS: macOS
 - Browser: Firefox, Safari
- Running Ant Media Server: 1.8.1

**Additional context**

Rebooting the server after renewing the certificates worked. Maybe some service is not restarted properly after renewal, for example apache?

Here's the output of running `./enable_ssl.sh`:

```
ubuntu@ip-172-31-18-32:/usr/local/antmedia$ sudo ./enable_ssl.sh -d REDACTED
domain: REDACTED
creating new certificate
gpg: keyring `/tmp/tmp3mek7afs/secring.gpg' created
gpg: keyring `/tmp/tmp3mek7afs/pubring.gpg' created
gpg: requesting key 75BCA694 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3mek7afs/trustdb.gpg: trustdb created
gpg: key 75BCA694: public key "Launchpad PPA for certbot" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/REDACTED.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/REDACTED/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/REDACTED/privkey.pem
   Your cert will expire on 2020-03-03. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le


Importing keystore /usr/local/antmedia/REDACTED/fullchain_and_key.p12 to /usr/local/antmedia/REDACTED/keystore.jks...
Certificate stored in file </usr/local/antmedia/REDACTED/tomcat.cer>
Certificate was added to keystore

SSL certificate is installed.
Https port: 5443
You can use this url: https://REDACTED:5443/
```

**Comment by vtsatskin** [comment]
Hello, has anyone had a chance to look at this?

Thanks,
Valentin

**Comment by ithirzty** [comment]
Hi! I'm having the same problem, have you found a solution? Thanks.

**Comment by mekya** [comment]
Sorry for not being responsive. We'll assign someone for this issue.

**Comment by mekya** [comment]
Hey @muratugureminoglu , 
Could you help resolving this issue?

It's running 1.8.1. It may already be resolved in 1.9.1

**Comment by muratugureminoglu** [comment]
Hi,

Could you upgrade to version 1.9.1 please ? then rerun enable_ssl.sh script.

Best.

**Comment by ithirzty** [comment]
Hi,
The script wasn't working 1.9.1 still but I made a new script myself and it
works.

Thanks, best regards.
