### ISSUE TITLE
 [RTMPConnectionExecutor-4] ERROR o.red5.server.stream.StreamService - Bad name

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#1784]
**Describe the bug**
2020-01-03 16:30:04,344 [RTMPConnectionExecutor-4] ERROR o.red5.server.stream.StreamService - Bad name 982461415187086075828557
2020-01-03 16:30:04,344 [RTMPConnectionExecutor-4] ERROR o.red5.server.stream.StreamService - Bad name 982461415187086075828557

**To Reproduce**
1. The issue that if I stop the stream and I start again after a while (like 2-3 hours) I have this error in the console.

**Screenshots**
![Ir8VpNUO6ugmMXk8yK7RJx-I7hvOQyC5ug](https://user-images.githubusercontent.com/6337605/71738018-62f53380-2e66-11ea-9abf-9a95a29a0f85.png)

**Additional context**
Logs will add as soon as possible.
Enterprise Edition 1.9.0 20191127_1810

**Comment by riodda** [comment]
Hi, I have done some experiments and i suspect that this issue is coming out when i have no data input on the HDMI port of my hardware streamer (like a full blue frame).

**Comment by mekya** [comment]
Can you provide logs @riodda ? 

Log files are under "/usr/local/antmedia/logs/"

**Comment by mekya** [comment]
I've checked the related part in the code. It seems that this issue happens when another stream with the same stream id is already published. 

Can you regularly reproduce the issue?
