### ISSUE TITLE
jmx.rmi.host value is ignored

### ISSUE THREAD

**Issue by cemalgultekin** [ant-media/Ant-Media-Server#1808]
Hello,

we are testing _Enterprise Edition 1.9.0 20191127_1810_ on _Ubuntu 16.04 LTS_ .

We want to change the *jmx.rmi.host* to serve from a specific ip address, therefore changed the value from _/usr/local/antmedia/conf/red5.properties_ file, however it still serves from all the available ip addresses.

**Comment by muratugureminoglu** [comment]
Hello Cemal,

We dont use red5.properties file for Jmx configration. 

You need to change /etc/init.d/antmedia file as follows.

Open with editor the following file.

**vim /etc/init.d/antmedia**

find "**JVM_OPTS=**" variable then change this line as follow.
```
JVM_OPTS="-Xverify:none -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:InitialCodeCacheSize=8m -XX:ReservedCodeCacheSize=32m -Dorg.terracotta.quartz.skipUpdateCheck=true -XX:+UseG1GC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5599 -Djava.rmi.server.useLocalHostname=true -Dcom.sun.management.jmxremote.rmi.port=5599 -Djava.rmi.server.hostname=YOUR_SERVER_IP"
```
After saving file, restart antmedia service.

Reference Link:
https://raw.githubusercontent.com/ant-media/Ant-Media-Server-Service/master/src/main/daemon/antmedia

**Comment by cemalgultekin** [comment]
Hello Murat,

changed

    JVM_OPTS="-Xverify:none -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:InitialCodeCacheSize=8m -XX:ReservedCodeCacheSize=32m -Dorg.terracotta.quartz.skipUpdateCheck=true -XX:+UseG1GC"

to 
    
    JVM_OPTS="-Xverify:none -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:InitialCodeCacheSize=8m -XX:ReservedCodeCacheSize=32m -Dorg.terracotta.quartz.skipUpdateCheck=true -XX:+UseG1GC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5599 -Djava.rmi.server.useLocalHostname=true -Dcom.sun.management.jmxremote.rmi.port=5599 -Djava.rmi.server.hostname=*.*.*.*"

I have also replaced the actual ip address with \*.\*.\*.\*, in my _/etc/init.d/antmedia_ file. Also since this is systemd, I have executed 

    systemctl daemon-reload
 , and then 

    systemctl restart antmedia


however executing
 
    lsof -i -n -P | grep 5599
, shows me that 

    jsvc      15749 antmedia   28u  IPv6  37760      0t0  TCP *:5599 (LISTEN)

**Comment by muratugureminoglu** [comment]
Hi, Could you try the following line?

`JVM_OPTS="-Xverify:none -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:InitialCodeCacheSize=8m -XX:ReservedCodeCacheSize=32m -Dorg.terracotta.quartz.skipUpdateCheck=true -XX:+UseG1GC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5599 -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.host=127.0.0.1 -Djava.rmi.server.hostname=127.0.0.1 -Djava.rmi.server.useLocalHostname=true -Dcom.sun.management.jmxremote.rmi.port=5599"`

**Comment by muratugureminoglu** [comment]
Hi, Can you add the following parameter to the end of the JMV variable? This parameter listen only the localhost.
`JVM_OPTS= -Dcom.sun.management.jmxremote.host=127.0.0.1
`
`tcp        0      0 127.0.0.1:5599          0.0.0.0:*               LISTEN      8566/jsvc.exec      
`
