### ISSUE TITLE
Disable VoD downloading

### ISSUE THREAD

**Issue by jeusdi** [ant-media/Ant-Media-Server#1860]
I've just installed an ant media server instance.

I've uplaod mp4 video as VoD and I've been able to see them using this code snippet:

    <iframe width="560" height="315" src="http://localhost:5080/LiveApp/play.html?name=378475861251583275889765" frameborder="0" allowfullscreen></iframe>

However, I faced with I was able to download the video.

 1. I thought that when "a stream" is not able to download, it's just an stream.
 2. I guess I'm doing something wrong. Any ideas?

**Comment by muratugureminoglu** [comment]
If you watch as WebRTC and HLS, mp4 files cannot download 

http://localhost:5080/LiveApp/play.html?name=378475861251583275889765&playOrder=hls  
http://localhost:5080/LiveApp/play.html?name=378475861251583275889765&playOrder=webrtc
