### ISSUE TITLE
Installed Ant Media Server in an LXD Container.

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1951]
# Issue
How to broadcast using Ant Media installed in an LXD container?

### Short description
Can't access Ant Media Server that is installed in an Ubuntu 18.04 LXD Container. The container has a 10.xxx.xxx.xxx IP only.  Not sure how to configure this.  I need to access the Ant Media Server from the internet.  Do I need some sort of port forwarding?
I can ping the container from the host and the host can ping the container.

### Environment

* Operating system and version: Host is Ubuntu 18.04
LXD Container is Ubuntu 18.04
* Java version: 
* Ant Media Server version: 1.9
* Browser name and version:

### Expected behavior
Browsing to container should prompt for access to camera/mic
### Actual behavior
?  How should I access the container from 

### Steps to reproduce
1. Create the LXD Container
2. Install Ant Media Server 
3. Access the Ant Media Server

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by rayj00** [comment]
java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**Comment by muratugureminoglu** [comment]
Hi, We do not support the LXD container structure. We support the Docker.

**Comment by rayj00** [comment]
LXD comes native to Ubuntu OS.  I got it to work.
