### ISSUE TITLE
Error executing enable_ssl.sh script

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1955]
***Attention:*** *For your support questions, ask at [stackoverflow](https://stackoverflow.com/questions/tagged/ant-media-server) or [our community forum](https://groups.google.com/forum/#!forum/ant-media-server).*

***PLEASE FILL THE FOLLOWINGS AS MUCH AS POSSIBLE FOR FASTER SOLUTION***
I installed the Ant Media Server 1.9.1 in an LXD container.
I then tried to install the letsencrypt ssl certificate using the enable_ssl.sh script:
sudo ./enable_ssl.sh -d www.mydomain.us -i /usr/local/antmedia

and got the following error:

**Describe the bug**
 domain: www.mydomain.us
./enable_ssl.sh: 281: [: false: unexpected operator
./enable_ssl.sh: 290: [: false: unexpected operator

**_SSL certificate is installed.
Https port: 5443
You can use this url: https://www.streamingworld.us:5443/_**

I think the above 3 lines are a lie!!!

**To Reproduce**
Run sudo ./enable_ssl.sh -d www.mydomain.us -i /usr/local/antmedia

**Expected behavior**
Certificate created and installed

**I expected to see something like this:**

domain: www.mydomain.us
creating new certificate
Hit:1 http://mirrors.linode.com/ubuntu bionic InRelease
Hit:2 http://mirrors.linode.com/ubuntu bionic-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:5 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Fetched 88.7 kB in 1s (143 kB/s)
Reading package lists... Done
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.mydomain.us
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/www.mydomain.us/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/www.mudomain.us/privkey.pem

**Comment by rayj00** [comment]
Note that I can get to http://www.mydomain.us:5080/WebRTCApp/,  but it warns of "UnsecureContext"

**Comment by canat** [comment]
Hello,

the problem is most likely related to LXD containers. I am not sure, if enable_ssl.sh script is tested with LXD containers before and we don't officially support LXD containers yet. 
It seems, you have also posted a question in this web site: https://community.letsencrypt.org/t/ssl-for-lxd-container-websites/87244 Have you been able to fix your problem? 
If not, can you try enable_ssl.sh script in a setup without using LXD container? 

Best,
Can

**Comment by canat** [comment]
Could you please also update certbot package(or reinstall)? enable_ssl.sh script uses the certbot package. There is a small chance that the problem can be related to that.
