### ISSUE TITLE
iPhone (iOS) live stream output .m3u8 rotated

### ISSUE THREAD

**Issue by rogyvoje** [ant-media/Ant-Media-Server#1956]
Hey guys, I wanted to check the issue I found when streaming from a smartphone, iOS specifically.

I already left some comments on a closed one but I don't think it should be closed, but correct me if I'm wrong :smile_cat: 
https://github.com/ant-media/Ant-Media-Server/issues/825

* Go to example app to stream from iPhone SE (iOS 13.3.1, Safari)
* Start publishing
* Go to https://mydomain.com/#/applications/WebRTCAppEE (Dashboard)
* Click play to watch the stream, everything is fine, but keep in mind that this is using WebRTC to watch that live stream
* Install this extension https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof
* Now go to https://mydomain.com/WebRTCAppEE/streams/stream1.m3u8
* You will see that the stream is rotated horizontally but it should be in portrait mode as I'm publishing in portrait mode with my front camera. And the stream is fetched though HLS not WebRTC

**Expected behavior**
Keep .m3u8 output in the same rotation.

**Smartphone (please complete the following information):**
 - Device: [iPhone SE]
 - OS: [iOS 13.3.1]
 - Browser [Safari]
 - Version [latest]

We are using:
Enterprise Edition 1.9.1 20200112_1830

**Comment by JaviOverflow** [comment]
This has been open for more than a year now. Is there any progress on this? Any workarounds? I'm having this issue and we would like to go live soon.

**Comment by salsaweb** [comment]
Hello,

We are facing same issue for Android App and also for **web examples**.

**Steps to reproduce the behavior:**
1.  open in iPhone browser (safari, chrome) https://mydomain.com/WebRTCAppEE/ and publish broadcast
2. open in laptop browser https://mydomain.com/WebRTCAppEE/play.html?name=stream1&playOrder=hls it's important to set playOrder to HLS
3. as a result you will see video in rotation

we are using **Enterprise Edition 2.2.1 20201029_2042**

**Comment by mekya** [comment]
In order to fix it, we need to rotate the video in HLS player. 

We're also discussing this one in the issue below
https://github.com/ant-media/Ant-Media-Server/issues/3614
