### ISSUE TITLE
Broadcast Stops After 10-15 seconds.

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1968]
Using Ant Media in an LXD Container on Ubuntu 18.04

I can start a broadcast,  but after 10-15 seconds the broadcast stops for some reason!

I have googled the problem and found the "open udp ports 5000-65635"  but that does not work.

Any ideas?

Thanks,

Ray

**Comment by SelimEmre** [comment]
Can you please add some logs in here and please give us more detail in your use case to reproduce your issue?

**Comment by rayj00** [comment]
So I have Ant Media installed in an LXD Container.  I can access the  server externally and broadcast, but the broadcast aborts after 10-15 seconds.  Here is a log file. 

[Broadcast Stops After 10-15 Secs.txt](https://github.com/ant-media/Ant-Media-Server/files/4351713/Broadcast.Stops.After.10-15.Secs.txt)

**Comment by rayj00** [comment]
Please visit https://groups.google.com/forum/#!topic/ant-media-server/GzpI-q4iNhg for more details.

**Comment by rayj00** [comment]
No one has any ideas?

**Comment by muratugureminoglu** [comment]
Hi, We do not support the LXD container structure. We support the Docker.
