### ISSUE TITLE
Impossible to run enable ssl

### ISSUE THREAD

**Issue by ithirzty** [ant-media/Ant-Media-Server#1972]
# Issue

### Short description
I got some problems between certbot and ant media server that made me uninstall and reinstall ant media server. Now the script enable_ssl.sh is no longer working (python errors). It would be nice to try to uninstall it completely but there is no info on what to do... Even a list of programs to uninstall would be nice.

### Environment

* Operating system and version: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)
* Java version: openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
* Ant Media Server version: [1.8.0;1.9.1]
* Browser name and version: Chrome 80.0.3987.149 (latest version)

### Expected behavior
Expected behavior would be to let me run enable_ssl.sh script.
### Actual behavior
When exectuing `./enable_ssl.sh -d REDACTED.xyz` it simply says `domain: REDACTED.xyz
creating new certificate` and then nothing. When ^C it gives me a bunch of python errors ([pastebin](https://pastebin.com/hqhP0TW5))
### Steps to reproduce
1. install ant media server (with the install script)
2. run ./enable_ssl.sh -d REDACTED.xyz
3. after few hours of nothing type ^C (CTRL + C) to interrupt
### Log
[pastebin](https://pastebin.com/A3p68suw)

**Comment by muratugureminoglu** [comment]
Hi, 

Could you please update certbot package(or reinstall)?  enable_ssl.sh script uses the certbot package.

Best.

**Comment by ithirzty** [comment]
> Hi,
> 
> Could you please update certbot package(or reinstall)? enable_ssl.sh script uses the certbot package.
> 
> Best.

Hi, my certbot is up to date, I reinstalled it and tested it on my apache server with all my websites and it works but the enable_ssl.sh script still has the same output...

**Comment by muratugureminoglu** [comment]
Hi, 
Python errors are related to certbot and the script is working perfectly. You can try it in a new installation.

**Comment by ithirzty** [comment]
Thanks, it was an issue with certbot but because it wasn't working I ran the script multiple time and now I have exceeded the rates limit of lets encrypt. One week to wait I guess!
