### ISSUE TITLE
Adding specific RTSP ONVIF URL

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#1982]
**Is your feature request related to a problem? Please describe.**
I have "rtsp://user:pass@x.x.x.x:9001:5549/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast" - notice the ":9001:5549" part. The 9001 is the HTTP server port and 5549 is the RTSP port.
From what I can see, in the UI at least, there is no way for me to specify the exact ONVIF URL.

**Describe the solution you'd like**
1. I want to add a specific RTSP ONVIF URL in the IP Camera section.

**Comment by mekya** [comment]
This is a correct URL? It has two ports 9001 and 5549 

rtsp://user:pass@x.x.x.x:9001:5549/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast

**Comment by mekya** [comment]
Closing this issue for the inactivity.
