### ISSUE TITLE
Publishing Stops After 10-15 Secs. Getting desperate!!

### ISSUE THREAD

**Issue by rayj00** [ant-media/Ant-Media-Server#1988]
I am having this issue. I have opened the UDP ports 5000:65000 but still have the problem. 

One caveat, I am running the Ant Media Server out of an LXD container. Is there something special I need to configure?  The getUserMedia is working fine.  It's when I click on "Start Publishing", after 10-15 seconds it stops publishing. I think I may need some port forwarding on the container, but not sure how to implement it.  Can anyone help?

Thanks,

Ray

**Comment by rayj00** [comment]
BTW,  I am using HAProxy to redirect incoming calls to the correct container based on the sub-domain.

**Comment by rayj00** [comment]
Is this correct?  I see a UDP candidate as well as a TCP canidate then the publishing stop?

Ice candidate list size to be added: 1 webrtc_adaptor.js:831:12
received ice candidate for stream id stream1 webrtc_adaptor.js:1105:14
candidate:4173673917 1 **udp** 1686052607 23.239.31.177 37719 typ srflx raddr 10.90.200.76 rport 37719 generation 0 ufrag AAyc network-id 1 webrtc_adaptor.js:1106:14
Candidate is added for stream stream1 2 webrtc_adaptor.js:894:13
received ice candidate for stream id stream1 webrtc_adaptor.js:1105:14
candidate:1079423129 1 **tcp** 1518280447 10.90.200.76 59537 typ host tcptype passive generation 0 ufrag AAyc network-id 1 webrtc_adaptor.js:1106:14
Candidate is added for stream stream1 webrtc_adaptor.js:894:13
ICE failed, add a STUN server and see about:webrtc for more details
publish finished WebRTCApp:246:13

**Comment by rayj00** [comment]
Ok I fixed my problem.  I had a port forwarding issue.

Now is there anyway to reduce the latency for the Community version?  Right now it looks like a 10 second latency.

Ray

**Comment by mekya** [comment]
There is no much way to reduce the latency in community edition. It's about 10 seconds.  You may upgrade to enterprise edition

Closing this issue.
