### ISSUE TITLE
WebRTC stream not working on Firefox Android

### ISSUE THREAD

**Issue by naholyr** [ant-media/Ant-Media-Server#1991]
**Describe the bug**

In "WebRTCAppEE" we start a stream and try to play it from the Ant Media Server Web UI (clicking on the "play" button, to ensure there is no custom code involved) → Works fine on mobile, except on Firefox for Android:

- The WebRTC player shows no video (black screen) but controls are here
- The audio is correctly streaming
- The viewers/bandwidth report in Ant Media Server Web UI shows an empty blue bar (no sent data), which is wrong as we correctly receive audio, though…

We didn't test HLS as we're not interested in this fallback, but I guess this sould work properly and this issue is only related to WebRTC implementation.

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10E
 - OS: Android 10
 - Browser: Firefox
 - Version: 68.6.0

**Comment by mekya** [comment]
This issue has been fixed in #2046
