### ISSUE TITLE
Ant-Media-Server is not working on E drive

### ISSUE THREAD

**Issue by vibhutieclerx** [ant-media/Ant-Media-Server#2]
# Issue
Ant-Media-Server is not working other than C drive

### Short description
I kept the Server folder on E drive and server was not starting. I took help from support and moved server folder to C drive and then it worked. If this will be the case my IS team will not allow me to deploy Ant-Media-Server on production server.

### Environment

[] Operating system and version: Windows Server 2008 R2
[] Java version: jdk1.8.0_144
[] Red5 version: ant-media-server-1.1.1

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mekya** [comment]
Hi,
If there is a white space in the path ("E:/Streaming Server/ant-media-server....") please change white space between "Streaming" and "Server" to a character like "-" and please try again.

Bests

**Comment by mekya** [comment]
Closing issue if you have any other problem, please let me know

Regards,
