### ISSUE TITLE
publish_started is sent before the stream is ready for clients

### ISSUE THREAD

**Issue by roeycohen** [ant-media/Ant-Media-Server#20]
if a viewer tries to play a stream immediately once the publisher received the publish_started notification, he receives an error: "No stream available with that name".

**Comment by roeycohen** [comment]
hi, is there any solution for this issue? maybe a workaround to tell when the stream is ready for subscribing?

**Comment by mekya** [comment]
Yeah this issue is fixed on webrtc_cluster branch. 

In webrtc_cluster branch, we are also trying N-to-N streaming in other words video conference.

**Comment by mekya** [comment]
Yeah this bug is fixed on the 1.4.0-SNAPSHOT enterprise edition, we have sent you today. Please reopen the issue if it does not work for you.
