### ISSUE TITLE
Implement switch in front and back camera in JS SDK for mobile platforms

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2022]
- Provide a method in JS SDK to switch cameras in the system(back/forth or other cameras)
- Switching cameras should be working in non-broadcasting and broadcasting state. 
   - In broadcasting state, streaming should not be stopped while switching cameras
- Create a radio button in WebRTC Publish demo that user can choose cameras
- Please check turnon/turnoff camera works for all cameras

**Comment by RodrigoRVieira** [comment]
Facing exactly the same issue here with latest SDK/server. Fix please.

**Comment by Glfarley** [comment]
Inconvenient to have to disable/enable cameras in Windows to switch them. Cannot choose any cameras at all in iOS 13.4.1!

**Comment by mekya** [comment]
This feature is implemented and it's in PR.  Unfortunately, travis has some problem for a couple of days that forces java 11 installation. This is why we don't merge it into the master.

**Comment by Glfarley** [comment]
Thanks. Will this also fix the problem where AMS does not choose any camera at all on my iPhone 11?

**Comment by 0x62** [comment]
This feature appears to be broken on Firefox - both in my implementation and on the demo application.

Enterprise Edition 2.3.2 20210422_0456
Firefox Developer 89.0b15

![Screenshot 2021-06-03 at 13 49 45](https://user-images.githubusercontent.com/6038417/120647568-a6e0d380-c472-11eb-8c66-ea0e90efc0e5.gif)

**Comment by mekya** [comment]
Thank you so much for your update @0x62.

I'm opening this issue to fix
