### ISSUE TITLE
How to record stream video to AWS s3 when build from AWS marketplace (Scaling with AWS)

### ISSUE THREAD

**Issue by MinhHungTrinh** [ant-media/Ant-Media-Server#2048]

**Comment by mekya** [comment]
Hi,

You can do that with S3 Integration. 

Check this out -> https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration

**Comment by MinhHungTrinh** [comment]
> https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration
I don't think so. I use Ant media is a Media server. Built it with AWS auto scale, Use launch config from AMI Ant media in AWS Marketplace (https://github.com/ant-media/Ant-Media-Server/wiki/Scaling-with-AWS). So, I can't access each ec2 instance to fix code as your guide.

**Comment by MinhHungTrinh** [comment]
Please explain how to do this.
