### ISSUE TITLE
joinRoom  Socket Command

### ISSUE THREAD

**Issue by khoogheem** [ant-media/Ant-Media-Server#2053]
First can we get updated Socket information in the Wiki it seems pretty out of date.

Issue - the `joinRoom` specifies that only a `room` is needed however if you do it produces the error on the socket: 
```
{"definition":"noStreamNameSpecified","command":"error"}
```

if you provide the `streamId` there is an issue in the console that the room/stream is out of order.  It looks like in parsing the json you are expecting that room and stream should have some sort of order when sending it.  However order shouldn't matter in JSON

**Comment by eneskuluk** [comment]
*  Websocket messaging wiki has been updated and you can check this out here for the joinRoom:
   * [https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference#conference-webrtc-stream](url)
* Currently it does not need a stream id for joinRoom command, it's optional. 
   * If you provide a streamId, server will return that id. 
  * But if you don't provide any streamId and send only roomId, server will generate a random streamId and will return it for the client.
