### ISSUE TITLE
MP4 Files cannot be downloaded because of the wrong absolute path.

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#2070]
**Describe the bug**
MP4 Files cannot be downloaded because of the wrong absolute path.

**To Reproduce**
1. Go to Settings
2. Set VoD Streaming Folder (Add directory where Mp4 files are located)
3. Go to Vod Tab Menu
4. Try to download a Vod file. You will get an error such as "Failed - No file". VOD directory path will not appear on the download link.

Link:
**http://192.168.1.245:5080/WebRTCAppEE/streams//test1.mp4**

The current link should be as follows.
**http://192.168.1.245:5080/WebRTCAppEE/streams/vod/test1.mp4**

**Expected behavior**
Should add absolute path on Vod download link.

- Version 1.9.1

**Comment by mekya** [comment]
Thank you for good report. It's confirmed and scheduled for fix.
