### ISSUE TITLE
Social Media Streaming with 720p Hard-Coded Resolution

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2073]
**Is your feature request related to a problem? Please describe.**
I am broadcasting to Youtube with 1080p stream resolution, but youtube dashboard showing me 720p resolution.

**Describe the solution you'd like**
Social streamings should show the right streaming resolution.

**Describe alternatives you've considered**
It can be solved by the add custom endpoint.

**Additional context**.
I realized, AMS enters 720p hard-coded streaming resolution in createBroadcast function / recreateEndpointsForSocialMedia / AntMediaApplicationAdapter.java

**Comment by mekya** [comment]
This problem is fixed in v2.1
