### ISSUE TITLE
Memory leakage bug report 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2087]
Request more info

**Comment by developer-appdam** [comment]
Hi all, I'm having this issue as well. The JVM keeps increasing and never going down(even after a restart). That is giving us issues with our streams.
Is there any solution?

**Comment by mekya** [comment]
This is about memory leakage in 2.0-snapshot. Do you encounter the problem in 2.0-snapshot?

**Comment by developer-appdam** [comment]
I haven't tried yet version 2.0, doesn't seem solid...

**Comment by saadqc** [comment]
is this fixed? I am have same issue. it keeps increasing
![image](https://user-images.githubusercontent.com/14905293/83082627-6602f180-a09d-11ea-9c43-adc15f488f9a.png)

**Comment by saadqc** [comment]
@mekya : Any update on this issue? we have r3.2xlarge instance (60Gb of ram) running in prod. But system memory usage keeps increasing even if there is no stream.

**Comment by mekya** [comment]
Yeah it's confirmed by some users. Btw, the behaviour is a little different
because the garbage collector is used for collecting native memory.
Secondly, we also improved the system memory graph to show more reliable
value
