### ISSUE TITLE
Take a look at how to integrate with Amazon Rekognition 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#209]

**Comment by mekya** [comment]
How to integrate live stream

**Comment by davutcavdar** [comment]
![Screenshot from 2018-07-30 21-43-30.png](https://images.zenhubusercontent.com/5b0923a876f98d26207425f6/9aa2eef7-3050-4e2f-aa83-e1438c7a2649)

**Comment by davutcavdar** [comment]
![Screenshot from 2018-07-30 21-40-46.png](https://images.zenhubusercontent.com/5b0923a876f98d26207425f6/e33e0465-2991-4fe7-b72b-25605b00fcc9)

**Comment by davutcavdar** [comment]
https://docs.aws.amazon.com/rekognition/latest/dg/streaming-video-starting-analysis.html 

To stream video into Amazon Rekognition Video, you use the Amazon Kinesis Video Streams SDK to create and use a Kinesis video stream. The PutMedia operation writes video data fragments into a Kinesis video stream that Amazon Rekognition Video consumes. Each video data fragment is typically 2–10 seconds in length and contains a self-contained sequence of video frames. Amazon Rekognition Video supports H.264 encoded videos, which can have three types of frames (I, B, and P). For more information, see Inter Frame. The first frame in the fragment must be an I-frame.

**Comment by davutcavdar** [comment]
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-putmedia.html
