### ISSUE TITLE
SRT Protocol Implementation - Phase 1 

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#2094]
Integrate JavaCPP with libsrt and start the server in listener mode

**Comment by akiziltoprak** [comment]
Should we also consider restream via SRT as well like RTMP restream

**Comment by deadbeef84** [comment]
It would be really great if you could support playing from SRT as well as restreaming.

**Comment by mekya** [comment]
Thank you @deadbeef84,

I see your point. Yes then SRT is a solution for you. 
If we implement the WebRTC support for ffmpeg,  is it also a solution for you?

**Comment by deadbeef84** [comment]
Yes, I would be fine with either.

**Comment by deadbeef84** [comment]
Would be nice if we could track this in a new issue, do you want to create one?

**Comment by mekya** [comment]
Yes, sure. I've create this one above.
