### ISSUE TITLE
Micro freeze in FMLE RTMP streams

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2095]

**Comment by mekya** [comment]
What I figure about this issue is sampling rate. 

When we publish a stream(H264 and AAC(Sampling rate: 12Khz)) through RTMP , there are so many freezes in the WebRTC playing. However everything is almost perfect in the controlled environment. 

Then we figure out that sampling rate of the video is 12Khz and it causes this problem. When we encode the audio with 44.1, it plays smoothly.   This issue will be resolved in 2.1 and it's already resolved in 2.1-SNAPSHOT. 

If you use older versions, please make sure that your sampling rate is 44.1 Khz.

**Comment by vattisampath** [comment]
Hi @mekya its good to see someone using fmle with antmedia. Didnt find much articles with fmle and antmediaserver.

i m trying to stream RTMP from FMLE but couldnt connect to my server and getting below error.
Can you please help me in finding out the reason for below in connecting to AMS server.. ?
I got same error in both 2.1 and 2.0 versions too.

![image](https://user-images.githubusercontent.com/38237181/88383763-bd38f000-cdc8-11ea-97e6-24b44cca651d.png)

hoping for some help in this regard. thanks in advance.

**Comment by mekya** [comment]
Hey @vattisampath ,

Generally the issue about FMLE is not about connecting, it's related to the user experience.

I think, there is a problem in url or in installation or maybe configuation. 

* Please check that you're using correct RTMP URL. What is the url you're using?
* Make sure that you're using H264 (Baseline) and AAC for encoding.

**Comment by vattisampath** [comment]
Thanks @mekya for quick reply.

Ya I missed AAC for audio. I m using default mp3 which is coming with FMLE. How can we add aac audio codec to FMLE .. ?

Is it mandatory to use only AAC, cant we make it work with MP3 audio codec .. ?

**Comment by mekya** [comment]
Hey @vattisampath ,

It can work with MP3(Not tested too much) because the industry uses AAC for years. I think you can also use OBS for streaming. Because FMLE is discontinued 

Anyway,  I've find a doc for you about that. Take a look at "Setting Up FMLE Audio Encoding" . You can change from MP3 to AAC.  Check this out. https://community.jisc.ac.uk/system/files/22983/Flash%20Media%20Live%20Encoder%20Audio%20Only%20Broadcast%20Guide.pdf

**Comment by vattisampath** [comment]
Thanks @mekya 

Yes its working with mp3 also.. But suddenly today when i started again from FMLE. I got the same error for the first time but when tried after little time, it got connected without any change from my side.

I didnt get any clue why it throw error first time and worked fine after few minutes. 
Do you have any idea on this kind of issue.. ? Is it happening because of FMLE or something on server to do. ?

Note I m still using Trail version of license. Please let me know if you have any idea on this error occuring sometimes .

Thanks in advance and its really helping me to understanding better.

**Comment by mekya** [comment]
Hey @vattisampath ,
Could you provide server logs(/usr/local/antmedia/log/ant-media-server.log) with the time of occurrence and stream id?

Regards
