### ISSUE TITLE
Bug in Peer.html

### ISSUE THREAD

**Issue by maydin** [ant-media/Ant-Media-Server#2109]
iPhone 7 (Firefox), I got the UnSecureContext message.

- Connection is secure(https) and it shouldn't give unsecure context message

**Comment by maydin** [comment]
![scr.jpg](https://images.zenhubusercontent.com/5b09234676f98d26207425f5/1802e2b0-4f28-406b-88c7-352bcab0a8d2)

**Comment by Glfarley** [comment]
Same problem with us. Disconcerting to get this type of warning message.

**Comment by eneskuluk** [comment]
Actually this issue is caused by ios itself. IOS does not permit video camera access to the 3.rd party browsers such as firefox. Only safari can have video camera access.

**Comment by Glfarley** [comment]
Yes, it would save your customers a lot of time if you posted clearly in your documentation that Ant Media on mobile devices works ONLY with Safari, no other browsers.

**Comment by mekya** [comment]
Yes you're right. My colleague is preparing a browser compatibility support matrix for that. 

So I'm closing this ticket now.

**Comment by Glfarley** [comment]
OK, thank you.

Glen Farley

**Comment by mekya** [comment]
THANK YOU
