### ISSUE TITLE
Streams list sorting and preview thumbnails doesn't work

### ISSUE THREAD

**Issue by 350d** [ant-media/Ant-Media-Server#2113]
**Describe the bug**

Any column sorting on my app streams list doesn't work.
In grid mode I don't see any of stream previews created.

**Expected behavior**
I expected sorting will work fine and I can see preview snapshots in grid mode

**Screenshots**

<img width="1053" alt="Screenshot 2020-04-29 12 42 46" src="https://user-images.githubusercontent.com/429208/80583397-d411b580-8a18-11ea-94d9-79670fde161a.png">
<img width="1051" alt="Screenshot 2020-04-29 12 42 37" src="https://user-images.githubusercontent.com/429208/80583408-d7a53c80-8a18-11ea-9e43-1830da897b6c.png">
<img width="1051" alt="Screenshot 2020-04-29 12 42 31" src="https://user-images.githubusercontent.com/429208/80583415-d83dd300-8a18-11ea-8dfd-a2a46ea40e1c.png">

Grid view:

<img width="1056" alt="Screenshot 2020-04-29 12 57 15" src="https://user-images.githubusercontent.com/429208/80583604-189d5100-8a19-11ea-8a15-d54db01a1e9c.png">

Previews in app folder:

<img width="404" alt="Screen Shot 2020-04-29 at 12 59 31 PM" src="https://user-images.githubusercontent.com/429208/80583738-46829580-8a19-11ea-94ff-648909d28f76.png">

**Comment by muratugureminoglu** [comment]
Hi Vladimir, 

We no longer support the grid view.
Best.
