### ISSUE TITLE
Unable to install Ant Media 

### ISSUE THREAD

**Issue by CristianPopp** [ant-media/Ant-Media-Server#2120]
Hello,

I'm unable to install Ant Media server on Ubuntu 16.04 running on VM. 
I have the following message on terminal: 

**_unzip:  cannot find or open [ant-media-server-1.9.1-community-1.9.1-20200112_1622], [ant-media-server-1.9.1-community-1.9.1-20200112_1622].zip or [ant-media-server-1.9.1-community-1.9.1-20200112_1622].ZIP.

No zipfiles found.
There is a problem in installing the ant media server. Please send the log of this console to contact@antmedia.io_**

Tried several times, no success. Everything done according with installation instructions.

* Operating system and version: Ubuntu 16.04
* Java version: opnejdk 1.8.0_252
* Ant Media Server version: 1.9.1 community

Thank you,

Cristian

**Comment by SelimEmre** [comment]
Hi @CristianPopp,
Have you tried according to the AMS installation video? Please check -> 
 https://www.youtube.com/watch?v=Hf8vzteVa04

**Comment by CristianPopp** [comment]
Thank you!

**Comment by SelimEmre** [comment]
Closing this issue. Please re-open it if you need.
