### ISSUE TITLE
REST API sorting VODs do not work with the field names

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2121]
**Describe the bug**
Customer reported bug:
REST API sorting VODs do not work with the current field names as Parameters unlike described in REST API because it does not use correct field names in the sortAndCropVodList in DataStore.java

https://antmedia.io/rest/#/VoD%20Rest%20Service/getVodList

**To Reproduce**
Rest API calls like down below do not sort accordingly but gives run time error
http://192.168.1.23:5080/WebRTCAppEE/rest/v2/vods/list/0/50?sort_by=creationDate&order_by=desc
Or
http://192.168.1.23:5080/WebRTCAppEE/rest/v2/vods/list/0/50?sort_by=vodName&order_by=desc

**Expected behavior**
You get a sorted list based on the field name.

The reason:
 In the sortAndCropVodList in DataStore.java "name" and "date" strings are hard coded for comparison but normally it should get these field names from REST API or Database so when the field names change, this method should not break like present case.

**Comment by unkn19wn** [comment]
hi
is this method only enterprise edition ?
i have commercial edition and none of [search,sort and order_by] works

**Comment by golgetahir** [comment]
No it is a generic method that is under ant media server repository it should work with both. Can you write your steps of how you are trying to get it to recreate it on our end also your version.

**Comment by unkn19wn** [comment]
http://IP:PORT/WebRTCApp/rest/v2/broadcasts/list/0/50?sort_by=status&order_by=desc

@golgetahir
