### ISSUE TITLE
In play.html restart playing automatically after publish stopped and restarted

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2122]
A customer request:
**Is your feature request related to a problem? Please describe.**
In play.html after publishing from webRTC and then playing it in play.html. If you stop the stream and restart publishing it again, you need to refresh the play.html web page to watch the video but we want it to start playing automatically after publishing restarted.

**Describe the solution you'd like**
After video restart to be stream, the video should appear in the play.thml web page. 
This can be implemented for example by automatically refreshing the web site programatically after some time if the video is not playing.

**Additional context**
Tested in Chrome and Firefox, this feature is not present currently.

**Comment by mekya** [comment]
If the playOrder is only [webrtc in this doc](https://github.com/ant-media/Ant-Media-Server/wiki/Embedded-Web-Player), it restarts playing. 

The sample url is something like

http://server_address:5080/WebRTCAppEE/play.html?id=stream1&playOrder=webrtc

So closing this issue for now.
