### ISSUE TITLE
Data Channel Webhook doesn't work in publisher side

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2141]
**Describe the bug**
Data Channel Webhook works only player side.

**To Reproduce**
1. Enable Data Channel both of the publisher&player side.
2. Add `settings.dataChannelWebHook` in application settings
3. Restart AMS
4. Open and try to send a message, publisher and player sample pages in the application.

**Expected behavior**
 Data Channel Webhook should work in publisher side.

**Additional context**
Ant Media Server Enterprise Edition 2.0 version.

**Comment by chai2** [comment]
+1 - experiencing the same issue. Any recommendations on how to resolve this?

**Comment by mekya** [comment]
Could you please just update the version and try again?

**Comment by chai2** [comment]
Thanks for the response @mekya 

I'm on version: Enterprise Edition 2.1.0 20200720_1328. We are using AWS Marketplace image. 

Mind telling me how do I can update to the latest version?

**Comment by mekya** [comment]
We have some plans for auto-update however it's not available yet. 

Basically, you just need create a new instance and copy your db files(usr/local/antmedia/*.db) and configurations file(/usr/local/antmedia/conf/red5.properties and /usr/local/antmedia/webapps/*/WEB-INF/red5-web.properties) to the new one.  

Sorry for the inconvenience.

**Comment by chai2** [comment]
Got it. Thats not that bad to just copy these files. While it will be awesome to do auto-update, but that's fine for now. 

Thanks for the info.

**Comment by mekya** [comment]
Thank you

**Comment by chai2** [comment]
Confirmed, working as expected after upgrading to 2.2.1

**Comment by mekya** [comment]
Perfect. Thank you for letting us know.
