### ISSUE TITLE
VP8 Recording

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2144]

**Comment by maydin** [comment]
<div>Agent ahmet oguz mermerkaya linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/5830">5830</a> for this issue.</div>

**Comment by maydin** [comment]
<div>Agent ahmet oguz mermerkaya created comment. </div></br><div style="font-family:-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif; font-size:14px">
<div dir="ltr">
<div dir="ltr">Hi Arun​,</div>
<div dir="ltr">
<br>Thank you for reaching out.</div>
<div dir="ltr">​<br>
</div>
<div dir="ltr">Yeah you're right VP8 recording feature. It's a critical feature as you mention. </div>
<div dir="ltr">MKV cannot be used for VP8 recording in Ant Media Server right now.</div>
<div dir="ltr">​<br>
</div>
<div dir="ltr">I've created an issue for VP8 recording in next release.  <a href="https://github.com/ant-media/Ant-Media-Server/issues/2144" rel="noreferrer">Check this out</a> </div>
<div dir="ltr"><br></div>
<div dir="ltr">Btw, shall we have deal with you about your scaling? I mean you can be happy about that. You'll get the latest VP8 recording feature soon and cut your licenses cost.  </div>
<div><br></div>
<div dir="ltr"><div>Looking forward to hearing from you soon.</div></div>
<div><br></div>
<div>
<span style='font-family: -apple-system, system-ui, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'>PS: Free one-to-one support and consultancy for your streaming project, please book at </span><a href="https://calendly.com/antmedia/call" rel="noreferrer" style='box-sizing: border-box; background-color: rgb(255, 255, 255); color: rgb(44, 92, 197); font-family: -apple-system, system-ui, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'>https://calendly.com/antmedia/call</a>
</div>
</div>
<div dir="ltr">
<div><br></div>
<div style="box-sizing: border-box; word-break: break-word">Regards,<div>A. Oguz</div>
</div>
</div>
</div>

**Comment by maydin** [comment]
<div>Agent ahmet oguz mermerkaya unlinked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/5830">5830</a> from this issue.</div>
