### ISSUE TITLE
Rotate incoming videos according to frame rotation value in adaptive streaming

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2160]
When mobile devices are sending streams, each frame has a rotation value. When the rotation has changed, encoder does not rotate the video on the fly. It causes wrong rotation. 

This problem occurs when adaptive streaming is enabled.  It works in SFU mode.

**Comment by maksym-dukov** [comment]
+1
Having issue this issue.

**Comment by mekya** [comment]
Hi @maksym-dukov 
The problem is being fixed with this issue
https://github.com/ant-media/Ant-Media-Server/issues/6099

FYI
