### ISSUE TITLE
Low Audio in Android SDK when playing a stream

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2161]
**Describe the bug**
A customer reported that the audio level is too low when playing a stream in Android SDK 

**Expected behavior**
Audio level can be similar to be published streams audio or the audio level when played in Web (in according with mobile phone speaker capacities.)

**Smartphone (please complete the following information):**
Android SDK Xiaomi A3

Analysis and possible Solution:
After a lot of constructive help from the customer, it is suspected that that volume was actually not low rather right audio device is not selected, speaker mode was off and audio was playing from earpiece during the video call.
The reason likely is that AppRTCAudioManager is disabled for mode==play, but AppRTCAudioManager.java doesnt seem to be involved in recording, its for playing the sound and it takes care of routing to proper audio device.
 _if (peerConnectionParameters.audioCallEnabled) { ... }_
Initializing the AppRTCAudioManager always by commenting above if condition in WebRTCClient inside init method seems to work but it needs to be tested.

**Comment by AndroidTNTU-3** [comment]
Hi.
Could you let me know if you solved this issue?
Because I have the same problem.
I have noticed that if a user moves the system Media data volume control to the maximum value the audio volume level becomes normal. In case a user uses the Call volume control it has no effect.

**Comment by mekya** [comment]
Hi @AndroidTNTU-3,

I think the problem on your end may be about the enabling the speaker. 
If you still have the same problem, I think it's not something that we can think about improving the experience.
