### ISSUE TITLE
To be able stream to multiple Periscope Accounts for the same stream

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2162]
A customer wants this feature request. 
Currently,  it is not possible to stream to many periscope accounts from the same stream. I verified this when helping a customer. He can authenticate to multiple periscope accounts but he cannot add both periscope accounts to the same stream. 
It only allows to add latest authenticated periscope account to the stream but this customer wants to stream same published stream to his multiple periscope accounts in the same time.

**Comment by shadowlerawr** [comment]
Bump

**Comment by mekya** [comment]
PSCP is already discontinued and we are removing the Periscope support from the server. Moreover, we no longer maintain direct integration with social medias. Ant Media Server continue to support adding any RTMP endpoint including(youtube, facebook, instagram, vimeo, etc.)

So closing this issue.
