### ISSUE TITLE
Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by RobyHTS** [ant-media/Ant-Media-Server#2185]
I got this error When I compile your latest iOS AntMediaSDK with my project.

Xcode Version: 11.3
Language : swift 5

Kindly help me to fix this problem with same Xcode version. 
Thanks in advance.

**Comment by Viktor84** [comment]
Hi
You need  Xcode 11.4.1

**Comment by RobyHTS** [comment]
Thanks for the information. 
What about latest Xcode version 11.5?

**Comment by Viktor84** [comment]
I do not know that.
My version Xcode 11.4.1

**Comment by RobyHTS** [comment]
@Viktor84 Its working good with Xcode 11.5.
