### ISSUE TITLE
Add new server users to web management panel

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#219]
* Create 3 level of privileges READ, WRITE, ADMIN
* Add new user via web panel with its level
* Registered user can login to web panel and perform their operations
* User can change password
* Admin users can add/remove/update password for the other users
* User with READ, WRITE privileged cannot add/remove/update password for other users

**Comment by rwblackburn** [comment]
@mekya  - This would be hugely helpful to our project. Has there been any updates on the likelihood of this being added?

**Comment by mekya** [comment]
@rwblackburn  thank you for your comment. 

We don't get too many requests for this feature. Just a few users have asked this feature. So that it's not scheduled for a specific release for now. 

Hint:  I mean if you make your friends(about 10 people) ask this feature to contact@antmedia.io, I think we can schedule it for next release. 😜  Please don't use bots for that  😇

**Comment by rwblackburn** [comment]
@mekya  - I'll see what I can do :)

What would a change like this entail? If someone can point us in the right direction I might be able to have someone on my team do it (or myself if I can get some free time int he next few months)

**Comment by mekya** [comment]
@rwblackburn, you're great. 

It will be perfect. I can point you in the right direction.  I think I can make some analysis and write some documentation  here to let you make the implementation. 

It sounds ok for you?

**Comment by rwblackburn** [comment]
Thanks @mekya  that would be helpful.

**Comment by mekya** [comment]
Thank you @rwblackburn .

Here are the basic points from my point of view 

I think we should first handle the backend which is this repo -> https://github.com/ant-media/ManagementConsole_WebApp/

We should do the changes in this service [RESTService](https://github.com/ant-media/ManagementConsole_WebApp/blob/master/src/main/java/io/antmedia/console/rest/RestService.java).

Only ADMIN user should have the right to call the following methods
-  `Result addUser(User user)` :  User object should have a field for the level.

WRITE access 
- `String changeSettings(@PathParam("appname") String appname, AppSettings newSettings)`
- `String changeServerSettings(ServerSettings serverSettings)`
- `Result resetBroadcast(@PathParam("appname") String appname)` 
- `String changeLogSettings(@PathParam("level") String logLevel)`

Other changes
- `Result addUser(User user)`: There should be a field in User object that specify the level of the user "Admin", "Write", "Read"
- `Result addInitialUser(User user)`: The first user should be "Admin"
- `Result authenticateUser(User user) `: We should add level of the user to the Session. So that we can check this session value in other methods.

New methods to implemented
- `Result editUser(User user)`: To change user password or e-mail. It should be only called by ADMIN
- `Result deleteUser(User user)`: To delete user. It should be only called by ADMIN
- `List<User> getUserList(int offset, int batch)`: To return users. It should be only called by ADMIN. `offset` the start index of the list, `batch` the number of users to return

After that, we can do the changes in the frontend. At this repo -> https://github.com/ant-media/ManagementConsole_AngularApp/

How does it sound for you?

**Comment by golgetahir** [comment]
Above referenced PRs for both frontend and backend

**Comment by shubik22** [comment]
Just wanted to check on the status of this.  This feature would be awesome to have (I'm currently using Ant Media Server via Ant's offering on AWS).

Are the two above open PRs the only remaining work to enable multiple accounts?

**Comment by mekya** [comment]
Hi @shubik22 ,
Yes these PRs the only remaining work to enable multiple accounts. They have not been merged into the master and they will be available in v2.3.2

We're about to release v2.3.1

**Comment by shubik22** [comment]
Thank you @mekya!  Looking forward to this functionality.

**Comment by rjmtldo** [comment]
Hi @mekya  how can we add this to our antmedia dashboard multiple accounts? i saw already the update on my account antmedia 2.3.2

**Comment by mekya** [comment]
Hi @rjmtldo ,

Full working version of this is not available in v2.3.2. There are some other PRs to be merged into the master. 
I am going to try to review and merge them to the master. I hope it'll be available in 2.3.3. We're likely release 2.3.3 in a couple of weeks.

**Comment by rjmtldo** [comment]
thanks @mekya

**Comment by rjmtldo** [comment]
@mekya  is it possible to push this on version 2.3.3?

**Comment by mekya** [comment]
Yes I've something to finish on my end. After that I'm going to merge other related PR.

**Comment by rjmtldo** [comment]
@mekya  just wanted to ask if these features included in the latest release 2.3.3.1?

**Comment by mekya** [comment]
Yes it's available in 2.3.3.1

Check this out  `Settings > Users`

<img width="1401" alt="Screen Shot 2021-06-15 at 11 18 48" src="https://user-images.githubusercontent.com/3456251/122018435-88140280-cdcb-11eb-9e23-7b7cb72dd579.png">

**Comment by rjmtldo** [comment]
thanks mekya

**Comment by vimalpremkumar** [comment]
Hi @mekya  ,Is there any option to show only particular application to a user. ie for user "A" only LiveApp should be accessible and for USER "B" WebRTCApp should be accessible. ?
