### ISSUE TITLE
NullPointerException in WebRTCEncoderAdaptor.java:666

### ISSUE THREAD

**Issue by Coderah** [ant-media/Ant-Media-Server#2193]
Hi there, we just had a live event, `Enterprise Edition 1.9.1 20200112_1830` crashed repeatedly during a show (10+ times) it seemed to enter a crash loop once it started, had to reboot ec2 instance but it continued crashing.

only thing that changed since last time that worked well, was fixing our IOS safari client (it wasn't loading data properly before, and disabling HLS streaming as we do not rely on it at all, is it possible either of those things triggered the error below?

what seems to be the main cuplrit in logs:
```
java.lang.NullPointerException
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.getWebRTCPublisherStats(WebRTCEncoderAdaptor.java:666)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.lambda$null$0(WebRTCEncoderAdaptor.java:700)
Exception in thread "network_thread - 26802"

#
# Fatal error in: gen/sdk/android/generated_external_classes_jni/jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 37
# last system error: 101
# Check failed: !env->ExceptionCheck()
# Service killed by signal 6
```

though there is also plenty of:
```
SEVERE: Failed to call onClose method of POJO end point for POJO of type [io.antmedia.enterprise.streamapp.WebSocketLocalHandler]
```

**Comment by mekya** [comment]
Yeah we've fixed this issue in last week. You can ask the latest snapshot(2.1.0-SNAPSHOT)

**Comment by mekya** [comment]
Closing this issue. Please re-open if it's not working for you
