### ISSUE TITLE
WebRTC play doesn't work in Samsung Internet browser

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2196]
**Describe the bug**
WebRTC play doesn't work in Samsung Internet browser.

**To Reproduce**
1. Enable both of VP8 and H.264 Encoders
2. Enable 1 Adaptive stream. 
3. Open your Samsung Internet browser, you will see WebRTC player doesn't play. 

**Expected behavior**
As you can see in this [link](https://caniuse.com/#search=webrtc), WebRTC should play in Samsung Internet browser.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 4.4.2
 - Browser: Samsung browser

**Additional context**
AMS EE 2.0.0 version is using.

**Comment by josermorales** [comment]
Maybe it has something to do with compatibility

[https://caniuse.com/#search=media%20source%20extensions](https://caniuse.com/#search=media%20source%20extensions)

**Comment by mekya** [comment]
Yeah it maybe true. We just have not confirmed yet.

**Comment by mekya** [comment]
Test 1:
- Samsung Internet Browser(11.2.1.3) on Galaxy S5 - Android 6.0.1 
- AMS Version -> Enterprise Edition 2.1.0-SNAPSHOT 20200530_1845 
- Status: Passed

Test 2:
- Samsung Internet Browser(11.2.1.3) on Galaxy S5 - Android 6.0.1 
- AMS Version -> Enterprise Edition 2.0.0-20200504_1748
- Status: Passed

I couldn't confirm this case. I'll try another device. It's likely running Android 4.4

**Comment by mekya** [comment]
In Android 4.4.2, Samsung Internet version is 1.5.28. 
According the compatibility matrix(https://caniuse.com/#search=webrtc), there is no exact info about that. It shows that Samsung Internet 4 has WebRTC support. Samsung Internet 4 has 0.94 global usage. Samsung Internet 1.5 is likely very less. 

If this is the case, it does not seem reasonable to spend time for supporting Samsung Internet 1.5 running in Android 4.4.2.

**Comment by mekya** [comment]
@SelimEmre , can you confirm the Samsung Internet version. Maybe I miss something.

**Comment by SelimEmre** [comment]
Yes, I confirmed. It's not working in Samsung Note II (GT - N7100)

**Comment by mekya** [comment]
This problem turns out to be a h264 encoder profile in some old Samsung devices. 
AFAIK WebRTC should supports baseline(42e01f). But this samsung device only h264 profile is 42e015 likely main or high. So that it does not decode the incoming video. 

This problem does not exist in Android 6 and S 5 or similar devices. 

Anyway here is a workaround for this problem, only enable VP8(disable h264) in Ant Media Server
