### ISSUE TITLE
Start recording button for live streams in web panel

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2210]
An enterprise customer wants to have button for stream recording for each stream in the web panel because it is not comfortable for novice customers to use REST API for this purpose. MP4 recording check box will also not help in his use case:
"I will have multiple streams publishing simultaneously and I want to stop and start recording each one at different times so the MP4 checkbox won't work for this use case"

**Comment by Glfarley** [comment]
Any progress on this feature request? We could benefit greatly from it and we were told it is very little work to add it.

**Comment by mekya** [comment]
Hey @Glfarley ,

I've just added this to our backlog and schedule for v2.2.

When this ticket is assigned to one, it means it's scheduled at that week.

**Comment by Glfarley** [comment]
Any progress on this feature?

**Comment by SelimEmre** [comment]
Hi @Glfarley,

It's already implemented. You can use this feature in v2.2. 

Check also -> https://github.com/ant-media/ManagementConsole_AngularApp/pull/88
