### ISSUE TITLE
Remove 8081 websocket support from server

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#222]
- Delete related pom dependencies
- Delete releated bean definitions under settings file in conf directory and apps

**Comment by mekya** [comment]
Update this doc 
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Details

is it ok @roeycohen ?

We are moving all documentation to wiki. It is much more easy for CRUD.

**Comment by roeycohen** [comment]
seems great :)
