### ISSUE TITLE
Support JWT for Token in Stream Security

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2239]

**Comment by HesselTjeerdsma** [comment]
The current one-time token implementation is insecure. It makes it possible for user to share a one-time token by sharing their JSESSIONID cookie. A solution using JWT would be better, this way the stream authentication system in Antmedia could become way more extensible. 

My suggestion of implementation would look like this:
- An API endpoint for generating, listing and deleting private signing keys is developed
- Antmedia only stores the public key, and relies on a external application to generate the JWTs.
- Antmedia checks for every request if the JWT is valid (so properly signed and not expired), and then checks some fields that could be defined in the JWT, like request IP is the IP added extra field in JWT etc.
