### ISSUE TITLE
obfuscation of license operations and codes

### ISSUE THREAD

**Issue by davutcavdar** [ant-media/Ant-Media-Server#226]
* red.xml licenceservice initialization
* json key file
* engine class and db url

**Comment by maydin** [comment]
Lisanslama konusunda yaptigim arastirlamalarda bu konuya fazla takilmayin, cok ugrasmayin, eninde sonunda kirilacaktir diyor. Zaten su an kullanici sayimiz cok degil, bu o yuzden o kadar da bir problem degil. Cok oldugunda hackerlarin ilgisini cekecek hale geldiyse zaten o zaman dusunuruz ama yapacak cok da fazla birsey yok, windows her turlu kiriliyor mesela. Ama simdilik basit de olsa bir onlem almak gerekirse sunlari yapabiliriz:

1)kullanicidan input alarak key verme:
Kullanicinin mac id'sini alip bir key verebiliriz. Acilista o key'i lisanslama modulumuz ile okuyup valid mi degil mi bakabiliriz. Key icine key'in gecerli oldugu tarih araligini ve mac id'sini gomeriz. Kullanici bu key'i bir xml icine koyabilir. Lisanslama modulumuz mac id ile key'deki mac id karsilastirir ve gecerlilik tarih araligi icerisinde ise bir dosya olusturur. o dosya her acilista kontrol edilir.dosya icerisine o makineye ait lokal bir bilgi de kayit edilir boylece kopyalanmasi durumunda calismaz. bu dosyalarin icerigini sifreleyerek olusturabiliriz. bu dosya varsa devam eder sunucu. evet mutlaka kirilabilir ama son kullanicilara yetecektir.

2) kullanicinin adi soyadi gibi bilgileri alip kullaniciya ozel bir build vermek. Lisanslama modulumuz bu bilgiler ile derlenir (c/C++ ile tercihen) . about kisminda mesela kullanicinin adi soyadi gozukur .Boylece kullanici dagitirsa yazilimi internette, kim oldugu belli olur. 1.maddeye ek olarak bu madde de yapilabilir. 

3) internet varsa her yeni bilgisayar bizim sunucuya ben aktive oldum diye mesaj gonderebilir. boylece o kullanicinin kac tane bilgisayara yuklemeye calistigini da gorebiliriz.

Lisanslama modulunun kodunu korumak icin iki yontem uygulanabilir:
1) Proguard ile obfuscation yapilabilir. Bu sadece crackerin isini biraz zorlastirabilir.
2) Lisanslama modulunun kodunu c/c++ ile yazip JNI ile kullanabiliriz. c/C++ in decompile edilmesi daha zor olur.

referans:https://stackoverflow.com/questions/2642259/looking-for-a-license-key-algorithm

**Comment by mekya** [comment]
Teşekkurler @maydin 

Peki diyelim ki lisanslama kısmını karıştırdık bir şekilde. Lisanslama modülü olmadığında veya olumsuz döndüğünde diğer kısımların çalışmamasını nasıl sağlayabiliriz?

**Comment by maydin** [comment]
lisanslama bean red5 startup'da c++ kutuphanesine input verilebilir. o kutuphane de duruma gore birsey doner.o bean cikartirsa proje compile olmaz bu durumda.cikartilmasini engellemis oluruz.  o dondugu sey red5 startup icin gerekli birsey olabilir , birseyin path'i olabilir, basit birsey olabilir. amac biraz zorluk cikartmak sadece. 

http://docs.hazelcast.org/docs/3.0/manual/html/ch12s08.html
Hazelcastte calisan bir arkadasa sordum nasil yaptiniz diye. Decompile edilebilir, cracklenebilir dedi. Bu sadece bir uyari dedi. Bu arkadas zorlastiralim diye onermis, gerek yok demisler.

**Comment by maydin** [comment]
Bazi kodlar spring boot'a da tasinabilir:https://spring.io/guides/gs/securing-web/
