### ISSUE TITLE
Fatal error in platform_thread.cc

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2261]
**Describe the bug**
We encountered this error with the WebRTC play stress tests. We opened 8 core machines (C2-30). We encountered this error when WebRTC play count reached 470 viewers.

**To Reproduce**
1. We added a 240p adaptive option.
2. One publisher sent with a test.mp4 file which is a load test resources file.
3. After some minutes, Ant Media Server can't handle the overload.

**Additional context**
Ant Media Server EE 2.0 version. There are no other error related this issue.

```
#
# Fatal error in: ../../rtc_base/platform_thread.cc, line 87
# last system error: 11
# Check failed: 0 == pthread_create(&thread_, &attr, &StartThread, this) (0 vs. 11)
# 

```

**Comment by mekya** [comment]
Thank you for reporting the bug. 

In our tests we identified that this problem happens in 18.04. [Check this reddit enty](https://www.reddit.com/r/linuxadmin/comments/adyk43/what_change_between_ubuntu_1604_and_1804_is/)

Quick fix is just adding `TasksMax=20000` after `RestartSec=5s`  in this file `/lib/systemd/system/antmedia.service`.  
After that reload the systemd and restart the service
```
sudo systemctl daemon-reload
sudo service antmedia restart
```
Fix will be available for 2.1

Two news. Maybe we're late about that. On ther hand, late is better than never. 
1. We'll optimize the number of threads
2. We'll add load test to our pipeline(no manual work) as we did for fully functional cluster tests
