### ISSUE TITLE
IP camera: pull RTSP via REST API

### ISSUE THREAD

**Issue by creimers** [ant-media/Ant-Media-Server#2280]
I would like to use ant media server to forward an ip camera via webrtc:

```
ip camera ==> ant media server ==> webrtc ==> browser
```

In my current setup, I'm using ffmpeg inbetween the camera and ant media server. However, according to the [docs](https://github.com/ant-media/Ant-Media-Server/wiki/IP-Camera):

> Ant Media Server can pull RTSP streams from IP Cameras easily [...].

That's cool 😎.

It is my understanding that this can be done via the [REST API](https://antmedia.io/rest/). Specifically, it seems to me that `/v2/broadcasts/create` is the endpoint I'd want to `POST` to. I can, however, not get it to work. Here's what I've been trying to post:

```json
{
    "streamId": "RGB_1",
    "type": "ipCamera",
    "name": "RGB_1",
    "description": "ding dong",
    "publish": true,
    "date": 1589445937380,
    "plannedStartDate": 0,
    "duration": 0,
    "endPointList": [
        {
            "type": "string",
            "broadcastId": "string",
            "streamId": "string",
            "rtmpUrl": "string",
            "name": "string",
            "endpointServiceId": "string",
            "serverStreamId": "string"
        }
    ],
    "publicStream": true,
    "is360": false,
    "listenerHookURL": null,
    "category": "string",
    "ipAddr": "192.168.1.102",
    "username": null,
    "password": null,
    "quality": null,
    "speed": 0.0,
    "streamUrl": "rtsp://192.168.1.102:8554/unicast",
    "originAdress": "127.0.1.1",
    "mp4Enabled": 0,
    "expireDurationMS": 0,
    "rtmpURL": "rtmp://127.0.0.1/WebRTCAppEE/RGB_1",
    "zombi": true,
    "pendingPacketSize": 0,
    "hlsViewerCount": 0,
    "webRTCViewerCount": 0,
    "rtmpViewerCount": 0,
    "startTime": 0,
    "receivedBytes": 0,
    "bitrate": 0,
    "userAgent": "string",
    "latitude": null,
    "longitude": null,
    "altitude": null,
    "mainTrackStreamId": "string",
    "subTrackStreamIds": [
        "string"
    ]
}
```

Can you point me in the right direction? Thanks!

**Comment by mekya** [comment]
Hey @creimers ,

The simple form is like this

Make a request to the following endpoint. Please read the [REST Guide in advance especially for IP filtering](https://github.com/ant-media/Ant-Media-Server/wiki/REST-Guide#security--ip-filtering).
```
 http://YOUR_SERVER:5080/WebRTCAppEE/rest/v2/broadcasts/create?autoStart=true
```

Your request can be something below.  It's added as a stream source in the below example.  Make sure that your stream Url is accessible from the server's network. Because it's local ip address and you need to run the server in the same network. 
```
{
    "streamId": "hello",
    "type":"streamSource",
    "streamUrl":"rtsp://192.168.1.102:8554/unicast"
}
```

**Comment by mekya** [comment]
Closing this issue. Please re-open if it does not work for you.
