### ISSUE TITLE
Check Firefox Mobile Compatibility

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2286]
### Short description
Firefox Mobile does not play the WebRTC Stream

### Environment
* Samsung Galaxy 7
* Samsung Note
* Firefox Mobile : 68.9.0

### Steps to reproduce
1. Publish stream from iOS through native application to Ant Media Server
2. Try to Play the stream in Galaxy 7 and Note in Firefox Mobile

### Expected behavior
It should play

### Actual behavior
It does not play
 
Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by bomiteva** [comment]
Hello I have a problem with Firefox 77.0.1 does not play the WebRTC Stream. I'm using AntMedia Server Instance on AWS . This is works on Chrome and Safari.
![image](https://user-images.githubusercontent.com/15668141/86251303-5bff7180-bbba-11ea-9675-3c76e934756f.png)
this is my web page:

<!DOCTYPE html>
<html>
<body>

<h2>Ant Media</h2>

<iframe width="560" height="315" src="http://<SERVER_IP>:5080/WebRTCAppEE/play.html?id=132607746147676128290239&token=383125e7869597cfe696d00a3d2c57a217b06fa4de8a844f39bdbb791ef73a4e" frameborder="0" allow="autoplay 'src'; fullscreen"></iframe>


</body>
</html>

and also receive `No event.candidate in the iceCandidate event` like https://github.com/ant-media/Ant-Media-Server/issues/2295

And question if we using AntMedia in how to upgrade the software when you have new release ? This is EC2 instance.

**Comment by tekoma** [comment]
Same issue here with an AWS EC2 instance running.

It starts playing some video cache when the stream is stopped. but doesn't start when the stream starts again.

Browser: Firefox 77.0.1 (Mac/PC)
Enterprise Edition 2.0.0 20200504_1748.

**Comment by bomiteva** [comment]
yes abs the same ```It starts playing some video cache when the stream is stopped. but doesn't start when the stream starts again.```

**Comment by burak-58** [comment]
According to this:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs
>  _ Firefox for Android 68 and later do not support AVC (H.264) anymore. _

But I tried the FF beta from Google Play, it worked for me.

**Comment by tekoma** [comment]
Thank you, burak-58
But I can't tell clients to install a beta Version of whatever. I feel like I am stuck to the IE 6 problems with css in the 90th. 
How do I get an EC2 Ant Media Low Latency Instance running on all Browsers?

**Comment by burak-58** [comment]
You can use the VP8 codec instead of H.264 to support all browsers.
