### ISSUE TITLE
./enable_ssl.sh does not remove old crontab entries

### ISSUE THREAD

**Issue by k0nr4d** [ant-media/Ant-Media-Server#2296]
### Short description
When ./enable_ssl.sh is executed, it grabs the ssl certificate from letsencrypt and creates the following crontab entry:
00 03 */85 * * cd /usr/local/antmedia && ./enable_ssl.sh -d host.domain.com -r

If the domain is changed after the fact, it does not remove the old entries and we end up with several crontab entries:
00 03 */85 * * cd /usr/local/antmedia && ./enable_ssl.sh -d old.domain.com -r
00 03 */85 * * cd /usr/local/antmedia && ./enable_ssl.sh -d new.domain.com -r
00 03 */85 * * cd /usr/local/antmedia && ./enable_ssl.sh -d third.domain.com -r

Since all 3 get executed at the same time, we may end up with the wrong SSL certificate being installed if all the domains in question resolve to the same server.

Additionally, if a certificate is provided manually to ./enable_ssl.sh there probably shouldn't be a crontab task for updating it via letsencrypt to begin  with. This I haven't tested so it may not be the case but if I installed a wildcard certificate for *.domain.com I suspect that it would get overwritten by letsencrypt.

### Environment
Linux CentOS 7 & Ubuntu 18
AntMedia Enterprise Edition 2.1.0-SNAPSHOT 20200609_0637
Also occurred on latest stable release prior to updating to snapshot.

### Steps to reproduce
1.  ./enable_ssl.sh -d old.domain.com
2.  ./enable_ssh.sh -d new.domain.com
3. Both domains will have crontab entries.

### Expected behavior
Should remove older crontab entry in order.

### Actual behavior
Does not remove older crontab entry.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by muratugureminoglu** [comment]
Hi, thanks for your feedback. We 've solved this issue in the next release.
Best.

**Comment by mansouralex** [comment]
@muratugureminoglu we are facing the same issue, how we can solve it without upgrading to the new release?

**Comment by muratugureminoglu** [comment]
Hi @mansouralex 

If you can use the latest enable_ssl.sh script, your problem will be resolved. 

Here is a link;
[https://raw.githubusercontent.com/ant-media/Ant-Media-Server/master/src/main/server/enable_ssl.sh
](https://raw.githubusercontent.com/ant-media/Ant-Media-Server/master/src/main/server/enable_ssl.sh
)
You can just copy the script to /usr/local/antmedia and then run enable_ssl.sh script.
Best.

**Comment by mekya** [comment]
@mansouralex let us know if it's working for you

**Comment by mansouralex** [comment]
@mekya @muratugureminoglu thank you, yes it's working as expected.

**Comment by mekya** [comment]
Great to hear that. Closing this issue then. 

Let us know if we can help you for anything
