### ISSUE TITLE
Extend API to cover server information

### ISSUE THREAD

**Issue by k0nr4d** [ant-media/Ant-Media-Server#2297]
**Is your feature request related to a problem? Please describe.**
The REST API does not allow me to request system information that is returned in the Antmedia dashboard by "/rest/getSystemResourcesInfo"

**Describe the solution you'd like**
I would like to be able to request this information via the REST API so that I can monitor system disk, system memory usage and CPU load within my application. 

**Describe alternatives you've considered**
While possible to do this outside of Antmedia, if we have a several dedicated external servers running nothing else except Antmedia it this would allow a quick and easy way to monitor the status of each along with other API requests we may be making.

**Comment by mekya** [comment]
Hi @k0nr4d 
Thank you for your question. 

You can disable authentication by commenting out the following line in `/usr/local/antmedia/webapps/root/WEB-INF/web.xml` 

  ```
  <filter>
    	<filter-name>AuthenticationFilter</filter-name>
   		<filter-class>io.antmedia.console.rest.AuthenticationFilter</filter-class>
  </filter>	
  <filter-mapping>
    <filter-name>AuthenticationFilter</filter-name>
    <url-pattern>/rest/*</url-pattern>
  </filter-mapping>
```

If you also need some kind of authentication, you can use the [Web Panel IP Filtering](https://github.com/ant-media/Ant-Media-Server/wiki/Web-Panel-IP-Filtering)
