### ISSUE TITLE
Codec exception in Android SDK for some devices

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2298]
# Fatal error in: gen/sdk/android/generated_base_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 85
    # last system error: 11
    # Check failed: !env->ExceptionCheck()
 
Preceded by:
W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff3
W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2834)
W/System.err:     at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.releaseOutputBuffer(MediaCodecWrapperFactoryImpl.java:78)
W/System.err:     at org.webrtc.HardwareVideoEncoder.lambda$deliverEncodedImage$0$HardwareVideoEncoder(HardwareVideoEncoder.java:591)
W/System.err:     at org.webrtc.-$$Lambda$HardwareVideoEncoder$F5M8yR9Mkg8WzwHcYIIOdTEImls.run(Unknown Source:4)
        at org.webrtc.RefCountDelegate.release(RefCountDelegate.java:45)
W/rtp_to_ntp_estimator.cc: (line 163): Multiple consecutively invalid RTCP SR reports, clearing measurements.
W/System.err:     at org.webrtc.EncodedImage.release(EncodedImage.java:69)

**Comment by MohdIrfan12** [comment]
I am also getting this issue

**Comment by mekya** [comment]
You may ask to get M85 update for the Android SDK from support team.

We don't merge M85 to master because of some H265 issues.

**Comment by mekya** [comment]
M85 branch is merged into the master
FYI
