### ISSUE TITLE
Are there any instructions on adding IP cameras?

### ISSUE THREAD

**Issue by savageautomate** [ant-media/Ant-Media-Server#23]
Are there any instructions on adding IP cameras?

Anytime I enter an IP camera address on the web ui, it just disappears after pressing the ADD button and no error information is emitted and no streams are added to the listing.  

On the server I see a ConnectException with no host available followed by a NullPointerException.  
Maybe I'm entering the wrong Onvif IP URL?  What should it look like?

I have tried things like:
- http://10.1.2.227:888/onvif/device_service
- http://10.1.2.227:888/onvif
- http://10.1.2.227:888

but none are accepted.

I have installed the latest CE release version from:
https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v1.2.6

Running on Ubuntu 16.04.4 LTS using Oracle Java 8.

**Comment by mekya** [comment]
Hi,

Please take a look at this blog post. Adding IP Camera via web interface is added on 1.3.0+ 

https://antmedia.io/how-to-pull-ip-camera-streams-with-ant-media-server/

If you are still having an issue, please let us know. 

Regards,
A. Oguz

**Comment by mekya** [comment]
Closing this issue. Please let us know if you have any issue.
