### ISSUE TITLE
RTSP log filled with timeouts

### ISSUE THREAD

**Issue by gmoore-sjcorg** [ant-media/Ant-Media-Server#230]
# Issue
Using RTSP as stream source fills error log. 
### Short description
Added RTSP as stream source. Left server running but shut off stream source. Error logs filled with:
[tcp @ 0x7fcb88071180] Connection to tcp://{RTSPIP}:554?timeout=5000000 failed: Connection refused
[tcp @ 0x7fcb94955280] Connection to tcp://{RTSPIP}:554?timeout=5000000 failed: Connection refused

Pulling RTSP from [Crestron STRO](https://www.crestron.com/en-US/Products/Video/DigitalMedia-Modular-Matrix/Output-Cards-Blades/DMC-STRO)

### Environment

[] Operating system and version: Oracle Linux EL7
[] Java version: openjdk version "1.8.0_171"
[] Red5 version: Bundled

### Expected behavior
When stream is active or inactive error log should not fill up.

### Actual behavior
System makes memory and swap space and error log fills.

### Steps to reproduce
1. Install
2. Add stream source
3. Wait

### Logs
[tcp @ 0x7fcb88071180] Connection to tcp://{RTSPIP}:554?timeout=5000000 failed: Connection refused
[tcp @ 0x7fcb94955280] Connection to tcp://{RTSPIP}:554?timeout=5000000 failed: Connection refused

**Comment by davutcavdar** [comment]
Please make sure that your host/firewall inbound and outbound port access configurations are configured properly. Also please share your error log file.

**Comment by davutcavdar** [comment]
Closing this issue, if you still have problems, please re-open.
