### ISSUE TITLE
Unable to re-stream to Azure Media Services RTMP endpoint

### ISSUE THREAD

**Issue by doublepithre** [ant-media/Ant-Media-Server#2316]
### Short description

Unable to stream to Azure  RTMP endpoint
```
[mpegts @ 0x7f4cac919f80] H.264 bitstream malformed, no startcode found, use the video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb' option with ffmpeg)
```
```
[http-nio2-0.0.0.0-5080-exec-2] INFO  io.antmedia.rest.RestServiceBase - IP: xxxxx.channel.media.azure.net
[http-nio2-0.0.0.0-5080-exec-2] INFO  io.antmedia.muxer.RtmpMuxer - rtmp muxer opening: rtmp://xxxxx.channel.media.azure.net:1935/live/xxxxx/tetststtstst time:1594387060063
[webrtc-audio-encoder-teststrtetetete-0] INFO  io.antmedia.muxer.RtmpMuxer - Not writing to muxer because it's not started for rtmp://xxxxx.channel.media.azure.net:1935/live/xxxxx/tetststtstst
[webrtc-audio-encoder-teststrtetetete-0] INFO  io.antmedia.muxer.RtmpMuxer - cannot write frame(not video) to muxer. Error is End of file 
[DecodingQueue - 7107] INFO  io.antmedia.muxer.RtmpMuxer - Frame is not key frame to start
```
### Environment

* Operating system and version: Ubuntu 18.04
* Java version: OpenJDK 11.0.7 2020-04-14
* Ant Media Server version: Enterprise Edition 2.0.0 20200504_1748
* Browser name and version: Chrome 

### Steps to reproduce
1. Turn on H.264 and MP4 recording in the settings
2. Publish the stream using WebRTCEE app
3. Then to the broadcast add Azure Media Services RTMP endpoint (live event) something like **rtmp://xxx-aase.channel.media.azure.net:1935/live/xxxx/test1**

### Expected behavior
The stream should be available on the Azure media service

### Actual behavior
Getting errors 
 

### Logs
[Logs](https://pastebin.com/e7e7ayPn)

**Comment by mekya** [comment]
Hi, 
When we checkout that we could not even send stream to the Azure via ffmpeg. 

I think there is a kind of configuration issue in Azure side. We can schedule this issue to look at that part.

**Comment by doublepithre** [comment]
@mekya Sure, I have some interesting info from Azure support, we can discuss in the call, let's schedule it.

**Comment by mekya** [comment]
Is it possible to schedule a meeting here ? https://calendly.com/antmedia/

Sorry for not providing something very quick. Schedule is really tight.

**Comment by doublepithre** [comment]
Thanks, I will schedule a meeting

**Comment by doublepithre** [comment]
Thanks for the call. Here is the [video](https://x0pa-my.sharepoint.com/:v:/p/bhadra/EaAZfcfLmbVNhr8rJICvC6sB3J-g3i4hKbUXyc-Q8qAVEQ?e=hLKZR5) I used and the command I used is the following
```
ffmpeg -re -i BigBuckBunny.mp4 -codec copy -f flv rtmp://xxxxx.channel.media.azure.net:1935/live/xxxxxxx/teststream1
```

**Comment by mekya** [comment]
Thank you so much. I'll test it

**Comment by mekya** [comment]
Hey @doublepithre ,

I've just sent a fix about the Azure RTMP compatibility.

**Comment by doublepithre** [comment]
@mekya Thanks for the fix. Looking forward to the release after testing.
