### ISSUE TITLE
Recorded Stream using a Mobile phone front Camera gets Distorted

### ISSUE THREAD

**Issue by McBacker** [ant-media/Ant-Media-Server#232]
# Issue
Recorded stream using mobile phone front camera gets distorted
Using notebook's camera the video is fine!

### Short description
1. Brand new installation on AWS using ant-media-server-community-1.3.6.2-180621_2202.zip
2. Recorded using built-in app "WebRTCApp"

### Environment
Ubuntu (t2 medium instance on AWS)

[] Operating system and version: Linux ip-xxxxxxx 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[] Java version: openjdk version "1.8.0_171"
[] Red5 version: Probably red5-io-1.0.9-M2

### Expected behavior
Regular video playback

### Actual behavior
Recorded stream using mobile phone front camera gets distorted

### Steps to reproduce
1. Navigate to https://[dns]:5443/WebRTCApp using a mobile phone
2. Allow audio/camera
3. Click Publish
4. Playback the stream that was recorded

### Logs
![antonaws](https://user-images.githubusercontent.com/7377236/42249572-66973b88-7f02-11e8-9ed6-ede052afa0d8.PNG)

**Comment by davutcavdar** [comment]
Dealing with the issue.

To make it clear ant test : 

Could you please share your server URL?
Do you have a chance to try with another mobile device?
Any error logs in log files?

**Comment by davutcavdar** [comment]
Hi again,
Could you please use latest 1.4.0 snapshot release. Download from the [link](https://drive.google.com/file/d/16TvHFpettW2j0yaZblSkvOPMnOh37HJ8/view?usp=sharing) it will be probably fixed. Please let us know.

**Comment by davutcavdar** [comment]
Let's proceed in this way;
1) Please install the latest release that I have sent in the previous comment. It is community (free) version and installed in the same way.
2) If the problem still exists, please find the log files under /usr/local/antmedia/log location and send them to contact[at]antmedia.io with the server URL.

**Comment by McBacker** [comment]
It's working but, are you sure that the zip provided is free? It says Enterprise Edition in the bottom of the Dashboard...

**Comment by davutcavdar** [comment]
It is a snapshot (pre-release) not release. In 1.4.0 community edition release, your issue will be fixed. Until it is released, you can use that snapshot release then you need to install latest 1.4.0 community edition. 

Closing this issue, if you have a new one please reopen.

**Comment by Osirys25** [comment]
This issue still occurs in 1.5.2 community edition, when our camera is in vertical mode.
