### ISSUE TITLE
Investigate CPU spike 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2322]

**Comment by heldner** [comment]
Hello!

Seems to be, I have the same issue. I have two instances of ant working in clustermode. High CPU usage on one server when ant has no active streams.                                   
 
Only one message in logfile, about 300Mb of this message in minute:
> 2020-07-03 10:18:19,091 [Red5_Scheduler_Worker-26] ERROR o.r.s.stream.RemoteBroadcastStream - java.lang.IndexOutOfBoundsException
>         at java.nio.Buffer.checkBounds(Buffer.java:567)
>         at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:187)
>         at org.apache.mina.core.buffer.AbstractIoBuffer.put(AbstractIoBuffer.java:645)
>         at org.red5.server.stream.RemoteBroadcastStream.sendData(RemoteBroadcastStream.java:345)
>         at org.red5.server.stream.RemoteBroadcastStream$WriteCallback.call(RemoteBroadcastStream.java:228)
>         at org.bytedeco.javacpp.avformat.av_write_frame(Native Method)
>         at org.red5.server.stream.RemoteBroadcastStream.execute(RemoteBroadcastStream.java:451)
>         at org.red5.server.scheduling.QuartzSchedulingServiceJob.executeInternal(QuartzSchedulingServiceJob.java:89)
>         at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
>         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
>         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)


at 05:00 there is no active streams:
![prod-tv-live-3-cpu-load_joined](https://user-images.githubusercontent.com/4851642/87671600-496c6700-c77a-11ea-8a57-c33c28878618.jpg)

**Comment by mekya** [comment]
Hi @heldner ,

It seems that you're using RTMP playback in the cluster mode. It's not deprecated to use RTMP playback.
You can use HLS or WebRTC for playback.  We're also working on LHLS for decreasing the HLS latency.

**Comment by heldner** [comment]
@mekya yes, you are right. I have one client that connected throw rtmp and watch every stream. That client is prepare hls stream and send it to s3.
Thanks for the answer!

**Comment by mekya** [comment]
It's my pleasure. 

Just let me give one more information. It turns out that WebRTC stack has some issues with TCP ICE candidates.
Some threads may consume high CPU in TCP ice candidates. The quick workaround is closing TCP ports for ICE and use UDP for WebRTC playing.
