### ISSUE TITLE
Pixelation in VP8

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2328]
### Short description
Sometimes pixelation can be seen in the player side when only VP8 is enabled without ABR

### Environment

* Operating system and version: macOS/Ubuntu 18.04
* Ant Media Server version: 2.0, 2.1-Snapshot
* Browser name and version: Chrome

### Steps to reproduce
1. Disable H.264 and enable VP8
2. To increase the chance, use conference.html and connect 4-5 participants
3. Wait some minutes

### Expected behavior
Playing stream without any issue

### Actual behavior
Sometimes pixelation can be seen in the player

**Comment by bdaver** [comment]
any news on this ?

**Comment by mekya** [comment]
Thank you for follow up @bdaver. 

It's still under investigation.
