### ISSUE TITLE
Conference doesn't work properly in IOS using Safari browser.

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2336]
### Short description
Conference.html is not working properly ios environment. Users' videos are paused when they connect to the room. When user clicks to play button, video becomes full screen and cannot see other users at the same time.

### Environment

* Operating system and version: Iphone 11-IOS 13.5
* Ant Media Server version:Enterprise Edition 2.1.0-SNAPSHOT 20200717_0932
* Browser name and version:Safari 13.1

### Steps to reproduce
1. Add users to Conference.html
2. See their playback is paused
3. Click to play button on the users.
4. It transitions to full screen which makes impossible to see other users at the same time.

### Expected behavior
User should be able to watch other's playback in small form instead of full screen.

### Actual behavior
Users' playback is paused until played manually and it transitions to full screen.

**Comment by naveedaziz** [comment]
Same here...

**Comment by precision1980** [comment]
It works for me if I connect using the rtmp or the long htttp://domain/LiveApp/{appname}/{identifier}.m3u8

**Comment by mekya** [comment]
I think it's just about adding `playsinline` field to video tag.
