### ISSUE TITLE
iOS App crashes on launch after importing frameworks

### ISSUE THREAD

**Issue by kingsleychuuu** [ant-media/Ant-Media-Server#2339]
### Short description
__Brief description of what happened__

Frameworks were just imported as embedded binaries, app successfully builds and runs, but crashes immediately due to:
```
dyld: Symbol not found: _$s10Starscream16FoundationStreamCAA8WSStreamAAWP
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
  Expected in: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/Starscream.framework/Starscream
 in /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
```

No code has been written yet. The existing project had no issues before this. The frameworks were taken from the sample app. Starscream 4.0.0, and 3.1.1 has been installed already via pods successfully. 

### Environment
* Operating system and version: XCode 11, iPhone XR Simulator iOS 13, Swift
* Java version: N/A
* Ant Media Server version: N/A
* Browser name and version: N/A

### Steps to reproduce
1. Navigate to $(PROJECT_NAME), General Tab > Frameworks, Libraries, and Embedded Content > "+" button > Add Other > Add Files > Select WebRTC.framework and AntMediaSDK.framework in root directory of $(PROJECT_NAME).
2. Command R
3. Crash > Thread 1: signal SIGABRT

### Expected behavior
__Put as much detail here as possible__

iOS App builds normally and does not crash. Nothing else needs to happen yet. 

### Actual behavior
__Put as much detail here as possible__

 iOS App builds normally and crashes due to:
```
dyld: Symbol not found: _$s10Starscream16FoundationStreamCAA8WSStreamAAWP
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
  Expected in: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/Starscream.framework/Starscream
 in /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
```

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

```
dyld: Symbol not found: _$s10Starscream16FoundationStreamCAA8WSStreamAAWP
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
  Expected in: /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/Starscream.framework/Starscream
 in /Users/admin/Library/Developer/CoreSimulator/Devices/807CCDFC-ACD3-497E-B44D-B6E730CE704B/data/Containers/Bundle/Application/8B63650A-76D3-4654-B339-44D8E07A5A39/Bounce.app/Frameworks/AntMediaSDK.framework/AntMediaSDK
```
This is everything in the terminal

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi @kingsleychuuu ,

Thank you for your question. 

In our sample project, there is a pod file and includes the following content.  

```
target 'AntMediaReferenceApplication' do
    platform :ios, '10.0'
    use_frameworks!
    pod 'Starscream', '~> 3.1.1'
end
```
Before starting your application, you need to install pod file. The Symbol not found is about the `Starscream` dependency in the pod file. 

Check this out -> https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by mekya** [comment]
Btw, we start to deliver the iOS and Android SDK through website for free. 
https://antmedia.io/free-webrtc-android-ios-sdk/

We'll also update the iOS documentation later this week.
