### ISSUE TITLE
REST API Not showing

### ISSUE THREAD

**Issue by precision1980** [ant-media/Ant-Media-Server#2341]
**_I am using the following:_**

Community Edition 2.0.0.0
Ubuntu 18.04
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

_**I run the following command from another server:**_

curl -X POST https:/demo.dev.local:5443/LiveApp/rest/v2/broadcasts/create -H 'content-type: application/json' -d '{"name":"test_video1"}'

**_I get the response_**

{"streamId":"931973706888927779581525","status":"created","type":"liveStream","name":"test_video1","description":null,"publish":true,"date":1595255397705,"plannedStartDate":null,"duration":null,"endPointList":null,"publicStream":true,"is360":false,"listenerHookURL":null,"category":null,"ipAddr":null,"username":null,"password":null,"quality":null,"speed":0.0,"streamUrl":null,"originAdress":"10.10.1.120","mp4Enabled":0,"expireDurationMS":0,"rtmpURL":"rtmp://10.10.1.120/LiveApp/931973706888927779581525","zombi":false,"pendingPacketSize":0,"hlsViewerCount":0,"webRTCViewerCount":0,"rtmpViewerCount":0,"startTime":0,"receivedBytes":0,"bitrate":0,"userAgent":"N/A","latitude":null,"longitude":null,"altitude":null,"mainTrackStreamId":null,"subTrackStreamIds":null}

**_I can connect to the stream, it says I am streaming. then I look in the stream and see :+1:_** 
![Screenshot from 2020-07-20 07-25-23](https://user-images.githubusercontent.com/47580398/87949565-08ff3880-ca5b-11ea-9323-c3a4e2bef5ed.png)

**_I look inside of that folder, don't see anything. I look in the Management of Ant and it doesn't show anything. Sometimes it has a difficult time displaying_** 

![Screenshot from 2020-07-20 07-44-18](https://user-images.githubusercontent.com/47580398/87950993-e40bc500-ca5c-11ea-8145-bee67e84b47f.png)

![Screenshot from 2020-07-20 07-33-14](https://user-images.githubusercontent.com/47580398/87949770-4a8fe380-ca5b-11ea-9064-035c4037d29e.png)

**_I look at the REST API and see 3 of broadcasts that I tried_**

![Screenshot from 2020-07-20 07-55-41](https://user-images.githubusercontent.com/47580398/87952258-75c80200-ca5e-11ea-8049-6f0e1ea94539.png)

![Screenshot from 2020-07-20 07-52-43](https://user-images.githubusercontent.com/47580398/87951952-14a02e80-ca5e-11ea-90f7-9af5b5e742b8.png)

![Screenshot from 2020-07-20 07-52-57](https://user-images.githubusercontent.com/47580398/87951956-1538c500-ca5e-11ea-8973-dd3ceeaa64ad.png)

_**It show a down arrow but the arrow doesn't respond. if I stop the service and restart the service it works fine. However, the REST API call on anything i create VOD or Broadcast it will not show up in the system nor will it allow me to watch the stream. if I do it from the web application, no issues.**_

**_When I look at the logs I see this consistently since deployment._**

WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2328 ms, time limit is 2000
Jul 20, 2020 2:57:06 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3328 ms, time limit is 2000
Jul 20, 2020 2:57:20 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2241 ms, time limit is 2000
Jul 20, 2020 2:57:21 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3241 ms, time limit is 2000
Jul 20, 2020 2:57:36 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2806 ms, time limit is 2000
Jul 20, 2020 2:57:37 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3807 ms, time limit is 2000
Jul 20, 2020 2:57:51 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2734 ms, time limit is 2000
Jul 20, 2020 2:57:52 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3734 ms, time limit is 2000
Jul 20, 2020 2:58:06 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2561 ms, time limit is 2000
Jul 20, 2020 2:58:07 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3561 ms, time limit is 2000
Jul 20, 2020 2:58:21 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2331 ms, time limit is 2000
Jul 20, 2020 2:58:22 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3331 ms, time limit is 2000
Jul 20, 2020 2:58:37 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2877 ms, time limit is 2000
Jul 20, 2020 2:58:38 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3877 ms, time limit is 2000
Jul 20, 2020 2:58:52 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2311 ms, time limit is 2000
Jul 20, 2020 2:58:53 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3311 ms, time limit is 2000

**Comment by precision1980** [comment]
Here is another issue I am finding with REST API

**Comment by mekya** [comment]
Hey @precision1980 ,

Are you using some kind of slash at the end of the stream id?

I mean if you're streaming to `rtmp://demo.dev.local/LiveApp/streamid_39393/` or `rtmp://demo.dev.local/LiveApp/streamid_39393/some_other_value`, it may cause this problem.

It should exactly be something  `rtmp://demo.dev.local/LiveApp/streamid_39393` - No slash at the end. 

Please just check and let us know about that.
