### ISSUE TITLE
Update AWS Marketplace Image for 2.1

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2345]

**Comment by shprota** [comment]
Any progress on that? When can we expect the updated image?

**Comment by mekya** [comment]
We've already sent the AMI to the AWS Marketplace. I think it may take a couple of days to appear in the Marketplace.
@burak-58

**Comment by danielbiagi** [comment]
Do I need to create another instance from Marketplace or my enterprise edition instance can be upgraded somehow?
Thanks

**Comment by muratugureminoglu** [comment]
Hi, 
Yes you need to create a new instance. 

Best.
