### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by precision1980** [ant-media/Ant-Media-Server#2358]
REST API's are very useful. I don't see one a GET for listing all STREAMS or VOD. That would be helpful

**Comment by mekya** [comment]
Hey @precision1980 ,

There is one for streams at here -> https://antmedia.io/rest/#/BroadcastRestService/getBroadcastList

One for vod at here ->  https://antmedia.io/rest/#/VoD%20Rest%20Service/getVodList
