### ISSUE TITLE
Enable Record Live Streams as MP4. After stop publishing a stream by OBS software, the preview image doesn't upload to S3 storage.

### ISSUE THREAD

**Issue by MinhHungTrinh** [ant-media/Ant-Media-Server#2359]
### Short description
Enable Record Live Streams as MP4. After stop publishing a stream by OBS software, the preview image doesn't upload to S3 storage.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: Enterprise Edition 1.9.1 20200112_1830
* OBS software: OBS Studio 25.0.8 (64 bit)

### Steps to reproduce
1. Configure S3 config in  **/usr/local/antmedia/webapps/WebRTCAppEE/WEB-INF** file. Follow this guide: **https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration**
2. Add Adaptive Streaming in Ant media console management
3. Publish stream by OBS software, check it's preview image in **/usr/local/antmedia/WebRTCEEApp**, have a preview image of that stream
3. Then, Stop that stream. Preview image doesn't upload to S3 storage. But, if I publish stream by WebRTC in my Website, preview uploaded to S3 storage.

### Expected behavior
Preview image upload to S3 storage when I published both OBS software and WebRTC on my website. 

### Actual behavior
Preview image doesn't upload to S3 storage when I publish stream by OBS. But Preview image uploaded to S3 storage when I published stream by WebRTC on my Website

**Comment by MinhHungTrinh** [comment]
Sorry, i'm wrong. Because I deleted the VOD of that preview.

**Comment by mekya** [comment]
Thank you for closing this issue.
