### ISSUE TITLE
Make Flutter WebRTC Solution for Android

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2374]

**Comment by lumec** [comment]
same here

**Comment by mekya** [comment]
Thank you for your comment @lumec 

@eneskuluk is currently working on this issue .

**Comment by mrhmamun** [comment]
Any progress? eagerly waiting....

**Comment by mekya** [comment]
WebRTC Flutter is ready for testing. You can ask at google group https://groups.google.com/g/ant-media-server and some one in ant media can provide the link to download for you.
