### ISSUE TITLE
Mongodb connect issue

### ISSUE THREAD

**Issue by nilava** [ant-media/Ant-Media-Server#2383]
### Short description
Cant connect to mongodb replica set on cloud atlas

https://cloud.mongodb.com/

### Environment

* Ubuntu 18.04 & Latest Enterprise Edition

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcat.cluster' defined in class path resource [jee-container.xml]: Cannot create inner bean 'io.antmedia.enterprise.cluster.ClusterStore#6cf0e0ba' of type [io.antmedia.enterprise.cluster.ClusterStore] while setting bean property 'clusterStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.antmedia.enterprise.cluster.ClusterStore#6cf0e0ba' defined in class path resource [jee-container.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.antmedia.enterprise.cluster.ClusterStore]: Constructor threw exception; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=ant-media.1dy4f.azure.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: ant-media.1dy4f.azure.mongodb.net: No address associated with hostname}, caused by {java.net.UnknownHostException: ant-media.1dy4f.azure.mongodb.net: No address associated with hostname}}]

**Comment by mekya** [comment]
Thank you for the report. 

It the log it says something 

java.net.UnknownHostException for ant-media.1dy4f.azure.mongodb.net

There may be a kind of DNS issue?

**Comment by nilava** [comment]
thats what i initially though, however looks like it cant connect to replica set

using this standalone code works, should i modify the db connect file and build one from source? or is there something i am doing wrong?

```
MongoClientURI uri = new MongoClientURI(
    "mongodb+srv://admin:<password>@ant-media.1dy4f.azure.mongodb.net/<dbname>?retryWrites=true&w=majority");

MongoClient mongoClient = new MongoClient(uri);
MongoDatabase database = mongoClient.getDatabase("test");

```

**Comment by mekya** [comment]
Thank you. I try to check it out at weekend.

**Comment by mekya** [comment]
My colleague(@muratugureminoglu ) will look into this.

Before that, I should mention that in order to connect to replicaSet. db.host url should be set to something like this.

`db.host=<mongo_host>:27017/?replicaSet=<replication_name>`

**Comment by nilava** [comment]
Tried everything with no success.

**Comment by mekya** [comment]
Hi @muratugureminoglu , 
Do you have some chance for trying that?

**Comment by burak-58** [comment]
Hi @nilava,
Could you please try it again after changing _change_server_mode.sh_ file with [this one](https://github.com/ant-media/Ant-Media-Server/blob/mongoReplicaConnection/src/main/server/change_server_mode.sh).

**Comment by nilava** [comment]
Sure, will try it out, right now we have moved to production use with local mongo db instance with no replica set. 
Will spin up a new test instance and test it out.

**Comment by choxnox** [comment]
I'm facing similar issues when trying to run the EE in cluster mode and when Mongo is hosted at Mongo Atlas. I've also tried the suggested `change_server_mode.sh` script but to no avail.

<img width="1680" alt="Screen Shot 2020-09-16 at 11 17 47" src="https://user-images.githubusercontent.com/1287099/93304627-5a833400-f80e-11ea-9926-dffae2852280.png">

It works just fine when I spin up MongoDB instance in DigitalOcean but when I try to use Mongo Atlas service, it simply fails. I've tried with the following:
- cluster0.xxxxx.mongodb.net
- cluster0-shard-00-00.xxxxx.mongodb.net:27017,cluster0-shard-00-01.xxxxx.mongodb.net:27017,cluster0-shard-00-02.xxxxx.mongodb.net:27017/replicaSet=atlas-yyyyyy-shard-0
- cluster0-shard-00-01.xxxxx.mongodb.net

I'm able to connect to the Mongo Atlas cluster with any of the above URIs using MongoDB Compass app or any other Mongo management app.

**Comment by choxnox** [comment]
@mekya Any inputs on this?

**Comment by mekya** [comment]
Re-opening issue and it'll be scheduled again in this week.

**Comment by burak-58** [comment]
For MongoDB Atlas, the following works for me:
`./change_server_mode.sh cluster 'mymongotestcluster-shard-00-00.xxxxx.mongodb.net:27017/?ssl=true&replicaSet=atlas-yyyyyy-shard-0' user pass`

**Comment by choxnox** [comment]
> For MongoDB Atlas, the following works for me:
> `./change_server_mode.sh cluster 'mymongotestcluster-shard-00-00.xxxxx.mongodb.net:27017/?ssl=true&replicaSet=atlas-yyyyyy-shard-0' user pass`

This is what I get when I execute that for my Mongo Atlas cluster (v2.1 EE):

<img width="411" alt="Screen Shot 2020-10-19 at 18 57 26" src="https://user-images.githubusercontent.com/1287099/96468328-08826380-123d-11eb-9d2a-84b20661ea1c.png">

**Comment by choxnox** [comment]
However, this seems to work: 

```
./change_server_mode.sh cluster 'mymongotestcluster-shard-00-00.xxxxx.mongodb.net:27017\/?ssl=true\&replicaSet=atlas-yyyyyy-shard-0' user pass
```

Notice the "escaped" slash and ampersand characters.
