### ISSUE TITLE
Internal IP not registered instead public IP registered in cluster

### ISSUE THREAD

**Issue by nilava** [ant-media/Ant-Media-Server#2384]
### Short description
Clustering doesn't use internal IP, but public IP instead! 

### Environment

* Ubuntu 18.04 & Latest Ant Media EE

### Expected behavior
{
    "_id" : "7479c287-98e3-47c3-992e-6c0a690db54a10.0.0.3",
    "className" : "io.antmedia.cluster.ClusterNode",
    "ip" : "10.0.0.3",
    "lastUpdateTime" : NumberLong(1596827616295),
    "cpu" : 1,
    "memory" : "586/1945"
}

### Actual behavior
{
    "_id" : "7479c287-98e3-47c3-992e-6c0a690db54a88.99.187.xxx",
    "className" : "io.antmedia.cluster.ClusterNode",
    "ip" : "88.99.187.xxx",
    "lastUpdateTime" : NumberLong(1596827616295),
    "cpu" : 1,
    "memory" : "586/1945"
}

88.99.187.xxx is my servers public IP and 10.0.0.3 my servers internal IP

**Comment by mekya** [comment]
Hey @nilava,

Thank you for your question. 

There is a property with name `useGlobalIp`  in conf/red5.properties. Its default value is `false`.  It means that AMS uses the the value return by `InetAddress.getLocalHost().getHostAddress();`

I think it returns your public IP address. Maybe taking a look at the `/etc/hosts` file or some kind arrangements in the your linux box may make `InetAddress.getLocalHost().getHostAddress();` return  your private address.

**Comment by nilava** [comment]
Ohh, after seeing the config found the issue, my server is not behind a NAT, the adapter IP is the public IP unlike AWS where adapter ip is a private one, however my system has private IP's as different adapter, is it possible to make use of it?

**Comment by mekya** [comment]
[Documentation of `InetAddress.getLocalHost()` says that](https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#getLocalHost--) 

>Returns the address of the local host. This is achieved by retrieving the name of the host from the system, then resolving that name into an InetAddress.

I think if you set hostname and its equivalent value to /etc/hosts, it's may return the ip address you want. I've not tested before.  I'm just thinking loudly.

**Comment by nilava** [comment]
Instead i just set the private IP's in the database and so far it works good.

**Comment by mekya** [comment]
I see. 
Somethings may need you to enter private IP's again such as server restart, etc.

**Comment by nilava** [comment]
@mekya Seems like it, for now closing the issue. Would be a great addition in future if we could specify the ip or adapter to use for clustering.
