### ISSUE TITLE
WebRTC playback

### ISSUE THREAD

**Issue by bradleat** [ant-media/Ant-Media-Server#24]
# Issue

I am streaming to the WebRTCApp using OBS and rtmp.

My intent is to be able to connect WebRTC clients ant media server. However, I am unable to follow this tutorial:

https://github.com/ant-media/Ant-Media-Server/blob/master/doc/WebRTC_Publish_and_Play_JavaScript_SDK_Details.md

I cannot locate the `<script src="js/webrtc_adaptor.js" ></script>`.

Moreover, `<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>` creates an undefined webRTCAdaptor object.

Were this tutorials meant for the Enterprise version of the software?

### Environment

[] Operating system and version: Ubuntu LTS
[] Java version: (as instructed)
[] Red5 version: (as instructed)

**Comment by mekya** [comment]
Hi @bradleat ,

Yeah Playing with WebRTC clients can be done in Enterprise version. 

We may provide the latest snapshot version(1.4.0-SNAPSHOT) to you to test enterprise edition. 

Regards,
A. Oguz

**Comment by mekya** [comment]
Closing this issue. Please reopen if you have any further issue.
