### ISSUE TITLE
can't send 2Gb more networks

### ISSUE THREAD

**Issue by sg-studio** [ant-media/Ant-Media-Server#2404]
### Short description
__Brief description of what happened__

can't transfer 2Gb more networks

### Environment
AWS EC2 
* Operating system and version:  Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1032-aws x86_64)
* Java version: openjdk 11.0.8
* Ant Media Server version: v2.1 ( enterprise version )
  - origin c5.2xlarge
  - edge c5.9xlarge
  - test client c5n.xlarge ( 4ea ) + c5.24xlarge ( 1ea )
* Browser name and version: load test tool

### Steps to reproduce
1. send rtmp to origin server
  - rtmp information : 1080p / 30fps / 8000kbps
2. execute load test tool to edge server
  - c5n.xlarge amount = 50 * 4
  - c5.24xlarge amount = 100
3. show video 

### Expected behavior
__Put as much detail here as possible__

calculate send networks is 2.4Gb
but, edge server send network is less than 2Gb ( about max 1.8Gb )

### Actual behavior
__Put as much detail here as possible__

 edge server max network is 1.8Gb and video is delayed
I capture server monitor and video play

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

![image (2)](https://user-images.githubusercontent.com/11473699/90205135-841afb00-de1d-11ea-90e9-e466652e89b4.png)
![image (3)](https://user-images.githubusercontent.com/11473699/90205359-94cb7100-de1d-11ea-836f-1c369af6a865.png)
![image (4)](https://user-images.githubusercontent.com/11473699/90205432-9b59e880-de1d-11ea-97e1-0eee9e619122.png)
![capture](https://user-images.githubusercontent.com/11473699/90205913-c17f8880-de1d-11ea-99cc-491fb17c0e6b.JPG)

edge server network bandwidth test results are normal.
![image (5)](https://user-images.githubusercontent.com/11473699/90215321-47a7c900-de36-11ea-92de-df1df1ec5a90.png)

**Comment by sg-studio** [comment]
I have a question

I would like to know criteria for cost calculator in your homepage. ( rtmp infomation / bitrate / frame / resolution )
have been testing. but, don't show 32 Core CPU Instance 1200viewer / 400 broadcasts

**Comment by mekya** [comment]
Hi @sg-studio ,

Thank you for testing and reporting to us. 

Do you help us understand the case and locate the problem?

For instance, just for testingMake client side same 300 and if you decrease bitrate to 1000Kbps, you see 300Mbps throughput?
Keep the bitrate 1000Kbps and decrease the number of viewers from 300 to 50, you see 50mbps throughput? 

I mean I just want to find a working case for you. It creates highlight to understand the bottleneck.

One other thing is that we don't support Java 11 yet.

**Comment by sg-studio** [comment]
Hi @mekya 

I appreciate your answer.

I explain further this testcase.

ex1 ) bitrate 1000Kbps * client 300 = 300Mpbs
ex2 ) bitrate 1000Kbps * client 50 = 50Mbps
is good. this is the intended content.

In my test case, need more throughput.
>case )
>1. **Bitrate 8000Kbs**
>2. **client 300**
>3. **Expect throughput is 2.4Gbps**
>
>**But, My results are 1.8Gbps**

Like the screenshot attached before.  ( Check the client player, My broadcast computer time is faster than player time about 3minutes delayed )
if I reduce client 100, video time restore. ( delay is lower than 1second ( 8000Kbps * client 200 = 1.6Gbps ) )
My machine's network was suspicious, so I tested the bandwidth and it worked fine. ( I attached this test screenshot before )
**If throughput is higher than 1.8Gbps, video play gradually slows down. I think that looks like a bottleneck because the throughput is not enough**

additionally, I test another testcase
case 1)  **6000Kbps * 400client = 2.4Gbps**
**but, results is 1.8Gbps**
case 2) **4000Kbps * 600client = 2.4Gbps**
**but, result is same**

To solve this, do I need to change other settings?
Or is that bottleneck?

Java version is AWS default installed version.

( 32 Core CPU Instance 1200viewer / 400 broadcasts  ) is reference your homepage ( [part. cost-calculator](https://antmedia.io/cost-calculator/) )
I would like to know this test case.

I'm not good at English, but if you need more information, please tell me.
