### ISSUE TITLE
Cant't install media server on Windows 10

### ISSUE THREAD

**Issue by Omercanyt** [ant-media/Ant-Media-Server#2410]
I cant make "start.sh" work in my windows 10. Is there any .bat file and after doing this just need to replace rtmp address in mainactivity then it should work right ?

**Comment by mekya** [comment]
Hi,
Ant Media Server works in linux and mac. Windows is not supported. 

You can use ubuntu VM on your windows box. 

Closing this issue because we don't have plan to support windows.
