### ISSUE TITLE
Wrong reply from signalling server on webrtc play

### ISSUE THREAD

**Issue by prashantspandey** [ant-media/Ant-Media-Server#2428]
Hi I trying to play webrtc stream through ant media server signalling
according to docs:
Client sends play JSON command to the server with stream name parameter. (Remove token parameter if token control is not enabled)

```
{
    command : "play",
    streamId : "stream1",
    token : "tokenId",

}
If Server accepts the stream, it replies back with offer command
{
   command : "takeConfiguration",
   streamId : "stream1",
   type : "offer",
   sdp : "${SDP_PARAMETER}"
}
```
I am sending the play command to the server but in return I am getting candidates rather than an offer sdp.
Here is the example:
I am sending:
```
{"command":"play","streamId":"teacher_live"}

in return I am getting :
{
  "candidate": "candidate:2768984285 1 tcp 1518280447 172.31.60.229 41537 typ host tcptype passive generation 0 ufrag 7XMn network-id 1",
  "streamId": "teacher_live",
  "label": 1,
  "id": "video",
  "command": "takeCandidate"
}

```
instead I should be getting an sdp offer according to the docs.
Without the offer sdp I can't set the description and send the answer back.
Please solve this bug.

**Comment by eneskuluk** [comment]
Could you provide the steps to reproduce?
Commands are exchanging asynchronously. 
So, There should be no need for waiting it, you need to take necessary actions as they transmitted to you. 
As an example: 
* We can take a look to the index.html: https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/index.html#L328

```
callback : function(info, obj) {
					if (info == "initialized") {
```
It is listening for call back and asynchronously executing the commands.
