### ISSUE TITLE
After configuring recording to S3 have an option to remove mp4 files from local disk

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2429]
An Enterprise customer wants this feature as convenience: " I think that I could have an option to remove the mp4 files from the local folder after uploading to S3."

**Comment by eneskuluk** [comment]
This is already behaving in this manner. As you can see from this code segment:
* ```
   else if (event.getEventType() == ProgressEventType.TRANSFER_COMPLETED_EVENT){
				try {
					Files.delete(file.toPath());
  ```
   *  It is already deleting the uploaded folder.

Could you clarify the question if possible?
Is what you are asking is having an option to toggle on or off it?
Regards.

**Comment by canat** [comment]
I also checked the code. It seems that the problem which that customer had was likely related to the permissions or wrong configuration. This issue can be closed.
