### ISSUE TITLE
Audio lagging in webrtc enterprise edition

### ISSUE THREAD

**Issue by nagendraK6** [ant-media/Ant-Media-Server#2430]
### Short description
Hello Team Antmedia,
   We are using enterprise edition and using webrtc for broadcasting. Some of our users are reporting that the audio and video are out of sync. The audio got delayed. When they closed the browser and rejoin then it fixes for some of these users. For some of these users, it is working fine.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:Enterprise Edition 2.0.0 20200504_1748
* Browser name and version: Chrome

### Steps to reproduce
1.  Setup a server with enterprise edition Enterprise Edition 2.0.0 20200504_1748
2. Broadcast from webrtc sample code provided by antmedia
3. View from the webrtc sample code by other users (chrome)

### Expected behavior
__Put as much detail here as possible__

Video and audio for same stream must be in sync.

### Actual behavior
__Put as much detail here as possible__
Audio of the stream get delayed
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by nagendraK6** [comment]
@mekya  Sorry for explicit tagging you. We went to beta last week and started seeing this problem. Does the proximity of the video server to webrtc consumer (receiver) can play important role? In my case publisher is in calfornia, aws server is in california but receiver is in asia. In once the stream is published we show the same stream to other user in california and didn't face this issue.

**Comment by mekya** [comment]
No worry. I'm joining a meeting for now. I'll answer your question soon.

**Comment by mekya** [comment]
Hi @nagendraK6 , yeah proximity of the videoserver to webrtc consumer is critical. In your case, the distance is not small. For having better experience, using a second instance in Asia will help you a lot. 
You can install a cluster with two instances as shown here  -> https://antmedia.io/cluster-on-aws-from-different-geolocations/

**Comment by nagendraK6** [comment]
Thanks for suggestion. I will try this and let you know the experience.

**Comment by eneskuluk** [comment]
Hello @nagendraK6 , this issue has been assigned to me this week.
As you mentioned in your comment, have you had any chance to try the suggestion for your issue? 
If so, how was your experience? 
It would be good to to confirm this issue if it is still exists or not.
Best Regards,
Enes Kuluk.

**Comment by nagendraK6** [comment]
We can close this for now. It happens in a bad network but then recovers itself.
