### ISSUE TITLE
Bug wrong rotation value in watching stream on social media 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2431]
1. Send a stream to Ant Media server with portrait mode in iOS Safari
2. Make the stream publish to the Facebook Live Stream
3. Watch the stream

Expected: 
Stream should be in correct rotation

Actual:
Stream is rotated 90 degrees

**Comment by salsaweb** [comment]
Hello,

We are facing same issue for Android App and also for **web examples**.

**Steps to reproduce the behavior:**
1.  open in iPhone browser (safari, chrome) https://mydomain.com/WebRTCAppEE/ and publish broadcast
2. open in laptop browser https://mydomain.com/WebRTCAppEE/play.html?name=stream1&playOrder=hls it's important to set playOrder to HLS
3. as a result you will see video in rotation

we are using **Enterprise Edition 2.2.1 20201029_2042**

**Comment by mekya** [comment]
Yes you're right. I've answered a response to your issue. 
https://github.com/ant-media/Ant-Media-Server/issues/3614
