### ISSUE TITLE
Audio Switch which Conference n Laptop not working

### ISSUE THREAD

**Issue by rahulkent** [ant-media/Ant-Media-Server#2450]
### Short description
Audio Switch which Conference n Laptop not working

### Environment

* Operating system and version: Windows 10
* Java version: Angular 9/ JS SDK
* Ant Media Server version: 2.1 Enterprise
* Browser name and version: Chrome Latest

### Steps to reproduce
1. Start a Conference call.
2. Plug Headphones to Laptop
3. Try changing Audio Input/Output

### Expected behavior
Audio should Switch from Headphones to Laptop Audio even if Headphones are inserted.

### Actual behavior
Audio switching do not happen. But this works fine over Mobile. Issue comes on Laptop.
Tried with Normal as well as Bluetooth headphones but issue remains.
 

### Logs

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
Hi @rahulkent

I tried to recreate the issue with HS300 Bluetooth device. Which is working quite fine for the audio input. Can you check if your system can locate the device?



![Screenshot from 2020-10-27 11-23-51.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/ba20b2e6-ec3c-48c3-9fc5-a30e1a9b0d1e)

![Screenshot from 2020-10-27 11-24-15.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/043e3ac5-6ccd-40d0-ab52-d16f80e5d432)
