### ISSUE TITLE
How to solve NotSetRemoteDescription Error

### ISSUE THREAD

**Issue by martandmadhwani** [ant-media/Ant-Media-Server#2451]
I'm gettting NotSetRemoteDescription while same streamId connected twice.

When this error happens? can any once help me on this?

**Comment by eneskuluk** [comment]
This is caused if streamer sends vp8 and server only accepts h.264(or opposite), this error occurs. 
As a summary, this occurs when streaming media is not set with same parameters in the client and server side. 
If you want to solve this, you can activate the vp8 option in the Ant Media Server Dashboard. Please check the following screenshot:
![image](https://user-images.githubusercontent.com/54481799/93469245-e8d3e480-f8f8-11ea-9dca-a6f06a6292b0.png)
When you select the vp8, click the save button at the bottom.
But if you want both vp8 and h264 to be playable in client side, you need to add adaptive bitrate.

**Comment by Codeboys-hugo** [comment]
I have the same problem.

Set Ant Media as in the picture. It works fine on most devices and players.

But with Huawei p30 using Chrome mobile it doesn't work.

If in the Huawei p30 I use Firefox or Edge it works correctly.

Do you know if there is something I need to configure to work with Chrome on the p30?

**Comment by Codeboys-hugo** [comment]
After 24 hours of leaving the image settings, it started working in Chrome with Huawei p30. It seems that even if the configuration is saved and the ant media server is restarted, it does not take the change until several hours later.

In case someone has the same problem with the configuration of the image, it is solved.

**Comment by mekya** [comment]
hi @Codeboys-hugo ,
It's glad to hear that it's working for that. 

Generally, the settings are effective immediately for new started streams in Ant Media Server. I think there may be some other issue somewhere that may cause this problem. 

Anyway, I'm happy to see that it's working for you. Let us know if we can help further.
