### ISSUE TITLE
Cannot start stream - Enterprise 2.1.0

### ISSUE THREAD

**Issue by pippu** [ant-media/Ant-Media-Server#2452]
* After starting a small number of streams (5-6), the server starts throwing "publish_timeout" errors.
* Logs show several attempts at "Waiting for encoder to be ready for merged-7237 hash:1207506407"

Waiting ~5-10 minutes (or restarting Ant Media server) resolves the issue.

### Environment
Ant Enterprise 2.1.0
Using AWS Marketplace AMI ("Ant Media Server Enterprise- Low Latency Adaptive WebRTC, RTMP, MP4, HLS")
No changes made to server, configuration or security-groups

### Logs
https://pastebin.com/rG6nXiTS

**Comment by prashantspandey** [comment]
Same here, Did you find any solution? Today mine doesn't even resolve after restarting the server

**Comment by pippu** [comment]
> Same here, Did you find any solution? Today mine doesn't even resolve after restarting the server

Nope :-(

**Comment by sacel** [comment]
Same issue on Azure VM Ubuntu 1804

**Comment by doublepithre** [comment]
same issue here

**Comment by mekya** [comment]
Thank you for the report. Sorry for late reply. We'll schedule this issue for this week.

**Comment by SelimEmre** [comment]
Hi @pippu,

Is this the same issue with #2517?

**Comment by SelimEmre** [comment]
Hi @pippu,

It seems your IceCandidate messages couldn't complete. The main reasons are listed below.
1. UDP Port's(5000-65000) close.
2. A firewall is preventing to WebRTC Handshake.

Please make sure on the list.

**Comment by mekya** [comment]
Do you still have this problem? @pippu @sacel @prashantspandey 

If yes, we just need to reproduce the problem with the same scenario. Please provide the scenario step by step including instance type etc.
