### ISSUE TITLE
Sample Data Channel Example

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2454]
For customers, a sample data channel example could be useful. Such as image transfer through data channel.

**Comment by sbokatuk** [comment]
there is a sample in Android SDK source code, but it not functioning, said "Data channel not ready", can anybody help to get running sample?

**Comment by eneskuluk** [comment]
Could you confirm that you enabled data-channel in sdk and  in Ant Media Server dashboard?

**Comment by sbokatuk** [comment]
I confirm that I enabled Data channel on Server, also I checked, by default
on iOS and Android sample app it's set to "true" but I still have "data
channel is not ready"

we set up sample server, and even make trial license for it, you can check
our server:

https://antmedia.drmtm.us:5443/#/dashboard/overview
<https://www.google.com/url?q=https%3A%2F%2Fantmedia.drmtm.us%3A5443%2F%23%2Fdashboard%2Foverview&sa=D&sntz=1&usg=AFQjCNG_U70v__bSfhnEKXTkw0I6IvjWjg>
user: sbakatsiuk
password: qpF7b2Bp2QbhmKp

Thanks in advance,
Sergey
