### ISSUE TITLE
Finishing iOS RTMP reference app

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#246]

**Comment by ogulcan** [comment]
Completed, ready to review and test: https://gitlab.com/Ant-Media/RTMPiOSReferenceApp

**Comment by Base2526** [comment]
@ogulcan url 
<img width="1280" alt="screen shot 2561-07-14 at 22 18 27" src="https://user-images.githubusercontent.com/900211/42725786-dc17896c-87b3-11e8-9864-e79625ae8de3.png">

**Comment by mekya** [comment]
Review

Status:Live background
Close button at the bottom
Bigger buttons

**Comment by ogulcan** [comment]
Updated all issues.
