### ISSUE TITLE
Add screen share feature in conference sample page

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2462]
Some of our customers wants to add screen share feature in conference.html sample page.

**Comment by SelimEmre** [comment]
Also, solve this bug while developing this feature -> https://groups.google.com/g/ant-media-server/c/UfAYge3BDTk/m/O6Rv6oM7AAAJ

**Comment by mekya** [comment]
New issue is created for the bug report coming from community.  https://github.com/ant-media/Ant-Media-Server/issues/2520
