### ISSUE TITLE
Bug in Publish interface

### ISSUE THREAD

**Issue by Glfarley** [ant-media/Ant-Media-Server#2465]
I have an external webcam plugged in but I am just streaming from the built-in webcam on my laptop. Under Options I have chosen the correct Audio source: Microphone (Conexant SmartAudio HD). There is sound. If I unplug the external USB webcam, the sound from the internal microphone stops in the stream. I need to refresh the Publish page and start again. This bug is more of an inconvience than anything else, but someone could end up killing the sound in the one stream without knowing it by unplugging the unused camera.

**Comment by eneskuluk** [comment]
Thank you for the report, i will try to reproduce this on my end as soon as possible.

**Comment by eneskuluk** [comment]
I couldn't reproduce the same issue on my end.
What i did: Connect external webcam,
Select internal webcam for both video and audio,
Start streaming for 10 seconds and test whether video and audio has no issue on the player side,
Unplug the external webcam,
Check wheter audio has issues or not,
There is no issues and i can still hear my voice in the player.

I also tested this with external microphones and had no issues.

Is there anything i'm missing?
Regards.

**Comment by Glfarley** [comment]
Hi Enes,

It must have been an intermittent issue. Now we are live and streaming
several streams from two laptops so I can't try to reproduce the problem.
You can just close this ticket.

Glen Farley
