### ISSUE TITLE
how flip camera view like 90 degree 

### ISSUE THREAD

**Issue by niteshfel** [ant-media/Ant-Media-Server#2470]
how flip camera view like 90 degree  because in front camera is showing mirror image in some device ,  that's why any method for change angle in 90 degree . am using android SDK and when i am broadcasting video using RTMP then my left hand showing on right side and right hand showing on left hand  just like a mirror issue . please help me how can i solve this issue.

**Comment by niteshfel** [comment]
have any solution for this issue , because when i using front camera and showing some alphabets on screen then all alphabets showing me like a mirror image , in back camera its showing me perfect.
i am using this : https://github.com/ant-media/LiveVideoBroadcaster
for RTMP broadcast

**Comment by niteshfel** [comment]
I think problem have in this method

 public int getCameraDisplayOrientation() {
        Camera.CameraInfo info =
                new Camera.CameraInfo();
        Camera.getCameraInfo(currentCameraId, info);
        int rotation = context.getWindowManager().getDefaultDisplay()
                .getRotation();
        int degrees = 0;
        switch (rotation) {
            case Surface.ROTATION_0: degrees = 0; break;
            case Surface.ROTATION_90: degrees = 90; break;
            case Surface.ROTATION_180: degrees = 180; break;
            case Surface.ROTATION_270: degrees = 270; break;
        }

        int result;
        if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
            result = (info.orientation + degrees) % 360;
            result = (360 - result) % 360;  // compensate the mirror
        } else {  // back-facing
            result = (info.orientation - degrees + 360) % 360;
        }
        return result;
    }

**Comment by eneskuluk** [comment]
Could you confirm that in which devices you have this issue?

**Comment by niteshfel** [comment]
I am using Motorola E4 device and many more device have this issue

**Comment by niteshfel** [comment]
Also you can check on these devices : Samsung m31 , vivo andopppo

**Comment by eneskuluk** [comment]
Is there any device this correctly works?

**Comment by niteshfel** [comment]
I think no , all new devices have same issue using front camera same mirror issue.

**Comment by niteshfel** [comment]
How much time you take solve this issue ? @eneskuluk

**Comment by eneskuluk** [comment]
I have been digging this issue and it seems this is default behivour of the front facing cameras. Looking for viable solutions.

**Comment by niteshfel** [comment]
Thanks i waiting for this any kind of solution, if we use front camera then work perfect like back camera

**Comment by eneskuluk** [comment]
I have digged this issue and requires many modifications which includes the rendering style. 
Could you try using the Android WebRTC SDK? Currently, it is in higher priority in development wise and probably don't have this issue.
You can check it here:https://antmedia.io/free-webrtc-android-ios-sdk/
Regards.

**Comment by niteshfel** [comment]
Yes please so fix as soon possible , I don't need webRTC i need RTMP broadcast so please fix this front camera issue .

**Comment by eneskuluk** [comment]
Hello, as i mentioned in my previous comment, it needs heavy modifications on how things are rendered and it goes deeper than i anticipated.

Sorry for the inconvenience, we will try to plan this in the future when the time is appropriate.

But, this would take some time to plan and fix it.
Since it is open-source, you can try to work on it.

As a last question, is there any specific reasons to not use Android WebRTC SDK?

**Comment by niteshfel** [comment]
Ok i am still waiting for solution.

**Comment by niteshfel** [comment]
How much more time will you take for this solution? @eneskuluk @mekya @maydin @dvmarcilio @antmedia-bot

**Comment by ThirupathiMukkera** [comment]
> Also you can check on these devices : Samsung m31 , vivo andopppo

I am also facing this issue on samusung, asus and vivo on these devices, did you get any solution

**Comment by mekya** [comment]
It seems that this issue is about LiveVideoBroadcaster. 

We don't have resources to maintain LiveVideoBroadcaster. You're welcome to fix the issues and make PR.
Sorry for that.  

Alternative solution is about using our WebRTC SDK as my colleague recommends.

So closing this issue.

**Comment by smaldd14** [comment]
Would it be possible to use https://antmedia.io/discover-the-filter-plugin/ the Filter Plugin to apply an ffmpeg filter to flip the video horizontally? From this website https://ffmpeg.org/ffmpeg-filters.html#hflip , we could use hflip to theoretically unmirror the video feed. Does anyone have feed back on this? @yashtandon113 @Mohit-3196

**Comment by Mohit-3196** [comment]
Hi @smaldd14 ,
How are you!
Yes, you can use horizontal filter to flip the output horizontally.

The sample cURL command for creating the filter would be like:
curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/create" -d '{"filterId":"flip","inputStreams":["stream1"],"outputStreams":["test"],"videoFilter":"[in0]hflip[out0]","audioFilter":"[in0]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'

Let me know if it works for you.

Thank you

**Comment by smaldd14** [comment]
> Hi @smaldd14 , How are you! Yes, you can try horizontal filter to flip the output horizontally.
> 
> The sample cURL command for creating the filter would be like: curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/create" -d '{"filterId":"flip","inputStreams":["stream1"],"outputStreams":["test"],"videoFilter":"[in0]hflip[out0]","audioFilter":"[in0]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'
> 
> Let me know if it works and we can proceed accordingly.
> 
> Thank you

@Mohit-3196 Thanks for the info! I will be trying this out today and will let everyone know how it works. As per my email, I asked "Will this solution work in real-time? Like can I apply the filter while the stream is live? And what would be the REST API call to unapply the filter? Would I just call to delete that filter with the ID I gave it?" Do you have an answer for this?

**Comment by Mohit-3196** [comment]
Hi @smaldd14 
Yes you can apply the filter is real time.

As you can deduce from the cURL command, we'll pass the incoming streamid (let's say stream1) and the filter will generate a horizontally flied stream with pre-defined output streamId in the parameters (test in this case)

The given command will create and apply the filter.

When you want to delete the filter, you just need to pass the filterId in the delete call as:
curl -i -X DELETE -H "Accept: Application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/flip" 

I have passed filterId as flip while creating the filter and that's why passed flip as the filterId while deleting the filter as well.

Let me know if I missed anything.

Thank you

**Comment by smaldd14** [comment]
@Mohit-3196 can the inputStream and outputStream parameters be the same stream?

**Comment by smaldd14** [comment]
@Mohit-3196 If I have a different parameter for outputStream than inputStream, the response from the POST call I get back is 
HTTP/1.1 200 
Access-Control-Allow-Origin: *
Content-Type: Application/json
Content-Length: 58
Date: Wed, 23 Feb 2022 00:35:45 GMT

{"success":false,"message":null,"dataId":null,"errorId":0}

However, if I have the same stream for parameters inputStream and outputStream, the result I get back is "{"success":true,"message":null,"dataId":null,"errorId":0}"

With the "successful" call where I use the same inputStream and outputStream parameters, I do not see a change in the mirroring. i.e. the video is still mirrored. And with the "unsuccessful" call where the parameters are different, I do see a broadcast created on the AMS dashboard, however playing the stream via navigating to http://IP:5080/WebRTCAppEE/player.html and typing in the streamId does not work. Any Suggestions?

**Comment by smaldd14** [comment]
@Mohit-3196 

UPDATE:

After further trial and error, I have found that creating a filter with the above API call only changes the orientation of the video. If my camera is pointed straight up and down and I call 
"curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/create" -d '{"filterId":"flip","inputStreams":["stream1"],"outputStreams":["test"],"videoFilter":"[in0]hflip[out0]","audioFilter":"[in0]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'"

The outputStream just shows the video feed with a 90 degree rotated view.

What I need is the pixels of the view flipped. Snapchat does this with their selfie mode. If a user is in selfie mode and they move their hand from their perspective right side, it should also look like that on the camera! Not flipped

**Comment by Mohit-3196** [comment]
Hi @smaldd14 ,
Thank you for the details.
Yes the Horizontal flip filter is rotating the stream horizontally by 90 degrees.

What I need is the pixels of the view flipped. Snapchat does this with their selfie mode. If a user is in selfie mode and they move their hand from their perspective right side, it should also look like that on the camera! Not flipped

So I think you mean that if I take up my right hand then it should appear on my right only!
Isn't this opposite of mirroring! 

Pardon me if I'm missing anything. Can we have a call to look at this if you have some time!

Thank you

**Comment by smaldd14** [comment]
@Mohit-3196 , Yes I think you are correct. Basically, when a stream is in selfie mode, I want the view to be the exact opposite of what it looks like now. So that should be unmirroring, correct?

**Comment by smaldd14** [comment]
Hi @Mohit-3196 , Just checking in to see how things are going. Is there any more information you need from me? Or any help you need in implementation?

**Comment by Mohit-3196** [comment]
Hi @smaldd14 ,
How are you!

Thank you very much for your kind support and following up on the issue. 

It has been scheduled on our end and we are looking at the feasibility options. The iOS developer is a little overwhelmed and loaded with some pre-scheduled development work.

Here's the issue https://github.com/ant-media/Ant-Media-Server/issues/3645

We'll update you on this and definitely let you know if we need help.

Thank you so much.
