### ISSUE TITLE
Unable to set audio codec to opus?

### ISSUE THREAD

**Issue by anuragtb** [ant-media/Ant-Media-Server#2482]
### Short description
I'm using browser video and audio for streaming on WebRTC, audio quality in stream is very poor with default codec.so i was trying to change audio codec to opus.
But i didn't find any such option in ant-media js sdk.

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
Hi,

Our default codec for webRTC audio is actually opus, the problem you are facing is probably related with the sampling rate issue. With webRTC publishing it adjusts the sampling rates to be compatible with webRTC and readjusts when playing the stream, which may result in quality decrease. We have an open issue related with this subject which you can follow https://github.com/ant-media/Ant-Media-Server/issues/1097 

Thanks
