### ISSUE TITLE
webrtc_adaptor on NPM

### ISSUE THREAD

**Issue by devloe** [ant-media/Ant-Media-Server#2483]
Where can I find the official webrtc_adaptor library?
Why there is no webrtc_adaptor as npm package?

In the official documentation there is no reference to any library.

**Comment by golgetahir** [comment]
Hi,

You can access webrtc adaptor with `http://SERVER_ADDR:5080/LiveApp/js/webrtc_adaptor.js` . Also, Its file location is `/usr/local/antmedia/webapps/LiveApp/js/webrtc_adaptor.js`. The source code is also here; https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js
You may check our FAQ section from; https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions

We opened an issue about creating an npm package for it, you can follow the issue on; https://github.com/ant-media/Ant-Media-Server/issues/2504

Thanks
