### ISSUE TITLE
Join the published stream to conference room

### ISSUE THREAD

**Issue by otaqwawi** [ant-media/Ant-Media-Server#2487]
# Issue

I want know how to invite published stream in to conference room. Currently, when you join to conference room it will publish stream. How to invite published stream in to conference room
### Short description
__Brief description of what happened__

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by eneskuluk** [comment]
Could you fill the issue please?

**Comment by otaqwawi** [comment]
> Could you fill the issue please?

i have update the description
