### ISSUE TITLE
cannot start the service 

### ISSUE THREAD

**Issue by strelok899** [ant-media/Ant-Media-Server#2488]
### Short description
after yum update .
i getting 

Sep 11 17:02:32 ant-srv systemd[1]: Starting AntMedia...
-- Subject: Unit antmedia.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit antmedia.service has begun starting up.
Sep 11 17:02:32 ant-srv jsvc[17239]: Cannot locate Java Home
Sep 11 17:02:32 ant-srv systemd[1]: antmedia.service: control process exited, code=exited status=1
Sep 11 17:02:32 ant-srv systemd[1]: Failed to start AntMedia.
-- Subject: Unit antmedia.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit antmedia.service has failed.

### Environment

* Operating system and version: centos 7.8
* Java version: build 1.8.0_262-b10
* Ant Media Server version: 2.1.0
* Browser name and version:

### Steps to reproduce
1. yum update -y
2. systemctl start antmedia.service
3.

### Expected behavior
__Put as much detail here as possible__

it should work 

### Actual behavior
__Put as much detail here as possible__

service not starting
 

### Logs

https://pastebin.com/seYAemHX

**Comment by strelok899** [comment]
fixed it by compying 
cp -r jre-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64 java-8-openjdk-amd64
same as in the service .

**Comment by mekya** [comment]
Thank you @strelok899  So we're closing this issue.
