### ISSUE TITLE
Add ability to WebRTCAdaptor to publish on demand

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2489]
When user joins to the conference, user may not want to start publishing as soon as possible. User may want to start publishing after some point of joining.
As a summary, WebRTCAdaptor needs ability to publish on demand not when joining to the room.

**Comment by javierder** [comment]
Hi, does "closed" means this issue won't be worked on?
Thanks.

**Comment by golgetahir** [comment]
Hi Javier,

Closed means it is merged, you can join the conference without publishing and start to publish after a while in the current set up. 

See, in this callback, don't publish, take the publish method under however or whenever you want to publish and it will not cause problems;

```
else if (info == "joinedTheRoom") {
						var room = obj.ATTR_ROOM_NAME;
						roomOfStream[obj.streamId] = room;
						console.log("joined the room: "
								+ roomOfStream[obj.streamId]);
						console.log(obj)

						publishStreamId = obj.streamId

						if(playOnly) {
							join_publish_button.disabled = true;
							stop_publish_button.disabled = false;
							isCameraOff = true;
							handleCameraButtons();
						}
						else {
							publish(obj.streamId, token);
						}
```


Cheers
