### ISSUE TITLE
Latest Release won't start on mac: Could not find or load main class org.red5.server.Bootstrap

### ISSUE THREAD

**Issue by samcambridge** [ant-media/Ant-Media-Server#25]
As title says, downloaded latest release, navigated to the server directory and ran both `./start.sh` and `./start-debug.sh`.

Output of the latter is: 
```
Running on  Darwin
Starting Ant Media Server
Listening for transport dt_socket at address: 8787
Error: Could not find or load main class org.red5.server.Bootstrap
```

Latest release only has source code, no complete build.

Older version works.

**Comment by mekya** [comment]
Yes you are right. We are going to fix this issue later today. Sorry...

@davutcavdar

**Comment by davutcavdar** [comment]
We have updated latest release and build file is ready now. Thanks for your reminder. 

I close this issue now, if you have any further issue, please open another issue or mail to contact@antmedia.io.

**Comment by under-score** [comment]
Sorry, same error here on High Sierra, Java 1.8.0 and Ant-Media-Server downloaded today.
