### ISSUE TITLE
Rest api for recording is not working in some cases when using WebRTC streaming

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2502]
### Short description
In some cases, the rest api to start recording or stop recording the streams are not working as intended.
Relevant api is this: [https://antmedia.io/rest/#/BroadcastRestService/enableRecording](url)
This occurs when using WebRTC streaming and does occurs on RTMP streams.

### Environment
* Ant Media Server version:Enterprise Edition 2.1.0 20200720_1328

### Steps to reproduce
1. Start WebRTC streaming(Ex.ams:5443/LiveApp or WebRTCAppEE)
2. Call the rest api to start recording.

### Expected behavior
Api call returns true and starts recording.

### Actual behavior
Api call returns fall with no message and if user calls the api call again, api call returns false again but this time message is `"Recording is already active. Please stop it first"`. But recording is not active.

**Comment by irevomm** [comment]
Hi Enes - Is there any case where it is working?

**Comment by eneskuluk** [comment]
@irevomm I tested this on my environment and i couldn't reproduce the same issue but this is not working in your environment when streaming via webRTC.
When streaming from RTMP, there is no issue in your environment. You can set recording to true with the rest api method.

**Comment by irevomm** [comment]
Thank you. Are you able to confirm that WebRTC recording is working in your or any one else's environment? If this is a bug in Ant EE 2.1, can a fix be expedited?

**Comment by eneskuluk** [comment]
I have investigated this issue and you need to have HLS enabled to use recording rest api. Otherwise it is returning false. Enabling HLS streaming won't affect your latency or anything. So, there is no impact when you are enabling it.

**Comment by irevomm** [comment]
So you mean to say that WebRTC individual stream recording API works provided we enable HLS?

Thx.

**Comment by eneskuluk** [comment]
Yes, it does.

**Comment by irevomm** [comment]
Ends,

Thank you.

Dhimant

**Comment by eneskuluk** [comment]
We have found the cause of the issue. Creating a bug fix for it.
