### ISSUE TITLE
Social RTMP Endpoint Very High Keyframe Interval 

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2503]
### Short description
Very high keyframe causes to fail the stream. Usually it should be under 3 second and mostly 2 second or under 2 second.
But it is around 20~ seconds.
![image](https://user-images.githubusercontent.com/54481799/93131550-f0b73d00-f6dc-11ea-96b6-d493126f5704.png)

### Environment

* Ant Media Server version:Community Edition

### Steps to reproduce
1.Add some enpoints(such as periscope)
2. Start streaming via WebRTC 

### Expected behavior
Streams should work with no hassle on endpoints.

### Actual behavior
Streams are not working on the endpoints due to very high keyframe interval.

**Comment by burak-58** [comment]
When we make the same test with periscope, thre is no such an issue. Can you check your stream source please?
