### ISSUE TITLE
Add webrtc_adaptor.js as npm package

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#2504]
Being able to reach webrtc_adaptor.js as an npm package would be more convenient for users.

**Comment by mekya** [comment]
Update JS SDK about this package

**Comment by golgetahir** [comment]
Hi,

StreamApp repo is automated with an npm git package, the package can be installed via:

`npm install @ant-media/streamapp@1.1.0`

The package is on:

https://github.com/ant-media/StreamApp/packages/788162

@mekya after we merge the pull request, any commits merged with master will update the version of npm package automatically:
https://github.com/ant-media/StreamApp/pull/164

The one thing customers should keep in mind is that this is an npm git registry package rather than a pure npm package because of the github origin and automation, therefore in their ~/.npmrc file, they need to authenticate git as adding the line:

//npm.pkg.github.com/:_authToken={ Personal auth token from github }

To get personal access token from github for the people who doesn't use it in a detailed explanation:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages


Cheers

**Comment by mekya** [comment]
Thank you for your work @golgetahir 

I've added some comments in PR 
https://github.com/ant-media/StreamApp/pull/164#pullrequestreview-666716773

**Comment by mekya** [comment]
I've merged it with master. The version always seem to be 1.2.0?

**Comment by golgetahir** [comment]
https://github.com/ant-media/StreamApp/pull/176

**Comment by guiyom-e** [comment]
Hello @golgetahir,

I'm trying to use the npm package published at https://www.npmjs.com/package/@antmedia/webrtc_adaptor.

However, I can't use it as is for the moment because the entry point is `"main": "index.html"`, but it should be `"main": "js/webrtc_adaptor.js"` like on the github `package.json`. Is it planned to be changed ?

I also noticed that the npm package name is `@antmedia/webrtc_adaptor` and not `@ant-media/webrtc_adaptor` as defined in the doc. Is it a typo or done on purpose ?

Thanks !

**Comment by golgetahir** [comment]
Hi @guiyom-e 

We were using the github registry of npm npm.pkg.github.com because of the release automation and publish synchronization with workflows, however, some of the users couldn't download it from the github registry of npm so we have published also to the npm registry as a second package. You are right, I will update the package entry point as you suggested. Thanks for the notification.

Cheers

**Comment by mekya** [comment]
Let us put back to the `In Progress` pipeline to make this work automatically.

**Comment by mekya** [comment]
Btw, we've also created an issue to prepare doc for webrtc_adaptor 
https://github.com/ant-media/Ant-Media-Server/issues/4243

FYI

**Comment by AlexandreBourdeaudhui** [comment]
Hello @mekya, thanks for your feedback, and thanks for the publish 🙏
Have a great day!

**Comment by mekya** [comment]
My pleasure. Thank you for your patience. 

Regards,
A. Oguz
