### ISSUE TITLE
How to mount data when using Antmedia Docker ?

### ISSUE THREAD

**Issue by Lynvmili** [ant-media/Ant-Media-Server#2514]
## Short description
When I try to mount data from the container with the local machine there is only the log directory in /usr/local/antmedia.
In the docker-compose.yml file, I tried to mount the data like so:

      volumes:
        - ./data/:/usr/local/antmedia

## Environment
Ant Media Server version:2.1
OS: ubuntu:18.04

In the docker-compose.yml:

    networks:
      my-network:
        driver: bridge
        name: my-network-product

    my-antmediaserver:
      container_name: my-antmediaserver-product
      privileged: true
      stdin_open: true
      tty: true
      build:
        dockerfile: Dockerfile
        context: ./antmediaserver/
        args:
          AntMediaServer: ./ant-media-server-2.1.0-community-2.1.0-20200720_1340.zip
      hostname: my-antmediaserver-hostname
      networks:
        - my-network
      ports:
        - "5080:5080"
      volumes:
        - ./data/:/usr/local/antmedia

My Dockerfile:

    FROM ubuntu:18.04

    ARG AntMediaServer

    ENV http_proxy ${HTTP_PROXY}
    ENV https_proxy ${HTTPS_PROXY}

    RUN apt-get update
    RUN apt-get install -y libx11-dev
    RUN apt-get install -y libcap2
    RUN apt-get install -y wget

    ADD ./${AntMediaServer} /home

    RUN cd home \
        && pwd \
        && wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh --no-check-certificate\
        && chmod 755 install_ant-media-server.sh

    RUN cd home \
        && pwd \
        && ./install_ant-media-server.sh ${AntMediaServer}

    ENTRYPOINT service antmedia restart && bash

After, I run "docker-compose up",  then the antmedia directory in the Container only the "log" directory:

    root@my-antmediaserver-hostname:/usr/local/antmedia# ls
    log
    root@my-antmediaserver-hostname:/usr/local/antmedia# ls log
    antmedia-error.log

Content in file antmedia-error.log

    Cannot find daemon loader org/apache/commons/daemon/support/DaemonLoader
    Service exit with a return value of 1

**Comment by mekya** [comment]
Thank you for the report. 

We'll schedule this issue in this week.

**Comment by Lynvmili** [comment]
> Thank you for the report.
> 
> We'll schedule this issue in this week.

Thank you very much 👍

**Comment by golgetahir** [comment]
Hi @Lynvmili

I will show you how to mount data from /usr/local/antmedia to a docker volume. Please try to do so like this;

1) Create a volume named myvol using command;

`docker volume create myvol`

2) Check the volume. Mountpoint will be the data from docker container which in my case is in "/var/lib/docker/volumes/myvol/_data";

`docker volume inspect myvol`

3) Run your docker container with ( You can do it from the command prompt, download the zip in the same folder with your Dockerfile and run the command `sudo docker run --network=bridge -p 60000:5080 -v myvol:/usr/local/antmedia --privileged=true -it antmediaserver` )

 `volumes : myvol:/usr/local/antmedia`

**Comment by Lynvmili** [comment]
> Hi @Lynvmili
> 
> I will show you how to mount data from /usr/local/antmedia to a docker volume. Please try to do so like this;
> 
> 1. Create a volume named myvol using command;
> 
> `docker volume create myvol`
> 
> 1. Check the volume. Mountpoint will be the data from docker container which in my case is in "/var/lib/docker/volumes/myvol/_data";
> 
> `docker volume inspect myvol`
> 
> 1. Run your docker container with ( You can do it from the command prompt, download the zip in the same folder with your Dockerfile and run the command `sudo docker run --network=bridge -p 60000:5080 -v myvol:/usr/local/antmedia --privileged=true -it antmediaserver` )
> 
> `volumes : myvol:/usr/local/antmedia`
> 
> I hope this will help you
> Regards

Thank @golgetahir very much!
This is very helpful 💯 
I have successfully synced data 👍
