### ISSUE TITLE
Add Guide about RTMP Load Balancer in AWS Cluster doc

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2515]
As I see, we had only Application Load Balancer method in AWS Cluster docs. Application Load Balancer doesn't work with RTMP Streaming. So, we need to add a Classic Load Balancer guide for the RTMP streaming.

**Comment by aaryavrate** [comment]
Any update on this?

**Comment by mekya** [comment]
@muratugureminoglu could you please link the document to this issue?

**Comment by muratugureminoglu** [comment]
@aaryavrate Please check the following link.

https://github.com/ant-media/Ant-Media-Server/wiki/How-to-configure-RTMP-Load-Balancer-in-AWS
