### ISSUE TITLE
Bug Screen Sharing Blackout Problem

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2520]
Bug report from community

> i have found a bug in screen sharing function. 
> 
> For example if you use the screen sharing function and share only the desktop (without camera) it's ok. 
> But if you use screen share desktop with the camera when you press the "stop share" button, that chrome (like safari,firefox ecc ecc) show to you on a pop up window, in the console any message is displayed (i can't intercept event) and in the video remains on the right the camera with a black background. (Also in conference like in publish/play mode).
> 
> Any idea to solve this problem?

https://groups.google.com/g/ant-media-server/c/UfAYge3BDTk/m/O6Rv6oM7AAAJ

**Comment by eliapimpinicchio** [comment]
The issue about screen sharing with camera is the following. For example if you start screen sharing without camera, when you click on "stop sharing" (pop up google), the function generate a message/event that can i intercept, and after apply a routine to do something.
If you start sharing of screen with camera, when you click on  "stop sharing" ant message is generated, and click on the button the screen in which there is the captured screen, become black.

**Comment by mekya** [comment]
Hi @eliapimpinicchio ,

Do you mean the problem is the one in the video?
https://drive.google.com/file/d/1cVOselrOBShq6jT4RHhdqekDzyiFTLPp/view?usp=sharing

Regards,

**Comment by eliapimpinicchio** [comment]
Hi,
yes, the problem the i have is the same of your video.
i would like that when i press stop sharing, in the video the sharing are
stop and the camera return big like a the start.

In which way can i work to solve this?

Best Regards.

Elia Pimpinicchio


Il giorno gio 24 set 2020 alle ore 09:51 Ahmet Oğuz Mermerkaya <
notifications@github.com> ha scritto:

**Comment by mekya** [comment]
Hi @eliapimpinicchio ,

I see. When user stop sharing button, JS SDK should send a `screen_share_stopped` callback. After that, you can call `switchDesktopCapture` method.

**Comment by eliapimpinicchio** [comment]
Hi,

Do you mean the Webrtcadaptor callback?

Best regards.

Elia Pimpinicchio


Il giorno lun 28 set 2020 alle 15:48 Ahmet Oğuz Mermerkaya <
notifications@github.com> ha scritto:

**Comment by eliapimpinicchio** [comment]
Hi,

i tried the suggested solution, but the message, if i use desktop sharing
with the camera isn't generated.

The message comes only if i use switchDesktopCapture as a function to have
screen sharing mode.

Any Suggest?

Best Regards.

Elia Pimpinicchio


Il giorno mar 29 set 2020 alle ore 20:55 Elia Pimpinicchio <
elia.pimpy@gmail.com> ha scritto:

**Comment by golgetahir** [comment]
Hi @eliapimpinicchio ,

Check out the pull request I linked to this issue

Thanks
