### ISSUE TITLE
Bandwidth limitation does not work in Safari iOS

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2521]

**Comment by zafergurel** [comment]
Hello. This is a problem we faced recently.
In webrtc_adaptor.js, change the browser detection code to support Safari. 
Change the following code by adding Safari check.
**Old code:**
`
	/**
	 * If we have multiple videoÂ tracks in coming versions, this method may cause some issues
	 */
	this.getVideoSender = function(streamId) {

		var videoSender = null;
		if ((adapter.browserDetails.browser === 'chrome' ||
				(adapter.browserDetails.browser === 'firefox' &&
						adapter.browserDetails.version >= 64)) &&
						'RTCRtpSender' in window &&
						'setParameters' in window.RTCRtpSender.prototype)
		{
			const senders = thiz.remotePeerConnection[streamId].getSenders();

			for (let i = 0; i < senders.length; i++) {
				if (senders[i].track != null && senders[i].track.kind == "video") {
					videoSender = senders[i];
					break;
				}
			}

		}
		return videoSender;
	}
`
**New code:**
`
	/**
	 * If we have multiple videoÂ tracks in coming versions, this method may cause some issues
	 */
	this.getVideoSender = function(streamId) {

		var videoSender = null;
		if ((adapter.browserDetails.browser === 'chrome' ||
                     adapter.browserDetails.browser === 'safari' ||
				(adapter.browserDetails.browser === 'firefox' &&
						adapter.browserDetails.version >= 64)) &&
						'RTCRtpSender' in window &&
						'setParameters' in window.RTCRtpSender.prototype)
		{
			const senders = thiz.remotePeerConnection[streamId].getSenders();

			for (let i = 0; i < senders.length; i++) {
				if (senders[i].track != null && senders[i].track.kind == "video") {
					videoSender = senders[i];
					break;
				}
			}

		}
		return videoSender;
	}
`

**Comment by golgetahir** [comment]
Hi @zafergurel

Thank you for your contribution to our community. We will add the feature in following updates.

Thanks
