### ISSUE TITLE
MP4 freezes issue

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#2529]
### Short description
The MP4 file freezes when playing on local and broadcast. The MP4 file link is below.

https://antmedia.io/temp/221852299610803398500182_4.mp4

### Environment

* Operating system and version: Ubuntu 18.04
* Ant Media Server version: Enterprise Edition 2.1.0 20200720_1328

### Steps to reproduce
1. Play the MP4 file with Media Player.
2. Broadcast the MP4 file

### Expected behavior
Should play without freezing

### Actual behavior
Freeze MP4 File

**Comment by mekya** [comment]
I have make several tests for this case. 

* When running in local host, there is no problem.  There is no freeze. 
* When running in remote host, there are some freezes. In this case, I've checked that bandwidth between server and client is not high enough to play the stream. It's already reported by the server. 
* When running in remote host and known that there is enough bandwidth, there is no freeze.

From my point of view, the network between client and server is not good enough to play this WebRTC stream smoothly.

Possible solutions are 
- Decrease quality.  Decreasing bitrate(3.5Mbps), resolution(HD) and framerate(25fps) accordingly still provide good user experience that most of the users don't notice.
- Add adaptive bitrate to the server side. To serve good quality to high bandwidth users and lower quality for users having lower bandwidth
