### ISSUE TITLE
Remove JSP code snippets in sample pages

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2532]
**Is your feature request related to a problem? Please describe.**
Some of our customers don't know much information about HTML. If we remove JSP code snippets, it's helpful for the understand. 

**Describe the solution you'd like**
Remove JSP code snippets in sample pages.

**Comment by mekya** [comment]
Which sample pages you mean? 

If you mean the sample pages running in the server,  we'll lose some functionalities.

**Comment by SelimEmre** [comment]
I mean, WebRTC publish and play pages. As I see we are using for getParameter function in JSP Code snippets.  For example:
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/index.html and https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/player.html
