### ISSUE TITLE
Streams cannot be played with HLS but they can be playable with WebRTC

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2534]
### Short description
We'll encounter "Stream will start playing when its available" on long-time RTMP sources embedded on our site as HLS. When we encounter this, WebRTC of the same source plays fine. We've found that we cannot simply STOP and START those broadcasts-- the message on HLS persists. We have to Delete the broadcast entirely and re-add the Stream Source. I suspect the HLS encoding/wrapping is going corrupt or failing for a given stream ID. 

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 1.8
* Ant Media Server version: 2.1
Clustered Environment

### Steps to reproduce
1. Add RTMP as stream source 
2. Try to play the stream with HLS
3. Try to play the stream with WebRTC

**Note to Reporter: What is your RTMP stream source? As far as I remember, it is something hardware encoder.**

### Expected behavior
HLS playback should work. 

### Actual behavior
HLS playback does not work. WebRTC works. 
 
**Note to Reporter: Please let us have log files, stream id and estimated time of occurrence.**
 
Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by MrXermon** [comment]
Same problem on our end running the latest enterprise version. We currently are not able to start new streams without deleting and re-adding the streams.

**Comment by mekya** [comment]
Hi @MrXermon , Could you please provide some log files and provide some stream id?

If you can, we can immediately schedule this issue for this week.

**Comment by MrXermon** [comment]
Hi @mekya,

I've created a ticket on your end which hopefully contains log-files and the ticket ID. Please check if you can find the ticket attached to the mail jgilla@level66.network.

Jan

**Comment by t1m0007** [comment]
Hi- I'm the original Reporter (off-github). Stream source is a SDI to RTMP Encoder called the[ Kiloview E1](http://en.kiloview.com/product/E1-NDI-H.264-HD-SDI-to-NDI-Wired-Video-Encoder--62.html)

**Comment by MrXermon** [comment]
We're using Kiloview E1, too. I can confirm the issue with vMix as well.

**Comment by mekya** [comment]
Thank you @MrXermon , I've noticed your ticket today. We'll schedule it for this week.

**Comment by mekya** [comment]
From reporter

> Have a look at stream ID b5AVUtKzzj221598986231568  -- this was added via the New Live Stream flow with a RTSP source of rtsp://100.113.104.179:554/DPS-K139 and a name of DPS-K139 -- We were having issues with it so I deleted it and re-added the broadcast. After we did the upgrade to v2.1 Gold master, it magically came back with No Name again under this stream ID. So I do suspect these streams are still burdening the servers even after they are deleted.

Log files are available on me.

**Comment by MrXermon** [comment]
Upon request I've checked the settings.deleteHLSFilesOnEnded option but it is still set to it's default value (true). I've troubleshooted the problem a little further and it looks like neither the HLS playlist file nor the HLS segments are generated in the file-system. We've kept the stream running for a few hours and for a by now unknown reason the files are now generated correctly and the stream is working correctly via HLS. Regardless of this behavior it is still very critical for us to have the stream working upon the first creation.

**Comment by MrXermon** [comment]
My fault, still not working. I've checked the wrong livestream (one which was already recreated due to the problem).

**Comment by MrXermon** [comment]
Looks like we at least found our issue. For some reason our customer slightly customized the RTMP URL (added "/streams/" after the application name and before the stream-id) and therefore the HLS playlist and segment files got created in the "/usr/local/antmedia/webapps/AppName/streams/streams/" folder. This caused the URL to the playlist file to not be working.

To conclude, everything is working now from our end.

**Comment by golgetahir** [comment]
Thank you for your update @MrXermon I am happy that it worked for you.

**Comment by golgetahir** [comment]
Hi @t1m0007 , I tried to recreate this error, however, it does not happen on my side. Can you send me tahir.golge@antmedia.io your log files and stream id of stream that this happened. Also, estimated time of occurrence would be really helpful

**Comment by mekya** [comment]
Hey @golgetahir ,

I've some log files.  You can download them with the links below. Please have a look at the following description

> b5AVUtKzzj221598986231568  -- this was added via the New Live Stream flow with a RTSP source of rtsp://100.113.104.179:554/DPS-K139 and a name of DPS-K139 -- We were having issues with it so I deleted it and re-added the broadcast. After we did the upgrade to v2.1 Gold master, it magically came back with No Name again under this stream ID. So I do suspect these streams are still burdening the servers even after they are deleted.

https://drive.google.com/file/d/1V6RBYq8n67Wp7IdHoaM7cUUXZSNXBGfp/view?usp=sharing 
https://drive.google.com/file/d/1BpxdBztO4-8LyQ8LvCfUKv415F6z0zLt/view?usp=sharing

Second similar case is this one

> please see these logs for stream name: DPS-K137 Sub Stream
> Stream Id: 0AEUFDTh9kEE1601770417705  where WEBRTC played fine but HLS did not work at all. The stream was still present during log capture. Ive since deleted and re-added the RTSP src as a new broadcast (and its working find)

The log is available here -> https://drive.google.com/file/d/1xxHablybC6DlWtefpqzHdmGbeOC3ieal/view?usp=sharing
