### ISSUE TITLE
Adding stream sources more than 100

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2535]
### Short description
Run-away CPU Resources are still a problem. There seems to be a threshold on our server that is not correctly reflected in the WebUI of Ant. We generally hover around 35-40% of CPU Utilization with ~100 3Mbps RTMP Stream sources flowing through our server and being consumed in a typical way (normal business hour use). Once we cross the 100 Stream threshold on our Cluster, the CPU will incrementally run away and max out on both nodes. Consumption of those streams doesn't factor in (we never embed them on our site)-- its the simple act of adding more stream sources past the 100 stream threshold.

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 1.8
* Ant Media Server version: 2.1

### Steps to reproduce
1. Add RTMP stream sources more than 100

### Expected behavior
Server should utilize cpu resources about %35-40

### Actual behavior
The CPU usage  will increase incrementally 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by t1m0007** [comment]
Hello. I'm the original reporter. The nodes in our cluster are VMWare EXsi hosted VMs running 12v CPU and 32GB of RAM with VMXNET adapter on Ubuntu 18 and Ant 2.1 as noted.

**Comment by mekya** [comment]
Hi @t1m0007 , We first try to re-produce this issue on our end and confirm the case.

**Comment by muratugureminoglu** [comment]
Hi,

The problem is currently being tested and we will extend the testing time to see the problem.

We observe that the CPU is around 35-40% when we send the broadcast to our side with RMTP(120 RTMP Stream)

In your scenario, do you send with RTMP or do you pull the broadcast with RTMP?

**Comment by t1m0007** [comment]
We pulled from with the New Stream flow.

**Comment by muratugureminoglu** [comment]
When we added 150 RTSP on the 16-core server, it was observed that the CPU increased. 

![Screenshot at 2020-10-11 23-00-28](https://user-images.githubusercontent.com/6337605/95754310-84176a00-0cab-11eb-9341-0feed8a0b232.png)
![Screenshot at 2020-10-11 23-00-15](https://user-images.githubusercontent.com/6337605/95754314-84b00080-0cab-11eb-8c47-210c314c4de0.png)

**Comment by t1m0007** [comment]
hi. I'm not sure how to answer your question. We are using nodes hosted internally on VMWare on Ubuntu 18.04 - -The source of the RTSP streams (not RTMP) is a kiloview E1 encoder. Encode settings as follows. Source video is always 1920x1080 59.94i

![image](https://user-images.githubusercontent.com/5607762/95877419-1702e380-0d42-11eb-815c-7a2308682c0f.png)

**Comment by mekya** [comment]
What's the resolution and bitrate have you used in your test? @muratugureminoglu 

@t1m0007 there is just a confusing thing on my side. You mention that fps 59.94i but screenshot says that it's 30fps.

**Comment by t1m0007** [comment]
@mekya the input of the encoder is 59.94i (SDI Video)-- this should be of no consequence to you though. Effectively the RTSP stream you get from the encoder is the above spec. Here's the audio spec too since i did not include that previously:
![image](https://user-images.githubusercontent.com/5607762/95993235-dfa53d00-0dfc-11eb-848b-aece4fec75a2.png)

**Comment by mekya** [comment]
hey @t1m0007 , OK. I got it. So we need to test with 1920x1080 - 30fps - 3Mbps video stream and 48Khz, 64Kbps AAC audio stream.
