### ISSUE TITLE
Page scroll down to the bottom 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2536]
### Short description
Search as it pertains to the UI auto-scrolling to the bottom of the screen when more than 10 Items are in view

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 1.8
* Ant Media Server version: 2.1
* Browser name and version:

### Steps to reproduce
1. Add 100 records with stream name starts with 'stream1'
2. Make the page list size to 50
2. Search for stream1

### Expected behavior
It only should stay in the same scroll position

### Actual behavior
Scroll to the bottom of the screen for every update.
 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by Moka51** [comment]
La solución en el caso que he podido aplicar es reducir la vista de la web en menos de un 70%. En ese caso podrás leer todos los contenidos de la lista.

**Comment by mekya** [comment]
gracias por tu comentario @Moka51 :)
