### ISSUE TITLE
Transfer configuration to another docker instance

### ISSUE THREAD

**Issue by unbranched** [ant-media/Ant-Media-Server#2537]
I have a docker AMS image installed on the system, that for unknown reasons doesn't work anymore (unreachable dashboard even if the container & ports are on). I installed a second container without any issues.
Now I need to transfer the configurations from the first to the second container, is there an easy way? If I "physically" login via shell in the first container, where are the confs located?
Thanks in advance

**Comment by mekya** [comment]
Hi @unbranched ,

Basically you need to copy database files and configuration files as follows. 

1. Copy /usr/local/antmedia/*.db files to new container
2. Copy /usr/local/antmedia/webapps/*/WEB-INF/red5-web.properties file to the new container

**Comment by unbranched** [comment]
I'll need to investigate a little more because blindly copying those then the "Applications" list in the dashboard is empty. Anyway now I know which are the relevant files, thanks a lot mekya!

**Comment by mekya** [comment]
My pleasure
