### ISSUE TITLE
Update Guide for Grafana Connections With Domain and SSL Cert.

### ISSUE THREAD

**Issue by Moka51** [ant-media/Ant-Media-Server#2538]
# Issue

### Short description
No connection to source with Ant Media Server on Digital Ocean with custom Domain and SSL Cert. 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Open the guide to add Grafana
2. Test Data Source over IP XXX.XXX.XXX.XXX:3000 and dont work. 
3.

### Expected behavior
Connect to the data source.
### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

Many thanks team, awesome work!

**Comment by muratugureminoglu** [comment]
Thanks for your feedback. We added it to the document.

[How-to-Monitor-Ant-Media-Serversl](https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Monitor-Ant-Media-Servers#how-to-enable-ssl)

**Comment by Moka51** [comment]
Many Thanks! Awesome work!!
