### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by ATGeddan** [ant-media/Ant-Media-Server#2539]
Hello,
I get this error with the current iOS SDK

I tried Build Settings -> Build libraries for distribution: YES 
it raises another error: using bridging headers with module interfaces is unsupported
"It's a flutter project with AntMedia set natively"

I think the sdk needs to be updated. 
I hope you help me with this 
Thank you

**Comment by mekya** [comment]
Hi @ATGeddan ,

We right now has the iOS SDK beta version that is built with Xcode 12. I think it will fix your problem. You can ask to try the new beta iOS SDK through support at antmedia dot io

**Comment by ATGeddan** [comment]
> Hi @ATGeddan ,
> 
> We right now has the iOS SDK beta version that is built with Xcode 12. I think it will fix your problem. You can ask to try the new beta iOS SDK through support at antmedia dot io

Thanks a lot @mekya 
Will contact them now

**Comment by mekya** [comment]
My pleasure 👍 

Closing this issue. Let me know if you need further help
