### ISSUE TITLE
Issue with VP8 with Adaptive option and settings.rtmpIngestBufferTimeMs parameter

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2540]
### Short description
When we add `settings.rtmpIngestBufferTimeMs` parameter, AMS is always restarting few seconds. 

### Steps to reproduce
1. Enable VP8 Encoder and disable H.264 Encoder setting.
2. Add one adaptive option like 480p with default values.
3. Add `settings.rtmpIngestBufferTimeMs` parameter in settings
4. Send RTMP Stream with High profile encoder settings.

### Expected behavior
It shouldn't restart.

### Actual behavior
Always restarting.

### Logs
AMS V2.1
Here are the logs:
[logs.zip](https://github.com/ant-media/Ant-Media-Server/files/5285959/logs.zip)

**Comment by SelimEmre** [comment]
Let me give some details about this issue:

1. This error appears in `av_packet_unref(tempPacket);`. I added tempPacket size, null and other controls but, It couldn't stop appear fatal error. https://github.com/ant-media/Ant-Media-Server-Common/blob/master/src/main/java/io/antmedia/muxer/MuxAdaptor.java#L1102
2. While a solve this issue, I saw another fatal exception in `av_packet_ref(packet, pkt);`, Also I added controls, but It couldn't solve this issue. I attached this fatal error log file  -> [hs_err_pid14312.log](https://github.com/ant-media/Ant-Media-Server/files/5366366/hs_err_pid14312.log)

**Comment by SelimEmre** [comment]
I tested this issue in our latest SNAPSHOT. It seems it's solved with our latest changes. So, we can close this issue.

**Comment by mekya** [comment]
I'm also closing the PR in common project
