### ISSUE TITLE
If I send audio only stream to ant media server it could not start recording

### ISSUE THREAD

**Issue by kalradivyanshu** [ant-media/Ant-Media-Server#2549]
### Short description
If I send audio only stream to ant media server it could not start recording

### Environment

* Operating system and version: Ubuntu 16.04
* Java version: openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~16.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
* Ant Media Server version: ant-media-server-enterprise-2.1.1
* Browser name and version: Chrome 85.0.4183.121

### Steps to reproduce
1. Send a audio only stream
2. Trigger recording
3. Recording gives status false

**Comment by mekya** [comment]
Thank you for the info. We likely schedule this in this sprint.

**Comment by JonathanBristow** [comment]
I am also having issues recording audio only streams. When using the demo on audio_publish.html, clicking publish brings the stream up in the admin console but then it disappears after a few seconds. Is this what you are seeing @kalradivyanshu?

**Comment by golgetahir** [comment]
Hi @JonathanBristow and @kalradivyanshu , the issue I found that when you start publishing audio, if you send REST API command to the server, it returns success false and does not start recording, however, if you enable recording first ( before publishing ) from dashboard it records audio too. I am working on this to correct this behavior right now.  What I want to ask to you is if I understand the problem correctly or is there any other problem too?

**Comment by JonathanBristow** [comment]
I reinstalled with a trial enterprise license and audio recording seems to be working out of the box. The issue I was seeing in 2.2.0 community edition was I’d start publishing and then the stream wound just disappear and nothing would be recorded.
