### ISSUE TITLE
Latency test on Digital Ocean instance

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2550]
* Make test on such instance with high load:
CPU-Optimized
Dedicated CPU
16 vCPUs
32 GB
25 GB
7 TB
$320/mo
$0.476/hr

* OVH Large Instance load test

**Comment by rjmtldo** [comment]
CPU-Optimized
Dedicated CPU
32 vCPUs
RAM 32GB
HDD 200GB
Transfer 9TB


[console log.txt](https://github.com/ant-media/Ant-Media-Server/files/5332451/console.log.txt)
[error log.txt](https://github.com/ant-media/Ant-Media-Server/files/5332453/error.log.txt)
![image](https://user-images.githubusercontent.com/72129826/95180146-c5ab9f00-07eb-11eb-90da-0510569f2ba3.png)

**Comment by mekya** [comment]
Hey @burak-58 

The problem in the above comment is as follows from @rjmtldo

> as for my testing when i used to stream with vp8 our stream stop  frequently and we have to rerun it again after few hours will stop check our internet connection there's no problem
> i attached the logs
> using h264  our stream dont always stop like the issue with vp8 codec but some times its stream stops. what do you think the issue?
> 10 Pc Encoder specs  i7 7th gen 8gbs ram
> vmix encoder output bitrate settings 1000kbps
> bandwidth dedicated 35Mbps
> server digital ocean 32 core 64 gbs of ram 9tb transfer

**Comment by rjmtldo** [comment]
hi whats the redult of your testing?

**Comment by burak-58** [comment]
Hi,
We have checked the CPU issue with OVH, no problem and it is confirmed by the user.
We have checked the latency issue on Digital Ocean 16-core instance and recognize the instance provide 300-350 mbps bandwidth and this cause the issue after 200 viewers with 1.5 mbps bitrate video. Actually this is an expected behavior. Because that bandwidth can handle that number of viewers.

Also we have created a new issue #2608 for @rjmtldo report.

**Comment by jesusmunozmobivery** [comment]
Thanks for your response.

During a recent test on the Digital Ocean droplet, the CPU and RAM are apparently normal.
In the test, 10 viewers were connected to an audio-only stream.
 
CPU peaks at 70% usage and RAM remains constant at 60% usage.

I attach a screenshot of the bandwidth usage during that test.

![image](https://user-images.githubusercontent.com/77431293/105954197-a5db0800-6074-11eb-9eb9-7613ff2ad6c8.png)

Thank you.
