### ISSUE TITLE
Feature request show in Grafana the viewer's Ip address/location and the website where viewers streaming from.

### ISSUE THREAD

**Issue by rjmtldo** [ant-media/Ant-Media-Server#2553]
Send the client ip address and location to the Apache Kafka. if possible also to have the website where viewers streaming from?

**Comment by mekya** [comment]
Thank you for the request. Moving it to the backlog to schedule.

**Comment by rjmtldo** [comment]
thank you mekya

**Comment by rjmtldo** [comment]
@mekya  just to ask if you will include this feature on your next version release?

**Comment by mekya** [comment]
It seems that it's scheduled for v2.4. If it's critical for you. I can do my best to schedule for v2.3
ETA  for v2.3 is mid Jan.
ETA for v2.4 is late March. 

Regards,
A. Oguz

**Comment by rjmtldo** [comment]
@mekya  hi mekya is this set to 2.3 or still in  2.4 best regards

**Comment by mekya** [comment]
hi @rjmtldo,

@burak-58 has implemented this feature by sending a kind of metadata through websocket. 

Btw, I don't  see any sample or field in webrtc_adaptor.js for that @burak-58. Could you please let us know how to easily use this feature?

**Comment by rjmtldo** [comment]
@mekya @burak-58  thank you so much, I'm looking forward to the guide. btw just to ask do I need to upgrade my antmedia just to use this feature in my grafana?

**Comment by mekya** [comment]
You're right. Let me open the issue again for that

**Comment by rjmtldo** [comment]
hi, @mekya  any update on this?

**Comment by mekya** [comment]
Hi @rjmtldo ,

My colleague will give you update about this. @burak-58

**Comment by burak-58** [comment]
Hi @rjmtldo 
I have written a document about the usage of the viewer info feature. You can find it from
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Viewers-Info

Also we have a small fix for the feature in the PR:
https://github.com/ant-media/Ant-Media-Server/pull/3234

If you want, you can also make it work with a small trick in JS SDK in the current release. If you want I can tell you about it, or better you may wait the fixed snapshot.

**Comment by rjmtldo** [comment]
Hi, @burak-58  thank you for sending the guide, btw I would love to test it on my test server.  can you share also the fix for #3234?  I wanted to include it in my testing and also be waiting for the next snapshot for my production.

**Comment by mekya** [comment]
I've just initiated a new deploy for the enterprise master branch. I think it'll be deployed to the website in a couple of hours after it passes all tests

**Comment by mekya** [comment]
Closing this issue. This fix is already deployed. 

Please re-open if it's not working for you @rjmtldo

**Comment by rjmtldo** [comment]
hi @mekya  can have video guide or screenshots samples on how to use it?

**Comment by mekya** [comment]
Hi @rjmtldo,

What is the part that you're confused? Let us know that and we can provide some screenshots or video about that.

**Comment by rjmtldo** [comment]
@mekya  this part  can you help create a guide in video format? or have image shows how to do it?
![image](https://user-images.githubusercontent.com/72129826/120773399-82a4f580-c54b-11eb-938e-cafdf11c878a.png)

**Comment by mekya** [comment]
OK. I'm re-opening the issue to provide some more guidance.

**Comment by rjmtldo** [comment]
thank you @mekya

**Comment by burak-58** [comment]
Hi @rjmtldo,

I have added an image into the document.
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Viewers-Info

**Comment by rjmtldo** [comment]
@burak-58  thank you very much.

**Comment by rjmtldo** [comment]
@Mohit-3196  thanks it's working now I can see the test with an epoch date-time format if i want to view the IP address or Country location what parameter should I set in viewerInfo?

**Comment by Mohit-3196** [comment]
Hi @rjmtldo,
You can create a method in the JS code by calling some related libraries and provide it as a viewer info in form of a string to provide the player IP address and location.
I think you can make use of something like what is my ip and what is my location and can call them by integrating JS on the player side.
