### ISSUE TITLE
Possible bug in Refresh Logic - JS SDK

### ISSUE THREAD

**Issue by nagendraK6** [ant-media/Ant-Media-Server#2556]
### Short description
AutoRefresh is not working in mozila in publishing

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1.  Open the conference app and add the refreshlogic as suggested in this https://github.com/ant-media/StreamApp/blob/2248e7b54ef83fbb20237caa4ea8289f0c4b4647/src/main/webapp/index.html
2. Start publishing
3. Disable wifi and wait for 5 seconds then enable wifi

### Expected behavior
Publishing doesn't reconnect

### Actual behavior
Publishing should reconnect self
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by nagendraK6** [comment]
cc: @mekya  Please help me with this. This is critical - some of our customers denied using the product till this is not fixed.

I am trying to make publishing reliable by adding the refresh logic mentioned here
https://github.com/ant-media/StreamApp/blob/2248e7b54ef83fbb20237caa4ea8289f0c4b4647/src/main/webapp/index.html

This logic is working fine in chrome but on Mozila we are not able to reconnect as  webRTCAdaptor.signallingState(streamId); is returning stable.

As per the original code (above) the refresh logic is 
function checkAndRepublishIfRequired() {
 	var iceState = webRTCAdaptor.signallingState(streamId);
  	if (iceState == null || iceState == "failed" || iceState == "disconnected"){
  		console.log("Publish has stopped and will try to re-publish");
  		webRTCAdaptor.stop(streamId);
  		webRTCAdaptor.closePeerConnection(streamId);
  		webRTCAdaptor.closeWebSocket();
  		initWebRTCAdaptor(true, autoRepublishEnabled);
  	} 	
}


**I think in this case signalling state is compared like iceState I believe the actual logic should be this**
  checkAndRepublishIfRequired() {
    var signalingState = webRTCAdaptor.signallingState(streamId);
    if (signalingState == null || signalingState == "closed") {
      this.forceRetry();
    }

    if (signalingState != null && signalingState != "closed") {
      var iceState = webRTCAdaptor.iceConnectionState(stream_id);
      if (iceState == null || iceState == "failed" || iceState == "disconnected") {
        console.log(signalingState + " " + iceState);
        this.forceRetry();
      }
    }
  }

forceRetry() {
  		webRTCAdaptor.stop(streamId);
  		webRTCAdaptor.closePeerConnection(streamId);
  		webRTCAdaptor.closeWebSocket();
  		initWebRTCAdaptor(true, autoRepublishEnabled);
}

**Comment by mekya** [comment]
Hi @nagendraK6 ,

Sorry I just see this message. Yes, you're right. So changing from `signallingState` to `iceConnectionState` resolves your problem?

**Comment by nagendraK6** [comment]
yes it works with iceConnectionState
