### ISSUE TITLE
signallingState returns stable although network is down

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#2559]
### Short description
Chrome returns signallingState stable in 2.2.0 canary version (firefox is ok), firefox returns signallingState stable in enterprise 2.0.0 20200504_1748 version (chrome is ok). There is an instability should be investigated

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 1.8
* Ant Media Server version: enterprise 2.0.0 20200504_1748, enterprise canary 2.2.0
* Browser name and version: firefox 81, chrome 85.0.4183.121

### Steps to reproduce
1. Open index.html depending on version in firefox or chrome
2. Start publishing
3. Stop network connection
4. Check webRTCadaptor.signallingState

### Expected behavior
webRTCadaptor.signallingState should return null

### Actual behavior
webRTCadaptor.signallingState returns stable even though there is no network connection
 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by nagendraK6** [comment]
I tried with the most recent version of the ant-media server as well and hitting the same problem

**Comment by mekya** [comment]
I think it's expected because signaling connection can stay stable but ice connection state can be null or failed or disconnected.

**Comment by golgetahir** [comment]
@mekya index.html has following wrong code;

`var iceState = webRTCAdaptor.signallingState(streamId);`

It should be;

`var iceState = webRTCAdaptor.iceConnectionState(streamId);`

This is why this issue opened, because of this checkAndRepublishIfRequired() does not work properly

@nagendraK6  I think this applies to your case
