### ISSUE TITLE
S3 missing records when adaptive is enabled

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2563]
### Short description
When adaptive streaming enabled and assume 4 quality has set. Assuming there should be 4 file in the S3 but only 1 file is uploaded.
Server sends 4 put requests but only 1 file is being uploaded.

### Environment

* Ant Media Server version:2.0

### Steps to reproduce
1. Enable adaptive streaming and add multiple quality.
2. Start Stream.
3.Finish The stream.
4. Check if multiple files that are created because adaptive streaming is enabled are present.

### Expected behavior
Multiple files are uploaded to the S3.

### Actual behavior
Only 1 file is uploaded.

**Comment by eneskuluk** [comment]
This is tested, no issue has been found.

**Comment by selcuk1soylemez** [comment]
Enes Bey Merhaba;
peer to peer ikili görüşme veya 2 kişiye tanımlı konferans için kayıt yapamadık(iki kişinin görüşmesini tek kayıt altında görmek istiyoruz). Api tarafından gönderilmesi gereken kod nasıl olmalı? webrtc olarak mı livestream olarak mı kayıt yapabiliyoruz? Kaçırdığımız bir ayrıntı mı var.

**Comment by eneskuluk** [comment]
There is no recording option for P2P because peers are directly connected to each other bu you can overcome this issue by using conference where you can record each session seperately.
You can enable recording in the Ant Media Server dashboard in your desired application.
But user sessions are recorded seperately so you need to combine recordings after the recording is finished.
Best Regards.
