### ISSUE TITLE
VP8 stream stops after some time

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2608]
as for my testing when i used to stream with vp8 our stream stop frequently and we have to rerun it again after few hours will stop check our internet connection there's no problem
i attached the logs
using h264 our stream dont always stop like the issue with vp8 codec but some times its stream stops. what do you think the issue?
10 Pc Encoder specs i7 7th gen 8gbs ram
vmix encoder output bitrate settings 1000kbps
bandwidth dedicated 35Mbps
server digital ocean 32 core 64 gbs of ram 9tb transfer

**Comment by burak-58** [comment]
Hi @rjmtldo,
Could you please can you provide a reproduce scenario for this issue.

**Comment by rjmtldo** [comment]
![image](https://user-images.githubusercontent.com/72129826/95844535-37976180-0d73-11eb-9166-1fc4b182da93.png)
![image](https://user-images.githubusercontent.com/72129826/95844595-47af4100-0d73-11eb-9f2d-6dce513cdef5.png)
![image](https://user-images.githubusercontent.com/72129826/95844708-69102d00-0d73-11eb-8298-5470db230846.png)
![image](https://user-images.githubusercontent.com/72129826/95845117-fb183580-0d73-11eb-8335-d128350e6111.png)
![image](https://user-images.githubusercontent.com/72129826/95845248-200ca880-0d74-11eb-95c9-e1f941c77d7c.png)

here's my digital ocean that runs antmedia. the downtime every 11:30-12:00 noon is normal cause we all stop streaming.

**Comment by rjmtldo** [comment]
everyday use on our office we have dedicated 35 Mbps to stream this 10 broadcast each has 1000kbps 
![image](https://user-images.githubusercontent.com/72129826/95845407-534f3780-0d74-11eb-80da-b8f3f3b19632.png)

**Comment by rjmtldo** [comment]
![image](https://user-images.githubusercontent.com/72129826/95846422-9bbb2500-0d75-11eb-9520-80bea3acc47e.png)
average viewers daily

**Comment by burak-58** [comment]
@rjmtldo,
I have tested VP8 for hours but there wasn't any cut as you reported. Please provide a reproduce scenario.
