### ISSUE TITLE
Forcing resolution in player.html app does not work

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#2613]
### Short description
The page https://{ant-media-uri}/WebRTCAppEE/player.html does not retrieve resolutions in which a stream can be played. The resolutions apper after typing `webRTCadaptor.getStreamInfo("<stream id>")`, but picking one does not work. Instead, the app forces resolution for a stream with ID "streamId".

### Fix
1. Add `webRTCAdaptor.getStreamInfo(streamId);` on line 185 (function `startPlaying`)
2. Remove quotes on line 289: should be `webRTCAdaptor.forceStreamQuality(streamId,dropdownSelectedItem);`
instead of `webRTCAdaptor.forceStreamQuality('streamId',dropdownSelectedItem);`

### Remarks
Both `/LiveApp/player.html` nor `/StreamApp/player.html` might have the same issue, but I haven't checked them.

### Environment
* Ant Media Server version: Enterprise Edition 2.1.1 20200902_1011
* Uses Adaptive Bitrate

**Comment by SelimEmre** [comment]
Hi @kputyra,

Thank you for reporting us! We fixed this issue in the latest SNAPSHOT. You can check latest player.html page -> https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/player.html
