### ISSUE TITLE
Ability to upload any format of VoD

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2628]
There is a limitation both on angular side and REST API. 

Support at least for the following formats mov, avi and webm.

**Comment by mansouralex** [comment]
@burak-58 Do you have an estimated timeframe for this request?

**Comment by mekya** [comment]
For this case we'll just remove the limitation on extension on Angular side as far as I remember. 

Which kinds of format do you plan to upload?

**Comment by mansouralex** [comment]
@mekya There is a limitation on the REST API as well. 

For the formats, we need: **mov**, **avi** and **webm**. Thank you.

**Comment by mekya** [comment]
OKI get it. I've updated the description. 

Let me know if you need some more formats.

**Comment by SelimEmre** [comment]
Hi @mansouralex,

This feature available in v2.3. Which version are you using?

**Comment by mansouralex** [comment]
Hi @SelimEmre, we are on v2.2.1 20201029_2042 which we have installed using DigitalOcean Marketplace 1 week ago so we were expecting this to be the latest already. 

So how we can upgrade?

**Comment by SelimEmre** [comment]
Hi @mansouralex,

We are upgrading Digital Ocean snapshot. But it's taking some days to approve from Digital Ocean. You just need to download the latest install script and ams v2.3 file. Here are the commands:
```
wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && chmod 755 install_ant-media-server.sh
sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE] -r true
```
**Note: You can download latest version(v2.3) in your account Download section.**

Please check below docs:
https://github.com/ant-media/Ant-Media-Server/wiki/Installation#update-over-older-version
https://github.com/ant-media/Ant-Media-Server/wiki/SSL-Setup
