### ISSUE TITLE
Is there a way to convert the Ant Media Server's SSL certificate to another format?

### ISSUE THREAD

**Issue by JLRishe** [ant-media/Ant-Media-Server#2631]
I have inherited a project that involves an Ant Media Server and do not have a way of contacting the project's previous developers.

I believe that the Ant Media Server's site is using a certificate that was generated using the provided enable_ssl.sh script - if I inspect the certificate in my browser, it says it was issued by Let's Encrypt Authority X3, which seems to be consistent with what's in that script.

I need to set up another website on that server, with the same hostname and a different port. It is an ASP.NET Core site that uses nginx as its reverse proxy, so I believe I need a .crt and an .rsa file for the certificate.

So my question is - is there a way that I can convert the Ant Media Server site's certificate into this format, so that I can use it on the other site? I have tried the following, which is what I have seen suggested elsewhere as a first step in the process of extracting a certificate from a .jks file and converting it into another format:

```sh
keytool -export -alias tomcat -file mycert.der -keystore keystore.jks
```

But this fails with the error:

```
keytool error: java.lang.Exception: Alias <tomcat> has no certificate
```

If I run `keytool -list -v -keystore keystore.jks`, I get 

```
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: tomcat
Creation date: Jul 26, 2020
Entry type: PrivateKeyEntry
```

Which makes me wonder if maybe keystore.jks contains only the key and not the certificate. If so, I don't know where to look to find the certificate.

I appreciate any help you can provide.

**Comment by JLRishe** [comment]
I think I've managed to answer my own question. It looks like when the enable_ssh.sh script generates the Let's Encrypt certificate, the certificate file and key file are respectively placed in:

```
/etc/letsencrypt/live/{domainname}/fullchain.pem
/etc/letsencrypt/live/{domainname}/privkey.pem
```

So I can directly use those from nginx.

**Comment by mekya** [comment]
You're great. @JLRishe
