### ISSUE TITLE
Investigate Flickering HLS streams when publishing with OBS in Windows 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2637]

**Comment by golgetahir** [comment]
Customer reports this is also happening on WebRTC

**Comment by xpsnetworks** [comment]
Hello!

We are experience the same with RTMP Stream from vMix and HLS Adaptive or any transcoded profile.
Native profile - streamname.m3u8 are OK, but transcoded profiles are flickering.

On WebRTC we can watch the RTMP stream but its flickering all the time on native or transcoded profiles.
