### ISSUE TITLE
setParameter not works in Samsung Galaxy A 50 Device

### ISSUE THREAD

**Issue by niteshfel** [ant-media/Ant-Media-Server#2642]
E/CameraProxy: Camera operation failed
    java.lang.RuntimeException: setParameters failed

https://github.com/ant-media/LiveVideoBroadcaster 
Using this have problem in samsung galaxy device so please help

**Comment by mekya** [comment]
Hi @niteshfel ,

As mentioned before, we don't have resource to maintain https://github.com/ant-media/LiveVideoBroadcaster.
You can develop the fix and make the PR. 

So closing this issue. I'm sorry.
