### ISSUE TITLE
Investigate MongoDB Security Exception

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2645]
It seems that it's about mongodb authentication in v2.1.0. 
On the other hand, another version(2.1.0-SNAPSHOT) of Ant Media Server does not throw this exception and works well. 
Investigate if it's a known issue or a kind of configuration issue

[Log](https://app.zenhub.com/files/83530209/73ee7354-202d-4230-aa3f-f93acaa029fc/download)

**Comment by t1m0007** [comment]
thank you @mekya  - if any other information is required please do not hesitate. 
**MONGO DB Version 4.4.1**

**Comment by mekya** [comment]
Thank you @t1m0007 :)

I've an update for this case. 

User says that "wiping out the DB and re-installing I was finally able to get it to work properly."

I suspect that it's about MongoDB version and client library we use.

**Comment by burak-58** [comment]
Hi @t1m0007
I have made a test to reproduce the issue with the following scenario but I couldn't reproduce.

1. Create an instance and install Mongo 4.1.1, define user and password
2. Create another instance for Ant Media Server
3. Install AMS 2.0 and change mode to cluster
4. Create AMS user/password
5. Create a stream source
6. Install AMS 2.1 on 2.0 and change mode to cluster
7. Login AMS Management Panel
8. Check stream source
9. Check logs

Do you have any addition or correction to this scenario?
