### ISSUE TITLE
RTMPS load balancing in Nginx and HAProxy

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2655]
There is a following configuration 
```
frontend rtmp_lb
    bind *:8443
    mode tcp
    default_backend backend_rtmp
backend backend_rtmp
    mode tcp
    server ams1 xxx.xxx.xxx.xxx:8443 check  # Ant Media Server instance 1
    server ams2 xxx.xxx.xxx.xxx:8443 check  # Ant Media Server instance 2
    # you can add more instances 
```

Getting the following log
```
tail -f /usr/local/antmedia/log/ant-media-server.log 
2020-10-29 08:19:01,567 [pool-6-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2020-10-29 08:20:44,794 [RTMPConnectionScheduler-13] WARN  o.r.server.net.rtmp.RTMPConnection - Closing 0F6PNAISSFBW4, due to long handshake. State: connect
2020-10-29 08:20:44,795 [NioProcessor-9] INFO  o.r.s.net.rtmp.RTMPMinaConnection - Connection is closed: 0F6PNAISSFBW4
2020-10-29 08:20:44,796 [NioProcessor-9] WARN  o.r.s.net.rtmp.RTMPMinaIoHandler - Connection was not found for 0F6PNAISSFBW4
2020-10-29 08:22:37,090 [NioProcessor-26] WARN  o.r.s.net.rtmps.RTMPSMinaIoHandler - Keystore or Truststore file does not exist
2020-10-29 08:22:37,091 [NioProcessor-26] WARN  o.r.s.net.rtmp.RTMPMinaIoHandler - Force close - session: 425
2020-10-29 08:22:37,091 [NioProcessor-26] WARN  o.r.s.net.rtmp.RTMPMinaIoHandler - Force close - session: 425
2020-10-29 08:22:37,091 [NioProcessor-26] INFO  o.r.s.net.rtmp.RTMPMinaIoHandler - Close already forced on this session: 425
2020-10-29 08:23:05,337 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - System cpu load:0 process cpu load:0 available memory: 2861652 KB used memory(RSS): 809072 KB
2020-10-29 08:23:05,337 [vert.x-eventloop-thread-0] INFO  i.antmedia.statistic.StatsCollector - Vertx worker queue size:0 WebRTCVertx worker queue size:0
```

**Comment by rjmtldo** [comment]
Hi @mekya  do we have update with this one?

**Comment by mekya** [comment]
We don't have schedule this issue yet. I hope we can do it for next week.

**Comment by rjmtldo** [comment]
Hi @mekya just to ask if this is in progress?

**Comment by mekya** [comment]
Yes it'll be scheduled later today for this week.

**Comment by rjmtldo** [comment]
Hi @mekya  just want to check if theres any update inregards with this?

**Comment by muratugureminoglu** [comment]
Hi @rjmtldo 

Add the following lines to haproxy.conf file.

```
listen rtmps
	mode tcp
	bind :443 ssl crt /etc/haproxy/ssl.pem # Your cert file.
	server rtmp antmedia_server_ip:1935

```
then restart haproxy service.

Regards.

**Comment by rjmtldo** [comment]
Hi @muratugureminoglu  wow it works now. is it possible also to share the configurations for nginx load balancer version?

**Comment by muratugureminoglu** [comment]
@rjmtldo yes of course. 

Add the following lines at the top of the nginx.conf file. 

`vim /etc/nginx/nginx.conf`

```
stream {
    upstream rtmps_backend {
        server antmedia1_server_ip:1935;
        server antmedia2_server_ip:1935;
    }
    server {
        listen 443 ssl;
        proxy_pass rtmps_backend;
        ssl_certificate /etc/letsencrypt/live/yourdomain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yourdomain/privkey.pem;
    }
}
```
Finally, restart nginx service.

Regards.

**Comment by rjmtldo** [comment]
@muratugureminoglu  everytime add that line nginx get error 
![Uploading Screen Shot 2020-11-13 at 3.53.29 PM.png…]()

**Comment by muratugureminoglu** [comment]
@rjmtldo Please provide the logs as text.

**Comment by rjmtldo** [comment]
Hi @muratugureminoglu 

`-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit nginx.service has begun starting up.
Nov 13 12:09:43 LoadBalancer nginx[29510]: nginx: [emerg] "stream" directive is duplicate in /etc/nginx/nginx.conf:16
Nov 13 12:09:43 LoadBalancer systemd[1]: nginx.service: Control process exited, code=exited status=1
Nov 13 12:09:43 LoadBalancer systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 13 12:09:43 LoadBalancer systemd[1]: Failed to start nginx - high performance web server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit nginx.service has failed.
-- 
-- The result is RESULT.`

**Comment by muratugureminoglu** [comment]
@rjmtldo you should check your conf file. "Line 16"
```
"stream" directive is duplicate in /etc/nginx/nginx.conf:16
```

**Comment by rjmtldo** [comment]
do i need to remove the rtmp settings ? and replace it with rtmps ?

# RTMPS stream configuration
stream {
    upstream rtmps_backend {
        server 157.230.41.176:1935;
        server 167.99.75.225:1935;
    }
    server {
        listen 443 ssl;
        proxy_pass rtmps_backend;
        ssl_certificate /etc/letsencrypt/live/viva1234.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/viva1234.com/privkey.pem;
    }
}

# RTMP stream configuration
stream {
    upstream stream_backend {
        server 157.230.41.176:1935;
        server 167.99.75.225:1935;
    }

    server {
        listen        1935;
        proxy_pass    stream_backend;
        proxy_timeout 3s;
        proxy_connect_timeout 1s;
    }

} (note this is the 16 line)

**Comment by muratugureminoglu** [comment]
Please remove your rtmp conf, then add the following lines.

RTMP and RTMPS configuration for Nginx

```
stream {
    upstream rtmps_backend {
        server antmedia1_server_ip:1935;
        server antmedia2_server_ip:1935;
    }
    server {
        listen 443 ssl;
        proxy_pass rtmps_backend;
        ssl_certificate /etc/letsencrypt/live/yourdomain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yourdomain/privkey.pem;
    }

    upstream stream_backend {
        server 157.230.41.176:1935;
        server 167.99.75.225:1935;
    }

    server {
        listen        1935;
        proxy_pass    stream_backend;
        proxy_timeout 3s;
        proxy_connect_timeout 1s;
    }

}

```

**Comment by rjmtldo** [comment]
Now this is the error i get 
-- Unit nginx.service has begun starting up.
Nov 13 12:51:54 LoadBalancer nginx[29805]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Nov 13 12:51:54 LoadBalancer nginx[29805]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Nov 13 12:51:55 LoadBalancer nginx[29805]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Nov 13 12:51:55 LoadBalancer nginx[29805]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Nov 13 12:51:56 LoadBalancer nginx[29805]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Nov 13 12:51:56 LoadBalancer nginx[29805]: nginx: [emerg] still could not bind()
Nov 13 12:51:56 LoadBalancer systemd[1]: nginx.service: Control process exited, code=exited status=1
Nov 13 12:51:56 LoadBalancer systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 13 12:51:56 LoadBalancer systemd[1]: Failed to start nginx - high performance web server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--

**Comment by rjmtldo** [comment]
do i need to remove this as well ?    

 #Origin Configuration
    server {
            listen 443 ssl;
            ssl_certificate /etc/letsencrypt/live/viva1234.com/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/viva1234.com/privkey.pem;
            server_name ingest.viva1234.com;

            location / {
                proxy_pass http://antmedia_origin;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }

**Comment by muratugureminoglu** [comment]
use a different port for RTMPS.
example: 4433

```

    server {
        listen 4433 ssl;
        proxy_pass rtmps_backend;
        ssl_certificate /etc/letsencrypt/live/yourdomain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yourdomain/privkey.pem;
    }

```

**Comment by rjmtldo** [comment]
Hi @muratugureminoglu @mekya thank you all for your guidance, i can now stream with rtmps.
