### ISSUE TITLE
How to disable log file or limit log file size in /usr/local/antmedia/ directory?

### ISSUE THREAD

**Issue by tankienleong** [ant-media/Ant-Media-Server#2656]
The log file generated in /usr/local/antmedia/ consume 30GB disk space after running for 2 weeks. Is there any way to disable the log file or set file size limit?

**Comment by SelimEmre** [comment]
Hi @tankienleong,

You can change log details in`/usr/local/antmedia/conf/logback.xml` file.

Which version are you using? In our latest version, Ant Media Server log mechanism allows a maximum file size of 0.5 GB for server and error logs.

In addition, AMS has a maximum of 3 logfiles allowed for server and error logs. Btw, all log files can be 3 GB at maximum. When the log file limit is reached, the system overwrites it at the beginning of the file.

**Comment by mekya** [comment]
Hey @liz2021 ,

Your questions is about that issue #2845 

Please follow up there. This issue is not related to VoD upload.
