### ISSUE TITLE
Fmpeg on Ubuntu 20.04

### ISSUE THREAD

**Issue by mrananyan** [ant-media/Ant-Media-Server#2660]
### Short description
I'm tried to run the Enterprise version on Ubuntu 20.04. By some changes in the install script, I installed media server but when I try to run it by ```start.sh``` it's can't use FFmpeg's lib

### Environment

* Ubuntu 20.04
* OpenJDK 11.0.9 
* Lastest / ant-media-server-enterprise-2.2.0-20201021_1458.zip
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
https://pastebin.com/DrNSZmeN

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by muratugureminoglu** [comment]
Thank you for the info. Unfortunately, Ubuntu 20.04 support is not officially released yet. But you can install it using the link below. 

[install_ant-media-server](https://raw.githubusercontent.com/ant-media/Scripts/5cd1585143519b352f3a57bf54b99aa9407b70cb/install_ant-media-server.sh)

Or you can install the following packages.

`apt-get install openjdk-11-jdk unzip jsvc libapr1 libssl-dev libva-drm2 libva-x11-2 libvdpau-dev libcrystalhd-dev -y`

If you need more help, please let me know.
Regards.
