### ISSUE TITLE
Android SDK is Crashing and  Fatal error in: gen/sdk/android/generated_base_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 85

### ISSUE THREAD

**Issue by MohdIrfan12** [ant-media/Ant-Media-Server#2670]
Logs are :

<img width="1209" alt="Screenshot 2020-11-04 at 5 58 07 PM" src="https://user-images.githubusercontent.com/27348106/98116352-2a7f1580-1ece-11eb-8e36-44d9d65ef220.png">
<img width="1326" alt="Screenshot 2020-11-04 at 5 59 00 PM" src="https://user-images.githubusercontent.com/27348106/98116394-38349b00-1ece-11eb-97da-94373f1fe529.png">
<img width="1209" alt="Screenshot 2020-11-04 at 5 58 07 PM" src="https://user-images.githubusercontent.com/27348106/98116444-4682b700-1ece-11eb-9769-953bdd146594.png">
<img width="1326" alt="Screenshot 2020-11-04 at 5 59 00 PM" src="https://user-images.githubusercontent.com/27348106/98116455-4b476b00-1ece-11eb-957e-40487615dad5.png">
<img width="983" alt="Screenshot 2020-11-04 at 5 59 35 PM" src="https://user-images.githubusercontent.com/27348106/98116460-4c789800-1ece-11eb-95d9-f753cc321baf.png">

**Comment by mekya** [comment]
Something similar -> https://github.com/ant-media/Ant-Media-Server/issues/2298

**Comment by MohdIrfan12** [comment]
> Something similar -> #2298

get the latest SDK from ant media. this issue has been resolved in the latest version
