### ISSUE TITLE
iOS HTML embed player is broken

### ISSUE THREAD

**Issue by jakew009** [ant-media/Ant-Media-Server#2674]
When trying to use the embed player on iOS Safari (or Chrome) I get the following error:

![Screenshot from 2020-11-06 12-18-24](https://user-images.githubusercontent.com/3781208/98365375-397ada80-202a-11eb-8d42-35fc8d9c2b05.png)

It works fine on all other devices.

I am wondering if this is something to do with the SSL error reported here: https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M

As we have the same problem reported with the SSL certificate.

Test stream here: https://ant.onvp.io:5443/LiveApp/play.html?name=639493085012637060258081

**Comment by jakew009** [comment]
This is definitely caused by the SSL enable script being bugged in the latest release.

Will close this issue and open a new one.

**Comment by mekya** [comment]
Have you opened the new issue?
