### ISSUE TITLE
SSL Enable script is broken in version 2.2.1

### ISSUE THREAD

**Issue by jakew009** [ant-media/Ant-Media-Server#2675]
The SSL enable script for Letsecrypt is broken in 2.2.1.

The full chain of certs isn't used, and this means that lots of browser reject the connection (including iOS).

The same error is reported here: https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M

I can't be bothered to try and diagnose it (the commit descriptions are a mess) but it works fine in the previous release (2.1.0).

**Comment by burak-58** [comment]
burak@ant:~/AWS$ curl -i -H "Accept: Application/json" -X GET "https://burak.antmedia.io:5443/WebRTCAppEE/rest/v2/broadcasts/list/0/10"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
burak@ant:~/AWS$ 
burak@ant:~/AWS$ curl -i -H "Accept: Application/json" -X GET "http://burak.antmedia.io:5080/WebRTCAppEE/rest/v2/broadcasts/list/0/10"
HTTP/1.1 200 
Access-Control-Allow-Origin: *
Content-Type: Application/json
Content-Length: 2
Date: Sat, 07 Nov 2020 05:43:27 GMT

[]burak@ant:~/AWS$

**Comment by suricloud** [comment]
Is this solved now or not yet?

**Comment by WiertOmta** [comment]
The problem still exists

**Comment by mekya** [comment]
There is an on-going work on this issue. FYI

**Comment by burak-58** [comment]
Copy chain.pem to conf. 
sudo cp /etc/letsencrypt/live/your_domain/chain.pem /usr/local/antmedia/conf

Add this line
http.ssl_certificate_chain_file=conf/chain.pem
after
http.ssl_certificate_file=conf/fullchain.pem
in
/usr/local/antmedia/conf/red5.properties file.
​
Add this line
<entry key="SSLCertificateChainFile" value="${http.ssl_certificate_chain_file}" />
after
<entry key="SSLCertificateFile" value="${http.ssl_certificate_file}" /> 
in
/usr/local/antmedia/conf/jee-container.xml

**Comment by broundtree** [comment]
This solves the SSL error: unable to verify the first certificate

**Comment by Bhoopathismash** [comment]
The issue still remains even I followed the steps for the solution, Do I need to run any command after these 3 steps if it is no, kindly suggests me some other solution.

**Comment by mekya** [comment]
You probably need to restart the server.

```
sudo service antmedia restart
```

**Comment by broundtree** [comment]
I found my issue… it was a typo.  everything is working good now.

Thanks
Brian

**Comment by mekya** [comment]
Perfect thank you. 

Closing this issue.

**Comment by allayli** [comment]
/etc/letsencrypt/live/your_domain/chain.pem is not found

**Comment by mekya** [comment]
Then it means you don't have let's encrypt certificate for your domain. 

kindly reminder make sure that you have replaced {your_domain} with your own domain.
