### ISSUE TITLE
Ant Media Install Script Usage Message is incorrect and Wiki is also inaccurate

### ISSUE THREAD

**Issue by justinh24** [ant-media/Ant-Media-Server#2682]
### Short description
The installation instructions on this page: https://github.com/ant-media/Ant-Media-Server/wiki/Installation
do not have the correct usage instructions.

In addition, when you run sudo ./install_ant-media-server.sh the usage instructions give are also not accurate:
The currently state:
```
  echo ""
  echo "Usage:"
  echo "$0 OPTIONS"
  echo ""
  echo "OPTIONS:"
  echo "  -i -> Provide Ant Media Server Zip file name. Mandatory"
  echo "  -r -> Restore settings flag. It can accept true or false. Optional. Default value is true"
  echo "  -i -> Install Ant Media Server as a service. It can accept true or false. Optional. Default value is false"
  echo ""
  echo "Sample usage:"
  echo "$0 -i name-of-the-ant-media-server-zip-file"
  echo "$0 -i name-of-the-ant-media-server-zip-file -r false -i true"
  echo "$0 -i name-of-the-ant-media-server-zip-file -i false"
  echo ""
```
but in reality

the install as service flag is '-s'
and it also looks like Restore settings defaults to false, and install as service defaults to true which is the opposite
of what is specified in the message.

### Environment

Unix install

**Comment by mekya** [comment]
Thank you for the report. We'll check it out.
