### ISSUE TITLE
Unexpected shutdown

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2686]
Environment
Operating system and version: Ubuntu 18.04
Ant Media Server version: Enterprise Edition 2.2.0

Logs
All Log files:
[ant-media-server.log (6).zip](https://github.com/ant-media/Ant-Media-Server/files/5530547/ant-media-server.log.6.zip)

**Comment by chai2** [comment]
@mekya @burak-58 - I had a similar incident today with "Unexpected Shutdown" notification, but forgot enter the email address. How do I retrieve these logs to the team to look at? 

<img width="531" alt="Screen Shot 2021-03-28 at 1 34 39 PM" src="https://user-images.githubusercontent.com/168434/112767231-5b213200-8fca-11eb-9244-368aedf6082c.png">

**Comment by mekya** [comment]
Hi @chai2 ,

You can just collect logs under /usr/local/antmedia/log directory and also add any log file(if exists) in this format hs_errpidxxx.log under /usr/local/antmedia/


Regards,
A. Oguz

**Comment by chai2** [comment]
Thanks. I opened a support ticket for it.
