### ISSUE TITLE
Video Sender Not Found to Change in conference.html

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2698]
### Short description
Conference.html fires "Video Sender Not Found to change" in console

### Environment
* Ant Media Server version:2.2.1
* Browser name and version: MacOS Chrome 86

### Steps to reproduce
1.  Open conference.html and start to publish
2.  Open another tab for conference.html and start to publish as a second user
3.  Wait a few seconds to see the both users in publishing and playing  
3.  Open the Developer Console for each user

### Expected behavior
There should be no error log with "Video Sender Not Found to change"
![video_sender_not_found](https://user-images.githubusercontent.com/3456251/99356946-1bc83380-28bc-11eb-9b23-9857feb0a2e1.png)

### Actual behavior
There are ""Video Sender Not Found to change" log appearing for both users' developer console.   

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
I've take a look at this problem. It seems that this log is expected. There is no problem with that. 
Because it tries to change the bandwidth for the playing stream and there is no video sender for the incoming stream. 

The functionality(change bandwidth) works for the outgoing stream.

**Comment by MaZZly** [comment]
@mekya if this is "not a problem", could the code be modified to not raise this error in the "okay cases" ?
