### ISSUE TITLE
Altering the URL from local IP address

### ISSUE THREAD

**Issue by oryfoxer7410** [ant-media/Ant-Media-Server#27]
When accessing from the public side, I get the following tomcat error with the default configuration:

_The origin server did not find a current representation for the target resource or is not willing to disclose that one exists._

I need to edit the binding address which the servers see's from the local IP to the public domain for both browsing and for copy rtmp urls. 

Where do I change the URL options I can browse the server on the public side along with update the urls for copy/paste within the application? 

I tried the file, red5.properites and adjusted from 0.0.0.0 to the public ip, which did not fix the problem. Can you help please?

**Comment by mekya** [comment]
Hi @oryfoxer7410 ,

It is a weird error that I have not faced before. I am going to try to reproduce this error. 

Could you please describe how I reproduce this error?

Regards,
A. Oguz

**Comment by oryfoxer7410** [comment]
Fresh Install, setup NAT and try to browse to the server from the public side using the nat'd public IP. I receive this error.

**Comment by mekya** [comment]
I could not reproduce this issue on my local environment. Maybe problem is about my modem. It is not forwarding correctly.  Do you still have this problem in your environment?

**Comment by mekya** [comment]
I am closing this issue for the inactivity. Please re-open it if you are still having this issue
