### ISSUE TITLE
EncoderNotOpened error when publishing with firefox screen sharing

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2706]
### Short description
When some users are publishing stream, they get the warning of EncoderNotOpened. On the other hand, I can publish the stream correctly with my current computer(MacOS)

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.2.1
* Browser name and version: Firefox

### Steps to reproduce
1. Add three adaptive bitrates(720, 480, 360)
2. Open the sample WebRTC publisher page(WebRTCAppEE/index.html) with Firefox
3. Choose 'Screen with Camera' for the video source
3. Start Publishing button

### Expected behavior
Publishing should start

### Actual behavior
Warning appears EncoderNotOpened error and publishing does not start
 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Yeah this problem exists in v2.2.1 because Firefox may send unexpected aspect ratios(1.56, 1.65, etc) while sharing screen. Ant Media Server tries to have the same aspect ratio with the source resolution in transcoding. 
This calculation can lead to false calculations for width and height and it makes the encoder not opened.

The fix for this problem has been sent to enterprise repo.

**Comment by Nokama4** [comment]
I have this issue even on Chrome when I try to share a window and not a screen (it's ok for Atom or a browser but not for Slack or a terminal)
