### ISSUE TITLE
Check if a room exit.

### ISSUE THREAD

**Issue by altezza04** [ant-media/Ant-Media-Server#2707]
Does this function exit? Check if a room Id exit in the server?

**Comment by mekya** [comment]
Hi @altezza04 ,
There is a REST method for room-info but it's not very convenient. 
https://antmedia.io/rest/#/BroadcastRestService/getRoomInfo

We're going to add GET method to check if room is available. I'm converting this to a task in our end. 

1. Add GET method to return ConferenceRoom in REST API
2. Refactor [room-info method](https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/rest/BroadcastRestService.java#L1109) to not query conference room two times from database
3. Add GET method to return the Conference Rooms lists with offset and batch parameters

**Comment by altezza04** [comment]
Thanks, that's would be really nice to have for dealing with multi room situation.

**Comment by mekya** [comment]
You're right.  It's scheduled and I think it will be available in the snapshot later this week.

**Comment by altezza04** [comment]
When will this function be ready to release on Enterprise Edition?

**Comment by mekya** [comment]
Hi @altezza04 ,

This implemented and available in the snapshot edition. You can ask latest enterprise snapshot from support channel. They check your license and provide the latest snapshot.  

New release likely will be available in mid of Jan 21
