### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2738]
- [x] WebHook Guide
- [x] Embedded Web Player
- [x] Simulcasting to Social Media Channels
- [x] Add Troubleshooting for OBS Guide
- [x] Add HLS Record configuration

**Comment by akiziltoprak** [comment]
Documents for iOS, Android and JS SDKs

**Comment by SelimEmre** [comment]
- https://github.com/ant-media/Ant-Media-Server/wiki/Webhook-Integration
- https://github.com/ant-media/Ant-Media-Server/wiki/Embedded-Web-Player
- https://github.com/ant-media/Ant-Media-Server/wiki/Simulcasting-to-Social-Media-Channels
- https://github.com/ant-media/Ant-Media-Server/wiki/Open-Broadcaster-Software-Publishing#troubleshooting
- https://github.com/ant-media/Ant-Media-Server/wiki/HLS-Playing#save-hls-records
