### ISSUE TITLE
Provide a solution for storing files to the sub-folders

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2753]
-

**Comment by KeithLeoSmithIdeam** [comment]
We really need this feature so that each stream source can be saved to its own folder instead of all streams stored in a single vod folder for each ams application. We need to be able to have a configurable subfolder for each stream id

**Comment by mekya** [comment]
Hi @KeithLeoSmithIdeam ,

Thank you for letting us know. 

Please let me understand your requirement, you need to configure subfolder for each stream id via REST method?

**Comment by KeithLeoSmithIdeam** [comment]
Thanks, So the requirement is simply to be able to have VOD files saved to a different directory per stream configured either via Rest or UI. This is as opposed to saving all VOD's in a single directory configured per application. I need this as we have a multi-tenanted AMS server and need to separate client videos from each other. We cannot use different AMS applications as this requires manual intervention and a server restart as AMS is running in containers/Kubernetes as such the infrastructure as code manifests files needs to change to handle new applications.

At the moment I'm using a custom a muxerScript as a workaround which figures out which folder to move each VOD to based on the streamID, but I'm finding that it's very difficult to troubleshoot. It does not show the logs of what's happening when the script runs. So the ability to have directories per stream would be very useful especially in a multi-tenant environment.

**Comment by mekya** [comment]
Hi @KeithLeoSmithIdeam ,

Thank you so much for the explanation.  I'm very interested in your multi-tenant solution.  We may schedule a video call together and I personally really would like to see what you accomplish. I've just sent an invitation on linkedin for you. 

I think we can implement this feature for the REST at first. So that you can set the custom directory for each stream id when you create the stream via REST method. Is it OK?

**Comment by KeithLeoSmithIdeam** [comment]
No problem. I would be happy to take you through it.
That's great, that would work perfectly yes thanks
