### ISSUE TITLE
Cors Filters doesn't work properly.

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#2763]
### Short description

Cors filter doesn't work.

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.2.1

### Steps to reproduce
1. Open web.xml file with the editor 
vim /usr/local/antmedia/webapps/WebRTCAppEE/WEB-INF/web.xml
2. Find the following lines
```
                    <param-name>cors.allowed.origins</param-name>
                    <param-value>*</param-value>
```
3. Change `*` to `URL address`
```
                    <param-name>cors.allowed.origins</param-name>
                    <param-value>http://test.antmedia.io</param-value>
```
4. Restart the service.
`systemctl restart antmedia`

### Expected behavior
It should work
### Actual behavior
It does not work.
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by studiostream** [comment]
I have the same problem!

**Comment by KeithLeoSmithIdeam** [comment]
So I have found that setting the CORS values in the filter does work but then has an unintended consequence where the AMS Admin UI no longer can make calls to the backend.

**Comment by AvrumFeldman** [comment]
From my tests I'm getting the same results. cors restrictions has no affect whatsoever. Unless I'm misunderstanding what the cors filter is intended for, I'm trying to use it to limit the player.

**Comment by petsoukos** [comment]
@KeithLeoSmithIdeam You have to put the domain your AMS ADmin UI sits behind in the allowed origins
