### ISSUE TITLE
Multiple Publish (WebRTCClient) in Android SDK

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2768]

**Comment by mekya** [comment]
What's the latest status for this issue?

**Comment by mekya** [comment]
Can you give some info here?

**Comment by burak-58** [comment]
Lets assume you need to have 2 activities in your Android application that  publishes 2 streams foe example front camera and screen. Then when you create 2 activities both of them try to access microphone and it may cause problem. So you should set false CallActivity.EXTRA_AUDIO_CALL parameter for the second activity.

**Comment by mekya** [comment]
I see and it's fixed in the latest MR. Thank you
