### ISSUE TITLE
Make configurable Keyframe parameter for WebRTC Streaming

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2779]
We are using 2 seconds keyframe value for WebRTC streaming. It means each WebRTC streams start at least 2 seconds. Some of our customers are want to decrease this value. So, we need to change this parameter to configurable instead of hard-coded.

**Comment by gohkimnam** [comment]
Would prefer to make it seamless when switching streams. Meanwhile do you have the steps for a workaround?
