### ISSUE TITLE
Customer Request - A single endpoint to get the number of active live stream viewer count

### ISSUE THREAD

**Issue by zafergurel** [ant-media/Ant-Media-Server#2797]
To get the number of active publishers for an application, there is an endpoint:
/v2/broadcasts/active-live-stream-count

But to get the total of viewers, there is no single endpoint. To get it, one should get all the streams by /v2/broadcasts/list/{offset}/{size} endpoint and sum the viewer counts up from that data. This is very inefficient.

Instead, there shall be an endpoint just returns the active live stream viewer count:
/v2/broadcasts/active-live-stream-viewer-count

**Comment by chai2** [comment]
+1 - this will be user useful. 

Are they any other ways to get the viewer count using Javascript sdk?

**Comment by chai2** [comment]
@zafergurel - Is this what you're looking for?

```
Request: /v2/broadcasts/{id}/broadcast-statistics

Response: {"totalRTMPWatchersCount":-1,"totalHLSWatchersCount":0,"totalWebRTCWatchersCount":2}%

```

**Comment by zafergurel** [comment]
@chai2 Thank you for the information. But this is not I'm looking for.
This is only for a stream, not for an application. Let's say there are 50 streams published via an application, we still need to call this endpoint 50 times to get the total viewer count.

**Comment by mekya** [comment]
I think we have this information in somewhere in the server side. Let us check and make it available through REST call.
