### ISSUE TITLE
Already playing alert in conference room when same streamId removed and added back again via rest

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2799]
### Short description
When a stream is playing in a conference room and removed then added same stream stream to the room, it does not play it and shows already_playing alert in javascript sdk.

### Environment

* Ant Media Server version:2.2.1

### Steps to reproduce
1. Add a stream to the room via rest method
2. Join to the room and play the stream in the conference.html 
3. Remove the stream via rest method.
4. Add same stream back to room.

### Expected behavior
Plays the stream.

### Actual behavior
Alerts already_playing.

**Comment by broundtree** [comment]
Hi Enes, Still seeing this issue

**Comment by broundtree** [comment]
works great !!  Thanks for the fast response!
