### ISSUE TITLE
Unable to Access Web UI - Fresh Install - Ubuntu Server 18.04.5 LTS

### ISSUE THREAD

**Issue by maverickgardner** [ant-media/Ant-Media-Server#2800]
### Short description
I am unable to access the Ant Media web UI after installation. I followed the instructions provided. These instructions worked flawlessly when I installed Ant Media 2.0 on 16.04 LTS several months ago. Wanted to upgrade to 2.2.1 for H265 support, installation seemingly not working. I have enabled all firewall rules, forwarding, disabled ufw, but always get Connection Refused. 

### Environment

* Operating system and version: Ubuntu 18.04.5 LTS
* Java version: 
* Ant Media Server version: 2.2.1 Community
* Browser name and version: MS Edge (Chromium)

### Expected behavior
Able to access http://SERVER_IP_ADDRESS:5080 to create username and password.

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5599          0.0.0.0:*               LISTEN      1594/jsvc.exec      
tcp        0      0 0.0.0.0:34501           0.0.0.0:*               LISTEN      1594/jsvc.exec      
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN      1594/jsvc.exec      
**tcp        0      0 0.0.0.0:5080            0.0.0.0:*               LISTEN      1594/jsvc.exec**      

### Actual behavior
Connection Refused- doesn't load. 
Netstat doesn't show anything configured for 0.0.0.0:5080, even if I add the entry manually. 

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:44217           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:5599          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -

**Comment by mekya** [comment]
Thank you for the report. Let us schedule this issue.

**Comment by triangle-stream** [comment]
Same here. It happened a few times both for http and https. Try to reboot your server or uninstall and then reinstall AntMedia Server. I don't know what exactly is causing this (sometime I switched the Java Version from 11 to 8 and vice versa and it worked).

**Comment by maverickgardner** [comment]
> Same here. It happened a few times both for http and https. Try to reboot your server or uninstall and then reinstall AntMedia Server. I don't know what exactly is causing this (sometime I switched the Java Version from 11 to 8 and vice versa and it worked).

I have rebooted, uninstalled Ant Media, as well as re-built the Ubuntu 18.04.5 box - I will however try changing Java. Thanks for the tip, I'll update accordingly.

**Comment by mekya** [comment]
This issue is schedule for this week and assigned. 

Could you please provide the logs under /usr/local/antmedia/log directory?

**Comment by eneskuluk** [comment]
Hi, this issue is assigned on me this week. How was the outcome of your changes? @maverickgardner 
Is your issue resolved? Is your problem persists? If yes, as this assigned on me, I'm responsible to resolve this issue. I'll try to do some tests and reproduce the issue. 
Version 2.2 is incompatible with Ubuntu 16.04
If your issue is continues, could you send the logs?

**Comment by eneskuluk** [comment]
Hi @maverickgardner, is your problem resolved? If so, could you share how you solved it so maybe another people can find this thread.
If not, I'm here to help.

**Comment by maverickgardner** [comment]
> Hi @maverickgardner, is your problem resolved? If so, could you share how you solved it so maybe another people can find this thread.
> If not, I'm here to help.

Apologies on the silence- have been off for the holidays. I am still having the problems- let me generate the log files and send them over.

**Comment by maverickgardner** [comment]
> Hi @maverickgardner, is your problem resolved? If so, could you share how you solved it so maybe another people can find this thread.
> If not, I'm here to help.

Here are the attached logs. 
[ant-media-server.log](https://github.com/ant-media/Ant-Media-Server/files/5748400/ant-media-server.log)
[antmedia-error.log](https://github.com/ant-media/Ant-Media-Server/files/5748401/antmedia-error.log)

From what I can tell the problem arises from the Apache Tomcat Native library failed to load - causing the HTTP/1.1-5080 connector to fail. Spring context lookup is also failing. 

Also noticed this statement: _OpenJDK 64-bit Server VM Warning: OpenJDK 64-Bit Server VM warning: You have loaded library /usr/local/antmedia/lib/native/libtcnative-1.so which might have disabled stack guard. The VM will try to fix the stack guard now._

**Comment by eneskuluk** [comment]
Could you try executing following script sudo apt-get install openjdk-11-jdk unzip jsvc libapr1 libssl-dev libva-drm2 libva-x11-2 libvdpau-dev libcrystalhd-dev -y
Then try again if possible?

**Comment by maverickgardner** [comment]
I have executed the script - got these results: 
Reading package lists... Done
Building dependency tree
Reading state information... Done
libapr1 is already the newest version (1.6.3-2).
libvdpau-dev is already the newest version (1.1.1-3ubuntu1).
jsvc is already the newest version (1.0.15-8).
libcrystalhd-dev is already the newest version (1:0.0~git20110715.fdd2f19-12).
libva-drm2 is already the newest version (2.1.0-3).
libva-x11-2 is already the newest version (2.1.0-3).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.7).
openjdk-11-jdk is already the newest version (11.0.9.1+1-0ubuntu1~18.04).
unzip is already the newest version (6.0-21ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Since nothing was changed- should I run a purge, then re-run the script?

**Comment by eneskuluk** [comment]
Are you trying with old install script or newer install script? If not, Could you try the latest version: https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh
Could  you mention your environment? Are you running on VM or cloud provider etc. 
Also could you send your server's ssh information to enes.kuluk@antmedia.io please? So we can check what could be wrong.

**Comment by maverickgardner** [comment]
I wasn't certain I was using the latest installer script, so I re-installed using what you linked. Same errors following installation. 

It's a VM running onsite locally on Cisco UCS. 
ESXi v 6.7.0 Build 15976728
Ubuntu Server 18.04.5 LTS 64bit
CPU: 4 Cores (1 socket)
Memory: 32GB
Hard Disk 64GB 

I cannot provide SSH access to this system as we're in an extremely controlled environment. I am going to do a fresh VM with a different configuration to see if I can get it to work...

**Comment by eneskuluk** [comment]
Did you test it? If yes, what was the outcome here?

**Comment by maverickgardner** [comment]
Haven't had a chance to re-build yet- just got back from the holidays. Will update the issue tomorrow once I've had a chance to do the work.

**Comment by maverickgardner** [comment]
@eneskuluk I have rebuilt the VM with the same error. 

Not sure if this is related- but my system had issues downloading the `install_ant-media-server.sh`  as there was a self-signed certificate error. I was unable to bypass with the `--no-check-certificate` flag, but it would fail regardless. I ended up downloading the script from another system and loading it up.

**Comment by maverickgardner** [comment]
@eneskuluk furthermore, I have uninstalled `ant-media-server-2.2.1-community-2.2.1-20201029_0748` and success installed `ant-media-server-2.1.0-community-2.1.0.20200720_1340` without issue. I am able to access the web GUI. 

It would seem the issue is due to a corruption with the `/usr/local/antmedia/lib/native/libtcnative-1.so` compiled library file. All error logs point to this corruption being the cause of all the problems.

**Comment by eneskuluk** [comment]
Thank you for your effort, i will take a look at that.

**Comment by eneskuluk** [comment]
I think you are correct about libtcnative-1.so. But at the same time, we started to use native libraries on version 2.2.1. Maybe this might be the reason.
We try these deployments before release and the instances we tried had no error. We are doing tests on Amazon AWS, Azure and some other cloud providers and we do not encounter such error.

Do you have any recommendation for us to reproduce this issue on the environment(cisco ucs) you tried?

**Comment by cezane** [comment]
Same problem here.

I reinstalled and tried to access the dashboard, without success:

> Failed to connect to 0.0.0.0 port 5080: Connection refused

```
sudo service antmedia status
● antmedia.service - AntMedia
   Loaded: loaded (/lib/systemd/system/antmedia.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-08 15:23:41 UTC; 11s ago
  Process: 9756 ExecStop=/usr/bin/jsvc -stop -pidfile ${PID} org.red5.daemon.EngineLauncher 9
  Process: 9795 ExecStart=/usr/bin/jsvc -home ${JAVA_HOME} -user antmedia -cwd ${ANTMEDIA_HOM
 Main PID: 9798 (jsvc)
    Tasks: 17 (limit: 36000)
   CGroup: /system.slice/antmedia.service
           ├─9798 jsvc.exec -home /usr/lib/jvm/java-11-openjdk-amd64 -user antmedia -cwd /usr
           └─9799 jsvc.exec -home /usr/lib/jvm/java-11-openjdk-amd64 -user antmedia -cwd /usr

Apr 08 15:23:40 ant systemd[1]: Starting AntMedia...
Apr 08 15:23:41 ant systemd[1]: Started AntMedia.

Any hint on how to solve this problem and get Ant server running?

```

**Comment by mekya** [comment]
Could you please share logs under /usr/local/antmedia/log directory? 

Secondly, you are sure that port(5080) is open? 

Regards,
A. Oguz

**Comment by cezane** [comment]
Hello, @mekya . The `/usr/local/antmedia/log` directory only has one empty file: `antmedia-error.log`.

**Comment by mekya** [comment]
Hi @cezane ,

It's likely that server is not started for some reason. It may something about installation or environment.

You follow the installation instructions or you're trying something different?
https://github.com/ant-media/Ant-Media-Server/wiki/Installation

Regards,
A. Oguz
