### ISSUE TITLE
adaptive bitrate is always drops to low quality

### ISSUE THREAD

**Issue by rjmtldo** [ant-media/Ant-Media-Server#2804]
Hi why the adaptive bitrate is always drops to low quality? even the bandwidth we have is high to test alone the stream.note that i add this line settings.excessiveBandwidth_enabled=true in settings. we experience this on these browsers safari Version 14.0.1   Google Chrome 87.0.4280.88 as for firefox 82.0.2 its always playing with this resolution to high and medium vice versa after 15 min will drop to low. and it doesnt switch back to high res.
![Screen Shot 2020-12-11 at 5 48 05 PM](https://user-images.githubusercontent.com/72129826/102755763-73692b80-43a1-11eb-8aad-31607f4c80af.png)
![Screen Shot 2020-12-11 at 5 43 55 PM](https://user-images.githubusercontent.com/72129826/102755823-85e36500-43a1-11eb-9517-c3a5f9698410.png)

**Comment by mekya** [comment]
Hi @rjmtldo ,

There was an improvement about this issue in v2.2. 

Are you using the v2.2?

Regards,
A. Oguz

**Comment by rjmtldo** [comment]
Hi @mekya 

![image](https://user-images.githubusercontent.com/72129826/102757991-a6f98500-43a4-11eb-9128-f3f5041abc7b.png)

yes we are using 2.2 please refer to screenshot above

**Comment by mekya** [comment]
Yeah you're right. 

Where are the server's and client's physical location?

I mean we need to make sure that End to End bandwidth between client and server is good enough to play the higher quality.  The measurement you show is the bandwidth between client and likely the closest point in the internet.

**Comment by rjmtldo** [comment]
our antmedia server is hosted to linode cloud we are usind dedicated cpu 
![image](https://user-images.githubusercontent.com/72129826/102764920-7cacc500-43ae-11eb-920c-27da87f50079.png)

**Comment by rjmtldo** [comment]
![singapore](https://user-images.githubusercontent.com/72129826/102764997-98b06680-43ae-11eb-818e-479398aee9ec.png)
![image](https://user-images.githubusercontent.com/72129826/102765216-e331e300-43ae-11eb-8d3b-f89986e87418.png)
Our Antmedia Server is hosted to Linode Cloud, we have a dedicated cpu plan and we are based in Cambodia  please refer to screenshot above.

**Comment by mekya** [comment]
It's not about the server configuration. 

It's about the network distance and E2E network bandwidth between client and server. 
I mean if there is a congestion in somewhere in any part of the route, then you can see bandwidth bottleneck.

Maybe we can schedule a call to investigate the case.

**Comment by rjmtldo** [comment]
Ok is it possible to schedule tomorrow or what works best for you? Please let us know.

**Comment by mekya** [comment]
Could you please book a session in here?
https://calendly.com/antmedia/consultancy?back=1&month=2020-12

I see if you don't want to have paid consultancy, on the other hand schedule is very busy.  It just helps us scheduling easy. I mean I can make the refund if you want.
