### ISSUE TITLE
Digital Ocean Recommendation about Server Type

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#2825]
Some of our clients at DO complained about poor performance of Ant Media Server on specific servers which provided shared CPUs. 
We need to have recommendation list of droplets in DO in order to provide better customer experience for clients. Otherwise, it will impact customer experience badly.

**Comment by o0Gandhi** [comment]
Would suggest to shift to Low Latency instance type on AWS, and running in cluster if running a lot of streams. Also please verify the instance requirements. 

Would recommend this - 
1) Check latency for choosing the right location http://speedtest-sfo1.digitalocean.com/

2) A General Purpose Droplet with at-least 2 vCPU and 4GB Ram
