### ISSUE TITLE
High memory usage in iOS SDK ANT video call due to rotation of device(IPhone)

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2828]
### Short description
I am getting a memory-related issue when remote views are joined to the stream in iOS SDK ANT call, it's getting increased automatically, We are encountering the issue in WebRTC iOS SDK. This scenario is reproducible. 
 

### Environment

* Operating system and version:
* Java version: 11
* Ant Media Server version: 2.2.0

### Steps to reproduce
1. Get into the meeting.
2. joined remote streams memory get's usage gets increase but not much at this stage.
3. when rotating the device(IPhone) to landscape and then portrait it's getting increased and after 4-6 times the rotation app gets crashed because of memory usage.
4. we are removing all views and other arrays related to this and as well as "Stop" method is called for deallocating ant media objects.

Ticket ID: 36739

**Comment by KavyashreeBasavesh** [comment]
@yashtandon113 @mekya @lastpeony 
We are also facing the similar issue.

@SelimEmre 
Have you got any lead to resolve this issue. Please let us know, even we are facing the similar issue.

**Comment by mekya** [comment]
Hi @KavyashreeBasavesh,

We've a fix about rotation issue with this one
https://github.com/ant-media/Ant-Media-Server/issues/6099

What do you encounter specifically on your end?

Regards
