### ISSUE TITLE
Confirm that Firebase support Oauth2 and callback URL 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#284]

**Comment by ogulcan** [comment]
As I can see from the documents and screenshot, this is not possible at all. Just the opposite, firebase wants us to set redirect url.

![Screen Shot 2018-07-27 at 17.55.30.png](https://images.zenhubusercontent.com/5b1585ca76f98d262074628d/ee3f43fb-6a41-4c4c-a214-de8e470f90a1)
