### ISSUE TITLE
Listen to broadcast status and start playing it (Publish/Play model)

### ISSUE THREAD

**Issue by RomaDev94** [ant-media/Ant-Media-Server#2842]
Hi everyone, I'm developing an Android app with webRTC support and I want one of the users to be able to connect to the created stream even if it isn't playing, when the other user broadcasts I want to start the reproduction of the stream.

I got a message on my client socket telling me that the publisher has entered:

```
else if (active && message.equals("trainer_entry")) {
                                        Log.e(TAG, "Publisher entered");
                                    }
```
Then I would like to start playing that stream so the onPlayStarted listener do its stuff, the thing is that it wont start if I disconnect the client and try to init() again like this:

```
 webRTCClientPlayer.disconnect()
webRTCClientPlayer.init(SERVER_URL, streamPlayID, webRTCModePlayer, "tokenId", activity.getIntent());
```

How can I start playing a stream where I'm connected when it starts to broadcast?

Thanks in advance.

**Comment by mekya** [comment]
Thank you for closing the stream. Please let us know if we can help for anything.
