### ISSUE TITLE
Get all broadcasts

### ISSUE THREAD

**Issue by mrtdgny1903** [ant-media/Ant-Media-Server#2852]
I can get broadcast object with streamId but I want to get all broadcasts. Are there any way to get all broadcasts using rest APIs?

**Comment by golgetahir** [comment]
Hi,

You can call getBroadcastList : https://antmedia.io/rest/#/BroadcastRestService/getBroadcastList

**Comment by mrtdgny1903** [comment]
Thanks. I missed it.

**Comment by golgetahir** [comment]
My pleasure. Closing the issue.
