### ISSUE TITLE
Enable jwt filter does not appear on web panel.

### ISSUE THREAD

**Issue by mrtdgny1903** [ant-media/Ant-Media-Server#2867]
I want to use JWT Filter but this option does not appear on web panel. I don't know why?

**Comment by SelimEmre** [comment]
Hi @mrtdgny1903,

This feature is not yet available in our latest version(2.2.1). You can use this feature in the latest SNAPSHOT version.  If you contact us with support@antmedia.io, our support team can help you with how to use this feature.
