### ISSUE TITLE
WebRTC is not smooth in 2.2.1 version

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#2868]
### Short description

Customer uses 1.9.1 in an old hardware and wants to switch 2.2.1 on a new hardware
Sending the stream with RTMP to both, in webRTC the old version is performing very good but the new version have frame dropping issue. This is being tried by several transcoded videos and with the command;

```
ffmpeg -thread_queue_size 2048 -f decklink -video_input sdi -audio_input embedded -i 'DeckLink Mini Recorder 4K' -threads 4 \
-filter_complex "[0:v]scale=-2:1080,fps=25,split=outputs=2[1080a][1080b]" -map "[1080a]" -map "[1080b]" -map 0:a \
-c:v libx264 -tune zerolatency -c:a aac -b:a 128k -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 15000k -crf 25 -pix_fmt yuv420p -g 50 -f tee \
"[select=\'v:0,a\':f=flv:onfail=ignore]rtmp://10.0.0.222/WebRTCAppEE/hq-rlt-studio-5-1| \
 [select=\'v:1,a\':f=flv:onfail=ignore]rtmp://172.16.241.106/WebRTCAppEE/hq-rlt-studio-5-1"
```

The screen record of the problem;
https://drive.google.com/file/d/1I-r_wxjFkZfxIKoLoSIJ8aITVAixik-4/view

The server sits inside an internal network so it is not reachable for us.

### Environment

* Operating system and version: 
* Java version: 11
* Ant Media Server version: 2.2.1
* Browser name and version: Chrome,Safari, Opera tried all.

### Steps to reproduce
1. Send the RTMP stream with the given ffmpeg command
2. Watch the stream from any browser
3. Notice if there is frame drops.

### Expected behavior
Video should play smoothly.

### Actual behavior
There are dropped frames in the playback.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by zaleschoenborn** [comment]
We are seeing very similar issues and wondering if there's any updates￼

**Comment by zaleschoenborn** [comment]
Key points:
1 - stutter is most noticeable with very slow video (see our color bars mpg, included as a link below. this works very well to reproduce issue due do the limited block of motion at the bottom)
2 - only happens with H.264 (VP* makes it more of a periodic blur than stutter)
3 - only happens on highest quality stream in adaptive settings
4 - happens no matter how you publish (RTMP or web rtc)
5 - There is no setting we've found to make it better so far

Here's a link to the colorbar video that will produce the stuttering every time reliably to test against.
[https://drive.google.com/file/d/1YR_Q-VOLuhK5QfBP5Qj5Qo_MigGR67Oj/view?usp=sharing](url)

**Comment by SelimEmre** [comment]
Hi All,
I tried this issue both of 1.9 and 2.2.1 versions in my test environment. I couldn't reproduce this issue.

**Comment by zaleschoenborn** [comment]
Please watch the moving part of the color bars And you'll see the stuttering.

We did find a workaround which was to increase the number of threads in the encoding

**Comment by SelimEmre** [comment]
Hi @zaleschoenborn,

Thanks for your clarification. Let me give some details about this issue. I have tested your `colorbars.mpg` file that you provided. I couldn't see any stuttering.  Is there anything did I miss?

OBS Dashboard: https://imgur.com/a/huLkUvI
OBS Settings:  https://imgur.com/a/JCmWQrB and https://imgur.com/a/CIitwtt

WebRTC Statistics: https://imgur.com/a/pEfFVIa
Ant Media Server configs: https://imgur.com/a/4mHGTSZ

Default stream mp4 record: https://drive.google.com/file/d/11Mr5vi2Kc-oI1_Im7OfBCHSE31U-TRUi/view?usp=sharing
Adaptive stream mp4 record: https://drive.google.com/file/d/1YrRZnqgKM_LzvmkoFKjTPRqdnGGiATCh/view?usp=sharing

**Comment by belthesar** [comment]
Hi folks! 

I'm seeing this as well with a bog-standard vanilla install of Ant Media Server Enterprise via Docker. I'm testing purely via localhost for right now, ingesting via RTMP, using the default LiveApp for output. I'm running with a clock on stream, and I'm only getting video updates every 1 second (to the millisecond). Audio is smooth.
