### ISSUE TITLE
Save HLS Records should be store in S3 when we configured save HLS records and AWS S3 integration.

### ISSUE THREAD

**Issue by komgritch7** [ant-media/Ant-Media-Server#2872]
We have the solution recorded livestreaming(rtmp) as HLS and have to store in AWS S3 so we configured follow these document guides correctly.
https://github.com/ant-media/Ant-Media-Server/wiki/HLS-Playing#save-hls-records
https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration

But we have a issue. The save HLS records stored files only local disk.

Actually, It should be store HLS recorded files to AWS S3 when we configured AWS S3 integration for store all HLS recorded files also.

**Comment by mekya** [comment]
Hi @komgritch7 ,

Thank you for the issue. We've received this request many times. Moving to backlog to schedule it. 

Regards,
A. Oguz

**Comment by SelimEmre** [comment]
Hi @komgritch7,

I'm developing this issue right now. Do you mean upload HLS files during the stream or after the stream ended? Currently, I'm developing for after the stream ended case. Is this development solve your issue?

**Comment by mekya** [comment]
@SelimEmre , let's synch with this issue. I think we should have some kind of good design in the software because there are some issues interconnected
https://github.com/ant-media/Ant-Media-Server/issues/3005
https://github.com/ant-media/Ant-Media-Server/issues/2753

**Comment by komgritch7** [comment]
@mekya That is good design.
@SelimEmre I means after the stream ended. Anyway logic of record streaming as mp4 and hls should be the same.

**Comment by SelimEmre** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/318
https://github.com/ant-media/Ant-Media-Server-Common/pull/288

**Comment by seniorcorel** [comment]
I would like to apply this new commit in my Enterprise version. 
How to update the Enterprise Edition 2.2.1 20201029_2042 running in AWS to the last one commit?
Should I have to redeploy the AMI?

Kind regards.

Pablo

**Comment by mekya** [comment]
Hi @seniorcorel ,

This MR is not merged to master yet. 

This feature will be available in 2.3.1 and yeah you need to redeploy the AMI. We plan to release 2.3.1 early April. 

If you want to test before it's available in AMI, you can ask support team to give you a snapshot for that.

**Comment by Nyceane** [comment]
@mekya let me know when this is available, I am looking for this as well :)  if possible, would HLS be uploaded to a different S3 bucket than the mp4?  Otherwise I have to manually move them.

**Comment by SelimEmre** [comment]
Hi @Nyceane

This issue assigned to me. Currently, It's in the test phase. I think it will ready to use in a short time.

**Comment by mekya** [comment]
Hi @Nyceane, 

Sorry, unfortunately, it will not be in 2.3.1. Its merge will postponed to v2.3.2.

You don't need to wait for the 2.3.2 release. You can get a snapshot if you want to have early access.  

Regards,
A. Oguz
