### ISSUE TITLE
WebRTC- Audio level is too low in Android devices

### ISSUE THREAD

**Issue by jesusmunozmobivery** [ant-media/Ant-Media-Server#2881]
### Short description
The audio level is too low when playing a stream in some Android devices. 

### Environment

* Android device: BQ Aquarius X5
* Android version: Android 7.1.2
* Ant Media Server version: Enterprise Edition 2.1.0 20200720_1328
* Browser name and version: 

### Steps to reproduce
1. An user creates a streaming channel and starts broadcasting through a mobile device.
2. Another users connect to that channel in order to receive the signal from the user who is broadcasting.

### Expected behavior
Audio level can be similar to other devices

**Comment by mekya** [comment]
Could you please give an update for this issue @burak-58?  if it's already fixed, just let us know.
Alternatively, let us know instructions if we need.

**Comment by burak-58** [comment]
We have previously resolved this issue and we can't reproduce it again. We need to know devices on which this issue occur.
