### ISSUE TITLE
SSL error occurs if there is Tomcat Certificate folder

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2887]
### Short description
This issue encounter when renew certificate script. In some cases, the tomcat.cer file cannot be deleted.  So, we need to check SSL folder is already exists. 

### Expected behavior
I expected app.blabla.ca folder name change with app.blabla.ca_backup and try to create new certificate file. 

### Actual behavior
SSL Script reports folder already exists and process is stopped.

### Logs
```
domain: app.blabla.ca
creating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Cert not yet due for renewal
Keeping the existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Importing keystore ./app.blabla.ca/fullchain_and_key.p12 to ./app.blabla.ca/keystore.jks...
Existing entry alias tomcat exists, overwrite? [no]:  yes
Certificate stored in file <./app.blabla.ca/tomcat.cer>
keytool error: java.lang.Exception: Certificate not imported, alias <tomcat> already exists
There is a problem in installing SSL to Ant Media Server.
 Please take a look at the logs above and try to fix.
 If you do not have any idea, contact@antmedia.io
```

**Comment by muratugureminoglu** [comment]
Hi @SelimEmre, As it is understood from the logs below, Ant Media Server was not installed with the install script. It is an error caused by incomplete installation and incorrect running.

`sudo ./enable_ssl.sh -d domain.com -i .`

`chown: invalid user: antmedia:antmedia`

`Failed to stop antmedia.service: Unit antmedia.service not loaded.`

Regards.
