### ISSUE TITLE
Customer Request - Limit participants in Conference Room

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#2898]
Ability to limit participants in a conference room to allow admitting only a limited number of users to each conference room.

**Comment by timantmedia** [comment]
It is possible to limit the viewers by setting a viewer restriction on the live stream parent track, but although you cannot view all the other participants, publishing still starts. 

What is needed is the ability to restrict publishing as well as viewer limit on the live stream. 

Possible solution: add a new field to configure a publisher limit.

<img width="796" alt="Screenshot 2023-10-11 at 09 16 14" src="https://github.com/ant-media/Ant-Media-Server/assets/121940452/3d3e2b6a-8dda-47ff-ab8b-4ea930aff8a6">

**Comment by lastpeony** [comment]
Its done

https://github.com/ant-media/Ant-Media-Server/issues/5723
