### ISSUE TITLE
WebRTC to RTMP Adaptor does not work a virtual webcam

### ISSUE THREAD

**Issue by VShtaba** [ant-media/Ant-Media-Server#29]
# Issue
The WebRTC to RTMP Adapter does not recognize a virtual webcam.

### Short description
On the my remote mashine is not possible to connect physical the webcam. I use the software that creates a virtual camera. With virtual device does not want to work WebRTC to RTMP adapter.

### Steps to reproduce
1. I downloaded Community Edition Open Source Ant Media Server 1.3.2 (Apr 12, 2018) https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v1.3.2
and install this Server on my remote server Ubuntu 16.4.
2. Enable SSL for Ant Media Server and open ports. 
3. Launch server, login to control panel, open url
https://localhost:5443/WebRTCAppEE
and provide access to camera and microphone in browser.
4. Ok. I see video from my physical webcam on my virtual machine and see media streem in player web page https://localhost:5443/WebRTCAppEE/player.html
5. Then I remove (detached) physical webcam and install a program that emulates the virtual webcam driver. Load in browser web page https://localhost:5443/WebRTCAppEE
6. But the service does not see the virtual camera and refuses to work.

### Environment
[] Operating system and version: Ubuntu 16.4, 64-bit
[] Java version: build 1.8.0_162-8u162-b12

### Expected behavior
The WebRTC to RTMP Adapter works with virtual camera (as well as with physical).

### Actual behavior
The WebRTC to RTMP Adapter does not works with virtual camera.

**Comment by mekya** [comment]
You use which virtual webcam driver? iSpyConnect ?

As I remember, audio and video should be both enabled for this virtualization case.

**Comment by VShtaba** [comment]
I use ManyCam virtual webcam driver.

**Comment by SelimEmre** [comment]
Hi @VShtaba,
I hope you solved your problem. If the problem persists, please reopen this issue. Thanks.
