### ISSUE TITLE
Preview of live conference is getting streched when we change the orientation 

### ISSUE THREAD

**Issue by ThirupathiMukkera** [ant-media/Ant-Media-Server#2901]
### Short description
We have an issue with the preview of live conference when we change the orientation, the preview is getting stretched. In Firefox browser

### Environment

* Android version 9.0
* Java version: 1.8
* Ant Media Server version: Enterprise Edition 2.1.1 20200902_1011
* Browser name and version: 

### Steps to reproduce
When we start the conference in Portrait mode preview is showing in Portrait, but when we change the orientation to landscape the preview resolution is not changing to landscape and it is getting stretched. 

### Expected behavior
Preview resolution has to change to landscape when we switch portrait to landscape. Actually its stretching when we change  the orientation.

How to dynamically change the preview resolution when we change the orientation?

### Actual behavior
Preview resolution is not changing dynamically when we change the orientation rather it is getting stretched.

Here I gave the image links for reference.
App Screenshot when shooting in portrait mode
http://bit.ly/PhonePortrait
Preview in portrait mode:
http://bit.ly/PreviewPortrait
App Screenshot when switched the orientation to landscape:
http://bit.ly/PhoneLandscape
Preview in landscape(Stretched) - __The resolution has to change to landscape resolution instead stretching__
http://bit.ly/PreviewLandscape

**Comment by mekya** [comment]
Hi @chai2 ,

Thank you for your comment. 

It's a known issue and right now I have an idea how to resolve the issue. 

I've moved to the backlog and increased its priority. I think we can schedule it in a couple of weeks.

**Comment by chai2** [comment]
Great. Thanks for taking customer issues into priority 🙌🏻

**Comment by golgetahir** [comment]
Hi @mekya 

Merge request id: 364

Cheers
