### ISSUE TITLE
360 player no audio

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2903]
### Short description
360 player should have audio and voluma control but neither is available.

### Steps to reproduce
1. Start stream.
2. Play with 360_live.html
3. Check the behavior

### Expected behavior
Even with 2d streams, there should be audible sound.

### Actual behavior
There is no audio. Only video is available. Also there should be a volume control for audio.

**Comment by SelimEmre** [comment]
Hi @eneskuluk,

Yes, it's an expected issue. Browser policies do not allow audio playback without user consent. We may add a enable sound button somewhere. 
Please check: https://stackoverflow.com/questions/62128125/why-my-webrtc-stream-in-ant-media-server-doesnt-start-to-play-automatically

**Comment by recnmix** [comment]
audio works for a 2d player but not 360

**Comment by recnmix** [comment]
checking in here about getting audio enabled for the 360 ant media player. Was this ever solved>?

**Comment by dominik-schmid** [comment]
## Fix

I have a fix for this problem and wanted to create a pull request. Unfortunately, the HTML files aren't included in the Ant Media Server repo, or am I missing something?

You can add this code to the `360_live.html` file, for example below the already existing script:
```html
<!-- Mute/Unmute Video Button -->
<button
    onclick="changeVideosMuteStatus()"
    id="unmuteButton"
    title="Mute/Unmute Video"
>
    Unmute
</button>

<style>
    #unmuteButton {
        display: block;
        position: fixed;
        bottom: 20px;
        left: 30px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: red;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
    }

    #unmuteButton:hover {
        background-color: #555;
    }
</style>

<script>
    // This function mutes or unmutes the video stream.
    // This is necessary because the browser doesn't allow videos to be played automatically and unmuted by default.
    // Exceptions are possible: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

    function changeVideosMuteStatus() {
        const video = document.getElementById("remoteVideo");

        // Checks the current "mute" status of the video
        if (video.muted) {
            // Unmute the video and change the button's text
            video.muted = false;
            document.getElementById("unmuteButton").innerText = "Mute";
        } else {
            // Mute the video and change the button's text
            video.muted = true;
            document.getElementById("unmuteButton").innerText =
                "Unmute";
        }
    }
</script>
<!-- END Mute/Unmute Video Button -->
```

## Caveat

This is working like a charm on the desktop (macOS 11.3, Firefox Version 88.0.1 and Google Chrome Version 90.0.4430.212).

However, it only works one time when using my smartphone (iOS 14.5.1, Safari and Chrome). I can enable the audio one time and I can disable it also. But when I want to enable the sound again it doesn't work but the text of the button changes. Therefore I don't think it's a problem how the script checks for the muted property but may be an issue with some mobile browser restrictions.

**Comment by eneskuluk** [comment]
Thank you for your contribution, here is the 360_live.html.
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/360_live.html
You can create pull request and reference this issue please.

Regards,
Enes.

**Comment by SelimEmre** [comment]
Hi @dominik-schmid,

Thank you for your contribution. I did some changes to this issue and added PR. Could you please check it: https://github.com/ant-media/StreamApp/pull/167

**Comment by dominik-schmid** [comment]
Hi @eneskuluk,
Thank you for the link to the StreamApp repo. Haven't found that before.

I'm glad that I was able to contribute a bit. Thank you @SelimEmre for completing the work.

Did you also get the same behavior on mobile devices?

**Comment by mekya** [comment]
I've merged this request but it should be better. So that I've re-opened this issue. 

@SelimEmre 
Please think that we're creating a player and let's implement it with the user habits. 
- Use a speaker image to mute/unmute in the default html video player 
- Popup a message if stream id is missing. 
- If possible, create a single video player(play.html) and provide 360 playback as a query parameter. It will be easier for users and for us.
