### ISSUE TITLE
WebRTCAdaptor closeStream() can't stop mic access

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#2925]
### Short description
When we call closeStream method, it can close webcam reach but can't close microphone reach. Browser still shows red spot and shows the page is accessing your microphone like;

![Screenshot from 2021-02-03 14-15-06](https://user-images.githubusercontent.com/32591015/106739526-4eb3d500-662a-11eb-9a1b-eaf15245d67f.png)

### Environment

* Operating system and version: ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.2.1
* Browser name and version: Chrome 87.0.4280.88

### Steps to reproduce
1. Edit some function in conference.html to call webRTCAdaptor.closeStream() ( I used it under turnOffLocalCam method )
2. Try to call closeStream's method ( Click on turn off camera )
3. Camera reach closes but page is still accessing the microphone as in the screen shot.

### Expected behavior
closeStream() should relieve camera and microphone access

### Actual behavior
closeStream() does not relieve microphone access

### POSSIBLE REASON
Under webrtc_adaptor.js we call audio and video streams separately, which may cause some track to left open or possibly we are calling getUserMedia two times somewhere. Under the setGainNode method if we remove the audio track from controlled stream, the red dot disappears but camera sign stays which may be a browser bug also.
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by anhoang318** [comment]
it's work for me
```
 webRTCAdaptorRef.current.closeWebSocket()
 webRTCAdaptorRef.current.closeStream()
```

**Comment by mekya** [comment]
Thank you for your comment @anhoang318 

Cheers
Oz
