### ISSUE TITLE
conference.html

### ISSUE THREAD

**Issue by srinivaskolla** [ant-media/Ant-Media-Server#2927]
### Short description
In conference.html after clicking on joinRoom() nothing happens.

### Environment
* Operating system and version: CenOS
* Java version: open jdk 11
* Ant Media Server version: 2.2 community edition.
* Browser name and version: All browsers ( Chrome/Firefox)

### Steps to reproduce
1. Install community edition.
2. enable_ssl.sh
3. start-debug.sh
4. /LiveApp/conference.html?streadId=testthisone
5. Click on Join Room button.
6. Brifely shows publishing message, nothing happens after that.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
Nothing Happens
Look at the console message 
sent message:{"command":"joinRoom","room":"room1","streamId":"testthisone"}
No messages after that. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
Hi,

Conference Room function uses webRTC for the ultra low latency streaming. Ant Media Server Community edition does not support webRTC, only Enterprise does, that is an expected behavior that conference did not work.

Thanks
