### ISSUE TITLE
Deleting Videos from CLI

### ISSUE THREAD

**Issue by jfreak53** [ant-media/Ant-Media-Server#2941]
Is there a way to delete a video from the CLI and have it removed from the database? Scenario: I want to auto clean using linux' find command any videos over 15 stored videos.

If I just `rm` the video it removes the video but it's still listed in antmedia panel since it's in the database.

Thanks!

**Comment by golgetahir** [comment]
Hello,

If I understand correctly, you want to remove the VoDs from both system disk and Ant Media web panel.

You can use https://antmedia.io/rest/#/VoD%20Rest%20Service/deleteVoD this REST call programmatically with this rest call ( https://antmedia.io/rest/#/VoD%20Rest%20Service/getVodList ) and you can delete the items from the incoming list in this manner. Is this sound reasonable?

Thanks

**Comment by jfreak53** [comment]
Yes, this will work. I just prefered to do it over CLI than API if I could. Thanks!

**Comment by mekya** [comment]
@jfreak53 take a look at the cURL samples 
https://github.com/ant-media/Ant-Media-Server/wiki/REST-API-cURL-Samples
