### ISSUE TITLE
Provide websocket message for the viewer to start/stop tracks from server side 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2947]

**Comment by mekya** [comment]
The pipeline is not passing for this PR. 

Please also mention the PR link for convenience in future PRs.

**Comment by kputyra** [comment]
Hi @mekya and @golgetahir 

What is the current status of this feature? Are the enable/disable commands already implemented in v2.3.2?

**Comment by golgetahir** [comment]
Hi @kputyra

It is waiting for a review before merging in PR, passed automated tests.

@mekya  For your reference the PR is;

https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/332

Thank you

**Comment by mekya** [comment]
It's already merged. Closing this issue.
