### ISSUE TITLE
Support quick sync as hardware encoder

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2952]
https://trac.ffmpeg.org/wiki/Hardware/QuickSync

**Comment by MarianoFacundoArch** [comment]
We really need this :D

**Comment by strelok899** [comment]
would be great!!!

**Comment by mekya** [comment]
Great to hear that. We'll schedule it for next release(v.2.3.1) We plan to release more frequently. 
2.3.1 is scheduled for early March.
