### ISSUE TITLE
Load Test not available

### ISSUE THREAD

**Issue by cronenborg** [ant-media/Ant-Media-Server#2958]
# Issue

Both Load Test AMI and docker image are no longer available

This documentation is no more applicable:
https://antmedia.io/webrtc-load-testing-in-5-minutes/

And also this one:
https://github.com/ant-media/Ant-Media-Server/wiki/Preparation-of-Test-Server-and-Running-Tests

because this docker image is no longer available:
https://raw.githubusercontent.com/ant-media/Scripts/master/Dockerfile_AntMediaTest

Please give me an available way to load test it.
Thank you.

**Comment by cemklc** [comment]
Hello, you can check issue #2975. Ant Media no longer supports dockerfile for testing. Some details and instructions on Load Test are provided there.

Thanks.
