### ISSUE TITLE
Fix readme download link

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2959]
Fix Ant Media Server Community 2.2.0 (Oct 21, 2020) link in Read me -> https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.2.0/ant-media-server-2.2.0-community-2.2.0-20201021_1516.zip

**Comment by mekya** [comment]
Resolved the conflicts and updated for the direct link. 

We've deleted v2.2.0 because there was a hotfix in that release and we've released 2.2.1 so that you don't find the direct link for 2.2.0.
