### ISSUE TITLE
Opera does not work with sample pages.

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#2974]
### Short description
In Linux, opera gives an error in index.html, play.html etc. and they do not work.
![Screenshot from 2021-02-16 21-32-31](https://user-images.githubusercontent.com/32591015/108106054-839a4000-709e-11eb-9236-0f7edbbd703c.png)

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.2.1
* Browser name and version: Opera 74.0.3911.107

### Steps to reproduce
1. Open Opera in Linux ( Ubuntu 18.04 )
2. Try to go index.html of AMS
3. Callback returns but local camera is not being reached

### Expected behavior
It should work

### Actual behavior
Does not work at all, throws the error in description
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by TerranceWolfe** [comment]
I have the same error on Windows 10 with Opera. I connect to the Linux Box which is running CENTOS 7.9 and Apache with PHP version 749. exact same error. Background Videos are not showing up, Also keeps reporting that I have an incorrectly formatted color tag in a place that has no tags at all.

**Comment by Sibicle** [comment]
I am having the same issue, macOS 10.3, Opera 76.0.4017.94 (x86_64)

![image](https://user-images.githubusercontent.com/4299422/117206541-3a5db080-adb0-11eb-9593-597dece46191.png)

seeing the color tag thing too, although I didn't think that was related 😬

**Comment by ahmedgadit** [comment]
Having the same issue, Opera 77.0.4054.60 and running on Ubuntu 20.04.2 LTS

**Comment by mekya** [comment]
The cause of the problem is explained at #3553
