### ISSUE TITLE
RTSP stream doesnt load on v 2.3.0 and weird bug upon downgrading versions

### ISSUE THREAD

**Issue by Matthew-Ayers** [ant-media/Ant-Media-Server#2978]
# Issue

### Short description
__Brief description of what happened__
Adding RTSP stream to stream source doesn't play, only on V2.3.0

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Add RTSP stream
2. Try to play it
3. Doesnt load

### Expected behavior
__Put as much detail here as possible__
Plays RTSP stream
### Actual behavior
__Put as much detail here as possible__
Doest load RTSP stream
 

For some reason, upon downgrading my version using 
"./install_ant-media-server.sh -t ant-media-server-2.2.1-community-2.2.1-20201029_0748.1.zip -r true"

I have a new application underneath LiveApp and WebRTCapp called root

**Comment by mekya** [comment]
Thank you for letting us know. I'm going to check the community edition for RTSP stream source.

**Comment by burak-58** [comment]
Hi @Matthew-Ayers,
Did you make a fresh install of v2.3.0-rc?
I did and could play RTSP stream. If you can share, logs I can check it.

**Comment by Matthew-Ayers** [comment]
I had done a fresh install twice of 2.3.0 and both times the error occured, I've since downgraded to the last stable release and that worked fine for it, Unfortunatly dont have the logs anymore

**Comment by mekya** [comment]
It may be about transport type with udp or tcp. By default, Ant Media Server uses tcp to fetch RTSP streams. You can change it to tcp or udp. 

```
settings.rtspPullTransportType=udp
```

ıf your issue persists, I recommend you scheduling a meeting @Matthew-Ayers

**Comment by Matthew-Ayers** [comment]
Okay thanks for your help.

**Comment by mekya** [comment]
Does that resolve your issue? @Matthew-Ayers

**Comment by Matthew-Ayers** [comment]
Yes thats fine, thank you.

**Comment by mekya** [comment]
Thank you.
