### ISSUE TITLE
Audio Source does not change in the index.html

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2982]
### Short description
Audio source does not change while publishing.

### Environment
* Ant Media Server version:Enterprise Edition 2.3.0-SNAPSHOT 20210215_0930

### Steps to reproduce
1. Start publising in index.html.
2. Start watching from player.html to observe the behavior.
3. Change to another audio source in index.html while streaming.
4. Check the results
 
### Expected behavior
Audio source should change i should be able to hear another source.

### Actual behavior
Audio source is not changing and i still hear the microphone that i started streaming.

**Comment by ncsu1** [comment]
I believe it's related to `updateLocalAudioStream` and `updateAudioTrack` in the javascript adaptor being hardcoded to look at track [0] with the addition of the audio node for gain control.
![image](https://user-images.githubusercontent.com/68408292/108524848-7c8d5080-729d-11eb-8c98-b64728b5a648.png)
If you get the audio tracks when the page loads, it looks correct, as shown above.
However, if I go and select another audio device, in this case "CABLE Output", the media tracks are reconfigured as such:
![image](https://user-images.githubusercontent.com/68408292/108525054-b2cad000-729d-11eb-8dc6-0492cab816df.png)
and I do not hear the CABLE Output, and I still hear the microphone.
