### ISSUE TITLE
Screenshare only publishing at the same while publishing with camera

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2983]
### Short description
When user is publishing already and wants to publish another stream with screenshare, it's not possible to do. Because user gets error and unable to select source and start publishing screenshare.
![image](https://user-images.githubusercontent.com/54481799/108529080-280dc380-72e5-11eb-9641-301b2a5f5ca6.png)

Solution proposition is, if user's camera is being used, discard the camera's and let user screenshare.

### Environment

* Ant Media Server version: Enterprise Edition 2.3.0-SNAPSHOT 20210215_0628

### Steps to reproduce
1.  Start streaming with webcam
2. Open another tab of index.html
3. See the error

### Expected behavior
If camera is already in use, user should be able to screenshare and maybe notify about it that camera is not available due to already in use.

### Actual behavior
Can't  screenshare because it is already disabled because camera/mic under usage.

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/143
