### ISSUE TITLE
VoD Rest Service api response issue, returning null

### ISSUE THREAD

**Issue by ar5-rehman** [ant-media/Ant-Media-Server#2988]
VoD Rest Service:

I am using the rest APIs to get the vod recorded videos but in response, I am getting null with 200 response.

response from the http://ip:5080/WebRTCAppEE/rest/v2/vods/{id}

{
    "streamName": null,
    "vodName": null,
    "streamId": null,
    "creationDate": 0,
    "duration": 0,
    "fileSize": 0,
    "filePath": null,
    "vodId": null,
    "type": null
} 

same for delete, not deleting the video file from the server, returning false.

**Comment by golgetahir** [comment]
Hello,

You need to call the REST for VoDs with the vod ID, try the following;

`curl -X GET "http://localhost:5080/LiveApp/rest/v2/vods/list/0/2"

An example return of this call:
[{"streamName":"bunny.mp4","vodName":"bunny.mp4","streamId":"file","creationDate":1614162164663,"duration":125952,"fileSize":10546620,"filePath":"streams/087626198649621394039225.mp4","vodId":"087626198649621394039225","type":"uploadedVod"}
`
This will get you the VoD list, every information about VoD will be there, grab the vodId from there and try;

`curl -X GET "http://localhost:5080/LiveApp/rest/v2/vods/087626198649621394039225"`

I believe this would work. 

Our web panel does not show vodId in the vod list, I am opening an issue to add it in web panel front end; 
https://github.com/ant-media/Ant-Media-Server/issues/3006

Thanks

**Comment by ar5-rehman** [comment]
Hi,

Thanks for your response, it really help us, we need to have all the VoD
id's, can we do that?

Thanks

**Comment by golgetahir** [comment]
You can get them up to 50 per offset with: https://antmedia.io/rest/#/VoD%20Rest%20Service/getVodList

Ex:

`curl -X GET "http://localhost:5080/LiveApp/rest/v2/vods/list/0/50"`

You can then extract it from the returned object.
