### ISSUE TITLE
Credentials of Manager of Ant Media Server

### ISSUE THREAD

**Issue by ashutoshpw** [ant-media/Ant-Media-Server#30]
What are the Credentials of Manager of Ant Media Server?

**Comment by davutcavdar** [comment]
You set the credentials of Ant Media Server in the first run.

**Comment by ashutoshpw** [comment]
Is there any way to reset the password in case I forgot the credentials?

**Comment by mekya** [comment]
Yeah if you remove the server.db file in /usr/local/antmedia then restart the server and it let you define new user.  server.db contains only user data right now.

**Comment by ashutoshpw** [comment]
Thanks
