### ISSUE TITLE
Make S3 save folder configurable

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#3005]
A customer asked to save the streams in specific folders,

https://groups.google.com/g/ant-media-server/c/VI9dAUAcMIs/m/fOcQV3JzAwAJ

**Comment by gambithunt** [comment]
Use case would be to keep storage specific to a particular stream and further down the line in the app, allow access to playback footage based on the unique stream ID that would correspond to the s3 folder name.

**Comment by mekya** [comment]
Hey @gambithunt ,


Is it ok if we provide an option in Ant Media Server S3 plugin to let it create a folder with the stream id for each stream?

I mean stream whose stream id is `stream1234` will be recorded to `stream1234/stream1234.mp4` in S3. 

Does that resolve your problem?

Regards,
A. Oguz

**Comment by gambithunt** [comment]
Hi Mekya

That would be perfect.

**Comment by mekya** [comment]
We will reference the commits with this issue. So that you'll see when there is a commit and snapshot is ready.

There is another similar issue like this
https://github.com/ant-media/Ant-Media-Server/issues/2753

I think we can make this implementation compatible with #2753. I mean if stream is recorded any specified subdirectory than it will be uploaded to the S3 with the same directory. Is it ok for you?

**Comment by gambithunt** [comment]
That would be perfect.

Once this is added, what would be the best way to update my server?

**Comment by mekya** [comment]
I think you get the latest snapshot for the community from sonatype
https://oss.sonatype.org/#nexus-search;gav~io.antmedia~ant-media-server~~~~kw,versionexpand

If you are using enterprise edition, you can ask the latest snapshot from the support channel. 
We've some plans to make the latest enterprise snapshot be downloadable on the accounts at antmedia.io  

Duplicated #2872

**Comment by gambithunt** [comment]
Thanks, we are using the enterprise edition, I'll ask for the latest snapshot once the update is committed.

Please keep me updated.

Thanks again

**Comment by mekya** [comment]
My pleasure. Keep in touch :)

**Comment by SelimEmre** [comment]
https://github.com/ant-media/Ant-Media-Server-Common/pull/294
https://github.com/ant-media/Ant-Media-Server/pull/3080
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/324
