### ISSUE TITLE
2.3 RC issue report

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#3008]
Please find a list of our issues below, some of these are specific to V2.3 and some are outstanding issues:
1. Audio would not connect in conferencing or through live streaming but video would. - (RTMP worked sometimes when WebRTC would not)
2. Audio would drift out of sync frequently, usually refreshing the browser will fix. - This is an ongoing issue and I would very much appreciate any remedy :) - I do know that this is usually caused by an end user that is connected on wifi or that has slow internet connection, however we have this issue with some users on fiber internet as well.
3. Random Publish Timeout Errors - unable to replicate frequently
4. Users behind firewalls had major issues connecting at all through WebRTC - RTMP would work however they could not stream or view a stream (WebRTC) behind any major firewall unless we enabled consistent NAT on the end users firewall (even then some would not connect). Please note we did not have this issue on previous versions and this issue goes away when we downgraded to V 2.2.1
5. WebRTC Publish through the browser has very bad audio no matter what way we try to use it. - When we publish through RTMP or OBS the audio is exponentially better. (Please note that for dialogue it is not as noticeable but for any type of music the audio is terrible, it sounds very crushed.)
6. Streams would ghost on the server (this is specific to V2.3) . By this I mean that our server thinks that a stream is still live when it is not. RTMP streams did this mainly however sometimes it would happen with WebRTC.
7. Lastly I don't know if this is an "issue" however was mp3 support removed from V2.3?

**Comment by k0nr4d** [comment]
I am also seeing your #5 with the bad audio. When doing WebRTC Ingress the audio is very staticy. This happens on 2.3.0 but not earlier versions.
