### ISSUE TITLE
Centos8 permission

### ISSUE THREAD

**Issue by TempleNode** [ant-media/Ant-Media-Server#3009]
The permission on centos  8 on 

/usr/local/antmedia/.javacpp
/usr/local/antmedia/work
 /tmp/vertx-cache

are pieces of crap.  Where is the x flag on those? 
I can't believe you put that software as the final release when is a piece of shit?  Do you even test it before you release it?

**Comment by mekya** [comment]
hi @TempleNode ,

Thank you for the feedback. I don't understand the problem you mention. Sorry it's my lack of information.  We can make it better with your support/feedbacks. 

Could you explain further?

I am not sure if it's related to official Centos support. Because CI test the software with Ubunt 18.04.

**Comment by TempleNode** [comment]
On those directory 
/usr/local/antmedia/.javacpp
/usr/local/antmedia/work
/tmp/vertx-cache

there is no execute (x) flag and when you run the program it said you do not have permission.

**Comment by mekya** [comment]
As far as I know there should be no (x) flag for these folders. 

Anyway, let us check. Thank you so much for the feedback.

**Comment by TempleNode** [comment]
and how you write files if there is not x flag?

**Comment by mekya** [comment]
Maybe I'm missing something but no need to have x(executable) permission when you write the files. Write permission is enough as far as I know. Maybe I'm having some misunderstanding. 

My colleague @muratugureminoglu has more experience in linux, Centos. He'll give you an answer.

**Comment by muratugureminoglu** [comment]
@TempleNode There is a x flag by default in the directories that I have checked. Can you share the exact error that you received with us? Maybe you have installed with an unauthorized user before.

**Comment by muratugureminoglu** [comment]
Thanks for the info.

I think 644 is sufficient for our application. Since jsvc will be removed in the future, these parts will be deleted. Thanks for your comment.

Regards.

**Comment by mekya** [comment]
Shall we provide a quick workaround for this issue @muratugureminoglu?

Because we don't know how much we need to work in removing the jsvc.

**Comment by muratugureminoglu** [comment]
This issue has been fixed. 

https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L276

Regards.
