### ISSUE TITLE
OBS->WebRTC, 20fps, plays fine on Chrome but skips like crazy on Firefox(Ubuntu 20.04 and Windows)

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3014]
- Add Adaptive bitrate and play the stream with Firefox.

**Comment by rjmtldo** [comment]
guys do u have any update on this?

**Comment by muratugureminoglu** [comment]
Hi,

I didn't face any problems when I tested it. Test environment and settings are as follows.

**Test Environment and Settings**

Ubuntu 20.04
Firefox 87.0
OBS 26.1
Nvidia Graphic Card

**OBS Settings**
Encoder > NVIDIA NVENC H.264
Bitrate > 2500 Kbps
Keyframe > 2
Profile > Baseline
Max-B-frames > 0
FPS > 20

**Ant Media Server Settings**
720p, 20fps ABR

**Example Video**
https://drive.google.com/file/d/1hR4PVcH6LWK0PY2lqS5zvgE-YZzrWnai/view?usp=sharing

Regards.
