### ISSUE TITLE
Support and Refactor Multiple Audio and Video Tracks in WebRTC Client  

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3028]
This feature will support 
- Multi language audio
- Single WebRTC connection in conference room

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/332

Merge request on gitlab.

**Comment by mekya** [comment]
Could you please add new methods to the WebSocket Reference?
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference
