### ISSUE TITLE
Can't call Rest API through HTTPS

### ISSUE THREAD

**Issue by infantryman77** [ant-media/Ant-Media-Server#3030]
# Issue

### Short description
Can't call Rest API through HTTPS (port 5443) nor through port 5080 when SSL is enabled.

### Environment

* Ubuntu 20.04 LTS
* Java version: 
* Community Edition 2.3.0
* Chrome 

### Steps to reproduce
1. Using Postman v8.0.6
2. Using GET with URL = https://myserverip:5443/LiveApp/rest/v2/broadcasts/count

### Expected behavior
Expecting return in the Body with "number": int

### Actual behavior
Only works with my new build without SSL Enabled.

 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by SelimEmre** [comment]
Hi @infantryman77,

I tried this issue in my test environment. It worked. It may be related to SSL Chain. Could you please check your SSL status here -> https://www.sslshopper.com/ssl-checker.html

If you have an issue with SSL Chain, please check this answer: https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M/m/C6Cb590VAgAJ

**Comment by mekya** [comment]
Hi @infantryman77 ,

Maybe the problem is about IP Filter which is enabled by default for only 127.0.0.1
https://github.com/ant-media/Ant-Media-Server/wiki/REST-Guide#security--ip-filtering

I mean are you using the same ip address in all of your tests?

**Comment by infantryman77** [comment]
> Hi @infantryman77,
> 
> I tried this issue in my test environment. It worked. It may be related to SSL Chain. Could you please check your SSL status here -> https://www.sslshopper.com/ssl-checker.html
> 
> If you have an issue with SSL Chain, please check this answer: https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M/m/C6Cb590VAgAJ

I'll give it a try then come back to you.

**Comment by infantryman77** [comment]
> Hi @infantryman77 ,
> 
> Maybe the problem is about IP Filter which is enabled by default for only 127.0.0.1
> https://github.com/ant-media/Ant-Media-Server/wiki/REST-Guide#security--ip-filtering
> 
> I mean are you using the same ip address in all of your tests?

The client making the request is in the IP Filter list as it is able to make request on HTTP.

**Comment by infantryman77** [comment]
> Hi @infantryman77,
> 
> I tried this issue in my test environment. It worked. It may be related to SSL Chain. Could you please check your SSL status here -> https://www.sslshopper.com/ssl-checker.html
> 
> If you have an issue with SSL Chain, please check this answer: https://groups.google.com/g/ant-media-server/c/UPdGaItfa6M/m/C6Cb590VAgAJ

It was the chain! I've had to use ./enable_ssl.sh -f /etc/ssl/certs/myfullchain_cert.pem -p /etc/ssl/private/mykey_priv.pem -c /etc/ssl/certs/mychain_chain.pem -d example.com

I was able to call the API using HTTPS on port 5443.

Thank you very much for pointing me out in the right direction.

**Comment by infantryman77** [comment]
For anyone wondering in the future, have a look at SelimEmre's solution.
