### ISSUE TITLE
Audio intermittently cuts out.

### ISSUE THREAD

**Issue by k0nr4d** [ant-media/Ant-Media-Server#3035]
### Short description
Audio intermittently cuts out in Enterprise Edition 2.3.0-SNAPSHOT 20210224_1217 using WebRTC Ingress after a few minutes of streaming.

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: Whatever antmedia installs
* Ant Media Server version: Enterprise Edition 2.3.0-SNAPSHOT 20210224_1217
* Browser name and version: Chrome newest

### Steps to reproduce
1. Stream for a few minutes via WebRTC

### Actual behavior
Audio stops being sent by the server and does not resume until microphone device is changed. Did not occur in 2.2.1.

**Comment by mekya** [comment]
Hi @k0nr4d ,

Do you see this problem in the release as well? 
Because we know a similar problem in the snapshots(RC) and fixed it.

**Comment by k0nr4d** [comment]
I see this in the March 2nd snapshot that was available for download today. In fact, it seems to crash the daemon entirely too.

(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
java.lang.NullPointerException
        at io.antmedia.enterprise.adaptive.AVFramePool.getAVFrame(AVFramePool.java:25)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.onOpusPacket(WebRTCEncoderAdaptor.java:1007)
        at io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor.lambda$getAudioDecoderFactoryFactory$0(WebRTCEncoderAdaptor.java:960)
        at org.webrtc.BuiltinAudioDecoderFactoryFactory.onAudioPacket(BuiltinAudioDecoderFactoryFactory.java:41)
Exception in thread "network_thread - 27933"
# Fatal error in: gen/sdk/android/generated_builtin_audio_codes_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 85
# last system error: 0
# Check failed: !env->ExceptionCheck()
# WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/usr/local/antmedia/lib/spring-core-4.3.28.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.3].
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: APR/OpenSSL configuration: useAprConnector [true], useOpenSSL [true]
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFO: OpenSSL successfully initialized [OpenSSL 1.1.1  11 Sep 2018]
Mar 08, 2021 12:48:16 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-apr-0.0.0.0-5080"]
Mar 08, 2021 12:48:16 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["https-openssl-apr-0.0.0.0-5443"]
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.58
Mar 08, 2021 12:48:16 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Mar 08, 2021 12:48:16 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Mar 08, 2021 12:48:17 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Mar 08, 2021 12:48:18 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Mar 08, 2021 12:48:18 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Mar 08, 2021 12:48:18 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Mar 08, 2021 12:48:18 PM org.glassfish.jersey.server.spring.SpringComponentProvider initialize
SEVERE: Spring context lookup failed, skipping spring component provider initialization.
Mar 08, 2021 12:48:18 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-0.0.0.0-5080"]
Mar 08, 2021 12:48:18 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["https-openssl-apr-0.0.0.0-5443"]
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.
(rtp_sender.cc:593): Tried to get DTMF sender from video sender.

**Comment by k0nr4d** [comment]
Further info - we were able to circumvent the issue by turning off stereo and forced sampling rate (so Mono and 48hz default Opus works, Stereo cuts out after a few minutes).

**Comment by burak-58** [comment]
Hi @k0nr4d,
Thanks for your report and info.
Could you please tell me if you have any configuration changes to reproduce it on my side?
How you switch between mono and stereo on you side?

**Comment by k0nr4d** [comment]
Hi @burak-58,
I've sent a msg to my worker to get the exact code/method. As soon as he gets back to me I will let you know.

**Comment by mekya** [comment]
Is there any update on this issue? @k0nr4d

**Comment by k0nr4d** [comment]
@burak-58 @mekya 

We had the following code (we used this for a while back from when we were using Wowza's earlier WebRTC implementation):

navigator.mediaDevices.getUserMedia({
  audio: {
    channelCount: 2
  },
  video: true
});

We removed channelCount to resolve.

**Comment by mekya** [comment]
thank you for the issue @k0nr4d ,

We schedule this issue for 2.3.1
