### ISSUE TITLE
Livestream screen cannot be displayed on PC which only has access to Local Network.

### ISSUE THREAD

**Issue by Lynvmili** [ant-media/Ant-Media-Server#3037]
### Short description
Livestream screen cannot be displayed on PC which only has access to Local Network.
However, the Livestream Screen is displayed normally when it connected to the Internet.

### Environment
* Network: Only allow access in LAN, not allowed to access the Internet
* Operating system and version (DockerFile): ubuntu 18.04
* Ant Media Server version: ant-media-server-2.1.0-community-2.1.0-20200720_1340
* Browser name and version: Google Chrome, version:  88.0.4324.190
* Using Docker Desktop

### Steps to reproduce
1. Create a Network environment only access in LAN (No Internet Access).
2. At the Live App screen, create a New Livestream from Stream Source. Here I use an IP Camera in LAN.
3. Click **"Play Stream"** button.

### Expected behavior
When I click **"Play Stream"** button, I can watch Stream from CameraIP.

### Actual behavior
When I click **"Play Stream"** button, the Stream from CameraIP cannot be viewed.
The camera screen always shows **“Stream will start playing automatically when it is live”**
The Console window displays error: **Error: ReferenceError: videojs is not defined**
Refer to the image below:

![Capture](https://user-images.githubusercontent.com/54199190/110290077-e71fe980-801c-11eb-97c9-4659d68a33d4.JPG)

**Comment by kputyra** [comment]
The player is assumed to have a connection to the Internet - it loads several external modules maintained by other communities. VideoJS is one example, another one is adaptor.js, which makes the browser compatible with the latest WebRTC standard. You can download those scripts locally - check the header section of LiveApp/play.html and/or LiveApp/player.html for a complete list - and update the HTML files accordingly.

**Comment by mekya** [comment]
Thank you for the issue. This PR fixes the problem. 
https://github.com/ant-media/StreamApp/pull/141

**Comment by mekya** [comment]
Duplicate https://github.com/ant-media/Ant-Media-Server/issues/2943
