### ISSUE TITLE
Make AppConfiguration Doc up to date

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3039]
https://github.com/ant-media/Ant-Media-Server/wiki/Application-Configuration-Documentation

I think we should use javadoc for that.

**Comment by cemklc** [comment]
https://github.com/ant-media/Ant-Media-Server-Common/pull/300

https://antmedia.io/javadoc/io/antmedia/AppSettings.html

https://github.com/ant-media/Ant-Media-Server/wiki/Application-Configuration-Documentation

https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Generate-AppSettings-Javadoc
