### ISSUE TITLE
About the S3 are you planing adding Wasabi soon

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [ant-media/Ant-Media-Server#3046]
I would like to be able to use Wasabi instead of Amazon s3 please let me know when is available

**Comment by k0nr4d** [comment]
+1, but not to adding Wasabi specifically. I would add a for ip/host of s3 storage - then it would be compatible with any S3/S3 compatible storage.

**Comment by SelimEmre** [comment]
Hi All,

As I saw Wasabi already compatible with S3. Let me check this issue in my test environment.

**Comment by k0nr4d** [comment]
@SelimEmre So is google drive and numerous others. At least in the PHP library, everything is identical and it's just a matter of swapping out the host.

**Comment by mekya** [comment]
@k0nr4d, you mean google cloud storage or google drive?
 Basically you just want to use all S3 compatible storages easily. That absolutely makes sense to me.

**Comment by k0nr4d** [comment]
@mekya Google cloud storage sorry. And yes, making it use ANY s3 compatible cloud storage is what i'm suggesting.

**Comment by mekya** [comment]
@SelimEmre 
do we need to specify different customizations for different S3 providers? Shall we make a generic solution as @k0nr4d recommends.

**Comment by SelimEmre** [comment]
Hi All,

I have added Wasabi guide in our [S3 guide](https://antmedia.io/how-to-record-streams-to-s3-compatible-systems/) blog post.

**Comment by mekya** [comment]
Hi @SelimEmre ,

Thank you for your work. Are you clear with @k0nr4d recommendation?

Regards,
A. OGuz
