### ISSUE TITLE
Server start.sh not working

### ISSUE THREAD

**Issue by punitagoel2403** [ant-media/Ant-Media-Server#3049]
When I run start.sh, it runs and says no such file or folder not found. I am unable to capture the file name as it closes itself and no log file is generated. Can you please check and confirm?

**Comment by SelimEmre** [comment]
Hi @punitagoel2403,

Could you please add a full of your error logs? It would great to understand your issue.

**Comment by punitagoel2403** [comment]
But there is no log file in the entire folder. Where do I get the error logs from?

**Comment by punitagoel2403** [comment]
waiting for your response

**Comment by cemklc** [comment]
Hello,

Can you try running with sudo ./start.sh

Log file is extremely important for resolving this problem. You can find the error statement by clicking search and then type 'file' or 'folder' and swipe up or down until you find the error statement.

It's Shift + Ctrl + F.

You might want to change the Scrollback value to Unlimited to not lose any lines:

Edit > Profile Preferences > Scrolling   under scroll back -->check  unlimited

Another common problem is permissions mixing. Have you used AMS as a service before? Or you always used with start.sh script?

**Comment by punitagoel2403** [comment]
[Error.docx](https://github.com/ant-media/Ant-Media-Server/files/6164528/Error.docx)
PFA
I am using it for the first time. Just downloaded the folder and ran start.sh

**Comment by cemklc** [comment]
Hello again,

Ant Media Server is build and optimized for Ubuntu systems. We can only recommend using AMS on windows devices with a Virtual Machine or with Docker.

After you install a Virtual Machine with Ubuntu Installed, you can follow this guide to install
https://github.com/ant-media/Ant-Media-Server/wiki/Installation

Best Regards,
Cem

**Comment by K12-K** [comment]
Hello,
[ErrorInUbuntu.log](https://github.com/ant-media/Ant-Media-Server/files/6211086/ErrorInUbuntu.log)
This is the error log generated when I try to run the server in Ubuntu System(Installed in Virtual Machine).

**Comment by punitagoel2403** [comment]
Hi,
Kindly reply to K12-K comment. He is from my team.

**Comment by mekya** [comment]
Hi,

You probably clone the repository or download the source. Are you sure that you downloaded the package from here?
https://github.com/ant-media/Ant-Media-Server/releases

**Comment by K12-K** [comment]
Hi,
Yes, I downloaded from your mentioned link.
Release:  Ant Media Server Community 2.3.0 (Mar 3, 2020).

**Comment by mekya** [comment]
Do you follows the instructions?
https://github.com/ant-media/Ant-Media-Server/wiki/Installation

Let me know if it's not working for you.
