### ISSUE TITLE
Camera still enable after calling TurnOffCamera function

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3050]
### Short description
When we call `TurnOffCamera` in WebRTC Javascript SDK, Camera should disable. But still enable.

### Steps to reproduce
1. Call `TurnOffCamera` function
2. Check camera usage. You will see it still in use.

### Expected behavior
I'm expecting camera should disable

### Actual behavior
Still enable after calling `TurnOffCamera` function.

**Comment by mekya** [comment]
I think @golgetahir has spent time for a similar issue. 

Please share your tests and experience @golgetahir

**Comment by golgetahir** [comment]
Hi,

TurnOffCamera does not release the camera instead sends a black frame. Please call closeStream to release camera.

Cheers

**Comment by mekya** [comment]
It's fixed #3420
