### ISSUE TITLE
Cannot share desktop in Safari browser

### ISSUE THREAD

**Issue by PawHusIC** [ant-media/Ant-Media-Server#3052]
### Short description
In my app there is a possibility to stream local camera, desktop or both. I use those methods from JS adapter:

- webRTCAdaptor.switchVideoCapture(streamId);
- webRTCAdaptor.switchDesktopCapture(streamId);
- webRTCAdaptor.switchDesktopCaptureWithCamera(streamId);

I test it in Chrome, Firefox and Safari and sharing a camera works well but I'm not able to share a desktop in Safari.
For _switchVideoCapture(streamId)_, a pop-up window appears asking for permissions and after agreeing, the image from the camera appears but for _switchDesktopCapture(streamId)_ nothing is happening.

**Ticket ID: 39444**

### Environment

* Operating system and version: macOS 10.15.7
* Ant Media Server version: Enterprise Edition 2.3.0-SNAPSHOT 20210224_1217
* Browser name and version: Safari 14.0.2

### Steps to reproduce
1. Create a simple app with AntMedia JS SDK
2. Open it in the Safari browser
2. execute: webRTCAdaptor.switchDesktopCapture(streamId)

### Expected behavior
Probably a pop-up window should appear asking for permissions and after agreeing, the desktop image should appear

### Actual behavior
Nothing is happening

 

### Logs
No logs in the console. No errors.

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you for letting us know. We'll check that

**Comment by mekya** [comment]
This is fixed in some commits and closing the issue. Please re-open if you think it's not working for you
