### ISSUE TITLE
Distro Support Message not displayed in install_ant-media-server.sh 

### ISSUE THREAD

**Issue by mackey1** [ant-media/Ant-Media-Server#3065]
### Short description
install_ant-media-server.sh does not display install error message when an invalid distro is found by the script. 

### Environment

* Operating system and version: Centos 7
* Java version: 
* Ant Media Server version: 2.3.0
* Browser name and version:

### Steps to reproduce
1. Setup an Ant install with an unsupported distro (e.g. Centos 7 not Centos 8)
2. run install_ant-media-server.sh 
3. Install does not work and no install error message is displayed to explain why. 

### Expected behavior

Incorrect shell script variable found on line 131 of file install_ant-media-server.sh 
Current line = "echo $mgs"
Correct line = "echo $msg"
Looks like there's a simple shell variable typo with an untested script use case when a distro is found which is not supported. 
A one character change fixes the problem ... "mgs" to "msg"

### Actual behavior

No message is displayed leaving the installer confused about why the install failed. 

 
### Logs

Not Applicable - Install shell script problem

**Comment by mekya** [comment]
Thank you for letting us know. We'll try to schedule this issue in this sprint
