### ISSUE TITLE
Can't install server on centOS 7

### ISSUE THREAD

**Issue by aksthelion** [ant-media/Ant-Media-Server#3067]
ls -l
-rw-r--r--. 1 root root 168803381 Mar 20 19:28 ant-media-server-2.3.0-community-2.3.0-20210301_0825.zip
-rwxrwxrwx. 1 root root     11222 Mar 20 19:27 install_ant-media-server.sh

./install_ant-media-server.sh -i ant-media-server-2.3.0-community-2.3.0-20210301_0825.zip -r true

Above command returns with no error, no progress, no message. How do you install this on centOS?

**Comment by SelimEmre** [comment]
Hi @aksthelion,

Unfortunately, v2.3 does not support centos7 due to some missed packages in Centos 7. Please check it for details -> https://stackoverflow.com/questions/64859409/why-ant-media-server-doesnt-support-centos-7

**Comment by SelimEmre** [comment]
Hi @aksthelion,

We are supporting Centos 8. You can use Centos 8 instead of Centos 7.
