### ISSUE TITLE
UnsecureContext message on Mac Chrome, Safari etc

### ISSUE THREAD

**Issue by aksthelion** [ant-media/Ant-Media-Server#3069]
I've installed media server on ubuntu.
http://myserveripaddress:5080/WebRTCApp
I get UnsecureContext error on MacOS Chrome, Safari and other browsers. Why is this and how to fix it?

![UnscureContext](https://user-images.githubusercontent.com/45408351/111917618-e6ee0800-8a78-11eb-8f59-dbfe3aa9ac6a.png)

**Comment by mekya** [comment]
Hi @aksthelion ,

Please install SSL to your server and access to the server via https

https://github.com/ant-media/Ant-Media-Server/wiki/SSL-Setup

Web browsers may not allow to access camera and mic from non-secure(http) pages

**Comment by aksthelion** [comment]
Yes, thanks figured it out already.

**Comment by mekya** [comment]
My pleasure. Great to know that it's working for you.
