### ISSUE TITLE
Provide configuration option to push CMAF and HLS to any Http Endpoint  

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3071]
Create an app configuration property for DashMuxer which is basically a Http Endpoint for CMAF and HLS.
When it's configured, dash muxer should push the content to the http endpoint

**Comment by SelimEmre** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/326
https://github.com/ant-media/Ant-Media-Server-Common/pull/299
