### ISSUE TITLE
Audio/Video sync issue in 2.3 with ABR

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#3088]
### Short description
When using ABR and playing from HLS/RTMP(by forward), it seems audio/video out of sync.
User says that this was not happening in 2.1.

##### Personal note:
I was able to get better results on 30 fps rather than 20 fps. In 20 fps, it is more apparent. This might related to source's fps and ABR fps relation, but not entirely sure about it.

### Environment
* AWS Instance c5.xlarge
* Ant Media Server version: 2.3

### Steps to reproduce
1. Turn 720p ABR on, recording enabled in mp4
2. Publish webrtc from browser
3. Try to play HLS stream or add RTMP endpoint and play there

### Expected behavior
No sync/lag in audio/video while playing.

### Actual behavior
There is a lag in audio/video while playing.

**Comment by mekya** [comment]
The fix has been pushed for this bug. The user is testing the fix.
