### ISSUE TITLE
Webm start - stop recording does not work

### ISSUE THREAD

**Issue by cemklc** [ant-media/Ant-Media-Server#3096]
When publishing from browser, auto recording works fine however, webm start - stop recording option creates an error and creates corrupted video files.

To reproduce:
AMS v2.3.0

Disable h264 and enable VP8.
Enable stream recording as webm
User starts broadcasting
Go to live streams page in actions click “Stop WebM Recording” 
Error pops up and second time, corrupted video files added to VoD

**Comment by mekya** [comment]
It's schedule for 2.3.1 and commit has been pushed for this bug
