### ISSUE TITLE
server version display

### ISSUE THREAD

**Issue by roeycohen** [ant-media/Ant-Media-Server#31]
it could be nice to see the server version in the dashboard in order to know that an upgrade process had succeeded or not.

**Comment by mekya** [comment]
I think this feature will be available later this week in the snapshot. 

@SelimEmre

**Comment by mekya** [comment]
This feature is added.  It is on the bottom left of the main panel. thank you @SelimEmre 
<img width="1472" alt="screen shot 2018-05-13 at 18 54 53" src="https://user-images.githubusercontent.com/3456251/39969057-4334642c-56df-11e8-8919-2864c0d7f059.png">

**Comment by mekya** [comment]
This feature will be 1.3.5+ version and it is available as snapshot right now. Closing this issue. Please open if it does not work for you.
