### ISSUE TITLE
A Prometheus exporter to provide Antmedia statistics

### ISSUE THREAD

**Issue by zafergurel** [ant-media/Ant-Media-Server#3122]
**Is your feature request related to a problem? Please describe.**
Antmedia can send statistics to Kafka in order to be monitored by an external system. This is explained in [this blog post](https://antmedia.io/how-to-monitor-ant-media-server/).
We use Prometheus for collecting usage data from our systems and if Antmedia provides an exporter for Prometheus, that would be great.

**Describe the solution you'd like**
A Prometheus exporter to collect statistics from an Antmedia instance.
There is the documentation to develop an exporter: https://prometheus.io/docs/instrumenting/writing_exporters/

**Describe alternatives you've considered**
There is an alternative as using Kafka to collect logs. But Prometheus is very widely used. And you don't need another solution to connect it to Grafana. For Kafka, you also need Logstash (as mentioned in [the blog post](https://antmedia.io/how-to-monitor-ant-media-server/)).

**Comment by MrXermon** [comment]
I already do this by using the json_exporter agains the AntMedia API without any issue. I‘ve dropped the details into a (sadly german) blog post some time ago: https://mrxermon.de/2021/01/antmedia-server-statistiken-in-prometheus/
If you need any help in setting up, feel free to hit me up.

Regardless of the option with the json_exporter in combination, a dedicated exporter gathering stats about the cluster status and stuff like that would be very interesting, too.

**Comment by zafergurel** [comment]
Thank you for the suggestion @MrXermon. Using json_exporter is a valid alternative.
As you mentioned, a dedicated exporter supplying detailed statistics would be a very neat feature.

**Comment by mekya** [comment]
Thank you so much @MrXermon. You're perfect!

**Comment by ddudx** [comment]
> I already do this by using the json_exporter agains the AntMedia API without any issue. I‘ve dropped the details into a (german only) blog post some time ago: https://mrxermon.de/2021/01/antmedia-server-statistiken-in-prometheus/ If you need any help in setting up, feel free to hit me up.
> 
> Regardless of the option with the json_exporter in combination with the API, a dedicated exporter gathering stats about the cluster status and stuff like that would be very interesting, too.

Hi @MrXermon  could you help provide the steps on how to achieve this?

**Comment by MrXermon** [comment]
@ddudx Blog got moved to a new address. Just take a look here: https://netaviator.xyz/blog/20210107-antmedia-server-statistiken-in-prometheus/

**Comment by ddudx** [comment]
> @ddudx Blog got moved to a new address. Just take a look here: https://netaviator.xyz/blog/20210107-antmedia-server-statistiken-in-prometheus/

thank you @MrXermon

**Comment by mekya** [comment]
Thank you guys. I'm just closing this issue. Please feel free to open if you have any issue.

**Comment by rjtoledo** [comment]
@MrXermon  would you mind sending here your Grafana Dashboard json file? 


best regards

**Comment by MrXermon** [comment]
> @MrXermon would you mind sending here your Grafana Dashboard json file?
> 
> best regards

Sadly, I don't have it anymore.

**Comment by rjtoledo** [comment]
It's ok thanks @MrXermon.
