### ISSUE TITLE
Optimize Ubuntu for Better Performance

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3130]
- Startup time
- Kernel Parameters

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/Performance-Tips

**Comment by mattskinosix** [comment]
Hi, 
I have premium edition edition,
How I can access this link? When I try to access i have this response from GitHub.
Thank you 
![Uploading Screenshot_20220510-232745.png…]()

**Comment by muratugureminoglu** [comment]
@mattskinosix 

It's still in the testing and not finished yet, please take a backup and try it.

[https://github.com/ant-media/Ant-Media-Server/wiki/Ant-Media-Server-Optimization](https://github.com/ant-media/Ant-Media-Server/wiki/Ant-Media-Server-Optimization)
