### ISSUE TITLE
Stream audio-only to RTMP

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3132]
Steps to reproduce: Stream audioTrack to WebRTCAppEE/stream1 Add RTMP endpoint, the error message is shown "RTMP Endpoint is not be saved", but it appears on the list of endpoints. Embed and play from dashboard works as expected but can't access RTMP stream. Is it possible to stream audio-only to RTMP? And if it is, what is the issue with our case?

**Comment by SelimEmre** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/334
