### ISSUE TITLE
port 5443 not found

### ISSUE THREAD

**Issue by VNAPNIC** [ant-media/Ant-Media-Server#3140]
I installed in the AWS Ubuntu 18

Step 

sudo ./install_ant-media-server.sh ant-media-server-enterprise.zip.zip

sudo systemctl status antmedia.service

sudo ufw allow 1935   (RTMP)
sudo ufw allow 5080   (HTTP)
sudo ufw allow 5443   (HTTPS)
sudo ufw allow 5554   (RTSP)

Then i check with the netstat -tulpn

tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      30758/jsvc.exec
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN      30758/jsvc.exec
tcp        0      0 0.0.0.0:39637           0.0.0.0:*               LISTEN      30758/jsvc.exec
tcp        0      0 xxxxxx:53           0.0.0.0:*               LISTEN      978/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1441/sshd
tcp        0      0 0.0.0.0:5080            0.0.0.0:*               LISTEN      30758/jsvc.exec
tcp        0      0 xxxxxxxx:5599          0.0.0.0:*               LISTEN      30758/jsvc.exec
tcp6       0      0 :::22                   :::*                    LISTEN      1441/sshd
udp        0      0 xxxxxxx:53           0.0.0.0:*                           978/systemd-resolve
udp        0      0 1xxxxxx:68         0.0.0.0:*                           938/systemd-network

I don't see port 5443

**Comment by SelimEmre** [comment]
Hi  @VNAPNIC,

Did you enable SSL? Ant Media Server uses 5443 as an HTTPS. You can enable SSL with [this guide](https://github.com/ant-media/Ant-Media-Server/wiki/SSL-Setup). Also please make sure you can access AMS dashboard via http://serverIP:5080 address.

Is it clear for you?
