### ISSUE TITLE
In case of publisher having a low internet connection, the quality (bitrate) of the publisher's stream is automatically adjusted.

### ISSUE THREAD

**Issue by YalimEristiren** [ant-media/Ant-Media-Server#3150]
In order to make sure that the video stream is not interrupted due to an instant change in the quality of internet connection on the publisher side, if the the quality (bitrate) of the publisher's stream is automatically adjusted, that will also provide a better streaming or conferencing experience for all parties (publisher & viewers, or conference attendees).

**Comment by mekya** [comment]
This is an expected behavior.  If the video quality is same under low bitrate, then latency will increase.
