### ISSUE TITLE
Stream doesn't work + questions

### ISSUE THREAD

**Issue by unbranched** [ant-media/Ant-Media-Server#3153]
Hi, I successfully streamed a video from a webcam but a second one doesn't work.
This second one is a D-Link DCS-5222L that streams via rtsp (sdp) or direct http (mjpeg).

The stream needs auth, I can correctly see the video with the url rtsp://user:pwd@IPAddress/live1.sdp .

When I add it to Ant, from UI the broadcast seems to be working but the web player never connects. Looking at the browser console, I see many 404 on m3u8 elements.

Some questions are:
-should I use LiveApp or WebRTCApp? What's LiveApp?
-from "New Live Stream" button should I choose IP Camera or Stream Source ?
-are user & password special characters handled correctly or should I html-encode them?

Here is the log:

> 2021-04-14 09:16:27,030 [Thread-1853] INFO  i.a.streamsource.StreamFetcher - StartStream called, new thread is started for 604285373842315351008701
> 2021-04-14 09:16:27,030 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - Preparing the StreamFetcher for rtsp://user:pwd@192.168.1.5/live1.sdp
> 2021-04-14 09:16:27,035 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - Setting rtsp transport type to tcp for stream source: rtsp://user:pwd@192.168.1.5/live1.sdp
> 2021-04-14 09:16:30,702 [vert.x-eventloop-thread-3] INFO  i.antmedia.statistic.HlsViewerStats - Update HLS viewer in stream ID:673654006448794830005890 increment count:5 decrement count:-4 diff:1
> 2021-04-14 09:16:31,641 [vert.x-eventloop-thread-0] INFO  i.a.s.StreamFetcherManager - Stream is not alive and setting quality to poor of stream: 604285373842315351008701 url: rtsp://user:pwd@192.168.1.5/live1.sdp
> 2021-04-14 09:16:32,660 [Thread-1854] ERROR io.antmedia.muxer.MuxAdaptor - io.antmedia.enterprise.adaptive.EncoderAdaptor
> 2021-04-14 09:16:32,660 [Thread-1854] INFO  io.antmedia.muxer.MuxAdaptor - vertx exist io.vertx.core.impl.VertxImpl@717e8d37
> 2021-04-14 09:16:32,660 [Thread-1854] INFO  io.antmedia.muxer.MuxAdaptor - adding HLS Muxer for 604285373842315351008701
> 2021-04-14 09:16:32,661 [Thread-1854] INFO  io.antmedia.muxer.HLSMuxer - hls time: 2, hls list size: 5
> 2021-04-14 09:16:32,661 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - 604285373842315351008701 stream count in stream rtsp://user:pwd@192.168.1.5/live1.sdp is 2
> 2021-04-14 09:16:32,661 [Thread-1854] INFO  io.antmedia.muxer.MuxAdaptor - Video format width:1280 height:720 for stream: 604285373842315351008701
> 2021-04-14 09:16:32,661 [Thread-1854] INFO  io.antmedia.muxer.MuxAdaptor - Audio format sample rate:8000 bitrate:64000 for stream: 604285373842315351008701
> 2021-04-14 09:16:32,661 [Thread-1854] WARN  io.antmedia.muxer.MuxAdaptor - addStream returns false hls for stream: 604285373842315351008701
> 2021-04-14 09:16:32,662 [Thread-1854] INFO  i.a.AntMediaApplicationAdapter - start publish leaved
> 2021-04-14 09:16:32,662 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - last dts-9223372036854775808 is bigger than incoming dts -1
> 2021-04-14 09:16:32,662 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - dts (0) is bigger than pts(-9223372036854775808)
> 2021-04-14 09:16:32,662 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - last dts0 is bigger than incoming dts 0
> 2021-04-14 09:16:32,662 [Thread-1854] INFO  i.a.streamsource.StreamFetcher - dts (1) is bigger than pts(0)
>

**Comment by unbranched** [comment]
@SelimEmre thanks for taking care of this issue. While you're looking at it, could you please answer to my frist two questions, that are just about application usage?

**Comment by mekya** [comment]
Hi @unbranched ,

We had a fix one of the similar issue in 2.3.1. Can you try that?

>-should I use LiveApp or WebRTCApp? What's LiveApp?

Both of them are same. You can use the one that you prefer. 

>-from "New Live Stream" button should I choose IP Camera or Stream Source ?

In your case, you need to use Stream Source because you directly add Stream Source. 

In IP camera, you need to add the onvif url of the IP Camera

>-are user & password special characters handled correctly or should I html-encode them?

I think user & password can be handled correctly.  Even if it does not work for you, we can schedule a meeting to take a look together.

**Comment by unbranched** [comment]
Thanks for the answers.
> Both of them are same. You can use the one that you prefer.
How come? Why are there 2 then?

>We had a fix one of the similar issue in 2.3.1. Can you try that?
Sadly v2.3.1 it has the same issue.

**Comment by mekya** [comment]
Ok. Let's schedule a meeting to understand the problem together?

**Comment by unbranched** [comment]
What do you need to know? Tell me any info could help you better find the problem?
I really appreciate the support you're giving me but having a full time job it's really unlikely I'll be able to do a meeting.

**Comment by mekya** [comment]
I see @unbranched 

Let us have the rtsp url if possible.

If you cannot share it publicly, you can send to selim@antmedia.io and mekya@antmedia.io

Btw, @SelimEmre is assigned to this issue. He's responsible to fix it

**Comment by unbranched** [comment]
I sent an email to Selim, thanks.

**Comment by SelimEmre** [comment]
I'm curious about Audio Codec parameter.
Here are the FFprobe outputs:
```
ffprobe 'rtsp://antmedia:Issue3153@151.0.212.43/live1.sdp'
ffprobe version 4.3.1-8ubuntu1~18.04.sav0 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='8ubuntu1~18.04.sav0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-crystalhd --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55eb3a5fa9c0] UDP timeout, retrying with TCP
Input #0, rtsp, from 'rtsp://antmedia:Issue3153@151.0.212.43/live1.sdp':
  Metadata:
    title           : RTSP/RTP stream 1 from DCS-5222LB
    comment         : live1.sdp with v2.0
  Duration: N/A, start: 0.033000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1280x720, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

**Comment by SelimEmre** [comment]
Hi All,

I searched `pcm_mulaw` audio codec for HLS playing. It seems HLS player already doesn't support it. You have 2 options for playing your stream.
- Using WebRTC for playing. But if you want to use WebRTC Playing, you need to have Enterprise Edition.
- Changing `pcm_mulaw` audio codec in your source.

**Comment by mekya** [comment]
> It seems HLS player already doesn't support it. 
Just let me give a comment about it. It's actually a container problem not a player problem. HLS format does not support `pcm_mulaw`
 
Additionally, adding one adaptive bitrate makes the stream play for HLS as well.

**Comment by unbranched** [comment]
Sorry, I didn't see your answers until today.
Sadly the audio codec can't be changed, so it looks like I need to give up on this webcam.

Thanks a lot both for your support!
