### ISSUE TITLE
WebSocket connection gets closed when publishing stream on chrome 90

### ISSUE THREAD

**Issue by ksinas** [ant-media/Ant-Media-Server#3164]
### Short description
Yesterday I upgraded my browser to chrome 90. When I try to publish stream, websocket connection gets closed. None of the default examples work anymore, neither my own implementation.

Disconnect reason:
"The decoded text message was too big for the output buffer and the endpoint does not support partial messages"

### Environment

* Operating system and version: macOS 11.2.3
* Ant Media Server version: Enterprise Edition 2.3.0 20210302_1431
* Browser name and version: Chrome 90

### Steps to reproduce
1. Start publishing stream
2. 
3.

### Expected behavior
Stream to be published

### Actual behavior
Socket disconnects 
    code: 1009
    reason: "The decoded text message was too big for the output buffer and the endpoint does not support partial messages"

**Comment by ksinas** [comment]
The problem is sdp message size 
```js
// webrtc_adaptor.js
const jsCmd = {
    command: 'takeConfiguration',
    streamId,
    type: configuration.type,
    sdp: configuration.sdp, // this stringified is over 7800 characters long  
};
```

**Comment by mekya** [comment]
Thank you for the update. We'll schedule this in this sprint.

**Comment by mekya** [comment]
Hi @ksinas ,

Thank you for the report again. 

You can get the latest snapshot from your account at antmedia.io and changes in latest snapshot is available here
https://antmedia.io/latest-snapshot

We're going to release v2.3.2 probably today and update marketplaces

**Comment by Nyceane** [comment]
Hey @mekya, problem still persist, just updated server to 2.3.2 and i am still encountering the problem

<img width="1345" alt="Screen Shot 2021-04-27 at 2 04 03 PM" src="https://user-images.githubusercontent.com/271430/116314579-22f54680-a764-11eb-995e-1304f9317b59.png">


<img width="1680" alt="Screen_Shot_2021-04-27_at_5 01 23_PM" src="https://user-images.githubusercontent.com/271430/116314533-1113a380-a764-11eb-86a6-204fa96df14e.png">

**Comment by mekya** [comment]
Hi @Nyceane , 

I get several confirmations about this issue from the users. 
I think the problem on your side is something different. 
Please try to use the following link. 
```
https://server_domain:5443/WebRTCAppEE/
```

If it still does not work for you, we can schedule a meeting to understand the problem.

**Comment by AlexandreBourdeaudhui** [comment]
Hello, i have the same issue here, on application initialization, i get the message "The decoded text message was too big for the output buffer and the endpoint does not support partial messages", the current WebSocket is disconnect, and another Websocket is alive, which i have only ping/pong request


* Operating system and version: macOS 11.2.3
* Ant Media Server version: Enterprise Edition 2.3.2 20210422_0456
* Browser name and version: Chrome 90

**Comment by mekya** [comment]
Hi @AlexandreBourdeaudhui ,

Is it possible to give a reproduce scenario step by step? Because I'm using MacOS 11.2.3 and Chrome 90. 

I don't encounter this problem again.

**Comment by AlexandreBourdeaudhui** [comment]
Hi, thanks for the response.
I'm trying to isolate this part of my application to provide you a reproduce repository. If needed, i can open a request support too.

And for the reproduce scenario, step by step, i think it's classic scenario don't know which detail you need… When i start the application, we join automatically a room and start to publish. When we're sending the `takeConfiguration` event, the WesbSocket signal is closed.

<img width="1243" alt="Capture d’écran 2021-05-06 à 14 46 31" src="https://user-images.githubusercontent.com/24500083/117300637-0bac0c80-ae7a-11eb-9e14-de1b90713fc9.png">

<img width="1122" alt="Capture d’écran 2021-05-06 à 14 43 08" src="https://user-images.githubusercontent.com/24500083/117300238-a821df00-ae79-11eb-815e-de5cbf443ae0.png">

**Comment by mekya** [comment]
Hi @AlexandreBourdeaudhui ,

I did a basic testing on sample conference.html and I could not reproduced the problem in 2.3.2. Are you sure that you've upgraded the server?

Secondly, if you are using a custom application, probably you need to delete it and re-create in v2.3.2

Step by step scenario is something like this 

1. Go to the sample WebRTCAppEE/conference.html
2. Let two people join the conference

Expected:
Two people will have a conference call

Actual:
Websocket connection drops and people will not have a conference call.

**Comment by AlexandreBourdeaudhui** [comment]
Hi @mekya ! I just send a request support w/ system info.
If necessary, i created a reproduce repository : https://github.com/AlexandreBourdeaudhui/Antmedia

**Comment by mekya** [comment]
Hi @AlexandreBourdeaudhui ,

I had just find sometime to check the github notifications. I've returned to my daily routine. 

I find your ticket and my colleague has responded you one week ago and made a follow-up two days ago. 

Have you received that?

**Comment by AlexandreBourdeaudhui** [comment]
Hey, sorry, it was a long week-end for me 😅 !
Yes i received that, I will answer it.
Thanks 🙏.

**Comment by mekya** [comment]
It's a pleasure :)
