### ISSUE TITLE
The image is freezing every time for Ant media 2.3

### ISSUE THREAD

**Issue by Juanfree** [ant-media/Ant-Media-Server#3165]
### Short description
We are using Ant media server in AWS.

The current version that we are using is 2.3

When we start to emit some streaming, each time the image is freezing.

We are emitting 720 with 2 MB of bitrate.

### Environment

The same machine that is in the AWS marketplace. 

Ant media version 2.3

### Expected behavior
Emit the stream and watch it without these freezes.

Thanks in advance.

**Comment by mekya** [comment]
Hi @Juanfree ,
If you are sending with RTMP,  are you sure that you're using baseline for video encoding?

**Comment by k0nr4d** [comment]
@Juanfree Further to @mekya  's comment, if you are using RTMP please make sure your FPS matches the output (which is 20fps by default). We had a similar issue with frame dropping and freezing and doing this resolved it.

**Comment by mekya** [comment]
Thank you so much @k0nr4d for adding your comment.

**Comment by cemklc** [comment]
Hello, I am the responsible developer for this issue. Can you give any updates about it?

**Comment by cemklc** [comment]
Hello, due to the inactivity, I'm closing this issue. However, you are always welcome to reopen the issue again.
