### ISSUE TITLE
Remove RTMP Endpoint doesn't work properly in MongoDB

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3169]
### Short description
RTMP Endpoint removing doesn't work in MongoDB structure.

### Environment
* Ant Media Server version: v2.3.2 SNAPSHOT

### Steps to reproduce
1. Use Mongo DB.  
2. Add any RTMP Endpoint
3. Remove RTMP Endpoint

### Expected behavior
It should remove it.

### Actual behavior
It's not removing. 

### Logs
There is no fatal error. Also, Remove RTMP Endpoint REST Service returning true. But it's not removing.

**Comment by mekya** [comment]
I've used add/remote RTMP endpoint through web panel. I cannot re-produce this issue. It's working for me. 
Do you have any other idea?
