### ISSUE TITLE
Stream quality is not good for specific sample video

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3170]
### Short description
One of our users reported this issue. He is using [this video](https://www.dropbox.com/s/x1sw5noxv7qyrnr/dj%20light.mp4?dl=0) as background. But for some reason, MP4, HLS  and WebRTC streams seem to blur.

**What I did to solve it?**
- I converted to baseline profile. 
- I increased the bitrate parameter on the publisher side

Ticket ID: 38998

### Environment
* Ant Media Server version: v2.3.2 SNAPSHOT

### Steps to reproduce
1. Add 720p adaptive option 
2. Stream this video with OBS
3. Watch HLS, VoD and WebRTC

### Expected behavior
I'm expecting even HLS and VoD files stream quality should better.

### Actual behavior
I couldn't achieve

### Logs
There are no error logs.

**Comment by SelimEmre** [comment]
As my tests, I have found somethings about this issue:
1- I was tried with 30 FPS and 1080p. But video resolution is 720p and FPS is 20.
2- I was tried with Zerolatency and Fastdecode for tune parameter. 
When I changed above details about my test environment, video quality is changed.

**Comment by mekya** [comment]
I'm closing this issue. Please feel free to re-open if you think it's not working for you.
