### ISSUE TITLE
Ice State disconnected - Better ice state management

### ISSUE THREAD

**Issue by fabioginzel** [ant-media/Ant-Media-Server#3181]
### Short description
Disconnected ice state should not bring down the connection

### Expected behavior
According to the documentation "diconnected"  it is a temporary state
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState

**Comment by mekya** [comment]
Hi @fabioginzel ,

Yes you're right. We'll improve state management. Moving to the backlog to schedule.

**Comment by sudharsans85** [comment]
On the same lines, is it possible to keep ice connection & websocket independent ?Currently on ice disconnection, we end up recreate adaptor(web)/webrtcclient(android). And with this websocket connection is newly made and this is additional overhead. In case of internet lost and restored, both will have to be reset, but most of the times for a ice disconnection, i happen to notice that websocket is intact.

**Comment by golgetahir** [comment]
Hi @sudharsans85

As you stated, we have merged some commits for disconnected state to keep the connection until it goes to failed state or the connection loss drops the websocket connection. Therefore disconnected state is actually separated from the websocket connection but failed state is not recoverable and it kills everything. I am still researching about this issue if we can do more than this to recover. You can try the new snapshot and get back to us if you see any more problems, it would be very nice for us.

https://antmedia.io/latest-snapshot/

Cheers
