### ISSUE TITLE
Audio distortion/buzzing noises in 2.3.2 EE

### ISSUE THREAD

**Issue by k0nr4d** [ant-media/Ant-Media-Server#3196]
### Short description
Occasionally, during WebRTC ingress there are weird buzzing noises for a couple of seconds.  Issue did not exist in 2.3.1 or 2.3.0. recreatable on multiple servers. 

### Environment
* Operating system and version: Ubuntu 18.04
* Ant Media Server version: 2.3.2 20210422_0456 Enterprise Edition 
* Browser name and version: Chrome 90
* Adaptive streaming turned on, HLS disabled, VP8 disabled

### Steps to reproduce
1. Start a stream with WebRTC, play some music or something
2. Sooner or later on egress of the stream you will hear some kind of strange buzzing noise for a few seconds once in a while. It's not super often but it does occur.

**Comment by mekya** [comment]
Thank you for the report. Let's schedule this issue in this sprint.

**Comment by k0nr4d** [comment]
Client just told me that the recordings of the stream **did not** contain the buzzing noise so it appears to be happening at the broadcast end not the processing/adaptive end. I have not verified this myself.

**Comment by k0nr4d** [comment]
@burak-58 Please disregard the above, the buzzing is in fact in the recording. It is in all versions of the recording (so both 720 and 480 in our case). I'm preparing an MP3.

**Comment by k0nr4d** [comment]
@burak-58 
https://mechbunny.net/konrad/antmedia_buzzing.mp3 (there's a shower in the background)
This one is exceptionally long, usually it lasts only 1 or 2 seconds. It's not incredibly frequent, but it seems to happen on most streams.
