### ISSUE TITLE
Reconnecting a new stream with the same name does not work 

### ISSUE THREAD

**Issue by roeycohen** [ant-media/Ant-Media-Server#32]
when a publisher and a consumer already connected using web sockets, stopping the stream and then republishing a new stream with the same id doesn't work on the consuming side and he never gets "play_started" event even that sdp data exchange occurred.

ant-media-server-enterprise-1.4.0-SNAPSHOT-180404_1253

hope i've explained my self good enough...

**Comment by burak-58** [comment]
Hi,
I have checked the issue you defined with 1.5.2 and I did not encounter with the problem. Can you check it with newer versions?
