### ISSUE TITLE
Support bi-directional voice in publish & play model

### ISSUE THREAD

**Issue by rajvarshu** [ant-media/Ant-Media-Server#3211]
**Is your feature request related to a problem? Please describe.**
 We are using AntMedia Enterprise Edition 2.3.0 20210302_1431 license. We have the following requirement

1. Android/Client screencast/broadcast along with audio
2. Portal/Web needs to play this broadcasted stream 

As of now we are using publish(Android will publish) and play(portal plays the stream). Is it possible to publish audio stream also from portal/web and listen it on Android client. If yes, could you please help us to achieve this?

**Describe the solution you'd like**
Publish audio stream from portal/web & listen it on the client

**Comment by rajvarshu** [comment]
Any update on this?

**Comment by mekya** [comment]
Thank you for explanation. Yes there is a way for doing it. I'll try to schedule this issue to let one of my colleague help you.

**Comment by SelimEmre** [comment]
Hi @rajvarshu,

You need to use 2 WebSocket connections for your requirements. One of them is for publishing. The other one is for playing. Is it clear for you?

**Comment by mekya** [comment]
@SelimEmre, could you please give some more explanation? It's at least not clear for me.

**Comment by SelimEmre** [comment]
Hi @rajvarshu,

I have created a bi-directional publish/play audio sample page. Could you please check it? https://gist.github.com/SelimEmre/214b811d737f9f23fd86ecafe0d2a323

**Comment by rajvarshu** [comment]
@SelimEmre thank you for your response.

**Comment by SelimEmre** [comment]
Hi @rajvarshu,

I have configured with browser. So, mobile and desktop behavior should be same.
