### ISSUE TITLE
AWS Cloud Instances Have Syntax issues in  /etc/apt/apt.conf.d/20auto-upgrades

### ISSUE THREAD

**Issue by justinh24** [ant-media/Ant-Media-Server#3215]
### Short description
When running apt (as is done by enable-ssl.sh) on AWS cloud configuration, the following error is returned:
```E: Syntax error /etc/apt/apt.conf.d/20auto-upgrades:3: Extra junk at end of file```

### Environment

* AWS Enterprise Install Version 2.3.2

### Steps to reproduce
Launch your official AWS cloud instance for Version 2.3.2 (I am on US-WEST-2.  Assuming this affect all AMI's but not sure).
type ```apt```

### Expected behavior
apt to not throw errors

### Actual behavior
apt throw error:
```E: Syntax error /etc/apt/apt.conf.d/20auto-upgrades:3: Extra junk at end of file```

 I am pretty sure the line referenced in the error was set to prevent automatic upgrades (which I originally submitted as a feature request since it delays server startup if you need to install SSL certificates). 

Adding a semi-colon to the end of line 3 of 20auto-upgrades fixes this issue.

**Comment by mekya** [comment]
Hi @justinh24 ,

Thank you so much. We've fixed this issue and provide a new release(2.3.2.1) to the AWS marketplace. 

Regards,
A. Oguz

**Comment by mekya** [comment]
I'm closing this issue. Please feel free to re-open if there is still a problem.
