### ISSUE TITLE
Stop WebM Recording option not working on dashboard

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3218]
Short description
Observed this issue during testing. The stop WebM recording option is not working on dashboard during the stream broadcasting and giving popup error on screen "WebM recording service failed". 

Environment
Ant Media Server version: v2.3.2

Steps to reproduce
1. Enable VP8 codec support
2. Enable WebM recording
3. I am using OBS to ingest the stream.
4. Try to stop the stream by stop webm recording option.

Expected behavior
It should work.

Actual behavior
It is not stopping when we try to stop. It will only stop once the stream will end.

**Comment by cemklc** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/381
