### ISSUE TITLE
Add a short pause when switching resolutions on stream

### ISSUE THREAD

**Issue by cemklc** [ant-media/Ant-Media-Server#3236]
Currently: The stream becomes noisy and blurry for a small duration when switching resolutions

Requested: When switching resolutions, add a short pause until the stream is available and continue from there.

Current Example#1: https://antmedia.slack.com/files/U016ERCQD2M/F01UXBBQVDL/antmedia.mov
Requested Example#2: https://antmedia.slack.com/files/U016ERCQD2M/F0202NX7JAD/twitch_1.mov

**Comment by rjmtldo** [comment]
Thanks, @cemklc  looking forward to this feature

**Comment by rjmtldo** [comment]
Hi @cemklc  when do u plan to release this?

**Comment by eneskuluk** [comment]
It is in the pull request currently and will be available with the next release @rjmtldo

**Comment by rjmtldo** [comment]
@eneskuluk  thank you for the update :)

**Comment by rjmtldo** [comment]
that would be 2.3.3 right?

**Comment by eneskuluk** [comment]
If the pull request is approved until that time, yes it would be 2.3.3.

**Comment by mekya** [comment]
@rjmtldo it's merged and we're running enterprise master branch. I think something will be deployed later today.

**Comment by rjmtldo** [comment]
@mekya  thanks mekya for  the info

**Comment by rjmtldo** [comment]
Hi, @mekya I just noticed that when it automatically switch its quality the screen tearing is still visible but If I manually change it works fine there's a short pause on a video stream.

**Comment by mekya** [comment]
I see.  I think it's working for you now?

**Comment by rjmtldo** [comment]
Hi, @mekya  it works when we manually switch to each resolution,  but when the stream auto switches The stream becomes noisy and blurry. it doesn't have a short pause and loading icon just like the implementation when manually switching its resolutions.

**Comment by mekya** [comment]
Yes you're right. In auto switch, server decides when to switch the quality so that player does not have a short pause.

We can think implementing a solution that client may decide when to switch the quality and then it can pause and start again. I'm not sure for this implementation but you can implement that javascript stuff in your side.

**Comment by rjmtldo** [comment]
Hi @mekya how can we achieve this stuff we don't any coding experience will your side can help fix this?

**Comment by mekya** [comment]
Hi @rjmtldo ,

Yes, we can put it to the backlog. Could you please create another issue for this?

**Comment by rjmtldo** [comment]
thanks @mekya  we will create new issue.

**Comment by rjmtldo** [comment]
is it possible to change the current loading.gif of our custom choice of  loading.gif?
