### ISSUE TITLE
Update Cluster guides for MongoDB MD5 password

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3242]
AMS changed to password structure(MD5) on latest version. We need to update Cluster guides for it.

**Comment by lauchdown** [comment]
Yes I just made an AWS cluster and the first admin password seems to be encypted so I can't login.

**Comment by SelimEmre** [comment]
Hi @lauchdown,

I have just explained these details in this guide: https://groups.google.com/g/ant-media-server/c/G2MmQEkN3L0/m/ah2G4G8JBAAJ
