### ISSUE TITLE
is there any way that i can use mp4 file as input for a WebRTC Stream

### ISSUE THREAD

**Issue by ysureshbabu** [ant-media/Ant-Media-Server#3245]
is there any way that i can use mp4 file as input for a WebRTC Stream or 
any jar application with in Antmedia that helps us with this

**Comment by k0nr4d** [comment]
You can stream it via RTMP
ffmpeg -re -i ~/INPUT_FILE -vcodec libx264 -profile:v main -preset:v medium -r 20 -g 60 -keyint_min 60 -sc_threshold 0 -b:v 2500k -maxrate 2500k -bufsize 2500k -filter:v scale="trunc(oha/2)2:720" -sws_flags lanczos+accurate_rnd -acodec libfdk_aac -b:a 96k -ar 48000 -ac 2 -f flv rtmp://1.2.3.4/app/stream_id_goes_here

**Comment by ysureshbabu** [comment]
[antmedia_ce_logs.zip](https://github.com/ant-media/Ant-Media-Server/files/6463990/antmedia_ce_logs.zip)
[antmedia_ee_logs.zip](https://github.com/ant-media/Ant-Media-Server/files/6463997/antmedia_ee_logs.zip)
attached the logs of:
1. antmedia server & error
2. the command run.sh is being run in nohup, so attached nohup.out as well

please help with the responses for the below queries 

1. Is the load testing works with CE edition of server or not?
2. Same tool works fine with test.antmedia.io server, but strangely doesn't work well with EE edition.

**Comment by golgetahir** [comment]
Hi

The load test tool does not developed for streaming mp4 as a webrtc stream though it seems like way to do it, well it is not. You can accomplish such task by using playlist which is given in this documentation; 

https://github.com/ant-media/Ant-Media-Server/wiki/Playlist

Thanks.

**Comment by rvjtech** [comment]
Thanks for the reply.  I am sorry to say, but the documentation is very
poor.  In the link below, it explains how to create a playlist.  But
nothing is shown, how to broadcast or schedule the broadcast in the case of
Linear Live streaming.  At the end of the article, there is a link on how
to play linear live streaming which takes us to regular playing.  There is
no mention of how to play Linear Live streaming or scheduling of the same.

https://github.com/ant-media/Ant-Media-Server/wiki/Playlist

**Comment by golgetahir** [comment]
Hi,

mr. @mekya maybe I can adjust the documentation about playlist as the given feedback.

The thing why it goes to the regular playing is that there are no difference between playlist item and regular playing. When you create a playlist object, there will be streamId assigned to it, which you can use that id like a regular stream and use the REST methods for regular stream as well as playlist.

https://antmedia.io/rest/

There is
no mention of how to play Linear Live streaming or scheduling of the same.

You can play it directly from the streamId like I mentioned above and scheduling can be done with start method of rest in your application level: https://antmedia.io/rest/#/BroadcastRestService/startStreamSourceV2

**Comment by rvjtech** [comment]
Thanks. With this explanation it is clear and we are able to broadcast the
play list.

**Comment by ysureshbabu** [comment]
Hi,
Thanks. we were able to use to instructions and achieve the expected results.
However there is a query that is still pending - still we are unable to use the load test -- https://github.com/ant-media/Ant-Media-Server/wiki/Load-Testing.
Our main intent behind the query was to load test the system so that we can have a baseline of the usage
Please assist 

Thanks
Suresh

**Comment by golgetahir** [comment]
Hi,

The exact steps I am taking is;

Go to the test tool and run;
​
`./run.sh -f test.mp4 -m publisher -n 1`

​It will create a broadcast named myStream as default on localhost:5080/WebRTCAppEE

Then run;

`./run.sh -m player -n 100 -u false`

It will create 100 viewers for myStream at localhost:5080/WebRTCAppEE , if you want to change the parameters reference this table;

Flag      Name           Default        Description                 
----      ----           -------        -----------   
f         File Name      test.mp4          Source file* for publisher output file for player        
s         Server IP      localhost      server ip                   
q         Security       false          true(wss) or false(ws)      
l        Log Level       3               0:VERBOSE,1:INFO,2:WARNING,3:ERROR,4:NONE
i         Stream Id      myStream       id for stream               
m         Mode           player         publisher or player         
u         Show GUI       true           true or false               
p         Port           5080           websocket port number 
v         Verbose        false          true or false 
n         Count          1              Number of player/publisher connctions 
k        Kafka Broker    null            Kafka broker address with port
r         Publish Loop      false           true or false
c         Codec           h264            h264 or VP8 
d         Data Channel    false           true or false

**Comment by ysureshbabu** [comment]
Hi,

Thanks . will test it out 

Regards
Suresh

**Comment by mekya** [comment]
Thank you for the comments. 

Closing the issue. Please re-open if it does not work for you.
