### ISSUE TITLE
Adaptive bitrate does not upscale

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#3247]
### Short description
Adaptive bitrate not upscale encoding creates problems in webrtc since the resolution varies in webrtc, if it does not encode some nodes can't get the stream.

### Steps to reproduce
1. Add an high Adaptive Bitrate 
2. Send a lower resolution stream
3. Server does not encodes the stream

### Expected behavior
Server should encode the stream

### Actual behavior
Server does not encode

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/350

**Comment by mekya** [comment]
Thank you for the work.  It's merged. 

Nevertheless I think something is missing(It's not related to your implementation), I don't want to be perfectionist to stop the merge. Maybe we can revisit this issue again later. 

I'm just adding some comments for the related code snippets
