### ISSUE TITLE
[iOS] Stream disconnected after going back from the background

### ISSUE THREAD

**Issue by haihoang88** [ant-media/Ant-Media-Server#3256]
**Is your feature request related to a problem? Please describe.**
I'm using AntMediaClient library for iOS. Currently, after publishing the stream successfully (Can view it in the server). I must keep the device awake in order to maintain the stream.
If I bring the app to the background, wait about 10 seconds and bring it up, the stream is disconnected already and cannot be resumed

**Describe the solution you'd like**
Stream can still continue to work until client.stop() is called

Is there anything that I'm missing to handle this case?

**Comment by mekya** [comment]
hi @haihoang88 ,

Thank you for the question. Could you please try to add background capability to the app?

When I add the following capability, it's not disconnected when the app goes background.  

<img width="1512" alt="Screen Shot 2021-06-14 at 15 59 37" src="https://user-images.githubusercontent.com/3456251/121896271-c8bb3f80-cd29-11eb-8909-b78cd002bb62.png">

Could you please try it on your end?

Regards,
A. Oguz

**Comment by haihoang88** [comment]
Hi @mekya ,

I confirmed that when enabling background mode, the stream doesn't disconnect when putting to the background.
But it still gets disconnected if I answered a phone call (or Skype, Slack... call).
I wonder if we can somehow resume the stream after such calls?

Thanks & Best Regards.

**Comment by mekya** [comment]
Hi @haihoang88 ,

I've not tested yet but as I read, enabling `Audio, AirPlay, and Picture in Picture` may help. It's mostly a permission issue in iOS side. 

Can you try and let us know? I can continue searching and trying to find out a solution for you.

PS: Even if I maintain the iOS SDK, I'm not originally an iOS developer. My knowledge in iOS is limited. Fortunately, I'm learning and I can continue this work for you.
