### ISSUE TITLE
Analyze 32 core publishing performance under various ABR configurations.

### ISSUE THREAD

**Issue by DespicableSensei** [ant-media/Ant-Media-Server#3264]
### Short description
Analyze the performance impact of using multiple ABR options and optimization routes for maximum number of publishers. Focus on 32 core instances.

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by cemklc** [comment]
Hi, I will be doing the analysis of the ABR load tests. Are you focusing on a particular configuration for ABRs and can you tell me your experiences?

**Comment by cemklc** [comment]
32 core instance: test with different ABRs:
Important note: the load on cpu does not increase linearly per stream. The load vs stream count curve resembles a logarithmic curve. So the estimations of maximum number of streams written here are the worst case scenarios.


2160p: 74% CPU with 16 streams -----> estimated 5% cpu per stream at max load, 17 streams
1080p: 49% CPU with 16 streams -----> estimated 3% cpu per stream at max load, 26 streams
720p: 26% CPU with 16 streams -------> estimated 1.5% cpu per stream at max load, 50 streams
480p: 13% CPU with 16 streams -------> estimated 0.8% cpu per stream at max load, 100 streams
360p: 10% CPU with 16 streams -------> estimated 0.8% cpu per stream at max load, 128 streams
240p: 8% CPU with 16 streams -------> estimated 0.5% cpu per stream at max load, 200 streams

**Comment by mekya** [comment]
What if there is no adaptive bitrate?
