### ISSUE TITLE
upload of the stream is not happening on Minio ( amazons3 like storage )

### ISSUE THREAD

**Issue by ysureshbabu** [ant-media/Ant-Media-Server#3277]
Hi,

we are using minio storage, which is an amazon s3 like storage. so amazon s3 api's will work with minio

when we tried filling in the parameters as recommended to store it in s3 like storage - we are getting an error 

while we do a config change to point it to s3, it is working 

please advise 

Attaching the logs along with this issue 

Thanks
Suresh Babu Y

**Comment by ysureshbabu** [comment]
[Minio.zip](https://github.com/ant-media/Ant-Media-Server/files/6506938/Minio.zip)
[S3.zip](https://github.com/ant-media/Ant-Media-Server/files/6506940/S3.zip)

IP Addresses masked

**Comment by ysureshbabu** [comment]
@SelimEmre, we were following the steps in our document to integrate with minio storage and we encountered an error. 

Error - 
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: bucketName cannot be null

Below is our test configuration:
</bean>
        <bean id="app.storageClient" class="io.antmedia.storage.AmazonS3StorageClient">
    <property name="accessKey" value="accesskey" />
    <property name="secretKey" value="secretkey" />
    <property name="region" value="ap-south-1" />
    <property name="storageName" value="testingio" />
    <property name="endpoint" value="loansenable.co.in:9000/minio/antmedia-storage/" />
</bean>

**Comment by ysureshbabu** [comment]
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: bucketName cannot be null

</bean>
        <bean id="app.storageClient" class="io.antmedia.storage.AmazonS3StorageClient">
    <property name="accessKey" value="accesskey" />
    <property name="secretKey" value="secretkey" />
    <property name="region" value="ap-south-1" />
    <property name="storageName" value="testingio" />
    <property name="endpoint" value="loansenable.co.in:9000/minio/antmedia-storage/" />
</bean>

**Comment by muratugureminoglu** [comment]
Hi @ysureshbabu 

Sorry for the late response. I was able to upload successfully in the latest version of Minio. I am attaching screenshots for reference.

![minio1](https://user-images.githubusercontent.com/6337605/143674037-562fc2a1-3ce1-4e30-8579-b13513d3fa62.png)
![minio2](https://user-images.githubusercontent.com/6337605/143674039-14ee27c6-565b-4750-9a0b-c8f2baf7b868.png)
![minios3](https://user-images.githubusercontent.com/6337605/143674040-fc013a63-6bed-4919-88b0-76a6aebf1e75.png)
