### ISSUE TITLE
Being able to add logo as an overlay on to the stream

### ISSUE THREAD

**Issue by YalimEristiren** [ant-media/Ant-Media-Server#3279]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by burhankaymaz** [comment]
Hello,

We have been informed about the plugins related to the published [blog](https://antmedia.io/plugins-will-make-ant-media-server-more-powerful/).
It will be possible to add logo/watermark as explained in synchronized case. 

Is the plugin structure only for developers? So is there any ready to use plugin plan with v2.4?

**Comment by mekya** [comment]
Hi @burhankaymaz ,

Yes it will be possible to add logo/watermark as explained in synchronized case.

>Is the plugin structure only for developers? So is there any ready to use plugin plan with v2.4?

The plugin structure is for developers. On the other hand, we'll prepare some plugin for the community such as adding logo/watermark etc.

**Comment by mekya** [comment]
In this blog post, there are some very useful filters. 

https://antmedia.io/discover-the-filter-plugin/

Check the following title in the blog post above. 
```
3. Movie Filter and Adding Logo:
```

I'm closing this issue for now. Please feel free to reopen if it does not help you.
