### ISSUE TITLE
Add stream to conference REST method does not work

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#3281]
### Short description
Adding or removing a pre-defined stream to a pre-defined conference room does not work, namely the methods:

https://antmedia.io/rest/#/BroadcastRestService/addStreamToTheRoom
https://antmedia.io/rest/#/BroadcastRestService/deleteStreamFromTheRoom

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.3.3 SNAPSHOT latest commits merged on the creation date
* Browser name and version: 

### Steps to reproduce
1. Create a room with : 
`curl -X POST "http://localhost:5080/LiveApp/rest/v2/broadcasts/conference-rooms" -H "Content-type:application/json" -d '{"roomId":"room1", "endDate":0, "startDate":0}'`
It is successful.
2. Try to add a stream using the given CALL in definition of the problem namely:
`curl -X PUT "http://localhost:5080/LiveApp/rest/v2/broadcasts/conference-rooms/{room1}/add?streamId=stream1"`
3. It does not return success. 

### Expected behavior
Pre-defined broadcasts should be a part of the conference room.

### Actual behavior
Add or delete pre-defined broadcasts to the conference room does not work

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by eneskuluk** [comment]
I investigated this issue and found the cause.
It's coded in the way that only broadcasting streams are allowed to being added to the room.
I'll check why this is implemented in this way and fix if there is no reason to add streams that is not being broadcasting currently.
