### ISSUE TITLE
Add checkpoint if rtmp-endpoint is already added to broadcast in REST API.

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3284]
Add checkpoint if rtmp-endpoint is already added to broadcast in REST API.

Current issue:
We are able to add multiple times the same RTMP Endpoint but this shouldn't be possible. It should give an error.

**Comment by f135ta** [comment]
I'd like to second this.. It'd be useful if we could block incoming connections and restrict them to 1 per RTMP client. Currently, if two RTMP clients use the same "stream key" it breaks both streams. It should just reject the second one
