### ISSUE TITLE
Unable to Install or upgrade Ant Media Server on Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by Fiqih57** [ant-media/Ant-Media-Server#3285]
Hello,
I am using Ubuntu 18.04 x64 and i followed this Documentation
When i try to install the Ant Media (ant-media-server-enterprise-2.3.2-20210422_0457.zip), got this error.
fiqih@PMI-DEV-FIF:~/Downloads/antmedia$ sudo ./install_ant-media-server.sh -i ant-media-server-enterprise-2.3.2-20210422_0457.zip 
Hit:1 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu bionic InRelease
Hit:2 http://id.archive.ubuntu.com/ubuntu bionic InRelease                                                                                           
Hit:3 http://ppa.launchpad.net/kdenlive/kdenlive-stable/ubuntu bionic InRelease                                                                      
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                    
Hit:5 http://id.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                   
Hit:6 http://deb.playonlinux.com cosmic InRelease                                                                                                    
Hit:7 http://packages.microsoft.com/repos/code stable InRelease                                                                                      
Hit:8 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic InRelease                                                                          
Hit:9 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                         
Hit:10 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease                                                                                     
Hit:11 https://linux.teamviewer.com/deb stable InRelease                                                                                             
Hit:12 https://deb.nodesource.com/node_10.x bionic InRelease                                                                                         
Hit:13 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                                   
Hit:14 https://packages.microsoft.com/repos/vscode stable InRelease      
Hit:15 https://packages.microsoft.com/repos/ms-teams stable InRelease                               
Hit:16 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu bionic InRelease                     
Hit:17 http://ppa.launchpad.net/webupd8team/atom/ubuntu bionic InRelease      
Hit:18 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease      
Reading package lists... Done                                                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libapr1 is already the newest version (1.6.3-2).
libapr1 set to manually installed.
jsvc is already the newest version (1.0.15-8).
libva-drm2 is already the newest version (2.1.0-3).
libva-drm2 set to manually installed.
libva-x11-2 is already the newest version (2.1.0-3).
libva-x11-2 set to manually installed.
unzip is already the newest version (6.0-21ubuntu1.1).
The following additional packages will be installed:
  libssl1.1 openjdk-11-jdk-headless
Suggested packages:
  libssl-doc libvdpau-doc openjdk-11-demo openjdk-11-source visualvm
The following packages will be REMOVED:
  libsasl2-modules:i386 libssl1.1:i386
The following NEW packages will be installed:
  libcrystalhd-dev libvdpau-dev openjdk-11-jdk openjdk-11-jdk-headless
The following packages will be DOWNGRADED:
  libssl-dev libssl1.1
0 upgraded, 4 newly installed, 2 downgraded, 2 to remove and 14 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
There is a problem in installing the ant media server. Please send the log of this console to support@antmedia.io

but when I install a lower version ( ant-media-server-enterprise-2.1.1 ), it works

when i want to update to new version (ant-media-server-enterprise-2.3.2-20210422_0457). I got an error like the information above

Thanks

**Comment by muratugureminoglu** [comment]
@Fiqih57 libssl-dev libssl1.1 packages should be downgraded. I guess you did a manual update. You can downgrade manually and try again. If you still encounter an error, you can send an e-mail to support@antmedia.io by mentioning me.

Regards.
