### ISSUE TITLE
Add more security restriction for request types(POST) to token mechanism

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3291]
### Short description
Anyone can access MP4 records using POST requests when the JWT token mechanism enabled.

### Steps to reproduce
1. Enable Play One-Time token, Hash-based or JWT token filters.
2. Request `http://localhost:5080/LiveApp/streams/stream1.mp4` with POST request type.

### Expected behavior
It shouldn't access directly if token mechanism enabled.

### Actual behavior
Anyone access MP4 records.

**Comment by kputyra** [comment]
@SelimEmre 
Does it apply only to `localhost` or also to remote locations?
