### ISSUE TITLE
WebHook does not fire for reused streamId

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#3312]
### Short description
The web hook does not fire liveStreamStarted and liveStreamEnded when a stream reappears with the same streaming id.
I don't know if this is a desired behaviour, because the documentation does not mention it. This might be related to #2036.

### Environment
* Operating system and version: Ubuntu 18
* Ant Media Server version: 2.3.2 Enterprice Edition

### Steps to reproduce
1. Create a live broadcast via REST API, set listenerHookURL to your web hook script and get {streamId} from the response.
2. Start streaming using {streamId}, then stop the stream.
3. Start streaming again using {streamId}, then stop the stream.

### Expected behavior
The web hook script receives liveStreamStarted and liveStreamEnded in both 2 & 3.

### Actual behavior
The notification are received only in 2, but not in 3.

**Comment by mekya** [comment]
Thank you for the issue. We've added to backlog to schedule

**Comment by eneskuluk** [comment]
Hi @kputyra , 
I have tested this in both latest snapshot versions and in 2.3.2 but couldn't find any issues regarding your report. 
I used https://webhook.site for testing purposes. I set the webhook URL in dashboard under the advanced settings section. See the screenshot below for what i did.
![image](https://user-images.githubusercontent.com/54481799/121227263-0a646a00-c894-11eb-9d0e-6398e8a0bc94.png)

So let me write in a organized matter:
* I set webhook URL in dashboard in advanced settings that is in the application settings.
* After pasting webhook url, I clicked to save.
* Then I created a broadcast with a stream id of `test` through REST.
* I started streaming with stream id test then stopped the stream. I saw the both liveStreamStarted and liveStreamEnded could be seen.
* I tried the last step again, started and stopped streaming and saw webhook receives liveStreamStarted and liveStreamEnded.
Could you tell whether my reproduce scenario attempt was successful or not? If I was not correct on what i did, could you elaborate your reproduce scenario again please?

**Comment by mekya** [comment]
Good comment @eneskuluk

We're waiting for your comments @kputyra

**Comment by kputyra** [comment]
@eneskuluk 
Thanks for your test. It does things a bit differently though.

I don't set the webhook URL in the dashboard, but I pass it in the REST call that creates the broadcast. The reason is that I add extra data in the query string to the web hook. I post to /broadcasts/create an object like this:
```
{ "name": "My stream",
  "listenerHookURL":"https://mydomain.com/path-to-hook/webhook.php?id=mystreamid&owner=streamOwnerId"}
```
The parameters `mystreamid` and `streamOwnerId` are different for each stream and used by the hook script.

I will test tomorrow as you did, with setting the webhook script in the dashboard, to see if the problem appears in this case or not.

**Comment by kputyra** [comment]
Well, that was silly of me. My webhook script does a clean up in a response to liveStreamEnded, which deletes the broadcast from AntMedia. Once I removed that line the problem disappeared.

**Comment by eneskuluk** [comment]
It's nice to hear that you found a solution! @kputyra
