### ISSUE TITLE
Project Env Setup

### ISSUE THREAD

**Issue by aqzwss** [ant-media/Ant-Media-Server#332]
Hi,

There is no class io.antmedia.muxer.MuxAdaptor found once I download the project.

And when I execute the maven cmd: mvn clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
it failed with "ould not resolve dependencies for project io.antmedia:ant-media-server:jar:1.4.1: Failure to find org.red5:red5-server-common:jar:1.4.1"

Could someone help me?

thx

**Comment by mekya** [comment]
Hi ,

You just need to clone https://github.com/ant-media/Ant-Media-Server-Common
and install it in advance by mvn.
`
mvn clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Dgpg.skip=true
`

After that dependency will be resolved.
