### ISSUE TITLE
Ant media server v2.3.3 installation failing in arm64 instance

### ISSUE THREAD

**Issue by Siva-Detect123** [ant-media/Ant-Media-Server#3328]
### Short description
__Brief description of what happened__

Installation script doesn't support arm64 architecture

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: 11
* Ant Media Server version: 2.3.3
* Browser name and version:

### Steps to reproduce
1. Download Ant Media server 2.3.3 community edition
2. Download default installation script from  https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh
3. Install using sudo ./install_ant-media-server.sh -i ant-media-server-2.3.3-community-2.3.3-20210606_1542.zip

### Expected behavior
Proper installation of AMS

### Actual behavior
Some packages like libcrystalhd-dev not found in arm64 repository, hence installation fails

### Logs
zip
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:2 http://ap-south-1c.clouds.ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ap-south-1c.clouds.ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://ap-south-1c.clouds.ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libcrystalhd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libcrystalhd-dev' has no installation candidate
There is a problem in installing the ant media server. Please send the log of this console to support@antmedia.io

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
We updated the install script a few hours ago. Could you please try again?
