### ISSUE TITLE
License key Invalid error - when node was being rebuilt

### ISSUE THREAD

**Issue by ysureshbabu** [ant-media/Ant-Media-Server#3333]
Hi
We had some issues with the underlying network, so we had to rebuild the node on the new network/VLAN.
Now the license key states it is invalid 

Please help with the fix of the issue. 

Regards
Suresh Babu Y

**Comment by yashtandon113** [comment]
Hi @ysureshbabu,
When you delete the old instance and create the new one, it usually resolve within 15 minutes when license server refreshes the usages of the licenses.
It should be working fine now.
