### ISSUE TITLE
Write blog post about 150K viewers 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3339]

**Comment by sahiljain2497** [comment]
why just 150k viewers 🧐
https://antmedia.io/publish-hls-stream-cloudfront-with-ant-media-server/

**Comment by mekya** [comment]
150K is with WebRTC in other words it's real-time(0.5 secs) streaming. We just create blog series for scaling the number of viewers. Next stage will be 300K viewers

In cloudfront, viewer scaling is on the CDN side and it has traditional latency such 8-12 secs.
