### ISSUE TITLE
Support DASH MP4 from RTMP?

### ISSUE THREAD

**Issue by aqzwss** [ant-media/Ant-Media-Server#334]
Hi,

Does Ant-Media-Server has a way to support converting a realtime RTMP stream to DASH MP4 for playback？

Thx in advance.
Sprintee

**Comment by mekya** [comment]
Hi @aqzwss ,

We have some plans for that. As I remember this feature is scheduled for 1.6.0 or 1.7.0 version. 

We have recently changed the way how we release new versions. We plan to release new versions more frequent than before.

Regards,
A. Oguz

**Comment by aqzwss** [comment]
Thank you @mekya ,

Another question, is there a way fetching realtime stream from remote and mock it as a VOD type to web users using Ant-Media-Server?

For a good UE, I hope user can watch the video immediately once he did a request action (in the backend, we start to fetch stream once received user's requests,  and this time we already fetched several GOPs), and then as fetching more continuous video data, we can guarantee user's video watching.

Best Regards,
Sprintee

**Comment by mekya** [comment]
Hi @aqzwss ,

There is a support for fetching remote streams(HLS, RTMP, RTSP) and they plays like a live stream in Ant Media Server. 

I think your request is not something like that. You mean fetching remote stream at the time of the request that comes to Ant Media Server from remote resource. Is it correct? 

Secondly, you mean fetching a live stream from remote or fetching vod stream from remote?

Regards,
A. Oguz

**Comment by aqzwss** [comment]
Nope, I hope to fetch remote record stream and mock it as a vod to users.

**Comment by davutcavdar** [comment]
Hi,
You can fetch external sources with Ant Media Server. Please have a look at the [blog post](https://antmedia.io/pull-live-streams/).

**Comment by SelimEmre** [comment]
Hi @aqzwss,
Thank you for your interest. If you encounter an error when applied according to the blog post, can you re-open this issue?
