### ISSUE TITLE
Tomcat Error 404

### ISSUE THREAD

**Issue by phires** [ant-media/Ant-Media-Server#3345]
### Short description
I did a fresh installation of the Community Edition according to the documentation. 
Everything went well, but I can't access the Web Panel.

### Environment

* Operating system and version: Ubuntu 20.04 LTS
* Java version: OpenJDK 11.0.11 2021-04-20
* Ant Media Server version: 2.3.3-20210606_1542 Community
* Browser name and version: Edge 91.0.864.48

### Steps to reproduce
1. Setup a fresh Ubuntu 20.04 LTS VM
2. Download current ant media server version and install it using the install script
3. Access http://[IP-ADDRESS]:5080 or do a curl http://localhost:5080/ on the VM

### Expected behavior
Access to the Web Panel is possible

### Actual behavior
Reply from server is:
`$ curl http://localhost:5080
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.58</h3></body></html>`

 

### Logs
https://pastebin.com/kqZCMhiG

**Comment by tomasguirao** [comment]
me too..

**Comment by mekya** [comment]
Thank you for the issue. We've scheduled that immediately. 

Let's provide a quick solution @SelimEmre

**Comment by MoonTTMM** [comment]
resources in webapps/root is missing. I have workaround to copy resources from 2.3.2 to the root folder to make it work temporarily.

**Comment by SelimEmre** [comment]
Hi @phires,

Thank you for reporting us!

I updated the Community Edition download file. Could you please use the new one?

**Comment by navanjr** [comment]
> resources in webapps/root is missing. I have workaround to copy resources from 2.3.2 to the root folder to make it work temporarily.

@MoonTTMM can you be more specific about the workaround?

**Comment by phires** [comment]
Hi @SelimEmre, 

the new download works, thank you a lot :)
