### ISSUE TITLE
Publish time out error and Logs issue after upgrading to v2.3.3.1

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3352]
**Short description**
Customer upgraded his server to v2.3.3.1. After upgraded to latest version logs are not generating and Publish timeout error issue is occurred when try to stream. 

**Environment**
Ant Media Server version: v2.3.3.1

**Steps to reproduce**
1. upgraded using update over older version documentation 
https://github.com/ant-media/Ant-Media-Server/wiki/Installation#update-over-older-version
2. Check logs ( It is showing **There is no log yet**)
3. Try to publish webrtc stream ( publish time out error)

**Expected behavior**
The server should work fine.

**Actual behavior**
It is not working as expected and having issues.

**Comment by muratugureminoglu** [comment]
Hi @yashtandon113,

There is no log because the new install script was not used. Please use the script below.

https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh

Regards.

**Comment by muratugureminoglu** [comment]
@yashtandon113 

There is no log because the new installation script was not used. Please use the script below.

https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh

Regards.

**Comment by freshdev2015** [comment]
Was this fixed?
This is opened on my side as well.
- Publish time our error for video publish
- Auto close data channel for audio publish

How can we find solution?

**Comment by muratugureminoglu** [comment]
Hi @freshdev2015 

Could you please share your reproduce scenario and logs files ?

Regards.
