### ISSUE TITLE
Flutter webrtc screen sharing not working in vp8 encoding

### ISSUE THREAD

**Issue by prashantspandey** [ant-media/Ant-Media-Server#3360]
Hi , I am using flutter sdk.
getUserMedia() works well in both vp8 and h.264 encodings.
buy when I use getDisplayMedia() , the client side shows black screen in vp8 encoding but works well in h.264 but the problem is there are many devices which don't support h.264 hence I have to use vp8. Please fix this. 

Also when I enable both h.264 and vp8 (with one adaptive bit rate), it only streams in vp8 and doesn't adjust encoding according to the device as stated here:
"In Adaptive Bitrate mode, Ant Media Server transcodes incoming stream to the VP8 and H.264 stream and can send the appropriate one to the players. I mean some of the devices cannot play H.264 streams, for this case Ant Media Server can choose correct stream to send to that player."
link: https://antmediaserver.medium.com/webrtc-vp8-codec-data-channel-and-4k-60fps-supports-unleashed-in-ant-media-server-2-0-6284eb6b646f

**Comment by mekya** [comment]
@eneskuluk, what's current status of this issue? Please let me know through here in your convenient time.

**Comment by eneskuluk** [comment]
I was in contact through tickets, followed up many times but since i didn't get any response after some time, I closed the ticket with noticing replying will reopen the ticket.

**Comment by mekya** [comment]
OK. Thank you. @eneskuluk 

It's good to update issues to follow up. I may forget or users would like to see the progress/result about the issue.
