### ISSUE TITLE
Create a script to install all monitoring pipeline (kafka, elasticsearch and grafana) in one shot

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3367]

**Comment by mekya** [comment]
I think the PR is this one
https://github.com/ant-media/Scripts/pull/108

Could you please update the doc? Just let the user run this script and life will be easier.

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Monitor-Ant-Media-Servers

**Comment by mekya** [comment]
Thank you for the doc. 

Please assume me as a dummy/lazy user. My comments are 
 

> What to do after I run the script and then everything is installed. Where to login and what's password? 
> 
> I don't want to read the manual installation to find the url and password. It's too much work for me. I just want to make everything ready and see that it's working in a couple of minutes.

**Comment by muratugureminoglu** [comment]
I had already specified the username, password, and URL at the end of the script.[1]. Also, I added it to the document[2].

[1] https://github.com/ant-media/Scripts/blob/147ced4eb45e24b83fd0e8fdbc8da58f7caa8b14/install-monitoring-tools.sh#L174-L175
[2] https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Monitor-Ant-Media-Servers#automatic-installation-script
