### ISSUE TITLE
Chrome plays stereo audio in mono & provide options for libopus parameters 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3368]
Story by the user
----------------------
I’ve tried the stereo audio WebRTC streaming which is ingested rtmp protocol.
I played and listened streaming on AMS sample player.html.
However, It seems mono audio.
> a=rtpmap:111 opus/48000/2
I checked SDP, it shows audio channel is 2.
It seems to be the issue when converting AAC to Opus.
Could you look up that command which is probably converting with libopus of ffmpeg?
By the way, the MP4 (AAC, H264) recorded with the recoding function of AMS was stereo as expected.
In addition, I am also interested in the libopus option.

Do you specify any of these option, or none? 
-application voip
-application audio (default)
-application lowdelay

env: 
(Server) Ubuntu 18.04 on AWS
(AMS version) Enterprise Edition 2.3.2 20210422_0456
(Client) macOS 11.2.3, Chrome 91.0.4472.106
(I’ve attached a stereo audio sample for clarity.)
https://www.dropbox.com/s/suip1lrs1r7pywg/sample1.mp3?dl=0

Best regards,

**Comment by fcqpl** [comment]
Same issue as https://github.com/AirenSoft/OvenMediaEngine/issues/203#issuecomment-861296943

**Comment by SelimEmre** [comment]
Hi @mekya,

I have tried(adaptive and non-adaptive) with RTMP ingest(with VoD https://www.youtube.com/watch?v=6TWJaFD6R2s) and play WebRTC. WebRTC player sound was Stereo was expected.

**Comment by mekya** [comment]
Hi @SelimEmre ,
You mean it's working as stereo without changing any SDP in the Chrome 91.0.4472.114?

**Comment by SelimEmre** [comment]
Yes, it's working without any SDP changes.
