### ISSUE TITLE
can´t stream over index.html, when there is no webcam connected to my Pc

### ISSUE THREAD

**Issue by Quiet20** [ant-media/Ant-Media-Server#3374]
### Short description
Can´t start a stream on index.html (or any other site for publishing) without a connected webcam.

### Environment

* Operating system and version: Windows10 Versioni 2004
* Ant Media Server version: Enterprise Edition 2.3.3.1 20210609_2033 
* Browser name and version: newest Version of Firefox, Chrome and Edge

### Expected behavior
go on .../index.html
select screen in options
start publishing

### Actual behavior
I tried to share my screen over .../index.html
getting a "InvalidStateError" message as soon I open the site
Screen wouldn´t be displayed, after selecting it in the options
couldn´t start publishing (button for starting the stream did nothing)

problem was solved after connecting a webcam to my Pc and reloading the site.

**Comment by yashtandon113** [comment]
Hi @Quiet20 
As I have checked by disabling my laptop's webcam, I was able to share my screen over index.html and stream was published. But I have provided the mic permission.

**Environment**
Operating system: Windows10
Ant Media Server version: Enterprise Edition 2.3.3.1
Browser name: Firefox & Chrome

It checks the webrtc permissions in total if the permissions are not given to use getUserMedia, you can't use any of the webrtc.
Please check below 
/*
	* Checks if we is permitted from browser
	*/
	checkWebRTCPermissions(){
		if (!("WebSocket" in window)) {
			console.log("WebSocket not supported.");
			this.callbackError("WebSocketNotSupported");
			return;
		}

		if (typeof navigator.mediaDevices == "undefined" && this.isPlayMode == false) {
			console.log("Cannot open camera and mic because of unsecure context. Please Install SSL(https)");
			this.callbackError("UnsecureContext");
			return;
		}
		if (typeof navigator.mediaDevices == "undefined" || navigator.mediaDevices == undefined || navigator.mediaDevices == null ) {
			this.callbackError("getUserMediaIsNotAllowed");
		}
	}
