### ISSUE TITLE
Re-init of webrtc adaptor is required in some cases when other users drops and re-joins 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3381]
### Short description
Full restart is required to watch some dropped-joined streams in the conference call 

### Steps to reproduce
1. Let the 3 users join to a conference room
2. Make the user 3 leave from the conference room 
3. Make the user 3 join to the conference room again

### Expected behavior
User 1 should see the user 3 without any interaction or initialization.

### Actual behavior
User 1 should init the WebRTC connection from scratch again to see the user #3. However it is not a good user experience

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/181
