### ISSUE TITLE
I can not start in docker container ubuntu/debian latest Error: Could not find or load main class org.red5.server.Bootstrap

### ISSUE THREAD

**Issue by maddog043** [ant-media/Ant-Media-Server#340]
I run start.sh
RUN /ant-media-server/start.sh
 ---> Running in bd5ac13602d3
Running on  Linux
Starting Ant Media Server
Error: Could not find or load main class org.red5.server.Bootstrap
ERROR: Service 'ant' failed to build: The command '/bin/sh -c /ant-media-server/start.sh' returned a non-zero code: 1

When I run start-debug.sh
/ant-media-server/start-debug.sh: line 15: /start.sh: No such file or directory

Ant Media Server Community 1.4.0 (August 2, 2018)

**Comment by maddog043** [comment]
My docker file

`
FROM ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:webupd8team/java && apt-get update -y
RUN echo oracle-java8-installer shared/accepted-oracle-licence-v1-1 boolean true | /usr/bin/debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
RUN apt-get install oracle-java8-installer -y --allow-unauthenticated
ADD ./ant-media-server /ant-media-server
RUN /ant-media-server/start-debug.sh
`

**Comment by SelimEmre** [comment]
Hi @maddog043,
Thank you for your interest. Do you still have problems? If the problem persists, can you re-open this issue?
