### ISSUE TITLE
Random antmedia thread crashes 

### ISSUE THREAD

**Issue by lerenarzp** [ant-media/Ant-Media-Server#3403]
### Short description
Antmedia processes crash randomly, probably related to compatibility issues between antmedia and current versions of libraries on the server (?)

### Environment
Available in the crash report here: https://pastebin.com/W2gAwzap
Antmedia version is 2.3.3.1

### Steps to reproduce
The issue is intermittent and quite rare. Found no patterns.

Could you please take a look at the dump above and advise if you see anything out of order and what may be done to avoid such crashes? Not sure if that is application-related or server-related.

**Comment by eneskuluk** [comment]
Hi @lerenarzp 
We took a look on the issue and it looks what you said. It seems you installed the ant media over one already installed which led some of the configuration files remained unchanged. `https-openssl-apr` should be `https-openssl-nio2`. This the reason of the crash.
I think best solution can be clean installation, this is not optimal but probably quickest one.

**Comment by lerenarzp** [comment]
Hi @eneskuluk 
Thank you for your help, will do as suggested. 
Closing this thread, thank you again.
