### ISSUE TITLE
There seems to be a bug in the "DELETE /v2/broadcasts/{id}/rtmp-endpoint" API endpoint

### ISSUE THREAD

**Issue by hamitdemir** [ant-media/Ant-Media-Server#3404]
### Short description
__Brief description of what happened__
For example, if the RTMP restreaming fails and the status of the RTMP endpoint is set to "failed", we can't programmatically remove that RTMP endpoint.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by choxnox** [comment]
Is there any update on this issue?

We raised this issue in the call with you guys and it's kind of important since it's part of our restreaming offering and yet it breaks our functionality.

**Comment by mekya** [comment]
Not yet. I've put it into this week's sprint. Sorry.

**Comment by SelimEmre** [comment]
I have checked this issue in the latest SNAPSHOT. We already solved this issue. It can be removable with https://antmedia.io/rest/#/BroadcastRestService/removeEndpointV2 REST API.

**Comment by medzin** [comment]
Is there a workaround for this issue? I ran into the same problem.

**Comment by mekya** [comment]
Hi @medzin ,
You're using the latest snapshot? As @SelimEmre says it seems to be fixed in the 2.4.0 SNAPSHOT. 

You can download the latest snapshot on your account(Subscriptions > Downloads) at https://antmedia.io

Let me know if we can help further
