### ISSUE TITLE
Looking for WebRTC App Java Code

### ISSUE THREAD

**Issue by singhalkarun** [ant-media/Ant-Media-Server#3406]
Hi All, 

There is a built in application called WebRTCApp in ant media community edition that comes by default. 

I am looking for Java Code that was used to build it so that I can add more features into it as per requirement.

Can you please help me with code?

Thanks in advance for the help.

**Comment by Mohit-3196** [comment]
Hi Karun,
Thank you for your interest, hope you are doing well.
You can download the community edition source code for AMS v2.3.3 from [https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.3.3](url)
Also you can navigate to directory \src\main\java\io\antmedia\webrtc to locate the codes.
I hope this helps.

**Comment by singhalkarun** [comment]
Hi @Mohit-3196 @cemklc,

Thanks for the help with code. Much Appreciated. I would like to discuss one more problem with you. Let me describe what i am trying to achieve with ant media and what are the steps i followed.

Requirement:

Build a group call application with merged stream option.

Steps I followed:

https://antmedia.io/merge-webrtc-conferences-as-a-single-video-stream/

I followed steps as described in this blog. 

I replaced <application-name> by WebRTCApp which is default application provided by ant media.

Below is a link to short clip of how i tried. When I tried to join room, join message is being sent but nothing happens after that.

https://youtu.be/OWBNk0jdRM8

It would be great if you can help me debug where the issue is. I needed java code to debug the same. 

Thanks in advance for the help.

**Comment by Mohit-3196** [comment]
Hello @singhalkarun ,
Thank you for listing down your issue. As far as I understand, conference is an application of WebRTC (ultra low latency) solution and WebRTC playback is supported on the Enterprise edition and that is why you are not able to create the conference.
I suggest you to try Ant Media enterprise edition. You can take a free 14 days trail of enterprise edition from https://antmedia.io/
Let me know how it goes with you.

Have a great day.

**Comment by singhalkarun** [comment]
Hi @Mohit-3196,
Thanks for the info.

Actually, my goal as of now is to learn and work on community edition of ant media.

Regarding webrtc playback, i am able to publish and play webrtc streams in ant media community edition by following below steps:-

1. For Publishing Stream (Supply stream name and start publishing.)

http://localhost:5080/WebRTCApp/

2. For Playing Stream (Supply stream id to play and start playing.)

http://localhost:5080/WebRTCApp/play.html?id=stream1

Recently, I also found one more blog for building conference solution with ant media by @burak-58 
https://antmedia.io/how-to-create-a-conference-solution-ant-media-server/

I built the war file for code at https://github.com/ant-media/ConferenceApp. I faced few errors when building. I have created the pull request that resolves th same.

https://github.com/ant-media/ConferenceApp/pull/5

After building, I deployed it with steps as in blog. 

After deploying, I found that the websocket was not able to initialize so join room button stayed disabled.

After bit of tinkering, changing the websocket url, I was also able to activate the join room button.

Now, when i click on join room button, data channel opens and also i am able to see streams in the ant media dashboard.

Also, if somebody joins room, I am able to see the stream joined message in console of each user. 

The issues to be solved now are :-

1. Play all streams on single page
2. Merge all streams to form a single stream

**Comment by Mohit-3196** [comment]
Hello @singhalkarun ,
That's good to know. We can check in together as well to see these issues.
Also, if I understand the play URL that you mentioned plays HLS streams and not WebRTC http://localhost:5080/WebRTCApp/play.html?id=stream1
You can see the play type in the dashboard. Do let me know about it and we can then see to it accordingly. Also, thanks for your contribution.

**Comment by singhalkarun** [comment]
Hi @Mohit-3196, you are right.

The stream which we are playing are hls ones and not webrtc ones. I mistakenly thought ant media community server to be acting as sfu and restreaming webrtc.

It would be great if we work on ant media community edition server to give atleast a basic sfu functionality and then we can integrate conference app application with it to build a mini conference call application..
