### ISSUE TITLE
Unable to publish WebRTC stream when microphone permission is not allowed or there is no audio device

### ISSUE THREAD

**Issue by ipliu** [ant-media/Ant-Media-Server#3407]
### Short description

I used _LiveApp/index.html_ to publish WebRTC stream.
When I set the microphone permission to deny or `mediaConstraints.audio = false;`, getting a "InvalidStateError" message as soon I open the page.

This error message cause by _LiveApp/js/webrtc_adaptor.js_ `setGainNodeStream(stream)` function.
This function does not check whether the stream has AudioTracks.
When execute this line `this.audioContext.createMediaStreamSource(stream);`, it will throw `DOMException: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track`.

### Environment

* Operating system and version: CentOS 8.2.2004
* Java version: 11.0.9
* Ant Media Server version: v2.3.3.1
* Browser name and version: Chrome 91

### Steps to reproduce
1. Open LiveApp/index.html and set the microphone permission to deny.

### Expected behavior
I can publish WebRTC stream when I set the microphone permission to deny or `mediaConstraints.audio = false;`.

### Actual behavior
Unable to publish WebRTC stream when I set the microphone permission to deny or `mediaConstraints.audio = false;`.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by Mohit-3196** [comment]
@ipliu ,
Hope  you are doing well.
These are the mandatory constraints and therefore are to be allowed.
Have you tried audio_publish.html!

**Comment by ipliu** [comment]
@Mohit-3196 ,
I want to publish WebRTC stream without audio device or microphone permission is not allowed.
But audio_publish.html only publish audio stream without video stream.

**Comment by Mohit-3196** [comment]
Hello @ipliu,
There is a toggle audio/video command that in the websocket. You can check this
https://github.com/ant-media/StreamApp/blob/ec7a6922d6ef84c313f74c58fa8a716a9821b98a/src/main/webapp/js/webrtc_adaptor.js#L634

Also, please refer https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference

**Comment by ipliu** [comment]
Hi @Mohit-3196 ,

I cannot call the toggle audio/video command because when I set `mediaConstraints = { video : true, audio : false; }` in _LiveApp/index.html_, getting a "InvalidStateError" message as soon I open the page.

And the websocket doesn't connect to the server, the _Start Publishing_ button is disabled.

**Comment by Mohit-3196** [comment]
Hi @ipliu ,
Please set mediaConstraints = { video : true, audio : true; }
and then call the toggle command.

**Comment by ipliu** [comment]
Hi @Mohit-3196 ,

I set `mediaConstraints = { video : true, audio : true; }` in _LiveApp/index.html_.
But if there is no audio device on my computer, _LiveApp/js/webrtc_adaptor.js_ will set `mediaConstraints = { video : true, audio : false; }`, and getting a "InvalidStateError" message as soon I open _LiveApp/index.html_.
How can I solve this issue?

**Comment by golgetahir** [comment]
Similar development for: https://github.com/ant-media/Ant-Media-Server/issues/3478

Here is the PR for specifically this one:
https://github.com/ant-media/StreamApp/pull/201

**Comment by SelimEmre** [comment]
Hi All,
Thank you @golgetahir.  @ipliu Please update your webrtc_adaptor.js.
Looking forward to hearing from you soon.
