### ISSUE TITLE
WebSocket will establish two connections to the server when publish WebRTC stream.

### ISSUE THREAD

**Issue by ipliu** [ant-media/Ant-Media-Server#3408]
### Short description

I used _LiveApp/index.html_ to publish WebRTC stream.
When I open this page, WebSocket will establish two connections to the server, one of which is always idle.

This issue cause by by _LiveApp/js/webrtc_adaptor.js_.
In `prepareStreamTracks(mediaConstraints,audioConstraint,stream,streamId)` function,
it will execute `this.gotStream(stream);` and `this.checkWebSocketConnection();`,
but `gotStream(stream)` function will execute `this.checkWebSocketConnection();` too.

### Environment

* Operating system and version: CentOS 8.2.2004
* Java version: 11.0.9
* Ant Media Server version: v2.3.3.1
* Browser name and version: Chrome 91

### Steps to reproduce
1. Open _LiveApp/index.html_ page

### Expected behavior
WebSocket establish one connections to the server.

### Actual behavior
WebSocket establish two connections to the server.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by eneskuluk** [comment]
Hi @ipliu,
This PR looks like resolves the issue you have: https://github.com/ant-media/StreamApp/pull/162
It's an easy fix, just change the webrtc_adaptor.js according to change in this pull request.
webrtc adaptor locates in: `<AMS_DIR>/webapps/<AppName>/js/webrtc_adaptor.js`

Enes.

**Comment by mekya** [comment]
This fix is refactored and merged into the master
