### ISSUE TITLE
Not able to save setting from ant media web panel

### ISSUE THREAD

**Issue by singhalkarun** [ant-media/Ant-Media-Server#3417]
Hi All,
I have deployed ant media community edition of cloud on aws ec2 insatnce and also configured domain name and ssl.

When i try to update any settings for WebRTCApp from ant media web panel, I see "Settings could not be saved."

Logs: 

2021-07-05 06:41:19,807 [https-openssl-nio2-0.0.0.0-5443-exec-8] WARN i.a.AntMediaApplicationAdapter - Settings cannot be saved for WebRTCApp

Can you please help?
Thanks in advance for helping me out.

**Comment by cemklc** [comment]
Hello,

Can you tell us if that happens for a specific settings or every other settings? I have tried to reproduce this issue but I managed to save the settings. Only issue might be security groups or something went wrong when configuring the domain name or ssl.

Are the security group configured as in the following figure?
https://i0.wp.com/antmedia.io/wp-content/uploads/2019/02/Screenshot-from-2019-02-20-21-58-44-1024x342.png

Give us an update please,

Regards.

**Comment by singhalkarun** [comment]
Hi @cemklc,
Thanks for the reply.

I am able to save the settings now. The isse was with permissions in linux.

When deploying ant media. if we use "sudo", then only root user is able to save settings which was causing the issue.
