### ISSUE TITLE
Create doc for MongoDB Replica set installation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3418]

**Comment by chris-makaio** [comment]
uhm, just found out that it doesn't exist - only for AWS, not for self-hosted... that's a bummer

**Comment by mekya** [comment]
Hi @chris-makaio ,

Thank you for your comment. Even if MongoDB has already this doc, we just would like to make it easier for the users.

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/MongoDB-Replica-Set
