### ISSUE TITLE
Multitracks streaming in cluster mode

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3423]

**Comment by peterzanetti** [comment]
Can you describe what this is? It sounds like simulcasting?

**Comment by mekya** [comment]
No it's not simulcasting. It's about support of multi audio/video track in a single webrtc session in cluster mode

**Comment by peterzanetti** [comment]
Can you tell me an example use case of multi track video then?

**Comment by mekya** [comment]
In a conference, each attendee will be a different video track and there will be a single webrtc connection to the server . This webrtc connection sends all attendees' videos in different video tracks in the same single webrtc connection.

**Comment by peterzanetti** [comment]
Oh! Ok so this is the single peer connection upgrade I’ve been waiting for. Great.
