### ISSUE TITLE
Turn off Webcam Light when camera is off 

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#3424]
duplicate #3420

**Comment by golgetahir** [comment]
Hi all,

To turn off the camera light, you can call closeStream() method of webrtc_adaptor.js . However, this will close everything and stop accessing camera, which means, you need to republish to the server when the camera turn on, that is how webrtc works. For not doing that, we use `track.enabled = false;` which does not release camera just stops the video track and can be resumed with the same connection. If you want to release camera totally, you need to call track.stop() as in closeStream method, checkout the implementation:

https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js#L376

And this is turnOffLocalCamera:

https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js#L1281

Cheers.
