### ISSUE TITLE
Unity SDK not working with DllNotFoundException. (following the tutorial)

### ISSUE THREAD

**Issue by gft-ai** [ant-media/Ant-Media-Server#3435]
### Short description
As the title suggests, Unity SDK is not working as it throws the following error:

`DllNotFoundException: SoraUnitySdk`

This happens upon start:
`DllNotFoundException: SoraUnitySdk
Sora.GetVideoCapturerDevices () (at Assets/SoraUnitySdk/Sora.cs:294)
SoraSample.Start () (at Assets/SoraSample.cs:95)`

and also upon pressing the Start Streaming button:
`DllNotFoundException: SoraUnitySdk
Sora..ctor () (at Assets/SoraUnitySdk/Sora.cs:92)
SoraSample.InitSora () (at Assets/SoraSample.cs:182)
SoraSample.OnClickStart () (at Assets/SoraSample.cs:347)
UnityEngine.Events.InvokableCall.Invoke () (at /home/bokken/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:180)
UnityEngine.Events.UnityEvent.Invoke () (at /home/bokken/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)`

**ALSO**
There is no "Camera Usage Description*" setting in the configuration to use the camera for streaming.

I can only presume that the unity sdk is no longer maintained. If this is the case you should really update the documentation saying this sdk is no longer supported. Otherwise, you should really update the documentation so it is always up to date and the tutorial is working, especially if you want the people to pay for the stuff.

### Environment

* Operating system and version: Ubuntu 20
* Java version: 
* Ant Media Server version: Latest
* Browser name and version:
* Unity version: 2021.1.7f1

### Steps to reproduce
1. Download the sdk
2. open up unity
3. try to follow the tutorial.

### Expected behavior
Tutorial to work

### Actual behavior
Tutorial not working

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by eneskuluk** [comment]
Hi @gft-ai, 
`Camera Usage Description` is for IOS. As you can see, it is being mentioned under the IOS guidance in the tutorial. It is to get camera and microphone permissions from the IOS operating system.
Could you provide more information about how do you trying to stream please? Steps are not clear enough. In which step you got stuck? Could you post the scene please and make sure the settings are visible which are located at the right side of the scene.
