### ISSUE TITLE
Cannot log support request from Web Interface

### ISSUE THREAD

**Issue by francoisdutoit** [ant-media/Ant-Media-Server#3464]
Since updating to the latest ANT I am unable to submit a support request from the Web Interface

### Environment
Azure ANT Instance

### Steps to reproduce
Open Web Interface
Click On Support
Fill Out Details
Click - Send

### Expected behavior
Ticket Gets submitted

### Actual behavior
Screen Hangs - Ticket does not get submitted

**Comment by aybb** [comment]
Same issue.

**Comment by yashtandon113** [comment]
Hi @francoisdutoit 
This is the known issue in current version v2.3.3.1 and it was in our issue tracking list also.
https://github.com/ant-media/Ant-Media-Server/issues/3379

It is fixed by development team and will be merged into upcoming version.
