### ISSUE TITLE
Disonnect open client connections to prevent "streamIdInUse" error

### ISSUE THREAD

**Issue by larsschwarz** [ant-media/Ant-Media-Server#3466]
Sometimes we see that users have multiple tabs/windows open when using the WebRTC client on their mobile.

They start a stream for testing purposes, don't click "disconnect" and then open a new tab/window some time later on and experience the "streamIdInUse" error, because there still is an open connection in another open tab/window in the background. 

It would be helpful to have a client-side method that disconnects all open client connections for a specific stream ID.

Original Google group discussion for reference: https://groups.google.com/g/ant-media-server/c/O93zFG3AmB0

**Comment by mekya** [comment]
Hi @larsschwarz ,

TBH, I think you want a method to stop the stream that is running another tab? I'm not sure if browsers allow doing some manipulation in another tab.

What you can do is that there should be some kind of javascript event that is called when the tab goes background, you can call webrtc adaptor's `stop` command in that event. 

Do you think this kind of solution works for you?

**Comment by mekya** [comment]
I'm closing this issue for the inactivity. Feel free to re-open if you think it should be resolved.
