### ISSUE TITLE
Implement partial interface on webrtc data channel that makes limitless binary data sending 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3469]

**Comment by burak-58** [comment]
When a binary data which size is larger than 16MB cause data channel problem.
WebRTC data channel is buffering the data until transfer channel becomes available. This buffer is 16MB. So if you are sending high message and network cannot meet the the writing speed to the buffer then buffer will be exceeded and  data WebRTC channel connection will be broken. We are working on a solution to control the buffer size and write if it has place. Unfortunately bufferedAmount is return a cumulative value.
