### ISSUE TITLE
Provide an option to update the name in webrtc publishing

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3477]

**Comment by SelimEmre** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/380
https://github.com/ant-media/StreamApp/pull/192

**Comment by mekya** [comment]
Quality gate is failed in the enterprise project. 

StreamApp project "streamName" field may be converted to "undefined" if it's not specified.
