### ISSUE TITLE
Start publishing without video(audio only) in the beginning of WebRTC stream and enable video after sometime

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3478]
Some of our clients want to publish WebRTC stream without video.

**Comment by mekya** [comment]
Audio only support is already available. I don't understand the question

**Comment by sagark1510** [comment]
@mekya  yes that is available the problem is once you start with audio only I mean by making `{audio: true, video: false}`. later in the call you can not stream the video no matter what.

**Comment by mekya** [comment]
Thank you @sagark1510, I got the point. 

Quick workaround is opening video and audio at first and then closing the video track. With this solution, you enable video at any time. 

Make sense?

**Comment by sagark1510** [comment]
@mekya True that and I'm doing that too. But that is bad user experience to ask for Video permission even though user just want to do a audio only session. I'm developing mobile app.

**Comment by mekya** [comment]
Yes, you're right. Thank you for the feedback. Sent to the backlog to schedule.

**Comment by golgetahir** [comment]
Hi all,

New development about the issue is here: https://github.com/ant-media/StreamApp/pull/202/files

I hope it solves your problems.

Cheers

**Comment by sagark1510** [comment]
@golgetahir Thank you for the update. Can you tell me what changes I need to do on this lib https://github.com/TecladistaProd/rn-antmedia/
