### ISSUE TITLE
VODs are not getting deleted in S3 bucket when Add Date-Time is enabled from dashboard.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3486]
**Short Description**
When deleting a VOD from the Ant Media Web Panel Dashboard having "Date-Time enabled" it is not getting deleted from the AWS S3 storage. The issue remains same, with or without HTTP forwarding.

**Environment**

* Operating system and version: Ubuntu 18.04.5 LTS
* Java version: 11
* Ant Media Server version 2.3.3.1 and snapshot v2.4
* Browser name and version: Chrome 92.0.4515.107

### Steps to reproduce
1. Install AMS v2.3.3.1
2. Enable Live stream recording and S3 Recording. HTTP Forwarding is optional
3. Enable Add Date-Time to Record File names
3. Publish the stream and stop it.
4. Delete the generated VOD stream from the Server Dashboard.

**Expected behavior**
The VOD with Date and Time in S3 bucket should also get deleted when deleted the VOD from dashboard.

**Actual behavior**
The VOD with Date-Time stored in AWS S3 bucket is not getting deleted. Whereas it works as expected when "Add Date-Time to Record File names" is not enabled.

**Comment by mekya** [comment]
Good bug report. Thank you @Mohit-3196

**Comment by donikatz** [comment]
FWIW, I have the same problem in Enterprise Edition v2.3.3.1. Raised it with support, waiting to hear back.
Log error is re. deleting from internal path, even though that's not where it is:
`File is not deleted because it does not exist /usr/local/antmedia/webapps/<app>/streams/<filename>`

**Comment by mekya** [comment]
Thank you for the comment. We likely schedule it in next week.

**Comment by Mohit-3196** [comment]
It's working fine in community as well as enterprise edition unless Add Date-Time to Record File Names is checked and is only specific to those particular VODs which have Date and Time to their names.

**Comment by mekya** [comment]
Thank you for the update @Mohit-3196 , could you please update the issue report and add details about Add Date-Time. This makes life easier for the developer

**Comment by Mohit-3196** [comment]
I have updated the issue report.

**Comment by cemklc** [comment]
https://github.com/ant-media/Ant-Media-Server/pull/3535
