### ISSUE TITLE
How to change text on video player?

### ISSUE THREAD

**Issue by haizrul** [ant-media/Ant-Media-Server#3498]
![Screenshot_1](https://user-images.githubusercontent.com/8771582/127966994-887e7b46-2434-45e3-a062-fc15ec874984.png)

I want to change the text on the video player to "Loading..." , may i know what file should i edit to change this text? Thank you.

**Comment by mekya** [comment]
Hi @haizrul ,

You can find/change the text on the play.html(`/usr/local/antmedia/webapps/{APP_FOLDER LiveApp or WebRTCAppEE}/play.html`)

Regards,
A. Oguz

**Comment by haizrul** [comment]
> Hi @haizrul ,
> 
> You can find/change the text on the play.html(`/usr/local/antmedia/webapps/{APP_FOLDER LiveApp or WebRTCAppEE}/play.html`)
> 
> Regards,
> A. Oguz

Thanks a lot @mekya !

**Comment by mekya** [comment]
My pleasure :)
