### ISSUE TITLE
How to make audio unmute on video player

### ISSUE THREAD

**Issue by haizrul** [ant-media/Ant-Media-Server#3499]
Currently, the audio on the video player is automatically mute when the video load. How do i change it to make it automatically unmute when the video load?

**Comment by yashtandon113** [comment]
Hi @haizrul 
This is a default behavior of the browser. If auto play is enabled, audio is muted.

You can make it unmute by changing in the play.html file
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L120

You can find the play.html file in /usr/local/antmedia/webapps/WebRTCAppEE/play.html

This is about browser policy. It may not start auto play in some cases if video has audio and you may need to manual interaction to play the video.
For further information, take a look at this blog post
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by haizrul** [comment]
Oh i see. Ok understood. Thanks for the answer @yashtandon113 .
