### ISSUE TITLE
audio only stream does not reflect on the dashboard in community edition 

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3503]
**Short description**
When publishing the audio only stream in community edition, the stream is not reflecting on the dashboard.

**Environment**
Ant Media Server version: 2.3.3.1 community edition

**Steps to reproduce**
1. open and publish stream with https://domain:port/application/audio_publish.html or with index.html by setting (video:false) in media constraints
2. check stream on AMS dashboard

**Expected behavior**
Stream should reflect on the dashboard.

**Actual behavior**
Stream is not reflecting on the dashboard.

**Comment by aalgrou** [comment]
Same with me

**Comment by mekya** [comment]
Thank you @aalgrou 

There are some new commits for fixing the issue. It's on CI for now. After that it's going to be merged.  Likely today.  

Check these out

- https://github.com/ant-media/StreamApp/pull/247
- https://github.com/ant-media/Ant-Media-Server/pull/3625

**Comment by mekya** [comment]
Both of the PR have been merged. So closing the issue. 
Please watch out the next snapshot for community edition
https://oss.sonatype.org/#nexus-search;gav~io.antmedia~ant-media-server~~~~kw,versionexpand

Feel free to open if it's not working for you.
