### ISSUE TITLE
Script/Feature to save only highest quality or a specific bitrate in the MP4 recording when ABR is enabled

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3505]
A user has requested the feature to only save the highest bitrate VoD file when MP4 recording is enabled and ABR is set.

**Comment by mekya** [comment]
We're not sure about this feature.  On the other hand, we can provide a workaround for this problem.

User can delete the other files in user-defined script that is called whenever mp4 recording is finished
https://github.com/ant-media/Ant-Media-Server/wiki/User-defined-Scripts

**Comment by Mohit-3196** [comment]
Yes. I did suggest the user for it though he wants us to provide a script which can do so.
The exact use case is that user is saving the recordings to S3 bucket as well. So the script should be deleting the VODs other than the highest bitrate from S3 as well.

**Comment by mekya** [comment]
Can you provide that script @Mohit-3196? It's a simple script and we can share that script in this issue as well for later usage.

**Comment by muratugureminoglu** [comment]
@mekya @Mohit-3196  Here is the bash script. 

https://raw.githubusercontent.com/muratugureminoglu/Ant-Media-Server/master/user_defined.sh

```
#!/bin/bash

# Please make sure you installed FFmpeg before running the script.
# apt-get install -y ffmpeg

# TARGET : The location of the transcoded file.
# BITRATE: Bitrate 

INPUT="$1"
TARGET="/usr/local/antmedia/custom"
BITRATE="4000k"

# If you want to upload to S3, fill in the below lines.
AWS_ACCESS_KEY=""
AWS_SECRET_KEY=""
AWS_DEFAULT_REGION=""
S3_BUCKET_NAME=""
S3_UPLOAD="NO"

mkdir -p $TARGET
chown -R antmedia:antmedia $TARGET

upload(){

	if [ -z `which aws` ]; then
	rm -r aws* > /dev/null 2>&1
	echo "Please wait. AWS Client is installing..."
	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null 2>&1
	unzip awscliv2.zip > /dev/null 2>&1 
	sudo ./aws/install &
	wait $!
	rm -r aws*
	fi

	# Set credentials 
	aws configure set aws_access_key_id $AWS_ACCESS_KEY
	aws configure set aws_secret_access_key $AWS_SECRET_KEY
	aws configure set default.region $AWS_DEFAULT_REGION
	aws s3 sync $TARGET s3://$S3_BUCKET_NAME/
}

FILE=`echo $INPUT |egrep "[0-9]+p"`
FILE_NAME=`echo $FILE |egrep "[0-9]+p"  | awk -F "/" '{print $(NF-0)}'`

echo $FILE | xargs -I {} ffmpeg -v quiet -i {} -c:v libx264 -b:v $BITRATE -bufsize 1835k $TARGET/$FILE_NAME

if [ "$S3_UPLOAD" == "YES" ]; then
	upload
fi
```

**Comment by mekya** [comment]
Let's share this script in somewhere on stackoverflow, reddit, etc. to save time of developers.

@Mohit-3196 can you ask a question on stackoverflow and answer it by yourself? Or ask @muratugureminoglu  to answer. You can make the question title easy to find for the developer perspective.

**Comment by Mohit-3196** [comment]
@mekya abi, It is done. https://stackoverflow.com/questions/69044739/how-can-we-customize-mp4-savings-when-abr-is-enabled
Thanks @muratugureminoglu abi

**Comment by mekya** [comment]
Thank you closing this issue
