### ISSUE TITLE
Ads on the video player

### ISSUE THREAD

**Issue by haizrul** [ant-media/Ant-Media-Server#3508]
Is it possible to add banner ads on the video player? I'm currently using ant media community edition.

**Comment by mekya** [comment]
Hi @haizrul ,

I think yes it's possible. Unfortunately it's not supported as a feature. 

Source code is open and you can make the changes.  
https://github.com/ant-media/StreamApp

**Comment by haizrul** [comment]
> Hi @haizrul ,
> 
> I think yes it's possible. Unfortunately it's not supported as a feature.
> 
> Source code is open and you can make the changes.
> https://github.com/ant-media/StreamApp

Ok noted @mekya . Thanks for the answer.
