### ISSUE TITLE
VoD multi-select for delete

### ISSUE THREAD

**Issue by donikatz** [ant-media/Ant-Media-Server#3515]
In the console, I would like to be able to select multiple VoD recordings at once to action for deletion. Currently I can only delete one at a time. If I have a large volume to delete, it is time consuming.

Ideally a checkbox next to each VOD item on screen to be able to multi select rows and be able to click DELETE once for all selected.

Thanks, Doni

**Comment by mekya** [comment]
Yes, thank you for the issue. Sure we're adding this to schedule.

**Comment by mekya** [comment]
@cemklc , could you please apply the same thing for `Live Streams` tab as well?
