### ISSUE TITLE
Add stereo support on WebRTC Publish

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3527]
Add stereo support on WebRTC Publish

### What I tried?
I have tried channelCount: 2 parameters. But I couldn't achieve it yet.

**Comment by zaleschoenborn** [comment]
Any updates on when this should be available as stereo is a basic feature and multi track surround sound is also important.

**Comment by mekya** [comment]
It's provided in the 2.7.0 release
 
I'm closing this issue because it's a duplication of https://github.com/ant-media/Ant-Media-Server/issues/4642
