### ISSUE TITLE
Stream was stopped but stream files (*.m3u8, *.ts) doesn't clean

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#354]
# Issue

### Short description
Stream was stopped but stream files (*.m3u8, *.ts) doesn't clean, it still keep at /usr/local/antmedia/webapps/WebRTCAppEE/streams

### Environment

Operating system and version: Ubuntu 16.04
Java version: 1.8.0_171
Red5 version: Unknown

### Expected behavior
I want when stream ended all stream files was removed.

### Actual behavior
Stream ended and stream files was kept.

### Steps to reproduce
1. Create stream by WebRTC or RTMP via OBS
2. Stop this stream
3. View files at /usr/local/antmedia/webapps/WebRTCAppEE/streams by command "ls"

**Comment by davutcavdar** [comment]
Please make sure that settings.deleteHLSFilesOnEnded is set to true in the file :

../webapps/WebRTCAppEE/WEB-INF/red5-web.properties

**Comment by ntnahn** [comment]
Yeah, it's working. Thank you.

**Comment by harush** [comment]
Having the same issue, settings.deleteHLSFilesOnEnded is set to true but still files are not deleted. 

### Environment
Ubuntu 18.04
Antmedia 1.6.2-SNAPSHOT-190117_0945
Cluster of 3 edges under LB & mongodb.

**Comment by mekya** [comment]
Your issue should be something about cluster case, it's been resolved in another issue. Just use the latest version ;)

**Comment by loversandcode** [comment]
Hello, got same issue on latest AntMedia Community Edition.
It seems like some of ffmpeg process doesn't finished if webrtc stream doesn't  finish clean. There are still m3u8 file and it's empty, so hls player cannot parse it.

The same thing happens if I delete stream manually from dashboard.

deleteHLSFilesOnEnded is set to true

Do you have any suggestions, how to fix this?

**Comment by narayan494pandey** [comment]
> Please make sure that settings.deleteHLSFilesOnEnded is set to true in the file :
> 
> ../webapps/WebRTCAppEE/WEB-INF/red5-web.properties

**Comment by narayan494pandey** [comment]
my folder look like red5pro/live/WEB_INF/red5-web.properties .

Your solution is not working for me and  WebRTCAppEE is not present in my red5pro directories

**Comment by mekya** [comment]
Hi @narayan494pandey ,

red5pro is actually something else, it is not compatible with that.
