### ISSUE TITLE
Mp4 recording upload in S3

### ISSUE THREAD

**Issue by adisahu1989** [ant-media/Ant-Media-Server#3549]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Is it possible to give option for select object class type while uploading mp4 recording in S3 bucket. Where if we get this option then we can minimize storage cost by defining object storage type in S3 directly from Ant Media Dashboard.

**Describe alternatives you've considered**

**Additional context**

**Comment by mekya** [comment]
Hi @adisahu1989 ,

Thank you for this feature request. I've not understand the solution. It's my bad. 

What is the object class type? How will it reduce the storage?

Could you please give some more information about your request?

**Comment by adisahu1989** [comment]
Hi,

There are different storage classes present in AWS s3 for an object which
is uploaded and every class having its own storage cost. Classes like
Standard, Standard_IA, Glacier, one Zone IA.

Thanks,
Ashima Sahu

**Comment by mekya** [comment]
I see. OK. 

I'm moving to the backlog.  Its priority does not seem very high at this point because it's first time I've  encountered this feature request.

**Comment by adisahu1989** [comment]
Hi,

Thank you for your reply. Can you make it atleast medium priority in your
backlog. For cost reduce purpose it will great benefit for customers like
us.


Thanks,
Ashima Sahu

**Comment by mekya** [comment]
Yes sure.

**Comment by golgetahir** [comment]
Hi @adisahu1989

The feature will be there for next release, you need to update the setting for example as;

settings.s3StorageClass=glacier

The values you can enter is the same with StorageClass.values() array in AWS java SDK. Other values than that will be ignored.

Cheers.

**Comment by mekya** [comment]
Closing this issue because related branch is merged to the master and snapshots are available for now.
