### ISSUE TITLE
Update S3 guides according to latest changes on v2.4

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3550]
Update S3 guides according to latest changes on v2.4

**Comment by mekya** [comment]
I'm sorry. What are the new changes in 2.4?

**Comment by SelimEmre** [comment]
I mean, we transferred S3 settings to red5-web.properties file. But AWS S3 guidance shows still `red5-web.xml` on AWS S3 doc: https://github.com/ant-media/Ant-Media-Server/wiki/Amazon-(AWS)-S3-Integration

**Comment by mekya** [comment]
Ok. It's updated. @muratugureminoglu has already written that doc.

**Comment by mekya** [comment]
It's updated and closing the issue.
