### ISSUE TITLE
Play.html page reports error logs on browser 

### ISSUE THREAD

**Issue by cemklc** [ant-media/Ant-Media-Server#3555]
### Short description
Play.html page seems to produce new error codes after the latest update. These error logs don't affect the player and there is no issue with playing the stream, however, the console might spam those errors and it may result in missing the important logs.

### Environment

* Ant Media Server version: v2.3.3 and upper
* Browser name and version: Chrome

### Steps to reproduce
1. Publish a stream 
2. Play the stream via play.html page
3. Open chrome developer tools and look at the console

### Expected behavior
There shouldn't be new error logs.

### Actual behavior
There are error logs as shown in the figure.  
![image](https://user-images.githubusercontent.com/30143025/130356305-62fa5c59-2166-4f63-b574-effcad27e8d8.png)

![HYL_0rWZ_KITcA9TG4oSl_Dme8CYFCj7Xw](https://user-images.githubusercontent.com/3456251/131105935-94453b86-9cf7-4239-873f-2d49cf4cd3e8.png)

![c-4uygOnonRJG-Z2qOii-EhmDpznBdl4Zw](https://user-images.githubusercontent.com/3456251/131106598-a54f18f6-307a-4f2f-8825-c619363b0511.png)

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by eneskuluk** [comment]
Failed to load source maps actually is not an error, it comes from chrome's internal engine checks for map files for external javascript imports. They do not affect any functionality. For aframe, I'm sent a PR that creates a-scene programmatically.
