### ISSUE TITLE
Upgrading to 2.4

### ISSUE THREAD

**Issue by alxlion** [ant-media/Ant-Media-Server#3572]
### Short description
After 2.4 upgrade, webserver doesn't listen on 5080 anymore.

### Environment

* Operating system and version: Ubuntu 18.04.5 LTS
* Java version: openjdk 11
* Ant Media Server version: 2.3.3.1 EE
* Browser name and version: 

### Steps to reproduce
1. Get the latest installer
2. Upgrade AMS EE 2.3.3 to 2.4
3. Check the opened ports (5080 is not running anymore)

### Expected behavior
Webserver should listen on 5080 after upgrade.

### Actual behavior
Service is running well but nothing on port 5080.

### Logs
https://zerobin.net/?0c133fd1561ae334#KhE5Lcz9YS0aUIyKZhrIASIXe2ZROTsKrL6SE+IWQ7w=

**Comment by mekya** [comment]
Thank you for letting us know. Let us investigate the case on our end.

**Comment by harshald28** [comment]
Hi,

Yes, after the upgrade 5080 is not listening to any request. Finally, it worked with **clean installation** but due to that, we need to add our server config settings again.

@alxlion thanks for this ticket.

**Comment by mekya** [comment]
Yes, we've scheduled this issue for this week.

**Comment by donikatz** [comment]
Is this still open? I need to upgrade to 2.4.0.2, but not a clean installation.

**Comment by mekya** [comment]
Hi @donikatz ,

Sorry my colleague has some kind of personal stuff so that he could not complete this issue. Another of my colleague will take a look at this issue in a couple of days.

**Comment by mekya** [comment]
Hi Guys,

Here is a quick workaround for this problem. After you make the installation

1. Open the jee-container.xml -> /usr/local/antmedia/conf/jee-container.xml
2. Replace the `Http11AprProtocol` with `Http11Nio2Protocol`.  There are two changes. If you don't find any `Http11Nio2Protocol`, no worries. There should be no problem in your installation.  
3. Save and exit the file. 
4. Restart the service `sudo service antmedia restart`

For permanent solution, I'm updating the install script to handle this case.

**Comment by mekya** [comment]
I'm closing this issue guys. We've merged the PR to the master in the installation script. 
https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh

Please feel free to re-open if it does not work for you
