### ISSUE TITLE
Add a short pause when it auto switch resolutions on streams

### ISSUE THREAD

**Issue by rjtoledo** [ant-media/Ant-Media-Server#3575]
#3236  It works when we manually switch to each resolution, but when the stream auto switches The stream becomes noisy and blurry. it doesn't have a short pause and loading icon just like the implementation when manually switching its resolutions.

**Comment by rjmtldo** [comment]
Hi @mekya  is there any update regards with this? we just want the same implementation of the animation when switching to different resolution they way your team implemented manual selection, i think still be in the server side?



this is the current animation when auto switch to other resolution. it could be nice if there will be a short pause when it switches automatically as this video is not good to see when we push to production.
https://user-images.githubusercontent.com/72129826/134000608-1b090f1b-e31f-4ae7-bd33-89b0660e77fd.mp4

**Comment by mekya** [comment]
Hi @rjmtldo ,

I'm sorry there is no update. It's not a priority issue because it's not requested by users. I think it takes at least a couple of months to schedule this feature.

**Comment by notmilkipe** [comment]
Hi, I agree with Rj, can we please have a setting that turn on/off the switching animation.
because when the stream auto switches the stream becomes noisy and blurry.

**Comment by notmilkipe** [comment]
Hi @mekya, I agree with @rjmtldo, can we please have a setting that turn on/off the switching animation.
because when the stream auto switches the stream becomes noisy and blurry.

**Comment by mekya** [comment]
Thank you for the follow up. I've increasing its priority in the backlog to schedule it soon.   

If you would like to see the stage of the issue, I can even invite you to zenhub.

Regards,
A. Oguz

**Comment by mekya** [comment]
Hi @USAMAWIZARD ,
Progressbar should be shown in the embedded player, I've implemented that function in this PR -> https://github.com/ant-media/StreamApp/pull/425

Let's add half donation amount for this missing part so that you make the world better place ;)

**Comment by mekya** [comment]
Hi @rjtoledo,
This feature will be available in the next release.

FYI
