### ISSUE TITLE
audio_player.html always lands on default page with streamId=stream1

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3577]
* Ant Media Server version: 2.4
* Browser name and version: Chrome v92.0.4515.159

### Steps to reproduce
1. Publish a conventional or audio only stream(audio_publish.html)
2. Play audio only(audio_player.html) by giving streamID as a query parameter in the URL.
Sample URL: https://Domain:5443/LiveApp/audio_player.html?name=streamID 

### Expected behavior
It should open audio_player.html page with the given streamID

### Actual behaviour
The custom audio_player.html page loads with the default streamID i.e., stream1

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by cemklc** [comment]
https://github.com/ant-media/StreamApp/pull/215
