### ISSUE TITLE
Incorrect TURN server instruction

### ISSUE THREAD

**Issue by algentok** [ant-media/Ant-Media-Server#3584]
### Short description
__Brief description of what happened__
TURN server configuration contains a mistake in JS code.
https://github.com/ant-media/Ant-Media-Server/wiki/Turn-Server-Installation

			'urls' : 'turn:<turn_server_address>:<port_number>'
                        'username': "username"
                        'credential': "password"
Code above should contain commas after "<port_number>'" and " 'username': "username"".
This can cause surprising issues to people not familiar with JS.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Yes, you're absolutely right. It's added for now. Could you please check it?

**Comment by mekya** [comment]
My pleasure :)

Take care
