### ISSUE TITLE
Create a blog post about 2.4.0 Release

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3605]

**Comment by FriedWaffle** [comment]
Will the blog's post about the 2.4.0 version release include what has changed from the previous version? My team had added a custom layout to the frontend for antmedia. We prefer to keep our custom JavaScript codes and update the only thing that is changed.

**Comment by mekya** [comment]
Hi @FriedWaffle ,

We'll plan to introduce the new features in 2.4.0.  For the full change log, you can take a look at the auto-generated changelog. 
https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.4.0.2

Btw, how does your custom layout look like? I mean if it's ok for you, we can introduce your layout, your name, company to the community?

Regards,
A. Oguz
