### ISSUE TITLE
No StreamId for a created Broadcast

### ISSUE THREAD

**Issue by Fyb3roptik** [ant-media/Ant-Media-Server#3612]
### Short description
Created a Broadcast without setting StreamId. StreamId never gets set and now I cannot remove it!

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
* Ant Media Server version: 2.4.0.2 20210905_1320
* Browser name and version: Chrome 92.0.4515.159

### Steps to reproduce
1. Create a LiveApp Broadcast
2. Do not set StreamId
3. It breaks

### Expected behavior
StreamId should be set if blank

### Actual behavior
StreamId is blank

**Comment by mekya** [comment]
hi @Fyb3roptik ,

I think you are mentioning the community edition. @Mohit-3196 , may I ask for your help? Could you confirm the issue?

**Comment by Fyb3roptik** [comment]
Yes this is the Community Edition. I also need to know how to login to the DB so I can remove this broadcast with no ID. I have db software to do so (Golang Dev here)

**Comment by mekya** [comment]
I think you're using the default DB(mapDB) ?

If mapDB, we need to manually find that record and remove it programmatically.  Alternatively, if you don't have too much records in DB, you can delete the {appNAME}.db file under /usr/local/antmedia/ directory and restart the server.

**Comment by Fyb3roptik** [comment]
Ah ok I will do that! Yes its a small server for testing a production setup. I also am running into another issue but will put a sep ticket for that

**Comment by Mohit-3196** [comment]
hi @Fyb3roptik 
I just tried this is community version and it seems to be working fine for me.
Please take a look at this https://drive.google.com/file/d/1tRWL58UO6ttrZqLeHp43dBCtXZv_LhKt/view?usp=sharing

**Comment by Fyb3roptik** [comment]
Weird it is working for me now too...so random heh. I guess we can close this one. Must have been a weird issue right after upgrading. It didnt keep my settings when I upgraded (I see it was already reported), so maybe it was due to that

**Comment by mekya** [comment]
I see, thank you :)

**Comment by mekya** [comment]
Closing the issue because it's fixed.
