### ISSUE TITLE
Web GUI not available after upgrade to 2.4.0.2

### ISSUE THREAD

**Issue by rszrowe** [ant-media/Ant-Media-Server#3613]
Having upgraded one of our servers to 2.4.0.2 Enterprise edition the Web GUI was not available on port 5080 showing a connection refused message in the web browser.  All port and firewall settings seemed fine for the system. Once reverted back to 2.3.3 the GUI became available.

**Comment by mekya** [comment]
Hi @rszrowe ,

Can you make a fresh install? It seems that when restoring settings there is an issue. It's already reported here and scheduled #3572

**Comment by mekya** [comment]
#3572 is closed so I'm also closing this issue.
