### ISSUE TITLE
Livestream cache problem

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#362]
# Issue
Player load fragments wrong
### Short description
Sometime the player load the old fragments and the content display not correct. I face the problem same to this link: https://www.wowza.com/docs/how-to-control-apple-hls-client-caching-ext-x-allow-cache
BTW: When I tracking the server files content and stream with long duration (>1h) i see the index of file *.ts will be full of 4 digits and it rollback to index 0000. And I am using CDN, don't know it affect to this issue

### Environment

[] Operating system and version: Ubuntu 16.04
[] Java version: 1.8.0_171
[] Red5 version: Unknown

### Expected behavior
The stream content must be current fragments

### Actual behavior
The stream content sometime get old fragments

### Steps to reproduce
1. Livestream via RMTP by OBS
2. Wait for >1h to full index of *.ts file Or stop current livestream and publish stream with same id to faster reproduce
3. Sometime player load old fragments

**Comment by burak-58** [comment]
Hi,
I tried your reproduce scenario with 1.5.2-Snapshot version but I didn't encounter problem. Even if I recognize that after 9999.ts server continues to increment as 10000, 10001...

Your faster reproduce scenario is another case to your problem.

Can you try again with 1.5.2-Snapshot
https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/ant-media-server/1.5.2-SNAPSHOT/ant-media-server-1.5.2-20181106.195758-39-community-1.5.2-SNAPSHOT-181106_1955.zip
