### ISSUE TITLE
Audio and Video are out of sync on iOS devices using conference.html on AMI 2.4

### ISSUE THREAD

**Issue by zaleschoenborn** [ant-media/Ant-Media-Server#3626]
### Short description
Using latest AMI 2.4 iOS received conference streams from a PC device have video and audio out of sync

### Environment

* Operating system and version: ioS 14.8
* Java version: 
* Ant Media Server version: 2.4.0.2, no ABR enabled, h.264 only
* Browser name and version: Safari

### Steps to reproduce
1. Start a conference.html session with a PC and iOS device both joining a room
2. iOS device stream will have the audio out of sync with the video 
3. PC will have audio/video in sync

### Expected behavior
should be no sync issues

### Actual behavior
out of sync everytime

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by zaleschoenborn** [comment]
Test issue caused this issues

**Comment by mekya** [comment]
Thank you for update. I appreciate that.
