### ISSUE TITLE
How can I change the default network error background image?

### ISSUE THREAD

**Issue by RobotWeaver** [ant-media/Ant-Media-Server#3629]
Please help me on how to replace the default network error background image. I would like to replace it with the custom image I have

Below is the default image that ships with the application. Its what I would like to replace with my own custom image

![Default Network Error Background image](https://user-images.githubusercontent.com/90986522/133907646-99ea1fbd-e4e5-40e5-a3f0-752a3ae9ca26.PNG)

**Comment by Mohit-3196** [comment]
Hello @RobotWeaver,
There are some options to achieve this,
You can customize  this by editing the play.html and player.html files
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L51
If you want you can also comment out the network warning message by commenting out the lines 
 https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L594
