### ISSUE TITLE
Add webhook when there are issues with the stream

### ISSUE THREAD

**Issue by choxnox** [ant-media/Ant-Media-Server#3630]
**Is your feature request related to a problem? Please describe.**
Streaming can fail for any reasons and right now if that happens then the only way to find about what is the problem is to dig into the error logs and try to make the sense out of it. There is no system which would allow us to detect issues when they happen.

**Describe the solution you'd like**
It would be great to extend the webhook system to receive information regarding the streaming issues as they happen and not after someone reports that something doesn't work. This would allow us to wire the webhooks into our notification system to receive issues immediately.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mekya** [comment]
Hi @choxnox ,

Thank you for your recommendation. I'm just thinking how to build a reasonable structure for that. 

Let me know when you dig into the error logs, what kind of root cause do you encounter that fails the streaming?

**Comment by ncsu1** [comment]
I receive "stream stopped" webhook notifications to a stream that wasn't previously running and can usually take that to mean the publisher received a publishTimeoutError -- meaning their network was blocking the connection or there was an issue with their microphone connecting to the stream. It would be great if the webhooks could differentiate between a stream stopping, and a stream "stopped" that was never actually running.

**Comment by choxnox** [comment]
Hi @mekya, I believe the first step towards this would be to first standardize error messages, preferably with error codes. For example:
```
E1001 - High resources usage
E1002 - Disk out of space
...
E1190 - RTMP endpoint failed
...
E1490 - Unknown error occurred
```

I'm afraid that without the above it won't be possible to structure error reporting regardless of the error message delivery method (logs, webhook etc.).

**Comment by mekya** [comment]
Thank you for recommendations. 

Standard error messages make sense @choxnox  

> I receive "stream stopped" webhook notifications to a stream that wasn't previously running and can usually take that to mean the publisher received a publishTimeoutError -- meaning their network was blocking the connection or there was an issue with their microphone connecting to the stream. It would be great if the webhooks could differentiate between a stream stopping, and a stream "stopped" that was never actually running.

I see. Thank you @ncsu1 ,Let me think what's the proper way for doing that. Because if we don't do that in a proper way, the project becomes very complex and we'll suffer when we add a new feature.
