### ISSUE TITLE
Switch on-off Mirror in iOS SDK

### ISSUE THREAD

**Issue by phungbuuquang** [ant-media/Ant-Media-Server#3645]
I following to the guide Ant media iOS SDK. I am facing a problem is my camera when live stream reversed. Please help me solving this problem. Thank you so much.

**Comment by mekya** [comment]
Hi @phungbuuquang ,

Thank you for the issue. 

Unfortunately, it's very hard to understand the problem. You can use the bug report template in creating issue to let us understand your problem and fix it.  This makes us save good amount of time.

**Comment by phungbuuquang** [comment]
Hi @mekya.
I using iOS SDK when livestream , I use front camera , when I right hands up then camera show at left. It don't like camera original when without live stream.

**Comment by shinyjohn** [comment]
@mekya  any solution for above issue

**Comment by smaldd14** [comment]
Bump... Any solution for this?

**Comment by smaldd14** [comment]
@Mohit-3196 looking forward to hearing the updates about this issue. Is there any timeline you can provide for us? If you are looking for help, I would be interested in speaking more.

**Comment by Mohit-3196** [comment]
Hi @smaldd14 ,
The task has been scheduled and we'll have some updates soon.
We'll check on the feasibility and If it is something which is easy to implement and doesn't require too much time and resources then it'll be implemented soon.

Thank you

**Comment by smaldd14** [comment]
> Hi @smaldd14 , The task has been scheduled and we'll have some updates soon. We'll check on the feasibility and If it is something which is easy to implement and doesn't require too much time and resources then it'll be implemented soon.
> 
> Thank you

Hi @Mohit-3196 , any update on this task? It has been 3 weeks.

**Comment by mekya** [comment]
Hi @smaldd14 

I understand your frustration. This task has been assigned to me for the 3 weeks. I wish I could finish it 3 weeks ago. Unfortunately,  I could not make it because having some critical tasks are blocking me to work on this issue.

I'll do my best working to start this issue asap.  

PS:  I'm even paying some fee for every task I don't finish in each week. It's a game in the team. So really I would like to finish it :)

**Comment by smaldd14** [comment]
@mekya I'd love to help you finish this task! I've found this article below that describes a potential solution; https://stackoverflow.com/questions/40259041/mirroring-flipping-camera-preview-layer

It seems like there have been a few people in the last few years that this solution has worked for.

Unfortunately, I am not familiar enough with WebRTCiOSSDK to know where this piece of code should go. Any ideas where it may fit in?

**Comment by phungbuuquang** [comment]
I found a solution. It is pretty simply:

fullVideoView.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)

Vào Th 6, 18 thg 3, 2022 vào lúc 04:36 Devin Smaldore <
***@***.***> đã viết:

**Comment by smaldd14** [comment]
@phungbuuquang Do you put that in viewDidLoad, ViewWillAppear, or is needs to be somewhere else?

**Comment by phungbuuquang** [comment]
You can it in viewDidLoad

Vào Th 6, 18 thg 3, 2022 vào lúc 08:44 Devin Smaldore <
***@***.***> đã viết:

**Comment by smaldd14** [comment]
@phungbuuquang ah wow that works perfectly. Thanks for this! I also change it back to its normal view with fullVideoView.transform = CGAffineTransform(scaleX: 1.0, y: 1.0) when we switch to the front facing camera

**Comment by phungbuuquang** [comment]
You're welcome! I hope this solution solves your mission.

Vào Th 6, 18 thg 3, 2022 vào lúc 09:14 Devin Smaldore <
***@***.***> đã viết:

**Comment by shinyjohn** [comment]
> I found a solution. It is pretty simply: fullVideoView.transform = CGAffineTransform(scaleX: -1.0, y: 1.0) Vào Th 6, 18 thg 3, 2022 vào lúc 04:36 Devin Smaldore < ***@***.***> đã viết:
> […](#)

its fine while streaming , but after stream completed play recorded video not fixed(playing mirror videos)

**Comment by mekya** [comment]
Hey Guys,

You're definitely doing perfect. Thank you @smaldd14 for your understanding and 
thank you so much @phungbuuquang . You're absolutely great @phungbuuquang. I really appreciate your support.

Please let me know if I can do something for you. 

Regards

**Comment by phungbuuquang** [comment]
Thank you so much, I hope this solution can help you improve your product.
Because I live in VietNam, I think it is difficult to receive anything from
you <3.

Vào Th 6, 18 thg 3, 2022 vào lúc 13:37 Ahmet Oğuz Mermerkaya <
***@***.***> đã viết:

**Comment by mekya** [comment]
Thank you @phungbuuquang ,

I see. Maybe we can send some gift cards(Amazon, Starbucks ) with our love :)

Just let me know if it's possible.

**Comment by phungbuuquang** [comment]
Thank you so much! Gift card starbuck is perhaps useful in VietNam. I used
to receive your Christmas gift. Let's search my email in your data to get
my information.

Vào Th 6, 18 thg 3, 2022 vào lúc 14:16 Ahmet Oğuz Mermerkaya <
***@***.***> đã viết:

**Comment by mekya** [comment]
Sure. Let me ask help from my colleague to do that.

**Comment by phungbuuquang** [comment]
Thank you so much.

Vào Th 6, 18 thg 3, 2022 vào lúc 14:59 Ahmet Oğuz Mermerkaya <
***@***.***> đã viết:

**Comment by hamitdemir** [comment]
Hi @phungbuuquang, it is Hamit from Ant Media. Thanks for your contribution. Let's find a good way to send you a gift from Ant Media. :) I just sent you an e-mail.
