### ISSUE TITLE
Feature Request - Logo or Image displayed instead of text message "stream will start when playing"

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#3651]
To:"Ant Media" <contact@antmedia.io>
Hi,

I'm not sure if this feature exists but I think it'd be a great addition to be able to add a poster image in the player so when embedded we can have a logo or show image instead of the stream will start when playing text slate. Just a thought..

Thanks,

**Comment by mekya** [comment]
Yes, this request have been received a couple of times. Let's schedule it.

**Comment by golgetahir** [comment]
Hi people,

With the above PR you can add logo to your pages, just change the logo.png under /<ams_installation_folder>/webapps/<your_app_name>/images (default is: /usr/local/antmedia/webapps/WebRTCAppEE/images )

If you want to delete Stream will play automatically you can delete it from: https://github.com/ant-media/StreamApp/pull/217/files#diff-df443c20afd341b366bd2b2691ffdc189bce111feb301a1e3ced0eccacaec3eaL28

![Screenshot from 2021-10-15 11-52-04](https://user-images.githubusercontent.com/32591015/137460793-43f08991-f8ba-49c7-84ce-88687ede7eb2.png)

**Comment by USAMAWIZARD** [comment]
<ol>
  <li>Open your terminal and navigate to the directory where Ant Media Server is installed:<br>
  <code>cd /usr/local/antmedia/{APP_NAME}</code></li>
  
  <li>Use your favorite text editor to open the <code>play.html</code> file:<br>
  <code>sudo nano play.html</code></li>
  
  <li>In the <code>play.html</code> file, search for the "logo" section in the text. It should look like this:<br>
  <pre><code>&lt;div&gt;
    &lt;img id="logo" src="images/logo.png" /&gt;
  &lt;/div&gt;</code></pre></li>
  
  <li>Remove the commented-out parts (<code>&lt;!--</code> and <code>--&gt;</code>) <br>

  <li>This will display a logo on the player side </li>
</ol>
![image](https://github.com/ant-media/Ant-Media-Server/assets/47350008/4a7b942c-03d3-43c4-b181-63d03daa47a2)
<p>To change the default logo image:</p>

<ol start="6">
  <li>Navigate to the directory where the logo image file is located:<br>
  <code>cd /usr/local/antmedia/{APP_NAME}/images/</code></li>
  
  <li>In this directory, you will find a file called <code>logo.png</code>. Replace this file with another image file of the same name.</li>
</ol>
