### ISSUE TITLE
Cannot play hls stream

### ISSUE THREAD

**Issue by quan612** [ant-media/Ant-Media-Server#3655]
Short description

HLS stream cannot be play at
Community edition:
http://10.70.127.91:5080/WebRTCApp/play.html?id=Taft37th&playOrder=hls
http://10.70.127.91:5080/LiveApp/play.html?id=Taft37th&playOrder=hls

enterprise:
http://10.70.127.91:5080/WebRTCAppEE/play.html?id=Taft37th&playOrder=hls

Environment
Operating system and version: Ubuntu 20.04

Expected behavior
Stream can be played with HLS

Actual behavior
Stream cannot be played

Steps to reproduce
Created a new stream using stream source
Open the links above.

Error on Chrome / Firefox console

HEAD http://10.70.127.91:5080/LiveApp/streams/Taft37th_adaptive.m3u8?token=undefined&subscriberId=undefined&subscriberCode=undefined net::ERR_ABORTED 404

-- some related info
I wanted to try the community version but cannot play the HLS, also because community version does not let us to stream using WebRTC, 

So I installed the Enterprise Edition later to try: 
I could play the webRTC normally with this link:
http://10.70.127.91:5080/WebRTCApp/play.html?id=Taft37th

But the same issue happens on HLS streaming
http://10.70.127.91:5080/WebRTCAppEE/play.html?id=Taft37th&playOrder=hls

Ant Media Server Enterprise Edition 2.4.0 20210824_1123
Ant Media Server Community 2.4.0.2 (Sep 5, 2021)

**Comment by Mohit-3196** [comment]
Hi @quan612,
Can you share your Ant Media server dashboard credentials so that I can check and look into it.
Please write us on support@antmedia.io mentioning Mohit in the mail and we can continue it there.
Thanks

**Comment by quan612** [comment]
Hi,

I am not sure what is dashboard credentials, I am just using the default setting of installation and does not change anything
![image](https://user-images.githubusercontent.com/14017471/136037970-ea1acab3-ef1a-46af-a25d-ce99fc2f2a8f.png)

![image](https://user-images.githubusercontent.com/14017471/136038127-5e469759-d135-418a-a93e-d7da0b9041b9.png)

**Comment by Mohit-3196** [comment]
Hi @quan612 ,
I can see your ticket. Lets continue there and we can post the conclusion here.
