### ISSUE TITLE
Send the correct mime-type for Javascript module (.mjs) 

### ISSUE THREAD

**Issue by Davilink** [ant-media/Ant-Media-Server#3672]
**Is your feature request related to a problem? Please describe.**
I can't use javascript module in the stream app, because the extension .mjs is not recognized by the server by default and give the incorrect mime-type which prevents the browser from loading the module.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#aside_%E2%80%94_.mjs_versus_.js

**Describe the solution you'd like**
Support the .mjs extension

**Describe alternatives you've considered**
Add this in the web.xml will make it works, but required manual editing of the file
![image](https://user-images.githubusercontent.com/1498932/137400302-cb2f4ac9-1ece-4506-b70f-a659efe157ed.png)

**Comment by Mohit-3196** [comment]
Hi @Davilink ,
I tried by adding the extension and I was able to publish and play with the sample pages.
I tried it with version 2.4.0.2 and 2.4.1 snapshot version.
Please see the screenshots and let me know if I have missed anything.
![changes](https://user-images.githubusercontent.com/86982446/139636207-f723c70c-d1fc-4f37-b29e-c6d5e11c1dfd.png)

WebRTC Publish
![publish](https://user-images.githubusercontent.com/86982446/139636255-946de151-b00c-4114-b838-e1d769d6d279.png)

WebRTC Play
![play](https://user-images.githubusercontent.com/86982446/139636297-39fbcec7-f63e-4314-9dd3-10b37d36efc0.png)

Thanks

**Comment by Davilink** [comment]
Hi @Mohit-3196 , the alternative works, i already knew that, the purpose of this ticket (request feature) is that the mime type should be natively supported, meaning the we shouldn't be required to manually add it in the web.inf file.

**Comment by Mohit-3196** [comment]
Hi @Davilink,
Thank you for that.
@mekya abi, I guess we can do it with a PR. Please let us know if we can move forward.
Thanks.

**Comment by mekya** [comment]
Here we go -> https://github.com/ant-media/StreamApp/pull/223

**Comment by Davilink** [comment]
LGTM
