### ISSUE TITLE
WebRTC does not play on certain devices

### ISSUE THREAD

**Issue by emmanperion** [ant-media/Ant-Media-Server#3673]
### Short description
WebRTC is not playing on our clients on certain devices.

A device I had in me that is also not working is:
Samsung Galaxy A32.
Browser: Chrome 94.0.4606.85
OS: Android 11

Other browsers work:
- Whale

### Environment

* Operating system and version: Default from AWS t2.large
* Java version: Default from AWS t2.large
* Ant Media Server version: Enterprise Edition 2.4.0.2 20210905_1241.
* Browser name and version: Chrome 94.0.4606.85

### Steps to reproduce
1. Create new ant media instance
2. Create stream using stream source [we are using stream from an rtsp]
3. Login on a device (In this case, the Samsung Galaxy A32)
4. Play the stream (default: webrtc)
5. Video does not play

### Expected behavior
The video should play using webrtc.

### Actual behavior
The video does not play.

### Logs
[vp8] https://pastebin.com/FUNpXpPz
[h264] https://pastebin.com/5WCSG245

**Comment by yashtandon113** [comment]
Hi @emmanperion 
As I have checked using my Samsung S20 with chrome 94.0.4606.85 & latest 95.0.4638.50  it works fine for me and I could not reproduce the issue. I have also tried to check on your server that you have provided to my colleague but it is not responding. Also can you please share the RTSP Url that you are trying and are you able to publish the WebRTC stream through your Samsung A32? Please let me know.

**Comment by emmanperion** [comment]
Hello, 

Yes, most of devices do not have an issue. but many of our clients report they cannot play the video.
Devices vary, depending on the client. some use laptops, some mobile.

Fortunately, we have a device onhand that cannot play the video. It's where we test the latest version of ant media.
but still cannot play.

Unfortunately, I'm not authorized to share the RTSP url, but you may get it on the admin panel.
but using it will use additional bandwidth on our server, so please use with caution.

**Comment by thorfi** [comment]
I can report this is currently not working on macOS in Firefox 96.0.2 (64-bit) - see GitHub Issue #3160
