### ISSUE TITLE
WebRTC stream playback doesn't start on big sur chrome 95

### ISSUE THREAD

**Issue by Rostyk** [ant-media/Ant-Media-Server#3695]
### Short description
WebRTC stream playback issues

### Environment

* Operating system and version: Big Sur 11.6
* Ant Media Server version: Enterprise Edition 2.3.3.1 20210609_2033
* Browser name and version: Google Chrome 95

### Steps to reproduce
1. Create the stream at WebRTCAppEE section
2. Open a link in chrome
3. Playback doesn't start. It always shows "Stream will play automatically when it is live". The same url opens fine on this mac using VLC player.

### Expected behavior
The webrtc stream playback starts

 

### Logs
I noticed the suspicious log at the end:

```
.....
Sending ice candidate for stream id xxxxxxxxxxx
{"candidate": "candidate:1 1 UDP 1685987327 80.187.96.xx 12360 typ srflx raddr 0.0.0.0 rport 0", "sdpMid": "audio", "sdpMLineIndex": 0, "usernameFragment": "9c56b28b"}
sent message: {"command": "takeCandidate", "streamId": "2273xxxxxxxxxxxxxx", "label": 0, "id": "audio", "candidate": "candidate:1 1 UDP 1685987327 80.187.96.xx 12360 typ srflx raddr 0.0.0.0 rport"
No event.candidate in the iceCandidate event

Sending ice candidate for stream id xxxxxxxxxxx
sent message:{"command": "takeCandidate", "streamId": "xxxxxxxxx, "label": 0, "id": "audio", "candidate": ""}
No event.candidate in the iceCandidate event
```

Local and remote SDPs look okay.

The problem is that for some Big Sur users with the same version of chrome the playback starts. Any ideas appreciated

**Comment by Mohit-3196** [comment]
Hi @Rostyk,
I think it might be about some connection issue with regards to TURN server.
Please use a TURN server for play.html and player.html and it should work. You can configure a TURN server as https://github.com/ant-media/Ant-Media-Server/wiki/Turn-Server-Installation
And then you can add it to the play.html and player.html pages as https://github.com/ant-media/Ant-Media-Server/wiki/Turn-Server-Installation#how-to-add-turn-server-to-ant-media-sample-pages

Please try it and let us know if it works. In case it doesn't we can check the issue together as well.

Thanks

**Comment by Mohit-3196** [comment]
Hi @Rostyk,
Were you able to check with TURN server. 
Please let us know if there's any issue.

Thanks

**Comment by Rostyk** [comment]
Hi @Mohit-3196 
Thanks for a quick reply. Specifically our issue was resolved by adding
`settings.replaceCandidateAddrWithServerAddr=true` as described in [this issue](https://github.com/ant-media/Ant-Media-Server/issues/1249)

Instruction about TURN server setup is a useful resource anyway. Thanks for providing. I think we can close this issue

**Comment by Mohit-3196** [comment]
Hi @Rostyk , Thank you for writing.
cheers.
