### ISSUE TITLE
Preview images are uploading in the s3 bucket root folder and not in previews subfolder compared to v2.3.3.1

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3701]
### Short description
When previews are uploading to s3 bucket then the previews sub folder is not creating in s3 bucket and preview files are uploading in s3 bucket root folder directly but it should upload in preview sub folder like in previous v2.3.3.1.

### Environment
* Ant Media Server version: v2.4.0.2

### Steps to reproduce
1. Enable s3 recording and generate previews option.
2. Record the stream and then check the preview file in s3 bucket

### Expected behavior
Previews sub folder should be created in s3 bucket and file should be uploaded there.

### Actual behavior
Preview file is uploaded in root folder of bucket like **previews:stream_id_here.png**
![ant_preview](https://user-images.githubusercontent.com/82374739/139489570-04ddc9a2-ff85-4808-97d6-11dbd7531818.png)

**Comment by mekya** [comment]
Thank you. Fix has been sent to the repo. It's running in CI and it will be available on the website likely later today. 
https://antmedia.io/latest-snapshot

**Comment by mekya** [comment]
Closing the issue because it's fixed.
