### ISSUE TITLE
Upgrade the WebRTC iOS SDK to the latest build. 

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3707]
Recommend Commit Id: 2bcd4837dd5eeed98523344d437eb0b7e4f441ba

<img width="1035" alt="Screen shot 1" src="https://user-images.githubusercontent.com/86982446/139667786-063257fa-cdc4-4c42-a5eb-057d66528030.png">

Commit Id: d30ece1804dc91e84850cf07100c27a8e7b00d81

<img width="1037" alt="Screen shot 2" src="https://user-images.githubusercontent.com/86982446/139667893-9bde29bf-e2bb-4369-a285-41d1acae364c.png">

**Comment by mekya** [comment]
It's updated to M96
