### ISSUE TITLE
Fix wavelength issues 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3710]
- [x] Load balancer - Distribution algorithm
- [ ] Target Scaling CPU 
- [ ] Warm up time
- [x] SSL installation through IAM Role
- [x] Add custom STUN server to CloudFormation
- [x] Create two STUN instance in different wavelength zones

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/Scripts/pull/127
