### ISSUE TITLE
Console Error with Bootstrap Libraries

### ISSUE THREAD

**Issue by DanielGunther99** [ant-media/Ant-Media-Server#3729]
# Console Error with Bootstrap Libraries

### Short description

__When the page loads, a failure to load the content for bootstrap occurs. It appears that the map file for bootstrap is missing.__
![image](https://user-images.githubusercontent.com/40878804/141006459-c9cf21c4-d1e2-46f9-bbc0-f6a8e014b2bc.png)

### Environment

* Operating system and version: Windows 10 v10.0.19402
* Java version: 1.8.0_202
* Ant Media Server version: 2.4.1
* Browser name and version: Chrome v95.0.4638.69

### Steps to reproduce
1. Attempt to open the conference.html file.
2. View the console in chrome.
3. See attached image for example error.

### Expected behavior
__Expected to load the bootstrap.min.js.map.__

### Actual behavior
__Is unable to load the bootstrap map file as it is missing from the external folder.__

 
### Questions
I found a temporary fix to the error by removing the comment that looks for the map file. Is there a reason that the line still exists if the map file isn't present?

**Comment by golgetahir** [comment]
Hi,

Map files are just for debugging purposes for the library owners and they don't matter, the exception only thrown when you open the console. So deleting them has no effect on library or SDK, for more information you can check this out: https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

Thanks
