### ISSUE TITLE
iOS SDK build failed Monterey Xcode 13.x

### ISSUE THREAD

**Issue by lime-nk** [ant-media/Ant-Media-Server#3752]
error >> Module compiled with Swift 5.4 cannot be imported by the Swift 5.5.1 compiler : 

Update is required by building the iOS SDK in swift 5.5.x or later.

**Comment by mekya** [comment]
Hi @lime-nk , there is an update for iOS SDK for Monterey. We've also updated the WebRTC Stack.  It's in beta. You can test download the from here
https://drive.google.com/file/d/1cx-zA516LAzKYYXSpnO2X_tR_WNkMhH0/view?usp=sharing

After a while this beta is going to be deleted and newer version is distributed.

**Comment by mekya** [comment]
It's closing because duplicate #3707
