### ISSUE TITLE
Playlist of m3u8 fails when it is broadcasted to another Ant Media application.

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#3765]
### Short description
Playlist broadcast with m3u8 can't write header in muxers. The problem is most possibly related with the audio codec tag, because from this part writeHeader fails in Ant Media side. Here is the exited part of ffmpeg; https://ffmpeg.org/doxygen/3.2/mux_8c_source.html#l00385

The second possible invalid data is from pts, I don't think it does exit from there.

### Environment

* Operating system and version: Ubuntu 20.04.03
* Java version: 11
* Ant Media Server version: 2.4.1
* Browser name and version: Chrome 95

### Steps to reproduce
1. Create an m3u8 with ts files ( possibly from not deleting hls files at the end of the stream which I did )
2. Create a playlist and add the related m3u8 as a link
3. Add an endpoint to an instance of Ant Media ( possibly the same server's different application rtmp://localhost:5080/WebRTCAppEE )
4. Start playlist and check logs.

### Expected behavior
Run

### Actual behavior
writeHeader fails with invalid data error

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Duplicate #3790
