### ISSUE TITLE
Customization of the webhooks

### ISSUE THREAD

**Issue by streamninja-io** [ant-media/Ant-Media-Server#3766]
**Is your feature request related to a problem? Please describe.**
We are using the ant media as main streaming platform, but we want to have Ant media stopped and once we have an event run all the system.

**Describe the solution you'd like**
We want to know when the system is up and running, one possibility that we have is request the servers (long polling) in order to know when is started, but we are wondering if is possible to customize the webhooks in order to create one that send a request to some service when the system is up and running.

**Describe alternatives you've considered**

**Additional context**

**Comment by muratugureminoglu** [comment]
Hi @streamninja-io 

You are able to do this in many ways. I’m going to give you 2 examples of them. Hope it helps.

**1-** If you want to use Webhook, the antmedia service will send a request to your web_hook_url everytime it’s started by following the instructions below. 

when antmedia service starts, web hook will run automatically.

`vim /etc/systemd/system/antmedia.service`
```
ExecStartPost=/bin/sh -c 'curl -s your_webhook_url'
```
```
systemctl daemon-reload
systemctl restart antmedia
```

**2-** If you want to use monitoring tool, you can instantly find out if the server is running and whether the Antmedia server is running by using software such as Icinga, Nagios, Zabbix and you can receive notifications accordingly.

For instance, Ant media server uses 5080 port and if the 5080 port is not accessed, it means Ant media server is not working. If you cannot access your server with ssh, ping etc. that means your server is down and it will send you a notification when it starts to be accessible.
