### ISSUE TITLE
mute not working with sharescrean  on conference.html and camera not working on switchback 

### ISSUE THREAD

**Issue by mhalahmadi** [ant-media/Ant-Media-Server#3796]
### Short description
when I switch to screen share on conference.html and muted my voice sill the other on the conference can hear my voice  
and then switch back to the camera not working as the black screen appears and with this error message " There is no device found that fits your video and audio constraints. You may change video and audio constraints.  "

### Environment

* Operating system and version:

* Ant Media Server version: 4.2.1
* Browser name and version: Chrom 96.0.4664.93

**Comment by golgetahir** [comment]
Hi @mhalahmadi

With these changes you can apply, the problem will be resolved. It will be merged and released for the next release but it is easy to apply javascript changes. Please check this: https://github.com/ant-media/StreamApp/pull/231/files 
The files are located under /usr/local/antmedia/webapps/<your_app_name>

Thanks
