### ISSUE TITLE
playOnly start and end action to webhook

### ISSUE THREAD

**Issue by ashrafbendary** [ant-media/Ant-Media-Server#3798]
**Is your feature request related to a problem? Please describe.**
webhook capture conference start and end action but when you use playOnly mode for attending it dosent see you
  
**Describe the solution you'd like**
start capture start and end actions for attendance so we can integrate with applications to capture attendance time and create reports according to that.

**Comment by mekya** [comment]
Webhook for each attendee does not sound very good to me.  
It may be a solution that tracks events on the player side. There are callbacks in JS side to handle the events. 

Does that make sense?
