### ISSUE TITLE
Make StreamSource Fetching Restart Period Parametric

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#38]
Stream Fetcher stops and starts the streams periodically to create VoD files. 
Some use cases do not need to have VoD files so that periodicity should be parametric. 

There should be a parameter in properties file with name

settings.streamFetcherRestartPeriod=

this field should be in seconds and stream fetcher will be restarted periodically with this value. 

If this field is not defined or value is zero then stream fetcher will not restart periodically. 
It will work continuously and it restarts only when there is a problem in the stream or in the network

**Comment by mekya** [comment]
@maydin @davutcavdar bununla ilgili pull request yaptım. Gözden geçirir misiniz?

https://github.com/ant-media/Ant-Media-Server/pull/67

**Comment by davutcavdar** [comment]
Roger that

**Comment by maydin** [comment]
👍
