### ISSUE TITLE
How to install Ant Media on Ubuntu 21.04?

### ISSUE THREAD

**Issue by flagam1** [ant-media/Ant-Media-Server#3802]
Hello.

Recently I wanted to install "ant media" games on Ubuntu 21.04, it turned out that I can't do it, because the sh installation file is not adapted to the newest Ubuntu. My question is this. So how should you install "ant media" on version 21.04?

Eventually I was forced to downgadre ubuntu to version 20.04 to be able to use the script (luckily I could afford it, because VPS didn't contain anything important except this software)

It does not change the fact that I am interested in this topic, how is it installed on 04/21 and how the software is updated to a newer version, if such an update appears. Please give me feedback.

Thank you and best regards.

**Comment by mekya** [comment]
Moving this issue to the backlog to schedule. 

Thank you @flagam1

**Comment by mekya** [comment]
Hi @flagam1 ,

Install script is updated. Could you please check it?

Please feel free to open if it's not working for you.

**Comment by flagam1** [comment]
> Hi @flagam1 ,
> 
> Install script is updated. Could you please check it?
> 
> Please feel free to open if it's not working for you.

Currently, I have already installed on version 20.04. How is your script updated when there is a new version?
