### ISSUE TITLE
In cluster, WebRTC port range properties are not updating in nodes when doing changes in MongoDB

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3812]
### Short description
When we change WebRTC minimum and maximum port range settings in MongoDB, it does not update for origin or edge nodes in cluster.

### Environment
* Ant Media Server version: v2.4

### Steps to reproduce
1. Deploy cluster
2. Change WebRTC min and max port range
3. check the settings on origin or edge node

### Expected behavior
These settings should update for nodes in cluster.

### Actual behavior
Port range is not updated for nodes.

**Comment by mekya** [comment]
This problem is my mind for some time.  

In addition, I've been working "settings" related issue and I've just implemented something that access fields in somewhere so I've just pushed a commit that fixes this and similar field problems.
