### ISSUE TITLE
Javascript SDK: Browser crashing when no applicable media devices present

### ISSUE THREAD

**Issue by petsoukos** [ant-media/Ant-Media-Server#3819]
### Short description
When using the Javascript SDK to create a browser based streaming UI, the browser crashes when no applicable media devices present.

Looking at the webdev console there is a torrent of messages:
```
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
```
Leaving it running eventually crashes the browser

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: Not applicable
* Ant Media Server version: Enterprise Edition 2.4.1 20211124_1803
* Browser name and version: Chrome & Chromium 96, Opera 82, Firefox 95

### Steps to reproduce
1. Unplug any input device of type 'audioinput', 'videoinput'
2. Open your page and view the javascript console
3. Leave it running, if you have low system resources it should crash

### Expected behavior
Should stop and return a message of no devices found

### Actual behavior
Endless looping which may cause the browser to crash if system has low resources (RAM)

### Logs
```
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
Audio input not found
webstreamer.js:331 Retrying to get user media without audio
```

**Comment by mekya** [comment]
Moved to the Backlog to schedule

**Comment by golgetahir** [comment]
Hi @petsoukos

Fixed with the above PR.

Thanks
