### ISSUE TITLE
WebRTCAdaptor double initialization

### ISSUE THREAD

**Issue by petsoukos** [ant-media/Ant-Media-Server#3821]
### Short description
Seems like the WebRTCAdaptor class gets triggered twice, even if I use the index.html example, on my domain, it triggers twice but on the antmedia server instance it works as expected. On all browsers on Ubuntu and on all browsers on Windows. Literally took the index.html file from the antmedia server (with all javascript and stuff) and threw it on a random server and I get

websocket connected
initialized undefined
websocket connected
initialized undefined

it comes from the console.log() inside the callback of the class.
```
webRTCAdaptor = new WebRTCAdaptor({
        debug: false,
        websocket_url: "wss://mydomain.tld:5443/WebRTCAppEE/websocket",
        mediaConstraints: {
            video: {
                width: {
                    min: 720,
                    max: 1080,
                },
                aspectRatio: 1.7777,
                frameRate: {
                    min: 20,
                    max: 30,
                    ideal: 25,
                },
            },
            audio: true,
        },
        peerconnection_config: {'iceServers': [{'urls': 'stun:stun1.l.google.com:19302'}]},
        localVideoId: "video-element",
        bandwidth: "unlimited",
        callback: (info, obj) => {
            console.log(info, obj);
        },
        callbackError: function(error, message) {
            console.log(error, message);
        }
    });
```
On the dev tools' network tab, I see 2 websockets connections
```
websocket connected
initialized undefined
websocket connected
initialized undefined
```

### Environment

* Operating system and version: Ubuntu 20.04 with any browser, Windows with any browser
* Java version: not applicable
* Ant Media Server version: 2.4.1
* Browser name and version: All browsers

### Steps to reproduce
1. Take index.html and all related files (css, javascript) from the server's examples (located: /usr/local/antmedia/webapps/WebRTCAppEE/index.html)
2. Place it on a different webserver
3. Open this page and check the Console in webdev tools

### Expected behavior
Have only 1 websocket connection, just as it does when opening the example from the instance.

### Actual behavior
Initializes 2 websocket connections

### Logs
```
websocket connected
initialized undefined
websocket connected
initialized undefined
```

**Comment by mekya** [comment]
Hi @petsoukos ,

Thank you for the issue. I think it's resolved in the latest snapshot but let's check it again.

**Comment by petsoukos** [comment]
Hello,

Yes, I had to figure it out that the NPM pacakge was not to the latest version. Please fix that also.

**Comment by mekya** [comment]
hmm, maybe that's the problem. Thank you.  Let us check NPM package automation and monitoring again.

**Comment by golgetahir** [comment]
Fixed in https://github.com/ant-media/Ant-Media-Server/issues/3822

**Comment by mekya** [comment]
Duplicate #3822
