### ISSUE TITLE
"NotReadableError" error on switching a camera & mic (Chrome for Android)

### ISSUE THREAD

**Issue by Flaeron** [ant-media/Ant-Media-Server#3826]
### Short description
When I try to switch a camera and microphone a few times from a mobile device an error "Camera or Mic is being used by some other process that does not let read the devices" appears.

### Environment

* Operating system and version: `Android 11`
* Ant Media Server version: `Enterprise Edition 2.4.1 20211124_1803`
* Browser name and version: `Chrome 96.0.4664.104`

### Steps to reproduce
1. open `/WebRTCAppEE/index.html` from a mobile Chrome (Android)
2. open `Options`
3. switch a camera to the `back`
4. switch a mic to any option except default
5. switch a camera to the `front`

Also, the same issue appears when I try to switch quickly from one camera to another.

### Expected behavior
Switching works properly without any errors.

### Actual behavior
After switching a camera (front/back) & mic gets an error.

**Comment by mekya** [comment]
Thank you @Flaeron , moving to the backlog to schedule

**Comment by golgetahir** [comment]
Hi @Flaeron 

Audio and camera switches are resolved with the mentioned PR. However, about switching quickly, it takes time to load in some devices, it is expected behavior to get that error therefore if you try to switch before loading. What we can do is maybe not allowing switching for a while after the button is clicked but it feels like the same thing as it does with the current alert. What do you think about it ?

Cheers

**Comment by Flaeron** [comment]
@golgetahir hello!

I assume that if we will be able to get the "switching state" and by this to disable buttons or for example use this "state" to show a loader it will be very helpful and it will help to avoid such kinds of errors. 

Thus if it's possible it would be handy to have for example something like `onEndedCallback` as the third parameter of the `switchVideoCameraCapture` function so we can catch a moment of the start of switching and with a callback catch the end of an async operation.

**Comment by golgetahir** [comment]
Hi @Flaeron

It makes sense, thank you for your suggestion, it is added to the related PR. If you have any other suggestions please feel free to hit us, feedbacks are always valuable.

Cheers

**Comment by mekya** [comment]
It's merged to the master and it'll be available in the next snapshot.  

Snapshot changelog is available here. 
https://antmedia.io/latest-snapshot/

Do you want to get notified when a new snapshot is available? @Flaeron 
If yes, what kind of notification is good for you? Email, tweet, slack channel

**Comment by Flaeron** [comment]
@mekya Thank you! 

Currently, no notification is required, as you have a link where we can check the changelog by need.

**Comment by jerzy-dudzic** [comment]
Correct me if I'm wrong, but if you look at the `switchVideoCameraCapture` in `webrtc_adaptor.js` in branch master, it does accept `onEndedCallback` but it never calls it.

It doesn't seem to be an only Chrome for Android issue, as I'm having the same issue on Chrome 98 for desktop.
