### ISSUE TITLE
Audio-only RTMP to HLS stream

### ISSUE THREAD

**Issue by spiermar** [ant-media/Ant-Media-Server#384]
# Issue

### Short description

Looking to stream live to AMS via RTMP, and consume the HLS stream from the clients (web and mobile). Using ffmpeg to encode a live stream.
If I include both audio and video tracks/streams, it works as expected, but if I only include an audio track/stream, I can consume the audio via RTMP, but not HLS. Both .m3u8 and .ts files are empty in the streams directory.

### Environment

[X ] Operating system and version: Ubuntu 16.04
[X] Java version: OpenJDK 8
[X] AMS version: Community Edition 1.4.1

### Expected behavior

Send an audio-only stream to AMS via RTMP, and consume this audio-only stream via HLS.

### Actual behavior

.m3u8 playlist is empty and 000.ts file too, so HLS streaming does not work. Consuming the same audio-only stream via RTMP works. Audio and video streams with the same setup work as expected. No out of the ordinary errors or messages in the logs. Stream shows as broadcasting normally in the UI, but I can't play the stream.

### Steps to reproduce

1. ffmpeg -v verbose -f avfoundation -i ":0" -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k -f flv rtmp://<ams_server>/LiveApp/<stream_id>
It's ffmpeg running on a Mac (avfoundation), `":0"` means there is no video input, only audio. `"0:0"` means is both audio and video, and that works. On Linux, the input configuration is slightly different, but the rest of the command should be the same.
2. 
3. 

### Logs

https://wsi.li/1Dco0LVG6wUt

**Comment by mekya** [comment]
Hi @spiermar ,

This issue is resolved for version 1.5.1.1. Could you please check it out and let us know if it is working for you?

Regards,
A. Oguz

**Comment by spiermar** [comment]
Hey @mekya ! Thank you for the update. I'll try it out as soon as I can. Cheers, Martin

**Comment by mekya** [comment]
Hi @spiermar ,

Thank you, closing this issue. Please re-open it if it's not working for you.
