### ISSUE TITLE
DataId field is Null in the response for REST API Call /v2/broadcasts/{id}/recording/{recording-status}

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3845]
### Short description
DataId field gives a null value in response to the REST API calls made for starting and stopping recording on FLY /v2/broadcasts/{id}/recording/{recording-status}

### Environment
* Ant Media Server version: v2.4.1

### Steps to reproduce
1. Start a stream.
2. Make the REST API call to start/stop recording for the stream on FLY.

### Expected behavior
DataId field in response should give a string value as documented https://antmedia.io/rest/#/BroadcastRestService/enableRecording

### Actual behavior
DataId filed in response gives null.
 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi Mohit,
It's an expected behavior. DataId is not filled all the responses. The `Result` response is generic that is being used many places.

**Comment by mekya** [comment]
Then I'm closing this issue. Please feel free to reopen if you think it's not ok.
