### ISSUE TITLE
Support uploading/deploying third party application to the Ant Media Server

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3856]
**Describe the solution you'd like**
Applications are built on top of Ant Media Server such as webinar, video chat, conference etc.  Let the users provide applications with good UI and focus on specific vertical 

**Describe alternatives you've considered**
Searching/Deploying automatically through web panel seems much more easy

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/452
