### ISSUE TITLE
Create Flag to play RTMP stream if required

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3863]
**Is your feature request related to a problem? Please describe.**
We have successfully integrated tokens for stream publish and play security. But we found out that if anyone has the RTMP url, they can play the stream through RTMP using VLC media player without the token.

**Describe the solution you'd like**
As RTMP playback is not recommended, it should be removed by default. In case user want to play the RTMP so it can be played by enabling the RTMP flag in the properties.

**Comment by WarrenG-I** [comment]
I agree that having RTMP stream access is actually a major security issue when you have play tokens in place. Looking forward to get a new version with a fix to this.

**Comment by mekya** [comment]
Thank you so much for your comment that reminds us this issue again. Let us schedule it.

**Comment by mekya** [comment]
Let's create the flag for RTMP playback and make the default value false
