### ISSUE TITLE
Is it possible to stream cctv rtsp streams to webrtc.

### ISSUE THREAD

**Issue by anand-010** [ant-media/Ant-Media-Server#3881]
I am new to this repo i am tring to stream my cctv rtsp streams to webrtc using this repo i have already added stream url to WebRTCApp and i don't know how to stream it to webrtc.
Please someone help me.

**Comment by yashtandon113** [comment]
Hi @anand-010 
I think you are using community edition and in CE webrtc playback is not supported but HLS can be played. Please check [doc](https://github.com/ant-media/Ant-Media-Server/wiki/HLS-Playing) for HLS playback.
WebRTC playback and other features are available in Enterprise edition. You can check comparison [here](https://github.com/ant-media/Ant-Media-Server/wiki/Introduction) & for the trial of AMS enterprise edition you can mail on contact@antmedia.io

**Comment by mekya** [comment]
Hi @anand-010
I'm closing this issue for the inactivity. Please feel free to re-open if you would like to discuss.
