### ISSUE TITLE
When the playlist finishes the last video, don't loop to the beginning

### ISSUE THREAD

**Issue by Toxic-Omega** [ant-media/Ant-Media-Server#3910]
So i have a playlist with around 200 videos, and when the playlist finishes streaming i would like it to stop streaming instead of looping?
Is there any way i could do this? Thanks

**Comment by mekya** [comment]
Thank you for the issue. Let's assign someone in the team to take a look at this.

**Comment by Toxic-Omega** [comment]
thanks, and its not a issue

**Comment by Toxic-Omega** [comment]
I fixed it myself. I changed "var_regex = re.compile(r"^\$*\w+\W")" on the 30th line of "/usr/local/lib/python3.9/dist-packages/pytube/cipher.py"
Thanks for the help...

**Comment by Toxic-Omega** [comment]
i accidentally closed the issue

**Comment by Toxic-Omega** [comment]
why did u you my message, i still need help!

**Comment by mekya** [comment]
@Toxic-Omega , as far as I understand, @SelimEmre  just would like to say that 'yes I got it, no worries'. 

This issue is scheduled for this week and there will be likely a snapshot ready to use in next week.

**Comment by Toxic-Omega** [comment]
oh ok,thanks

**Comment by SelimEmre** [comment]
Thank you for your explanation @mekya. Yes, @Toxic-Omega I realized about your accident. No worries. This feature is almost done.

**Comment by Toxic-Omega** [comment]
and one last thing, how do i download this change, and how do i enable the option?

**Comment by SelimEmre** [comment]
Hi @Toxic-Omega, you can download the SNAPSHOT version for using this feature after the merge to master. I just added `Enable Playlist Loop` option in playlist details. It's enabled by default. It can be disabled according to usage. Is it ok for you?

**Comment by mekya** [comment]
Where is the `Enable Playlist Loop`?

**Comment by SelimEmre** [comment]
I have added `Enable Playlist Loop` as below:
![Screenshot from 2022-01-31 12-05-23](https://user-images.githubusercontent.com/9084130/151766327-bf2da116-35b1-4792-a8b3-e183bf1cb0cf.png)

**Comment by mekya** [comment]
Thank you @SelimEmre for making it clear.

**Comment by SylvainSB** [comment]
Hi,
Nice, could we also please get this parameter in the API method?

Thanks

**Comment by Toxic-Omega** [comment]
> Hi, Nice, could we also please get this parameter in the API method?
> 
> Thanks

That would be nice!

**Comment by SelimEmre** [comment]
Hi @SylvainSB,

`playlistLoopEnabled` parameter is in broadcast object. If you want to use via REST API, you just need to update broadcast object `playlistLoopEnabled` parameter to `true` or `false`. 

For more detail, please check this guide: https://github.com/ant-media/Ant-Media-Server/wiki/REST-Guide

**Comment by Toxic-Omega** [comment]
I see you merged this to master, so i downloaded it, how do i install it? what do i run? thanks!

**Comment by SelimEmre** [comment]
Hi @Toxic-Omega,

It's not merged yet. These are PR's:
https://github.com/ant-media/Ant-Media-Server/pull/3926
https://github.com/ant-media/ManagementConsole_AngularApp/pull/161

If you want to upgrade your AMS version with your current settings, you need to add `-r true` parameter in your installation command. 

Please check it for more detail: https://github.com/ant-media/Ant-Media-Server/wiki/Installation#update-over-older-version

**Comment by SylvainSB** [comment]
Hi @SelimEmre 
I just tried the latest snapshot (Enterprise Edition 2.4.3-SNAPSHOT 20220131_0502 and I get

Unrecognized field "playlistLoopEnabled" (class io.antmedia.datastore.db.types.Broadcast), not marked as ignorable (49 known properties: "is360", "playListStatus", "plannedEndDate", "speed", "webMEnabled", "publicStream", "rtmpURL", "name", "plannedStartDate", "subFolder", "publish", "mp4Enabled", "duration", "username", "hlsViewerLimit", "password", "webRTCViewerLimit", "absoluteStartTimeMs", "zombi", "pendingPacketSize", "altitude", "playListItemList", "publishType", "latitude", "bitrate", "date", "longitude", "webRTCViewerCount", "status", "endPointList", "listenerHookURL", "expireDurationMS", "type", "streamId", "description", "category", "quality", "currentPlayIndex", "receivedBytes", "streamUrl", "mainTrackStreamId", "hlsViewerCount", "ipAddr", "userAgent", "originAdress", "rtmpViewerCount", "startTime", "subTrackStreamIds", "metaData"]) at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 102] (through reference chain: io.antmedia.datastore.db.types.Broadcast["playlistLoopEnabled"])
