### ISSUE TITLE
Support built-in backup streams and support different output url 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3917]
**Is your feature request related to a problem? Please describe.**
Yes,  I need to have a backup url if the primary fails. But there is no built-in solution for that.   

**Describe the solution you'd like**
1. There will be primary and backup streams for a stream. 
2. There will be no encoding on primary and backup streams at the same time. 
3. Primary and backup should have the same output and it should be configurable.  
4. If primary stream fails for some reason, backup stream will be activated and it starts to encodes according to the bitrates. 
5. Primary and backup streams will be on the same application but they can be on different origins. 
6. Player never knows if it plays primary or backup because primary and backup will have the same output.

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/471

**Comment by lastpeony** [comment]
We decided to build this feature on web player side. Check mentioned PR

**Comment by mekya** [comment]
Hi @burak-58,

I've added test codes to both the web player and integration test code to enterprise project to check if it switches to backup stream. I've merged them and this issue is closable for now.

FYI
