### ISSUE TITLE
Ant Media server installation on ubuntu 21.10

### ISSUE THREAD

**Issue by neevista** [ant-media/Ant-Media-Server#3929]
Hello,

I was planning to install Ant-media-server on ubuntu 21.10 and was wondering if the installer supports this version of ubuntu or not?

Has anyone tried installing on ubuntu 21.10 before?

Thanks in Advance!

**Comment by Mohit-3196** [comment]
Hi @neevista ,
How are you!
We are supporting 21.10 I think. I also tried to install AMS on 21.10 and it worked fine.
Here's the related PR https://github.com/ant-media/Scripts/pull/137

Please try and let us know if you face any issues.
Thanks.

**Comment by Mohit-3196** [comment]
Hi @neevista ,
Please let me know in case you are facing any issues.
If the installation worked for you, we can close this issue.

Thanks.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please feel free to re-open if it's not working for you
