### ISSUE TITLE
LiveStream RSTP didnt boardcast / stream index issue

### ISSUE THREAD

**Issue by yun00001** [ant-media/Ant-Media-Server#3934]
As the title said, i got the problem that when i start my LiveStream, Console will just keep spaming io.antmedia.muxer.TrmpMuxer not registered stream index 12345678
And at the start in console, it will said Could not write header to rtmp url rtmp://twitch's RTMP

Anyone know what happend here? was trying to host a LoFi Twitch Stream.

Edit: I self host this on my VM

**Comment by mekya** [comment]
Thank you for the issue @yun00001 , let us schedule this issue to confirm the case.

**Comment by yun00001** [comment]
Okay, @me when you found the issuse. Thank you.

**Comment by mekya** [comment]
Hi @yun00001 ,
My colleague @Mohit-3196 will confirm the issue to have the exact reproduce scenario. Btw, in order to confirm the issue, could you just write a reproduce scenario or sample stream? 


Regards,

**Comment by yun00001** [comment]
@mekya Sorry for the late reply.
Step are here:
Create VM (Ubuntu 20.04LTS) -> Setup Ant Media Server -> Applications -> LiveApp -> New Live Stream -> PlayList -> Named Playlist -> VoD -> Upload a mp4 file -> Copy ID -> Go back to Live Streams and paste on it -> Edit RTMP Endpoints -> add Twitch RTMP link / ID -> Start Boardcast -> Error.

Sorry if i miss reading, im not good at English.

**Comment by yun00001** [comment]
![image](https://user-images.githubusercontent.com/87031118/152043097-93dc7073-c150-4535-bff9-853109de7283.png)
here is the picture, just incase if you needed.
I have reset the youtube api key so dont worry

**Comment by Mohit-3196** [comment]
Hi @yun00001 ,
Thank you very much for the details.
Can you please let me know about the AMS version that you are using!
I tried to reproduce the case at my end with v2.4.2.1 and it went smooth.

Also if you would like, we can get on a quick call and look at the issue together.

Thank you

**Comment by yun00001** [comment]
@Mohit-3196 Version is [ Community Edition 2.4.2 20220125_1618 ]
Do you want to use Discord or other app? 
My Discord is Yun#9001

**Comment by yun00001** [comment]
is it cause server cpu is Xeon, and some Xeon cpu wont have encoding on it?

**Comment by Mohit-3196** [comment]
Hi @yun00001 ,
Thank you for version details.
I don't think that using Xeon processor will cause any issue.
Let's have a quick meeting on Google Meet if you can share you mail address please or you can even provide me remote access of the server through anydesk.

Thanks

**Comment by yun00001** [comment]
My email is: yuen2020tw@gmail.com i'll sent you anydesk id after i join Google Meet.

**Comment by Mohit-3196** [comment]
Thank you @yun00001 
I have sent you an invite.

**Comment by yun00001** [comment]
Solve! Thank you for taking time in google meet to help me!

**Comment by mekya** [comment]
Thank you so much guys @Mohit-3196 @yun00001 ,

May I ask what the problem is and how did you resolved that? 
Because maybe some other guy will just have the same issue and would like to know how it's resolved.

**Comment by Mohit-3196** [comment]
I have checked the specific MP4 file and it seems fine as the audio codec is AAC.
I think preliminary it seems to be related to FPS as the file has FPS 6.
I'm looking into this and I will update here with the exact findings.

Thank you

**Comment by yun00001** [comment]
> I have checked the specific MP4 file and its audio codec is AAC.
> 
> I think preliminary it seems to be related to FPS as the file has FPS 6.
> 
> I'm looking into this and I will update here with the exact findings.
> 
> 
> 
> Thank you

Okay!

**Comment by Mohit-3196** [comment]
Hello,
I have checked the file and logs related to it.
When we upload the MP4 file and create Playlist with this [MP4 file](https://drive.google.com/file/d/1HGqMFQA9Mt3gEYbKmmgNcbrHpfLDS4TR/view?usp=sharing) and start the playlist, with WebRTC playback it gives below error:

022-02-02 14:58:10,203 [vert.x-worker-thread-48] ERROR i.a.e.adaptive.StreamAdaptor - java.lang.NullPointerException: Pointer address of argument 2 is NULL.
	at org.bytedeco.ffmpeg.global.avutil.av_rescale_q(Native Method)
	at io.antmedia.enterprise.webrtc.WebRTCMuxer.writeVideoBuffer(WebRTCMuxer.java:668)
	at io.antmedia.enterprise.adaptive.base.VideoEncoder.writeVideoBuffer(VideoEncoder.java:350)
	at io.antmedia.enterprise.adaptive.StreamAdaptor.write2VideoEncoderBuffer(StreamAdaptor.java:303)
	at io.antmedia.enterprise.adaptive.StreamAdaptor.execute(StreamAdaptor.java:247)
	at io.antmedia.enterprise.adaptive.StreamAdaptor.lambda$start$0(StreamAdaptor.java:182)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

It works fine with HLS playback.

Also, when publishing the MP4 file as RTMP and playing with WebRTC works fine and adding RTMP endpoint works too.

The reproduce scenario for the issue is:
1. Upload the MP4 file to AMS VODs.
2. Create a playlist with the VOD file.
3. Start the playlist.
4. Play the stream as WebRTC and add RTMP endpoint.

Expected Behaviour:  WebRTC playback should work fine.

Actual Behaviour: WebRTC playback dosen't work.

Thanks.

**Comment by yun00001** [comment]
Hmm, i guess i'll try it again?

**Comment by Mohit-3196** [comment]
Hi @yun00001 ,
Sure you can try it. 
However, you might not see these errors on Community Edition as WebRTC playback is supported on Enterprise Edition.

Here's something you can try with this MP4 file. You can use any encoder like [OBS](https://github.com/ant-media/Ant-Media-Server/wiki/Open-Broadcaster-Software-Publishing) and push the stream as RTMP to AMS and then add the YouTube endpoint.

It should work most probably.

Also we'll check the reason behind these NullPointerException errors.

Thank you.

**Comment by yun00001** [comment]
Hey! @Mohit-3196 
Thank you for the information, i have tried the OBS RTMP guide, and it worked all good!
Many Thanks for the info that you provide, and big thank you for keep updating these type of problem!

Huge thumbsup!

**Comment by Mohit-3196** [comment]
Hello @yun00001 
Thank you very much for your kind words :)
Also, we'll review the logs and try to understand what's causing that.

Thank you
