### ISSUE TITLE
Release 2.4.2.1 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3940]

**Comment by suricloud** [comment]
Hi,

I just installed fresh on ubuntu 20.04
but antmedia page is not loading
get stuck here
HTTP Status 404 – Not Found

**Comment by suricloud** [comment]
HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.73

**Comment by mekya** [comment]
Hi @suricloud ,

You're right. For some reason, automation does not include the webapp.  
I've just updated the package. It's working for me. 

Could you please download and try again?
https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.4.2.1

**Comment by suricloud** [comment]
yes,working now :)

**Comment by mekya** [comment]
Good to know.

Btw, are you open having such a partnership discussion with Ant Media? Maybe suricloud can be listed on the main page(https://antmedia.io) with AWS, Azure, and others?
