### ISSUE TITLE
Wrong instructions in Wiki for Fresh install

### ISSUE THREAD

**Issue by Molnfront** [ant-media/Ant-Media-Server#3944]
There is a bug in your Fresh install instructions.

### Environment
Ubuntu 20 ARM

### Steps to reproduce
1.  Read the instructions
2. Try to follow it
3. Bug

### Expected behavior
There is no file. The instruction is wrong.

Fresh Installation
For a clean new installation:

sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE] 

### Actual behavior

You only have to issue this command: sudo ./install_ant-media-server.sh

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi @Molnfront ,

Thank you for the issue. I think there is something wrong. Let's confirm this issue. 

@Mohit-3196 , could you help confirming the issue?

Regards,

**Comment by mekya** [comment]
Closing the issue for the inactivity. 

Please feel free to reopen if it does not work for you @Molnfront
