### ISSUE TITLE
No LiveStreams detail in Kafka If WebRTC Disabled

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#3951]
### Short description

If WebRTC is disabled, streams that are being published via RTMP will not appear on Kafka

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: 11
* Ant Media Server version: 2.4.1
* Browser name and version:

### Steps to reproduce
1. Open the following file with the editor
`/usr/local/antmedia/webapps/WebRTCAppEE/WEB-INF/red5-web.properties`
2. Change the following line from true to false
`settings.webRTCEnabled=false`
3. Restart Ant Media server
4. Publish via RTMP
4. Check your Kafka output

Example Output:
```
{"instanceId":"48e9e7cb-da16-44cb-b21e-c63662841703","cpuUsage":{"processCPUTime":13450000,"systemCPULoad":0,"processCPULoad":0},"jvmMemoryUsage":{"maxMemory":517996544,"totalMemory":251658240,"freeMemory":171906128,"inUseMemory":79752112},"systemInfo":{"osName":"Linux","osArch":"amd64","javaVersion":"11","processorCount":2},"systemMemoryInfo":{"virtualMemory":3117555712,"totalMemory":2065936384,"freeMemory":77037568,"inUseMemory":1988898816,"totalSwapSpace":2147479552,"freeSwapSpace":2146942976,"inUseSwapSpace":536576,"availableMemory":1274761216},"fileSystemInfo":{"usableSpace":10852040704,"totalSpace":21000437760,"freeSpace":11942400000,"inUseSpace":9058037760},"jvmNativeMemoryUsage":{"inUseMemory":420745216,"maxMemory":1035993088},"gpuUsageInfo":[],"localWebRTCLiveStreams":0,"localWebRTCViewers":0,"localHLSViewers":0,"encoders-blocked":0,"encoders-not-opened":0,"publish-timeout-errors":0,"vertx-worker-thread-queue-size":0,"webrtc-vertx-worker-thread-queue-size":0,"server-timing":{"up-time":212180,"start-time":1643138713626},"time":"2022-01-25T19:28:45.786374Z","host-address":"192.168.1.251"}
```
### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/467
