### ISSUE TITLE
Application Live Stream rest request returns only RTMP Live Streams

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3952]
### Short description
`/v2/applications/live-streams/{appname}` REST request returns only RTMP Live Streams. It should include other live stream types.

### Steps to reproduce
1. Publish WebRTC Stream 
2. Call `/v2/applications/live-streams/{appname}` REST request
3.It shows nothing

### Expected behavior
It should count WebRTC Live Stream as well

### Actual behavior
It's counting only RTMP Live Streams.

**Comment by mekya** [comment]
That method(Web panel REST method) should be deprecated. No need to fix this issue.

Same information is accessible through application's REST API
