### ISSUE TITLE
App Store Registration followup 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#396]

**Comment by mekya** [comment]
Yeah we've d-u-n-s number(520101780)

about two factor authentication. I need password for antmedia.development@gmail.com?

**Comment by ogulcan** [comment]
Status: Your enrollment is being processed.

**Comment by ogulcan** [comment]
@mekya, I forwarded an email to you, please let me know when you check it.

**Comment by ogulcan** [comment]
This is a friendly reminder that we need to complete our process with payment :)
