### ISSUE TITLE
Ant Media server live Stream Storing with Min.io Server is not working

### ISSUE THREAD

**Issue by mohandass-pat** [ant-media/Ant-Media-Server#3963]
### Short description
I can able to give AWS S3 as a storage target. the data will be stored in the bucket after the live stream completes.

But If I try this approach with Min.io server endpoint (custom endpoint) it fails to store the stream file in the bucket.

I'm using AntMedia with Docker.

Will this approach work with Min.io?

### Environment
* Docker Image: nibrev/ant-media-server
* Operating system and version: docker
* Ant Media Server version: Community Edition 2.4.1 20211124_1905

### Steps to reproduce
1. Create App.
2. Give Minio Server endpoint and Credentials for S3 storage.
3. Start Mp3 recording.
4. After finishing files will not be stored in Minio Bucket.

### Expected behavior
After Finishing the record Files stored in VoD and can be accessed from there and also It should be stored in given Min.io Bucket (Min.io is S3 API compatable Server.). 

### Actual behavior
After Finishing the record Files stored in VoD and can be accessed from there and also It fails to store in given Min.io Bucket 
 
### Logs
2022-02-05 10:25:11,684 [vert.x-worker-thread-39] INFO  io.antmedia.muxer.RecordMuxer - Storage client is available saving 0001.mp4 to storage
2022-02-05 10:25:11,941 [vert.x-worker-thread-39] ERROR io.antmedia.muxer.RecordMuxer - Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null; Proxy: null)

Also attached the Minio Configuration screenshot in AntMedia App Settings Page.

![Screenshot from 2022-02-05 16-06-25](https://user-images.githubusercontent.com/43599092/152639091-466268da-5d4c-4860-bbf4-7f5c966e6e54.png)

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by Mohit-3196** [comment]
Hello @mohandass-pat ,
How are you!

Here's a similar issue that you can refer to https://github.com/ant-media/Ant-Media-Server/issues/3277

If the problem still exists after making the changes please let me know.

Thank you

**Comment by mohandass-pat** [comment]
@Mohit-3196 It Works with Minio new version. Thankyou

**Comment by Mohit-3196** [comment]
Hello @mohandass-pat 
It should upload to the respective buckets which are configured in the application settings.

Can we check this together please!

Thank you

**Comment by mohandass-pat** [comment]
Hello @Mohit-3196. Thanks for your support. 

Actually, the problem is if I configure with AWS S3 the recordings will be uploaded in their respective buckets. But If I give Min.io configurations it always looking for bucket name with streams. If I create a bucket it uploads all the recorded files in "streams" bucket, even though my configured bucket name for app is different.

Looks like if there is endpoint in s3 configurations, it ignores bucket name and always trying to upload in "streams" bucket. (Actually in aws S3 "/streams" is the prefix in all recording files).

Here I attached all the tested screenshots.

I have two apps.

1st app (office came 01 configured with bucket name office-01), 1st app (office came 01 configured with bucket name office-02)

![Screenshot from 2022-02-10 10-52-36](https://user-images.githubusercontent.com/43599092/153349086-6513a8ae-353e-4de0-be99-0c05b34a6149.png)
![Screenshot from 2022-02-10 10-51-02](https://user-images.githubusercontent.com/43599092/153349090-157db6d6-d773-49f9-aaf7-c7851360ffc0.png)

Bucket there are no files uploaded in these buckets in min.io.

![Screenshot from 2022-02-10 11-50-00](https://user-images.githubusercontent.com/43599092/153349472-fb8cda58-fc1b-47e2-a5e4-f1560a807213.png)

All the recored files uploded in "streams" bucket. but the prefix "streams" is missing. 

![Screenshot from 2022-02-10 11-51-41](https://user-images.githubusercontent.com/43599092/153349629-9629a4b0-70b2-4d2c-9048-e25b8c705ba4.png)

Looks like for minio for all apps it takes "streams" as bucket name, instead of configured bucket name for respective apps.

Note: Im using ant-media docker image (https://hub.docker.com/r/nibrev/ant-media-server). I belive this is the official one. and it is community version. (Community Edition 2.4.2 20220125_1618).

Thank you.

**Comment by mekya** [comment]
I think this issue is resolved. Closing the issue. Please feel free to reopen if it's not working for you.
