### ISSUE TITLE
Automatically push stream to Social Media (EX. Facebook)

### ISSUE THREAD

**Issue by danielbogdan** [ant-media/Ant-Media-Server#3981]
Hello,

We are a compani that we have in arround of 200 clients and thei want to stream to socials page.
To be more explicit, if you don't log on to the facebook page and enter the stream section, add the title of the stream you can't go live, and this has to be done manually, guys, we are in 2022, something like this should not be done to happen!
Unfortunately, the current solution does not allow the video to be published automatically on client pages, this is a big shortcoming, I searched in the version history and it seems that this option was once available. we come from the wowza platform, the people there offer this option, at the moment we use our own solution but also, it does not automatically push video to video on social stream.

Can anything be done about it?

Thanks!

**Comment by Mohit-3196** [comment]
Hello @danielbogdan ,
How are you!
Yes, you are absolutely right and we completely understand your point.

We want to be absolutely honest with you and help you with this. We had this feature in previous versions but as you are aware that Facebook keeps on changing the REST methods and API from time to time and therefore one needs to keep updating the solution accordingly.
This requires resources and time and unfortunately we couldn't dedicate such resources and therefore we decided to drop it.

However as a workaround, you can use some third party tools to fetch the endpoints from Facebook and re-stream to it.

You can write to our community as well and maybe some community members can develop a solution for you or can offer an existing solution as well.
https://groups.google.com/g/ant-media-server

Thank you

**Comment by mekya** [comment]
Closing this issue for the inactivity. 
Please feel free to re-open if you would like to discuss
