### ISSUE TITLE
Save Videos in different resolution from AntMedia Panel 

### ISSUE THREAD

**Issue by chitranjan-morwal** [ant-media/Ant-Media-Server#3983]
Hello Team,

We need to know that while uploading videos on antmedia panel is there any option that these uploaded videos save in different resolutions like 720p, 480p, and 360p, etc. means it will convert in these formats automatically when we upload any VOD.

If you can guide me on this it will be very helpful for me.
Thank You

**Comment by Mohit-3196** [comment]
Hi @chitranjan-morwal 
Thank you for the issue.

Let me discuss about this feature with team and I will update you :)

**Comment by chitranjan-morwal** [comment]
Hello @Mohit-3196 

Thank you for replying to me.

We will wait for your next reply.

**Comment by Mohit-3196** [comment]
Hi @chitranjan-morwal ,
Thank you again.

We definitely want to help you with this as much as possible.

I think it's not viable to use CPU and system resources for this and therefore we can use some script to scale the video to different resolutions once it's uploaded.

ffmpeg scripts can be called to do this once the VOD file is uploaded to server.
e.g., ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4

Please let me know if it seems good to you.

I suggest maybe you can write to our community as well and some community members can offer to write a script for this.
https://groups.google.com/g/ant-media-server

If you would like we can try and provide a script as well.

Thank you

**Comment by chitranjan-morwal** [comment]
It's better to provide me the script and also let me know where I can use that script when people upload the videos it will save videos on a mentioned path.

**Comment by Mohit-3196** [comment]
Hi @chitranjan-morwal ,
Sure. Thank you for writing.

Let me check on the script and we'll provide it to you soon.

Thank you

**Comment by chitranjan-morwal** [comment]
Yes, We will wait for your next update.

Thank you

**Comment by SelimEmre** [comment]
Hi @chitranjan-morwal,

Let me explain how can you achieve it. You can watch the streams folder on Application folder. If there is an mp4 file added to streams folder, then script will work for transcoding different resolutions. I have added  an example below:

```
ffmpeg -i bunny.mp4 -vf scale=1280:720 -preset slow -crf 18 output-720p.mp4 -vf scale=720:480 -preset slow -crf 18 output-480p.mp4 -vf scale=480:360 -preset slow -crf 18 output-360p.mp4
```
Please check [this guide](https://ottverse.com/change-resolution-resize-scale-video-using-ffmpeg/) for more detail.

**Comment by SelimEmre** [comment]
Hi @chitranjan-morwal,

I have developed the VoD finish script feature. You can use it in your environment. You just need to add your script path to app settings as below:
```
settings.vodUploadFinishScript=/home/mypc/processScript.sh
```
For example:
settings.vodUploadFinishScript=/home/mypc/processScript.sh
After the VoD upload process Ant Media Server will run script as below:
```
~/test_script.sh /usr/local/antmedia/webapps/LiveApp/streams/test_stream.mp4
```

**Comment by chitranjan-morwal** [comment]
Thank you so much @SelimEmre for this. I will use these settings in my AntMedia Server.
