### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by noorAlshaar12** [ant-media/Ant-Media-Server#3991]
### Short description
__The button does not work as intended __

### Environment

* Operating system and version: windows10
* Java version:  
* Ant Media Server version: 2.4.2.1
* Browser name and version: chrome 98.0.4758.102

### Steps to reproduce
1. enter conference-room.Html
2. share screen
3.stoped screen share

### Expected behavior
__when we press the share screen button it might stop screen share__

### Actual behavior
__ when I press on share screen button it didn't stop sharing __

 

### Logs
__  __

**Comment by yashtandon113** [comment]
Hi @noorAlshaar12 
I tried above steps and screen share is stopping after clicking screen share button.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please feel free to re-open if there is a problem for you.
