### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by noorAlshaar12** [ant-media/Ant-Media-Server#3992]
### Short description
__ Functions are not working properly __

### Environment

* Operating system and version: windows10
* Java version: 
* Ant Media Server version: 2.4.2.1
* Browser name and version: chrome98.0.4758.102

### Steps to reproduce
1.  enter to conference-room.html
2.  start screen share
3. turn off camera

### Expected behavior
__ When the camera is turned off, the site should not turn off screen sharing __

### Actual behavior
__When the camera is closed, screen sharing is turned off and a black screen appears for the viewer__

**Comment by yashtandon113** [comment]
Hi @noorAlshaar12 
Thanks for reporting this bug and it will be scheduled soon.

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/265
