### ISSUE TITLE
bug3

### ISSUE THREAD

**Issue by noorAlshaar12** [ant-media/Ant-Media-Server#3993]
### Short description
__Open the camera suddenly__

### Environment

* Operating system and version: windows10
* Java version: 
* Ant Media Server version: 2.4.2.1
* Browser name and version: chrome 98.0.4758.102

### Steps to reproduce
1.  enter to conference-room.html
2.  start share screen
3. stop share screen

### Expected behavior
__When screen sharing is closed, the camera should not be opened__

### Actual behavior
__When you finish screen sharing, the camera will open automatically__

**Comment by yashtandon113** [comment]
Hi @noorAlshaar12 
As you have not turned off camera during screen share so after stopping screen sharing camera remains on. You need to turn off camera but that stops the screen share as you mentioned in another Git hub issue. I have also created one more issue related to conference-room.html [here](https://github.com/ant-media/Ant-Media-Server/issues/4002)
All these issues will be scheduled and fixed asap.
