### ISSUE TITLE
Blog post & Documentation about Multi tenancy support 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3994]

**Comment by SelimEmre** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/Multi-Tenancy-Support

**Comment by timantmedia** [comment]
I cant find a blog post about this, so does it need writing or can we close this task? @mekya

**Comment by mekya** [comment]
Then the blog post is lacking. It's likely that Selim wrote the doc and didn't write the blog post. 
Then, decision is yours. If you think, it's going to be useful to write this blog post in terms of giving information and SEO, let's create another issue for writing this blog post. 

I'm currently making this task done.

**Comment by asharamseervi** [comment]
Hi @timantmedia & @mekya;

Probably what Selim drafted at that wiki isn't Multi-tenancy at all. Kindly re-validate what multi-tenancy termed as [here](https://www.cloudflare.com/learning/cloud/what-is-multitenancy/)
This [feature request #4840](https://github.com/ant-media/Ant-Media-Server/issues/4840) is look like multi-tenancy feature request. Kindly correct me if I'm wrong!

**Comment by mekya** [comment]
There are just some discussions about that. We separate the data and users are using the same resource through applications.

**Comment by timantmedia** [comment]
Do you mean to allow multiple instances of AMS using the same codebase on the same server?  @mekya Would this need to support multiple licenses?

**Comment by mekya** [comment]
I don't mean allow multiple instances of AMS on the same server. I mean letting users have their own applications on the same server.

**Comment by timantmedia** [comment]
I've started some new documentation for this as to go in the get started section to go over the entire web panel which will include setting up users/roles.

**Comment by timantmedia** [comment]
Documentation has been update https://antmedia.io/docs/get-started/user-management/#how-to-use-multi-tenancy-with-rest-api blog post to be planned and include virtualHosts.

**Comment by mekya** [comment]
Including virtualhost would be good. TBH, I don't know how to configure the virtual hosts. I think it should be resolved while writing the post.
