### ISSUE TITLE
Use VideoJS WebRTC Plugin for Embedded Player

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4000]

**Comment by rahul7827** [comment]
Hello @mekya , Is this VideoJS WebRTC Plugin is stable now ?
Can I use it my production environment ?

**Comment by mustafaboleken** [comment]
> Hello @mekya , Is this VideoJS WebRTC Plugin is stable now ? Can I use it my production environment ?

Yes, it's stable and you can use it. Instead of master, latest bugfix is not merged, you can use this pull request https://github.com/ant-media/videojs-webrtc-plugin/pull/16
