### ISSUE TITLE
Conference-room stop screen share issue when camera is turned off before screen sharing

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4002]
### Short description
In conference-room.html functions of buttons are not working correctly.

### Environment
* Ant Media Server version: v2.4.2.1

### Steps to reproduce
1. Open conference-room.html
2. Turn off camera
3. Share screen 
4. Try to stop screen share by clicking screen share button

### Expected behavior
Screen sharing should stop

### Actual behavior
Screen sharing is not stopping after clicking button

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/265
