### ISSUE TITLE
Change default bit rate value in index.html is not applied 

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4003]
### Short description
Changing the bit rate value in index.html is not applying when stream started publishing and it takes the default value while changing in between the stream works fine. As a work around solution change the default value from 900 to desired value in index.html file.

### Environment
* Ant Media Server version: 2.4 and above

### Steps to reproduce
1. Open index.html
2. Change bit rate from 900 to any other value
3. Check stats

### Expected behavior
Bit rate should be changed 

### Actual behavior
Bit rate is not changing and default value is showing.

**Comment by SelimEmre** [comment]
https://github.com/ant-media/Ant-Media-Server/issues/4003

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/266

**Comment by SelimEmre** [comment]
https://github.com/ant-media/StreamApp/pull/266
