### ISSUE TITLE
Streams doesn't play in latest Chrome

### ISSUE THREAD

**Issue by vlasovim** [ant-media/Ant-Media-Server#4020]
Server
Enterprise Edition 2.4.1 20211124_1803 

Chrome
Version 98.0.4758.102 (Official Build) (64-bit)

Console

```
Candidate is added for stream stream87
sending ice candiate for stream Id stream87
{"candidate":"candidate:842163049 1 udp 1677729535 IP_ADDRESS 16248 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag W9Hf network-cost 999","sdpMid":"audio","sdpMLineIndex":0}
No event.candidate in the iceCandidate event 
play finished
```

**Comment by vlasovim** [comment]
In previous versions of Chrome

`
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'.
`

**Comment by Mohit-3196** [comment]
Hi @vlasovim ,
How are you!

Thank you for the issue.

Can you please share your Ant Media Server Web Panel login credentials so that we can look at the issue.

You can send the credentials on support@antmedia.io mentioning me (Mohit) and we can check this.

Thank you

**Comment by vlasovim** [comment]
Thanks for the reply! This is a local problem, probably in the turn server. The issue may be closed.

**Comment by Mohit-3196** [comment]
Hi @vlasovim,
Thank you for writing and letting us know :)

Have a great week.
