### ISSUE TITLE
WebM recording is rotated by 90 degrees when publishing from iPhone

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4024]
### Short description
When publishing a stream from iPhone and recording it as webM, the recorded stream is rotated by 90 degrees.

### Environment

* Operating system and version: iOS 15.3.1
* Ant Media Server version: 2.4.2.1
* Browser name: Safari, Chrome

### Steps to reproduce
1. Enable VP8 codec and set WebM recording on AMS.
2. Publish a stream to AMS.
3. Stop the stream.

### Expected behavior
The recorded WebM file should not be rotated.

### Actual behavior
The recorded WebM file is rotated by 90 degrees.

 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi @Nealsoni00 
The problem is being fixed with this issue
https://github.com/ant-media/Ant-Media-Server/issues/6099

FYI
