### ISSUE TITLE
Invalid Stream Info Stats on Firefox Browser.

### ISSUE THREAD

**Issue by rahul7827** [ant-media/Ant-Media-Server#4025]
**Short description**

Video source width & height returns -1 on **Firefox** when we call webRTCAdaptor.enableStats(obj.streamId);. I have tested only on chrome and Firefox browser as of now. On chrome browser it works fine.

**My Environment**

* Windows 10
* AMS version 2.4.1
* Firefox 97.0.1 (64-bit):

**Steps to reproduce**

Open this file and do the following changes : 
  https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/index.html

1. Update Line number 493 (var mediaconstraints)

**From**

`var mediaConstraints = {
	video : true,
	audio : true
};`

**TO** 

`var mediaConstraints = {
    video: {
                    width: { min: 1024, ideal: 1280, max: 4096 },
                    height: { min: 576, ideal: 720, max: 2160 },
                    aspectRatio:1.777777778,
      },
     audio:true
};`

Reason to make these changes is : I was not able to get expected video resolution for the viewer and publisher,  Instead of having a Higher resolution 4k camera.

**Expected behavior**
 **obj.resWidth** and **obj.resHeight** should return the actual video resolution (width & height). Instead of **-1**. In chrome browser it is working fine.

**Actual behavior**

 **obj.resWidth** and **obj.resHeight** is returning -1.

**Logs**
Average outgoing bitrate 907 kbits/sec Current outgoing bitrate: 948 kbits/sec video source width: -1 video source height: -1frame width: -1 frame height: -1 video packetLost: 0 audio packetsLost: -1 video RTT: 0.246 audio RTT: -1 video jitter: 0.011977777777777778 audio jitter: -1

After publishing the stream observe the console log, at this line [Link](https://github.com/ant-media/StreamApp/blob/06cf81f20c6bfbd37a3d40ae3bb95102f59d6985/src/main/webapp/index.html#L582)

**Comment by SelimEmre** [comment]
Hi @rahul7827,

Unfortunately, it's related to Mozilla Firefox browser. These parameters providing by browser side. Mozilla Firefox doesn't share these details. That's why these values -1. You can also check Default WebRTC sample pages in here: https://webrtc.github.io/samples/src/content/getusermedia/resolution/

You may use native video tag `videoHeight` and `videoWidth` values.  Please check below resources:
https://stackoverflow.com/questions/43291388/client-side-javascript-get-video-width-height-before-upload
https://stackoverflow.com/questions/31192925/get-the-original-dimensions-of-a-video
https://stackoverflow.com/questions/16272924/get-width-and-height-of-html5-video-using-native-javascript

**Comment by rahul7827** [comment]
Thank you @SelimEmre 

As an alternate solution I was using the same solution which you provided.

**Mozilla Firefox doesn't share these details.**

Do you mean Firefox does not share 'mediaConstraints'  details with MEDIA SERVER ?

**Comment by SelimEmre** [comment]
Hi @rahul7827,

> Do you mean Firefox does not share 'mediaConstraints' details with MEDIA SERVER ?

Let me explain it. Ant Media Server using default browser WebRTC internal stats for these details. Of course Firefox shares `mediaConstraints` parameters with Media Server. But resolution parameters not showing on Firefox WebRTC internal stats. Please check below details:

https://antmedia.io/an-overview-webrtc-statistics/
https://testrtc.com/webrtc-internals-parameters/

![Screenshot from 2022-03-12 00-42-39](https://user-images.githubusercontent.com/9084130/157974543-d21f9531-ef16-4b9d-93c8-543bcf41afa8.png)

I hope, it's clear for you.

Best Regards,
Selim

**Comment by rahul7827** [comment]
Thank you @SelimEmre for the detailed explanation. Now its clear to me.
