### ISSUE TITLE
HLS muxer doesn't delete segment files on exit with more than 4 digit suffixes

### ISSUE THREAD

**Issue by janne808** [ant-media/Ant-Media-Server#4047]
### Short description
When HLS muxer exits and deletes the segments it misses files with more than 4 digit suffixes and eventually fills the filesystem with unused segment files.

### Environment

* Operating system and version: Ubuntu 20.04.4 LTS (Focal Fossa)
* Java version: openjdk 11.0.14 2022-01-18
* Ant Media Server version: 2.4.2.1

### Steps to reproduce
1. sudo touch webapps/LiveApp/streams/live_55555.ts
2. Restart RTMP stream
3. ls -al webapps/LiveApp/streams/

### Expected behavior
Folder should not have live_55555.ts or any other segment file with more than 4 digit segment suffixes.

### Actual behavior
File live_55555.ts is present and eventually long live streams fill the filesystem with unused segment files.

**Comment by mekya** [comment]
Thank you for the issue @janne808 

I'm moving to the backlog to schedule.
