### ISSUE TITLE
Publish Timeout error in AWS EKS 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4054]

**Comment by PiotrBaczkowski** [comment]
I am having the issue right now.

**Comment by muratugureminoglu** [comment]
Hi @PiotrBaczkowski 

You can solve this problem by using the latest Dockerfile. (we already solved on your side :)) )

**Comment by muratugureminoglu** [comment]
Hi @PiotrBaczkowski 

Pods could not fetch public IPs due to a missing curl package. We added curl package for this reason.

Here is the updated Docker file: https://github.com/ant-media/Scripts/blob/master/docker/Dockerfile_Process

Let me know if you are still having the same issue.
