### ISSUE TITLE
Prepare simple Marketplace roadmap 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4078]

**Comment by SelimEmre** [comment]
Here is the requirements list:
Requirements list:
- Compatible with WordPress(Important)
- Support Vendor feature(Important)
- People can add their product(plugin or etc.)
- People can able to sell it. So, it should support Stripe plugin(Important)
- Compatible with Woocommerce plugin

Here are the results:
I have found some plugins for our requirements. They have some advantages and disadvantages.
[Easy Download Digitals](https://easydigitaldownloads.com/):
Advantages:
They are compatible with WordPress. They also support vendor features and stripe options in their solution. If we decide to use this plugin, we need to use at least Professional package.
Disadvantages:
It's not compatible with Woocommerce

[Dokan](https://wedevs.com/dokan//):
Advantages:
They are compatible with WordPress. They also support vendor features and stripe options in their solution. If we decide to use this plugin, we need to use at least Starter package. 
Disadvantages:
It's not compatible with Woocommerce

In my opinion: We can use both of these plugins. But Dokan plugin has many more features than Easy Download Digitals. They are covering our requirements. Compatible with Woocommcer is not a really important thing.
