### ISSUE TITLE
Create SRT ingest support for Load Balancer (UDP load balancing)

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4079]

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/Nginx-Load-Balancer#configure-nginx-as-a-load-balancer

**Comment by ekrem-pinar** [comment]
https://resources.antmedia.io/docs/installing-with-nginx-load-balancer
