### ISSUE TITLE
Dash Viewer count

### ISSUE THREAD

**Issue by mukk38** [ant-media/Ant-Media-Server#4110]
Hi , I am new on Ant media, Is there any way to get dash viewer count?

**Comment by mekya** [comment]
It's a good point @mukk38 ,

Let us add this feature to the AMS. I'm moving to the backlog to schedule this feature.

**Comment by SelimEmre** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/481

**Comment by ekrem-pinar** [comment]
What exactly are you solving here? Can you briefly summarize?

**Comment by SelimEmre** [comment]
Hi @ekrem-pinar,
It's basically an implementation of DASH viewer counts. It means that you can access DASH viewer counts in Broadcast object or Dashboard.
