### ISSUE TITLE
toggleAudio() doesn't work while stream playback -  iOS SDK

### ISSUE THREAD

**Issue by denmorgenshtern** [ant-media/Ant-Media-Server#4111]
toggleAudio() doesn't work while stream playback on iOS SDK
iOS ver 15.4
Or maybe it's wrong approach to mute stream?

**Comment by mekya** [comment]
Hi @denmorgenshtern ,

Thank you for the issue. toggleAudio is un/mute the audio while it's publishing. 

You can use  ` RTCAudioSession.sharedInstance()`  to control the audio. We may add a utility method for this to the iOS SDK

**Comment by denmorgenshtern** [comment]
Thank you for the clarification.

**Comment by mekya** [comment]
It's my pleasure.
