### ISSUE TITLE
Weird PNG naming and losing previews

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4124]
### Short description
Weird png file naming and losing the previews

### Environment

* Operating system and version: Ubuntu 20.04
* Java version:  11
* Ant Media Server version: 2.4.2.1

### Steps to reproduce
1. Enable Preview generation and Add adaptive bitrate
2. Publish stream1 and its preview is recorded as stream1.png
3. Re-publish stream1 and finish the recording, stream1.png is deleted and stream1_1.png is generated
4. Re-publish stream1 and finish the recording, stream1.png is generated. There is no stream1_2.png
5. Re-publish stream1 and finish the recording, stream1.png is deleted and stream1_2.png is generated
		

### Expected behavior
Naming must be proper and there should be no missing

**Comment by ekrem-pinar** [comment]
I tried to reproduce scenario as yo mentioned above. But there were some changes. 

I tried to explain the scenario I followed below. It seems to me that there is a bug here.

1. I selected the WebRTCAppEE application from the Dashboard.
2. I went to Settings.
3. I added a new bitrate from Adaptive Streaming (Resolution=480p)
4. I checked the Generate Preview checkbox in the Advanced Setting section.
5. I clicked the Save button and said "Settings saved. They're effective for the broadcasts starting from now on." I got the warning.
6. I started a stream named "stream1" in the new tab.
7. I saw that a file named "stream1.png" was created under the preview folder.
8. When I stopped the stream I started, I saw that the file "stream1.png" was deleted. But I saw that it was replaced by a file named "stream1_finished.png".
9. When I started the stream(stream1) with the same name again, I saw that there were two files named "stream1.png" and "stream1_finished.png" under the preview file.
10. When I stopped the stream that I started again, I saw that there were "stream1_finished.png" and "stream1_finished_1.png" files under the preview folder.
11. Below is a screen recording link that summarizes what I've been talking about. You can see faster if you want, brother.

https://www.loom.com/share/37df3231bbc648a4be783f0bcb5407f5

**Comment by mekya** [comment]
Hi @ekrem-pinar ,

It's an expected behavior. What do you expect to see?

**Comment by mekya** [comment]
hi @ekrem-pinar ,

The reproduce scenario is about the problem and bug. We've resolved the issue and have the whole file names by adding 'finished' suffix.  Please pay attention that there is no file missing as mentioned in the report.

**Comment by ekrem-pinar** [comment]
Hi @mekya ,

Thanks again for the information. 

According to the latest situation, the problem seems to be solved. Thanks for solution.
