### ISSUE TITLE
HLS files are not deleting from server after disabling mp4 recording option.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4139]
### Short description
If HLS segment size is 5 then after 6th segment received first one should delete but .ts files are not deleting as expected after the recording gets disabled. After restarting the server it started working again. 

### Environment
* Ant Media Server version: v2.4.2.1 & above

### Steps to reproduce
1. Publish the stream (HLS segment list size=5)
2. Check .ts files in streams directory, old one is deleting after new .ts file created
3. Stop the stream & enable mp4 recording
4. Publish the stream again, .ts files will not delete as expected
5. Disable the recording 
6. Publish the stream again

### Expected behavior
old .ts files should be deleted after new files created.

### Actual behavior
It keeps storing all HLS files. It started working again as expected after restarting the server.

**Comment by zenyr** [comment]
I have also sent a feedback via email but this MIGHT be related to triggering HLS preview. I was running 2 different instances of AMS separately and one had this issue while the other one didn't. Disk usage continuously grew up and just before reaching my EBS volume limit the live streaming ended and the disk usage almost immediately went back to normal.

**Comment by zenyr** [comment]
Glad that you found the issue! 👍 Sorry for the late response.
I'll have a healthy snack instead 😄 I'm all good, thank you and I look forward to do more with AMS in the future. 
(besides, South Korean Paypal is notoriously bad for receiving anything, while having no issues sending out something)

**Comment by mekya** [comment]
Haha sure :), let me connect you with my colleague so that he can send the gift card with the proper way. Mostly, we send starbucks or amazon gift card.  He will contact you through your email on your github account

> Glad that you found the issue! 👍 Sorry for the late response. I'll have a healthy snack instead 😄 I'm all good, thank you and I look forward to do more with AMS in the future. (besides, South Korean Paypal is notoriously bad for receiving anything, while having no issues sending out something)

**Comment by hamitdemir** [comment]
> Glad that you found the issue! 👍 Sorry for the late response. I'll have a healthy snack instead 😄 I'm all good, thank you and I look forward to do more with AMS in the future. (besides, South Korean Paypal is notoriously bad for receiving anything, while having no issues sending out something)

Hi Zenyr, how are you? I am Hamit from Ant Media. Can you share your email address with me? So I can send your gift card. :) If you want you can send me an email, hamitdemir@antmedia.io.

**Comment by hamitdemir** [comment]
> Glad that you found the issue! 👍 Sorry for the late response. I'll have a healthy snack instead 😄 I'm all good, thank you and I look forward to do more with AMS in the future. (besides, South Korean Paypal is notoriously bad for receiving anything, while having no issues sending out something)

Hi Zenyr, I am Hamit from Ant Media. I just send you an Amazon gift card. Thank you very much for your contribution.
Let me know if you need anything from Ant Media.

**Comment by zenyr** [comment]
> > Glad that you found the issue! 👍 Sorry for the late response. I'll have a healthy snack instead 😄 I'm all good, thank you and I look forward to do more with AMS in the future. (besides, South Korean Paypal is notoriously bad for receiving anything, while having no issues sending out something)
> 
> Hi Zenyr, I am Hamit from Ant Media. I just send you an Amazon gift card. Thank you very much for your contribution. Let me know if you need anything from Ant Media.

Just received one, appreciate ya'll!
