### ISSUE TITLE
Create infrastructure for javascript unit tests for StreamApp and implement test for #3976

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4140]
#3976

**Comment by USAMAWIZARD** [comment]
I have create a CI pipeline to test the JS test cases on CI but the test cases are failing
https://github.com/ant-media/StreamApp/pull/353

**Comment by mekya** [comment]
Moving to In Progress because change has requested
https://github.com/ant-media/StreamApp/pull/353#pullrequestreview-1405648873

**Comment by USAMAWIZARD** [comment]
I have updated the code to build from Enterprise and its working on CI

**Comment by mustafaboleken** [comment]
@USAMAWIZARD thank you very much for your efforts. It looks fine, I just approve it.

**Comment by USAMAWIZARD** [comment]
Thanks
