### ISSUE TITLE
Merged audio stream in AMCU mode not available or stalled

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#4143]
### Short description
We want to use an AMCU conference room to merge audio streams from remote participants and play them on a loud speaker in a lecture room. The students come and go, so that the list of streams is dynamic (we expect them to use mics only when asking questions). As long as new audio streams are added the merged stream contains all of them, but each time an audio stream is stopped, the merged stream either pauses for a short time or stalls completely (usually when only one stream is left). Moreover, the room info obtained via a websocket does not coincide with the response to a REST call (the latter lists more streams).

Another problem for us is that the merged stream is not created unless at least one student publishes his/her microphone (more at the end of the post).

### Environment

* Operating system and version: Ubuntu 18.04.6 LTS
* Ant Media Server version: EE 2.4.2.1 20220201_1956

### Steps to reproduce
Our testing setup
1. We have a number of <audio> elements, each playing a different audio file in a loop, and we capture audio streams from them.
2. Each stream can be added to or removed from a conference room with a fixed name.
3. A merged stream, when it appears, is played from the Ant Media panel or fetched with ffplay/ffmpeg.

We add a stream to the conference room as follows.
1. Open a websocket connection to a streaming app on Ant Media with ABR turned on.
2. Create a broadcast using REST API with a random `streamId`. We set up a webhook script in order to catch the `liveStreamStarted` and `liveStreamEnded` notifications.
3. Send the `joinRoom` command with parameters `room` (the fixed name), `mode` (set to `amcu`), and `streamId`.
4. Send the `publish` command to initiate publishing of the stream. We follow the WebRTC messaging reference here.
5. The stream appears on Ant Media and can be listened to, confirming that the last step works properly.

We remove a stream as follows.
1. We send the `stop` command to Ant Media and wait until the stream is stopped.
2. Then we send the `leaveFromRoom` command with `room` set to the fixed name.
3. Once our webhook receives `liveStreamEnded`, the broadcast is deleted from Ant Media (this may happen before 2).

We also consider adding an RTMP stream via REST API along the following steps.
1. Create a broadcast with a random `streamId`.
2. Add the stream to the conference room.
3. Stream some audio with ffmpeg using the `streamId`.

### Expected behavior
The merged stream appears as soon as the first stream is added to the conference room and is active as long as at least one stream is in the room. The response to `getRoomInfo` over websocket as well as to the corresponding REST API call should return the list of active streams in the room.

### Actual behavior
In the first scenario we add streams only via a websocket. When two streams are added and the first of the streams is stopped, the merged stream is stalled - the playback is paused. Fetching it with ffmpeg throws only warnings:
> [hls @ 0x55cf0636d700] Skip ('#EXT-X-VERSION:3')
> [https @ 0x55cf06974800] Opening 'https://{antmedia.url}:5443/{appName}/streams/{roomName}Merged_1080p.m3u8' for reading

and the ffmpeg process is unresponsive - pressing `q` has no effect.
The response to `getRoomInfo` over websocket returns an empty list, whereas as REST API call returns a list with ids of both streams.
Stopping all streams does not remove the merged stream, although the merged stream is empty (like in the case of a single stream).

In the second scenario we first add an RTMP stream. Now the merged stream does not appear at all. Adding more streams later may or may not trigger the merged stream to appear. After the conference room is deleted via a REST API call (to clean up), the merged stream no longer appears in both scenarios, although both a REST API call and `getRoomInfo` command confirms that a conference room exists.

### Further notes
The merged stream appears only when there is at least one stream in the conference room. This makes it hard to play the stream in our scenario reliably, so our current approach is to add a silent stream in order to make sure that the merged stream exists (well, this does not work currently). It would be nice when a silent merged stream exists also when there are no streams in a conference room in case the room has been created by a REST call. It would be great if in this REST call one can also set parameters for the merged stream (name, webhook url, etc.) and receives the id of the merged stream in the response.

**Comment by mekya** [comment]
Thank you so much @kputyra for the issue. 

We're moving to the backlog to confirm the issue this week.

**Comment by Mohit-3196** [comment]
Hello @kputyra ,
How are you!

Again, thank you very much for the detailed reporting and reproduce scenario.
I will try to reproduce the issue at my end and will get back to you ASAP.

Thank you.

**Comment by Mohit-3196** [comment]
Hi @kputyra ,
I tried to reproduce the issues and it's reproducible at our end with Sample pages as well.
We can confirm that it's a bug and we will be scheduling this at our end.

Also, there's a workaround solution for now which you can use if you think it's doable for you.
 1. Create the AMCU room with REST API.
 
 2. Join the conference room directly with streamId using JoinRoom.
In this way all the streamId in the room will be merged to AMCU.

 3. While leaving the room, instead of first stopping the stream and then leaving the room, you can directly send LeaveFromRoom

In this way the streamId will directly be added and removed from the conference room and it will not corrupt the merged Audio stream.

Currently when you are sending the stop command, though the stream is stopped but the streamId is still there in the conference room database and that's corrupting the merged stream.

Here's how you can test this with AMS sample pages.
1. Create an AMCU room with REST API call.

2. Join the AMCU conference room with streamId
e.g., https://domain:5443/LiveApp/conference.html?streamId=stream1

3. The merged stream will have all the streams merged within the AMCU room.

4. When you leave a room, the corresponding stream will be removed from the merged stream without corrupting the AMCU merged stream.

I hope it could be useful.

Please let me know if you come across some issue or in case I have missed anything.

Thank you!

**Comment by kputyra** [comment]
Hi @Mohit-3196 

I'm glad that you could reproduce the issue and thanks for suggesting a workaround. I will test it next week to see how it works in our setup.

There's one think I'm not sure about, though. You've mentioned the `JoinRoom` command - as I understand, this is in case of WebRTC streams. In our setup, however, the first stream sent to the conference room is an RTMP stream (silence or very quiet noise) - this was to guarantee that the merged stream exists, so that we can pull it an play on the loud speaker without waiting for any of the students to turn on their microphone. Unfortunately, the merged stream was not always created in this situation. The `streamId` is added to the conference room when it is created with REST API, so way before the stream is live. Do you think that adding the stream to the room after it becomes live might solve it?

Thank you!
