### ISSUE TITLE
Trying to live stream a playlist to youtube through Ant Media

### ISSUE THREAD

**Issue by TTVSaber3000** [ant-media/Ant-Media-Server#4154]
I am trying to create a 24/7 music stream through Ant Media I got everything set up but I am getting, Broadcasting 1.00x on the main area and on youtube it says this. What should I do?
![Screenshot 2022-04-20 194827](https://user-images.githubusercontent.com/103728764/164349739-92ea157d-47ca-4488-82ee-4beb0cbc9e38.png)

**Comment by yashtandon113** [comment]
@TTVSaber3000 
Did you add the RTMP end point of You tube in your Ant media server stream/playlist?  Please check https://resources.antmedia.io/docs/simulcasting-to-social-media-channels#how-to-publish-live-stream-on-youtube

**Comment by TTVSaber3000** [comment]
@yashtandon113 I did add the RTMP end point and made sure all of the ID'S matched up with everything but I am still getting this Broadcasting 1.00x and the same youtube connect streaming software to start preview error.

**Comment by yashtandon113** [comment]
@TTVSaber3000 
Can you please let me know that which version of AMS you are using? I will try in our test environment.

**Comment by Ivl-Nunez** [comment]
I am having the same issue, was there ever any resolution steps for this?

**Comment by yashtandon113** [comment]
Hi @Ivl-Nunez 
Thanks for your comment.
Unfortunately, I was unable to replicate the problem on my end. Could you please provide a step-by-step scenario for reproducing the problem?
Please also ensure that the stream contains audio, or it will not stream to You Tube, and that the RTMP URL contains no blank spaces.

**Comment by Ivl-Nunez** [comment]
Hey there, it seems maybe I didn't have sound? I had tried another video with sound and it had a similar problem, but I made sure of it this time and it's finally working! Thank you so much :)

**Comment by yashtandon113** [comment]
@Ivl-Nunez 
It is good to know that your issue has been resolved.
