### ISSUE TITLE
Upgrade Tomcat to latest version

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#4155]

**Comment by quan612** [comment]
Is there anyway to manually upgrade the tomcat version by the end-user without waiting, and without affecting how Ant works?

Due to the version of Tomcat being flagged as security risk in one of the firewall scan from our client, we have to stop Ant server for almost a week since.

**Comment by SelimEmre** [comment]
Hi @quan612,

Which version are you using(Community or Enterprise)? If you use Community Edition, you just need to switch `update-tomcat-version` branch and run `mvn clean install -Dgpg.skip=true` command in `ant-media-server-parent` project. You need to run `redeploy.sh` script for `StreamApp` and `Ant-Media-Server` projects as well.

If you are an Enterprise Edition user, I can provide you with the Enterprise Edition which is built with `Tomcat 8.5.78` version. Please provide me with your email address. I can share it with you.
Disclaimer: I tested WebRTC Publish&Play scenario, it's working fine. But we are skipping CI/CD processes with this process. Just FYI.

Best Regards,
Selim

**Comment by quan612** [comment]
hi @SelimEmre ,
We are using Ant Media Enterprise version 2.4.1 20211124_1803, that is the version we grabbed within the account we bought the license.

My email is at: quan@transnomis.com

**Comment by SelimEmre** [comment]
Hi @quan612,

I sent it via email. I will push to merge the latest Tomcat version as well. Just FYI. Thanks again.

**Comment by quan612** [comment]
hi @SelimEmre,

May I know the Ubuntu command to check the Tomcat version after upgrade to the new Ant. I tried a few common command to check but I think the tomcat is installed as a module, not a separated module so the normal checking command does not work

**Comment by quan612** [comment]
Hi,
May I know for the package you sent. Is it that I just need to copy the folder over to the installed directory>

Sorry I was not paying attention to the zip file yesterday and thought it is an install package like normal.
    On Monday, April 25, 2022, 12:48:58 PM EDT, Selim Emre Toy ***@***.***> wrote:  
 
 


Hi @quan612,

I sent it via email. I will push to merge the latest Tomcat version as well. Just FYI. Thanks again.

**Comment by quan612** [comment]
can you please help with the installation, i went ahead to overwrite a few files but then server cannot start anymore. Thank you very much.
    On Tuesday, April 26, 2022, 02:05:04 PM EDT, QUAN HUYNH MINH ***@***.***> wrote:  
 
  Hi,
May I know for the package you sent. Is it that I just need to copy the folder over to the installed directory>

Sorry I was not paying attention to the zip file yesterday and thought it is an install package like normal.
    On Monday, April 25, 2022, 12:48:58 PM EDT, Selim Emre Toy ***@***.***> wrote:  
 
 


Hi @quan612,

I sent it via email. I will push to merge the latest Tomcat version as well. Just FYI. Thanks again.

**Comment by SelimEmre** [comment]
Hi @quan612,

You can understand Tomcat version with the beginning of the Ant Media Server logs. You will see Tomcat version as below:
![Screenshot from 2022-04-27 17-44-53](https://user-images.githubusercontent.com/9084130/165545396-5bf25462-94c9-4f4c-b4cf-61d931d58dca.png)

You can also control it with browser as below:
![Screenshot from 2022-04-27 17-48-09](https://user-images.githubusercontent.com/9084130/165546200-ff8b24f2-4417-4f26-837b-29f25ab72782.png)

I can recommend you use latest version of installation file as below:
```
wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && chmod 755 install_ant-media-server.sh
```

After that you can upgrade your server with below:
```
sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE] -r true
```

Best Regards,
Selim

**Comment by quan612** [comment]
Hi @SelimEmre 

I got issue when trying to install / upgrade from the snapshot file you sent me the day before.

Here is what I did:

1. Fresh install of 2.4.1 Enterprise version, ensure everything works on 2.4.1, then run the upgrade command using the snapshot file
sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE] -r true

2. Fresh install of 2.4.4 using the snapshot file you sent
sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE]

both using the latest version of installation file from wget.

I attached the logs

This is on Ubuntu 20.04.3 LTS
[logs_new_install.txt](https://github.com/ant-media/Ant-Media-Server/files/8591475/logs_new_install.txt)
[logs_old_upgrade_to_new.txt](https://github.com/ant-media/Ant-Media-Server/files/8591477/logs_old_upgrade_to_new.txt)

**Comment by SelimEmre** [comment]
Hi @quan612,

I contacted you by email. We can continue by email.

**Comment by quan612** [comment]
Hi,
May I know for the package you sent. Is it that I just need to copy the folder over to the installed directory>

Sorry I was not paying attention to the zip file yesterday and thought it is an install package like normal.
    On Monday, April 25, 2022, 12:48:58 PM EDT, Selim Emre Toy ***@***.***> wrote:  
 
 


Hi @quan612,

I sent it via email. I will push to merge the latest Tomcat version as well. Just FYI. Thanks again.

**Comment by SelimEmre** [comment]
Hi @quan612,

You just need to upgrade to the latest version of Ant Media Server(v2.5.1). We are using Apache Tomcat/8.5.82 version in that version. Please check [this guide](https://resources.antmedia.io/docs/upgrade-ams) for the upgrade process. 

Let me know if there is anything I can help you with. 

Best Regards,
Selim
