### ISSUE TITLE
HFLags is not updated and returned null

### ISSUE THREAD

**Issue by LeDoTruongAn** [ant-media/Ant-Media-Server#4158]
### Short description
I am trying to update hls_flags by using REST API:
`rest/v2/applications/settings/LiveApp`

> {
>  "hlsFlags": "delete_segments"
> }

### Environment

* Operating system and version: Ubuntu 18
* Java version: 

> openjdk version "11.0.14.1" 2022-02-08
> OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04)
> OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

* Ant Media Server version: 2.4.1
* Browser name and version: None

### Steps to reproduce
1. Create a App by using Rest API
2. Update hlsFlags by `rest/v2/applications/settings/{{appname}} `
3. Get settings via Rest API
4. Verify `/usr/local/antmedia/webapps/LiveApp/WEB-INF/red5-web.properties`
### Expected behavior
- hlsFlags value should be returned instead of null
- `settings.hlsFlags` should be presented in red5-web.properties
### Actual behavior
- hlsFlags value is null
- No `settings.hlsFlags` insdie the red5-web.properties
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you so much for this issue @LeDoTruongAn , the way you report is really good.

Moving to the backlog to schedule. 

Thank you again.

**Comment by yashtandon113** [comment]
@LeDoTruongAn 
I was able to reproduce the issue. After the rest API call, the setting is applied on restarting the server.
One of my colleague from development team will work on this issue.

**Comment by LeDoTruongAn** [comment]
@yashtandon113 Thank you so much. It would be great to have this fix by next release.

**Comment by mekya** [comment]
This issue has been fixed in another PR(I'm not sorry it's not referenced) and it's available in the recent versions so closing this issue. 

Please let me know if it's not working for you @LeDoTruongAn
