### ISSUE TITLE
Huge Amount of Traffic Usage While using Playlist 24/7

### ISSUE THREAD

**Issue by LeDoTruongAn** [ant-media/Ant-Media-Server#4169]
I've started using Ant Media for our product since last month. We are using Cachefly and Deft (their S3) as CDN Server and has been reported a bill today for 2,528,848.5 GB worth of extra bandwidth usage ( in 10 days)

I am not sure how should i ask for explanation but i would like to get help from you guys about my situation.

**Comment by mekya** [comment]
Thank you for the issue @LeDoTruongAn. I'm just moving it to the backlog to assign one of my colleague. So that he will give you a clear response.

**Comment by LeDoTruongAn** [comment]
@mekya Thank you so much. I think it should due to the way ffmpeg read the video/audio file while running in the background for playlist purpose.... It should be my configuration to use cdn url instead of direct object url from s3.

**Comment by Mohit-3196** [comment]
Hi @LeDoTruongAn ,
Thank you for the update and writing back. Really appreciate it.
Please let us know if you face any issues.

Thank you
