### ISSUE TITLE
No scroll bar in Playlist UI

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4197]
### Short description
There is no scroll bar to go down and save while adding more playlist items. 

### Environment
* Ant Media Server version: 2.4.3 & above

### Steps to reproduce
1. Create the playlist initially with 7-8 playlist items.
2. Go and try to add more playlist items in the same playlist.

### Expected behavior
There should be scroll bar to move down and add more items.

### Actual behavior
There is no scroll bar.

**Comment by mekya** [comment]
Closing this issue because it's duplicated
