### ISSUE TITLE
SRT ingest on Ant Media Server Enterprise for ARM?

### ISSUE THREAD

**Issue by NickMoores** [ant-media/Ant-Media-Server#4198]
Is SRT ingest enabled on the "Ant Media Server Enterprise for ARM" AMI located here?: https://aws.amazon.com/marketplace/pp/prodview-s72grshttriy4

I created an EC2 instance based on the ARM version of Ant Media Server Enterprise, but I haven't been able to establish a connection to port 4200 from FFMPEG, like I can with the non-ARM version.

I've verified I'm using v4.2.3, and tried swapping the EC2 security group back and forth between an ARM instance and a non-ARM instance to ensure my network ACLs were configured correctly.

**Comment by yashtandon113** [comment]
@NickMoores 
Thanks for creating the issue. 
SRT support is available in X86_64 architectures for now. It’s not currently available in ARM and will be added in the next release.

**Comment by NickMoores** [comment]
@yashtandon113 Thank you. Will keep an eye out.
