### ISSUE TITLE
Documentation about VoD Streaming via WebRTC/HLS

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4216]
VoD files can be streamed as Stream Source. Let's write the documentation for that.

**Comment by muratugureminoglu** [comment]
https://portal.document360.io/033a096a-b182-4b05-8c1b-425e70959431/document/v1/view/442bb2a3-ba88-41d7-8f99-a4170ab47cac

**Comment by yashtandon113** [comment]
Published --> https://resources.antmedia.io/docs/vod-streaming-via-webrtchls
