### ISSUE TITLE
Error in first enter to application when activated JWT app filter

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4217]
### Short description
If you activate JWT, it gives an error on the first login.

### Environment

* Operating system and version: Ubuntu 20.04
* Java version: 11
* Ant Media Server version: 2.4.3
* Browser name and version: Firefox/Chrome

### Steps to reproduce
1. Login to Dashboard.
2. Click the APP(LiveApp/WebRTCAppEE) where you have activated the JWT.
3. You will encounter an error.
![Screenshot at 2022-05-24 15-35-25](https://user-images.githubusercontent.com/6337605/170040672-9dc20ac6-248a-46c8-9038-0c6e8486cc20.png)

**Comment by muratugureminoglu** [comment]
Sorry for that Mr. @mekya 

" Enable JWT Filter for RESTful API "
![Screenshot at 2022-05-24 16-26-29](https://user-images.githubusercontent.com/6337605/170046340-aa3d33cb-7efc-4b04-8369-5416edcf1c12.png)

**Comment by lastpeony** [comment]
this was caused because initial http requests were sent before jwt of application was retrieved from server thus authorization header of those initial requests were null.
fixed with https://github.com/ant-media/Ant-Media-Management-Console/pull/213
we can close after a simple review.

**Comment by mekya** [comment]
Thank you @lastpeony for your development.
