### ISSUE TITLE
metaData of Stream is not updated

### ISSUE THREAD

**Issue by LeDoTruongAn** [ant-media/Ant-Media-Server#4218]
### Short description
I am having issue when updating the metaData of stream with playlist type.

### Environment

* Operating system and version: Ubuntu 20.
* Java version: 
> openjdk version "11.0.15" 2022-04-19
> OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1, mixed mode, sharing)

* Ant Media Server version: 2.4.3 Enterprise
* Browser name and version: Postman

### Steps to reproduce
1. Using Rest API to update the metaData for broadcast object with following payload

> {
>     "metaData": "duration:315360000000"
> }
3. Using Rest API to get broadcast object to check and receive following result

> {
>  .....
>  "metaData": "",
>  ......
> }

### Expected behavior
* the metaData is updated and returned via Rest API

### Actual behavior
* Rest API is return blank one.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you for the issue. I've moved to the backlog to schedule

**Comment by FarhodKurbonov** [comment]
I guess this issue can be  closed. REST successfully  returns metaData

**Comment by mekya** [comment]
Thank you @FarhodKurbonov,

Yes, you're right. I'm closing the issue.
