### ISSUE TITLE
Support external video frames and create some sample with Deep AR.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4223]
Supporting external video frames and create some samples with Deep AR for native SDKs.

**Comment by adepane** [comment]
any progress of this issue?

**Comment by mekya** [comment]
Thank you for follow up @adepane . I've moved to the backlog. 

Backlog is full so we have not scheduled it yet.

**Comment by burak-58** [comment]
External frame feed feature is implemented for both Android and iOS. We also have samples for external frame feed. So I am closing this issue.
