### ISSUE TITLE
vod issue

### ISSUE THREAD

**Issue by roteckk** [ant-media/Ant-Media-Server#424]
Hello. I have installed Ant Media Server Community 1.5.0 on both Ubuntu 16 and 18 and when i upload a vod file it automatically renames it into a file like 839497578934798.mp4.
I need to go to server and rename the file manually to the original name of the file. After that embedded code is working. Anyone else have the same problem?

Also the play button of the vod file is not working. When you press it, nothing happens.

Thank you.

**Comment by davutcavdar** [comment]
Hi @roteckk ,
Ant Media Server automatically saves uploaded VoD with unique VoD Id as a name.

Play issue is resolved in v1.5.1 and it will be released in a week. Sorry about that.

**Comment by roteckk** [comment]
v1.5.1 resolved play issue but it didn't for the embedded code.

When you copy the live embedded code from vod in clipboard, it has the original name of the file in it, and not the unique VoD ID as the file was already renamed on the server.

**Comment by davutcavdar** [comment]
@roteckk @hoos the original name of the VoD is used for stream VoD, unique VoD id is used for uploaded VoD.  We are analyzing and trying to fix this issue and will update you.

**Comment by hoos** [comment]
I should add the broken embedded code links that I'm seeing are from the LiveApp VoD page.
