### ISSUE TITLE
Cluster dosen't start when passing username and password with -u and -p flags

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4242]
### Short description
When using mongodb+srv URI to start AMS in cluster mode with ./start.sh by passing -u username and -p password filed, the cluster doesn't start and gives Bootstrap exception. 

### Environment

* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Create an Atlas database with mongodb+srv URI
2. Run the ./start.sh script with sudo ./start.sh -m cluster -h mongodb+srv://<URL> -u username -p password

### Expected behavior
Server should start in cluster mode.

### Actual behavior
Server gives Bootstrap exception and doesn't start in cluster mode.

**Comment by muratugureminoglu** [comment]
Hi @Mohit-3196 When I test it, it works properly when I use mongodb+srv://<username>:<password>@<url> cluster URL like this. This is how the cluster URL should be used in MongoDB Atlas.

```
sudo ./change_server_mode.sh cluster mongodb+srv://<username>:<password>@<url>
```
Reference URL: https://resources.antmedia.io/docs/using-mongodb-atlas-with-mongodbsrv-uri
