### ISSUE TITLE
Starting docker container on ARM server crashes

### ISSUE THREAD

**Issue by samfry13** [ant-media/Ant-Media-Server#4249]
### Short description
After building and starting the docker container on an ARM server, I get a Java instantiation error, and the program exits

### Environment

* Operating system and version: Ubuntu 20.04 aarch64
* Java version: N/A
* Ant Media Server version: Enterprise 2.4.3
* Browser name and version: N/A

### Steps to reproduce
1. Build docker container on specified OS
2. Attempt to run container using `docker run -d --name antmedia --network=host -it antmediaserver`

### Expected behavior
The server starts without crashing

### Actual behavior
The server spits out Java instantiation error and docker container exits.
 

### Logs
Logs can be found [here](https://pastebin.com/sS2eJuFT)

**Comment by mekya** [comment]
I think I know this problem. We can provide a quick workaround solution for that and permanent solution is already in its way. 

Thank you @samfry13

**Comment by samfry13** [comment]
> I think I know this problem. We can provide a quick workaround solution for that and permanent solution is already in its way.

Awesome, great news. What is the workaround in the meantime?

**Comment by mekya** [comment]
Thank you for follow up. 

Can you just disable the SRT bean in the `/usr/local/antmedia/conf/red5-common.xml` and start again?

- Just open the file `/usr/local/antmedia/conf/red5-common.xml`
- Comment out the srtAdaptor as follows 
```xml
<!--   	
 <bean id="srtAdaptor" class="#{ T(io.antmedia.rest.RestServiceBase).isEnterprise() ? 'io.antmedia.enterprise.srt.SRTAdaptor' : 'io.antmedia.srt.SRTAdaptor' }"></bean>
-->
```
- Save the file 
- Rebuild image if it is necessary
- Start the container 

If it does not work, please let me have the logs (/usr/local/antmedia/log/ant-media-server.log and /usr/local/antmedia/log/antmedia-error.log)

>Logs can be found [here](https://pastebin.com/sS2eJuFT)
I cannot reach the logs. I think it's expired.

**Comment by samfry13** [comment]
Sorry for the late response. When commenting out that adapter, then rezipping up the folder, then trying to build the container again, the build process fails, and [these](https://pastebin.com/yb6edcyS) are the logs I get.

**Comment by mekya** [comment]
Thank you for letting us know

**Comment by mekya** [comment]
Hi @samfry13 ,

Let me update you. 

SRT ARM64 support is added in this issue(#4210) and it should work without changing the bean in the `/usr/local/antmedia/conf/red5-common.xml`
You can download the latest snapshot(Ant Media Server Latest Snapshot(Unstable)) under your subscriptions at antmedia.io

If you use AMS in some marketplaces and you want to test the latest snapshot, I can share the latest snapshot via email. Just send me an email(mekya at antmedia dot io) about that 

FYI
