### ISSUE TITLE
Ubuntu 22.04 LTS (Jammy) support (libcrystalhd-dev not available)

### ISSUE THREAD

**Issue by Quppa** [ant-media/Ant-Media-Server#4251]
**Is your feature request related to a problem? Please describe.**
Ant Media Server can't be installed on Ubuntu 22.04 due to package `libcrystalhd-dev` [being unavailable](https://packages.ubuntu.com/search?keywords=libcrystalhd-dev).

```
Package libcrystalhd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Describe the solution you'd like**
The ability to install Ant Media Server on Ubuntu 22.04.

**Describe alternatives you've considered**
Downgrading to Ubuntu 21.10 (support ends in July 2022) or 20.04 (standard support continues until April 2025).

**Additional context**
N/A

**Comment by muratugureminoglu** [comment]
Hi @Quppa 

You can install the `libcrystalhd-dev` package on Ubuntu 22.04 using the Ubuntu community repository. I'm dropping the steps below.

**1.** `echo "deb http://ftp.ubuntu.com/ubuntu   focal universe" >> /etc/apt/sources.list`
**2.** `apt-get update`
**3.** Then try to install the Ant Media Server
`sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_INSTALLATION_FILE]`

We do not support Ubuntu 22.04 officially, so don't forget to edit the install script.

**1.**  Open `install_ant-media-server.sh` with editor and go to line 140
**2.** Add Ubuntu 22.04 as follows
`if [ "$VERSION_ID" != "22.04" ] && [ "$VERSION_ID" != "20.04" ] && [ "$VERSION_ID" != "22.04" ]`
**3.** Save then run the install script again.

Regards.

**Comment by mekya** [comment]
It's time to update the installation script @muratugureminoglu

**Comment by mekya** [comment]
It's supported and automation is added for 22.04. 

Thank you for raising this issue @Quppa 

I'm closing this issue now. Please let us know if you have any questions or feedbacks

**Comment by kboek** [comment]
Trying to install 2.9.0 EE on Ubuntu 24.04 LTS and getting the same error (libcrystalhd-dev not available). According to [the documentation](https://antmedia.io/docs/guides/installing-on-linux/installing-ams-on-linux/), installing on 24.04 is supported.

**Comment by muratugureminoglu** [comment]
Hi @kboek 

Ant Media Server does not need the **libcrystalhd-dev** package after version 2.6[1]. This problem usually occurs if you are using an outdated install script. 

[1] https://github.com/ant-media/Scripts/blob/update-dockerfile-for-mediapush/install_ant-media-server.sh#L321-L330

You can update the installation script as follows.
```
bash install_ant-media-server.sh -u
```

If you are having the same issue still, please run the installation script as follows then share the output of this process.
```
bash -x ./install_ant-media-server.sh -i your_ams.zip
```
Regards.

**Comment by kboek** [comment]
@muratugureminoglu, must be something in your script then, or in the ant-media-server.jar, because I did use [the script from your GitHub](https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh) to install, and also the error happens with 2.9.0 but not with 2.8.1

**Comment by muratugureminoglu** [comment]
@kboek 

I need to see the debug output of your installation process.  

Let give some information. If you check the following link, you can see how many times tested in Ubuntu 24.04 . If there had been such an issue, it would not have been passed by the CI. Please check the zip file and install script on your side. 

https://github.com/ant-media/Scripts/actions/workflows/install-latest-to-ubuntu-24-04.yml
