### ISSUE TITLE
can you please create Docker for arm machines

### ISSUE THREAD

**Issue by rahul1996pp** [ant-media/Ant-Media-Server#4254]
### Short description
can you please create Docker for arm machines

### Environment

* Operating system and version: ubuntu

**Comment by mekya** [comment]
Thank you @rahul1996pp for the issue. 

I think the current docker file should work in ARM machines as well. 
https://github.com/ant-media/Scripts/blob/master/docker/Dockerfile_Process

Maybe, your problem is about in this issue
https://github.com/ant-media/Ant-Media-Server/issues/4249

**Comment by mekya** [comment]
Hi @rahul1996pp ,

SRT ARM64 support is added in this issue(https://github.com/ant-media/Ant-Media-Server/issues/4210)
You can download the latest snapshot(Ant Media Server Latest Snapshot(Unstable)) under your subscriptions at antmedia.io

If you use AMS in some marketplaces and you want to test the latest snapshot, I can share the latest snapshot via email. Just send me an email(mekya at antmedia dot io) about that.


If you still help with this issue, please let me know. 

Regards,
A. Oguz
