### ISSUE TITLE
Setting auto scaling on AWS with a license on dedicated servers and scaling on marketplace image

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#4256]
Autoscaling does not raise new ec2 instances since it does not know anything about the two manually launched.
Let me describe the algorithm of my actions:
With the help of cloud formation, I raised the basic infrastructure for AMS - ALB + auto scaling (min 1, max 1) + 2 target groups for origin and edge. As a result, the request goes to ALB, depending on the parameter (query target can be origin or edge), it redirects to the corresponding origin or edge group.
I manually launch two ec2 based on a manually created image (ams and the necessary configs are already installed on it and the license key is registered).
And I switch them to cluster mode by specifying the private ip of the running mongoDB.
I add these two ec2s to ALB - in fact, I add one to target group origin, and the second to target group edge and I go to the admin panel (ant media) to check and I displayed 4 servers in the cluster tab
Changed configs in auto scaling (min 0). Stopped 2 out of 4 servers (the two that were automatically started). And I conducted load testing - I brought the CPU load to 90-100 % and the new servers did not start.

**Comment by muratugureminoglu** [comment]
Hi, 

Let me explain how to do it.

There is 1 licensed Ant Media Server in this structure, and it triggers the marketplace instances in autoscale, provided that the same load balancer is used under load. 

**1.** In the Cloudwatch service, 2 alarms must be added for scale-up and then scale-down.

**a.**  Scale-Up

`Select Metric > Ec2 > Per-Instance Metrics > Choose Your Static Server > CPUUtilization` and then set Condition as `"Static > Greater > 50" After that set Additional Configuration to  "1 out of 3".` and Create an alarm without any data in Configure Action.

**b.**  Scale-Down

`Select Metric > Ec2 > Per-Instance Metrics > Choose Your Static Server  > CPUUtilization and set "Static > Lower > 50"` as Condition and then  Additional Configuration  should be `"1 out of 3"` again. Create an alarm without any data in Configure Action.

**2.** Select the` AutoScale group` and create 2 Dynamic scaling Policies from the Auto Scaling menu, one will be scale-up and the other for scale-down. Create and set settings as in the images below.

Configuration for Scale-Up:
![scale-up](https://user-images.githubusercontent.com/6337605/180663033-233b5e63-67a3-4fa8-9ab4-631ce98fbfdd.png)

Configuration for Scale-Down:
![scale-down](https://user-images.githubusercontent.com/6337605/180663290-19369c1e-fa57-4895-85ff-369030f80de5.png)

**3.** Finally, let's make the load balancer settings. Select `Load Balancing > Target Groups > Your Target Group > Register your static server.`

Now you can use your static server and your server in autoscale from a single load balancer.

If you have any questions, please just drop a message.

**Comment by muratugureminoglu** [comment]
Hi, 

Let me explain how to do it.

There is 1 licensed Ant Media Server in this structure, and it triggers the marketplace instances in autoscale, provided that the same load balancer is used under load. 

**1.** In the Cloudwatch service, 2 alarms must be added for scale-up and then scale-down.

**a.**  Scale-Up

`Select Metric > Ec2 > Per-Instance Metrics > Choose Your Static Server > CPUUtilization` and then set Condition as `"Static > Greater > 50" After that set Additional Configuration to  "1 out of 3".` and Create an alarm without any data in Configure Action.

**b.**  Scale-Down

`Select Metric > Ec2 > Per-Instance Metrics > Choose Your Static Server  > CPUUtilization and set "Static > Lower > 50"` as Condition and then  Additional Configuration  should be `"1 out of 3"` again. Create an alarm without any data in Configure Action.

**2.** Select the` AutoScale group` and create 2 Dynamic scaling Policies from the Auto Scaling menu, one will be scale-up and the other for scale-down(Cloudwatch Alerts are added to the policies you have created.). Create and set settings as in the images below.

Configuration for Scale-Up Policy:
![scale-up](https://user-images.githubusercontent.com/6337605/180663640-7e56ef54-ee5b-46d4-b26e-03cf8290a62a.png)

Configuration for Scale-Down Policy:
![scale-down](https://user-images.githubusercontent.com/6337605/180663653-53924a8e-1d27-4d5b-8fbe-bbad101eb865.png)

**3.** Finally, let's make the load balancer settings. Select `Load Balancing > Target Groups > Your Target Group > Register your static server.`

Now you can use your static server and your server in autoscale from a single load balancer.

If you have any questions, please just drop a message.
