### ISSUE TITLE
Get Recording Status

### ISSUE THREAD

**Issue by JCFontoura** [ant-media/Ant-Media-Server#4261]
Is there an endpoint to check if the stream is with a started recording?
I need to know if the recording is stopped before setting it to on with PUT /v2/broadcasts/{id}/recording/{recording-status}

**Comment by yashtandon113** [comment]
@JCFontoura 
Thanks for your question.
You can check the recording status of individual stream through [Get broadcast object](https://antmedia.io/rest/#/BroadcastRestService/getBroadcast) rest API before enabling/disabling it.
