### ISSUE TITLE
Self-camera switching

### ISSUE THREAD

**Issue by wonjangcloud9** [ant-media/Ant-Media-Server#4267]
**Is your feature request related to a problem? Please describe.**

Self-camera switching in webRTC between mobile and mobile does not apply as a traditional function.

**Describe the solution you'd like**

The camera must be able to change back and forth between the mobile and the WebRTC call.

**Describe alternatives you've considered**

Function added to existing available webrtc_adaptor.js.

  async switchCameras(streamId, camera) {
      this.localStream.getVideoTracks().forEach(function (track) {
          track.stop();
      });
      const resolution = {
          facingMode: camera,
      }
      const mediaConstraints = {
          video: resolution,
          audio: true,
      };
      const stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
      this.updateVideoTrack(stream, streamId, this.mediaConstraints, onended, null);
  }

**Additional context**

I've been lost for a week in relation to the above case. I hope it helps someone who needs to change the screen while making a webRTC call.

**Comment by mekya** [comment]
Thank you @wonjangcloud9 for your contribution. 

There is another method(switchVideoCameraCapture) that can be used with `available_devices` callback to switch the cameras 

```
webRTCAdaptor.switchVideoCameraCapture(streamId, deviceId);
```

You can see how it's used in this sample -> https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/index.html

**Comment by wonjangcloud9** [comment]
I thought of the self-camera switching mode provided by the basic camera application in an environment where both are smartphones.

You might misunderstand because it's always video: {facingMode: "user"} on the desktop.

What I thought of was a transition between video: {facingMode: "environment"} and video: {facingMode: "user"}.

Next time, I'll try to write more clearly.

Thank you for your answer and I hope you are always happy.

**Comment by mekya** [comment]
I see the point. I think we can add this method to the SDK as well. 

Thank you for your contribution @wonjangcloud9

**Comment by wonjangcloud9** [comment]
I love u!!!!

**Comment by wonjangcloud9** [comment]
I sent the email you told me.

Thank you for making my day special.

I wish you all the best!

**Comment by mekya** [comment]
Thank you. I've received and we'll send you the starbucks gift card shortly.  

Wish you the best.

**Comment by dnish** [comment]
@mekya Is there some additional function we need to call? If I do the switch on Safari, the stream is stopped on the receiver side and doesn't start again even if I reload the page.

**Comment by dnish** [comment]
And when importing the latest version I only get TypeError: Logger is not a constructor (evaluating 'new WebRTCAdaptor(obj)')
