### ISSUE TITLE
How to know the clustering actually works

### ISSUE THREAD

**Issue by andriisapizhak-intent** [ant-media/Ant-Media-Server#427]
Hi!

We are using AntMedia Enterprise 1.4 on AWS and have set up static clustering using EC2 for testing purposes. Two instances are up and running but the question is:

Is there any way to get to know the clustering actually works?

I've checked /usr/local/antmedia/logs , AntMedia dashboard at port 5080 and haven't found any clue. Maybe some instances list that can be seen somewhere so I can actually see that my config works, or some line in the logs that e.g. "3 static instances with adresses a,b,c added in cluster and 2 of them are up and 3rd inaccessible", or anything else how can I check the clustering actually works? Any help is appreciated, thanks!

**Comment by andriisapizhak-intent** [comment]
After hours of looking into logs, code, google and ssh, I found nothing, so had to think something out. As a result, I found out that clustering didn't work and there was no information about it. Nowhere. The problem was in closed port 5000 which is recommended to open for UDP but static clustering actually uses it for TCP. Had to stare into config to think about it. And again, three log files and no one complained. Maybe please at least add warning or severe lines when instance cannot reach other instances?
The solution for me to try if it works was when I got stream url from one server, I pasted that url in the browser and then changed server IP to another from the cluster - and when I realised that the problem may be in closed tcp port and opened it - it worked. Before that, the other server just gave me 404.

I believe this process definitely has to be improved as I spent several hours just to see if it works or not and there's no documentation, notifications or even log entries that configured cluster nodes are unreachable.

**Comment by SelimEmre** [comment]
Hi @andriisapizhak-intent,
Thank you for your interest. Sorry for the delay. Did you install AMS by yourself on EC2 or create EC2 with our AMI?
If you have any question, please feel free to ask us. 

Best Regards,
Selim
