### ISSUE TITLE
WHIP (WebRTC HTTP Ingest Protocol)

### ISSUE THREAD

**Issue by samidalati** [ant-media/Ant-Media-Server#4307]
**Is your feature request related to a problem? Please describe.**
we keep experiencing network issues when attempting to stream using RTMP from Australia to Ant media server in North America. 

**Describe the solution you'd like**
The ability to ingest RTSP over HTTP directly using Gstreamer or similar  

**Additional context**
similar to Millicast https://docs.millicast.com/docs/using-gstreamer-with-millicast

**Comment by mekya** [comment]
Thank you for feedback @BCordleRossVideo . It's in the backlog

You can also send stream to Ant Media Server with websocket by WebRTC or pushing with SRT. What makes you prevent using  these ways?

**Comment by USAMAWIZARD** [comment]
Request : 92929 Publishers: 100 Players: 100
