### ISSUE TITLE
How many User Per Session?

### ISSUE THREAD

**Issue by zionnite** [ant-media/Ant-Media-Server#4308]
just come across this package, please how many user does ant media allows per session?

**Comment by yashtandon113** [comment]
@zionnite 
Thanks for your question.
On the server side, there is no limit on the quantity of streams/sessions or viewers. It depends on your server's specifications.
You can contact us at contact@antmedia.io to discuss this in more detail.

**Comment by zionnite** [comment]
Am interested...

**Comment by yashtandon113** [comment]
@zionnite 
Sure, you can directly email to contact@antmedia.io to discuss your requirements.

**Comment by yashtandon113** [comment]
Closing this issue. Please feel free to open if you have any questions.
