### ISSUE TITLE
Progress bar while uploading VOD on the server

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4313]
**Is your feature request related to a problem? Please describe.**
When we try to upload heavy mp4 file like 500Mb or more, it says it's saving but doesn't upload and in the end it gets failed.

**Describe the solution you'd like**
GUI should have a progress bar so that we can check the status and stop the upload if it is taking too long.

**Comment by Mohit-3196** [comment]
Also it would be nice to include the VOD id in the stop/start recording REST API call as many users have been asking for this and another REST API to download the VOD file.

**Comment by mustafaboleken** [comment]
Hi @asharamseervi

We merged the adding progress bar to upload VOD. You can test it on the latest snapshot version soon. Also, we get some actions on our side to review and merge tasks more quickly fyi
