### ISSUE TITLE
Merge master to M85 update for the Android SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4314]
Android SDK is crashing when repeatedly attempt to start/stop streams(meaning start/stop streams more than once within a short window). For reference issue --> https://github.com/ant-media/Ant-Media-Server/issues/2298

**Comment by doggomir** [comment]
We tested the latest merge and couldn't get the screen capturer example running. I added the error message to this ticket: https://github.com/ant-media/Ant-Media-Server/issues/4266

**Comment by mekya** [comment]
Thank you @doggomir
