### ISSUE TITLE
Investigate the case that server is not responding 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4316]
Logs are being collected and we just need to spend time to understand/reproduce it.
BG
NB
DA

**Comment by yashtandon113** [comment]
HLS stream is playing fine on the origin server but giving 404 error on edge server while WebRTC playback is fine. Logs are attached below.
[origin.zip](https://github.com/ant-media/Ant-Media-Server/files/9302879/origin.zip)
[edge.zip](https://github.com/ant-media/Ant-Media-Server/files/9302881/edge.zip)
