### ISSUE TITLE
Finish WebRTC screenshare extension and publish it

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#432]

**Comment by ogulcan** [comment]
@mekya, Share extension checkbox is not available on the page. Version: 1.5.1

Btw, I followed up the instructions on the blog post. 

![Screen Shot 2018-10-16 at 18.28.02.png](https://images.zenhubusercontent.com/5b1585ca76f98d262074628d/3a2ae9c6-0560-4425-ad0c-5c58f9b52631)
