### ISSUE TITLE
"Not saving the settings" warning in logs after deployed cluster on AWS using marketplace image.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4328]
### Short description
When saving any settings in cluster on AWS, below mentioned warning is generating in logs.

2022-08-04 10:44:19,210 [vert.x-eventloop-thread-0] WARN  i.a.AntMediaApplicationAdapter - Not saving the settings because current appsettings update time(1659609854236) is later than incoming settings update time(1659609854236)  

### Environment

* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Deploy cluster using CloudFormation template.
2. Try to change any application setting and save.
3. Check the above mentioned error in logs.

### Expected behavior
There should be no warning logs while saving the settings.

### Actual behavior
Settings are getting saved but only warning is repeating in logs.

**Comment by SelimEmre** [comment]
I have checked this issue. It's not the real issue. On the backend side, if MongoDB is updated somehow, it will ping all nodes to update. It will ping the same node. So it will skip like console log. But I changed it to console log severity. I guess it should debug type.
