### ISSUE TITLE
Ant Server Community Version not installing

### ISSUE THREAD

**Issue by chiragnahata** [ant-media/Ant-Media-Server#4357]
I installed Ant Media Community Server on my server and cannot access the admin panel. I am getting the following error. Please help me as soon as possible.

Server : antmedia.chiragnahata.ml
 
![image](https://user-images.githubusercontent.com/63905783/185604291-53a251d1-9e97-487e-a7a5-dce788e477c8.png)

**Comment by yashtandon113** [comment]
Hi @chiragnahata 
Could you please let us know which Ant media server version you have installed? Also, please make sure that required [server ports](https://resources.antmedia.io/docs/installation#server-ports) are whitelisted on your firewall.

**Comment by chiragnahata** [comment]
> Hi @chiragnahata Could you please let us know which Ant media server version you have installed? Also, please make sure that required [server ports](https://resources.antmedia.io/docs/installation#server-ports) are whitelisted on your firewall.

Version : Ant Media Server Community 2.4.3
Yes added all the ports to the firewall

I tried the docker compose also. Not happening

**Comment by arnowelzel** [comment]
Maybe this is a similar problem as I experienced in #4360 - when Ant Media is behind a proxy it may deny access to the dashboard.

**Comment by yashtandon113** [comment]
@arnowelzel 
Thank you for your comment.

@chiragnahata 
I would like to know if your problem has been resolved. If not, we can check this together by scheduling a meeting. You can contact me directly at yash.tandon@antmedia.io.

**Comment by muratugureminoglu** [comment]
@arnowelzel It's not about #4360 . This 403 page is not served by Ant Media Server. So there is an external device. It could be Firewall, Proxy etc.

**Comment by chiragnahata** [comment]
> @arnowelzel 
> Thank you for your comment.
> 
> @chiragnahata 
> I would like to know if your problem has been resolved. If not, we can check this together by scheduling a meeting. You can contact me directly at yash.tandon@antmedia.io.

Not resolved

**Comment by mekya** [comment]
@yashtandon113 , could you please help @chiragnahata resolve the issue?

**Comment by yashtandon113** [comment]
@mekya 
I'm following up with @chiragnahata via email and trying to set up a meeting.

**Comment by chiragnahata** [comment]
> @mekya 
> I'm following up with @chiragnahata via email and trying to set up a meeting.

Can we please schedule a meeting on 30th September 2022 at 4 pm IST ?

**Comment by yashtandon113** [comment]
@chiragnahata 
I've scheduled the meeting, and an invitation link has been sent to your email address.
See you on the 30th.

**Comment by yashtandon113** [comment]
@chiragnahata 
Thanks for joining the call today. I am closing this issue now as your problem is resolved.

**Issue Description:-**
Because Ant media server does not officially support Ubuntu 22.04 and 22.10, we used the workaround solution suggested by @muratugureminoglu on the below-mentioned Git Hub issue.
https://github.com/ant-media/Ant-Media-Server/issues/4251
