### ISSUE TITLE
Android device streaming using WebRTC-Android-SDK

### ISSUE THREAD

**Issue by bikee1235** [ant-media/Ant-Media-Server#4365]
Hi 
We are using Ant Media server for streaming 

using [WebRTC-Android-SDK](https://github.com/ant-media/WebRTC-Android-SDK) we are able to stream front and back camera of device but not able to stream hole device screen can you please help me in streaming device page

he have ant-media server setup

**Comment by mustafaboleken** [comment]
Hi @bikee1235, we fixed the bug about screen share not working on Android(11,12). Could you please try it with the latest snapshot?

**Comment by mustafaboleken** [comment]
This issue solved on pull request 
https://github.com/ant-media/WebRTC-Android-SDK/pull/1

Because of that we didn't receive feedback. We are closing this issue right now.
