### ISSUE TITLE
Youtube Receives Software Video And Audio But Doesn't Play It On Stream. Stream Video Does Not Load. But When The Live Stream Is Published As A Video, You Can Hear The Audio And See The Video Fine

### ISSUE THREAD

**Issue by githubissocool** [ant-media/Ant-Media-Server#4375]

**Comment by Mohit-3196** [comment]
Hi @githubissocool ,
How are you?

Thank you for the issue.

You can refer to [this guide](https://resources.antmedia.io/docs/simulcasting-to-social-media-channels#how-to-publish-live-stream-on-youtube) on how to stream to YouTube.

If it still doesn't work, please share your Ant Media Server Web Panel login with me on support@antmedia.io and I can check it and we'll make it to work.

Thank you

**Comment by Mohit-3196** [comment]
Hi @githubissocool ,
Let me know if you still face the issue.

BTW as per the YouTube policy, it doesn't accept the incoming stream if audio is not there. So when pushing a stream to YouTube RTMP endpoint please make sure that it has audio as well.

Thank you again

**Comment by mekya** [comment]
I'm closing this issue because it's already addressed. Please feel free to re-open if you would like to discuss further.
