### ISSUE TITLE
iOS SDK  Screen capture is pixelating when screen changes

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4382]
Being [discussed here](https://github.com/ant-media/Ant-Media-Server/issues/4278)

### Steps to reproduce
1.  Run iOS Sample Project and Choose to Publish the screen
2. Play the stream on Ant Media Server with WebRTC
3. Swipe left-right in the screen  

### Expected behavior
There should be smooth video play

### Actual behavior
Pixelating the video. Check the recorded video here 

https://user-images.githubusercontent.com/3456251/187892806-19fbfea0-d7fa-4898-9bd2-9f8ab8c19f05.mp4

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by shibupanda** [comment]
Hi @mekya 
it's (screen shaking ) a critical bug for us. If possible please prioritise it

**Comment by mekya** [comment]
Hi @shibupanda ,

We'll do our best. I think the best scenario we can work for this issue next week.

**Comment by shibupanda** [comment]
Hi @mekya 
Any update on this?

**Comment by mekya** [comment]
Unfortunately, there is no update yet. There is too much demand to the product and we're overloaded. Btw, we're also trying to find someone in the community or partners to make this development for you.

**Comment by mekya** [comment]
Hi @shibupanda ,

I've just merged a PR to address this issue. Here is the sample videos before and after the fix. 

 Before the fix, I'm having these pixelating problems. 

https://user-images.githubusercontent.com/3456251/194822902-5b72fda7-6bec-4f41-8bfa-d309e2f81594.mp4

After the fix, I don't have pixelating in the video. 


https://user-images.githubusercontent.com/3456251/194823062-136c1a6f-08ad-40e6-baa3-8052c3f7156d.mp4


Could you please try and let me know if it works for you?

Regards,
A. Oguz

**Comment by shibupanda** [comment]
Sure @mekya

**Comment by shibupanda** [comment]
@mekya it is working now.
It is in UAT phase will raise if will get any new challenges.

**Comment by rjtoledo** [comment]
hi @mekya  we have a similar issue but only when changing to a different resolution using adaptive bitrate how could we fix it?
