### ISSUE TITLE
Installation problem in ubuntu 21.04 and 21.10

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4383]
Heikki:

I tried to use versions Ubuntu 21.04, Ubuntu 21.10 as written in your installation script(https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh), but they did not install out of the box on OVHcloud - some of the dependencies could not be installed. Ended up installing 3 times, and the last one was 20.04 that then worked. You should check it out, and if it is not possible anymore, then remove the support of those in the script. Thanks!

**Comment by muratugureminoglu** [comment]
Hi @mekya 

Unfortunately, Ubuntu 21.04 and 21.10 versions are EOL and the package cannot be installed because the repos are not available. I m going to update the installation script for that. 

https://ubuntu.com/about/release-cycle

**Comment by walt93** [comment]
Hello! Running into the same issue, on OVHCloud also, and all of the Ubuntu prior to 22.04.1 LTS are flagging as repos unavailable, and there is some issue with the install script.

Any ETA on this?

**Comment by muratugureminoglu** [comment]
@walt93 

Let me clarify that. The problem you are facing is related to the repos, not the install script. The install script only uses repos. We also officially support 20.04 and there is no problem in 20.04. We've already removed support for non-TLS versions because of EOL.
