### ISSUE TITLE
Monitor Ant Media Server

### ISSUE THREAD

**Issue by annibal1** [ant-media/Ant-Media-Server#4394]
https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Monitor-Ant-Media-Servers

I followed this guide and it is very comprehensive
I managed to get what I wanted except if it was possible to see the ip addresses of the people who are connected to the stream
is it possible with some configuration ??
Great job and congratulations for all the work done

**Comment by muratugureminoglu** [comment]
@annibal1 Thanks for that. Let me create an issue for your request.

**Comment by annibal1** [comment]
Thanks for your interest
I await news thanks again

**Comment by muratugureminoglu** [comment]
Hi @annibal1 

I created it as a feature request. We will evaluate it together with the team.

https://github.com/ant-media/Ant-Media-Server/issues/4431

Thanks.

**Comment by ddudx** [comment]
Hi, @muratugureminoglu what's the difference with this feature before?  #2553 anyway I'm interested in this feature.

**Comment by muratugureminoglu** [comment]
Hi @ddudx Here we will send Server and Client IP addresses to Kafka then we will be able to monitor/parse easly.

**Comment by annibal1** [comment]
sorry I read
But I don't understand how to carry out the tests
from ssh ?? Or from Grafana ??
the commands ??

**Comment by muratugureminoglu** [comment]
Hi @annibal1 

The issue has been assigned to one of our collogue and he's working on it. Once he has finished it, I will let you know how to see the client's IP address by installing Kafka monitoring  tool.

**Comment by mustafaboleken** [comment]
We merged the development. I will provide you snapshot version to test it out.

**Comment by rjtoledo** [comment]
hi is it available now ? on what version this implemented?

**Comment by mustafaboleken** [comment]
Hi @rjtoledo 
Yes, it's implemented. You can use the latest snapshot version to test it. It will be available in the next release. Btw, you can get the latest snapshot from your account at antmedia.io
