### ISSUE TITLE
Audio in 23.976 Fps

### ISSUE THREAD

**Issue by Stirop** [ant-media/Ant-Media-Server#4396]
Hello, I have a problem with the antmedia server enterprise, if I send a streaming (rtsp) with audio at 23,976 FPS, after a few seconds the audio is out of sync. Has this happened to anyone else?

Thanks

**Comment by Mohit-3196** [comment]
Hi @Stirop ,
How are you?

Thank you for writing about the issue here.

Please share your AMS Web Panel login details with me on support@antmedia.io so that I can check the issue.

Thank you.

**Comment by Mohit-3196** [comment]
Hi @Stirop 
I'm waiting to hear from you.
Kindly respond or else we'll have to close the issue due to inactivity.

Thank you

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please feel free to open if you need
