### ISSUE TITLE
@antmedia/webrtc_adaptor package isn't compatible with Node.js

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4402]
### Short description
Npm module is not compatible with Node.js applications

### Steps to reproduce
1. Create a Node.js application with Express.js
2. Add "@antmedia/webrtc_adaptor": "^2.4.3" into package.json
3. Try to import or add require state to webrtc adaptor

### Logs
Cannot find module. Please verify that the package.json has a valid "main" entry

 
Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by subastandoco** [comment]
I'm facing this issue when trying to import the library in an angular project. is there some @types to be installed ? I'm facing: Cannot find module '@antmedia/webrtc_adaptor' or its corresponding type declarations error

**Comment by mustafaboleken** [comment]
Hi @subastandoco,
We were still working on fixing the npm package. I suggest you download our javascript library manually on StreamApp and insert them into your project. You can also check our conference app which is written in React to see how you should use.

https://github.com/ant-media/StreamApp
https://github.com/ant-media/conference-call-application/blob/main/react/package.json

**Comment by rahul7827** [comment]
> I'm facing this issue when trying to import the library in an angular project. is there some @types to be installed ? I'm facing: Cannot find module '@antmedia/webrtc_adaptor' or its corresponding type declarations error

Hi @subastandoco 

Can you please try the solution mentioned here. I have answered here.
Please let me know this works for you 

[Solution](https://stackoverflow.com/questions/70950715/unable-to-import-webrtcadaptor-which-is-in-js-file-from-antmedia-package-in-node)
