### ISSUE TITLE
Maven Build

### ISSUE THREAD

**Issue by gazibastug** [ant-media/Ant-Media-Server#4403]
Can you give information about this library?
I can't do the enterprise build.

artifactId>srt-platform</artifactId>
<version>${javacpp.srt.version}</version>

**Comment by yashtandon113** [comment]
Hi @gazibastug
This is the SRT library. Please find the attached zip file for SRT.
[srt.zip](https://github.com/ant-media/Ant-Media-Server/files/9632965/srt.zip)

Go to ~/.m2/repository/org/bytedeco/ path and copy srt and srt-platform folders inside zip file. 

After that, try building again. Please also ensure that you have enterprise source code available for enterprise build.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please feel free to open if you need
