### ISSUE TITLE
Android streaming in landscape mode

### ISSUE THREAD

**Issue by bikee1235** [ant-media/Ant-Media-Server#4409]
### Short description

When we are rotating device from Portrait  to Landscape it's not fitting properly 

Device in Portrait

<img width="576" alt="Screenshot 2022-09-20 at 2 31 51 PM" src="https://user-images.githubusercontent.com/23609848/191219259-8f490636-2a46-4b82-9fc3-b202a5b6e26f.png">

After device rotation  Landscape

<img width="575" alt="Screenshot 2022-09-20 at 2 32 06 PM" src="https://user-images.githubusercontent.com/23609848/191219384-01a664d6-4155-43a9-9d74-202f0caaea21.png">

Similar type of issue we found in iOS too for that we have fixed using making rotation constant using 

var rotation = RTCVideoRotation._0 in RTCCustomFrameCapturer.swift file in framework
 

### Steps to reproduce

1.Strat Android device streaming 
2.Play using URL 
3.Try to Rotate the device in Landscape mode 

### Expected behaviour

Device should show some thing like this  when we rotate device from portrait to landscape  

<img width="172" alt="Screenshot 2022-09-20 at 2 50 45 PM" src="https://user-images.githubusercontent.com/23609848/191220465-6937b59e-25b9-4bb7-a4de-f9fd11bcbd53.png">

### Actual behaviour

And Device is showing in player like this

<img width="575" alt="Screenshot 2022-09-20 at 2 32 06 PM" src="https://user-images.githubusercontent.com/23609848/191220050-a0343d95-a07a-4569-9042-949e9e02c6f3.png">

@SelimEmre Can you please help us in resolving this issue

**Comment by shibupanda** [comment]
@SelimEmre if we'll instruct anything here so we can also try from our end meantime.
If it will be fix well and good.

**Comment by shibupanda** [comment]
@mustafaboleken now one more issue came.
Device: Google Pixel 4XL, 4
STR:
Try to rotate 4-5 times then sometimes getting black and sometimes it's stuck
attaching [log--Pixel4_2022_November_23_4_30_pm__140_a35ef-7160.log](https://github.com/ant-media/Ant-Media-Server/files/10077814/log--Pixel4_2022_November_23_4_30_pm__140_a35ef-7160.log) please check.

**Comment by mustafaboleken** [comment]
@shibupanda thanks for reporting, I will check it
