### ISSUE TITLE
Request to update Apache Tomcat to version 8.5.82 (latest version)

### ISSUE THREAD

**Issue by CKWong-git** [ant-media/Ant-Media-Server#4411]
We we are vulnerability test, we realized that current Antmedia version still running on old version Apache Tomcat version that prompted to several CVE.

We would like to request Ant Media team to update the current Apache Tomcat version. Thank you.

**Comment by mustafaboleken** [comment]
@CKWong-git thanks for reporting, I opened a pull request. We will merge it soon.
