### ISSUE TITLE
Question {ant media community}

### ISSUE THREAD

**Issue by SudoDios** [ant-media/Ant-Media-Server#4415]
HI.
Is it possible to make a voice chat with **ant media community** so that everyone can talk to each other?
And is it possible to use [WebRTC-Android-SDK](https://github.com/ant-media/WebRTC-Android-SDK) for servers other than ant media?

**Comment by mekya** [comment]
Hi @SudoDios ,

Thank you very much for the question. There are community hours(weekly - thursday at 3:00pm GMT+3) and community events(once for every 2-3 months). 
Community hours is Q/A and discussion session between community members and developers
Community events are having a specific agenda and demonstrates somethings or tell new features in the Ant Media Server.
Please join the [community.antmedia.io](https://community.antmedia.io/) to get notified from these events 

>And is it possible to use [WebRTC-Android-SDK](https://github.com/ant-media/WebRTC-Android-SDK) for servers other than ant media?
Unfortunately, you cannot use it directly. If you want to do that, you need to implement the signalling part on yourself.  

Regards,
A. Oguz

**Comment by SudoDios** [comment]
Thank you 🌹👍

**Comment by mekya** [comment]
Hi @SudoDios ,

I hope we can meet with you in community hours this week. 

Have a great Sunday

Regards,
A. Oguz
