### ISSUE TITLE
email validation in create new account in new antmedia server 

### ISSUE THREAD

**Issue by ashrafbendary** [ant-media/Ant-Media-Server#4418]
when create new account in first time account email validation didnt accept domain with 4 character ext like fakeeh.care its accept only 3 character ext like .com .net etc...

**Comment by yashtandon113** [comment]
Hi @ashrafbendary 
This issue is fixed by the team and PR is also raised --> https://github.com/ant-media/Ant-Media-Management-Console/pull/177
Most likely it will be merged before the next release.

**Comment by yashtandon113** [comment]
@ashrafbendary
Thanks for creating the issue. I was able to replicate the problem and reopened the related issue again.
https://github.com/ant-media/Ant-Media-Server/issues/4184

**Comment by mekya** [comment]
Hey Guys,
Any one of you can confirm the PR? @yashtandon113 @ashrafbendary

**Comment by yashtandon113** [comment]
@mekya 
I have confirmed and merged the PR.

**Comment by mekya** [comment]
You're doing great. 
Thank you @ashrafbendary for creating the issue.
