### ISSUE TITLE
HLS playback issue with H265 encoded SRT stream

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4419]
### Short description
There is a black video with audio in HLS playback (H264 transcoded) when the SRT stream is published with H265. In order to solve that player page to be refreshed on every new session.

### Environment
* Ant Media Server version: v2.4.3 and above

### Steps to reproduce
1. Enable at least one ABR on the server
2. Publish SRT with H265
3. Play the HLS stream
4. Stop publishing after few seconds and let all the HLS files delete from the server
5. Do not close the player Tab
6. Publish the stream again

### Expected behavior
Stream should connect and play fine

### Actual behavior
Connection is established as expected and the HLS stream started playing again but there is no video and only audio is playing. To resolve that we need to refresh the page. There is no such issue while publishing stream with H264.

**Comment by mustafaboleken** [comment]
Because of that H265 is not currently supported by browsers, this issue occurs. We added a setting to solve that. If you open `<AMS_DIR>/webapps/<AppName>/WEB-INF/red5-web.properties` and add `settings.addOriginalMuxerIntoHlsPlaylist=false`, then original stream is not played.
