### ISSUE TITLE
Hanging SRT streams published from Makito X4 SDI Encoder

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#4434]
SRT stream hangs and cannot be played until a system restart.

There are different observations:

1. When there is no signal on Makito input, but SRT output is configured on it - Makito keep sending SRT keepalives, but not streaming on that output, and that seems to confuse Ant.

2022-05-22 13:27:55,204 [vert.x-worker-thread-1] WARN  i.antmedia.enterprise.srt.SRTStream - Stream:stream2 in WebRTCAppEE does not get packet for 8959500 ms
2022-05-22 13:27:55,573 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-worker-thread-1,5,main] has been blocked for 9073636 ms, time limit is 10000 ms
io.vertx.core.VertxException: Thread blocked

2. It seems AMS is not hanging when it ingests two SRT streams simultaneously (same src and dst IP, same src and dst port, different stream names), although produces such error all the time:

2022-05-27 05:45:20,236 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,238 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,240 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,241 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,245 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,246 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0
2022-05-27 05:45:20,248 [Thread-6] WARN  i.a.enterprise.srt.SRTAdaptor - SRT stream map does not match any stream for socket:0

3. When stream hangs on, following logs are generated frequently.
![image.png](https://images.zenhubusercontent.com/5b0923f8425de866b93bf244/b92fb60c-0d32-4581-b502-3374556c8be5)

**Comment by da-morgan** [comment]
We are running into the same exact problem with our Ant Enterprise installation, is there a progress update on this? This is limiting us from using it in production.

**Comment by mekya** [comment]
Hi @da-morgan,
Yes, we've resolved appearing this issue in the recent versions. TBH, I've encountered this problem in one of the user deployment (having a premium support) and fixed the problem in one of the branch and deployed it.  They were using some other SRT pushing structure. They were not using Makito. After the fix, I don't see these logs and this problem in their deployment and It seems that I've missed tagging this issue.   

If you encounter the same problem again, it means there is something else triggers this problem. 

Do you confirm that you have this problem in the recent versions? If yes, you use the Makito?

Looking forward to hearing from you soon.
Oguz

**Comment by mekya** [comment]
It seems that this [issue](https://github.com/ant-media/Ant-Media-Server/issues/5504) is the one we're proceeding. I've asked the logs to analyze further for the problem. Let's proceed in here https://github.com/ant-media/Ant-Media-Server/issues/5504

**Comment by da-morgan** [comment]
These are two different issues. #5504 involves a single stream being unplayable but this issue involves the server completely failing.

We have done additional testing and have determined the exact test case where the issue arises. We are using an Makito X4 encoder to stream H265 SRT streams to the ant media server. The issue occurs when the Makito has an output channel connected to ant, but has no data flowing through from the encoder. If the encoder begins sending data the error resolves, and when it stops it reoccurs. 

The other note we found was that this error appears to only happen when ant is listening for the stream, and not calling it with a SRT URL. 

It would appear that there is some sort of handshake packet that the Makito sends to ant when it is in caller mode that ant gets tripped up on, and the server starts to crash. Due to the “thread blocked” error the server can not reliably serve any streams, even in different applications.

**Comment by mekya** [comment]
Thank you so much for your insights @da-morgan

**Comment by mekya** [comment]
> These are two different issues. #5504 involves a single stream being unplayable but this issue involves the server completely failing.
> 
> We have done additional testing and have determined the exact test case where the issue arises. We are using an Makito X4 encoder to stream H265 SRT streams to the ant media server. The issue occurs when the Makito has an output channel connected to ant, but has no data flowing through from the encoder. If the encoder begins sending data the error resolves, and when it stops it reoccurs.
> 
> The other note we found was that this error appears to only happen when ant is listening for the stream, and not calling it with a SRT URL.
> 
> It would appear that there is some sort of handshake packet that the Makito sends to ant when it is in caller mode that ant gets tripped up on, and the server starts to crash. Due to the “thread blocked” error the server can not reliably serve any streams, even in different applications.

Hi @da-morgan 
For the problem you mentioned above, we've introduced an activity timeout period for SRT streams. So if AMS doesn't receive any audio/video packets for a specific duration(5 seconds), it stops the connection. This implementation is in CI and running the tests currently. After it passes, you can get the latest snapshot and test it on your end. 

FYI
Cheers

**Comment by mekya** [comment]
Hi @da-morgan,
I've fixed the issue and merged to the master.  

Please check it and feel free to re-open if it does not work for you

Regards
