### ISSUE TITLE
Add guidance for using SRT with Gstreamer

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#4437]
https://community.antmedia.io/topic/1376-srt-using-gstreamer/

**Comment by SelimEmre** [comment]
Hi @SuperElectron,

Have a good day. Let me explain these details:
1- You can pull your UDP/SRT source from Ant Media Server. You don't need to send it through `srt-live-transmit`. 
2- Yes we are supporting a multi-track feature. Let's check if it's fit your scenario. 
3- It can be a good option. 

Thank you for your effort. We really appreciate that. Can we discuss these things in a meeting? We can check your Ant Media Server logs as well.

Best Regards,
Selim

**Comment by SuperElectron** [comment]
I emailed you

**Comment by SelimEmre** [comment]
Hi @SuperElectron,

I just wanted to add some comments regarding our work. We have just checked how we can integrate the Gstreamer SRT feature into Ant Media Server with @SuperElectron. It seems hard to do that because the Gstreamer SRT concept is a bit different than FFmpeg or others. If I add some technical details;
FFmpeg pushing the SRT source as below:
```
ffmpeg -re -i {INPUT} -vcodec libx264 -profile:v baseline -g 60 -acodec aac -f mpegts srt://test.antmedia.io:4200?streamid=WebRTCAppEE/stream1
``` 
The above command pushes Ant Media Server SRT Service. But If I try with Gstreamer SRT function, Gstreamer tries to create an SRT source. So that Gstreamer cannot able to send Ant Media Server, because SRT server is already created with Ant Media Server.
```
gst-launch-1.0 -v videotestsrc ! video/x-raw, height=1080, width=1920 ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, profile=baseline ! mpegtsmux ! srtsink uri="srt://test.antmedia.io:4200?streamid=WebRTCAppEE/stream1"
``` 

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @SuperElectron,

I sent a mail to you. But I wanted to update this GitHub issue with those who are encountering the same issue. 

I have great news for you! I checked this issue with my Gstreamer experienced colleagues. It worked with the latest version(1.20.3) on windows. I checked in detail after that. It seems that `streamid` parameter doesn't support the latest Gstreamer Linux version: 1.16.3. You can check the supported parameter list with this command: 
`gst-inspect-1.0 srtsink`

The important thing is that you need to compile with the 1.20.3 version on the linux machine. It will work after the compilation. 
https://www.linuxfromscratch.org/blfs/view/svn/multimedia/gstreamer10.html
https://tsaiyuyan.github.io/2020/05/11/gstreamer-bian-yi-bi-ji/

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @SuperElectron,

I sent a mail to you. But I wanted to update this GitHub issue with those who are encountering the same issue. 

I have great news for you! I checked this issue with my Gstreamer experienced colleagues. It worked with the latest version(1.20.3) on windows. I checked in detail after that. It seems that `streamid` parameter doesn't support the latest Gstreamer Linux version: 1.16.3. You can check the supported parameter list with this command: 
`gst-inspect-1.0 srtsink`

The important thing is that you need to compile with the 1.20.3 version on the linux machine. It will work after the compilation. 
https://www.linuxfromscratch.org/blfs/view/svn/multimedia/gstreamer10.html
https://tsaiyuyan.github.io/2020/05/11/gstreamer-bian-yi-bi-ji/

Best Regards,
Selim

**Comment by SuperElectron** [comment]
I have been extremely occupied with a software release on my end.  I will add to this issue here with some results after upgrading to gstreamer v1.20.3 or similar with ubuntu 18.04 or ubuntu 20.04.  

I will have these results within 2 weeks and I will include a gst-launch-1.0 command with either (1) something that works or (2) my issues.


I really appreciate the time your team has taken to investigate the issue. Thank you so much!!

**Comment by SuperElectron** [comment]
@jptalledo10 is this what you are looking for?


--------------------------------------------------------------------------------------------------------

(device 1)                     (device2: AntMediaServer)                                            (device3: viewer)
video source ----------->  video ingestions to [WebRTC]  ---------------------------> video player

--------------------------------------------------------------------------------------------------------
If so, you can one of the following on **device 1**:

(A) using a test source 
gst-launch-1.0 -v videotestsrc ! video/x-raw, height=1080, width=1920 ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, profile=baseline ! mpegtsmux ! srtsink uri="srt://test.antmedia.io:4200?streamid=WebRTCAppEE/stream1"

(B) using an mp4 video source
gst-launch-1.0 -v filesrc location=video.mp4 ! qtdemux ! avdec_h264 ! x264enc tune=zerolatency ! video/x-h264, profile=baseline ! mpegtsmux ! srtsink uri="srt://test.antmedia.io:4200?streamid=WebRTCAppEE/stream1"

(C) using rtsp source
-  you will need to replace this export with an rtsp source 

export URI="127.0.0.1:8554/video.sdp"

-  you will need to replace this export with your AMS server (WebRTCAppEE if paid, WebRTCApp if community version; change port 5080 to 5443 if you have enabled SSL)

export AMS_URI=rtmp://127.0.0.1:5080/WebRTCAppEE

gst-launch-1.0 -v rtspsrc location="rtsp://${URI}" ! qtdemux ! avdec_h264 ! x264enc tune=zerolatency ! video/x-h264, profile=baseline ! flvmux streamable=true ! rtmpsink location="${AMS_URI}"

--------------------------------------------------------------------------------------------------------

on **device 2**, you can click the play button and view the stream

--------------------------------------------------------------------------------------------------------

on **device 3**, you need to setup a WebRTC client (view https://resources.antmedia.io/docs/webrtc-sdks)

**Comment by jptalledo10** [comment]
Thank for the info.

Currently. I upgraded Ant-Media Enterprise to version 2.5.3.  Not sure if there is any setting to enable SRT?

When trying I am getting input/output error. Do I need to open Port 2000 for SRT?

**Comment by jptalledo10** [comment]
@SuperElectron Can you advise how to do SRT with video and audio using the gstreamer pipeline?

**Comment by mekya** [comment]
Hey @jptalledo10,

There is a sample for SRT Publish in here https://antmedia.io/webrtc-samples/

You need to open 4200 UDP port to let the AMS ingest SRT stream. 

For gstreamer pipeline, let me ask one of my colleague

**Comment by USAMAWIZARD** [comment]
here are the steps to send the SRT stream with gstreamer to ant media server 
1. install latest version of gstreamer (tested with 1.20.3 and above)
2. open port 4200 UDP

this command will only work with an mp4 file (file should contain both video and audio)
this is tested with GStreamer 1.20.3

gst-launch-1.0 filesrc location=movie.mp4  ! decodebin name=decode ! x264enc tune=zerolatency ! mpegtsmux name=muxer ! srtsink uri=srt://{AMS_IP}:4200?streamid=LiveApp/stream1  decode. ! audioconvert ! avenc_aac ! muxer.

I have also wrote a blog post recently for publishing with SRT and playing with WebRTC hope it will be helpfull
[blog post](https://antmedia.io/how-to-ingest-srt-and-play-with-webrtc/
)

**Comment by zeroflow** [comment]
I can't get neither the Example from the blogpost nor the gstreamer command from your last comment to run.

Is there an error on my side or could it be inside the app?

AMS Enterprise 2.5.3
GStreamer Core Library version 1.16.3 (tested on Ubuntu and NVidia Jetson, upgrade not feasible due to NVidia acceleration)

```
gst-launch-1.0 filesrc location=./Big_Buck_Bunny_1080_10s_30MB.mp4 ! qtdemux ! decodebin ! x264enc tune=zerolatency ! mpegtsmux ! srtsink uri=srt://<ip>:4200?streamid=WebRTCAppEE/stream1
18:31:26.293346/SRT:RcvQ:worker*E:SRT.c: HS VERSION=5 but no handshake extension found!
18:31:26.293402/SRT:RcvQ:worker*E:SRT.c: processAsyncConnectRequest: REJECT reported from HS processing, not processing further.
18:31:26.293413/SRT:RcvQ:worker*E:SRT.c: RendezvousQueue: processAsyncConnectRequest FAILED. Setting TTL as EXPIRED.
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstSRTSink:srtsink0: Could not write to resource.
Additional debug info:
gstsrtobject.c(1252): gst_srt_object_send_headers (): /GstPipeline:pipeline0/GstSRTSink:srtsink0:
Connection does not exist
Execution ended after 0:00:00.213397806
Setting pipeline to NULL ...
Freeing pipeline ...
```

AMS Error Log:
```
16:31:28.225685/SRT:RcvQ:w1!W:SRT.cn: @684401049:newConnection: connection rejected due to: INTERNAL REJECTION - ERROR:UNKNOWN
16:31:28.225728/SRT:RcvQ:w1!W:SRT.cn: processConnectRequest: rsp(REJECT): 1000 - Unknown or erroneous
```

AMS Console Log:
```
2023-06-26 18:31:28,225 [JavaCPP Thread ID 139875572438784] INFO  i.a.enterprise.srt.SRTAdaptor - Callback is called hsversion: 5  stream id:  
2023-06-26 18:31:28,225 [JavaCPP Thread ID 139875572438784] ERROR i.a.enterprise.srt.SRTAdaptor - Stream id is not in correct format. It should be '{APP_NAME}/{STREAM_ID}'. The stream id:
2023-06-26 18:31:46,301 [pool-4-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
```

**Comment by USAMAWIZARD** [comment]
@zeroflow 
gst-launch-1.0 filesrc location=movie.mp4  ! decodebin name=decode ! x264enc tune=zerolatency ! mpegtsmux name=muxer ! srtsink uri=srt://{AMS_IP}:4200?streamid=LiveApp/stream1  decode. ! audioconvert ! avenc_aac ! muxer.

unfortunately it does not work on previous versions the reason being the streamid is not passed to the server 
srtsink uri=srt://{AMS_IP}:4200?streamid=LiveApp/stream1

the stream id specified in the command is not passed to the server on previous versions of gstreamer that is why the stream is rejected by the server

**Comment by zeroflow** [comment]
That is unfortunate, but thank you for that fast and precise answer. 
Much appreciated.

**Comment by USAMAWIZARD** [comment]
@zeroflow @jptalledo10 @SuperElectron 

There will soon be a PR which will fix this issue , The LiveApp will be the default app to which streams will be published if there is no streamid specified and IP_address will be the Stream name for the stream

**Comment by USAMAWIZARD** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/654
