### ISSUE TITLE
Investigate the feasibility of updating contentSecurityPolicyHeaderValue in app settings on the FLY

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4443]
A user would like to update the contentSecurityPolicyHeaderValue in the app settings (red5-web.properties) to add/remove domains on the FLY without having to restart the server.

**Comment by Mohit-3196** [comment]
I have checked this and updated the document
https://resources.antmedia.io/docs/accessing-management-panel-rest-apis-with-user-authentication

Thank you

**Comment by mekya** [comment]
Hi @Mohit-3196 ,

There is an ambiguity in the docs. There are two docs about that and it's not giving a good experience. 
- https://resources.antmedia.io/docs/accessing-management-panel-rest-apis-with-user-authentication
- https://resources.antmedia.io/docs/jwt-rest-api-filter-for-web-management-panel-rest-services

Secondly, it will be great if there is a step by step instructions for the following doc.
https://resources.antmedia.io/docs/accessing-management-panel-rest-apis-with-user-authentication

**Comment by Mohit-3196** [comment]
Thank you for your inputs @mekya abi.

I think I can combine both documents in a structure like:
Accessing Management Panel REST APIs:

- Disabling authentication filter
- Via JWT Filters
- Via User Authentication  (I will refine the document stepwise)

I will update the instructions for changing `contentSecurityPolicyHeaderValue` here.

I hope it is fine.

Thank you

**Comment by mekya** [comment]
Yes, it's fine. Just a point no need to disable authentication filter anymore. Both JWT and User Authentication can work together.

**Comment by Mohit-3196** [comment]
OK. Thank you

**Comment by Mohit-3196** [comment]
Hello,
Below is a stepwise process to update `contentSecurityPolicyHeaderValue` properties in the application settings.
I have done this by the method of [AuthenticateUser](https://antmedia.io/rest/#/ManagementRestService/authenticateUser) 
You can checkout this reference [document](https://resources.antmedia.io/docs/jwt-rest-api-filter-for-web-management-panel-rest-services) for other method and how to use it.

1. First, let us **authenticate the user**. And to do this we need MD5 encrypted password, which we can get from [here](https://www.md5online.org/md5-encrypt.html) by entering the original password.

Now that we have the username and password let's make the REST API call to authenticate it.
![authenticate](https://user-images.githubusercontent.com/86982446/196133892-a7a695d9-a5b2-4e2f-bd44-ec4edf26ba96.png)

2. Now, let's get the **list of settings** of the application using [getSettings](https://antmedia.io/rest/#/ManagementRestService/getSettings)
![settings](https://user-images.githubusercontent.com/86982446/196135878-04e4f4f8-bc7e-40ec-ba69-84e4d424b3a5.png)

3. Now that we have all the settings listed, let's update the `contentSecurityPolicyHeaderValue`
![cors](https://user-images.githubusercontent.com/86982446/196141682-c9cd6f59-a328-4014-8617-a9b431a6a7d6.png)

The settings should be applied and the IFrame will only be playable on the listed domains.

**Comment by mekya** [comment]
I think accessing the server with JWT token is more friendly for development. I think documentation provides information for that. 

So I'm closing this issue. Please feel free to re-open if it does not resolve your problem.
