### ISSUE TITLE
How to compile and install programs from source ?

### ISSUE THREAD

**Issue by longtran84** [ant-media/Ant-Media-Server#4447]
can anyone help me on this? thanks

**Comment by longtran84** [comment]
@yashtandon113 i got the error like attach the file
![Screenshot from 2022-10-06 13-46-16](https://user-images.githubusercontent.com/33080326/194233225-73c1c682-666a-455f-88c1-ab563ec36411.png)

**Comment by yashtandon113** [comment]
@longtran84 
Thank you for providing the screenshot, but could you please elaborate on when you are experiencing this error and what you are attempting to achieve?

**Comment by longtran84** [comment]
@yashtandon113  I'm running class Bootstrap.java on the tool, then got that error.
![4ce620c452b395edcca2](https://user-images.githubusercontent.com/33080326/194250108-65edc635-df6c-4b51-b62c-ca7e42ab895b.jpg)

**Comment by mekya** [comment]
Alternatively, you can just take a look at this doc

https://resources.antmedia.io/docs/building-ams-from-source

**Comment by mustafaboleken** [comment]
Hi @longtran84
Did you compile it successfully?

**Comment by mekya** [comment]
I'm closing this issue for the inactivity. Please feel free to open if you have any problem
