### ISSUE TITLE
Better guarantees against corruption for MP4 backup

### ISSUE THREAD

**Issue by rsnk96** [ant-media/Ant-Media-Server#4449]
**Is your feature request related to a problem? Please describe.**
When saving backups of long-running feeds as mp4 files, the files often end up getting corrupted/not-playable. This can be particularly painful when there is a single mp4 file saving days/hours worth of feed (10+GB mp4) file which is not playable. Additionally, the fact that the moov atom has to be held in memory till the stream ends on AMS means that there could be a continually-growing memory consumption, which is not ideal.

**Potential Root Cause**
A guesstimate of why this is happening is because ffmpeg usually writes the moov-atom (a journal of properties like timescale, bitrate, and which key-frames are at what byte offsets, etc) of mp4 at the end. Hence, if a mp4 is being written to, but the mp4 muxing/writing process exits abnormally (Ex: AMS restarts, or the VM is restarted), we get a .mp4 file without a moov atom, which is not playable.

**Describe the solution you'd like**
1. Allow continually segmenting the mp4 files every 30 seconds (can be made a configurable parameter) into separate mp4 files (Can't use HLS chunks here as the HLS chunks do not contain a timestamp within their name, and we'd like to access the recordings by timestamp)
    * Why this will help: E.g. in case the mp4 muxing/writing process is interrupted at the 100th second, we will still have the first 90 seconds cleanly captured in 3 separate 30-second mp4 files which will be playable. Only the last 10-sec segment will not be playable
    * How this can be done: On ffmpeg in command line, this can be achieved by passing `-f segment -strftime 1 -segment_time 30 -reset_timestamps 1 -segment_format mp4` as described [here](https://stackoverflow.com/a/58910849/5714445). Unfortunately, not sure of how to add this in ffmpeg-java.
2. Write smooth-streaming fragment files instead of the current moov-atom-in-memory-till-EoS method
    1. Current method ([this line](https://github.com/ant-media/Ant-Media-Server/blob/971bff39743b25a257333a27f8dce38b4189ec0b/src/main/java/io/antmedia/muxer/Mp4Muxer.java#L115), essentially passing `-movflags faststart` to the ffmpeg command) only moves the `moov` atom of the mp4 file to the start **after** the mp4 file has successfully finished writing. This means if the mp4 file doesn't finish being written to, it ends up being corrupt (as it lacks a moov atom)
    2. Proposed method: Use `-movflags isml+frag_keyframe`, which will both bring down the memory consumption of AMS as a whole, and also allow most of the mp4 files to be playable in case the writing-process is interrupted (and mp4 writing process doesn't close/join cleanly). 

**Additional context**
* Reference for smooth-streaming (i.e. saving fragment-files instead of holding the moov atom in memory till end of stream): https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv
* `ffprobe`-ing the currently generated mp4 file reveals that it is a `moov` atom not found issue
```bash
% ffprobe xyz-2022-07-01_00-02-56.234..mp4
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564da16faf00] moov atom not found
xyz-2022-07-01_00-02-56.234.mp4: Invalid data found when processing input
```

**Comment by mekya** [comment]
Hi @rsnk96 ,

Thank you for the issue. I think we have a solution for your problem. Let one of my colleague respond you.

**Comment by Mohit-3196** [comment]
Hi @rsnk96 ,
Thank you very much for the detailed issue.

There are some better practises for recording and saving the streams as VODs. Let me try to write them for you and we can surely discuss it more.

1. One of the best practise is to save the recordings with HLS.
Since the .ts files are segmented, it's more reliable to save the recordings as HLS instead of MP4.
On the server side, we have this feature to record the HLS files and even if a streams beaks down due to network failure the .ts files will resume from where it ended and there will be a single master manifest .m3u8 files for a single streamId.

The .ts files can be appended to the same .m3u8 file with the same streamId.
To do so, edit and add the following hlsflag setting to the red5-web.properties file in /usr/local/antmedia/webapps/app-name/WEB-INF/ red5-web.properties
`settings.hlsflags=+append_list`
`settings.hlsPlayListType=event`
`settings.deleteHLSFilesOnEnded=false`

Then, restart the AMS with
`sudo service antmedia restart`

2. Recording as Dash
Similar to HLS recordings, streams can also be recorded as .mp4 for mpd files on server.

3. Recording as MP4
With AMS newer version even for MP4 recordings when there is an interruption in the broadcast due to network issues or re-connections, the server saves the mp4 files with prefixes.
So suppose if streamId stream1 is broadcasting and there is a network issue and broadcast stops for a few seconds and then starts back after reconnection, the server will save stream1.mp4 and when finally the stream finishes there will be stream1_1.mp4 and so on.

I hope these things find use for you and we can discuss more about them.

Thank you.
Cheers!

**Comment by rsnk96** [comment]
Hi @Mohit-3196 

Thanks for sharing the same. Creating a single continual manifest file is a good starting point, though it does not solve the time-stamp issue (we wouldn't know at which time a segment was recorded). The timestamp should be available in the mp4 file however, so we will try upgrading to the latest AMS for Point 3 (on mp4 files being saved during network interruptions), and get back on how it works.

**Comment by Mohit-3196** [comment]
Hi @rsnk96 ,
Yes you are right about timestamp with hls files.

You can get the latest version of AMS from [here](https://drive.google.com/file/d/1TbPFoISYUDuXUcSgVrvSmmESiX2abL2B/view?usp=sharing)

Please let me know if it of help for your cause.

Thank you

**Comment by Mohit-3196** [comment]
Hi @rsnk96 ,
How are you?

Let me know if you had any opportunity to test the HLS recording and the latest release for the MP4 recordings during reconnections.

Thank you

**Comment by rsnk96** [comment]
Hi @Mohit-3196 
Apologies for the delayed response. Our team is planning to check it in about a week or two, will get back here on how it goes

**Comment by Mohit-3196** [comment]
Hi @rsnk96 ,
How are you?
Let me know if you had any opportunity to check this and if there is any feedback for me.

Thank you
