### ISSUE TITLE
Ant media server working locally

### ISSUE THREAD

**Issue by itsfk** [ant-media/Ant-Media-Server#445]
I am using your ant media server community edition and your live broadcasting android app. What i want to achieve is that the ant media server is on a remote location and the app is on another network. Currently its all working locally. Please help me how to achieve this?

**Comment by mekya** [comment]
Hi @itsfk ,

I am assigned this task for this week. 

Firstly, you need to have a server with public static ip. You can start this instance on any cloud service. 
After that install Ant Media Server to this server and you may optionally assign a domain name to your instance through DNS as well. 
Lastly, you can use server ip address or domain name in the android app as RTMP BASE URL.

In short, server should be accessible through network by android device. 

Please let me know if you have any further question

**Comment by mekya** [comment]
Hi @itsfk ,

Is there any update on your side? 

Regards,
A. Oguz

**Comment by itsfk** [comment]
I haven't bought the instance will get back to you when i have bought it
and installed ant media server on it

On 20 Oct 2018 10:41, "Ahmet Oğuz Mermerkaya" <notifications@github.com>
wrote:

Hi @itsfk <https://github.com/itsfk> ,

Is there any update on your side?

Regards,
A. Oguz

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ant-media/Ant-Media-Server/issues/445#issuecomment-431551482>,
or mute the thread

**Comment by mekya** [comment]
OK. I'll close this issue soon. You can re-open it if you need .

**Comment by itsfk** [comment]
Okay sure
