### ISSUE TITLE
How to configure to allow Swagger URL ?

### ISSUE THREAD

**Issue by longtran84** [ant-media/Ant-Media-Server#4453]
can anyone help me on this ?...Thanks

**Comment by mekya** [comment]
Hi @longtran84 ,

Let me assign it to one of my colleague to respond you. 

In order to have quick responses, you can ask questions to https://community.antmedia.io because this channel is generally related to the bugs, issues, features. 

Regards,
A. Oguz

**Comment by SelimEmre** [comment]
Hi @longtran84,

Let me explain how can you add your own application URL to swagger. You have 2 options for that:
1- You can create a swagger json file according to your application URL. Here are the steps:
```
git clone https://github.com/ant-media/Ant-Media-Server.git
Change `host` url to `BroadcastRestService.java` file: `https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/rest/BroadcastRestService.java#L69`
cd Ant-Media-Server; 
mvn compile com.github.kongchen:swagger-maven-plugin:generate;
After that you can copy your json data to https://editor-next.swagger.io/ editor for testing. You can also create your own swagger guidance with your own website.
```
2- You can directly change `host` parameter in `https://antmedia.io/rest/2.4.3/swagger.json` file. After that, you can copy your json data to https://editor-next.swagger.io or you can create your own swagger guidance with your own website.

I hope, it's clear to you.

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @longtran84,

Did you see my message?

Best Regards,
Selim

**Comment by longtran84** [comment]
@SelimEmre 

Thank you for your support, How to embed Swagger UI into a webpage?

**Comment by SelimEmre** [comment]
Hi @longtran84,

You can do it with this tutorial: https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/ Please let me know if you need more help.

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @longtran84,

Just wanted to ask you, did you see my last message?

Best Regards,
Selim

**Comment by williehao** [comment]
@SelimEmre Sorry to bother you, but I need your assistance please help me. I got the error message when I followed your guidelines.
PS: 1. I didn't change "`host` url to `BroadcastRestService.java`". Even I have changed the error is still happen.
2. Error message when I use the command line  "mvn install"
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project ant-media-server: Fatal error compiling: Error while executing the external compiler. Error while executing process. Cannot run program "javac" (in directory "/Ant-Media-Server"): error=2, No such file or directory
3. then I try to use the command line "apt install openjdk-11-jdk -y " to fix the problem and using "mvn install" again
4. Error message when I use the command line  "mvn install" again 

![image](https://github.com/ant-media/Ant-Media-Server/assets/15116422/eb838c85-5009-465f-a6cd-6ac92aa352b4)


PS:
1. Do I need to upgrade the Java version from 11 to 16~ version?
2. or do I need to change pom.xml content if yes how can I do it?

Thanks,
Willie

**Comment by mekya** [comment]
Hi @williehao,

You're encountering a java version issue in v2.8.0+. The maven plugin that generates swagger doc is not Java 17 compatible. 

It's a known issue and it'll be resolved in the scope of the following issue 
https://github.com/ant-media/Ant-Media-Server/issues/6060

FYI
Regards
Oguz
