### ISSUE TITLE
IOS SDK issue

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#4459]
testonline.zip file can be downloaded through the ticket: 70214 on FD

**Comment by mekya** [comment]
This issue has been fixed. We just need to remove the following line 
```
config.build_settings.delete ‘IPHONEOS_DEPLOYMENT_TARGET’
```
from the PodFile and install the pod again.

The documentation has been already updated. 
https://resources.antmedia.io/docs/ios-sdk
