### ISSUE TITLE
Some video files are not uploading to Digital Ocean SPACE after video streaming stops

### ISSUE THREAD

**Issue by rahul7827** [ant-media/Ant-Media-Server#4464]
### Short description
__Brief description of what happened__
I have enabled adaptive bitrate and using webrtc for video streaming.
![image](https://user-images.githubusercontent.com/77726801/195307140-d5b64898-b0fe-4508-9c96-39b27d113b69.png)

Multiple camera devices are connected into computer. 

When video streaming stops I found only one video saved on space.
![image](https://user-images.githubusercontent.com/77726801/195308223-2ec847c8-444d-4f27-8f12-ddbb9adaa7c1.png)

I thought there would be some file transfer issue, so i checked the server instance /usr/local/antmedia/webapps/appName/streams

and i found these missing files from space are present at this place

![image](https://user-images.githubusercontent.com/77726801/195310384-ddec7c1a-2d21-4d3f-8fdd-7a21f1f75a9a.png)

Streaming going on 24 X 7 having unique streaming id.

### Environment
* Ant Media Server version: Enterprise Edition 2.4.3 20220418_2241 
* Server Operating system : Ubuntu 20.04.5 LTS ( Usage of /:   6.3% of 154.88GB )
* Instance type : g4dn (g family)

### Expected behavior
All video files should be uploaded as per adaptive bitrates configuration

### Actual behavior
Sometimes some video files are not getting uploaded on server.

**Comment by yashtandon113** [comment]
Hi @rahul7827 
Thanks for creating the issue.

The [similar issue](https://github.com/ant-media/Ant-Media-Server/issues/2598) was previously reported, and it has been fixed in new the version 2.5.0.
The latest version is available in the downloads section of your [antmedia.io](https://antmedia.io) account.

Please let us know if the problem persists after upgrading the server.

**Comment by rahul7827** [comment]
Hi @yashtandon113 @mekya 

Thanks for the reply.

Do we have to upgrade the JS SDK after upgrading the media server version (2.5.0) ?

If yes, then it would be very difficult for my team to make the changes in our application and get tested, Since we have made our own customization in the JS SDK as per our own application requirement.

This issue started occurring from few days back, earlier everything was working smoothly.

There are total 4 issues we have to discuss.

In which an issue cause stopped working of WebRTCAppEE application (Means streaming stopped), and we were unaware of this, Site visitor reported the issue to client and client informed us.

Can we have a feature that, if something is majorly impacting the webapps in AMS, (like : CPU Overuse, Crash, e.t.c). Administrator should get an email, So that we can fix these at our end ASAP and minimize the losses.

Could you please arrange a meeting today so that I can show you these and we can have better understanding.

Client is not willing to frequent upgrade, they need a stable solution so that their business could not hamper. 

I appreciate the effort, you guys are putting to the make this AMS better every day. As a developer I can understand noting is perfect in one go, But we have to come up with a stable version.

Thank you.

**Comment by rahul7827** [comment]
Thanks @yashtandon113  and @mustafaboleken for the support over ticket. Will let you know after the upgrade.

**Comment by mekya** [comment]
Hey @rahul7827 

Thank you. Let me try to answer your questions. 


> Hi @yashtandon113 @mekya
> 
> Thanks for the reply.
> 
> Do we have to upgrade the JS SDK after upgrading the media server version (2.5.0) ?

Mostly, you don't have to. But for some circumstances you may need to upgrade. 

> 
> If yes, then it would be very difficult for my team to make the changes in our application and get tested, Since we have made our own customization in the JS SDK as per our own application requirement.
> 
> This issue started occurring from few days back, earlier everything was working smoothly.
> 
> There are total 4 issues we have to discuss.
> 
> In which an issue cause stopped working of WebRTCAppEE application (Means streaming stopped), and we were unaware of this, Site visitor reported the issue to client and client informed us.
> 
> Can we have a feature that, if something is majorly impacting the webapps in AMS, (like : CPU Overuse, Crash, e.t.c). Administrator should get an email, So that we can fix these at our end ASAP and minimize the losses.

It's a good point. We can create an issue about that. 

> 
> Could you please arrange a meeting today (before 5 PM, IST) so that I can show you these and we can have better understanding.

I think you already have a meeting with @yashtandon113 and @mustafaboleken 
> 
> Client is not willing to frequent upgrade, they need a stable solution so that their business could not hamper.

I see. We can provide snapshots to you and you don't need to wait for the releases.
> 
> I appreciate the effort, you guys are putting to the make this AMS better every day. As a developer I can understand noting is perfect in one go, But we have to come up with a stable version.

You're perfect. It's great that we understand each other. 
> 
> Thank you.

THANK YOU

Regards,
A. Oguz

**Comment by yashtandon113** [comment]
Closing this issue. Please feel free to open if you have any questions.
