### ISSUE TITLE
playWithJWT enabled in cluster mode not always work

### ISSUE THREAD

**Issue by eshen89** [ant-media/Ant-Media-Server#4469]
Hi, I have Antmedia running in cluster mode, 3 nodes. 
I have HAProxy serve as load balancer in front of the 3 nodes.
I also have AWS Cloudfront attach to this HAProxy load balancer.

Everything works except when I enabled `Play with JWT Filter for Stream`, I have a edge function to inject generated token to each `.m3u8` and `.ts` request.

This works if AMS running in standalone mode. However, on cluster mode, this works 50% of time, I'm getting 200 and 404 interchangeably for all requests. My initial guess is that load balancer keep switching traffic between the nodes, sometime it hits to the right node and sometimes it doesn't.

![image](https://user-images.githubusercontent.com/6821374/195701676-b8ae0f51-0553-4c5e-9b34-2feb7ec7ce9b.png)

This brings another question: if I disable `Play with JWT Filter for Stream`, I don't have to worry this issue, the load balancer always hit to the right place. Also I can view the stream from a node even it is publish from another node.

Is something wrong with my setup? How can I request the stream with JWT through the LB without knowing the exact node having the broadcast?

**Comment by mekya** [comment]
Thank you for the issue @eshen89 , I've moved to the backlog to schedule.

**Comment by mekya** [comment]
Hi @eshen89,

This issue has been fixed in the issue below and integration test codes are available to check the streams are available to play in cluster modes.  

- https://github.com/ant-media/Ant-Media-Server/issues/4966

So I'm closing this issue and please let me know if it does not work for you
