### ISSUE TITLE
Investigate video issue in the new release ABR mode(openh264 thread blocking)

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#4471]
# Issue
Video may freeze in high resolution ABR.

### Environment
* Ant Media Server version: 2.5.0

### Steps to reproduce
1. Open 32 core instance
2. Add 1080p ABR
3. Create a 1080p 4000kbps RTMP stream
4. Play video

### Expected behavior
Video can be played without any issue.

### Actual behavior
Video freezes time to time.

**Comment by mekya** [comment]
Fix is available on the enterprise side -https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/575

Previously frames decoded / seconds was like below

<img width="326" alt="Screenshot 2023-04-04 at 02 48 34" src="https://user-images.githubusercontent.com/3456251/229651759-362c7155-0c15-434a-973a-4c0664dd62a6.png">

After this fix it's like below

<img width="363" alt="Screenshot 2023-04-04 at 02 35 45" src="https://user-images.githubusercontent.com/3456251/229651842-19e19e3b-b26b-4e95-8436-95871ce6acfe.png">

**Comment by mekya** [comment]
This issue has been fixed in 2.6.0.
