### ISSUE TITLE
Develop a plugin to add silence track if it's not present

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4473]
When sending a stream to YouTube, an audio track is mandatory.  For example when source is ip camera, audio track is not present.

My solution is adding silence track with a plugin.

**Comment by burak-58** [comment]
Try filter plugin to that.

**Comment by mustafaboleken** [comment]
When I try to use the filter plugin, the problem is solved. We got 2 options.

The first one is adding audio from another stream.

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/LiveApp/rest/v2/filters/create" -d '{"filterId":"filter1","inputStreams":["stream1","stream2"],"outputStreams":["test"],"videoFilter":"[in0]copy[out0]","audioFilter":"[in1]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'`


The second one is generating audio using audioFilter:

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/LiveApp/rest/v2/filters/create" -d '{"filterId":"filter1","inputStreams":["stream1"],"outputStreams":["test"],"videoFilter":"[in0]copy[out0]","audioFilter":"sine=frequency=1000:sample_rate=48000:duration=5000[s0];[s0]acopy[out0]","videoEnabled":"true","audioEnabled":"true"}'`
