### ISSUE TITLE
Ant Media Server rejecting SRT handshake when stream id is not sent in handshake

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#4480]
### Short description
not able to stream SRT 
from gstreamer version 1.16 

### Steps to reproduce
1. gst-launch-1.0 -v videotestsrc ! video/x-raw, height=1080, width=1920 ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, profile=baseline ! mpegtsmux ! srtsink uri="srt://PUBLIC_IP:4200"

### Expected behavior
should start streaming.

### Actual behavior
failing SRT handshake.

### Posible Reason
I have inspected SRT handshake using wireshark in gstreamer 1.16 as well as gstreamer 1.20
gstreamer 1.16 does not have option to set stream id where as gstreamer 1.20 does
with gstreamer 1.16 antmedia server is rejecting the handshake when the stream id is not send in SRT handshake.

### Logs

2022-10-19 15:16:49,157 [JavaCPP Thread ID 140209596520192] io.antmedia.enterprise.srt.SRTAdaptor - Callback is called hsversion: 5  stream id:
2022-10-19 15:16:49,158 [JavaCPP Thread ID 140209596520192] io.antmedia.enterprise.srt.SRTAdaptor - Stream id is not in correct format. It should be '{APP_NAME}/{STREAM_ID}'. The stream id:

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi Usama,

It's an expected behaviour because we need to have stream id to map the streams.
