### ISSUE TITLE
Finalize Auto-Scale K8S Documentation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4488]

**Comment by muratugureminoglu** [comment]
https://portal.document360.io/033a096a-b182-4b05-8c1b-425e70959431/document/v1/view/61e61c03-8a21-4c03-a1fc-38bd043f9e9c

https://portal.document360.io/033a096a-b182-4b05-8c1b-425e70959431/document/v1/view/6b9197ec-8d61-4174-aad3-55e1115451f8
