### ISSUE TITLE
Record Should be called from javascript api

### ISSUE THREAD

**Issue by Lethea** [ant-media/Ant-Media-Server#449]
Record to mp4 can be enabled / disabled from management panel. For cloudify and multitenancy project, it should be configured via js api

**Comment by mekya** [comment]
Actually, mp4 record is enabled/disabled from management panel. It totally enables/disables for mp4 records for all streams

You ask for enable/disable of mp4 record for each script specifically via JS api in WebRTC streams, don't you?

**Comment by Lethea** [comment]
yes , its a must for us, also for pricing strategy like up to 4 pariticipant and record all conversation 9$ without recording 6$.on the other hand if i make it enable from management panel then all the stream recorded. unfortunately at least one of the conference should not be recorded due to privacy

**Comment by ntnahn** [comment]
Hi,
I need to setting to record mp4 for each stream when publish stream via WebRTC

**Comment by SelimEmre** [comment]
Hi @ntnahn,
![asd123123](https://user-images.githubusercontent.com/9084130/50737459-99a85780-11da-11e9-9a34-9bc4b4f71a8f.JPG)
Firstly you should open WebRTCApp or WebRTCAppEE section -- Settings -- Enable MP4 Recording section.  
![asd213123](https://user-images.githubusercontent.com/9084130/50737489-fb68c180-11da-11e9-80b3-5aad8f03ad78.JPG)
After, your WebRTC records are listing in VOD section. You can delete, download, play or use embed code. If you have any problem, please inform me. Thanks.

**Comment by SelimEmre** [comment]
Hi @ntnahn,
I misunderstood you. Sorry for this. 
We are create rest service for this situation. You can look into https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/rest/BroadcastRestService.java enableMp4Muxing function. You can record mp4 each stream in this service. Thanks.

**Comment by ntnahn** [comment]
Thank for your answer @SelimEmre 
I'm using the WebRTC to push stream, so i need to setting the mp4 record attach to the data when emit the stream publish event. Do you have this option to do that?
Thanks.

**Comment by SelimEmre** [comment]
Hi @ntnahn,
You can use the same configuration. You can use the broadcast rest service(enableMp4Muxing) in the WebRTC stream.

Best Regards,
Selim

**Comment by krishnapsarthi** [comment]
> yes , its a must for us, also for pricing strategy like up to 4 pariticipant and record all conversation 9$ without recording 6$.on the other hand if i make it enable from management panel then all the stream recorded. unfortunately at least one of the conference should not be recorded due to privacy
@Lethea Are able to use js api for enable/disable recording on demand?

**Comment by Lethea** [comment]
> > yes , its a must for us, also for pricing strategy like up to 4 pariticipant and record all conversation 9$ without recording 6$.on the other hand if i make it enable from management panel then all the stream recorded. unfortunately at least one of the conference should not be recorded due to privacy
> > @Lethea Are you able to use JS API for enable/disable recording on demand?

I havent tried yet, let you know when tested
