### ISSUE TITLE
Reconnection is not successful when network is changed.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4492]
### Short description
When publishing a stream in conference and the network changes say wifi to mobile data or vice versa, the reconnection is not successful. 

### Environment
* Ant Media Server version: AMS v2.4.3 and 2.5.0

### Steps to reproduce
1. Join the sample conference page as conference.html or multitrack-conference.html with wi-fi
2. Change the network to mobile or cell
3. The connection breaks and Join Room is available but when joining server gives publish timeout/remote description not set error.

### Expected behaviour
When network changes, the stream should get reconnected in the room and publish should resume.

### Actual behaviour
The stream doesn't reconnect and when Join Room is called, server gives publish timeout and/or remote description error.

**Comment by mekya** [comment]
Thank you for the issue @Mohit-3196. You have catch a good point.

**Comment by yashtandon113** [comment]
The problem also occurs if one of the origin servers to which participants are connected fails. Participants should be reconnected to another origin server in this case.
