### ISSUE TITLE
[iOS] [Video Conference App] When turning on/off camera, audio is not sended

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4493]
https://community.antmedia.io/topic/1431-ios-154-not-sending-audio-when-turning-onoff-camera

**Comment by mustafaboleken** [comment]
Customer has a modified version of javascript sdk, so I close this issue.

**Comment by mekya** [comment]
Thank you @mustafaboleken for opening and following up the issue.
