### ISSUE TITLE
Random EC2 instance turn-off causes an unexpected shutdown

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#4494]
### Short description
It's happening %70 of shutdowns.

### Environment
* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Open-Close EC2 instance.
2. Sometimes Ant Media Server does not close as expected.

### Expected behavior
It should shutdown as expected.

### Actual behavior
Sometimes it's not shutting down as expected.

### Logs
[ant-media-server.log.zip](https://github.com/ant-media/Ant-Media-Server/files/9847413/ant-media-server.log.zip)

**Comment by mekya** [comment]
Good point @SelimEmre.

Do you understand the unexpected shutdown when you start the instance again?

**Comment by burak-58** [comment]
Closed because no problem with recent releases.
