### ISSUE TITLE
Issues with Deploying Applications in Cluster Mode

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#4498]
# Issue
Newly added instance cannot deploy custom application some cases

### Steps to reproduce
1. Create a standalone node and add a custom application
2. Then change mode to cluster
3. Add a new node without adding the app

### Expected behavior
The custom app should be downloaded from the first node and deployed to second node.
### Actual behavior
App isn't deployed to second node.

Also there may be some issue while undeploy/deploy case. Not investigated well. I will edit.

**Comment by mekya** [comment]
Closing this issue because it's fixed and merged
