### ISSUE TITLE
Android WebRTC App  sample disconnects after a few minutes

### ISSUE THREAD

**Issue by andreishosta** [ant-media/Ant-Media-Server#451]
Hi, I'm using WebRTCAndroidSampleApp with a demo enterprise Ant media server to perform some local test on how Ant works on my hardware. Ant media Server Enterprise is running in a virtual ubuntu on VMWare and I am running the WebRTCAndroidSampleApp  as mobile application client on my devices.
I perform this test with My cell phone (galaxy A3) and it has no problem, but when I run it on my own produced Android Devices (Android 4.4.4, 512MByte Ram, dual core A53 CPU, 2MP Camera), it does not last long time and after a few minutes connection gets closed. Also video is so laggy on the device.
This device supports Hardware accelerated Video Encoding/Decoding of up to 1080p@30FPS and I checked CPU and Memory usage are normal while running app. 

Now I need help in one of these:
1. Can you please help me understand the reason of instability of the connection? Logs of android app are attached.
2. How can I make sure there is no incompatibility between my Hardware and Ant Media Server android client apps.
3. How can I config app to make sure it uses Hardware Accelerated Codecs? I can't even change Video Resolution in the app.

### Steps to reproduce
1. Run android app
2. open player http://localhost:5080/WebRTCAppEE/player.html
3. Start playing video
4. After 2 or 3 minutes video stops

### Logs
Android Studio Log (from android app):
https://pastebin.com/LjYA0yuz

Thanks in advance,
Andrei

**Comment by mekya** [comment]
Hi Andrei,
I am assigned this task for this week :) I hope I can help you. 

I have an experience about running WebRTC SDK in a custom device. The problem I've seen there, WebRTC SDK is using hardware encoders for some chipsets like Exynos, Qualcomm etc. It does not use HW encoder even if exists in the device. We made a simple hack for that and it worked. Anyway,  what's the chipset in your device?

Regards,
A. Oguz

**Comment by andreishosta** [comment]
That's great to see you again Oguz!
It's a Spreadtrum chipset and these are the HW codecs:

OMX.sprd.mpeg4.encoder [ENCODER] {video/mp4v-es, }
OMX.sprd.h263.encoder [ENCODER] {video/3gpp, }
OMX.sprd.h264.encoder [ENCODER] {video/avc, }
OMX.sprd.mpeg4.decoder [DECODER] {video/mp4v-es, }
OMX.sprd.h263.decoder [DECODER] {video/3gpp, }
OMX.sprd.h264.decoder [DECODER] {video/avc, }
OMX.sprd.vpx.decoder [DECODER] {video/x-vnd.on2.vp8, }
OMX.sprd.aac.decoder [DECODER] {audio/mp4a-latm, }
OMX.sprd.ape.decoder [DECODER] {audio/ape, }
OMX.sprd.mp3.decoder [DECODER] {audio/mpeg, }
OMX.sprd.mp3.decoder [DECODER] {audio/mpeg-L1, }
OMX.sprd.mp3.decoder [DECODER] {audio/mpeg-L2, }

I think the SDK does not know OMX.sprd. codecs are HW codec. Am I right?
Can you help me on this?

Thanks again

**Comment by mekya** [comment]
Thank you. Nice to see you again @andreishosta :)

Yeah these are HW codecs but they still may not be supported.  
Please decompile the HardwareEncoderFactory class in libwebrtc.jar 

Put a breakpoint on the line(`return (VideoCodecInfo[])supportedCodecInfos.toArray(new VideoCodecInfo[supportedCodecInfos.size()]);`) of the function below
```
public VideoCodecInfo[] getSupportedCodecs()
```

At the breakpoint, take a look at which encoders are supported for the WebRTC SDK. If none, you can dig into the `getSupportedCodecs` and find out why SDK does not support. If there are some encoders in the list, let me know which ones are supported.

**Comment by andreishosta** [comment]
Hi @mekya 
This is the list of all codecs:

Codec: OMX.sprd.mp3.decoder [DECODER] {audio/mpeg, }
Codec: OMX.sprd.mp3.decoder [DECODER] {audio/mpeg-L1, }
Codec: OMX.sprd.mp3.decoder [DECODER] {audio/mpeg-L2, }
Codec: OMX.google.mp3.decoder [DECODER] {audio/mpeg, }
Codec: OMX.google.amrnb.decoder [DECODER] {audio/3gpp, }
Codec: OMX.google.amrwb.decoder [DECODER] {audio/amr-wb, }
Codec: OMX.google.aac.decoder [DECODER] {audio/mp4a-latm, }
Codec: OMX.sprd.aac.decoder [DECODER] {audio/mp4a-latm, }
Codec: OMX.sprd.ape.decoder [DECODER] {audio/ape, }
Codec: OMX.google.g711.alaw.decoder [DECODER] {audio/g711-alaw, }
Codec: OMX.google.g711.mlaw.decoder [DECODER] {audio/g711-mlaw, }
Codec: OMX.google.imaadpcm.decoder [DECODER] {audio/ima-adpcm, }
Codec: OMX.google.vorbis.decoder [DECODER] {audio/vorbis, }
Codec: OMX.sprd.mpeg4.decoder [DECODER] {video/mp4v-es, }
Codec: OMX.sprd.h263.decoder [DECODER] {video/3gpp, }
Codec: OMX.sprd.h264.decoder [DECODER] {video/avc, }
Codec: OMX.sprd.vpx.decoder [DECODER] {video/x-vnd.on2.vp8, }
Codec: OMX.vpu.video_decoder.avc [DECODER] {video/avc, }
Codec: OMX.vpu.video_decoder.mpeg2 [DECODER] {video/mpeg2, }
Codec: OMX.google.mjpg.decoder [DECODER] {video/mjpg, }
Codec: OMX.google.vp8.decoder [DECODER] {video/x-vnd.on2.vp8, }
Codec: OMX.google.vp9.decoder [DECODER] {video/x-vnd.on2.vp9, }
Codec: OMX.sprd.mpeg4.encoder [ENCODER] {video/mp4v-es, }
Codec: OMX.sprd.h263.encoder [ENCODER] {video/3gpp, }
Codec: OMX.sprd.h264.encoder [ENCODER] {video/avc, }
Codec: OMX.google.amrnb.encoder [ENCODER] {audio/3gpp, }
Codec: AACEncoder [ENCODER] {audio/mp4a-latm, }
Codec: OMX.google.raw.decoder [DECODER] {audio/raw, }

I took it from getSupportedCodecs.

The problem is it does not accept OMX.sprd codecs as HW codec and believes they are software codec.
How we can hack it to undertand OMX.sprd codecs can be accepted as HW ones?

**Comment by mekya** [comment]
Hi @andreishosta ,

I see. 

getSupportedCodecs has some checks. We need to find out in which part it fails.

Here is the call hierarchy. Put a breakpoint in isSupportedCodec and please find to look at why it is not failing when your HW encoder is given as parameter. 

-> isSupportedCodec()
  -> findCodecForType()
    -> getSupportedCodecs()

**Comment by mekya** [comment]
Yeah that is the hacking :)

Congrats...
