### ISSUE TITLE
Guest streams are added to live streamers

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#4512]
I would like the ability for users to have a guest stream added to live streamers. They would have the option before broadcast to add someone following them and during broadcast they would be allowed to add someone from the cue who are watching the stream to be added. Also the viewer in the stream can send a request to the broadcaster to join or the Broadcaster can send a request for the viewer to join the live broadcast. I would like the UI/UX to be like this.. Side by side when viewed

![attachment](https://user-images.githubusercontent.com/114407483/197514366-33adcb55-8db2-4e55-8598-259b3b03eede.png)

**Comment by rahul7827** [comment]
> Also the viewer in the stream can send a request to the broadcaster to join or the Broadcaster can send a request for the viewer to join the live broadcast. I would like the UI/UX to be like this.. Side by side when viewed

You can achieve this by using conference feature (Not sure but **conference.html** might be in Enterprise edition).
Now viewer will send request to broadcaster (or vice-versa) via websocket. (You may use socket.io)
Once the listener get request, script can trigger the publish/joinRoom function.

You have to customize the UI as per your requirement.

>I would like the ability for users to have a guest stream added to live streamers.

This is not very clear to me.

**Comment by umtcylmz** [comment]
Hi @rahul7827 

Thanks for your contribution! Let me tag @SelimEmre here for his reference.

The second part is related to multi screen streaming. User wants to share 2 streams on the same window.

Thanks,
Umut

**Comment by rahul7827** [comment]
Thanks for the question @umtcylmz 

It seems you are talking about **MCU**. BTW lets wait for selim input.

**Comment by umtcylmz** [comment]
Yes definitely. We are thinking about the MCU as well. But there is something else they want. Let's wait @SelimEmre for the update.

**Comment by SelimEmre** [comment]
Hi guys!

We discussed this issue internally. But I want to add some details here for newcomers. Thank you for adding these details @rahul7827. I just checked `conference.html` MCU feature. There are some blanks in the streams. 

<img width="1512" alt="Screenshot 2022-11-14 at 00 10 04" src="https://user-images.githubusercontent.com/9084130/201545033-0dd62979-a25f-41ae-87f1-0ec7c148c922.png">

Merging streams is doable with the Filter plugin as well. In this way, you will get more capability of stream properties. So that you can manage the blanks with REST API requests. 

Please check below links:
https://github.com/ant-media/Plugins/tree/master/FilterPlugin
https://antmedia.io/mcu-conference/

I hope, I could help you.

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi guys,

I want to add something details regarding Filter plugin. Merging streams is possible with no blanks. Here are steps you need to follow:
1- Add Filter plugin .jar file to Ant Media Server plugin folder. These steps are already in [this page](https://github.com/ant-media/Plugins/tree/master/FilterPlugin).
2- After that, you just need to call Merge REST API as below:
```
var data = JSON.stringify({
  "filterId": "10WjTw1112",
  "inputStreams": [
    "stream1",
    "stream2"
  ],
  "outputStreams": [
    "outputstream-filter"
  ],
  "videoFilter": "[in0]scale=360:240[s0];[in1]scale=360:240[s1];[s0][s1]hstack=inputs=2[out0]",
  "audioFilter": "[in0][in1]amix=inputs=2[out0]",
  "videoEnabled": "true",
  "audioEnabled": "true"
});

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://AMS-URL:5443/WebRTCAppEE/rest/v2/filters/create");
xhr.setRequestHeader("Content-Type", "application/json");

xhr.send(data);
```

That's all! I hope, it's clear for you.

![image](https://user-images.githubusercontent.com/9084130/202646178-dd444d29-ae92-492c-921b-e5749be5c4a5.png)

Best Regards,
Selim

**Comment by umtcylmz** [comment]
Hi @SelimEmre thank you so much for resolving this issue.
