### ISSUE TITLE
[IOS SDK] WebRTCiOSSDK - Unsupported Swift architecture error

### ISSUE THREAD

**Issue by denmorgenshtern** [ant-media/Ant-Media-Server#4521]
### Short description
__Brief description of what happened__
Im getting WebRTCiOSSDK-Swift.h -> "Unsupported Swift architecture" error with fresh WebRTCiOSSDK.xcFramework created by running ./export_xc_framework.sh

### Environment

* Operating system and version: 
macOS Monterey 12.5 
Xcode 14.0.1
Swift 5.7
iOS simulator iphone 14
M1 pro architecture

**Comment by mekya** [comment]
It's a good catch @denmorgenshtern ;) It will help us resolve the problem

**Comment by mustafaboleken** [comment]
Hi @denmorgenshtern 
I tested the pull request that @mekya opened with the m1 MacBook pro and it works fine. Please check it and give us feedback.

**Comment by denmorgenshtern** [comment]
Great, it works 🤘 
Thanks!

**Comment by mekya** [comment]
Hey @denmorgenshtern ,

Thank you for the update. Why don't you join the community hours and be part of this journey?
https://community.antmedia.io/topic/1414-%F0%9F%93%A3-weekly-qa-community-hours-about-anything-you-want-%F0%9F%98%8D-every-thursday/#comment-5079

Regards,
Oguz
