### ISSUE TITLE
sdp offer with resolution cause frame loss

### ISSUE THREAD

**Issue by Lethea** [ant-media/Ant-Media-Server#453]
we design a ui that the publisher client can choose stream quaility also we plan to measure the publisher upload speed and auto decide the publish stream quality. when we add the resolution params to sdp, performance and frame loss problem occurs

**Comment by SelimEmre** [comment]
Hi @Lethea,
Thank you for your interest. Do you still have problems? If the problem persists, can you re-open this issue?
