### ISSUE TITLE
Marketplace Update

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4530]

**Comment by asharamseervi** [comment]
Anyone care about to write description; what is cooking up there? I mean, we as a community are so curious of innovation happening around ant media server.

**Comment by SelimEmre** [comment]
Hi @asharamseervi,

Thank you for the great question. We are always adding some features, fixing issues, etc.  You can check full of changelog list here: https://github.com/ant-media/Ant-Media-Server/releases

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @asharamseervi,

You can also join community hours to discuss changelog details with developers.
Click Schedule Meeting on [antmedia.io](https://antmedia.io/) and Choose the Community Hours.

Best Regards,
Selim

**Comment by asharamseervi** [comment]
Thanks @SelimEmre, Let's  connect on 21st November!

**Comment by mekya** [comment]
You're right @asharamseervi . It was about updating the images in AWS, Azure, etc. for previous version
