### ISSUE TITLE
Update documentation accessing Management Panel API

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4532]
In the current documentation, it says that update the web.xml but no need to update the web.xml

JWT filter and Username and password can be used simulatenously

[document](https://resources.antmedia.io/docs/jwt-rest-api-filter-for-web-management-panel-rest-services)

**Comment by Mohit-3196** [comment]
I have been trying to use the JWT filter directly without updating web.xml but unfortunately I can't find any luck yet.
The process I followed is like
1. Edit `conf/red5.properties`
2. Made the following changes to the file:
`server.jwtServerControlEnabled=true`
`server.jwtServerSecretKey=32-character-secret-key`
3. Generated JWT token from JWT debugger using secret key.
4. Made the web panel rest api call directly.
The REST API call in response gives error 403

The existing method of updating the web.xml works. Though I can access the web panel as well.

Thank you
