### ISSUE TITLE
Publish iOS SDK to public repo

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4537]
1. SFM
2. Pod

**Comment by USAMAWIZARD** [comment]
Used SPM for publishing the IOS SDK can include the IOS SDK in project and see all the included file but there are some dependency issues with Starscream https://github.com/ant-media/WebRTC-iOS-SDK/tree/SPM_publish

**Comment by mekya** [comment]
Duplicate https://github.com/ant-media/Ant-Media-Server/issues/5014
