### ISSUE TITLE
Webrtc in browser playback of H.265/HEVC?

### ISSUE THREAD

**Issue by biviel** [ant-media/Ant-Media-Server#4538]
I'm reading everywhere that Ant Media supports h.265 playback in webrtc, is it really supposed to work? Chrome supports playback/decode of h.265 video, does videojs-webrtc implementation of Ant Media supports it?
I see nowhere on wiki codec h.265.

https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Codecs

Thanks!

**Comment by yashtandon113** [comment]
Hello, @biviel.
Thank you for raising the issue.
Please see the following link for H265 support in Ant Media: https://antmedia.io/the-first-hevc-h265-support-in-webrtc/

Our team will investigate H265 playback support in Ant Media video.js implementation. We've already created a Git Hub issue for it, and it'll be scheduled soon. Here is the link to the issue: https://github.com/ant-media/Ant-Media-Server/issues/4515

**Comment by biviel** [comment]
hi, @yashtandon113 ,
thank you for the information! 

Could you please estimate roughly when will this videojs-webrtc be able to play h.265? Like next 1-2 months or more? 

Regards

**Comment by mekya** [comment]
hi @biviel ,

Yes, end of Jan, 2022 is the ETA. 

Closing this issue as duplicate. Please continue discussion on #4515

Thank you

Regards,
Oguz

**Comment by biviel** [comment]
hi, @mekya ,
is there any update about this? You estimated before end of January for h.265 playback in browser (chrome), any new information or estimate to share?

Thanks in advance!

BR

**Comment by mekya** [comment]
Hi @biviel,
Thank you for follow up

We've almost finished the WebRTC stack update to m108. 
So the next task is supporting the stereo input and then h265. 

I think at the end of this month we may have something.
