### ISSUE TITLE
Ant Media Chat Query

### ISSUE THREAD

**Issue by sridhard** [ant-media/Ant-Media-Server#4539]
Hi,

I have few queries on data channel feature to implement chat. We are planning to use enterprise edition.

1. When there are multiple users in a conference, the message sent by one user should be broadcasted to all. Does ant media server do this broadcast message on all channels?
2. Suppose there are 5 users in conference and they exchanged some messages. When the 6th user joins we need to show the previous history. OR suppose when the user reload a page we need to show the history. How can we do this using ant media server

thanks

**Comment by rahul7827** [comment]
Hi @sridhard 

I am an enterprise user

> When there are multiple users in a conference, the message sent by one user should be broadcasted to all. 

Yes this feature is available, In the Media Server webpanel you can change setting as well.

![image](https://user-images.githubusercontent.com/77726801/200154926-deeb2425-4bd7-4c35-a193-4bc3af6acdc6.png)

> Suppose there are 5 users in conference and they exchanged some messages. When the 6th user joins we need to show the previous history.

You can custom implement the below solution at your end.

Steps :

At publisher end when broadcast start create an array(`lets say var cstm_messages = array() `) as global variable. When any messages are sent and received push them into messages array.

When any user join the stream you will get a callback at publisher end like -> `if (info == "joinedTheRoom")` or `(info == "newStreamAvailable")`.

At this callback event you can send the `cstm_messages` along with streamId, through datachannel

```
if (info == "joinedTheRoom") {
  let msgObj = {
         sent_for:obj.streamId,
         messages:cstm_messages
  }
}
```

Now this message would be delivered to all viewers, So at the viewer end you can compare the participant's streamId with the datachannel's **sent_for** value.

// This will ensure that message appended to newly connected member chat.

```
if (info == "data_received") {
   if ( (typeof(obj.data.sent_for) !== undefined) && (this.streamId ==  obj.data.sent_for) ){
   //     loop over the obj.data.cstm_message and append into message div
   }
}
```

>  OR suppose when the user reload a page we need to show the history. How can we do this using ant media server

push each of the newly received message to cstm_messages array and save these messages in browser localStorage against the streamName (roomName) and streamId. 

So when the page is refreshed/reloaded, You can check the localStorage message and can append in your chat div.

Please let me know if this solution is helpful for you. Feel free to write back if have any issue in implementation.


Thanks

**Comment by mustafaboleken** [comment]
Thank you very much @rahul7827 for the solution. I wanted to add something to it. If you wanted to store them in your local storage, you should also consider the case of using the same stream name and stream id multiple times. Otherwise, users get messages from the old one. You can clean messages on the broadcaster side before starting a new broadcast.

**Comment by rahul7827** [comment]
Hi @mustafaboleken 

Thanks for going through my answer and providing your additional view over it. 

While considering streamName (**roomName**) and **streamId** as comparable flag, I also had thought the same as you.

But There may be possibility that, At publisher end there may be some network issue (Internet Disconnection) and stream can have **autoRepublishEnabled** enabled. Then this will delete the localStorage cstm_messages and newly joined user might not get complete chat messages.

It was my assumption that there is less probability of having the same **StreamName** and **streamId** multiple times. (I am wrong here, Even 1% of probability may be an issue for client).

Your additional solution will help @sridhard and future readers to consider this scenario as well.


There may be other possible solution to resolve this as well :

We can keep one more flag (lets say **sessionId = Math.random()** ).

When page loads we can set a random value in sessionId.

If Publisher stop streaming by clicking on **Stop Publish** button then we can update the flag sessionId by some random value  and delete cstm_message from localStorage.

For Viewers, We can also delete cstm_message from localStorage when viewer leaves the room by clicking on (lets say "Stop Playing")  button.


Now the process would be like this.

1. Index.html page reloaded for publishing
   -> Check cstm_message is in localStorage if yes, delete this. 
   -> Set random value in sessionId variable before calling initWebRTCAdaptor().
 
3. When a new viewer joins the room share cstm_message via datachannel if cstm_message is not empty.

4. Viewer will check that is there anything in localStorage for cstm_message, If yes then delete cstm_message from localStorage.
5. Update the latest cstm_message to localStorage which viewer will receive from **data_received** event.


**CUSTOM SCENARIO AT PUBLISHER END.**

At Publisher end internet disconnected and publisher kept the page ideal (Not refreshed) for many hours. 

Then starts publishing,

In this case publisher might get old meeting message, To overcome this scenario we can do this.

Solution : Before calling publish() function, Check is there cstm_message in localStorage, 

```
if(localStorage.getItem("chat_message_from_localStorage")){
   if(sessionId_from_global_var == sessionId_from_localStorage){
//      confirm("Continue with previous meeting Or start fresh meeting")
   } else {
//      delete chat_message from localStorage
   }
}
```

Also for both Publisher and Viewer clear localStorage before page unload.

```
window.onbeforeunload = function(event) {
  // clear cstm_message from localStorage 
};
```

Still there may be some issue in my solution, If anyone try to achieve @sridhard's requirement is now have a roadmap.

Thanks again @mustafaboleken.
