### ISSUE TITLE
Prevent local streams to be downloaded from AMS server

### ISSUE THREAD

**Issue by kpsarthi** [ant-media/Ant-Media-Server#4542]
Hi,

I am able to prevent my local stream from being played in a multitrack conference. But it seems I am still downloading the streams and not playing. Is there a way we can only publish my stream and not play it at all?

Thanks,

**Comment by kpsarthi** [comment]
Found following comment here https://github.com/ant-media/conference-call-application/blob/main/react/src/antmedia/webrtc_adaptor.js#L313.

`enableTracks: required if the stream is a main stream of multitrack playing. You can pass the the subtrack id list that you want to play. you can also provide a track id that you don't want to play by adding ! before the id. `

Have done same with multitrack conference, but checking the bandwidth usage it seems when only one user is in the conference then its downloading the stream from AMS. Is there any other way to not play self track and not download any streams

**Comment by mekya** [comment]
Moving to the backlog to schedule. Thank you @kpsarthi

**Comment by Mohit-3196** [comment]
Hi @kpsarthi ,
Thank for the issue. Let me check on this and I will update you about it.

Thank you

**Comment by Mohit-3196** [comment]
Hi @kpsarthi ,
I tried to reproduce the issue at my end by opening the multitrack conference and joined the room and checked the webrtc internals, opened another tab and joined again.
Afterwards when checked the internals for the player page then in the inbound rtc there is no video and audio data.

If you are available then we can also check the issue together and try to reproduce it.

Thank you

**Comment by Mohit-3196** [comment]
Hi @kpsarthi ,
How are you?

Let me know if you had any chance to check this further.

Thank you

**Comment by kpsarthi** [comment]
Sorry for the late reply, I got engaged in other tasks. I am able to resolve the issue as suggested in the documentation. The bug was on our side and we were updating the streamId and which was not added in enableTracks array.

Thanks, for you support. This ticket can be closed.

**Comment by Mohit-3196** [comment]
Hi @kpsarthi ,
That's fine :)
Thank you and have a great week.
