### ISSUE TITLE
Recording of synchronous filtered streams

### ISSUE THREAD

**Issue by fabiox23** [ant-media/Ant-Media-Server#4557]
When applying a text filter of "synchronous" type on an input stream (and using the same stream id for the output stream), the recording function seems to apply to the original (input) stream, not the filtered (output) one. I would expect the filtered stream to be recorded instead.

Ant Media Server version: Enterprise 2.5.1 on an AWS-EC2 Ubuntu 20.04 server

**Comment by fabiox23** [comment]
Hi, the issue with the inability of recording asynchronous filtered streams has become quite urgent. Is there a quick fix that I can possibly apply? Thanks again, Fabio

**Comment by mekya** [comment]
I've increased the priority. I hope we can schedule it today.

**Comment by burak-58** [comment]
Hi @fabiox23 ,
Thanks for your report.
You should execute this scenario:
1. Enable adaptive streaming
2. Create a stream
3. Apply filter in sync mode by setting type to synchronous and setting outputStrems same with the inputStreams in the Rest method like the following:

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/WebRTCAppEE/rest/v2/filters/create" -d '{"filterId":"filter1","inputStreams":["stream1"],"outputStreams":["stream1"],"videoFilter":"[in0]vflip[out0]","audioFilter":"[in0]acopy[out0]","videoEnabled":"true","audioEnabled":"true","type":"synchronous"}'`

4.  start recording
....
5. stop recording
6. delete filter
7. stop stream

At the end you will have 2 records like {stream_id}.mp4 and {stream_id}_{resolution}p{bitrate}kbps.mp4
The first record has original stream and the second has the filtered stream.

PS: There is still a video duration issue in this scenario. I have sent the PR above to fix this.

**Comment by mekya** [comment]
I've merged the PR @burak-58 .

Shall we need a test code to not encounter the same problem again?

**Comment by fabiox23** [comment]
Hi,

I have tried the steps below but the procedure doesn't work for me.

After applying the filter and starting the recording, only one recording 
is available, ie {stream_id}.mp4.

Also, after stopping the recording, removing the filter and stopping the 
stream, the {stream_id} is still listed on the user interface and the 
corresponding *.ts and *.m3u8 files are not cleared. Even after removing 
those files manually, the file {stream_id}_adaptive.m3u8 is being 
recreated automatically.

Thanks.

**Comment by burak-58** [comment]
I have created this issue for the last message.
https://github.com/ant-media/Ant-Media-Server/issues/4640
