### ISSUE TITLE
Asynchronous text filter produces a Java error in enterprise v2.5.1 - works fine in v2.4.3

### ISSUE THREAD

**Issue by fabiox23** [ant-media/Ant-Media-Server#4558]
Using a text filter on a video stream using the “asynchronous” type (and a separate output stream id) produces the following error in 2.5.1. It works fine in 2.4.3.

[{"filterId":"textoverlay","inputStreams":["streamid"],"outputStreams":["streamid2"],"videoFilter":"[in0]drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:x=w-tw-5:y=5:fontsize=24:fontcolor=yellow@0.9:box=1:boxcolor=darkblue@0.7:textfile=text.txt:reload=1[out0]","audioFilter":"[in0]acopy[out0]","type":"asynchronous","videoEnabled":true,"audioEnabled":true}]

Ant Media Server version: Enterprise 2.5.1 on an AWS-EC2 Ubuntu 20.04 server

HTTP/1.1 500 
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 5354
Date: Fri, 11 Nov 2022 18:30:04 GMT
Connection: close

<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> java.lang.NullPointerException</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: java.lang.NullPointerException
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
	io.antmedia.filter.IPFilter.doFilter(IPFilter.java:24)
	io.antmedia.filter.ContentSecurityPolicyHeaderFilter.doFilter(ContentSecurityPolicyHeaderFilter.java:32)
	io.antmedia.filter.JWTFilter.doFilter(JWTFilter.java:44)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:368)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:174)
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
	io.antmedia.muxer.MuxAdaptor.enableMp4Setting(MuxAdaptor.java:448)
	io.antmedia.muxer.MuxAdaptor.init(MuxAdaptor.java:367)
	io.antmedia.enterprise.adaptive.EncoderAdaptor.init(EncoderAdaptor.java:195)
	io.antmedia.enterprise.plugin.CustomBroadcast.start(CustomBroadcast.java:104)
	io.antmedia.filter.FilterAdaptor.startBroadcast(FilterAdaptor.java:451)
	io.antmedia.filter.FilterAdaptor.createFilter(FilterAdaptor.java:365)
	io.antmedia.plugin.FiltersManager.createFilter(FiltersManager.java:34)
	io.antmedia.rest.FilterRestService.create(FilterRestService.java:49)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:566)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1230)
	io.antmedia.filter.IPFilter.doFilter(IPFilter.java:24)
	io.antmedia.filter.ContentSecurityPolicyHeaderFilter.doFilter(ContentSecurityPolicyHeaderFilter.java:32)
	io.antmedia.filter.JWTFilter.doFilter(JWTFilter.java:44)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:368)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:174)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.82</h3></body></html>

**Comment by burak-58** [comment]
We couldn't reproduce this issue with @fabiox23
