### ISSUE TITLE
Blogpost about Kubernetes Deployment in AWS Wavelength 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4570]

**Comment by burak-58** [comment]
The CPU usage measured by the AMS seems to be higher than the OS measurement.

![image.png](https://images.zenhubusercontent.com/5b0923f8425de866b93bf244/5475232f-3c46-4a41-a49d-26927015d226)

**Comment by muratugureminoglu** [comment]
https://antmedia.io/wp-admin/post.php?post=69337&action=edit
