### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by gioragotech** [ant-media/Ant-Media-Server#4575]
### Short description
crash when trying to play conference room using Flutter SDK

### Environment

We are using the Flutter SDK example and trying to use the "play" feature.
Our server is a c5.large instance in AWS launch by the AWS marketplace: 
https://aws.amazon.com/marketplace/pp/prodview-464ritgzkzod6
No special configurations.

### Steps to reproduce
1. Create a conference room with two attendees using this link: http://{our IP address}:5080/LiveApp/conference-room.html
2.  The dashboard look like the attached image
<img width="1371" alt="Screen Shot 2022-11-08 at 11 54 51" src="https://user-images.githubusercontent.com/94448974/201904039-da2cd4bb-639c-4534-b082-c267bee13c4b.png">
3. Using the Flutter SDK example, we are trying to connect to stream "room1". using PLAY

AntMediaFlutter.connect(
  //host
  remote,
  //streamID
  "room1",
  //roomID
  '',
  AntMediaType.Play,

4. We are expecting to receive a stream with two video tracks and be able to play them
5. Instead I'm receiving just one video track like that:
flutter: stream tracks [Track(id: ARDAMSviQElOktFsfzLarKj, kind: video, label: ARDAMSviQElOktFsfzLarKj, enabled: true, muted: false)]
6. The server immediately crashes, closing all sessions and the Ant Media Dashboard.

**Comment by mustafaboleken** [comment]
Hi @gioragotech,

Unfortunately, Flutter SDK doesn't support Multitrack Playback yet. I created a feature request for it. You can wait for it or you can switch to another conference solution.
If you use http://{our IP address}:5080/LiveApp/conference.html with MCU enabled, there is a stream called room1merged and you can watch it through Flutter SDK with Play Sample.

I couldn't reproduce the server crash on my side. Could you please provide me the hs_err file and logs which are located in /usr/local/antmedia/logs ? Also, if you can reproduce it, send me the steps or we can schedule a meeting.

**Comment by gioragotech** [comment]
Hi

We will send u the logs. regarding steps to reproduce. I wrote everything in the issue. So this are the steps. if u want we can schedule a meeting

**Comment by mustafaboleken** [comment]
@gioragotech please send it directly to my personal mail address mustafa.boleken@antmedia.io

**Comment by mustafaboleken** [comment]
When I check the server logs, because of that flutter doesn't support multitrack playback feature yet, application tries to create separate peer connections with participants and it causes the crash. We can ignore it because it's caused from misusage.

**Comment by gioragotech** [comment]
@mustafaboleken it sounds to me that a client misuse causing the server to crash is something that should not be ignored. It could be used with malicious intentions.
The expected behavior should be for the client action to be blocked or ignore without crashing the server.

**Comment by asharamseervi** [comment]
Hi @gioragotech, I would like you to try Fail2ban to avoid this kind of use-case! I'm not sure, how it sits with AMS, but if it worked as desired, you may update us so we can draft it under best practices!

**Comment by mustafaboleken** [comment]
@gioragotech you are right, in the first place I asked for logs because I wanted to know if there is a bug that we didn't know about. When we start to add the multitrack feature to Flutter SDK, we will also add some mechanisms to prevent such errors.

**Comment by mustafaboleken** [comment]
Hi @gioragotech and @asharamseervi 
After we investigate the issue deeply we found that cause of this type of crashes is sdpMin value cames null for some scenarious. We will add null pointer check on server side to prevent the crash. You can track the status here  https://github.com/ant-media/Ant-Media-Server/issues/4703

**Comment by mekya** [comment]
Yes, it's added and available as a snapshot
