### ISSUE TITLE
Video stuttering on GPU instance when loaded

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#4578]
# Issue
Video is stuttering on GPU instance when it is loaded with 5-7 streams and adaptive is on.

### Environment
* Ant Media Server version: 2.5.1

### Steps to reproduce
1. Create a g4dn.2xlarge wit v2.5.1 AMI on AWS 
2. Add 2 adaptive 1080p and 720p
3. Create 5-7 RTMP streams
4. Play one of the stream

### Expected behavior
Video play smoothly.

### Actual behavior
Video is stuttering.

**Comment by yashtandon113** [comment]
@burak-58 
According to my observations, it happens with a single stream as well, and it usually happens when playing at 720p or lower resolution.

**Comment by rahul7827** [comment]
Today this happened with me also.

Instance type : g4dn.xlarge on aws having GPU
AMS v2.5.1 on AWS
Having 2 adaptive 1080p and 720p

Streaming only 2 stream, First stream is from OBS (Which having this issue).
Other stream is working fine from laptop internal camera.

Both streams are webrtc.
