### ISSUE TITLE
Can't delete broadcast in UI

### ISSUE THREAD

**Issue by sir-dunxalot** [ant-media/Ant-Media-Server#4579]
### Short description
Cannot delete broadcast in UI due to "insecure XMLHttpRequest endpoint."

### Environment

* Operating system and version: Linux version 5.11.0-1022-aws / Ubuntu 20.04.4 LTS
* Java version: 
* Ant Media Server version: Enterprise Edition 2.4.3 20220418_2241
* Browser name and version: Chrome 107.0.5304.110 (Official Build) (x86_64)

### Steps to reproduce

This bug happens sometime but not always. It could be related to #4353, which we frequently experience.

1. Log into an instance that is using HTTPS
2. Click 'Applications'
3. Click on an application with streams
4. Click on the actions dropdown for a broadcast
5. Click 'Delete broadcast'
6. The broadcast request will go out over HTTP and an error will appear in the console.

### Expected behavior
When the user clicks 'Delete broadcast' in the admin UI of our Ant Media Server instances, the broadcast should be deleted, removed from the UI immediately, and a success message should appear saying something like "Broadcast deleted."

### Actual behavior
When the user clicks 'Delete broadcast' in the admin UI of our Ant Media Server instances, the request fails. For example, clicking this button...

<img width="237" alt="image" src="https://user-images.githubusercontent.com/4495352/202206064-29bda415-f2dd-4d81-8d2e-70884624f424.png">

... Produces this error in the console...

```
Mixed Content: The page at 'https://XXXXXXXXXX.com/#/applications/LiveApp' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://XX.XX.X.XXX:5080/LiveApp/rest/v2/broadcasts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'. This request has been blocked; the content must be served over HTTPS.
```

We are able to delete the streams with the following workaround in a terminal:

```
curl --request PUT \
  --url https://origin.media.onekeyvirtualcare.com/LiveApp/rest/v2/broadcasts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX \
  --header 'Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
  --header 'Content-Type: application/json' \
  --data '{
	"status": "finished"
}'
```

### Logs
N/A. This seems to be a frontend issue.

**Comment by sir-dunxalot** [comment]
CC @ayazhussein.

**Comment by mustafaboleken** [comment]
Hi @sir-dunxalot 

There are 2 places that use other instances' IP addresses to directly send requests. One is deleting broadcast and the other is adding a stream source. We refactor both of them. After the [pull request](https://github.com/ant-media/Ant-Media-Management-Console/pull/192) merged, I can provide you a snapshot version or you can wait for the next release. We will planning to release it soon.

**Comment by sir-dunxalot** [comment]
Perfect. Thank you @mustafaboleken. We are happy to wait for the merge to be completed.

**Comment by sir-dunxalot** [comment]
Hi @mustafaboleken. I see the related PR (#192) was merged. Is the latest release likely to go out before the end of the year?

**Comment by sir-dunxalot** [comment]
Hello @mustafaboleken. Was this fix included in 2.5.3 ([here](https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.5.3))? Thanks!

**Comment by mustafaboleken** [comment]
Hi @sir-dunxalot 

Yes, it's included. Can you please test it ant give us feedback.

**Comment by sir-dunxalot** [comment]
@mustafaboleken I can confirm this issue is fixed. Thank you to you and the team for your hard work!

**Comment by mekya** [comment]
Let's have some coffee together to celebrate @sir-dunxalot @mustafaboleken :)
