### ISSUE TITLE
Unity Sample Project missing dependencies

### ISSUE THREAD

**Issue by tomyates** [ant-media/Ant-Media-Server#4585]
I'm trying to get your Unity sample up and running, and it's missing Sora dependencies. I've spent a day downloading Sora separately and trying to get a solution working but it won't.

Could you upload a Unity sample that works? Or provide instructions on how to build the necessary libraries needed to get it running. 

https://github.com/ant-media/sora-unity-sdk-samples

Thanks.

**Comment by Mohit-3196** [comment]
Hi @tomyates ,
How are you?
You can get the Unity SDK sample from drive [here](https://drive.google.com/file/d/1h3vQtGxNXplx6S47aAf4BKtRC4ww38gM/view?usp=share_link)

Alternatively you can also download the same from the downloads sections of your account at https://antmedia.io/

We have a blogpost about using the unity sample that you can refer https://antmedia.io/webrtc-streaming-in-unity/

I hope it helps.

Best Regards,
Mohit Dubey

**Comment by mekya** [comment]
We're just creating a new Unity SDK on here 
https://github.com/ant-media/WebRTC-Unity-SDK

It's ongoing work and there will be documentation #4594 for that
