### ISSUE TITLE
npm package readme typo

### ISSUE THREAD

**Issue by fedezubo** [ant-media/Ant-Media-Server#4589]
### Short description
Hey there, your StreamApp npm package contains a typo in the git repo readme. 

You say to install the package like: 
`$ npm install @antmedia/webrtc_adaptor`

but then in the example code few lines below you initialise it with
`import { WebRTCAdaptor } from '@ant-media/webrtc_adaptor';`

having the package name hyphenated results in an error and you can't use the package. Removing the hyphen from the initialisation solves the issue.

**Comment by mustafaboleken** [comment]
Hi @fedezubo 
You are right, I will fix it.

**Comment by mustafaboleken** [comment]
It's merged.
