### ISSUE TITLE
By default, the embedded player (play.html) uses the lowest bit rate in HLS.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4592]
### Short description
Even if the network bandwidth is good, the embedded player (play.html), while playing the HLS stream, plays the lowest bit rate without switching to a higher bit rate.

### Environment
* Ant Media Server version: v2.5 and above

### Steps to reproduce
1. Enable 3 different adaptive bit rates (1080p, 720p & 480p)
2. Publish the high bit rate 1080p stream
3. Try playing the HLS stream

### Expected behavior
If the bandwidth is good then player should play highest available bit rate (1080p).

### Actual behavior
The player is only playing the lowest bit rate (480p) and not switching to higher bit rate.

**Comment by SelimEmre** [comment]
Hi @yashtandon113,

Let me add some details to this issue. Choosing stream quality is related to especially network quality and system resources. I added a quality selector to embedded player for you. It will be available on SNAPSHOT versions. But you can directly add required files to your current system without upgrade process. After using latest changes, you can force the stream resolution from embedded player.

Best Regards,
Selim

**Comment by mekya** [comment]
Generally, forcing the stream solution is a workaround solution.  Let's have a better solution for automatic switch

**Comment by SelimEmre** [comment]
Hi @mekya,

Thank you for guiding me. I really appreciate you @mekya. I found a solution to this issue. But first, let me give a short brief for followers. If someone tries to use an embedded player, the player was choosing low-quality bandwidth. It's expected behavior as I understand from [videojs documentation](https://github.com/videojs/http-streaming/blob/main/docs/bitrate-switching.md).  

```
player = videojs('video-player', {
	poster: "previews/" + preview + ".png",
	liveui: true,
	liveTracker: {
	    trackingThreshold: 0
	},
	html5: {
    		vhs: {
      			limitRenditionByPlayerDimensions: false
    		}
    	}
});
```

Best Regards,
Selim
