### ISSUE TITLE
Xms parameter is ignored

### ISSUE THREAD

**Issue by Netbulae** [ant-media/Ant-Media-Server#4597]
As we have an antmedia server with plenty of RAM (156GB) we see heavy garbage collection after we get high load after a restart.
To reduce the JVM garbage collection overhead I want to set the minimum heap size to something bigger to reduce the garbage collection overhead. So I added "-Xms90g" to the systemd service. But the JVM initial heap size doesn't increase.

https://alvinalexander.com/blog/post/java/java-xmx-xms-memory-heap-size-control/

### Environment

* Operating system and version:
Centos 8.6

* Java version:
openjdk 11.0.17 2022-10-18 LTS 

* Ant Media Server version:
2.4.3

### Steps to reproduce
1. Edit the antmedia.service file and add the -Xms parameter to either the "ExecStart" or "Environment=JVM_MEMORY_OPTIONS= parameter"
2. Restart the antmedia service
3. observe the JVM heap memory size.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by yashtandon113** [comment]
Hi @Netbulae 
Thanks for creating the issue.
Let me provide you step by step instructions to change the JVM heap memory.

1. Edit /etc/systemd/system/antmedia.service file.
2. Environment=JVM_MEMORY_OPTIONS=-Xmx90g
3. sudo systemctl daemon-reload
4. sudo service antmedia restart

Please let me know if that works for you.

**Comment by Netbulae** [comment]
@yashtandon113 
Yes that is the maximum heap size, that works. But the question was about the minimum initial heap size

**Comment by mekya** [comment]
Thank you. Putting to the backlog to assign to someone in the team.

**Comment by muratugureminoglu** [comment]
Hi @Netbulae 

Sorry for the late response. 

I think the **-Xms** parameter will work for you. You can edit antmedia.service file as follows.
```
Environment=JVM_MEMORY_OPTIONS=-Xmx4g -Xms2g
```

**Comment by Netbulae** [comment]
That's what I thought but it didn't work. Swapping them around does appear to be working:
`Environment=JVM_MEMORY_OPTIONS=-Xms2g -Xmx4g`

**Comment by mekya** [comment]
Thank you for the update @Netbulae

**Comment by muratugureminoglu** [comment]
Hi @Netbulae 

Thanks for the update. Yes, it should be as you mentioned.

**Comment by mekya** [comment]
Thank you guys for your great collaboration @Netbulae @muratugureminoglu 

I owe you a coffee :) May I send you a coffee with a Starbucks gift card?  @Netbulae @muratugureminoglu 

Take care

**Comment by muratugureminoglu** [comment]
Just I want to update you. It's working as follows with **double-quote**

```
Environment=JVM_MEMORY_OPTIONS="-Xms2g -Xmx8g"
``` 

then

```
systemctl daemon-reload  && systemctl restart antmedia
```
FYI.  :rose:

**Comment by mann9211** [comment]
Hi Team,

What will be the process to increase heap memory size if we are using a container for an ant-media server.?

**Comment by muratugureminoglu** [comment]
Hi @mann9211 

I 've already answered [here](https://github.com/orgs/ant-media/discussions/5043#discussioncomment-6381714). 

Regards.
