### ISSUE TITLE
newConstraints are not correctly passed to applyContraints method in NPM package (potential solution provided)

### ISSUE THREAD

**Issue by fedezubo** [ant-media/Ant-Media-Server#4598]
### Short description
Hello, I am reporting a bug in your NPM package where the newConstraints value isn't correctly passed to the applyConstraints method.

It's a one line/one word fix that we have tested locally so it should be pretty straightforward

### Environment
Latest NPM package @antmedia/webrtc_adaptor

### Steps to reproduce
1. Install latest npm package: npm install --save @antmedia/webrtc_adaptor
2. applyContraints initially gets called by webrtc_adaptor.js on line [1541](https://github.com/ant-media/StreamApp/blob/3774d497538da2fc0b0ded48652568616f9c2797/src/main/webapp/js/webrtc_adaptor.js#L1541) and it expects two arugments (streamId, newConstraints)
3. then the applyConstraints in media_manager.js gets called but it only takes one argument
4. Only the streamId will be passed to the function, missing out the constraints supplied

### Expected behavior
The constraints should be passed to the function

### Actual behavior
The constraints aren't passed to the function

 
### Potential solution

in [media_manager.js](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/media_manager.js) change the following

on line [1360](https://github.com/ant-media/StreamApp/blob/3774d497538da2fc0b0ded48652568616f9c2797/src/main/webapp/js/media_manager.js#L1360)
change from `this.applyConstraints(newConstaints)` to --> `this.applyConstraints(streamId, newConstaints)`

on line [1367](https://github.com/ant-media/StreamApp/blob/3774d497538da2fc0b0ded48652568616f9c2797/src/main/webapp/js/media_manager.js#L1367
)
change from `applyConstraints(newConstraints)` to --> `applyConstraints(streamId, newConstraints) `

**Comment by fedezubo** [comment]
@mustafaboleken anything on this?

**Comment by mustafaboleken** [comment]
Hi @fedezubo, 
We didn't have a chance to check it yet but I noted it. I will be sure it's added to the weekly sprint tomorrow.

**Comment by fedezubo** [comment]
> Hi @fedezubo, We didn't have a chance to check it yet but I noted it. I will be sure it's added to the weekly sprint tomorrow.

Thanks a lot!

**Comment by mustafaboleken** [comment]
Hi @fedezubo 

When I check related functions, they worked as they expected. Let's schedule a meeting and discuss the problem you faced together. https://calendly.com/mustafa-boleken
