### ISSUE TITLE
Happy to pay money: SwiftUI example for iOS SDK and help integrating AntMedia SDK

### ISSUE THREAD

**Issue by tomyates** [ant-media/Ant-Media-Server#4602]
Does anyone have any of example of using the iOS SDK in SwiftUI rather than UIKit?
I'm diving head first into developing in Swift, and I'm enjoying using SwiftUI but I'm struggling to get AntMedia SDK integrated and as far as I can tell, I'll need to wrap the UIView to get it to work in SwiftUI.

I'd be happy to pay for help getting this setup.

Thanks!

**Comment by mustafaboleken** [comment]
Hi @tomyates 

I will talk with some of our community members about that. Please also share this on our community page, so it will be heard by more people. https://community.antmedia.io/

**Comment by rahul7827** [comment]
Hi @tomyates 

We have done such application for our clients earlier.
I try a sample application (publish & play only) in swift and show its video demo to you. 
If it suites your requirement, We can proceed further How it sounds ?

**Comment by tomyates** [comment]
@rahul7827 please could you contact me at hello@tomyates.co.uk
