### ISSUE TITLE
[Android SDK] Crash after multiple times of rotating

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4604]
### Short description
When testing with [Change Aspect Ratio](https://github.com/ant-media/WebRTC-Android-SDK/pull/10) pull request, after multiple times of changing rotation, screen turns black or stucks.

### Logs
dequeBufferFailed for display error = -19

**Comment by shibupanda** [comment]
Hi @mustafaboleken any update on this issue ?

**Comment by mustafaboleken** [comment]
We fixed the issue and get confirmation from the user.
