### ISSUE TITLE
Find a way to solve limit vertext issue on unity

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#461]

**Comment by ogulcan** [comment]
![example.png](https://images.zenhubusercontent.com/5b1585ca76f98d262074628d/2f20b68f-96ec-472b-b800-121dade9e8d5)

**Comment by ogulcan** [comment]
Here is the project: https://wetransfer.com/downloads/befd8de0ba8670f8d137fda4e676724720181028102539/8f2fda9763e5d45394d59fbe63d776f520181028102539/c6e86c

**Comment by ogulcan** [comment]
https://assetstore.unity.com/packages/tools/utilities/point-cloud-free-viewer-19811
