### ISSUE TITLE
Cannot import package '@antmedia/webrtc_adaptor'

### ISSUE THREAD

**Issue by huynhvansang122** [ant-media/Ant-Media-Server#4621]
### Short description
 I can't use antmedia package after install it.
 

### Environment

* Operating system and version: macos
* Ant Media Server version: 2.5.1

### Steps to reproduce
1. npm i @antmedia/webrtc_adaptor
 2. import { WebRTCAdaptor } from '@antmedia/webrtc_adaptor'

### Expected behavior
Can use package @antmedia to implement antmedia to code

### Logs
And it has error: Cannot find module '/src/main/webapp/js/webrtc_adaptor.js'. Please verify that the package.json has a valid "main" entry.

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mustafaboleken** [comment]
Hi @huynhvansang122 

We fixed the issue recently and it will be released in 2.5.2 Until that, you can use the workaround below. 

https://stackoverflow.com/questions/70950715/unable-to-import-webrtcadaptor-which-is-in-js-file-from-antmedia-package-in-node
