### ISSUE TITLE
WebRTC Publisher draws couldn't reach the WebRTC players

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#4622]
### Short description
WebRTC Publisher draws couldn't reach the WebRTC players. 

### Steps to reproduce
1. Enable  `WebRTC Data Channel - Publisher and all Players`
2. Go WebRTC Whiteboard Publish page and start streaming
3. Open WebRTC Whiteboard Player page and start streaming
4. Draws something on Publisher page.
5. You won't see your draw on Player page. 

### Expected behavior
WebRTC Publisher draws should be on WebRTC Player page.

### Actual behavior
There is no draw on WebRTC player page.

### Logs
There is no error log.  Ant Media Server v2.5.1

**Comment by rahul7827** [comment]
@SelimEmre  I solved this by commenting this feature in my meeting application. 😄 
Thanks for creating this issue, which helped me to check this feature in my application.

**Comment by SelimEmre** [comment]
Hi @rahul7827,

Just wanted to update here. I have added a fix to the enterprise edition code base. It's merged now. It's available in SNAPSHOT versions.

Best Regards,
Selim
