### ISSUE TITLE
Store .ts information into MogoDB for HLS VoD

### ISSUE THREAD

**Issue by oleul05** [ant-media/Ant-Media-Server#4623]
We are looking for a solution with ANT Media Server for HLS Live and VoD playlist (chunked playlist).
For this we need the .ts file information. Is it possible to save the .ts information inside mongoDB when the .ts files are generated?
The information required are: streamId, filename, creationTime.

**Comment by burak-58** [comment]
Hi @oleul05,
If we create such an HLSListener Interface which has such a chunkFileGenerated method to notify the plugins, does it work for you?

**Comment by oleul05** [comment]
Hello @burak-58,
Thank you. Yes it will work for me. But I really appreciate if Ant Media Team save .ts information into MongDb for HLS VoD.

**Comment by burak-58** [comment]
Hi @oleul05 ,
I have checked how we can inform plugins as chucks created. The best way to do that is as @mekya told here:
https://community.antmedia.io/topic/1333-quick-instructions-how-to-push-hls-content-to-a-http-endpoint/#comment-4820

You can create an http endpoint in the plugin and use this feature.

**Comment by oleul05** [comment]
Hello @burak-58 ,
Thank you for your response. I have checked the above configuration but it is not working in my case. I am uploading the files into Wasabi (S3 compaitable). Maybe that is not http endpoint.
And one more things that I need to save the .ts files information into MongoDB which is also missing in the above documentation.

**Comment by mekya** [comment]
Thank you @oleul05 for your response. 

I'm moving to the backlog for your attention @burak-58

**Comment by burak-58** [comment]
Hi @@oleul05,
Can you look at [this discussion](https://stackoverflow.com/questions/14692353/executing-a-bash-script-upon-file-creation). You may create a script that is run when a new ts file is generated. Then you can consume the file as you want.

**Comment by oleul05** [comment]
Hello @burak-58, We prefer not to utilize scripts for this task. Is it possible to explore alternative solutions such as plugins, as we previously discussed in the meeting?

**Comment by burak-58** [comment]
Hi @oleul05,
I will discuss the possible solution with the team and create an issue.

**Comment by oleul05** [comment]
Hello @burak-58,
Please discuss and let me know when you have an update.

**Comment by burak-58** [comment]
As we discussed @oleul05 , the solution for #5082 will be a useful solution for your case also.
