### ISSUE TITLE
[IOS SDK] ITMS-90338: Non-public API usage - WebRTC.framework

### ISSUE THREAD

**Issue by denmorgenshtern** [ant-media/Ant-Media-Server#4639]
The iOS application build with latest master WebRTC.framework and WebRTCiOSSDK.xcframework is rejected by Apple with the message:

_ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/WebRTC.framework/WebRTC: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/_

I see you using m107 WebRTC Stack. This problem was resolved in m180: 
https://bugs.chromium.org/p/webrtc/issues/detail?id=14604#c1

Older WebRTC versions don't work with latest WebRTCiOSSDK.xcframework.

Please, update WebRTC.framework :)

**Comment by mekya** [comment]
Thank you @denmorgenshtern :)

**Comment by mekya** [comment]
Hey @denmorgenshtern ,

WebRTC.xcframework is updated in this PR -> https://github.com/ant-media/WebRTC-iOS-SDK/pull/13

Do you have some chance to check?

Regards,
Oguz

**Comment by denmorgenshtern** [comment]
Yep, made successful release today 🤘
Thank you @mekya @mustafaboleken

**Comment by mekya** [comment]
Thank you @denmorgenshtern .

Let us know if we can help anything for you ;)
