### ISSUE TITLE
No adaptive MP4 recording for RTMP stream in case of on the fly record starting

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#4640]
When we have an RTMP stream and adaptive settings enabled, MP4 recording disabled, if I start recording on the fly MP4 recording only one MP4 is created for the original stream. No records are created for adaptive settings.

### Environment
* Ant Media Server version: 2.5.1

### Steps to reproduce
1. Enabled adaptive settings, disable MP4 recording.
2. Start RTMP stream
3. Start recording on the fly
4. Stop Recording

### Expected behavior
There should be MP4 recordings for original stream and each adaptive settings.

### Actual behavior
There is only one MP4 recording for original stream.
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
hi @burak-58 ,

This is the expected behaviour. What makes you think that this is an urgent issue?

**Comment by asharamseervi** [comment]
> This is the expected behaviour.

I agree with @mekya !!
