### ISSUE TITLE
Stereo implementation

### ISSUE THREAD

**Issue by stephenanning** [ant-media/Ant-Media-Server#4642]
Hi there,

I'm looking to pay someone to build the stereo implementation of Ant Media. I'm broadcasting from the web and listening on both iOS and Android devices. stephenanning@gmail.com is me, please let me know your thoughts on hours and difficulty. Unrelated, how further difficult to reduce the packet size from 10ms to 3ms to better suit audio-only (less important). Thanks

**Comment by stephenanning** [comment]
Hi Burak, here's the github issue about Stereo for AMS. Thanks

**Comment by mekya** [comment]
Thank you @stephenanning ,

Currently this is the thing that we're going to focus with this issue #3076

**Comment by mekya** [comment]
There is a snapshot to try here 
https://drive.google.com/file/d/1f8DfYvc3K1crTjB-W6Vv7RYjSqRs4hhY/view?usp=drive_link
