### ISSUE TITLE
Installer script fails with an unclear message if Java is not preinstalled

### ISSUE THREAD

**Issue by jantekb** [ant-media/Ant-Media-Server#4648]
### Short description

Fresh installed an Ubuntu 20.04 and started to follow the installation guide. Downloaded the installer script and it fails fast:

```
ubuntu@ip-172-31-46-70:~$ sudo ./install_ant-media-server.sh -i ant-media-server-enterprise-2.5.1-20221030_1635.zip
readlink: missing operand
Try 'readlink --help' for more information.
We are supporting Ubuntu 18.04, Ubuntu 20.04, Centos 8, Rocky Linux 8 and AlmaLinux 8
ubuntu@ip-172-31-46-70:~$ DEFAULT_JAVA="$(readlink -f $(which java) | rev | cut -d "/" -f3- | rev)"
readlink: missing operand
Try 'readlink --help' for more information.
ubuntu@ip-172-31-46-70:~$ which java
ubuntu@ip-172-31-46-70:~$
```

### Environment

* Operating system and version: Ubuntu 20.04
* Java version:  not installed
* Ant Media Server version: 2.5.1
* Browser name and version: n/a

### Steps to reproduce
1.  See above

### Expected behavior

The installer should detect missing java and provide a helpful error message. The documentation should also point out installing java as a prerequisite, preferably giving some guidance on the Java versions and different builds available nowadays, as people can get a bit confused by the broad Java palette available.

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by jantekb** [comment]
Looks like the installer assumes the responsibility of installing java at a later stage, so in that case the expected behaviour could be that:
* if no java is installed, install the required one
* if the right java version is installed, do nothing
* if a newer java version is installed, that raises questions, as I am not sure if java versions above 11 are supported or not, but some people might want to use the latest possible version that works

**Comment by jantekb** [comment]
I was on 22.04, not 20.04. On 20.04 the error `readlink: missing operand` still appears, but the installation continues as expected. On 22.04 I misinterpreted the output and I thought that the readlink error causes the script to stop, but it was the wrong OS version really. My bad.

**Comment by vicheanath** [comment]
i also have this problem too

**Comment by mekya** [comment]
Thank you for the updates. Support for 22.04 is coming. 

@vicheanath if you still have this issue, please ask to the https://community.antmedia.io . 
Not only community members but also guys from Ant Media will write responses there.
