### ISSUE TITLE
Long session recordings fail to be uploaded to cloud storage. [Needs Confirming]

### ISSUE THREAD

**Issue by D3ST1N3D** [ant-media/Ant-Media-Server#4649]
### Short description
Antmedia server is configured simucast to Cloudflare. Tests of around 2 to 5 hours were successfully uploaded to Cloudflare by the system. An event of around 8 to 12 hours however was not uploaded to the Cloudflare side even though the antmedia panel shows a Cloudflare link for the video. If it was a RTMP connection error there would have been a piece of the session stored.

We have a cluster setup over the azure cloud and I checked the origin instance error logs for the date of the event and a piece of the logs found on the server are attached.

### Environment
* Operating system and version: Linux 
* Ant Media Server version: Enterprise Edition 2.5.1 20221030_1635

### Steps to reproduce
1. Have a room with a session of about 12 hours
2. Simucast the recording to Cloudflare 

### Expected behavior
The video will be successfully uploaded to the cloud system and stored there at the link shown on the antmedia panel.

### Actual behavior
The video link is shown on the antmedia panel yet is not present on the Cloudflare panel.

### Logs
[antmedia-origin-error-log.log](https://github.com/ant-media/Ant-Media-Server/files/10192963/antmedia-origin-error-log.log)

**Comment by mekya** [comment]
It's a good point @D3ST1N3D. Thank you. 

@SelimEmre, please let us know if you have any update for this issue.

**Comment by D3ST1N3D** [comment]
[origin-rtmp-server.log](https://github.com/ant-media/Ant-Media-Server/files/10258425/origin-rtmp-server.log)
I am adding server logs from the RTMP origin instance while trying to broadcast on the room with a simulcasting issue/
Hope they help in the investigation.

**Comment by SelimEmre** [comment]
Hi guys,

Thanks for these details. First, it was a bit not clear to me. I set a meeting regarding this issue. Here is the latest status of this issue. They are sending streams to the Cloudflare endpoint. It was working with the same RTMP endpoint with different stream IDs. I'm assuming that somehow RTMP endpoint status is stuck on an error. I'm still trying to reproduce this issue on my end.

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi guys,

I checked this issue with @D3ST1N3D. It seems that there is a problem with Cloudflare endpoint. It's working with the new Cloudflare RTMP Endpoint. 

Best Regards,
Selim
