### ISSUE TITLE
Facing errors on updating WebRTC.xcframework and WebRTCiOSSDK.xcframework after OS update (iOS)

### ISSUE THREAD

**Issue by tejasjuware** [ant-media/Ant-Media-Server#4661]
Hi, recently we updated mac OS to Ventura, and needed to upgrade xcode to 14.1, so got compilation errors for  WebRTC library.
As per your documentation provided by support https://resources.antmedia.io/docs/ios-sdk, 

followed this steps : 
step 1 : Downloaded AntMediaReferenceApplication Xcode project from https://github.com/ant-media/WebRTC-iOS-SDK and unzipped it 

Step 2 : Did change minimum deployment target for our Xcode project's target to 10.0

Step 3 : Did pod install in in WebRTCiOSReferenceProject directory

Step 4 : disabled bitcode in our Xcode project

Step 5 : Did run ./export_xc_framework.sh in WebRTCiOSReferenceProject directory

Step 6 : Copied WebRTC.xcframework and WebRTCiOSSDK.xcframework from WebRTCiOSReferenceProject to our project and changed to Embed & Sign, after that facing this errors

<img width="426" alt="Screenshot 2022-12-12 at 12 19 42 PM" src="https://user-images.githubusercontent.com/120358523/206979391-76920f84-2579-46e7-ad16-76f4878edd2c.png">

**Comment by tejasjuware** [comment]
More Information : 
<img width="783" alt="Screenshot 2022-12-12 at 12 45 50 PM" src="https://user-images.githubusercontent.com/120358523/206983920-ceac5a7d-f1dc-4f35-822e-f39f7c2bc439.png">

**Comment by mustafaboleken** [comment]
Hi @tejasjuware,

We recently update the WebRTC version and add arm64 emulator support. Could you please remove arm64 from excluded architectures and try again.

**Comment by tejasjuware** [comment]
<img width="418" alt="Screenshot 2022-12-12 at 3 07 58 PM" src="https://user-images.githubusercontent.com/120358523/207012071-8401a08d-8882-421a-a8e7-8ed91a24df5c.png">

Hello, issue still persists.

**Comment by mustafaboleken** [comment]
@tejasjuware let's schedule a meeting and check it together. https://calendly.com/mustafa-boleken

**Comment by tejasjuware** [comment]
<img width="528" alt="Screenshot 2022-12-12 at 3 26 40 PM" src="https://user-images.githubusercontent.com/120358523/207016076-13b60e28-3e18-442b-a6ff-7a7f9c982c95.png">

why is it blue? is it some mistake?

**Comment by mekya** [comment]
Hey Guys,
There is a new update in iOS SDK and it's being started to distribute as SPM package. 

Check this PR
https://github.com/ant-media/WebRTC-iOS-SDK/pull/20

**Comment by mekya** [comment]
Closing this issue for now. Pleaes feel free to re-open if it does not work for you.
