### ISSUE TITLE
[iOS] Audio issue during publishing on safari

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4662]
### Short description
There is no audio when publishing on safari.

### Environment

* Device: iPhone 7 iOS 15.7.1 Safari
* Ant Media Server version: 2.5.1
* Browser name: Safari

### Steps to reproduce
1. Open sample publishing page
2. Start publishing
3. Try to play on any device

### Expected behavior
Audio is also transmitted.

### Actual behavior
Viewer cannot listed audio.

**Comment by mekya** [comment]
In my test last week, I could reproduce the problem on iPhone 7 iOS 15.7.1 Safari. But I've just tested this scenario again, it's working for me at this time. Let's confirm the case with the user.
