### ISSUE TITLE
Edit Playlist Should Have Scroll Functionality

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#4670]
### Short description
Adding new items causes popup window to stuck since there is no scroll thus no new items can be added

### Steps to reproduce
1. add new playlist
2. click edit playlist
3. add many playlist urls until window cannot be scrolled.

### Expected behavior
there should be a scroll functionality on edit playlist popup

### Actual behavior
edit playlist popup cannot be scrolled thus no more new items can be added.

 
![Management of Ant Media Server - Google Chrome 12_17_2022 12_59_02 PM](https://user-images.githubusercontent.com/24750845/208384172-a945a6bd-f3f3-4609-bbd4-e10f17bee381.jpg)

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by SelimEmre** [comment]
Hi @lastpeony,

I have checked this PR. Yes, it's acceptable for functionality. But I think it's not good for UX standards. Please check my comments on the image.

<img width="636" alt="UX-changes" src="https://user-images.githubusercontent.com/9084130/211192857-6c3ce7b6-29b8-4877-899b-e9c4657b334d.png">

Best Regards,
Selim

**Comment by lastpeony** [comment]
> Hi @lastpeony,
> 
> I have checked this PR. Thank you @lastpeony. Development works as expected. But I think it's not good for UX standards. Please check my comments on the image.
> 
> <img alt="UX-changes" width="636" src="https://user-images.githubusercontent.com/9084130/211192857-6c3ce7b6-29b8-4877-899b-e9c4657b334d.png">
> 
> Best Regards, Selim

Fixed. Thank you for the review.
