### ISSUE TITLE
Add Type Definitions for JavaScript SDK & Improve Documentation

### ISSUE THREAD

**Issue by gyenabubakar** [ant-media/Ant-Media-Server#4677]
**Is your feature request related to a problem? Please describe.**

The lack of type definitions for `@antmedia/webrtc_adaptor` makes it hard to understand and use. In your documentation, you didn't even mention all the events that could be triggered.

**Describe the solution you'd like**

Provide type definitions for:

- all the event names
- the data that comes with all events.
- the options passed to the `WebRTCAdaptor` constructor.
- all the possible error types.

**Describe alternatives you've considered**

For now, I'm defining my own types but I'm doing this based on the logs I see in the developer console. There may be more so it's better you guys do this since you know more about the library.

**Additional context**

<img width="989" alt="Screenshot 2022-12-19 at 7 53 49 PM" src="https://user-images.githubusercontent.com/26672526/208508805-700ddd68-ebb8-451f-8be4-dd2bdd54a634.png">

**Comment by mustafaboleken** [comment]
Hi @gyenabubakar,

Thank you very much for your feedback. You are right. Actually, we are working on this right now. You can check the progress below.

https://github.com/ant-media/Ant-Media-Server/issues/4676
https://github.com/ant-media/Ant-Media-Server/issues/4526
