### ISSUE TITLE
Smooth Transition between Speakers in Conference Call

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4678]
Steps
1. Send three streams(speakers) to the Ant Media Server programmatically
2. Create a conference call programmatically 
3. Join the conference call via PortMeet - attendee
4. Add/Remove these three streams to the conference call programmatically

Expected to see:
Attendee 3 will see that speakers are added/removed to the conference call smoothly

**Comment by mustafaboleken** [comment]
We make a demonstration to the user and get confirmation.

**Comment by mekya** [comment]
hi @mustafaboleken,
Thank you. 

Is there any know-how that we can share or some developments we can merge?

I'm asking because if we encounter the same problem again, we should not need to invent the wheel again.

**Comment by mustafaboleken** [comment]
Hi @mekya 
This task is a unique scenario for the user but we can use this know-how to implement the breakout rooms feature.
It's a pretty standardised feature which Google Meet and Zoom have and we can add it.

**Comment by mekya** [comment]
That's really a good feature to have breakout rooms. 

Do we have some kind of branch in the project and simple instructions to proceed for breakout rooms?

**Comment by mustafaboleken** [comment]
[The feature request](https://github.com/ant-media/conference-call-application/issues/92) is created and the feature that I implemented can be seen by https://github.com/ant-media/conference-call-application/tree/amy branch.
