### ISSUE TITLE
RTMP Live stream stops after buffer underflow exception occurs

### ISSUE THREAD

**Issue by andreashermann** [ant-media/Ant-Media-Server#4681]
### Short description
We are using AntMedia from AWS Marketplace (GPU accelerated) with adaptive bitrate encoding in combination with a venue encoder from SimplyLive.
On one server we are receiving eight concurrent live streams over RTMP.

In our production environment we encountered that suddenly all the live streams of one server stopped after a few hours.
We were able to reproduce it in our test environment today after approximately five hours of live stream.

The vendor of the encoder, SimplyLive, claims that AntMedia sent a connection termination according to their logs.

We found this exception in the log (repeated)
> 2022-12-16 14:06:49,957 [NioProcessor-2] WARN  o.r.s.n.r.codec.RTMPProtocolDecoder - Failed to decodeBuffer
> 2022-12-16 14:06:49,958 [NioProcessor-2] WARN  o.r.s.n.r.codec.RTMPProtocolDecoder - Closing connection because decoding failed: RTMPMinaConnection from 46.140.244.** (in: 12963358810 out: 65397) session: 2YZDOBHOZ1G7W state: connected
> org.red5.server.net.protocol.ProtocolException: Error during decoding
> at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decode(RTMPProtocolDecoder.java:204)
> ...
> Caused by: java.nio.BufferUnderflowException: null
> ... 22 common frames omitted

If there is no way AntMedia can continue after such a decoding error we need to be able to provide details to the vendor of the encoder.

### Environment

* Operating system and version: Ubuntu 20.04.5 LTS
* Java version: Bundled Openjdk 11.0.6
* Ant Media Server version: AntMedia-AWS-Marketplace-GPU-EE-v243 (2.4.3 20220418_2241)
* AWS EC2 instance type g4dn.2xlarge

### Steps to reproduce
1. Run server for several hours with live stream over RTMP from SimplyLive

### Expected behavior
The server should not stop live streams if a recoverable RTMP decoding error occurs.

### Actual behavior
Server closes RTMP connection after decoding error.

### Logs
Complete log file: [2022-12-16-ant-media-server.log.txt](https://github.com/ant-media/Ant-Media-Server/files/10279600/2022-12-16-ant-media-server.log.txt)

**Comment by umtcylmz** [comment]
@umtcylmz

**Comment by mekya** [comment]
Thank you for the issue @andreashermann . Putting to the backlog to schedule

**Comment by mustafaboleken** [comment]
We meet yesterday and check logs, cpu, gpu and ram values. Values are look fine. The reason is not hardware related bottleneck.

**Comment by mekya** [comment]
Hi @andreashermann,

Did you have a chance to take a look at if it's working for you?

I'm closing this issue. Please feel free to re-open if it still don't work for you

Regards
Oguz
