### ISSUE TITLE
Release npm 2.5.1 and 2.5.2

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4687]

**Comment by mekya** [comment]
Hi @mustafaboleken ,

I don't understand what this issue is about?

If you mention publishing the JS sdk to the npmjs.com, there is a github action doing that automatically

**Comment by mustafaboleken** [comment]
Hi @mekya 

3 days ago one of the user says that why 2.5.1 is not released, my web app still has 2.4.3 and I create this issue. I forget that it's automatic. My mistake. I closed it right now.
