### ISSUE TITLE
OBS with ant-media-Server

### ISSUE THREAD

**Issue by AhmedKn** [ant-media/Ant-Media-Server#4689]
Hello,
I want to build live streaming platform like twitch.tv concept one to many with a sharing token using obs (Node js).
Thanks

**Comment by mekya** [comment]
Hi @AhmedKn ,

Thank you. The issues is mostly about bugs/feature requests for Ant Media Server. If you are requesting a feature request, could you please explain further what you need in technical perspective?
If you are just asking a question, it's better to ask https://community.antmedia.io or solutions guy at contact@antmedia.io

**Comment by AhmedKn** [comment]
Thanks
