### ISSUE TITLE
How can I share desktop from Screen share extension？

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#469]
# Issue
How can I share desktop from Screen share extension？

Is there any library for Screen share extension that I can use?
Or some tutorial can help me work with Screen share extension？

**Comment by mekya** [comment]
Hi,

Yeah there is an extension for that we have just developed. It's blog post is ready and waiting for to be published on blog. Maybe I can share in advance as well. 

Anyway,  chrome extension is here -> https://chrome.google.com/webstore/detail/ant-media-server-screen-s/jaefaokkgpkkjijgddghhcncipkebpnb

Regards,
A. Oguz

**Comment by arnoldcui** [comment]
Thanks a lot,I've already installed the extension,but I don't know how to driver it.

**Comment by mekya** [comment]
Let me share the guide on wiki.

**Comment by arnoldcui** [comment]
I have read `content-script.js` in `Chrome-Screen-Capture-Extension`.
I found `event.data` in code. But through CustomEvent,I can't achieve `data` field but can achieve `detail`.
How can I send an event with data field?Or there any problem?
https://developer.mozilla.org/zh-CN/docs/Web/API/CustomEvent

**Comment by mekya** [comment]
Please check this out
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Screen-Sharing

You may need to get update from WebRTCApp or WebRTCApp4Enterprise repo according to your version. 

Which version do you use community or enterprise?

**Comment by arnoldcui** [comment]
Hi ,I meet another question.Now I can switch camera between screen-share.
If I unplug the camera, It won't work.
How can I do,If I just want screen-share without camera?
