### ISSUE TITLE
[iOS SDK] Investigate the conference application problem 

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4691]
### Short description
When trying to use the conference application with iOS Sample App and conference.html with MCU enabled, cannot join properly on the iOS application.

### Environment

* Server: Azure Marketplace
* Ant Media Server version: 2.5.1
* Device iPhone XR 15.3.1

1. On the old iOS SDK, after pressing the join button, on the AMS dashboard stream is created and says preparing the stream for a couple of seconds, but then it failed.
2. After the M108 update, it couldn't even create the stream.

**Comment by mustafaboleken** [comment]
I tested the problem with the latest snapshot and 2.5.1 but couldn't reproduce it on iPhone 13 16.2 
When we meet with Srinivas, we reproduce it on his device with 2.5.1 but couldn't reproduce it on my server with the latest snapshot. Also, we tested with VP8 and H2.64 encoders but nothing is changed.
We should investigate more to determine what is the real problem.

**Comment by mekya** [comment]
iOS SDK works with `multitrack-conference.html` because `conference.html` is deprecated. So I'm closing this issue, please feel free to open it if you have any issues.
