### ISSUE TITLE
start.sh: no such file or directory

### ISSUE THREAD

**Issue by kamit-transient** [ant-media/Ant-Media-Server#4709]
### Short description

I am trying to install ant-media using the latest docker-compose file as suggested in the [official guide here](https://resources.antmedia.io/docs/docker-and-docker-compose-installation). Still, somehow I am getting the below error when running `docker-compose up -d` after the docker-compose build.

Here is the log:

```
Recreating 03dc0b0522f3_antmedia ... error

ERROR: for 03dc0b0522f3_antmedia  Cannot start service antmedia: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/antmedia/start.sh": stat /usr/local/antmedia/start.sh: no such file or directory: unknown

ERROR: for antmedia  Cannot start service antmedia: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/antmedia/start.sh": stat /usr/local/antmedia/start.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

```
To reproduce it just follow the official guide with latest 2.5.1/0 version of antmedia.

**Comment by muratugureminoglu** [comment]
Hi @kamit-transient 

Could you please share the steps ? I need to know your steps.

I tried as follows and I was able to access Ant Media Server without any problems.
```
mkdir docker
cd docker/
wget https://raw.githubusercontent.com/ant-media/Scripts/master/docker/docker-compose.yml
wget https://raw.githubusercontent.com/ant-media/Scripts/master/docker/Dockerfile_Process -O Dockerfile
cp ~/Downloads/ant-media-server-enterprise-2.5.1-20221030_1635.zip ~/docker/
docker-compose build --build-arg AntMediaServer=ant-media-server-enterprise-2.5.1-20221030_1635.zip
docker-compose up -d
```

**Comment by mekya** [comment]
I'm closing this issue for the inactivity. Please feel free to re-open if you still have this problem.
