### ISSUE TITLE
Update documentation and blog post about new auto ssl installation - enable_ssl.sh 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4714]

**Comment by muratugureminoglu** [comment]
https://resources.antmedia.io/docs/setting-up-ssl

**Comment by muratugureminoglu** [comment]
https://antmedia.io/wp-admin/post.php?post=70627&action=edit

**Comment by timantmedia** [comment]
Does this blog post need a review @muratugureminoglu ?I see it has not title yet? Should this still be in in-progress?

**Comment by mekya** [comment]
Gentle reminder for @muratugureminoglu

**Comment by timantmedia** [comment]
great @muratugureminoglu ! I guess we can close this issue.

**Comment by mekya** [comment]
Shall we publish this info in the new documentation?

**Comment by muratugureminoglu** [comment]
@timantmedia 

Both are the same. You did not miss anything.
