### ISSUE TITLE
How to push desktop sharing only without camera

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#472]
# Issue

Hi ,I meet a question.Now I can switch camera between screen-share.
If I unplug the camera, It won't work.
How can I do,If I just want screen-share without camera?

**Comment by azhali** [comment]
Hi, is there any update on this? We have exact same scenario where we only want to do the screen share

**Comment by arnoldcui** [comment]
> Hi, is there any update on this? We have exact same scenario where we only want to do the screen share

yeah,I have write an Adaptor,But I just can sent a stream with video tracks and audio tracks both.
In antMedia's demo,It can only send stream with video tracks.
I am trying to figure out why this is happening.

**Comment by arnoldcui** [comment]
> > Hi, is there any update on this? We have exact same scenario where we only want to do the screen share
> 
> yeah,I have write an Adaptor,But I just can sent a stream with video tracks and audio tracks both.
> In antMedia's demo,It can only send stream with video tracks.
> I am trying to figure out why this is happening.

Update ,I find two track after publish,with antmedia library.so I guess,stream may modify somewhere.so, I try just get desktop captrue,and add mic track,then publish it.

**Comment by mekya** [comment]
Hi Guys,
I was assigned this issue earlier this week but do not have chance to reply. Sorry for this. 

In latest 1.5.2 - SNAPSHOT, we provide screen share feature as [documented here](https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-Screen-Sharing) and 1.5.2-SNAPSHOT is [available on sonatype](https://oss.sonatype.org/#nexus-search;gav~io.antmedia~ant-media-server~~~~kw,versionexpand) . (1.6.0 branch is not merged with 1.5.2-SNAPSHOT branch yet)

For capturing screen share at first you can take a look [at this code](https://github.com/ant-media/WebRTCApp4Enterprise/blob/master/src/main/webapp/extension.html). 

Does the sample above provide a solution for your case? If not, please let me know

**Comment by azhali** [comment]
@mekya Need an example where you only have screen share option. E.g if there is no camera installed then user should be able to do the screen share and stream one of the screens. Any example of doing that is what I would need. Most of our users will not have camera installed

**Comment by mekya** [comment]
Hi @azhali ,

Yeah you're right.  Can you try this code?

https://github.com/ant-media/WebRTCApp4Enterprise/blob/master/src/main/webapp/extension.html

The code above will ask the user for screen sharing permission. Could you please check this out and let us know if it's working for you?

Regards,
