### ISSUE TITLE
Can't able to run - ios

### ISSUE THREAD

**Issue by tiwariammit** [ant-media/Ant-Media-Server#4720]
### Short description
__Brief description of what happened__
Hi there,
I follow [this tutorial](https://resources.antmedia.io/docs/ios-sdk) to integrate SDK. I installed pod 'Starscream', '~> 4.0.4'.
Then, I copied WebRTC.xcframework and WebRTCiOSSDK.xcframework. After adding, I got a crash while running apps. 
Error is 

"dyld[13453]: Symbol not found: _$s10Starscream14WebSocketEventO12disconnectedyACSS_s6UInt16VtcACmFWC
  Referenced from: <6C5D435F-E789-3518-8FB8-C4E9FD6D5D0A> /Users/amrittiwari/Library/Developer/Xcode/DerivedData/iosTest-habrwjczjhlhsidwgqvrlrmnwxwa/Build/Products/Debug-iphonesimulator/WebRTCiOSSDK.framework/WebRTCiOSSDK
  Expected in:     <02B39DC9-C210-3A32-B1F4-C8885DB25A3B> /Users/amrittiwari/Library/Developer/CoreSimulator/Devices/A5CAF1CE-DD6E-4900-8199-B0EE0FB8285A/data/Containers/Bundle/Application/6C83F4E3-FD15-4C97-AF14-165E1BDEC29A/iosTest.app/Frameworks/Starscream.framework/Starscream
Symbol not found: _$s10Starscream14WebSocketEventO12disconnectedyACSS_s6UInt16VtcACmFWC
  Referenced from: <6C5D435F-E789-3518-8FB8-C4E9FD6D5D0A> /Users/amrittiwari/Library/Developer/Xcode/DerivedData/iosTest-habrwjczjhlhsidwgqvrlrmnwxwa/Build/Products/Debug-iphonesimulator/WebRTCiOSSDK.framework/WebRTCiOSSDK
  Expected in:     <02B39DC9-C210-3A32-B1F4-C8885DB25A3B> /Users/amrittiwari/Library/Developer/CoreSimulator/Devices/A5CAF1CE-DD6E-4900-8199-B0EE0FB8285A/data/Containers/Bundle/Application/6C83F4E3-FD15-4C97-AF14-165E1BDEC29A/iosTest.app/Frameworks/Starscream.framework/Starscream
dyld config: DYLD_SHARED_CACHE_DIR=/Users/amrittiwari/Library/Developer/CoreSimulator/Caches/dyld/21G115/com.apple.CoreSimulator.SimRuntime.iOS-16-1.20B72 DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/amrittiwari/Library/Developer/Xcode/DerivedData/iosTest-habrwjczjhlhsidwgqvrlrmnwxwa/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/amrittiwari/Library/Developer/Xcode/DerivedData/iosTest-habrwjczjhlhsidwgqvrlrmnwxwa/Build/Products/Debug-iphonesimulator DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib"

Can't able to understand what the issue is. Please help me to solve this. Thank you
### Environment

xcode version 14.1 (14B47b)
Minimum Deployment version = 14.0
Xcode 13.0- compatible.

**Comment by mekya** [comment]
Thank you @tiwariammit
