### ISSUE TITLE
Bitmovin Analytics Integration to AMS

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#4725]

**Comment by USAMAWIZARD** [comment]
Added options for sending the protocol which is used to play the stream and the customer id through which one can identify the behavior of individual user

**Comment by mekya** [comment]
Please write the features which you're checking @USAMAWIZARD

**Comment by USAMAWIZARD** [comment]
@Alper KIZILTOPRAK

Inbound - Ingest
must have
stream name / start / end time / duration :white_tick:
video codec
audio codec
video size (width and height)
FPS
Nice to have
total bitrate (bits per second)
video bitrate (bits per second)
audio bitrate (bits per second)
Outbound - Egress
Total Viewers - Bitrate consumption - Protocol Usage
viewers / start / end time / duration :white_tick:
video codec
audio codec
video size (width and height)
FPS
total bitrate (bits per second)
video bitrate (bits per second)
audio bitrate (bits per second)
Protocol :white_tick:
Browser :white_tick:
Device :white_tick:
Player :white_tick:
Umut Can Yılmaz

Country info that viewers attend from :white_tick:
Which part of the stream, viewer left the stream
Total number of unique participants :white_tick:
Gender info may be
What kind of device do they use :white_tick:
Wifi or cellular ?
@Yash Tandon

Incoming stream video and audio bit rates (In any of the stream like RTMP, WEBRTC, SRT etc)   (Iska bhi ek stream info krke rest method hai pr webrtc me problem krta hai, sirf initial resolution bitrate show krta hai. In case beech me change hua to update nhi hota)
Number of live viewers on a particular stream and historical data as well
client side stats like IP, how much bit rate client is getting (iska bhi ek client side stats krke rest api hai pr usme values seedhi seedhi show nhi hoti)
upto how much time one client watched the particular stream
Total viewers count like WebRTC viewers, HLS viewers, dash viewers (iska Rest API hai )

**Comment by USAMAWIZARD** [comment]
I have updated the comment here

**Comment by USAMAWIZARD** [comment]
<table class="tg" style="undefined;table-layout: fixed; width: 751px">
<colgroup>
<col style="width: 311px">
<col style="width: 63px">
<col style="width: 92px">
<col style="width: 54px">
<col style="width: 231px">
</colgroup>
<tbody>
  <tr>
    <td class="tg-zahu">Features</td>
    <td class="tg-zahu">HLS</td>
    <td class="tg-zahu">WEBRTC</td>
    <td class="tg-zahu">Dash</td>
    <td class="tg-0pky">DYNAMIC UPDATE</td>
  </tr>
  <tr>
    <td class="tg-0pky">stream name</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">start time</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">end time</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">video size</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">FPS</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">Audio Bitrate</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">❌</td>
    <td class="tg-zahu">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">Video Bitrate</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">❌</td>
    <td class="tg-zahu">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">Total Viewers</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Protocol</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">video codec</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">audio codec</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">Browser</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Device</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Player</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Country</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">unique participants</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">User using Wifi or cellular</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-0pky">❌</td>
    <td class="tg-zahu">❌</td>
  </tr>
  <tr>
    <td class="tg-0pky">historical data</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Number of viewers on a particular stream</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">IP</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-0pky">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">pageLoadTime</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Screen Size</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
  <tr>
    <td class="tg-0pky">Operating System</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
    <td class="tg-zahu">✅</td>
  </tr>
</tbody>
</table>

**Comment by USAMAWIZARD** [comment]
I have also created  feature request for displaying dynamically updated data on there dashbord
https://community.bitmovin.com/t/add-feature-of-displaying-dynamically-updated-custom-data-on-dashboard/1797

**Comment by umtcylmz** [comment]
Hi Usama, thanks a lot for your effort!
