### ISSUE TITLE
publish stream with webRTC on Community Edition 1.5.1.1 show wrong images

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#473]
# Issue

### Short description
publish  stream with webRTC on Community Edition 1.5.1.1 show wrong images

### Environment

[x] Operating system and version:ubuntu server 18.04
[x] Java version:open jdk 8

### Expected behavior
Show normal images

### Actual behavior
![image](https://user-images.githubusercontent.com/40977489/47211064-248d6900-d3c7-11e8-9cde-21e7a43b387d.png)

### Steps to reproduce
1. publish screen share

**Comment by siddu177** [comment]
I'm facing same issue .

**Comment by mekya** [comment]
Hi @arnoldcui ,

Did you close this issue because it's working for you or you close for the inactivity?

Regards,
A. Oguz
