### ISSUE TITLE
Auto Instance Switch(High Availability) Testing - Share the story in Blogpost

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4730]
# Scenario 1
1. Create two instances in cluster mode and Load Balancer
2. Publish stream on instance1 through load balancer
3. Play the stream on instance2 through load balancer
4. Stop the service instance2

Expectation:
Player on step3 will start to play through instance1 automatically

5. Start the instance2
6. Stop the instance1

Expectation:
Publisher on step 2 will start to publish to instance2 and Player on step 3 will play automatically

# Scenario 2
1. Create two instances in cluster mode and Load Balancer
2. Publish stream on instance1 through load balancer
3. Play the stream on instance2 through load balancer
4. Terminate the instance2

Expectation:
Player on step3 will start to play through instance1 automatically

5. Start the instance2
6. Terminate the instance1

Expectation:
Publisher on step 2 will start to publish to instance2 and Player on step 3 will play automatically

# Scenario 3
1. Create two instances in cluster mode and Load Balancer
2. Set the cpulimit to 30 on instance1 and instance2
3. Increase the cpu usage to 50 by running some tasks on shell both on instance1 and instance2
4. Publish stream on instance1 through load balancer

Expectation:
Publisher on step 4 will try to publish periodically but it will not succeed

5. Stop the load operation on instance2 

Expectation:
Publish will start to publish to instance2

6. Load the cpu instance2 to 50
7. Play the stream 

Expectation:
Player on step 7 will try to play periodically but it will not succeed

8. Stop the load operation on instance2

Expectation:
Player on step 8 will start to stream

**Comment by yashtandon113** [comment]
The reconnection mechanism should be present on the player in the first two circumstances so that it can connect to another server if one goes down.
For these cases, there is currently a issue on the player side. Here's the related GitHub issue: https://github.com/ant-media/Ant-Media-Server/issues/4778

**Comment by yashtandon113** [comment]
Blogpost is in progress and almost done: https://antmedia.io/?p=79124&preview=true

But the functionality is not working as expected so I reopened the Git Hub issue: https://github.com/ant-media/Ant-Media-Server/issues/4778

**Comment by yashtandon113** [comment]
https://antmedia.io/?p=79124&preview=true

Please check and suggest if any changes are required.

**Comment by timantmedia** [comment]
The content is good, but is it possible to add some images, even terminal images of shutting down servers or showing how to increase load on the server? If not, I can test this on my side and add some images. 

I think some images of what is happening might make this post more engaging.

**Comment by timantmedia** [comment]
@yashtandon113 do should I add some images for you on this and then I can add this blog post to the queue to be published?

**Comment by yashtandon113** [comment]
Blog post has been published so I am closing this issue now.
https://antmedia.io/unleash-high-availability-live-streaming/

Thanks @timantmedia
