### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME When trying to use videojs-webrtc-plugin

### ISSUE THREAD

**Issue by adammpolak** [ant-media/Ant-Media-Server#4731]
### Short description

Trying to implement webrtc plugin but when I point at: "ws://localhost:8080/websocket/" I get the ERR_UNKNOWN_URL_SCHEME  scheme.

### Environment

* Operating system and version: Windows 10
* Java version:  N/A
* Ant Media Server version: N/A
* Browser name and version: Chrome

### Steps to reproduce
1. npm install videojs and the webrtc plugin
2. Make the source a websocket: ws://localhost:8080/websocket/
3.Get the ERR_UNKONWN_URL_SCHEME error

### Expected behavior
it should connect to websockets

### Actual behavior
Does not accept the ws socket.

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

![image](https://user-images.githubusercontent.com/12940507/210895400-e390b887-97b9-4435-939e-6afd4bc81f5f.png)

**Comment by mustafaboleken** [comment]
Hi @adammpolak 
The missing part is the application name. For example if you wanted to use LiveApp, your websocket url will be like ws://127.0.0.1:8080/LiveApp/websocket

**Comment by adammpolak** [comment]
I am using an SDK that does not allow changing of the URL, does this mean I cannot use videojs?

**Comment by mustafaboleken** [comment]
Unfortunately, you cannot this repository. We modify the videojs-webrtc-plugin according to our custom signalling protocol and it is only compatible with Ant Media Server.

**Comment by adammpolak** [comment]
Thank you for letting me know
