### ISSUE TITLE
Write a blogpost about DuetMaster

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4740]

**Comment by timantmedia** [comment]
@mustafaboleken I made some edits https://docs.google.com/document/d/1R7GCqNpJcugrPrjbR00CZvtEFLn2cWYRsqEIUUYoGnQ/edit?usp=sharing

**Comment by mustafaboleken** [comment]
> @mustafaboleken I made some edits https://docs.google.com/document/d/1R7GCqNpJcugrPrjbR00CZvtEFLn2cWYRsqEIUUYoGnQ/edit?usp=sharing

You can directly update the blogpost. It will be easier for you too and me.
