### ISSUE TITLE
Fix placement for HLS Streaming setting related checklist!

### ISSUE THREAD

**Issue by asharamseervi** [ant-media/Ant-Media-Server#4743]
### Brief description
I've noticed minor glitch, to bring consistency around settings for HLS Streaming related checklist i.e. ```Enable Low Latency HLS Streaming(CMAF) ``` should be aligned with ```HLS Streaming``` rather than ```DASH Streaming```.

Just need to correct placement! To understand it clear kindly refer screenshot!

![fix-placement](https://user-images.githubusercontent.com/5942572/211388783-5930283b-8ed5-4fca-85cd-950f8390f82f.PNG)

**Comment by mekya** [comment]
Hi @asharamseervi ,
This is about internal implementaiton of ffmpeg.  HLS Section is about the classical HLS implementation. It creates and uses ts files. 

LL-HLS is provided through DASH and they use the CMAF files as the DASH provides.  I mean create HLS file is an option for DASH muxer.

**Comment by mekya** [comment]
The branches are merged so closing this issue.
