### ISSUE TITLE
Enable/Disable ABR per stream

### ISSUE THREAD

**Issue by felixmeedt** [ant-media/Ant-Media-Server#4746]
Please add an option in the app to generally disable or enable ABR.
In each stream there should be an option to enable/disable ABR.

**Comment by Mohit-3196** [comment]
Hi @felixmeedt ,
How are you?

Thank you for creating the issue.
As you are aware ABR is a CPU intensive process and it is application specific on the server side and not stream specific. 
However there is a quick workaround solution for this.
You can configure different applications to support different settings. e.g., Out of LiveApp and WebRTCAppEE, you can use one application for Adaptive streaming and other for SFU or you can have different sets of Adaptive settings for different applications.
If needed you can create more applications as per your use case.

I hope this helps.
Have a great week.

Thank you,
Mohit Dubey

**Comment by felixmeedt** [comment]
We are publishing many streams in one multitrack. But only one (sub-)stream have to be ABR. This is the one stream, which all viewers can consume.

BTW i talked to selim about this issue a few weeks ago.

**Comment by Mohit-3196** [comment]
Hi @felixmeedt ,
OK I see. Thank you.

I will discuss this within the team and will write to you.

**Comment by Mohit-3196** [comment]
Hi @felixmeedt ,
Hope you had a good day.

We had a discussion about this feature internally and it is not something that's doable easily.
Adding such a feature on server side will require a lot of time and resources to be dedicated and team is already loaded with the scheduled tasks and development works. Also this feature is not something which is requested by many users.

Thank you for your understanding.

Have a great week.

**Comment by mekya** [comment]
Thank you for the issue @felixmeedt and explanation @Mohit-3196 

Let's put to the backlog and we can revisit this issue when we have some time

**Comment by nocpbxchap** [comment]
I was checking these also, so then solution is to create an application for each stream?

And is possible to create application with api?
Open
[enable/disable ABR per stream](https://github.com/ant-media/Ant-Media-Server/issues/4746#top)
#4746
[felixmeedt](https://github.com/felixmeedt) opened this issue on Jan 11 · 5 comments
Assignees
@Mohit-3196
Comments
[felixmeedt](https://github.com/felixmeedt) commented [on Jan 11](https://github.com/ant-media/Ant-Media-Server/issues/4746#issue-1529051326)
Please add an option in the app to generally disable or enable ABR.
In each stream there should be an option to enable/disable ABR.

[Mohit-3196](https://github.com/Mohit-3196) commented [on Jan 11](https://github.com/ant-media/Ant-Media-Server/issues/4746#issuecomment-1378956960)
Hi @felixmeedt ,
How are you?

Thank you for creating the issue.
As you are aware ABR is a CPU intensive process and it is application specific on the server side and not stream specific.
However there is a quick workaround solution for this.
You can configure different applications to support different settings. e.g., Out of LiveApp and WebRTCAppEE, you can use one application for Adaptive streaming and other for SFU or you can have different sets of Adaptive settings for different applications.
If needed you can create more applications as per your use case.

I hope this helps.
Have a great week.

Thank you,

**Comment by Mohit-3196** [comment]
This feature has been implemented and is available in Ant Media Server version 2.8.3 and above.
For more details, check this document https://antmedia.io/docs/guides/adaptive-bitrate/adaptive-bitrate-streaming/#broadcast-level-adaptive-bitrate-setting

Thank you.

**Comment by nocpbxchap** [comment]
That is excellent. These must be done when stream started or during stream
can also be updated?

**Comment by mekya** [comment]
Hi @nocpbxchap ,

Changing the adaptive bitrates during the streaming is not effective on the fly. It should be set before the streaming has started. 

Let us understand why you need to change the bitrates during the streaming, we may alternatively recommend another solution. 

Btw, I'm closing this issue. We can follow up your need in here or in another issue @nocpbxchap 

Cheers
Oguz
