### ISSUE TITLE
After the Ant Media Server restarts, symbolic links are deleted

### ISSUE THREAD

**Issue by jumpingaccess** [ant-media/Ant-Media-Server#4748]
Hi, 
I've followed the documentation about store recording mp4 to another location but , it seems the link is not kept and reset to local streams folder into /usr/local/antmedia/webapps/[application].

is it a way to store this or avoid the reset of this link ?

thanks

Version on test server : Ant media Server 2.5.3 Community

**Comment by yashtandon113** [comment]
Hi @jumpingaccess 
Thanks for creating the issue.
Could you please share the document you used to make the symbolic link?

**Comment by jumpingaccess** [comment]
Yes of course, the link is the following 
: https://github.com/ant-media/Ant-Media-Server/wiki/Recording-Live-Streams 

In the section : Storing Recordings to Another Directory 

⁣Télécharger TypeApp pour Android ​

Le 11 janv. 2023, 20:30, à 20:30, yashtandon113 ***@***.***> a écrit:

**Comment by waltomatt** [comment]
I'm also experiencing this issue on 2.5.2

**Comment by yashtandon113** [comment]
@waltomatt @jumpingaccess 
We confirmed the problem on our end. The issue will be assigned to the development team in the next sprint.
We will send you the snapshot version once the problem has been resolved.

Meanwhile, you can use v2.5.1. There is no such issue as mentioned by @waltomatt

**Comment by yashtandon113** [comment]
@andreashermann
Yes, we are working on this issue and will provide an update as soon as possible. Meanwhile, you can use AMS v2.5.1 if it works for you.

**Comment by andreashermann** [comment]
As a workaround we are mounting the secondary data hard drive additionally on `/usr/local/antmedia/webapps/WebRTCAppEE/streams` instead of creating a symlink there. This seems to work.

**Comment by yashtandon113** [comment]
@andreashermann 
Great, thanks for sharing this workaround solution here.

**Comment by jumpingaccess** [comment]
Hi, 

Nice solution if you don't have other services on the drive itself. 

In my case, I run webservers and API servers that work on this other drives




Télécharger TypeApp pour Android



Le 25 janv. 2023, 16:35, à 16:35, yashtandon113 ***@***.***> a écrit:

**Comment by mekya** [comment]
The fix has been merged into the master. Thank you @lastpeony @jumpingaccess @yashtandon113 @andreashermann
