### ISSUE TITLE
SamplePlugin always got "audio frames:0	video frames:0"

### ISSUE THREAD

**Issue by MoonTTMM** [ant-media/Ant-Media-Server#4750]
Built SamplePlugin ant put it in the plugins folder, and then restart AMS. 
The rest api works. But when use the stats api, always return "audio frames:0	video frames:0".
I've checked the stream id I have input, it is right. And there is "adding HLS Muxer for UNVwUkrc3R711673594211368" in the log, so the muxer is ok.

**Comment by MoonTTMM** [comment]
I have called the register api.

**Comment by MoonTTMM** [comment]
any update?

**Comment by lastpeony** [comment]
> any update?

working on it

**Comment by lastpeony** [comment]
> any update?

Did you test this on community edition?

**Comment by lastpeony** [comment]
Please enable adaptive bitrate streaming from app settings and use enterprise edition. I tested this on my side and looks like it is working fine.
1-) go to app settings. add adaptive bitrate for example 720p
2-) start stream
3-) send post request to plugin to register stream
http://localhost:5080/WebRTCAppEE/rest/sample-plugin/register/teststream
4-) send get request to get stats
http://localhost:5080/WebRTCAppEE/rest/sample-plugin/stats/

![image](https://user-images.githubusercontent.com/24750845/216048696-d2fedb23-8d50-4d61-bdf9-8be634c3ba0f.png)

**Comment by lastpeony** [comment]
> Built SamplePlugin ant put it in the plugins folder, and then restart AMS. The rest api works. But when use the stats api, always return "audio frames:0 video frames:0". I've checked the stream id I have input, it is right. And there is "adding HLS Muxer for UNVwUkrc3R711673594211368" in the log, so the muxer is ok.

Did you have this result with RTMP publishing or WebRTC publishing ?

**Comment by MoonTTMM** [comment]
I am currently using the community edition with HLS stream, so the plugin is not supported?

**Comment by lastpeony** [comment]
> I am currently using the community edition with HLS stream, so the plugin is not supported?

Yes. It is not supported in community edition.

**Comment by mekya** [comment]
So I'm closing this issue. Please re-open if you think there is still an issue.
