### ISSUE TITLE
Voice Distortion - Known Issue 

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#4761]
When there is another app (like Whatsapp or Slack which uses mic of the pc) opened and used while conference call app running in the background, sound is disturbed and stutter. 
When the app is closed, it backs to normal.

**Comment by burak-58** [comment]
If sound meter is enabled for the local stream on the publisher side, the players hear audio distorted when another app is on the top and full screen.

**Comment by mustafaboleken** [comment]
The Sound meter uses createScriptProcessor which is deprecated in 2014. I'm migrating to AudioWorkletNode right now. AudioWorkletNode uses a separate thread to processor audio. It promises to avoid stuttering and unwanted pauses.
I strongly believe that this migration solved the problem.
