### ISSUE TITLE
Video Rotation Problem in HLS and MP4 files

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4762]
This problem happens when there is no adaptive bitrate on the server side. 

Steps
1. Send stream to Ant Media Server with Android SDK
2. Watch the stream with HLS
3. Rotate the mobile device to portrait and landscape several times

Expected:
Rotation has changed properly in HLS
Actual:
It's 90 degree rotated

Solution:
Use AV_PKT_DATA_DISPLAYMATRIX as side data for exporting packet-level
  spatial rendering on video frames for proper display.

**Comment by Samriddha01** [comment]
Still any update on the same?? i am facing this problem right now.

**Comment by mekya** [comment]
Hi @Samriddha01 
The problem is being fixed with this issue
https://github.com/ant-media/Ant-Media-Server/issues/6099

FYI
