### ISSUE TITLE
HLS Load creates problem on NGINX while using Kubernetes

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#4767]
When HLS is preferred to be used for streaming, during the load of X thousand of users for the clustered Ant Media Server implemented through Kubernetes, NGINX starts getting stuck and giving an error of 504.
We need to implement a similar solution as previously introduced to handle HLS load by passing through NGINX

**Comment by yashtandon113** [comment]
**Update:** During the tests, the HLS from the Edge Server worked intermittently. I'll look into it further.

**Comment by yashtandon113** [comment]
I and @burak-58 were able to reproduce the issue on our end, and the two different scenarios are as follows:

Origin: 1 pod/node - 4 cores
Edge: 1 pod/node - 4 cores

1. When an HLS load of 500 HLS viewers was applied, accessing the Edge server via ingress resulted in a 504 Gateway error, as described in the issue. After further investigation, the Edge server stopped responding to the request, but Edge pod was not restarted/crash. After I restarted the Edge pods, it becomes accessible again.

2. Loaded 100 HLS viewers, but this time the server responded but the HLS streams stopped playing from the Edge Server.

Following a deep investigation by @burak-58, the initial conclusion is that an HLS request is blocking somewhere and needs to be investigated further.

**Comment by yashtandon113** [comment]
The build has been provided to the user for testing following the fix by @burak-58.

I tested again with the previously mentioned test scenarios and did not encounter the problem.
> 
> 1. When an HLS load of 500 HLS viewers was applied, accessing the Edge server via ingress resulted in a 504 Gateway error, as described in the issue. After further investigation, the Edge server stopped responding to the request, but Edge pod was not restarted/crash. After I restarted the Edge pods, it becomes accessible again.
> 2. Loaded 100 HLS viewers, but this time the server responded but the HLS streams stopped playing from the Edge Server.
>

**Comment by yashtandon113** [comment]
The problem reappeared during load testing at the customer's end. I was able to duplicate it on our side once more, but it is no longer reproducing after multiple attempts as there is no specific scenario.

To replicate it, we need to delve deep into it.
