### ISSUE TITLE
AWS S3 integration - option settings.uploadExtensionsToS3=7 not working

### ISSUE THREAD

**Issue by fabiox23** [ant-media/Ant-Media-Server#4775]
### Short description
With settings.uploadExtensionsToS3=7, every file (ts, m3u8, mp4) should be saved on S3. However, when starting a stream and a recording, ts, m3u8 and temporary mp4 file are still being saved locally. When the recording ends, the final mp4 file is moved to S3. When the streams ends, ts and m3u8 are also moved to S3 instead of being deleted.

### Environment
Ubuntu 20.04 on EC2
Ant Media Enterprise 2.5.3

### Steps to reproduce
1. Start a stream
2. Start a recording
3. Stop a recording
4. Stop a stream

**Comment by yashtandon113** [comment]
@fabiox23
Thank you for creating the Git Hub issue.

As I have checked on my end, s3 uploading for mp4 and m3u8 works as expected. It first stores in the local disk space of the server and then uploads to the s3 bucket when the stream ends. If you want to upload all HLS files to an S3 bucket, set the hls playlist type to event under _/usr/local/antmedia/webapps/App-Name/WEB-INF/red5-web.properties_ file.

`settings.hlsPlayListType=event
`
As a result, old ts files will not be deleted from the server until the stream has finished.

Please correct me if I have misunderstood your question.

**Comment by fabiox23** [comment]
Also, with settings.hlsPlayListType=event, all ts files from the beginning of the stream are kept and never deleted until the end of the stream? Is this on S3 or on local storage? Because, the ts files are only moved to S3 at the end of the stream, if I understood correctly?

**Comment by fabiox23** [comment]
OK, using s3fs seems to be the way to go as I don't want the ts files to fill up storage on the EC2 server.

What does `settings.hlsPlayListType=event` do?

Thanks.

**Comment by yashtandon113** [comment]
@fabiox23 
If playlist type is event then server stores all the HLS files until the stream is finished. For more information, check [here](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/event_playlist_construction).

**Comment by yashtandon113** [comment]
I am closing this issue now.

@fabiox23
I hope your questions have been answered. If you have any further questions, please feel free to reopen the case.
