### ISSUE TITLE
If the origin servers scale-in in the Auto-scaling structure, forwarding publish to a server that works seamlessly

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4777]
### Short description
Broadcast is sent between one of the 2 open origins through the load balancer. The server which the broadcast is sent is scaled-in and the broadcast is interrupted.

### Steps to reproduce
1. Create a cluster using the CloudFormation Template.
2. Set desired capacity 2 for Origin configuration in Autoscale.
3. Send the stream to 2 origin instances
4. Set the Desired capacity to 1 in Autoscale (Origin)
5. One of the broadcasts will be interrupted.

### Expected behavior
Publish needs to broadcast through the running origin instance in a short time.

### Actual behavior
In the case of scale-in, the broadcast is interrupted.

**Comment by yashtandon113** [comment]
**Update:** According to my tests and observations, the process of stream forward is working as expected. Let me explain my test scenario in the following steps:

1. Using helm, I created a Kubernetes cluster with two origin pods (pod A and pod B) and ingress.
2. Published two streams, one on each server, using a load balancer.
3. In between, reduce the number of origin pods from two to one. After scaling down, pod A was deleted in my test.

As a result, the stream that was publishing on pod A was interrupted and switched to pod B in a few seconds. Same test was tested with the cluster without Kubernetes.

If required, I will check the same scenario with the Cloud formation cluster.
