### ISSUE TITLE
Rebroadcast AntMedia to AntMedia unstable

### ISSUE THREAD

**Issue by andreashermann** [ant-media/Ant-Media-Server#4783]
### Short description
We want to test the latest AntMedia release before we put it into production. For this purpose we were setting up a re-broadcast from the current production server (v2.4.3) to the newer release (v2.5.3). Live streams are produced by a venue encoder SimplyLive BMR.
The rebroadcasted stream is unstable and stops every now and then.

This problem prevents us from thoroughly testing the newest release of AntMedia 2.5.3 server. 
Alternative is to simulcast at the venue encoder. There network bandwidth is restricted which is why we tried this approach in the first place where a lot of network bandwidth is available on the AWS.

Additional hint: With a live stream produced using ffmpeg it works stable.

### Environment
* AntMedia Marketplace Image 2.4.3 and 2.5.3
* Operating system and version: 
* Java version: 
* Ant Media Server version: 2.4.3 and 2.5.3
* Browser name and version:

### Steps to reproduce
1. Start Live Stream on SimplyLive Encoder
2. Add RTMP endpoint AntMedia Server 2.4.3

### Expected behavior
Live stream is stable

### Actual behavior
Live streams stopps every now and then

### Logs
I think these are the relevant lines that appear repeatedly in the logs of the re-broadcasting server.

`2023-01-30 06:29:57,292 [vert.x-worker-thread-16] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to error  for streamId: behindgoal1 for url: rtmp://REDACTED:1935/WebRTCAppEE/behindgoal1
2023-01-30 06:29:57,321 [vert.x-worker-thread-22] INFO  io.antmedia.muxer.MuxAdaptor - Endpoint status updated to broadcasting  for streamId: behindgoal1 for url: rtmp://REDACTED:1935/WebRTCAppEE/behindgoal1`

[ant-media-server-2.4.3.log](https://github.com/ant-media/Ant-Media-Server/files/10533201/ant-media-server-2.4.3.log)
[ant-media-server-2.5.3.log](https://github.com/ant-media/Ant-Media-Server/files/10533200/ant-media-server-2.5.3.log)

**Comment by mekya** [comment]
Thank you for the issue.  There is too much error in 2.4.3 side and It does not even record MP4 or HLS. 
I think it's most likely about not pushing with RTMP, it's about ingesting.  
 
Do you encounter the same problem when you try with 2.5.3 to 2.5.3 streaming?  I think there are some improvements about the compatibility after 2.4.3 to ingest RTMP stream from SimplyLive Encoder.
