### ISSUE TITLE
Add blog post about which databases Ant Media Server supports

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4784]
- Mongodb
- Mongodb+srv
- Redis

Tell how to use this database in change_server_mode.sh and in start.sh and kubernetes

**Comment by Mohit-3196** [comment]
Here's the link to review the blogpost https://antmedia.io/?p=72779&preview=true

**Comment by timantmedia** [comment]
@Mohit-3196 please let us know here what you need to get this blog post published.

**Comment by Mohit-3196** [comment]
Hi, Thank you @timantmedia 
It is being reviewed by @lastpeony 
After he has reviewed it and there are no technical issues, we can publish.

**Comment by timantmedia** [comment]
@lastpeony has this been reviewed and do you need me to publish this?
