### ISSUE TITLE
Create python script that checks the webrtc samples on antmedia.io

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4787]
https://antmedia.io/webrtc-samples/

**Comment by yasht0105** [comment]
**Update:** For the currently running samples on antmedia.io, the script has been finished. I automated it on my repository using the github workflow for testing purposes.

**Comment by yashtandon113** [comment]
**Update:** For the currently running samples on antmedia.io, the script has been finished. I automated it on my repository using the Git hub workflow for testing purposes.

**Comment by mekya** [comment]
Congratultions @yashtandon113, could you please publish your codes to [Scripts](https://github.com/ant-media/Scripts/) repo by creating an appropriate folder?

**Comment by yashtandon113** [comment]
The script has been published to Scripts repository.

**Comment by mekya** [comment]
Thank you @yashtandon113

**Comment by yashtandon113** [comment]
Closing this issue. 
Duplicate https://github.com/ant-media/Ant-Media-Server/issues/4845
