### ISSUE TITLE
Can´t save App-Settings when Azure App-GW WAF prevention activated

### ISSUE THREAD

**Issue by felixmeedt** [ant-media/Ant-Media-Server#4792]
### Short description
When the WAF in Azure App-GW is activated the saving of Settings is not possible.
Message: "You are not allowed to access this resource. Contact your system administrator"

### Environment

* Operating system and version: Ubuntu 20.04.05 LTS
* Java version: ?
* Ant Media Server version: Azure AMS 2.5.3 20230107_0851
* Browser name and version: Google Chrome 109.0.5414.120

### Steps to reproduce
1. Create Cluster on Azure using the documentation https://resources.antmedia.io/docs/how-to-setup-ant-media-server-clustering-on-azure
2. Activate WAF with prevention on the created Application-Gatway
3. Change some settings in an app

### Expected behavior
Saving works

### Actual behavior
An error is displayed: "You are not allowed to access this resource. Contact your system administrator"
 

### Logs
Azure WAF Logging attached

[Azure Monitor Log Analytics Export - 2023-02-02.CSV](https://github.com/ant-media/Ant-Media-Server/files/10567211/Azure.Monitor.Log.Analytics.Export.-.2023-02-02.CSV)

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you @felixmeedt,

Let us reproduce the problem.

**Comment by muratugureminoglu** [comment]
Hi @felixmeedt 

Sorry for the late reply And thank you for reporting this issue. You know that WAFs sometimes give false positive alarms. Frankly, it can take some time to find them and fix them one by one. And from what I've checked, Azure WAF uses OWASP's 185 default rules.

There are two options for fixing these issues.

**1.** To disable it in **Managed rules** according to the errors you see in the logs.
**2.** Allow this url address `/rest/v2/applications/settings/` in **Custom rules**. (Please see the screenshot and don't forget the update and save the rule that you added)

![azure-waf](https://user-images.githubusercontent.com/6337605/219970638-b0d68706-57c9-4ed9-9351-1b249d584d74.png)

**Comment by Mohit-3196** [comment]
Hi @felixmeedt ,
How are you?

Please let me know if you had a chance to try the solution provided by my colleague.
Do let me know if you have any issues or comments.

Thank you

**Comment by Mohit-3196** [comment]
Hi @felixmeedt ,
I hope you are doing well.

Let me know if you have any questions for us or if you are still facing the issue.

Thank you

**Comment by felixmeedt** [comment]
Hi @Mohit-3196,
unfortunately it's been a bit stressful lately.
But finally I was able to test the WAF custom rule.
It works.
Thanks

**Comment by Mohit-3196** [comment]
Closing this issue as it has been completed.
