### ISSUE TITLE
Turn server configuration of red5-web.properties file not reflecting in html files

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#4794]
### Short description
When we set Turn server configuration in red5-web.properties file of the application it should  reflect in all the html pages but it does not.

### Environment

* Operating system and version:Linux
* Ant Media Server version:2.5.3
* Browser name and version:chrome

### Steps to reproduce
1. navigate to property file of the application /usr/local/antmedia/webapps/WebRTCAppEE/WEB-INF/red5-web.property
2. add the turn server configuration property 

settings.webrtc.stunServerURI=turn:IP:3478
settings.webrtc.turnServerUsername=xxxxxxxxxxxx
settings.webrtc.turnServerCredential=xxxxxxxxxxxxx

3. save the file 
4. navigate to http://IP:5080/WebRTCAppEE/
http://localhost:5080/WebRTCAppEE/samples/publish_webrtc.html

view page source code 

5. Turn server configuration should be updated in pc_config variable but it does not

### Expected behavior
Turn server config should be updated in all the Html files when update in red5 property file

### Actual behavior
It does not update in html files
 

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hey Usama,

This is an expected behavior due to the security and ambiguity of the HTML files in different applications. 
I mean this setting is supposed to be effective for the server side, not the client side.

If it's ok for you, you can close the ticket. If not ok for you, let's continue the discussion. 


Regards
Oguz

**Comment by mekya** [comment]
Thank you @USAMAWIZARD
