### ISSUE TITLE
Onboard Ant Media Server to IONOS Cloud

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#4796]
AMS will be listed on [ionos.com](https://www.ionos.com/) and one of our engineers to register on [here](https://cloud.ionos.de/compute/registrierung) in order to handle technical side of the process.

**Comment by mekya** [comment]
Hey @umtcylmz ,

Thank you for the issue. 

This link ( [here](https://cloud.ionos.de/compute/registrierung) ) is a registration link to ionos.

What do you expect to have when this job is completed?

Regards
Oguz

**Comment by mekya** [comment]
Hi @lastpeony 
Do we have some link that shows Ant Media Server in ionos cloud or we just close the issue because inactivity?

**Comment by mekya** [comment]
It's closed for the inactivity.
