### ISSUE TITLE
Missing VOD files

### ISSUE THREAD

**Issue by EddieLongStockings** [ant-media/Ant-Media-Server#4801]
### Short description
Hello! I'm hoping this is just a quick question. I'm missing some VOD files, the were uploaded to the Ant Media Server VOD interface several months ago. I also noticed that the hard disk is full. I'm wondering if Ant Media deletes older VOD files to make space? 

Otherwise I can't seem to explain why these older files are missing.

Thanks!

### Environment

Ant Media Community Community Edition 2.4.2 20220125_1618

### Steps to reproduce
It's not easy to reproduce.

### Expected behavior
VOD files don't go missing.

### Actual behavior
VOD files are missing. But just the older ones.

### Logs
No logs.

**Comment by mekya** [comment]
Hi @iLoveSarabear,

Thank you for asking this question. 

Ant Media Server does not delete older VoD files. 
Please don't fill the disk, it may have some consequences.  

If you still have the same problem and would like to discuss more, let's discuss on [community.antmedia.io](https://community.antmedia.io)

Regards
Oguz

**Comment by EddieLongStockings** [comment]
Thank you!
