### ISSUE TITLE
Installation script will try to install libcrystalhd-dev if the version is other than 2.6

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4813]
### Short description
Assume that we've released 2.7 or 3.0, then the installation script will try to install libcrystalhd-dev again.
This problem is not for today for the future so its priority is low

Check these lines 
https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L233
https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L240

### Expected behavior
libcrystalhd-dev should not be attempted to install in later versions 2.6+

### Actual behavior
libcrystalhd-dev is attempted to install in the future if version is 2.7, 3.0, etc.

**Comment by muratugureminoglu** [comment]
Hi @mekya 

The script is already working as expected.

![Screenshot at 2023-02-12 10-08-55](https://user-images.githubusercontent.com/6337605/218297931-b830a3dc-e7c1-4f70-b3fb-3f76eef42159.png)

**Comment by mekya** [comment]
What is the content of `test.sh` ?

**Comment by muratugureminoglu** [comment]
test.sh only confirmation that you mentioned the above. I run the test.sh instead of the installation script. 

```
VERSION="$1"
REQUIRED_VERSION="2.6"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
   echo -e "less than 2.6\nCurrent Version: $VERSION"
else
   echo -e "greater than 2.6 \nCurrent Version: $VERSION"	
fi
```

**Comment by mekya** [comment]
Thank you. Then closing this issue. It's my misinterpretation.
