### ISSUE TITLE
Minimum HW/SW Requirements To Run Ant Media Server

### ISSUE THREAD

**Issue by 79rpm** [ant-media/Ant-Media-Server#4819]
I need help finding a detailed description of the HW/SW requirement to run the Ant Media Server. 

What is the minimum requirement for RAM, CPU processors, and disk space to run the server? The only information is Ubuntu 18.04LTS as an OS. There are several references to GPUs; which minimum GPU should be used to run the server?

**Comment by Mohit-3196** [comment]
Hi @79rpm ,
Hope you are doing well.

To deploy Ant Media Server Community Edition, it is recommended to use a minimum of 2 cores CPU dedicated server with 4GB RAM.
For running the Ant Media Server Enterprise Edition, it's recommended to use a minimum of 4 cores CPU dedicated server with 8GB RAM.
Also, the recommended ubuntu version is Ubuntu 20.04LTS

GPU is used on the server for transcoding purposes. So if your use cases require transcoding/adaptive streaming, you can consider using GPU.

Let me know if you have any more queries.

Thank You,
Mohit Dubey

**Comment by 79rpm** [comment]
Thank you @Mohit-3196 for the details; this is very helpful.

**Comment by Mohit-3196** [comment]
Hi @79rpm ,
It is my pleasure :)
