### ISSUE TITLE
StreamApp ams-v2.5.3 failed to build

### ISSUE THREAD

**Issue by mojatter** [ant-media/Ant-Media-Server#4821]
### Short description

StreamApp ams-v2.5.3 is failed to build. 

```
% cd StreamApp
% git checkout ams-v2.5.3
% mvn clean package -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
[ERROR] Failed to execute goal on project StreamApp: Could not resolve dependencies for project io.antmedia.webrtc:StreamApp:war:2.5.3: io.antmedia:ant-media-server:jar:2.5.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

StreamApp ams-v2.5.1 is succeed.

```
% cd StreamApp
% git checkout ams-v2.5.1
% mvn clean package -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
% echo $?
0
```

### Environment

* Operating system and version: Debian GNU/Linux 11 (bullseye)
* Java version: openjdk version "20-ea" 2023-03-21
* Ant Media Server version: v2.5.3

**Comment by yashtandon113** [comment]
@mojatter
First you need to build the Ant-Media-Server project for dependencies.

```
git clone https://github.com/ant-media/Ant-Media-Server.git
git checkout ams-v2.5.3
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true
```
After that you will be able to build StreamApp.

**Comment by mojatter** [comment]
The error is `Could not find artifact io.antmedia:ant-media-server:jar:2.5.3 in central`.

I can find v2.5.2 as latest, v2.5.3 is not found.
https://search.maven.org/search?q=a:ant-media-server

**Comment by mekya** [comment]
Thank you for your comments. @mojatter @yashtandon113 

>The error is Could not find artifact io.antmedia:ant-media-server:jar:2.5.3 in central.

>I can find v2.5.2 as latest, v2.5.3 is not found.
>https://search.maven.org/search?q=a:ant-media-server

You're right. v2.5.3 is missing somehow in maven. Workaround solution provided by Yash help you build it.
2.5.3 is critical for you? If yes, we can try to re-publish to the maven repo. 
If no, It's likely we'll have a new release 2.6.0 soon.

**Comment by mojatter** [comment]
@mekya Thank you very much. I will wait for next release.

**Comment by mekya** [comment]
Hi @mojatter,
There is a new release and you can test it on your end. 

Please let me know if it works for you

**Comment by mojatter** [comment]
Hi @mekya,

StreamApp ams-v2.6.0 is succeed to build.
Thanks
