### ISSUE TITLE
Broken HLS Playback after Stream ends

### ISSUE THREAD

**Issue by andreashermann** [ant-media/Ant-Media-Server#4822]
### Short description

The following is a problem in AntMedia server 2.5.3 in combination with SimplyLive BMR.

We are using AntMedia with these features active
- HLS playback
- ABR (1080p, 720p renditions)
- DVR/Recording

After the broadcast of a live stream finishes, it cannot be played back anymore in our webapp using [hls.js](https://github.com/video-dev/hls.js/).
This happened in some 20% of our live streams and prevents our users from viewing the videos after the game.

#### hls.js playback
Playing the video with the [hls.js demo player](https://hls-js.netlify.app/demo/) doesn't work
Ultimately, there's an error "Buffer stalled error"

- a playable video has been emailed to AntMedia support.
- log files have been emailed to AntMedia support

#### Inspecting archived HLS video
Inspecting the archived passthrough video shows that the first few TS segments have unusually small file sizes.
image.png
ffprobe then explains the problems with these segments
> ffprobe https://videos-test.49ing.ch/hls/NLA/2023/2023-02-14-SCL-SCRJ-tvfeed/tvfeed000000000.t
h264 @ 0x7f966530de80] non-existing PPS 0 referenced
2    Last message repeated 1 times
3[h264 @ 0x7f966530de80] decode_slice_header error
4[h264 @ 0x7f966530de80] no frame!
![image (1)](https://user-images.githubusercontent.com/3263159/219303263-c201a2df-6d7a-4664-a6e8-1fecca287024.png)

Googling above error messages finds a stackoverflow question: https://stackoverflow.com/questions/15005436/errors-when-decode-h-264-frames-using-ffmpeg

> That just means that ffmpeg has not seen a keyframe yet, which carries SPS and PPS information. SPS and PPS are crucial in decoding an incoming frame/slice. Keyframes are sent periodically (i.e. every 5-10 seconds or more); so if it turns out that you joined a stream before the keyframe arrived; you will see this warning for every frame until a keyframe shows up.
> 
> As soon as the keyframe shows up from the wire, ffmpeg will have enough information to decode that frame (and any subsequent frames until the next keyframe), so those warnings will go away.
> 

Inspection of the encoded renditions (ABR mode)
![image](https://user-images.githubusercontent.com/3263159/219303147-7ff1dba0-67d9-4483-b475-5728658495de.png)

> Only the first segment seems to have an unusually small size, but this is enough to block web playback.
> ffprobe analysis:
> [mpegts @ 0x7fa2c1704e80] start time for stream 0 is not set in estimate_timings_from_pts
> [mpegts @ 0x7fa2c1704e80] stream 0 : no TS found at start of file, duration not set
> [mpegts @ 0x7fa2c1704e80] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> 

My hypothesis is: AntMedia server struggles to start the HLS video with valid segments. While live mode is active, viewers just start at the end of the live stream. As soon as broadcasting stops, the web player fails to load the first segments.

We assume this is a regression in AntMedia server 2.5.x. This problem is very inconvenient to us as it prevents us from using the HLS video after it was recorded.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.5.3 AWS Marketplace Enterprise Edition GPU
* Browser name and version:

### Steps to reproduce
1. Start stream on SimplyLive BMR
2. Run for 4h
3. Stop live stream on SimplyLive BMR

### Expected behavior
Video does play back in hls.js once live stream ended

### Actual behavior
Video does not play in hls.js once the stream ended

**Comment by mekya** [comment]
Thank you @andreashermann for the issue. I understand the issue and have an idea for a quick fix. 

Let me send a PR for that. 

@Mohit-3196 it's rather hard to reproduce on your end so I'm also assigning it to myself.

**Comment by Mohit-3196** [comment]
Hi @mekya abi,
OK, Thank you.

**Comment by andreashermann** [comment]
Thanks @mekya for the quick analysis!

I will share an example with you in private by email.

**Comment by mekya** [comment]
Hi @andreashermann,

I'm closing this issue. Please feel to re-open if it does not work for you. 

Regards
Oguz
