### ISSUE TITLE
Problem with Docker Cluster ( login and play stream )

### ISSUE THREAD

**Issue by boardmain** [ant-media/Ant-Media-Server#4826]
### Short description
Hi all i have a problem with a cluster,
i created a cluster with 2 Server
both are clean AMS Setup with docker ( enterprise edition )
if i log directly on the nodes i can see correctly the cluster tab active with 2 nodes ( but i see it both with the docker ip, 127.0.1.1 )

both server (and mongodb ) are in the same local network

i have a load balancer over it

with configured port 1935->1935
5080 -> 5080
5443 -> 5080 with valid certificate

when i try to login to the hostname that point to the load balancer i get Error 403 and i can't login

(login work correctly if i try to login directly to the nodes)

if i try to publish a stream and play it to the balanced hostname it start publishing
but i can't play it ( i play and publish with token and token creation works correctly)

i don't know what i can try

### Environment

Docker on Ubuntu 22.04.1 LTS
Enterprise Edition 2.5.3 20230107_0851

### Steps to reproduce
1. setup a docker cluster with 2 server
2. configure https to load balancer and configure it
3. try to login to the cluster

**Comment by boardmain** [comment]
when i try to login this are the error in the console

`AuthService: is authenticated: true local storage: null
main.7029e7f9b732de3a9de2.js:1 AuthService navigating login
:5443/#/pages/login:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password" class=​"form-control input-no-border ng-valid ng-touched ng-dirty" placeholder=​"Password">​
main.7029e7f9b732de3a9de2.js:1 AuthService: is authenticated: true local storage: true
:5443/rest/v2/system-resources:1          Failed to load resource: the server responded with a status of 403 ()
13.ee9c9a644dc7a1668f06.js:1 error status: 403
:5443/rest/v2/cluster-mode-status:1          Failed to load resource: the server responded with a status of 403 ()
:5443/rest/v2/applications:1          Failed to load resource: the server responded with a status of 403 ()
:5443/rest/v2/version:1          Failed to load resource: the server responded with a status of 403 ()
:5443/rest/v2/applications-info:1          Failed to load resource: the server responded with a status of 403 ()
main.7029e7f9b732de3a9de2.js:1 ERROR n
Hn @ main.7029e7f9b732de3a9de2.js:1
:5443/#/pages/login:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password" class=​"form-control input-no-border ng-valid ng-dirty ng-touched" placeholder=​"Password">​
main.7029e7f9b732de3a9de2.js:1 `

**Comment by muratugureminoglu** [comment]
Hi @boardmain 

Could you please share all the steps to test this on our side?

- Which document did you use?
- YAML files
- Ingress configuration
- Other customs conf.

**Comment by muratugureminoglu** [comment]
Hi @boardmain 

I'm closing this issue for now. I can test and solve it for you if you let me reproduce it.
