### ISSUE TITLE
Ubuntu 20.04 Arm64 libcrystalhd-dev issue

### ISSUE THREAD

**Issue by Antoni950425** [ant-media/Ant-Media-Server#4836]
Hello, I'm trying to install AMS community version on my arm64 ubuntu server. However, it always said: E: Package 'libcrystalhd-dev' has no installation candidate

By reading the past issues, I think the AMS should be already supported ARM64. And my ubuntu version is supported too. So I'm a bit clueless how to fix this.

Here are my terminal output:

root@livestreamserver:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

root@livestreamserver:/home/ubuntu# sudo ./install_ant-media-server.sh -i ant-media-server-community-2.5.3.zip
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:2 http://ap-osaka-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ap-osaka-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://ap-osaka-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Get:5 http://ftp.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
Get:7 http://ftp.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
Get:8 http://ftp.ubuntu.com/ubuntu focal/universe arm64 c-n-f Metadata [255 kB]
Ign:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
Ign:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
Ign:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
Ign:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
Err:6 http://ftp.ubuntu.com/ubuntu focal/universe arm64 Packages
  404  Not Found [IP: 185.125.190.39 80]
Fetched 265 kB in 3s (78.2 kB/s)
Reading package lists... Done
E: Failed to fetch http://ftp.ubuntu.com/ubuntu/dists/focal/universe/binary-arm64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvdpau-dev is already the newest version (1.3-1ubuntu2).
zip is already the newest version (3.0-11build1).
libva-drm2 is already the newest version (2.7.0-2).
libva-x11-2 is already the newest version (2.7.0-2).
unzip is already the newest version (6.0-25ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcrystalhd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libcrystalhd-dev' has no installation candidate
There is a problem in installing the ant media server. Please send the log of this console to support@antmedia.io

**Comment by yashtandon113** [comment]
@Antoni950425 
Thanks for creating the issue.

You can try installing libcrystalhd-dev using below commands:

```
echo "deb http://ftp.ubuntu.com/ubuntu   focal universe" >> /etc/apt/sources.list
sudo apt-get update
```
Then run the installation. Meanwhile, I'll try this on my end and discuss it further with my colleague in order to permanently resolve this issue. We encountered this issue on Ubuntu 22.04 but not on Ubuntu 20.04, so we need to double-check.

**Comment by Antoni950425** [comment]
> 

Hi Yashtandon, Thanks for your quick response! I already tried this, if you see the output it can not find the package. For ubuntu it seems libcrystalhd-dev doesn’t support aarch64 yet.

**Comment by yashtandon113** [comment]
@Antoni950425 
Thank you for providing this information. Yes, this package does not appear to be available for the arm64 (aarch64) architecture.

We recently upgraded the ffmpeg version for the upcoming version of Ant Media Server, and as I checked, there are no issues with the installation of that version. Crystal HD decoders have been disabled in the latest release.
You can download the 2.6.0 community snapshot version from [**here**](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/ant-media-server/2.6.0-SNAPSHOT/ant-media-server-2.6.0-20230221.150518-159-community.zip).

For change logs please check https://antmedia.io/changelog/changelog.html.

**Comment by mekya** [comment]
Hi @Antoni950425 

Thank you for this issue. 
In the recent versions(2.6.0+), libcrystalhd is not used anymore. Additionally, installation script is also updated for arm64 architecture in this PR https://github.com/ant-media/Scripts/pull/231

I'm closing this issue and please feel free to open it if it does not work for you.

Cheers
