### ISSUE TITLE
Sound choppy in chrome 110 version

### ISSUE THREAD

**Issue by jangjonghwa** [ant-media/Ant-Media-Server#4837]
### Short description
__Brief description of what happened__

### Environment

* Operating system and version: aws marketplace
* Java version: 
* Ant Media Server version: 2.5.3
* Browser name and version: chrome 110.0.5481.177

### Steps to reproduce
1. webrtc publishing in chrome 110 browser
2. Sound choppy
3. After downgrading to chrome 108 there is no problem.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you for the issue. It's an important issue so I've set the priority to urgent.

**Comment by mustafaboleken** [comment]
In the latest version of chrome echo cancelation and noise supression is enabled in defult and they cause choppy sound error. After I disable them in defult mode, it's solved.

**Comment by mekya** [comment]
Are you sure that this is related to the latest version of chrome?

I think it may be related to the soundmeter. This problem may be also the same  https://github.com/ant-media/Ant-Media-Server/issues/4955

**Comment by mekya** [comment]
Hi @jangjonghwa,
To be honest, I could not reproduce the sound choppy problem in chrome 110 version. Nevertheless, we have some improvements related to audio stuff. Is it possible to check that the latest master branch work for you?

If you want, we can even take a look at together and try to understand sound choppy issue on your end. 


Please let us know how you would like to proceed

Cheers
Oguz
