### ISSUE TITLE
Add an option in ant media server script to specify installation directory

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#4840]
**Is your feature request related to a problem? Please describe.**
If a user want to install ams in a different directory or a developer want to have multiple installation of  different versions of ant media server for development and testing purpose  There is no option currently available in install script

**Describe the solution you'd like**
add a option to specify the path where we want to install ant media server

[Ant media](https://antmedia.io/)

**Comment by mekya** [comment]
Thank you @USAMAWIZARD for the issue. 

Yes, we can add an option to specify the installation directory.  

Just FYI, if one installs two ant media server instances in the same machine, there will be a problem in  the ports. So some kind of virtualization is needed.

**Comment by USAMAWIZARD** [comment]
Thank you @mekya abi I did not intended to run it parallel to each other just wanted to have two installations. discussed internally with @muratugureminoglu abi unzipping would be more easy solution. closing the issue now.

**Comment by mekya** [comment]
I'm then moving this issue to the backlog because it's not done.

**Comment by USAMAWIZARD** [comment]
@mekya I have done some little implementation for this but after discussing with murat abi he told me its not necessary so scraped it If you still think it would be something useful I can continue on it

**Comment by mekya** [comment]
Let's keep it in backlog and we can revisit it later
