### ISSUE TITLE
Already playing error over single websocket connection

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4844]
We are using the subscriberId field in the response websocket message as per fresh development. We pass our custom metadata in this field, and in the cluster mode everything works as it should, the metadata is returned.

**However, we are faced with the following:**
-When retransmitting the 'play' message for one currently streaming camera with a subscriberId field, the response 'already_playing' will be returned. Without using the subscriberId field, we did not encounter such a problem (we passed 'play' several times for one camera over one connection, and everything worked).

**Let me re-describe our architecture (for your understanding):**
On the backend, we have one single websocket connection to the media server.
Using this connection we transmit and receive all the information.
We assume that it is only possible once per websocket connection to pass the subscriberId in the message.
In this regard, we would like to clarify:
Is it possible to make it possible to pass the subscriberId field more than once per stream, or is it impossible?

**Comment by mekya** [comment]
Thank you @yashtandon113 for creating this issue. 

We may add a flag to allow playing the stream id from the same subscriber more than once. It requires some development.

Regards
Oguz
