### ISSUE TITLE
 Install SSL for your Ant Media Server issue [ Please make sure you enter your license key ] in AWS Marketplace

### ISSUE THREAD

**Issue by jgcman** [ant-media/Ant-Media-Server#4846]
Hi.

I downloaded the Enterprise Edition from AWS Cloud Marketplaces.
And I proceeded to install ssl according to the [guide document](https://github.com/ant-media/Ant-Media-Server/wiki/Quick-Start), and I got unexpected output.

Console output
`Please make sure you enter your license key and use the Enterprise edition.`

I purchase Enterprise Edition from AWS Cloud Marketplaces and use it. 
Do I need to purchase a license key additionally?

Additionally, please let me know where I can find the client SDK.

**Comment by mustafaboleken** [comment]
Hi @jgcman,
When you use the AWS Marketplace image, the software license key is also included. So you don't need to pay an extra fee. I think there is a problem with the SSL script. We will investigate the issue. Can you please check the scenario @muratugureminoglu?

**Comment by mustafaboleken** [comment]
For the SDK you can check our documentation website https://antmedia.io/docs/category/developer-sdks-and-apis/
Our all SDKs are open source and you can get them on GitHub organization page https://github.com/orgs/ant-media/repositories

**Comment by jgcman** [comment]
Thanks for your support :)

**Comment by mustafaboleken** [comment]
> Thanks for your support :)

Is your SSL problem solved?

**Comment by sodos** [comment]
this issue still there

**Comment by mekya** [comment]
I'm re-opening issue to fix this problem

**Comment by muratugureminoglu** [comment]
Hi,

We do not currently provide a free domain for marketplace products. We will provide this as soon as possible. However, if you'd like, we can still offer you a free domain.

**Comment by sodos** [comment]
Thanks for the offer . we don't need free domain . 
fyi my server guy got stuck due to this issue . then i debug the script and find out that your free domain service is down . due to that, this issue occur . 

you just need to handle that in your script & update the document according. 

Thanks
