### ISSUE TITLE
VideoJs Plugin Not Releasing Connections

### ISSUE THREAD

**Issue by hikeeba** [ant-media/Ant-Media-Server#4851]
### Short description

__We have been using VideoJs with the Ant Media WebRTC plugin and it plays videos well, but it does not appear to release or clean up connections.__

https://github.com/ant-media/videojs-webrtc-plugin

### Environment

* Operating system and version: Windows 10 (Client) Ubuntu (Server)
* Java version: ?
* Ant Media Server version: Enterprise 2.5.3
* Browser name and version: Chrome 110.0.5481.178 

### Steps to reproduce

1. Load VideoJs and the Ant Media plugin.
2. Play a WebRTC video using `player.src(...)`. We'll call this `Source 1`.
3. Using the same player instance, play a different WebRTC video using `player.src(...)`. We'll call this `Source 2`.

Another method:

1. Load VideoJs and the Ant Media plugin.
2. Play a WebRTC video using `player.src(...)`. We'll call this `Source 1`.
3. Call `player.dispose()`.

In either scenario, when looking at the number of WebRTC viewers in Ant Media, notice that the number of viewers for `Source 1` does not go down. It will only go down if the page reloads (F5).

### Expected behavior
__When the src changes or the player is disposed, any existing WebRTC connections are closed and cleaned up.__

### Actual behavior
__All previous connections are kept alive for the life of the player, even if they are no longer being used to play anything.__

### Example
__I'll work on providing a workking code sample/example to demonstrate this. Right now it's in a React app in a private repo, but I'll work on recreating it in a different environment.__

**Comment by mustafaboleken** [comment]
Thank you for the issue. I put it into the backlog. We will schedule it in the next sprint.

**Comment by mekya** [comment]
I think we need a PR in StreamApp to fix this issue @mustafaboleken
