### ISSUE TITLE
/v2/vods/create api call ignores the vod folder path

### ISSUE THREAD

**Issue by Netbulae** [ant-media/Ant-Media-Server#4853]
### Short description
We have two ant servers behind a load balancer that record locally and transfer the vod's to a shared storage mount point.
For the app's we added the vod folder path.

When we use the api to upload clips generated elsewhere the get put in the /streams folder but not in the vod subfolder.
So when the load balancer switches to one of the servers and the mp4 is not on that local /streams folder the clients get 404 errors.

### Environment

* Ant Media Server version:
2.5.3

### Steps to reproduce
1. use the api to upload a vod mp4 with /v2/vods/create
2. stream the uploaded mp4 through the load balancer.
3.

### Expected behavior
We expect the vod folder setting to be respected when uploading a vod mp4

### Actual behavior
It uploads it to the live streams folder

**Comment by yashtandon113** [comment]
@Netbulae 
Thanks for posting the issue.
Are you using the AMS application settings for VoD streaming Folder? VoD files are expected to upload to the streams folder by default. You can use the symbolic link to upload your VoD file to another folder.

Please correct me if I misunderstand something.

**Comment by Netbulae** [comment]
No we use self hosted enterprise. I don't understand the symbolic link comment. The symbolic link is there in the streams directory and points to the vod. How do I upload it to there? As far as I can see there are no directory parameters in the api call.

**Comment by yashtandon113** [comment]
@Netbulae 
Could you please check to see if the symbolic link pointing to the streams directory still exists? There is a [known bug](https://github.com/ant-media/Ant-Media-Server/issues/4748) with symbolic links in v2.5.3 that will be fixed in an upcoming version 2.6.0. I can send you the snapshot version.

Also, check [this document](https://resources.antmedia.io/docs/recording-live-streams?highlight=Storing%20recordings%20to%20another%20directory) to create a symbolic link for storing recordings in another folder.

If it is still unclear, we can check it together.

**Comment by Netbulae** [comment]
Yes the symlinks are there to the vod folder. The document you link to is for setting the streams directory to another folder but we have the streams recording locally and a muxer script that moves them to the vod folder after recording.

We expected the uploaded vod to go to the vod folder (symlink) and not the streams folder (local disk)

**Comment by yashtandon113** [comment]
@Netbulae
So, as far as I understand, your streams are recording in the streams directory and then moving to the vod folder using a user-defined script, and you want the same for uploading VOD files.

Please correct me if I am wrong.

**Comment by Netbulae** [comment]
@yashtandon113 Yes that would be perfect!

**Comment by yashtandon113** [comment]
@Netbulae
For uploaded VOD files, use **vodUploadFinishScript** feature, which is similar to record muxer script. Please see [this document](https://antmedia.io/docs/guides/publish-live-stream/user-defined-scripts/#vod-upload-finish-process) for more information.

I hope it helps.

**Comment by yashtandon113** [comment]
@Netbulae
Have you looked into the suggested solution? Please let us know if you have any questions.

**Comment by mekya** [comment]
Thank you @yashtandon113 and @Netbulae for this conversation. 

@Netbulae please let us know if the solution provided by @yashtandon113 does not help you.

I'm just closing this issue and feel free to re-open it if it does not work for you.

Cheers
