### ISSUE TITLE
Cameras after restart server

### ISSUE THREAD

**Issue by jorrego** [ant-media/Ant-Media-Server#4858]
Hi

When I restart the server it doesn't reconnect to the RTSP cameras. An automatic reconnect is possible after restart server? Do I need mark any option or run a command?

**Comment by yashtandon113** [comment]
@jorrego
Please check my answer on the following link: https://community.antmedia.io/topic/1629-autostart-broadcast/?do=findComment&comment=6049

**Comment by mekya** [comment]
Thank you @yashtandon113 for your answer.  I'm pasting the answer below because we may archive the community forum. 

> Hi [@twister5800](https://community.antmedia.io/profile/1172-twister5800/)
> I hope you are doing well.
> 
> Auto fetcher has been disabled by default in v2.5.3 and above. To enable it, add the following flag to the /usr/local/antmedia/webapps/App-Name/WEB_INF/red5-web.properties file:
> 
> settings.streamFetcherAutoStart=true
>
> After making the change, restart the server once.


I'm closing this issue. Please feel free to re-open if it does not work for you @jorrego

**Comment by jorrego** [comment]
Thank

> @jorrego Please review my response for the same question at the following link: https://community.antmedia.io/topic/1629-autostart-broadcast/?do=findComment&comment=6049
> 
> You can also participate in the community to offer ideas and to get solutions from questions that have already been answered.

Thanks. It works for me.

**Comment by mekya** [comment]
Thank you for the update. 

Please let us know if we can help you with anything

Cheers ;)
