### ISSUE TITLE
Fix readlink error if Java is not installed

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#4864]
### Short description
In the installation script; If there is no Java on the system, readlink command gives an error.

```
Try 'readlink --help' for more information.
```

Reference link: https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L20

**Comment by mekya** [comment]
This issue has been merged and I'm closing the issue 

Thank you Mr. @muratugureminoglu
