### ISSUE TITLE
Is there an embedded SDK for two-way video call with WebRTC?

### ISSUE THREAD

**Issue by jgcman** [ant-media/Ant-Media-Server#4865]
Hi.

Is there an embedded SDK for two-way video call with WebRTC?

I'm looking for that.
But the embedded SDK I found below is only capable of one-way broadcasting.
https://github.com/ant-media/WebRTCEmbeddedSDKReference
> Embedded SDK is a C++ library that captures the camera stream from RTSP url and restreams it to the web browser with WebRTC. By using WebRTC, clients do not need to install any third party tool on their devices. Instead they can use the browsers only. Also the video latency is less than 1 seconds.

**Comment by yashtandon113** [comment]
@jgcman
The Embedded SDK is intended for capturing the RTSP URL.

You can use native SDKs such as Android, IOS, and others for WebRTC. Please see https://antmedia.io/docs/category/sdk-integration/.

You can also ask your questions on [community.antmedia.io](https://community.antmedia.io).

**Comment by jgcman** [comment]
@mekya @yashtandon113 

I am sorry my late reply and Thanks for your support.
If that feature is needed from us, we will request it as an additional ticket.
