### ISSUE TITLE
Imported VOD files do not play

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4866]
### Short description
Imported VODs from a directory using [importVoDs ](https://antmedia.io/rest/#/VoD%20Rest%20Service/importVoDs) REST API.
Though the VODs are imported and the directory is linked, the VoDs do not play.
#4535 

### Environment
* Ant Media Server version: AMS v2.5.3 

### Steps to reproduce
1. Import VoD files from a directory using [importVoDs](https://antmedia.io/rest/#/VoD%20Rest%20Service/importVoDs)
2. Play the imported VoDs

### Expected behavior
The imported/linked VoDs should play.

### Actual behavior
The imported VoDs do not play.
 

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
@mustafaboleken please review and merge it
