### ISSUE TITLE
streamID not defined in NPM media_manager.js throws error on applyConstraints function call

### ISSUE THREAD

**Issue by fedezubo** [ant-media/Ant-Media-Server#4886]
### Short description

Calling applyConstraints throws an streamID undefined error. This is most likely a leftover argument after issue #4598 was sorted in NPM release 2.5.1

The leftover streamID argument is on line [1340](https://github.com/ant-media/StreamApp/blob/c86d661f197238383b5eb75a421e58ae8fb6571e/src/main/webapp/js/media_manager.js#L1340)

and it throws the error in the image attached. Please disregard the line that is shown in the error since we are on 2.5.3 and the master branch seems to be ahead of the enterprise release

### Environment

* Ant Media NPM version: 2.5.1

### Steps to reproduce
1. Call the function
2. Function runs fine
3. Error shows up 

### Expected behavior
shouldn't use undefined parameters

### Actual behavior
uses streamID which is undefined after issue #4598 deprecated old applyConstraints function

 

![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/43973729/223726965-97822cb1-1b08-4f8f-97ee-5d03b600d52d.png)

**Comment by mekya** [comment]
Thank you for the issue @fedezubo . Moving to the backlog to schedule.

**Comment by mekya** [comment]
Hi @fedezubo,

[This fix](https://github.com/ant-media/StreamApp/pull/356) should resolve this issue as well. 

Please check and let us know if it works for you. 

I'm currently closing this issue and feel free to open if it does not work for you. 

Regards
Oguz
