### ISSUE TITLE
API resource "stream-info" return void array

### ISSUE THREAD

**Issue by jorrego** [ant-media/Ant-Media-Server#4890]
I call the resource "v2/broadcasts/{id}/stream-info" (using on id the streamID value) but the response is a void array: 
```
[]
```

On the documentation (https://antmedia.io/rest/#/BroadcastRestService/getStreamInfo) it should return me and array with this structure:

```
[
  {
    "videoHeight": 0,
    "videoWidth": 0,
    "videoBitrate": 0,
    "audioBitrate": 0,
    "videoCodec": "NOVIDEO"
  }
]
```
The camera is working.

**Comment by yashtandon113** [comment]
@jorrego
Thanks for reporting the issue.

Api appears to be working normally on my end. When the streamId is wrong, the response is usually empty. Please also double-check that the Application name is correct.

If the problem persists, we can investigate it together.

**Comment by jorrego** [comment]
@yashtandon113 

When I use an incorrect streamId, the server response a HTML message and 404, when the streamId is correct it show me "[ ]" and 200.

The camera streaming is by RTSP, no RTMP. Is it a problem to get this information?

**Comment by yashtandon113** [comment]
@jorrego
Even if the streamId is incorrect, you should not receive a 404 or 403 response because the API call is correct. Only that streamId is not publishing on that server.

Their is no problem to get this information using the mentioned Rest API. Could you please send your AMS temporary access to yash.tandon@antmedia.io?

**Comment by jorrego** [comment]
@yashtandon113 

I sent you an email with the access.

**Comment by yashtandon113** [comment]
@jorrego 
Thank you for providing access.
As I tested on my end as well, there is an issue with this Rest API call on the Community edition, whereas it appears to be fine on the Enterprise edition.

**Comment by jorrego** [comment]
@yashtandon113
I installed the 2.5.3 version but the AMS panel shows me as installed the 2.5.2 20230105_1947 version. Which lower version should I downgrade my AMS installation to get the response from that API call?

**Comment by yashtandon113** [comment]
@jorrego 
This Rest API end point is not available in the Community edition. Not only this, but API calls related to the WebRTC adaptor are not available in the community edition.
