### ISSUE TITLE
AMS (snapshot v2.6.0) is not utilizing GPU automatically

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4893]
### Short description
Installed AMS on a GPU-optimized server (on both x86 or Arm64), but the server did not automatically use the GPU driver.

### Environment
* Operating system and version: Ubuntu 20.04 and 22.04
* Ant Media Server version: v2.6.0 snapshot

### Steps to reproduce
1. Launch any GPU optimized server on AWS (g4dn.xlarge or G5g.xlarge)
2. Install AMS
3. Install CUDA with GPU driver by following your distribution. You can get commands from [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network) after putting your distribution details
4. After the installation, reboot the server and restart AMS

### Expected behavior
AMS should automatically use the GPU with the nvenc_h264 encoder.

### Actual behavior
The server did not use the GPU driver automatically. I had to change the encoder name in the red5-web.properties file by adding the below property in the /usr/loca/antmedia/webapps/LiveApp/WEB-INF folder.

`settings.encoding.encoderName=h264_nvenc
`

**Comment by lastpeony** [comment]
After installing CUDA 11.8, I tested this on my local Ubuntu 20.04 and confirmed that Ant Media was utilizing the CUDA encoder upon startup. As reported in the issue, Ant Media did not switch to the CUDA encoder upon startup when tested with some other versions (including the latest).
Use following commands to install CUDA 11.8
```
wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
sudo sh cuda_11.8.0_520.61.05_linux.run
```
The cause of this could be attributed to the version of the bytedeco.cuda.presets library.
![image](https://user-images.githubusercontent.com/24750845/235429703-28835ae2-bc6a-4879-a121-10974bda46bf.png)

Still, this needs to be tested on cloud provider instance with a GPU. I will update my comment.

**Comment by yashtandon113** [comment]
I checked and confirmed that the server uses the GPU automatically when CUDA 11.8 is used.

If the user is using CUDA 12 or higher, the encoder name must be entered in the properties to use the GPU, as specified in the issue.
