### ISSUE TITLE
Issue with scheduling pre-recorded live streaming using VOD

### ISSUE THREAD

**Issue by roseailsaa1** [ant-media/Ant-Media-Server#4908]
When we schedule pre-recorded live streaming using VOD. If I upload low size video then it works fine and we successfully go live on Facebook and RTMP but if I upload high quality then it starts broadcasting on the AMS dashboard but it's not connected to a social platform

**Comment by yashtandon113** [comment]
Hi @roseailsaa1 
Could you please share more information about your uploaded video, such as the resolution and bitrate, so that we can try it on our end? Is the same video publishing on YouTube?

**Comment by yashtandon113** [comment]
@roseailsaa1, Is your problem resolved? If not, please feel free to ask any questions.
