### ISSUE TITLE
Learn Unity and Draco Integration

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#491]

**Comment by jasonhbartlett** [comment]
Hi @mekya I see a few issues you have posted with the word "Unity" in the title but there isn't much info about what you are doing exactly.
I have recently installed AntMedia Server running in Bash on Windows and the player works great, but now I am trying to play the stream in Unity.  I'm using the VideoPlayer component like this:
![image](https://user-images.githubusercontent.com/22244576/50361696-876bbf80-0532-11e9-94db-0eee5d5d13dc.png)

But getting this error when I try to play the video stream:
![image](https://user-images.githubusercontent.com/22244576/50361733-aa966f00-0532-11e9-8eaf-c83718f6377f.png)

If getting a video stream from the AntMedia Server to play inside Unity is something you have got working, I would love to know how you did it!  Thanks!

**Comment by mekya** [comment]
Hi @jasonhbartlett ,

We actually working on something different. Some of the teammates are working about 3d model rendering for a project which is a superset of Ant Media Server.  So this issue is not about rendering videos on unity. 

Anyway, from the error logs in the screenshot. I think you may need to provide the full stream url not the web page that has a HTML5 player.

for your case, giving the following link may work http://localhost:5080/WebRTCApp/streams/451...595.m3u8 if player supports HLS playback.   

Also you can check this out 
https://github.com/ant-media/Ant-Media-Server/wiki/Play-Live-and-VoD-Streams-and-Previews

**Comment by jasonhbartlett** [comment]
Hey @mekya ,
Yeah I just did a google search for "Unity HLS plugin" and NexPlayer was one of the first of results.  Unfortunately that repo just points to their commercial website and it doesn't seem they have a NexPlayer Unity SDK anymore.. I'm e-mailing them about it.
Some indication may be that other Unity assets available on the Unity Asset Store may include a HLS plugin.  Looking into that.
This is a research paper that may prove useful: https://www.researchgate.net/publication/320312594_Augmented_Reality_as_a_Telemedicine_Platform_for_Remote_Procedural_Training 
I'll tell you what though, based on how hard it has been to find a solution for live streaming in Unity, considering all the Unity forum posts I've seen about RTMP and HLS with Zero responses, .. If we could figure this out it would be pretty epic and worth sharing.
