### ISSUE TITLE
Noticeable worse audio when using WebRTC compared to rtmp streaming source

### ISSUE THREAD

**Issue by fedezubo** [ant-media/Ant-Media-Server#4924]
### Short description

There's a noticeable audio compression when usign WebRTC streaming. To the point of almost destroy audio tracks on a pre-recorded video. 

The issue is not present when using rtmp as a source

### Environment

* Ant Media Server version: 2.5.3 enterprise

### Steps to reproduce
1. Open the publish sample
2. Set a music video as source
3. Listen to audio quality
4. Repeat by using rtmp streaming to the same ID
5. Notice extreme difference

### Expected behavior
If settings are the same between sources there should be audio quality consistency

### Actual behavior
Audio quality is noticeably worse when using WebRTC

**Comment by mekya** [comment]
Hi @fedezubo ,

Thank you for the issue. It's a known issue #4642 and is currently under development.  

I am closing this issue as duplicate. Please feel free to open if I've made a mistake.
