### ISSUE TITLE
There is a problem in installing the ant media server

### ISSUE THREAD

**Issue by Samriddha01** [ant-media/Ant-Media-Server#4941]
# Issue
While installing the ant-media-server-community-2.5.3.zip, I am getting an error like mentioned below. PFA.
_**unzip: cannot find or open ant-media-server-community-2.5.3.zip, ant-media-server-community-2.5.3.zip.zip or ant-media-server-community-2.5.3.zip.ZIP.**_

Initially, I thought that it could happen because of the ubuntu 20.0 then I installed the ubuntu 18.04.6 but even after that the issue is not resolved.

![amserror](https://user-images.githubusercontent.com/83784034/228130662-e49b8760-c765-481e-a6e5-d63eb0c517fa.PNG)

**Comment by muratugureminoglu** [comment]
Hi @Samriddha01 

unzip: cannot find or open ant-media-server-community-2.5.3.zip means "no zip file or zip file is broken".  Could you please show how you ran the installation script?

Example Usage: `sudo ./install_ant-media-server.sh -i [ANT_MEDIA_SERVER_DOWNLOADED_FILE]`

`sudo ./install_ant-media-server.sh -i ant-media-server-community-2.5.3.zip`    # The script and the zip file are in the same directory.

**Comment by Samriddha01** [comment]
My issue has been resolved now. thank you!
