### ISSUE TITLE
Unable to play API created playlists, though they're working great from the Web UI

### ISSUE THREAD

**Issue by walt93** [ant-media/Ant-Media-Server#4945]
### Short description
I'm trying to use Ant Media Server with a scheduler to play pre-recorded files over a livestream. My Roku channel has a RTMP server. We can beam to it from Ant Media Server and pack our RTMP full of podcasts this way.

### Environment

* Ubuntu 20.04.6 LTS
* Java version:  openjdk 11.0.18 2023-01-17
* Ant Media Server version: I don't see the version # anywhere in the control panel, looks like I installed whatever was shipping Dec 12 22', had installed 2.5.1 previously, so it's likely 2.5.2 (?)
* Browser name and version: N/A

### Steps to reproduce
1. Open web interface, create a playlist using, lets say... this video https://b-news.b-cdn.net/Conspyre/Balincaga.mp4, doesn't really matter, any MP4 on the CDN will do…
2. Add a RTMP endpoint to it, I'm using the RTMP server my OTT provider gives me for my Roku channel
3. Start the playlist playing. Watch it play on Roku. 😎🎥🍿

...

4. From python, call /v2/broadcasts/create with _identical parameters_ that we set up with the web interface
5. From python, POST to /v2/broadcasts/{stream_id}/rtmp_endpoint and add our RTMP endpoint
6. From curl, pull on both of these to verify that their JSON payloads are identical save for the timestamp
7. Start the API created playlist playing
8. Watch the UI light up *as if* the video were playing
9. Watch the Roku channel and there is no video playing

### Expected behavior
Expect for the API behavior to match the Web interface behavior. _🤔they should, the JSON payloads of each appear identical_

### Actual behavior
The web interface, when you go to play the video (from the web interface, or, from the /v2/broadcasts/{stream_id}/start API, behavior is identical in both cases), the UI lights up, shows the video is playing, though the speed seems to vary from 0.91x to 500x (because presumably there is nothing on the other end so its just spooling through the file). Nothing happens on my Roku channel. I don't have access to the Roku RTMP to get logs.

### Logs
Try `wget adserver.conspyre.tv/antmedia_logs.tar.gz` and just look at the most current to see my attempts to fire this off last night, apologies, I didn't prune those logs…

### Code

Here's some python code, maybe something will stand out?

```
def schedule_on_ant(
    cdn_url: str, rtmp_url: str, metadata: Dict[str, str]
):
    """Schedule this title on the ant media server

    Args:
        cdn_url: full path to the file on the CDN
        metadata: dictionary containing:
            metadata["title"]: title of the video e.g. "America's Mom 3/2/23"
            metadata["description"]: description of the video e.g. "Use code Mom on MyPillow.com"

    Returns:
        a string with the URL to start the scheduled playlist playing, or None if an error occurred
    """
    logging.info("schedule_on_ant (cdn_url:%s, rtmp_url:%s, metadata:%s)",
        cdn_url, rtmp_url, metadata)

    stream_id = re.sub(r"\W+", "_", metadata["title"]).lower() + "_" + str(time.time())
    timestamp = int(time.time())
    stream_id = f"{stream_id}_{timestamp}".replace(".", "_")

    headers = {
        "accept": "application/json",
        "Content-Type": "application/json"
    }

    create_url = f"{ANT_BASE_URL}/LiveApp2/rest/v2/broadcasts/create"
    rtmp_endpoint_url = f"{ANT_BASE_URL}/LiveApp2/rest/v2/broadcasts/{stream_id}/rtmp-endpoint"
    start_url =  f"{ANT_BASE_URL}/LiveApp2/rest/v2/broadcasts/{stream_id}/start"
    delete_url = f"{ANT_BASE_URL}/LiveApp2/rest/v2/broadcasts/{stream_id}"

    create_data = {
        "name": metadata["title"],
        "type": "playlist",
        "publish": True,
        "streamId": stream_id,
        "playListItemList": [
            {
                "streamUrl": cdn_url,
                "type": "VoD"
            }
        ]
    }

    rtmp_data  = {
        "rtmpUrl": rtmp_url,
        "endpointServiceId": stream_id,
        "status": "created",
        "type": "generic"
    }

    # Create the stream
    if post_endpoint(create_url, create_data, headers, f"create stream {stream_id}") != 200:
        return None, None

    # add the RTMP
    if post_endpoint(rtmp_endpoint_url, rtmp_data, headers, "add rtmp") != 200:
        return None, None

    return start_url, delete_url

def post_endpoint(url, data, headers, theThing):
    """
    Make a POST request to the endpoint with the specified data and headers and flash/log errors
    """
    try:
        logging.info("*** url:%s", url)
        logging.info("*** body:%s", data)
        response = requests.post(url, json=data, headers=headers)
        logging.info("*** response:%s", response)
        response.raise_for_status()  # Raises a requests.HTTPError if response status is not 2xx
    except requests.exceptions.RequestException as err:
        flash(f"Error {theThing} failed {err}", "error")
        if hasattr(err, "request") and err.request is not None:
            flash(
                f"Request headers = {err.request.headers} body = {err.request.body}",
                "error",
            )
        if hasattr(err, "response") and err.response is not None:
            flash(f"Response: {err.response.status_code} {err.response.text}", "error")
        return err.response.status_code
    return 200
```

**Comment by yashtandon113** [comment]
@walt93 
Thank you for providing such detailed information about the problem.

I tried to reproduce the same issue on my end using Rest API calls, and everything appears to be fine. The only difference is that I used the YouTube RTMP endpoint instead of Roku.

Here are my Postman Curl samples:

**Create Playlist:**
```
curl --location 'http://localhost:5080/LiveApp/rest/v2/broadcasts/create' \
--header 'Content-Type: application/json' \
--data '{   "name": "playlisttest",
    "streamId": "test",
    "type":"playlist",
    "playListItemList": [
        {
            "streamUrl": "http://localhost:5080/LiveApp/streams/377382782018593494909713.mp4",
            "type": "VoD"
        }
    ]}'
```

**RTMP Endpoint:**
```
curl --location 'http://localhost:5080/LiveApp/rest/v2/broadcasts/test/rtmp-endpoint' \
--header 'Content-Type: application/json' \
--data '{
    "rtmpUrl":"rtmp://a.rtmp.youtube.com/live2/8j68-0jhr-679s-pdam-81rg"
}
'
```
**Start broadcast:**
```
curl --location --request POST 'http://localhost:5080/LiveApp/rest/v2/broadcasts/test/start' \
--header 'Content-Type: application/json'
```

Now, when I used your shared video (https://b-news.b-cdn.net/Conspyre/Balincaga.mp4), I found that it is H265 encoded, which the RTMP protocol does not support. When I transcoded this video with H264 and enabled one ABR on the server side, it began streaming on YouTube as well.

If you're having issue with the shared mp4 file/URL, I believe this could be the problem.

**Comment by walt93** [comment]
Getting into this now, what did you mean by "and enabled one ABR on the server side", my media is at present encoded at just a single bitrate. Are we running a real-time transcoder here?

**Comment by yashtandon113** [comment]
@walt93 
I tested it on the Enterprise edition, which allows us to transcode with different codecs (H264) by enabling ABR. It can be published to the endpoint once it has been converted to H264.

This feature is not available in Community Edition so if you are using CE, so please make sure that your mp4 files are H264 encoded.

**Comment by yashtandon113** [comment]
@walt93
Please let us know if you have any further questions.

**Comment by walt93** [comment]
Yash-I forgot to come back to this one. I've got it working, thanks to your help with the curl commands. Thanks for following up. Sent from a mobile device.On Apr 7, 2023, at 4:47 AM, yashtandon113 ***@***.***> wrote:﻿
@walt93
Please let us know if you have any further questions.

**Comment by yashtandon113** [comment]
@walt93 
Thanks for confirming. I am closing this issue now.
