### ISSUE TITLE
Upgrade : Disk space not enough - although there is....

### ISSUE THREAD

**Issue by francoisdutoit** [ant-media/Ant-Media-Server#4946]
### Short description
I'm trying to upgrade to the latest enterprise version - but getting a "Disk space is not enough." Error. 

Disk space :  (25.5 GB / 490 GB)

There is enough space on my disk - so not sure why this is happening...

### Environment
* Operating system and version: Ubuntu 20.04
* Ant Media Server version: 2.4.3 20220418_2241
* Browser name and version:

**Comment by muratugureminoglu** [comment]
Hi @francoisdutoit 

Can you share the output of the following commands?

```
df -h
```
```
du -sh /usr/local/antmedia/
```

**Comment by francoisdutoit** [comment]
Hi,

All good now - I just did a fresh install.  Thanks!

**Comment by pank999** [comment]
root@Ubuntu-2004-focal-amd64-base ~ # du -sh /usr/local/antmedia/
220G    /usr/local/antmedia/
root@Ubuntu-2004-focal-amd64-base ~ # sudo ./install_ant-media-server.sh -i ant-media-server-community-2.7.0.zip -r true
Disk space is not enough.


tmpfs           6.3G  916K  6.3G   1% /run
/dev/md2        436G  227G  188G  55% /
tmpfs            32G     0   32G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/md1        989M   97M  841M  11% /boot
tmpfs           6.3G     0  6.3G   0% /run/user/0
