### ISSUE TITLE
WebRTC Stream not playing on Android 7.0

### ISSUE THREAD

**Issue by SanthoshRajendiran** [ant-media/Ant-Media-Server#495]
### WebRTC Sample Application not playing incoming stream

__The sample android application was not able to decode and play an incoming stream to device. Debug shows issues with null video decoder not getting initialized, and so the null video decoder not able to decode incoming frames. Working on major other android devices__

### Environment

[] Operating system and version: Android 7.0 - Moto C Plus
[] Ant Media version: Ant Media Enterprise 1.6.0

### Expected behavior
__Decode and Play the incoming stream on the surface view__

### Actual behavior
__Playing audio with echo (not sure), but video is not getting decoded, and hence output is not visualized__

### Steps to reproduce
1.  Run the android sample webrtc app code on the device
2.  Debug the output

### Logs
__[bugwebrtc.txt](https://github.com/ant-media/Ant-Media-Server/files/2509168/bugwebrtc.txt)__

**Comment by mekya** [comment]
Yeah it says NullVideoDecoder in the log. 

It is likely that Moto C Plus does not have a supported hardware decoder for h.264.
Have you tried soft decoding?

Regards,
A. Oguz

**Comment by SanthoshRajendiran** [comment]
Haven't tried soft decoding yet, as it will be an extra overload on the application. Will give it a try and check for the performance.

**Comment by SanthoshRajendiran** [comment]
Update on the issue:

We tried the application with another device - Honor 7S, where chipset is Mediatek MT6739. It supports H264, still is not able to receive and play the stream.

**Comment by mekya** [comment]
We've made an update in android SDK about supporting additional chipsets like Mediatek. You may try the new SDK version. 

Regards,
A. Oguz

**Comment by SanthoshRajendiran** [comment]
@mekya Thank you for the response. Can you please share the updated android SDK.

**Comment by mekya** [comment]
I think this issue is resolved. Please re-open it if it does not work for you
