### ISSUE TITLE
Flutter CI cannot publish new versions

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4956]

**Comment by USAMAWIZARD** [comment]
I tried to run the publish command in my local env by authenticating and I was able to publish it without any problem.
I have replaced the publishing credential in CI with the credentials I used in my local env but still does not work

**Comment by USAMAWIZARD** [comment]
Flutter published from CI  [here](https://github.com/ant-media/WebRTC-Flutter-SDK/actions/runs/4817110257/jobs/8577426049)
