### ISSUE TITLE
Live stream with autoplay don't work on Chrome

### ISSUE THREAD

**Issue by sebastianzabrzyski** [ant-media/Ant-Media-Server#496]
# Issue

### Short description
There's a problem when you try to play live stream on Chrome using autoplay=true like this "http://[SERVER_IP]:5080/LiveApp/play.html?name=[STREAM_NAME]&autoplay=true

The browser shows flowplayer window with play button, but the stream won't start if you click it. If you remove the autoplay parameter and click play button, it works fine. That's because antmedia uses old hls library, also the new library should be loaded before flowplayer.js, so the solution is to update files WebRTCApp/play.html and LiveApp/play.html with code:

```
<!-- 1. skin -->
<link rel="stylesheet"
	href="//releases.flowplayer.org/7.2.7/skin/skin.css">
<!-- 3. flowplayer -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.10.1/hls.min.js"></script>
<script src="https://releases.flowplayer.org/7.2.7/flowplayer.min.js"></script>
```

### Environment

Browser: Chrome v.69

### Expected behavior
Stream should start automatically with autoplay=true parameter

### Actual behavior
Flowplayer won't start stream, even if you click the play button.

### Steps to reproduce
1. start live stream
2. visit http://[SERVER_IP]:5080/LiveApp/play.html?name=[STREAM_NAME]&autoplay=true on Chrome
3. try to play stream

**Comment by mekya** [comment]
hi @sebastianzabrzyski ,

Sorry for late reply. 

You're right. It's a weird issue. It works on some cases but does not on others. I've come across this issue somehow. Let me check again and update you 


Regards,
A. Oguz

**Comment by SelimEmre** [comment]
Hi @sebastianzabrzyski,
Thank you for your interest. Do you still have problems? If the problem persists, can you re-open this issue?
