### ISSUE TITLE
Media server won't start due to Java issue

### ISSUE THREAD

**Issue by Donkwillis** [ant-media/Ant-Media-Server#497]
# Issue
Ant Media Server not starting.

### Short description
__Brief description of what happened__
I have an Ubuntu Server which I am trying to start the Ant Media Server on.  I downloaded Java and set the JAVA_HOME.  However, after running the command to start it fails on a java error.

### Environment

[] Operating system and version: Ubuntu Server 18.04 
[] Java version: 'Default' latest
[] Red5 version: Not sure

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

I posted a log below of start-debug

https://pastebin.com/imiymSdU

Thank you!

**Comment by sebastianzabrzyski** [comment]
I don't see anything wrong here, my debug log looks the same and it accepts streams without issue. How do you know the server is not starting? Can you access the manager at http://[server ip]:5080/, have you done any streaming tests yet?

**Comment by Donkwillis** [comment]
Thank you for getting back to me so quickly.  I tried running it, but it
kept kicking back a Java error.  I went ahead and installed the ant media
server per the documentation and now it is up and running.  When installing
the ant-media server, I noticed it grabbed more Java files, so I think I
just failed to deliver the proper requirements.

Peter
