### ISSUE TITLE
I am unable to repost a stream, for example in the screenshots. I have read as many articles and posts as possible and have not found a solution.

### ISSUE THREAD

**Issue by FranciscoNetoBr** [ant-media/Ant-Media-Server#4971]
I am unable to repost a stream, for example in the screenshots. I have read as many articles and posts as possible and have not found a solution.

VPS Settings - Oracle Cloud
Type: VM.Standard.A1.Flex
Number of OCPUs: 4
Network Bandwidth (Gbps): 4
Memory (GB): 24
Image: Canonical-Ubuntu-22.04-aarch64-2023.02.15-0

Ant Media simply doesn't play the URL (ex. rtmp://129.148.56.238/Youtube/Lz6b1W9LQq3d1677958482905)
--------------- If you have a solution, please provide a more detailed explanation. I am not an analyst or system developer.

![Captura1](https://user-images.githubusercontent.com/127934645/229871892-a9d2ecdd-22c1-430a-9b85-1b66ba2b5f5d.png)
![Captura2](https://user-images.githubusercontent.com/127934645/229871996-33d4f639-f9be-4864-bedc-dba01275757f.png)
![Captura3](https://user-images.githubusercontent.com/127934645/229872020-2ac89a23-5403-4b7c-a2ce-d46c89d44e77.png)

Second question, is it possible to use Ant Media to play the URL in the format - https.:// (Example: https://www.youtube.com/watch?v=jfKfPfyJRdk ) ??

--------------- If you have a solution, please provide a more detailed explanation. I am not an analyst or system developer.

![Captura4](https://user-images.githubusercontent.com/127934645/229872143-f1aa710e-5abe-42d6-bbb2-ca36f28782a6.png)

Thanks in advance for any help and attention given to my problem.

Francisco Neto

**Comment by FranciscoNetoBr** [comment]
No answer? 
What am I doing wrong?

**Comment by Mohit-3196** [comment]
Hi all,
We are discussing these here https://github.com/orgs/ant-media/discussions/5021

FYI Please.
