### ISSUE TITLE
Upgrade and Downgrade between Community and Enterprise editions

### ISSUE THREAD

**Issue by ed-fruty** [ant-media/Ant-Media-Server#4974]
Could you provide please step by step instruction how to upgrade or downgrade an existing Ant Media Server instance between Community and Enterprise editions?

I saw this [issue](https://github.com/ant-media/Ant-Media-Server/issues/508) but I didn't get the right answer, there is the answer how to upgrade from older versions.

Case 1.
I have Community Edition instance of Ant Media Server and want to try to upgrade to Enterprise Edition with saving current instance configurations (applications, their settings, users etc.). What steps do I have to do?

Case 2.
I tried Enterprise Edition and for some reason I want to switch back to the Community edition and save all current settings and properties (which are available in community edition).  What steps do I have to do in this case?

Thanks.

**Comment by mekya** [comment]
Thank you @ed-fruty, I've put it to the plan and one of my colleagues will give you an answer this week.

**Comment by muratugureminoglu** [comment]
Hi @ed-fruty 

Since the Enterprise version and the Community version are two different projects, unfortunately, you cannot get other settings except for users. You should readjust the Application settings.

To restore the user settings:
```
systemctl stop antmedia
cp -p /usr/local/antmedia-backup-*/server.db /usr/local/antmedia/
systemctl start antmedia
```

**Comment by Mohit-3196** [comment]
Hi All,

Ant Media Server Enterprise Edition supports WebRTC whereas the community edition doesn't have WebRTC signaling and other related supports and both are separate projects.

There could be compatibility issues between the Community and Enterprise editions that could result in conflicts. Also, the configuration settings for the Community and Enterprise editions differ, and the upgrade process may not handle these differences correctly.

Hence a fresh installation ensures that all components are installed and configured correctly for the Enterprise Edition.

For upgrading between different Enterprise editions and community editions themselves, using a -r true flag with the installation script can restore the settings.
Also, they can be restored manually by following these steps https://antmedia.io/docs/guides/upgrading-ant-media-server/#how-do-i-restore-ant-media-server-if-needed

Also, I thank you for your questions and suggestions. I think it is great and in the future, we can implement an easy solution to help migrate between the Community end Enterprise Editions.

Thank you

**Comment by mekya** [comment]
Shall we provide some workaround solution about copying settings file after the installation is done?

**Comment by muratugureminoglu** [comment]
**For Apps:**

1. Copy the following file (from the backup folder) to AMS folder
`/usr/local/antmedia-backup-folder/webapps/{Your_App}/WEB-INF/red5-web.properties`
2. Change the App name into red5-web.properties
`db.app.name=WebRTCApp` to `db.app.name=WebRTCAppEE`

**For Users:**
```
cp -p /usr/local/antmedia-backup-folder/server.db /usr/local/antmedia/
```

**For Other settings:**
```
cp -p /usr/local/antmedia-backup-folder/conf/{red5.properties,jee-container.xml,instanceId} /usr/local/antmedia/conf
```
If the SSL certificate is installed, follow the following.

```
cp -p /usr/local/antmedia-backup-folder/conf/{chain.pem,privkey.pem,fullchain.pem,truststore.jks,keystore.jks} /usr/local/antmedia/conf/
```

Restart the Ant Media Server service as follows.
```
systemctl restart antmedia
```
That's it.
