### ISSUE TITLE
What does the message returned by socket mean?

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#498]
Hi,I am Writing an WebRTCAdaptor to antMedia server EE.
Now I can publish stream to antMedia server.
But there still have some question.
What means about the message returned by socket.
Is there any docs can help me fingerout that?

**Comment by mekya** [comment]
Hi @arnoldcui ,

Sorry for late reply.

We've this doc for that
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Details

I hope it helps. If not, please let me know. 

Regards,
