### ISSUE TITLE
Generate Preview Functionality Not Working Correctly

### ISSUE THREAD

**Issue by sahiljain2497** [ant-media/Ant-Media-Server#4980]
### Short description
We have enabled generate preview option in the console and have s3 integration. We only see the _finished thumbnail uploaded to our bucket after stream ends and no other thumbnail is created/uploaded while streaming every 5s.

### Environment

* Operating system and version: Installed via aws marketplace
* Java version: 
* Ant Media Server version: Enterprise Edition 2.5.3 20230107_0851
* Browser name and version: Tried on Web, IOS and Android SDK

### Steps to reproduce
1. Enable Generate Preview 
2. Stream Via Webrtc
3. Preview is only generated at end of stream.

### Expected behavior
There should be multiple thumbnails uploaded to s3 bucket as per interval settings (default 5s)

### Actual behavior
only  _finished preview is found in bucket

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by yashtandon113** [comment]
Hi @sahiljain2497
Thanks for creating the issue.
This is an expected behavior in which a new preview overwrites the previous one every 5 seconds for the same stream Id and in the end you will get the finished preview.

As far as I can understand, you want to save all previews that are generated every 5 seconds. I'll talk to my colleagues about it to see if there's any workaround solution.

**Comment by sahiljain2497** [comment]
Hi @yashtandon113 , thanks for looking into this. The issue here is something else here -

I am not getting any previews saved to S3 at every 5 seconds. I see only the finished preview on s3 once the stream has stopped. I have tried streaming for more than 5mins but no preview was created and only _finished was created once stream was stopped.

Here are some use cases we need it for - 

1). we list live streams in our app where we want to show a preview image of the live streams. So basically once the preview image is added to s3 bucket -> lambda is triggered -> streamPreview link is updated in database.

2). we want to use these screenshots for content moderation using aws lambda and aws rekognition.

**Comment by yashtandon113** [comment]
@sahiljain2497 
Thanks for explaining it in detail.

1. When S3 integration is enabled, the mp4 file or preview file uploads to the bucket after the stream finishes.

2. However, if you want to upload the preview to a s3 bucket at the same time, you can use **s3 fuse**. Please see https://github.com/s3fs-fuse/s3fs-fuse for more information on s3 fuse.

You can also quickly mount your preview folder to your S3 bucket by following the steps below:

- Install s3fs

`sudo apt install s3fs`

- Add the credentials

```
echo ACCESS_KEY_ID:SECRET_ACCESS_KEY > /etc/passwd-s3fs
chmod 600 /etc/passwd-s3fs
```

- Mount previews folder of your application to the s3 bucket by creating the mount point.

`s3fs -o dbglevel=info -o curldbg -o allow_other -o use_cache=/tmp/s3-cache your-bucket-name /usr/local/antmedia/webapps/App-Name/previews`

- Once the mount point has been added successfully, run the **df -h** command and look for the mount point in an output. It should be as follows:

`s3fs             256T     0  256T   0% /usr/local/antmedia/webapps/WebRTCAppEE/previews`


I hope it helps.

**Comment by sahiljain2497** [comment]
Thanks for the help @yashtandon113 . I have implemented this and this working great for me. I am just going to try to test this further with cluster mode and iamroles.

I faced this one issue while implementing this but this seems like the correct behaviour.

I was trying to sync bucket/previews to /usr/local/antmedia/webapps/WebRTCAppEE/previews .
- Preview images were syncing while stream was publishing but the finished image would get deleted from bucket immediately maybe because antmedia backend is uploading it s3 as well and deleting it from local system which indeed removes the file from s3 as well because of the sync.

So I had to sync up a different bucket folder name than the folder that the one used by antmedia backend to upload finished preview.

**Comment by yashtandon113** [comment]
@sahiljain2497 
If you are using s3 fuse for previews then you do not have to use AMS s3 integration again to upload the preview.

You can stop uploading preview by changing the settings value. Please check https://antmedia.io/docs/guides/publish-live-stream/Recording-live-streams/#uploading-records-to-s3

By default, the value is 7 which means all mp4, HLS and previews will be uploaded after the stream is finished.

**Comment by sahiljain2497** [comment]
thanks, I have set this to 1 for now, this resolves the problem. 

Also, when the file get updated on S3 there is a 403 received if we try loading image as same point of time. Is there a way to handle this?

**Comment by yashtandon113** [comment]
@sahiljain2497 
Could you please confirm the situation? Is this happening after using s3 fuse or after using the first method of s3 integration? Are you also attempting to load the image directly from a s3 URL or an AMS URL?

**Comment by sahiljain2497** [comment]
I am using s3 fuse. Just tried It happens only with S3 URL and but not with AMS URL.

**Comment by yashtandon113** [comment]
@sahiljain2497 
Then it appears to be related to the permissions on the S3 bucket. You can determine whether the object permission is public or private.

**Comment by sahiljain2497** [comment]
resolved, had to add default_acl='public-read' in s3fs options to enable public access by default instead of updating later again.

**Comment by yashtandon113** [comment]
@sahiljain2497 
Great! Thanks for sharing the information.
Then I am closing this issue now.
