### ISSUE TITLE
Support Data Channel in videojs-webrtc-plugin

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#4990]
**Is your feature request related to a problem? Please describe.**
Support sending messages on data channel with videojs-webrtc-plugin.

**Additional context**
https://github.com/orgs/ant-media/discussions/4981

**Comment by USAMAWIZARD** [comment]
https://github.com/ant-media/videojs-webrtc-plugin/pull/21

**Comment by mekya** [comment]
Closing this issue because it's all merged into the master branches.
