### ISSUE TITLE
Customizable Layout for composite view - RTC -> HLS Scenario in Server-6

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#4991]
[Technical Requirements - HLS Playback.pdf](https://github.com/ant-media/Ant-Media-Server/files/11190360/Technical.Requirements.-.HLS.Playback.pdf)

**Comment by mustafaboleken** [comment]
It's merged into the Media Push Plugin. You can check the instructions from https://github.com/ant-media/Plugins/tree/master/MediaPushPlugin#optional-how-to-add-composite-layout
