### ISSUE TITLE
Question about WebRTC P2P features with Ant Media Community Edition

### ISSUE THREAD

**Issue by jwkim2079** [ant-media/Ant-Media-Server#5000]
Hello there,

I have one question regarding Ant Media Community Edition.
We are trying to check whether Ant Media Community Edition supports WebRTC P2P feature or not. We realized the P2P test failed when we tried to run your peer.html sample on Community Edition.

Can you check if we can use Ant Media Community Edition for WebRTC P2P feature?

Regards,
Gibbs

**Comment by Mohit-3196** [comment]
Hi @jwkim2079 ,
How are you?

WebRTC streaming/WebRTC signaling is an enterprise edition feature. 
Here's the comparison table for the Community Edition and the Enterprise Edition.
https://antmedia.io/docs/get-started/introduction/#community--enterprise-edition-comparison

You can get a trial license for the enterprise edition by writing to contact@antmed.io 
Alternatively, you can get a 5-day free trial of AMS on [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-464ritgzkzod6?sr=0-1&ref_=beagle&applicationId=AWSMPContessa) as well.

Thank you,
Mohit

**Comment by jwkim2079** [comment]
Hi Mohit,

Thank you for your kind response. I am clear now. :)
Thank you for your support again.

Regrads,
Gibbs

**Comment by Mohit-3196** [comment]
Hi @jwkim2079 ,
It is my pleasure :)

Let me know if you need any help with anything else.

Have a good day.

**Comment by mekya** [comment]
I'm closing this issue for now. Please feel free to re-open if it's not ok for you
