### ISSUE TITLE
Cors error on put and post methods

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5001]
When we try to make a post request from another website, it causes a cors error. I tested with fetch, axiom and ajax with { mode: 'no-cors'} parameter but it's not worked. Also I tried adding allowed origins into web.xml but no chance.

Reproduce scenario:

- Create a simple HTML page.
- Serve it on HTTP server
- Try to upload vod file from that website using [rest endpoint](https://antmedia.io/rest/#/VoD%20Rest%20Service/uploadVoDFile).
- It gives cors error.

**Comment by USAMAWIZARD** [comment]
Not reproducible now checked with @mustafaboleken

**Comment by mustafaboleken** [comment]
I double check it if the web.xml file allowed the domain entered properly, on the latest snapshots there is no problem.
