### ISSUE TITLE
New Pods do not pick up connection after scaling up triggers

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#5013]
The newly scaled pods will start pick up connections when new load will come.

**Comment by muratugureminoglu** [comment]
When I try to create this issue on my side, the new pod is triggered by hpa and then I send again the loads with the test tool through the load balancer and the new pod accepts the connections. If more information is provided I can try again.

**Comment by muratugureminoglu** [comment]
I'm currently closing this issue because it's not reproducible.
