### ISSUE TITLE
Keeps Buffering / Does not play on streaming 360 MP4 files as external source or using RTMP on OBS

### ISSUE THREAD

**Issue by sahiljain2497** [ant-media/Ant-Media-Server#5018]
### Short description
I have tried to stream files via OBS, external source and RTMP, but when we try to play the streams they buffer a lot and play only in like frames. I have tested this on a good network speed of 100-400mbps on client side. We would like to know if there is any settings to be modified as well for this

### Environment

* Operating system and version: Enterprise Edition 2.5.3 20230107_0851
* Java version: 
* Ant Media Server version: Enterprise Edition 2.5.3 20230107_0851
* Browser name and version: Chrome

We have cluster deployment over AWS. 

### Steps to reproduce
1. add this url as external source - https://d1h720pygp5zr.cloudfront.net/videoplayback.mp4
2. try to play stream - does not play from dashboard at all. also shows broadcasting330x  as status

1. tried to stream file via obs. 
2. plays only in frames keeps buffering.

1.  add this small file url as external source - https://d1h720pygp5zr.cloudfront.net/Store.m4v
2. does throw alot of 404 while playing stream and buffers in between but somehow plays.

### Expected behavior

Stream should work without buffering. 

### Actual behavior
Stream does not play or keeps buffering

**Comment by sahiljain2497** [comment]
[logs.zip](https://github.com/ant-media/Ant-Media-Server/files/11264130/logs.zip)

**Comment by sahiljain2497** [comment]
We just spotted one more thing, we have our setup with antmedia 2.4.2 and new one with 2.5.3

1). Testing via OBS -
- one video where I see 2.9mb chunks is v2.4.2 streams fine
- other one where I see 1.1mv chunks is latest one buffers alot.

https://user-images.githubusercontent.com/28824550/232868066-6d8840a5-bee2-4781-9325-7265a24a8ba7.mov

https://user-images.githubusercontent.com/28824550/232868073-4035a406-e728-46ad-a165-b24213ea6e2d.mov

**Comment by Mohit-3196** [comment]
Hi @sahiljain2497 ,
How are you?

Thank you for the detailed information.

I checked the two stream sources above.
For the stream source, https://d1h720pygp5zr.cloudfront.net/videoplayback.mp4

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://d1h720pygp5zr.cloudfront.net/videoplayback.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6av01mp41
    creation_time   : 2021-04-16T09:20:58.000000Z
  Duration: 00:15:55.66, start: 0.000000, bitrate: 13197 kb/s
    Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 5504x2752, 43 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
    Metadata:
      creation_time   : 2021-04-16T09:20:58.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Side data:
      stereo3d: 2D
      spherical: equirectangular (0.000000/0.000000/0.000000)
[libaom-av1 @ 0x5621ef7bacc0] v1.0.0
```
Since AV1 codec is not yet supported on the server side, hence after directly adding it as a stream source on the panel doesn't play the stream.
We are going to add AV1 codec support and it is in our roadmap. It will be available in Q3 this year most probably.

For the files above, you can use ffmpeg to convert the codec to H.264 and send it to the AMS as rtmp.
Here's a sample command: 
`ffmpeg -re -i https://d1h720pygp5zr.cloudfront.net/videoplayback.mp4 -c:v libx264 -b:v 2000k -profile:v baseline -c:a aac -b:a 128k -vf scale=1920:1080 -f flv rtmp://your_rtmp_server_address`

Let me know your thoughts and we can discuss these more deeply here.

Thank you

**Comment by sahiljain2497** [comment]
Hi @Mohit-3196 , I am good thanks. hope you are doing well.

I understand the issue with the file not supported which is fine for now but there is one more issue with buffering.

I have 2 versions setup and first one is working fine and second one keeps buffering. I am streaming a 360 video via OBS. 

1). antmedia 2.4

- try streaming using this - rtmp://stream.20twenty20.com/LiveApp/pgTkcTVfin601682758471196
- play using - https://stream.20twenty20.com/LiveApp/play.html?name=pgTkcTVfin601682758471196&autoplay=true&playOrder=hls&is360=true

2). antmedia 2.5

- try streaming using this - rtmp://rtmp.storbeey.com/LiveApp/AP2qb2kbq7WN1680253349461
- play using -https://antmedia.storbeey.com/LiveApp/play.html?name=AP2qb2kbq7WN1680253349461&autoplay=true&playOrder=hls&is360=true

**Comment by Mohit-3196** [comment]
Hi @sahiljain2497 ,
Thank you again.

Can you please tell me which version you are using in the second case please?
You mentioned v2.5 but I would just like to be sure if it is v2.5.3 or any other like 2.5.0

I tried this with the latest snapshot and it seemed to publish fine there.
Also, if you are available then we can make some detailed tests together in a call as well.

Thank you.

**Comment by Mohit-3196** [comment]
Hi @sahiljain2497 ,
OK, sure.
Thank you

**Comment by sahiljain2497** [comment]
> Hi @sahiljain2497 , OK, sure. Thank you

Hi @Mohit-3196 did you get a chance to look into this further?

**Comment by Mohit-3196** [comment]
Hi @sahiljain2497 ,
Unfortunately, I couldn't write to you for a call as I'm a little occupied with some tasks, sorry for that.
Let's have the call tomorrow. I will write to you by mail.

Thank you

**Comment by mustafaboleken** [comment]
Sahiljain2497 already provided detailed scenario above. When we start playing, we get video paused due to high energy consumption warning.

**Comment by mustafaboleken** [comment]
The main problem is related with the stream fetcher. Because of the 360 video we tested is 2 minutes 52 seconds length and 2.1 GB size, we get lots of buffer error. These errors also cause CPU consumption to increase.

![Screenshot 2023-06-05 at 11 30 41](https://github.com/ant-media/Ant-Media-Server/assets/23143596/7a6daafe-6910-419f-b253-963df8ef248d)
![Screenshot 2023-06-05 at 11 31 01](https://github.com/ant-media/Ant-Media-Server/assets/23143596/dcaaef76-6dcc-4619-923b-3cb1ece737bc)

**Comment by sahiljain2497** [comment]
> The main problem is related with the stream fetcher. Because of the 360 video we tested is 2 minutes 52 seconds length and 2.1 GB size, we get lots of buffer error. These errors also cause CPU consumption to increase.
> 
> ![Screenshot 2023-06-05 at 11 30 41](https://user-images.githubusercontent.com/23143596/243303210-7a6daafe-6910-419f-b253-963df8ef248d.jpg) ![Screenshot 2023-06-05 at 11 31 01](https://user-images.githubusercontent.com/23143596/243303227-dcaaef76-6dcc-4619-923b-3cb1ece737bc.jpg)

That is not case exactly, even if no one is watching, I still see 65% frames getting dropped in the OBS and the upload bitrate does move up than 2000kbps which seems like a problem with consuming & processing the stream. 

I have explained and shown the issue multiple times over google meet now.

**Comment by mustafaboleken** [comment]
Here is the solution:

First convert the video to baseline using FFmpeg `ffmpeg -i lake.mp4 -vcodec libx264 -profile baseline -g 60 -tune zerolatency -acodec aac output.mp4`

Second add output.mp4 as a MediaSource on OBS

Third publish into Ant Media Server v2.7.0 (You can use our test server, until you sure it's solved **rtmp://ovh36.antmedia.io/WebRTCAppEE/test3**)

Finally, you can watch it with `https://ovh36.antmedia.io:5443/WebRTCAppEE/play.html?id=test3&autoplay=true&playOrder=hls&is360=true`

**Comment by mustafaboleken** [comment]
I'm closing it due to inactivity. If the solution that I provided is not solve the problem, feel free to reopen it.
