### ISSUE TITLE
Can I use the SSM parameter? : /aws/service/marketplace/ant-media/latest

### ISSUE THREAD

**Issue by jgcman** [ant-media/Ant-Media-Server#5019]
Hi.

I am using Ant Media Server Enterprise with AWS Marketplace.
the AMI name is 'AntMedia-AWS-Marketplace-EE-v253-52cdb7ae-1096-4915-823f-ff83a0a529a9'
And AMI ID is 'ami-0c5104827b4eced6a'

And I recently found some SSM Public parameter.
 * /aws/service/marketplace/ant-media/latest
 * AMI ID is 'ami-04b196590225ec37e'

So i wonder that Are these two AMI the same thing?
Can I use this SSM parameter?

**Comment by muratugureminoglu** [comment]
Hi @jgcman 

There is a different image Id for each Zone. As far as I can see, there are two different image ids. This means that you have obtained it in two different zones. If what you want to do is just find the ImageId, you can also use the following command.

```
aws ec2 describe-images --filters Name=name,Values=AntMedia-AWS-Marketplace-EE-* --query 'Images[*].[ImageId,Name]'
```

In short, the zone where you use EC2 is different from the zone where you run SSM.

Let me know if you have further questions.

**Comment by muratugureminoglu** [comment]
Hi @jgcman 

I'm currently closing this issue and feel free to open it if it does not work for you.

Regards.
