### ISSUE TITLE
When the stream stopped and the player is running it will play HLS even the HLS is disabled.

### ISSUE THREAD

**Issue by k99IT** [ant-media/Ant-Media-Server#5025]
### Short description
Hi @mekya, 
When the stream stopped and the player is running it will play HLS even the HLS is disabled.
Even I disabled the HLS streaming we still getting a HLS views and a lot of it.

![image](https://user-images.githubusercontent.com/131236957/233312583-b10ce798-bf59-4d4c-8dcf-4558649f2e50.png)

![image](https://user-images.githubusercontent.com/131236957/233312040-97b9ea48-4bb3-4a40-bb28-528fcf5b2e40.png)

I also tried to limit the HLS Viewer limit but still having this issue.

![image](https://user-images.githubusercontent.com/131236957/233355194-3a4e5e06-b3f6-4e4a-b1cf-e6a98e3c9cea.png)

I noticed that when we stop the stream while the player is running it will show a video that is from the other day, a short video but in a loop. and when we start the stream again it shows on the GUI that its playing HLS.

### Environment
* Ant Media Server version: Enterprise Edition 2.5.3 20230107_0851

**Comment by yashtandon113** [comment]
@k99IT
Please restart the previously running streams after disabling the HLS playback. Changes are made to the new streams.
