### ISSUE TITLE
Find a way to dismiss screen share permission popup in Android SDK

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5032]

**Comment by mustafaboleken** [comment]
We can capture the screen from the Android Debug Bridge directly to dismiss screen share. Here is the bash command that we can use: `adb exec-out "while true; do screenrecord --bit-rate=16m --output-format=h264 --size 720x1280 --time-limit 180 -; done" | ffmpeg -re -fflags +genpts -i pipe: -c:v libx264 -f flv -flvflags no_duration_filesize rtmp://<server_domain>/<application_name>/<stream_id>`

**Comment by mekya** [comment]
I'm not sure if this is the solution that works for the user. Could you please confirm?

**Comment by mekya** [comment]
I've some ideas/hypotheses. Let's get the user feedback and we can proceed accordingly.

**Comment by mustafaboleken** [comment]
Thanks to @lastpeony, we had another way to dismiss the popup. If we give PROJECT_MEDIA through adb, it's not asked to user at all. `adb shell cmd appops set io.antmedia.webrtc_android_sample_app PROJECT_MEDIA allow`

**Comment by mustafaboleken** [comment]
We meet with the user and he confirmed that it's working as expected.
