### ISSUE TITLE
Ant Media Server not broadcasting.

### ISSUE THREAD

**Issue by Allerek** [ant-media/Ant-Media-Server#5039]
So, i've followed this tutorial to 6:28
https://www.youtube.com/watch?v=2FrrYuLh1kY

When i click play button, i see 'Stream will start playing automatically
when it is live'. 

In 'error log' i can see: 
[hls @ 0xffff958d6eb0] Opening '/usr/local/antmedia/webapps/LiveApp/streams/F6Y1IDLbUxfH1682349535789000000001.ts' for writing
[hls @ 0xffff958d6eb0] Opening '/usr/local/antmedia/webapps/LiveApp/streams/F6Y1IDLbUxfH1682349535789.m3u8.tmp' for writing

Tried a chmod on that folder, not working new files get created with these privileges:
![image](https://user-images.githubusercontent.com/12304071/234045552-79886232-6edd-47f4-a76f-8ed178d17fc5.png)

No other errors, just this. ConsoleLog is okay.

**Comment by timantmedia** [comment]
I've had to close this issue due to inactivity. Please feel free to open up a new issue if you still need support.
