### ISSUE TITLE
Service failing to start from the source code

### ISSUE THREAD

**Issue by Samriddha01** [ant-media/Ant-Media-Server#5046]
After successfully building the source code when we tried to start the server by giving the "./start.sh" command, we are getting following error..

![Screenshot from 2023-04-26 19-13-10](https://user-images.githubusercontent.com/83784034/234596337-1f479819-3490-49e2-8586-bb4744f4d85a.png)

@mekya  Please guide us in resolving the issue. We are running on Ubuntu 18.04 with Java 11 so not able to understand what is left behind actually..!

**Comment by muratugureminoglu** [comment]
Hi @Samriddha01 

After building[1] you run the **./repackage_community.sh** script and package the AMS that you built. The packaged file will be in Ant-Media-Server/target/ant-media-server-community.zip

[1] https://github.com/ant-media/Ant-Media-Server/wiki/Build-From-Source

Then you can proceed to the normal installation step[2].

**Example:** 
```
./install_ant-media-server.sh -i ant-media-server-community.zip
```
[2] https://antmedia.io/docs/quick-start/#install-ant-media-server

**Comment by Samriddha01** [comment]
Thank you so much for your response. It is working now.
