### ISSUE TITLE
Update adapter.js with the latest version

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5050]
- https://github.com/ant-media/StreamApp uses [adapter in this file](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/external/adapter-latest.js)
- adapter source code [is available here](https://github.com/webrtc/adapter/tree/master)
- [WebRTC samples ](https://webrtc.github.io/samples/)uses the sample adapter  

Just get the latest version from source code or [from here directly](https://webrtc.github.io/adapter/adapter-latest.js) and replace it on StreamApp

Then test if every sample is working as expected

**Comment by lastpeony** [comment]
The adapter-latest.js file has been updated with the file mentioned, and all samples have been thoroughly tested and confirmed to be functioning as expected.
