### ISSUE TITLE
Make JavaScript SDK typescript compatible

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5066]
https://betterprogramming.pub/turn-javascript-into-typescript-compatible-packages-cb81820838ed

**Comment by MaZZly** [comment]
* `webRTCAdaptor.play()` shows to have 7 required parameters, while only the first 2 are actually required.
* `webRTCAdaptor.joinRoom()` shows 3 required params, while only the first one is actually required.
* `callback()` and `callbackError()` are not defined at all..
* I'm sure there are many others like this...

Also, there are 178 instances of `: any` in the definitions, which is [not recommended by TypeScript](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any).

**Comment by mustafaboleken** [comment]
Hi @MaZZly,
It's a good idea. We can add some sample apps and with the help of it, we can also arrange the type definitions and required/optional parameters. I'm taking the initiative to proceed. @mekya

**Comment by mustafaboleken** [comment]
Conversation goes on https://github.com/ant-media/Ant-Media-Server/issues/4037
