### ISSUE TITLE
Signaling does not work if the Cloud server restarts and the stream does not play again.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5067]
### Short description
When a cloud server is used as a signaling server and a local server is used to ingest streams. If the cloud server is restarted, the stream is no longer playing. The signaling medium appears to be breaking down.

### Environment
* Ant Media Server version: v2.5.3

### Steps to reproduce
1. After setup signaling structure
2. Publish the stream on local
3. Play the stream on cloud (Works fine)
4. Restart the cloud server once
5. Try to play the stream again

### Expected behavior
Stream should work fine through signaling.

### Actual behavior
Stream is no longer working on the cloud server via signaling. To make things working again, restart the local server as well.

**Comment by lastpeony** [comment]
this issue fixed by implementing a reconnection and re-registering streams mechanism on client.
Feel free to re-open if seen again.

https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/581
