### ISSUE TITLE
Suggested Linux version for installation

### ISSUE THREAD

**Issue by jsfan3** [ant-media/Ant-Media-Server#507]
I'm going to try AntMedia.
In the "[Getting Started](https://github.com/ant-media/Ant-Media-Server/wiki/Getting-Started)" instructions, it is suggested to use Linux Ubuntu.

Which version of Linux Ubuntu is suggested? Is 18.04 fine?

In the installation instruction, there is no mention of the database. Have I to install a database like MySql?

Thank you for your support.

**Comment by mekya** [comment]
Hi @jsfan3 ,

You're right. It is better to use 16.04.  On the other hand, it's being used on 18.04 and no problem is reported. 

By default, it uses [mapdb](http://www.mapdb.org/) as a database engine. It's good for small-medium scales. If you are on the medium-large scale, mongodb can be used as well. 

Regards,
A. Oguz
