### ISSUE TITLE
NVIDIA-SMI couldn't communicate with the NVIDIA driver

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5072]
### Short description
When launching a GPU instance on Azure Marketplace and after installing CUDA drivers, NVIDIA-SMI fails because it couldn't communicate with the NVIDIA driver.

### Environment

* Operating system and version: ubuntu 20.04
* Ant Media Server version: v2.5.3

### Steps to reproduce
1. Launch a GPU instance on Azure Marketplace like NV4as_v4/NV6ads A10 or others.
2. Install CUDA drivers https://antmedia.io/docs/guides/advanced-usage/using-nvidia-gpu/
3. Run `nvidia-smi`

### Expected behavior
It should communicate with the NVIDIA driver and return the GPU status.

### Actual behavior
It prints

>  NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

#4582 

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by muratugureminoglu** [comment]
Hi,

It 's NVIDIA A10 Tensor Core GPU.  You can install it by following the steps below.

```
wget https://storage.googleapis.com/nvidia-drivers-us-public/GRID/vGPU15.2/NVIDIA-Linux-x86_64-525.105.17-grid.run
chmod +x NVIDIA-Linux-x86_64-525.105.17-grid.run
./NVIDIA-Linux-x86_64-525.105.17-grid.run
```
![Screenshot at 2023-05-08 21-46-53](https://user-images.githubusercontent.com/6337605/236906784-b7d257cf-fcbf-4532-8b4c-bfa257dfadb7.png)

**Comment by Mohit-3196** [comment]
Thank you.

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/69

**Comment by mekya** [comment]
Thank you @Mohit-3196.

Closing this issue then.
