### ISSUE TITLE
Hash Based Token is not working

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5075]
When we try to publish with the hash-based token, we get an unauthorized error.

**Comment by mekya** [comment]
Integration test code is written in this PR
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/585

Check `FrontEndTest#testPublishWithHashbased` 

It seems that it's working

**Comment by mustafaboleken** [comment]
@mekya then, there are some problems in the documentation. I will update it if there is a problem.
