### ISSUE TITLE
Bulk uploading of VOD files to the server

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5079]
I have more than 200 videos and they need to be placed in a playlist, the documentation describes how to add via a link, but adding a large number of videos one at a time will take long time.

**Comment by muratugureminoglu** [comment]
Hi @yashtandon113,

Here is a workaround solution.

Example Usage:
```
./script.sh /{your}/{video}/{path}
./script.sh /home/streams/
```
```
#!/bin/bash

appname="WebRTCAppEE"
url="http://localhost:5080"

for i in `find $1 -iname "*.mp4"`;do
        a=`basename $i`
	curl -L -X POST "$url/$appname/rest/v2/vods/create?name=$a" -H "Content-Type: multipart/form-data" -F "file=@$i"
done
```

**Comment by timantmedia** [comment]
Is it not possible to create a process to read the directory where the files are and call the `API POST /v2/vods/create` in a loop to upload the video?

**Comment by mekya** [comment]
I'm just closing this issue. Please feel free to re-open if you have any trouble or question
