### ISSUE TITLE
Upgrade from Community to Enterprise

### ISSUE THREAD

**Issue by jsfan3** [ant-media/Ant-Media-Server#508]
If in the future I'll want to update from Community to Enterprise, is it an easy task (keeping all the saved data)?

**Comment by mekya** [comment]
Hi @jsfan3 ,

Yeah it is an easy task. Just copy the db files if you use mapdb. We can also help if you encounter any problem. 

Regards,

**Comment by SelimEmre** [comment]
Hi @jsfan3,
Thank you for your interest. We updaded our install script for this situation. Please review our wiki page: https://github.com/ant-media/Ant-Media-Server/wiki/Getting-Started#41-update-over-older-version 
If you have any questions please feel free.

Regards,
Selim
