### ISSUE TITLE
Update Websocket Reference & list the formatting issues in the documentation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5081]
https://antmedia.io/docs/guides/publish-live-stream/webrtc/webrtc-websocket-messaging-reference/

Fix the formatting
![Image](https://user-images.githubusercontent.com/3456251/236704167-703c536e-8f51-4a19-974b-916eab238579.png)

**Comment by mekya** [comment]
- [ ] Publish
- [ ] Play

**Comment by Mohit-3196** [comment]
https://github.com/ant-media/ant-media-documentation/pull/71
