### ISSUE TITLE
Upload HLS files on the fly to the cloud storage

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#5082]
AMS waits for the stream end to upload HLS files to upload cloud storage. This may be done periodically for example each 15sec.

**Comment by mustafaboleken** [comment]
https://community.antmedia.io/topic/1333-quick-instructions-how-to-push-hls-content-to-a-http-endpoint/

**Comment by mekya** [comment]
Hi @mustafaboleken,
 
Is it working in uploading to S3?

**Comment by mustafaboleken** [comment]
Hi mekya,

I add this cause I tough it could be worked with S3 pre-signed URLs but it gives temporary access so instead of that I made custom development to upload regularly.

**Comment by mekya** [comment]
OK. 

I've just checked the PR. I see a flag about settings and in the enterprise I see uploading the m3u8 adaptive file. 
Please correct me if I'm wrong. 

How the ts files are uploaded to the S3?

Gentle Reminder: Check the PR is ready to merge and CI has passed.

**Comment by mustafaboleken** [comment]
@mekya 

I'm currently checking ci right now. Upload part is on the GitLab side here is the link https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/589/diffs
