### ISSUE TITLE
No audio from phone's primary speaker when playing stream or join conference using Android SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5084]
### Short description
When using the Android SDK to play the stream or join a conference, the audio does not come from the phone's primary speaker. The audio is coming from the calling speaker and is so low that it can only be heard by placing the phone to one's ear.

### Environment
* Ant Media Server version: v2.5.3 and above

### Steps to reproduce
1. Publish stream on the server with any stream type or join the conference
2. Play the stream on Android SDK or join conference room
3. Listen the audio

### Expected behavior
Audio should come from the primary speaker.

### Actual behavior
Audio is coming from the calling speaker which is very very low.

**Comment by toantk238** [comment]
I meet the issue too. It breaks our major features !
