### ISSUE TITLE
Configuring "maxAudioTrackCount" results in unnecessary video tracks creation

### ISSUE THREAD

**Issue by dalkofjac** [ant-media/Ant-Media-Server#5093]
### Short description
__Brief description of what happened__
It seems that configuring the red5-web.properties setting "maxAudioTrackCount" results in unnecessary video tracks being created per publishing stream instead. To be more precise, when we set "maxAudioTrackCount=3" and when new stream is published (with "mainTrackId" set), all the players of that stream correctly get exactly 3 audio tracks, but they also get 1 (empty) video track for each stream after first (so, for 50 publishers, players get 3 audio tracks and 49 video tracks). It's important to note that we do not set the "maxVideoTrackCount" setting, meaning it's set by default to "-1". Also, we do not publish the video at all in these streams, only audio tracks are present in them.

### Environment

* Ant Media Server version: Enterprise Edition 2.6.0-SNAPSHOT 20230213_0718
* Browser name and version: Google Chrome Version 113.0.5672.93 (Official Build) (64-bit)

### Steps to reproduce
1. Configure "maxAudioTrackCount=3" in red5-web.properties (together with enabling the DataChannel and implementing the feature itself on the client apps)
2. Start publishing streams (with only audio tracks) from multiple clients (with "mainTrackId" set, so it's a multitrack-conference setup)
3. Play the merged stream (with "mainTrackId") on one or more players and monitor the behavior (using chrome://webrtc-internals for example)

### Expected behavior
__Put as much detail here as possible__
The player gets the merged stream with exactly 3 audio tracks and 0 video tracks (since nobody is publishing the video).

### Actual behavior
__Put as much detail here as possible__
The player gets the merged stream with 3 audio tracks and N-1 video tracks (where N is the number of publishers).

P.S. The issue is already discussed with and reported to @burak-58, just putting the full explaining here in form of a ticket.

**Comment by mekya** [comment]
Thank you @dalkofjac 

We'll discuss this issue in today's meeting.
