### ISSUE TITLE
Support for automated installation

### ISSUE THREAD

**Issue by jantekb** [ant-media/Ant-Media-Server#5101]
I am trying to set up streaming infrastructure with Terraform+Ansible that involves Ant Media Server enterprise servers. The only way to create the admin user (not using MongoDB) is by logging into the web interface for the first time, the only documented way to specify enterprise license key is by doing that on the web UI. 

I would like to specify the admin user, password and the license key as parameters to the installer script - or have simple, documented CLI tools to set these straight after installation.

I have found that the license key gets stored in red5.properties, but it is not convenient to edit that file using shell scripting and I also find it fragile to rely on a non-public-facing internal property key.

**Comment by muratugureminoglu** [comment]
Hi @jantekb 

You can create a user using the following rest method. 
```
curl -s -X POST -H "Content-Type: application/json" -d '{"email": "your_email", "password": "your_password", "scope": "system", "userType": "ADMIN"}' http://localhost:5080/rest/v2/users/initial
```

For the license key, please check the following rest request.

https://antmedia.io/rest/#/ManagementRestService/changeServerSettings

Alternatively, you can use it on the terraform side as follows. Then you can write it in the conf file.
```
export TF_VAR_ams_license_key='your_license_key'
```
```
variable "ams_license_key" {
    type        = string
}
```
I hope this helps.

**Comment by mekya** [comment]
Thank you for the issue @jantekb and answer @muratugureminoglu 

I think there is also a way to specify the license key in the installation script? @muratugureminoglu

**Comment by muratugureminoglu** [comment]
Thanks for asking this @mekya 

I 'd added it for the automatic download/installation function pending in PR. We can enter the license key in start.sh. But it would be nice to add this in the install script.

https://github.com/ant-media/Scripts/pull/205/files#diff-259330a0e3a7ffcbe8c511ba0af0d8ccf885516603a52a46e77fff408274bfda

**Comment by mekya** [comment]
Hi Guys,

Thank you @muratugureminoglu 

@jantekb PR has been merged. With this PR, you can specify the license key in the installation script. 
I'm closing the issue for now.  Please feel free to open if you still have a problem. 

Take care
Oguz
