### ISSUE TITLE
Editing the created Stream playlist again will not scroll

### ISSUE THREAD

**Issue by hkthomas** [ant-media/Ant-Media-Server#5103]
**Is your feature request related to a problem? Please describe.**

Add stream for the first time and scroll through any URL when editing a playlist.  Once you've saved, edit the playlist again, and when there are more than 8 entries, you won't see the Add and save buttons at the bottom, and the page won't scroll.

**Describe the solution you'd like**

Add scrolling

**Describe alternatives you've considered**

Hold ctrl+ mouse wheel to zoom in and out can temporarily solve this problem, my screen is 1920*1080, reached the zoom limit is still the same problem as above

**Additional context**
![image](https://i.ibb.co/tHYQS4Z/Snipaste1.png)
![image](https://i.ibb.co/CKnDMzV/Snipaste2.png)

**Comment by yashtandon113** [comment]
@hkthomas 
Yes, it was a known issue and fixed with the following Git Hub issue: https://github.com/ant-media/Ant-Media-Server/issues/4670
PR was already raised by the developer and needs to be reviewed and merged.

**Comment by hkthomas** [comment]
okay, I will close the issue.
