### ISSUE TITLE
JS SDK does not publish to npmjs.com

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5104]
https://github.com/ant-media/StreamApp/actions/runs/4977865718/jobs/8907962472

**Comment by mustafaboleken** [comment]
As far as I see, it can be solved basically, creating an automation token and update the existing one on StreamApp.

https://github.blog/changelog/2020-10-02-npm-automation-tokens/

**Comment by mustafaboleken** [comment]
It's fixed https://github.com/ant-media/StreamApp/actions/runs/4991445876/jobs/8937938049
