### ISSUE TITLE
UnAuthorized access: Check your token

### ISSUE THREAD

**Issue by HadyHammad22** [ant-media/Ant-Media-Server#5109]
when add webrtc sdk in my project according to this link https://antmedia.io/build-and-try-webrtc-ios-app-for-dummies/
i have issue when live stream start say "UnAuthorized access: Check your token" and also when try to use the example project give me the same error
![WhatsApp Image 2023-05-16 at 4 03 08 PM](https://github.com/ant-media/Ant-Media-Server/assets/53533148/005d447e-8b06-4d7e-b239-27bd8c0f9a6f)

**Comment by yashtandon113** [comment]
@HadyHammad22 
Thanks for raising the issue.

As this issue has been resolved on https://github.com/ant-media/Ant-Media-Server/issues/5112

I am closing this one.
