### ISSUE TITLE
Latest version on iOS SDK not accepting one time token (always unauthorised)

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5112]
### Short description
The customer upgraded Xcode to version 14.3, but experienced build errors using an older version of the SDK.

Error when trying to use ```WebRTCiOSReferenceProjec_08_Dec_2021-kgiz4d.zip``` sdk is:

 ```When building for iOS, the expected library /Users/hady/Desktop/Mazaady-Work/mazaady-ios-new/WebRTCiOSSDK.xcframework/ios-arm64/WebRTCiOSSDK.framework was not found in /Users/hady/Desktop/Mazaady-Work/mazaady-ios-new/WebRTCiOSSDK.xcframework.```

using the latest version of the SDK builds the project successfully, but when trying to connect using a one time token there is always a response of  ```UnAuthorized Access```

Connection is successful without a one-time token. 

### Steps to reproduce
1. Xcode 14.3
2. Latest version of the SDK
3. Try to connect using a one time token

### Expected behavior
Connection successful

### Actual behavior
Unauthorized access

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @timantmedia,

Firstly, iOS SDK build has changed. We're distributing it through SPM. 
Here is a quick way how to add SPM dependency to iOS project
https://antmedia.io/build-and-try-webrtc-ios-app-for-dummies/

No need to deal with files. 

Do you confirm that user is using the latest version here?
https://github.com/ant-media/WebRTC-iOS-SDK

**Comment by HadyHammad22** [comment]
any updates?

**Comment by mekya** [comment]
Unfortunately, there is no update yet. 

We can discuss/test this issue in this event. It will be great if you join. 

[Live Coding: How to Develop WebRTC iOS apps?](https://github.com/orgs/ant-media/discussions/5121)

**Comment by mekya** [comment]
Hey @HadyHammad22,
Thank you for joining the meeting. 

I've sent a PR to the repo. Could you please check if it's working for you?
https://github.com/ant-media/WebRTC-iOS-SDK/pull/23

Have a great weekend

Regards
Oguz

**Comment by HadyHammad22** [comment]
I tried to use branch "fix_token" and now my issue is solved and works
well. I really appreciate your efforts
Thanks.

**Comment by mekya** [comment]
It's our pleasure.  Then closing this issue for now.

Have a great weekend
