### ISSUE TITLE
Web page recording blog post and documentation

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5113]

**Comment by mustafaboleken** [comment]
@timantmedia Can you please review and publish this https://antmedia.io/?p=64785&preview=true

**Comment by timantmedia** [comment]
@mustafaboleken we plan to publish this tomorrow (31 May) but it seems the plugin jar file is still not available https://github.com/ant-media/Plugins/raw/master/WebpageRecordingPlugin/build/webpage-recording-plugin.jar. 

Do you know whats happening here? Should we plan something else for tomorrow?

**Comment by mustafaboleken** [comment]
@lastpeony still reviews this. Maybe, you can go with virtual background blogpost for tomorrow. It's under review of @lastpeony right now.

**Comment by timantmedia** [comment]
@mustafaboleken @lastpeony I think this blog post can be made into a more comprehensive blog post. I am happy to write some more about it.  https://antmedia.io/?p=79672&preview=true
