### ISSUE TITLE
Installation is failed

### ISSUE THREAD

**Issue by amran-muhammad** [ant-media/Ant-Media-Server#5119]
I tried ito install  AMS from this link in my ubuntu 22.04 LTS but this command `sudo service antmedia status` I get `Unit antmedia.service could not be found.
`  Its not working

**Comment by muratugureminoglu** [comment]
Hi @amran-muhammad 

You are encountering such an error because the service file does not exist. Please share the installation steps then let me check.

**Comment by amran-muhammad** [comment]
I followed this article [https://github.com/ant-media/Ant-Media-Server/wiki/Installation](url)

**Comment by muratugureminoglu** [comment]
Can you please a screenshot of your terminal screen while you are installing the Ant Media Server ? 

- your command line
- which zip file you are using
- last output (screenshot) of your installation process

**Comment by amran-muhammad** [comment]
I follewd this link [https://github.com/ant-media/Ant-Media-Server/wiki/Beginners-Guide-To-Getting-Started-With-Ant-Media-server](url) and having same error 
![image](https://github.com/ant-media/Ant-Media-Server/assets/55654259/1c54f8c8-fe55-448b-95d5-fadd7dd6f122)
!

**Comment by muratugureminoglu** [comment]
Please try with the following version. 

https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.6.0/ant-media-server-community-2.6.0.zip

**Comment by amran-muhammad** [comment]
Thanks @muratugureminoglu It works for me

**Comment by muratugureminoglu** [comment]
My pleasure. Let me know if you have any questions. :) You can also ask your questions on Ant Media [Github Discussions](https://github.com/orgs/ant-media/discussions)
