### ISSUE TITLE
webrtc play issue

### ISSUE THREAD

**Issue by m0dawood** [ant-media/Ant-Media-Server#512]
# Issue
im using using webrtc to puplish audio only stream and every thing is ok
but when try to play stream i got this error
error Failed to set remote offer sdp: Failed to set remote video description send parameters.

### Short description
this the sdp i got from the server
`sdp":"v=0\r\no=- 6095081199371626728 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS stream100167659cd6d-6217-4391-a961-d1545f1a9f8a\r\nm=audio 9 UDP\/TLS\/RTP\/SAVPF 111 110\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:+lQR\r\na=ice-pwd:BUWYodAqoYinC0TmmM25PKdx\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 98:3E:A7:A6:AF:1B:18:45:87:2B:BA:9B:43:BB:EC:A6:C6:BD:B6:68:F9:6C:37:AD:62:53:B4:3A:56:AE:1A:24\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus\/48000\/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:110 telephone-event\/48000\r\na=ssrc:3892189442 cname:m8HAy5wMQAsnjfzs\r\na=ssrc:3892189442 msid:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a audio\r\na=ssrc:3892189442 mslabel:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a\r\na=ssrc:3892189442 label:audio\r\nm=video 9 UDP\/TLS\/RTP\/SAVPF 96 97\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:+lQR\r\na=ice-pwd:BUWYodAqoYinC0TmmM25PKdx\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 98:3E:A7:A6:AF:1B:18:45:87:2B:BA:9B:43:BB:EC:A6:C6:BD:B6:68:F9:6C:37:AD:62:53:B4:3A:56:AE:1A:24\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http:\/\/www.ietf.org\/id\/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/playout-delay\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264\/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:97 rtx\/90000\r\na=fmtp:97 apt=96\r\na=ssrc-group:FID 4248538006 3614302854\r\na=ssrc:4248538006 cname:m8HAy5wMQAsnjfzs\r\na=ssrc:4248538006 msid:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a video\r\na=ssrc:4248538006 mslabel:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a\r\na=ssrc:4248538006 label:video\r\na=ssrc:3614302854 cname:m8HAy5wMQAsnjfzs\r\na=ssrc:3614302854 msid:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a video\r\na=ssrc:3614302854 mslabel:stream100167659cd6d-6217-4391-a961-d1545f1a9f8a\r\na=ssrc:3614302854 label:video\r\n"`

### Environment

* Operating system and version: android 6

### Expected behavior
got an sdp with audio only

**Comment by mekya** [comment]
Hi @m0dawood ,

You're publishing to Enterprise edition? Do you use audio_publish.html and audio_player.html files?

Regards,
A. Oguz

**Comment by m0dawood** [comment]
im using webrtc module for react-native
using ant signaling messages i can puplish audio only sending this via sockts
`{
        command: "publish",
        streamId: `streamid`,
        video: false,
        audio: true,
    }`

**Comment by m0dawood** [comment]
when i try to play the stream using same way
`{
        command: "play",
        streamId: "streamId",
        video: false,
        audio: true
    }`

i'm getting video in the sdp of the offer created by the server that's cause some devices to fail as there is no real video and the percent of failed devices is not small its about 50% of tested devices

**Comment by m0dawood** [comment]
i'm using this [https://github.com/oney/react-native-webrtc](url)

**Comment by SelimEmre** [comment]
Hi @m0dawood,
Thank you for your interest. Do you still have problems? If the problem persists, can you re-open this issue?

Best Regards,
Selim

**Comment by mnjsnj** [comment]
Hi #mo-ah-dawood can you suggest me how can i use Ant media with React Native

**Comment by frangeris** [comment]
Hey @mo-ah-dawood could you please provide a small guide how did you get AntMedia working with [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc)? I've being struggling a lot with this, from my [logs](https://github.com/ant-media/Ant-Media-Server/issues/1849#issuecomment-688458997) everything seems to be working on react native side, but I'm not able to see the stream on And media, I don't know where could be the issue.

Thanks by the way!

**Comment by mekya** [comment]
Hi @frangeris , There is an issue about react native #1849 . Some of users in the community use react-native-webrtc with their implementation but we've not officially supported it yet.

**Comment by vivekspraxa** [comment]
@frangeris  - do have have any sample working of it using react-native and what changes we need to do on server to run it

**Comment by CyrusZei** [comment]
any update on a example for react native where you use the REST API for ant media

**Comment by mekya** [comment]
hi, there is no update for the react native official support. You should integrate it on your side. 

You don't need to do anything on the server side, you need to implement on the react native side according to this doc 
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference
