### ISSUE TITLE
I am streaming from obs but stream on ant media says Your live stream will play automatically as soon as it's available. Get ready to be part of the action!

### ISSUE THREAD

**Issue by Pugguroo** [ant-media/Ant-Media-Server#5128]
I am streaming from OBS
<img width="130" alt="image" src="https://github.com/ant-media/Ant-Media-Server/assets/98660834/30c17867-8543-437a-9efc-1a95382aa92b">

it says its broadcasting etc etc 

![image](https://github.com/ant-media/Ant-Media-Server/assets/98660834/cbfe0053-ccab-4283-bbb0-fe4df985e24e)
but when i try to view the stream it says this 

these are my obs settings: 
![image](https://github.com/ant-media/Ant-Media-Server/assets/98660834/dec62448-dc91-410a-b76c-ca48056f3db1)

![image](https://github.com/ant-media/Ant-Media-Server/assets/98660834/c32bd943-d265-4b7a-a200-c4c6a4f04c13)
and this is what i see on ant media (THE STREAM ID IS DIFFERENT I KNOW BECAUSE I DELETED BEFORE THE OLD SCREENSHOT)

im hosting it on a ubuntu VPS and used this video  for installation
https://www.youtube.com/watch?v=RM-5VeSK0T4&ab_channel=Knowing

ive also tried installting from the github docs from ant media and i still have the same issue

**Comment by rockstartsiddu143** [comment]
bro please help me to install i am gettting error 
![image](https://github.com/ant-media/Ant-Media-Server/assets/134163028/e6b3154e-44d3-4829-92a8-10b85b532c17)

**Comment by Pugguroo** [comment]
do 
apt install docker
apt install docker-compose


and make sure you update ur vps

apt-install upgrade
apt-install update

**Comment by Pugguroo** [comment]
can anyone help me here, been waiting for help for ages

**Comment by timantmedia** [comment]
When you try to live stream from OBS using the RTMP publish settings, does OBS connect? Or is there a connection error? 

Did you open port 1935 on the server for RTMP? Please confirm. 

Try to set undefined streams. if it's not checked https://antmedia.io/docs/guides/advanced-usage/stream-security/#1-enabledisable-accepting-undefined-streams to see if you can just create a random stream. 

Does webRTC streaming work? If you go to the sample publish page can you publish a stream and play it back?

**Comment by timantmedia** [comment]
@Pugguroo Thank you for reporting this issue, we've identified a bug and a fix has been sent in the 2.6.1 release due in the next couple of days.  Here is the PR for your reference https://github.com/ant-media/Ant-Media-Server/pull/5145. 

However, I've found if you append the `playOrder` parametre, it will playback. You should be able to use that until the fix is released. 

E.g. http://localhost:5080/LiveApp/play.html?name=HATDZLcqoZQL1684922725932&playOrder=hls

**Comment by Pugguroo** [comment]
> When you try to live stream from OBS using the RTMP publish settings, does OBS connect? Or is there a connection error?
> 
> Did you open port 1935 on the server for RTMP? Please confirm.
> 
> Try to set undefined streams. if it's not checked https://antmedia.io/docs/guides/advanced-usage/stream-security/#1-enabledisable-accepting-undefined-streams to see if you can just create a random stream.
> 
> Does webRTC streaming work? If you go to the sample publish page can you publish a stream and play it back?

obs connects and port 1935 is open and webrtc streaming does not work

**Comment by Pugguroo** [comment]
> @Pugguroo Thank you for reporting this issue, we've identified a bug and a fix has been sent in the 2.6.1 release due in the next couple of days. Here is the PR for your reference #5145.
> 
> However, I've found if you append the `playOrder` parametre, it will playback. You should be able to use that until the fix is released.
> 
> E.g. http://localhost:5080/LiveApp/play.html?name=HATDZLcqoZQL1684922725932&playOrder=hls

i will try this now

**Comment by Pugguroo** [comment]
yeah that works thanks
