### ISSUE TITLE
"WebRTC play" seems to work on iPhone (but not on Android), while "WebRTC Publish" doesn't work on both of them.

### ISSUE THREAD

**Issue by jsfan3** [ant-media/Ant-Media-Server#513]
I've done some tests with "ant-media-server-enterprise-1.6.0-SNAPSHOT-181030_1031.zip", installed as a Linux service (on Ubuntu 18.04, with port forwarding as suggested in the "Getting started" wiki).

**"WebRTC play" seems to work on iPhone (but not on Android), while "WebRTC Publish" doesn't work on both of them.**

More specifically, on iPhone X (iOS 12), if I open:
https://mydomain/WebRTCAppEE

- Safari asks permissions, after that is shows a blank black rectangle instead of the camera view; the "start publish" button is clickable, but if I open /WebRTCAppEE/player.html on my computer, the stream doesn't exist.

- Chrome doesn't ask permissions (however I enabled the Chrome camera permissions in the iPhone settings) and it doesn't show anything; the "start publish" button is not clickable.

Instead on Android 7, if I open:
https://mydomain/WebRTCAppEE

- Chrome asks permissions, it shows a rectangle with the camera view, but tapping "Start Publishing" doesn't do anything.

I can publish from Firefox (on a desktop computer). 

If on a mobile device I open:
https://mydomain/WebRTCAppEE/player.html

- on Android 7 (tested with Chrome) the "Start Playing" button doesn't do anything;
- on iPhone X (tested with Safari) the "Start Playing" button works.

If on a mobile device I open:
https://mydomain/WebRTCAppEE/play_embed.html?name=stream1

- on Android 7 (tested with Chrome) the stream doesn't start to play;
- on iPhone X (tested with Safari and Chrome) the stream plays correctly on both browsers (however it doesn't autostart, I suppose that on all mobile devices the video autostart is not available);

**Comment by mekya** [comment]
Yeah we've figure out some cases in 1.6.0-SNAPSHOT as you reported.  We also fixed some of them in latest snapshot. 

We'll update you after checking all issues you reported.

**Comment by mekya** [comment]
Hi @jsfan3 ,

We've fixed some issues on 1.6.0-SNAPSHOT which we know there is an issue on publishing with Android and iOS SDK. After that I test it with the scenarios you provided but different versions(Android 6, iOS 11.4), it worked for me.

Can you try again if we provide the latest snapshot?

**Comment by jsfan3** [comment]
Thank you, yes, I'll try again. Please provide me the latest snapshot.
Can you also provide me the SDKs for Android and iOS?

**Comment by SelimEmre** [comment]
Hi @jsfan3,
Thank you for your interest. I am sorry to say that; We provide Android SDK and IOS SDKs to people who buy Ant Media Enterprise Edition. Thank you for your understanding. If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Also you can review our [Google Group](https://groups.google.com/forum/#!forum/ant-media-server)

Best Regards,
Selim
