### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by rockstartsiddu143** [ant-media/Ant-Media-Server#5130]
bro please help me to install i am gettting error 
![image](https://github.com/ant-media/Ant-Media-Server/assets/134163028/e6b3154e-44d3-4829-92a8-10b85b532c17)

**Comment by muratugureminoglu** [comment]
There is no zip file where you ran the install script. Also, version 2.4.1 is outdated. Please download and try the file below.

https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.6.0/ant-media-server-community-2.6.0.zip

**Comment by 555farhan** [comment]
This is a scam

**Comment by 555farhan** [comment]
Scammers
