### ISSUE TITLE
VOD is not playing on dashboard and with Embedded player (play.html) in v2.6.0

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5137]
### Short description
The Recorded VOD is not playing on both dashboard and with Embedded player separately while the Uploaded VOD is playing fine with Embedded player separately but not on dashboard. As observed, it is happening because of extension issue during playback.

### Environment
* Ant Media Server version: v2.6.0

### Steps to reproduce
**Scenario-1**
1. Publish any stream and record it
2. Play the VOD on Dashboard from VOD section or from Embedded player (play.html) URL using playOrder=vod

### Expected behavior
VOD should play without any issue.

### Actual behavior
VOD is not playing because of extension issue as shown in below image.

![image](https://github.com/ant-media/Ant-Media-Server/assets/82374739/000f879b-0659-48dc-b112-2c1ea306db05)

**Scenario-2**
1. Upload any VOD on the server
2. Play the VOD on Dashboard from VOD section

### Expected behavior
VOD should play without any issue.

### Actual behavior
VOD is not playing from dashboard because of extension issue as shown in below image. However the uploaded VOD plays fine when playing with play.html using playOrder=vod

![Screenshot 2023-05-23 013254](https://github.com/ant-media/Ant-Media-Server/assets/82374739/52eab563-a668-4753-bd33-d430396cb347)

**Comment by mekya** [comment]
It's definitely my bad. While I'm refactoring embedded player, I've missed this. 

Let me quickly fix it.
