### ISSUE TITLE
When everybody leaves, Conference Room is not deleted

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5142]
Reproduced scenario:

- Join room A and room B with different accounts.
- Copy publisher from room A to room B as sub-track
- Exit from room A
- Exit from room B
- room B is not deleted (Reason: copied subtrack is not removed and server thinks it's still publishing)

Expected behaviour: When publisher A exit from room A, subtrack should removed from room B

**Comment by mekya** [comment]
> 1 Join room A and room B with different accounts. RoomA has just one user(userA) and RoomB has just one user(userB).
> 2 Copy publisher from room A to room B as sub-track. It's added through REST API as a sub-track.
> 3 Exit from room A- User A exits from room A
> 4 Exit from room B - User B exit from room B
> 5 room B is not deleted (Reason: copied subtrack is not removed and the server thinks it's still publishing)


The solution can be something like this.  In the item number 2, user A is added to another room. When user A is stop publishing, the user A should be removed through remove subtract REST method which is implemented on this issue #5143

**Comment by mekya** [comment]
Depends on #5143 and just check if it's working properly

**Comment by mustafaboleken** [comment]
During tests, me and Burak abi discover 2 scenarios. First one solved with remove subtrack task but the other scenario is, if you close the tab without clicking exit room button main track also stucks.

**Comment by mustafaboleken** [comment]
I confirmed that, it's fixed.
