### ISSUE TITLE
HLS playback on mobile is not working

### ISSUE THREAD

**Issue by ArthurPatriot** [ant-media/Ant-Media-Server#5144]
### Short description
If you open this from PC - it works. If from mobile - stream not works...
[Stream link](https://ant.net.vn.ua:5443/WebRTCApp/play.html?name=Sm11mVZzAjHc1684847802682&playOrder=hls)

### Environment

* Operating system and version: Ubuntu 22.04
* Ant Media Server version: 2.6.0
* Browser name and version: Any mobile (Chrome / Safari)

**Comment by mustafaboleken** [comment]
Hi @ArthurPatriot, 
thank you very much for the bug report. We will schedule this in the next sprint.

**Comment by ArthurPatriot** [comment]
> Hi @ArthurPatriot, thank you very much for the bug report. We will schedule this in the next sprint.

Can you tell me which version I can downgrade to so that it works?

**Comment by mustafaboleken** [comment]
You can use version 2.5.3 @ArthurPatriot

**Comment by mekya** [comment]
Hi @ArthurPatriot  , @mustafaboleken 

Fix is coming for this issue
