### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by knightwanter** [ant-media/Ant-Media-Server#5153]
/var/log/antmedia/antmedia-error.log {
    daily
    create 644 antmedia antmedia
    rotate 7
    maxsize 50M
    compress
    delaycompress
    copytruncate
    notifempty
    sharedscripts
    postrotate
       reload rsyslog >/dev/null 2>&1 || true
    endscript
}

**Comment by knightwanter** [comment]
while installing ant media on ubuntu

**Comment by muratugureminoglu** [comment]
Hi @knightwanter 

What is the issue, can you please provide more details ?

**Comment by knightwanter** [comment]
when I tried to install ant media server on ubuntu 22 vps it gave me the above error and it also said that ant media server installed and running but I am unable to connect to the page

**Comment by muratugureminoglu** [comment]
What is the version you have tried? Please run the following command and share the output.

```sudo lsof -i -P -n | grep LISTEN```

**Comment by knightwanter** [comment]
systemd-r   395 systemd-resolve   14u  IPv4  15143      0t0  TCP 127.0.0.53:53 (LISTEN)
sshd        704            root    3u  IPv4  16912      0t0  TCP *:22 (LISTEN)
sshd        704            root    4u  IPv6  16923      0t0  TCP *:22 (LISTEN)
java      15703        antmedia  210u  IPv4  39628      0t0  TCP 127.0.0.1:5599 (LISTEN)
java      15703        antmedia  211u  IPv4  39631      0t0  TCP *:44209 (LISTEN)
java      15703        antmedia  606u  IPv4  39711      0t0  TCP *:5080 (LISTEN)
java      15703        antmedia  660u  IPv4  39732      0t0  TCP *:1935 (LISTEN)
java      15703        antmedia  661u  IPv4  40582      0t0  TCP *:9999 (LISTEN)

**Comment by muratugureminoglu** [comment]
Everything seems to be working. You need to open the following ports from the firewall.

https://antmedia.io/docs/guides/installing-on-linux/installing-ams-on-linux/#server-ports

**Comment by muratugureminoglu** [comment]
Hi @knightwanter 

I'm currently closing this issue and feel free to open it if it does not work for you.

Regards.
