### ISSUE TITLE
[JavaScript SDK] Conference call switching room issues

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5159]
Start a conference call. Leave from room and enter another room again. You will get the following errors.

![Screenshot 2023-05-29 at 14 17 09](https://github.com/ant-media/Ant-Media-Server/assets/23143596/0a0118f3-c665-42cb-9ed9-0a4b7f9db2a0)
![Screenshot 2023-05-29 at 14 17 20](https://github.com/ant-media/Ant-Media-Server/assets/23143596/be645edb-1b49-4181-9557-0b418da9f14e)
![Screenshot 2023-05-29 at 14 17 41](https://github.com/ant-media/Ant-Media-Server/assets/23143596/f8382320-745b-41ac-9570-b4abf86da025)

**Comment by mekya** [comment]
I've merged this PR. We can let Amy know about that. They can use via npm snapshot version
@NurC123 @mustafaboleken
