### ISSUE TITLE
MP4 video recording file cycling

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5169]
**Is your feature request related to a problem? Please describe.**
We are running 24-hour surveillance cameras, it's required to record the stream 24/7. As a result, we need to download the recordings every 24 hours to avoid large MP4 files on the server and to be able to review the recordings every 24 hours. Currently, the MP4 is only created once the stream stops.  

**Describe the solution you'd like**
A built-in file cycling that automatically completes an MP4 stream recording at a given interval and then starts recording another MP4 file. There should be no gaps in the stream so everything is recorded. 

**Describe alternatives you've considered**
Currently, the only workaround is to stop/start the live stream every 24 hours to trigger a new MP4 recording. This is not ideal because, during the starting and stopping of the stream, there are some seconds that are left unrecorded while the live stream starts and stops.

**Comment by mekya** [comment]
Although there is a setting, `settings.streamFetcherRestartPeriod` that gets seconds as a value and starts/stops recording periodically, it's not an acceptable solution because of the unrecorded seconds that may happen live stream stops/starts. 
```
settings.streamFetcherRestartPeriod=
```

A permanent solution to this problem is to use the HLS. No need to restart the streams. HLS settings can keep the last 24 hours by specifying the list size and users can convert them to mp4 without transcoding and keep it in the storage. One automated shell script can do this.
  
I think this is a solution.  

PS: If you're onboarding the user, let's write this simple script or get help from the team to provide a working/ready solution to the user.

**Comment by mekya** [comment]
Yes, just let me add one thing. 

If one would like to delete the last 24 hours automatically, s/he can just specify the hls list size and duration accordingly and the server will delete it automatically on the fly. I mean changing following settings on the server
<img width="1717" alt="Screenshot 2023-06-07 at 17 08 44" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/88b9f090-8651-448b-ab9b-f9421fbe4808"> 

For instance, the following settings will keep the last 24 hours and delete older ts files automatically. 
 
segment list size: 720
segment duration: 60

Each ts file duration is 60 seconds and the number of items in the m3u8 is 720.

Let me know if you have further questions

**Comment by timantmedia** [comment]
@mekya just one thing so I fully understand. 

720 items * 60 seconds is 43,200 seconds, but there is 86,400 seconds in 24 hours. Have I calculated this incorrectly?

What's the best way to time the script to download the HLS and convert to MP4? If the HLS is set to be deleted after 24 hours, you might miss some files while downloading the HLS. 

So would a better solution be downloading the HLS and then deleting the files using the script?

**Comment by timantmedia** [comment]
Apologies, I've been backlogged with tickets and other tasks. Unless the priority is higher, I'll be working on this in the next couple of weeks.

**Comment by timantmedia** [comment]
This is first version of the shell script I created. The only issue is the ts files are not concatenating in order it seems. Its was understanding they should concatenate in alphabetical order by name? @mekya 

```shell
username="sshuser"
hostname="ant-media-server-address"

streamid="hlsdownload"
application="LiveApp"

remote_directory="/usr/local/antmedia/webapps/$application/streams"

local_directory="/Users/{user}/Documents/hlsdownload"
file_name=$(date +%Y-%m-%d)

tmp_directory="/Users/{user}/Documents/hlsdownload/tmp"

yesterday=$(date -d "yesterday" "+%Y-%m-%d")

ssh "$username@$hostname" "cd $remote_directory && find . -name '$streamid*.ts' -type f -newermt '$yesterday 00:00:00' ! -newermt '$yesterday 23:59:59' -exec stat -c '%Y %n' {} \;" | sort -n | awk '{print $2}' | while read -r file_path; do
  # Download the TS file to the temporary directory
  scp "$username@$hostname:$remote_directory/$file_path" "$tmp_directory/$(basename "$file_path")"
done

cd "$tmp_directory" && cat *.ts > "$local_directory/bundle.ts"


ffmpeg -i "$local_directory/bundle.ts" -c copy "$local_directory/$file_name.mp4"

rm "$tmp_directory/"*.ts
```

**Comment by muratugureminoglu** [comment]
Hi @timantmedia 

I believe this script should run on the server-side, so some modifications need to be made. Additionally, a cron job should be added, and the merged ts files should be moved or removed to another directory.

**Comment by timantmedia** [comment]
The script does remove the ts files that are downloaded using `rm "$tmp_directory/"*.ts` at the end, but I've noticed that the script doesn't seem to merge the ts files in the correct order. The generated MP4 is not played back as expected, for example, seeing frames from later on in the video at the start.

**Comment by timantmedia** [comment]
@muratugureminoglu please can you help advise what changes you recommend? Also, any idea why the ts files are not merging in correct order?

**Comment by muratugureminoglu** [comment]
Here is a script. 

**Script:**

```
#!/bin/bash

# Define source and destination directories
source_directory="/usr/local/antmedia/webapps/WebRTCAppEE/streams"
destination_directory="/path/to/destination/directory"

# Process .ts files
for ts_file in "$source_directory"/*.ts; do
    # Check if the file was created 24 hours ago
    if [ "$(find "$ts_file" -mtime +1)" ]; then
        # Convert the .ts file into a 24-hour video
        mp4_file="${ts_file%.ts}_24h.mp4"
        ffmpeg -i "$ts_file" "$destination_directory/$mp4_file"
        
        # Optionally, remove the processed .ts file
        # rm "$ts_file"
    fi
done
```

**crontab:**
```
0 0 * * * /path/to/your/script.sh
```

**Comment by muratugureminoglu** [comment]
I'm currently closing this issue and feel free to open it if it does not work for you.
