### ISSUE TITLE
Ability to turn off console.log statements in videojs-webrtc-plugin

### ISSUE THREAD

**Issue by wheelbarrow777** [ant-media/Ant-Media-Server#5174]
**Is your feature request related to a problem? Please describe.**
When using `@antmedia/videojs-webrtc-plugin`, especially the main branch, there is a lot of console.log statements. This clutters the console and it's often preferable to turn it off. 

**Describe the solution you'd like**
Add a log level option to allow for disabling console.log statements in production.

**Describe alternatives you've considered**
Fork the repository and remove all console.log statements. 

**Additional context**

**Comment by mustafaboleken** [comment]
Hi @wheelbarrow777 

I hope you are doing well. Currently, I'm working on this issue. To be on the same page, did you talk about the following logs?



![Image](https://github.com/ant-media/Ant-Media-Server/assets/23143596/6b134c6a-9ecd-4e7a-8c90-fa16f22f1215)
