### ISSUE TITLE
Update mongodb installation documentation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5176]
Mongodb is not installed to the lubuntu 22.04

Please use lsb_release instead of giving the ubuntu version name

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list

**Comment by muratugureminoglu** [comment]
MongoDB 5.0 does not have support for Ubuntu 22.04. Therefore, I have sent an update for MongoDB 6. Additionally, I have performed the following tests and did not observe any issues:

- Tested AMS with MongoDB 6.
- Ran AMS with MongoDB 5 and then upgraded from MongoDB 5 to MongoDB 6. No issues were observed.

https://github.com/ant-media/ant-media-documentation/pull/82

**Comment by muratugureminoglu** [comment]
Additionally, I have also updated the following documents as well.

https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/scaling-with-alibaba.md
https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/azure/setup-ams-clustering-at-azure.md
https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/aws/clustering-with-aws.md

**Comment by muratugureminoglu** [comment]
Additionally, I have also updated the following documents as well.

https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/scaling-with-alibaba.md

https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/azure/setup-ams-clustering-at-azure.md

https://github.com/ant-media/ant-media-documentation/blob/update_mongodb_doc/docs/guides/clustering-and-scaling/aws/clustering-with-aws.md

**Comment by mekya** [comment]
Thank you Mr @muratugureminoglu for your fast move.  "Health to your hands" :)

Could you please proceed one more step by making installation into a script and testing it on our CI?  
I'm asking these for the following reasons
- Installation process will be easier
- We find the issue immediately if there is a problem. Thanks to CI 
- There will be less documentation overhead in the future because we link the mongo installation script in the documentation.  

We can schedule it as a task in the next sprint.

**Comment by muratugureminoglu** [comment]
My pleasure Mr. @mekya 

If you are referring to something like the following, it is in PR[1]. I considered adding it to the other YAML files, but I didn't want to disrupt that structure, so I made a separate naming for it. In this way, we can use this general YAML file for other small automations as well. What do you think?

[1] https://github.com/ant-media/Scripts/pull/238

Additionally, I have added automation for Ubuntu 22.04.

https://github.com/ant-media/Scripts/pull/237

Let me know if you have questions, I will be here for you :)

**Comment by mekya** [comment]
Thank Mr. @muratugureminoglu 

I've one thing to make life easy for you,for me, and for humanity :)

- Put MongoDB installation into a script file. 
- Save the script file in the Scripts repo
- Test that script file in automation
- Add that script file to the documentation so we don't need to update the documentation about MongoDB again. 

Humanity will appreciate you then :))

**Comment by muratugureminoglu** [comment]
Got it. Thanks for clarifying

**Comment by muratugureminoglu** [comment]
https://github.com/ant-media/ant-media-documentation/pull/89
