### ISSUE TITLE
Write documentation/blogpost in Update AWS Cluster

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5185]

**Comment by muratugureminoglu** [comment]
https://antmedia.io/wp-admin/post.php?post=79639&action=edit

**Comment by timantmedia** [comment]
The content is perfect, just working on formatting the content.

**Comment by timantmedia** [comment]
@muratugureminoglu I made some edits and formatting, please just read through and make sure it still makes sense. @asharamseervi could you create a featured image for this if you have time?
