### ISSUE TITLE
AWS changed the flow so attached blogpost needs to be updated

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#5188]
https://antmedia.io/ssl-from-aws-certificate-manager-for-domain-name/

I tried to review #4432 which refers to the above blog post. The visuals from the blog post and AWS system don't match. It might be hard for users.

**Comment by muratugureminoglu** [comment]
https://antmedia.io/ssl-from-aws-certificate-manager-for-domain-name/

**Comment by umtcylmz** [comment]
My notes for this [blogbost](https://antmedia.io/ssl-from-aws-certificate-manager-for-domain-name/): 

Blogpost says "We use “acm-test.antmedia.cloud” and select “DNS validation” for our case"
I use the same URL. I am not sure I am supposed to do that

at the end, I see this: pending validation
<img width="1095" alt="image" src="https://github.com/ant-media/Ant-Media-Server/assets/114407483/20c02af0-ab6f-4a37-a212-b76423d32f29">

In this blogpost: https://antmedia.io/?p=79676&preview=true
It mentions the string name to be added as a last step, but I couldn't find any info about the string name in this [blogpost](https://antmedia.io/ssl-from-aws-certificate-manager-for-domain-name/). I didn't know what to add. I added the name of the load balancer I created.

Images from the heading below, needs to be updated(flow has been changed here as well):
**Use SSL in your Load Balancer**

**Comment by muratugureminoglu** [comment]
- You should use your own domain and verify it through your own DNS service. To verify this domain, you need access to the DNS service of this domain. As mentioned in the documentation:

Write your domain name into the box. We use "acm-test.antmedia.cloud" and select "DNS validation" for our case. 

- This is a CNAME record. It is still related to DNS management and you should have control over your DNS.

- This is a technical document, and it is readily available information that can be easily found on the internet. If we were to include every piece of information here, it would not turn into a blog post.

- Updated it.
