### ISSUE TITLE
Custom CloudFormation script for AWS

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5195]
A user wants to create an autoscaling AMS cluster on AWS using CloudFormation in which they would like to first start with two AMS instances using annual subscriptions from the AWS marketplace and then scale with hourly subscriptions if needed.
Therefore, it is needed to create a custom CloudFormation script to set us this environment.

**Comment by mekya** [comment]
I think we need to have a solution for these scenarios because it's a repeating request and manual work is needed every time. We can discuss it in the meeting.

**Comment by Mohit-3196** [comment]
The cluster has been created for the user.
