### ISSUE TITLE
Analyze which documents to be created and updated according to changelog in 2.6.0 and 2.6.1

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5201]

**Comment by mekya** [comment]
Hi @Mohit-3196 ,
Could you please be more specific about what to update? "JavaScript SDK" update means too generic. 

Gentle reminder: SMART starts with Specific ;)

**Comment by mekya** [comment]
@Yash will update the multirack documentation

**Comment by yashtandon113** [comment]
I have updated the Multitrack document and linked the PR on separate issue https://github.com/ant-media/Ant-Media-Server/issues/5396

**Comment by Mohit-3196** [comment]
#5421
