### ISSUE TITLE
Add blog post about 2.6 release

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5205]

**Comment by timantmedia** [comment]
@mekya Is this the blog post you want to publish https://antmedia.io/?p=79897&preview=true only there is a big overlap with this post https://antmedia.io/?p=79621&preview=true that's also ready to publish. Please let me know if i am looking at the correct blog post.

**Comment by mekya** [comment]
Yes, there is an overlap. As discussed, no worries, we can emphasize easy installation in several post by sharing team after a couple of weeks later.

**Comment by timantmedia** [comment]
This post is scheduled for this Wednesday.
