### ISSUE TITLE
Readme.md url broken

### ISSUE THREAD

**Issue by CrazyFluffyPony** [ant-media/Ant-Media-Server#5212]
### Short description

The link `Upgrade to Enterprise Edition` under the section `Get Started with` is broken:
```
https://https//antmedia.io/free-trial/
```

https://github.com/ant-media/Ant-Media-Server/blame/aa7a00522f96b66fa8e692bffcc3cdf662ffe00f/README.md#LL56C8-L56C8

**Comment by muratugureminoglu** [comment]
Hi @CrazyFluffyPony 

Thank you for bringing this to our attention. I have sent it as a pull request (PR).

https://github.com/ant-media/Ant-Media-Server/pull/5213/files
