### ISSUE TITLE
DataChannel sample app is not working

### ISSUE THREAD

**Issue by zzaman88** [ant-media/Ant-Media-Server#5216]
### Short description
I built the DataChannel sample apps for Flutter but it's not working as expectation

### Environment

* Operating system and version: Android 12
* Java version: 17.0.6
* Ant Media Server version: 
* Browser name and version: Google Chrome

### Steps to reproduce
1.  Run the Datachannel app
2.  Used the following info for the app: 
     Stream address: wss://test.antmedia.io:5443/WebRTCAppEE/websocket
     Stream id: streamId_g3GLk9AVE
3.  Used the following web app:
    https://test.antmedia.io/WebRTCAppEE/datachannel.html?id=streamId_g3GLk9AVE

### Expected behavior
Both ways messaging

### Actual behavior
The message is not sent or received from any end

I asked questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions/5215)

**Comment by mekya** [comment]
Hi @zzaman88 ,

Thank you for reporting this issue. It's likely we'll fix this issue soon and add test codes and we'll not encounter the same problem again.

**Comment by USAMAWIZARD** [comment]
@zzaman88  Thanks for reporting this issue I have fixed this issue and sent a pull request I will be reviewed and merged soon.

**Comment by zzaman88** [comment]
Is code merging done?

**Comment by USAMAWIZARD** [comment]
It has not been merged yet 
Its under review it might get merged by the next week

**Comment by mekya** [comment]
Thank you, guys, for the collaboration.  I've just one idea to proceed and not stay in the blocking state by waiting for the review and merge process. 

@USAMAWIZARD is there any change that you provide a quick workaround solution to let @zzaman88 try it?

**Comment by USAMAWIZARD** [comment]
Sure ,for workaround approch insted of getting the sdk from remote you can clone this repository
Checkout to fix_data_channel  

git checkout fix_data_channel

And then in your project yaml file.

  ant_media_flutter:
     path:  path to cloned repo

**Comment by USAMAWIZARD** [comment]
Lets check this on a call if you are available

**Comment by USAMAWIZARD** [comment]
After cloning the repo
run 
git checkout fix_data_channel

try building the example project

https://github.com/ant-media/Ant-Media-Server/assets/47350008/b7e01b44-dc66-4ad1-b8c7-2bcf2de153af

**Comment by zzaman88** [comment]
Thank you @USAMAWIZARD 
It's working!

but my confusion is why sometimes the stream id needs to change to a different one.

**Comment by mekya** [comment]
Thank you @USAMAWIZARD for providing a solution. I also appreciate that you provide a solution by showing it through video 👏 

There is just one question left from @zzaman88 above. 

Thank you guys.  

> After cloning the repo run git checkout fix_data_channel
> 
> try building the example project
> 
>  www_screencapture_com_2023-6-20_15_43.mp4

**Comment by USAMAWIZARD** [comment]
your welcome let me check this issue and get back to you .

**Comment by USAMAWIZARD** [comment]
@zzaman88 I did not quite understand the problem can you please elaborate  for me. I tried and joining from multiple sides and leaving and rejoining 10 to 15 times but its working for me can you please describe  problem more Thank you
