### ISSUE TITLE
JS SDK 2.6.1 - export 'WebRTCAdaptor' (imported as 'WebRTCAdaptor') was not found in '@antmedia/webrtc_adaptor'

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5221]
### Steps to reproduce
1. Create an simple react application with `npx create-react-app my-app`
2. Install JS SDK with `npm install @antmedia/webrtc_adaptor`
3. Import WebRTCAdaptor to the App.js
```
import { WebRTCAdaptor } from "@antmedia/webrtc_adaptor" 
```
4. Create WebRTCAdaptor object to publish stream
```
var adaptor = new WebRTCAdaptor({...
 websocketURL:"ws://localhost:5080/WebRTCAppEE/websocket"
...});
```

### Expected behavior
Publishing as expected 

### Actual behavior
It gives following error
export 'WebRTCAdaptor' (imported as 'WebRTCAdaptor') was not found in '@antmedia/webrtc_adaptor' (module has no exports)
 

<img width="1717" alt="Screenshot 2023-06-11 at 12 41 29" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/89bff0a7-5c97-42ca-b551-bffd44fdadf1">

**Comment by mekya** [comment]
Here is a workaround solution and permanent solution is coming soon

- Open `node_modules/@antmedia/webrtc_adaptor/package.json`
- Change `type` from `module` to `commonjs`. It should be like the below after you edit and save it
```json
  ....
  "scripts": {
    "codecov": "codecov",
    "compile": "rollup -c rollup.config.module.cjs && rollup -c rollup.config.browser.cjs ",
    "test": "karma start karma.conf.cjs"
  },
  "type": "commonjs",
  "version": "2.6.1"
}
```
- Install url as polyfill 
```
npm install url --save
```
- Remove cache directory to not encounter any cache issue
```
rm -rf node_modules/.cache
```
- Start again
```
npm start
```

**Comment by lastpeony** [comment]
I confirmed that commonjs fix provided by mekya is working.
Closing the issue.
