### ISSUE TITLE
Write script to publish and play streams 7/24 in staging environment

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5225]
New developments may have some unexpected memory issues so let's start running publish/play scenarios 7/24 

The first stage of this task, write a script(python, node, etc) having the following scenario

Publish and Play Continuously 
- Open headless web-browser for WebRTCAppEE/index.html with streamId: stream724
- Publish Live Stream
- Open another tab for WebRTCAppEE/play.html?id=stream724
- Check the system for every 1 minute  
    -  stream724 is alive and there is one player
    - there is no crash log and there is no heapdump 
    - If there is a crash or any error, send message to "alert" channel in slack
 

Publish and Play Intermittent 
Start:
   - Open headless browser publish live stream with random streamId
   - Open another tab and play the stream 
   - Check that stream is alive and there is one player
   - After 1 minute 
       - Stop playing
       - Stop publishing
   - Check that there is no crash log and there is no heapdump. If there is a crash or any error, send message to "alert" channel in slack
   - Goto 'Start' and repeat the again

**Comment by yashtandon113** [comment]
This task is in progress

**Comment by yashtandon113** [comment]
Work is in progress for 1st scenario:

Publish and Play Continuously - Script is almost done. I will schedule meeting with @muratugureminoglu to discuss about running the stream 24x7 using the workflow.

**Comment by yashtandon113** [comment]
Script has been completed and workflow is also created. Currently it is under testing on my own repo. Here is the reference link: https://github.com/yasht0105/24-7-staging

**Comment by yashtandon113** [comment]
Selenium is running on the server continuously, and a GitHub work flow is running every 5 minutes (cannot run the workflow for every 1 minute on GitHub workflow) to monitor the status of the stream and any error logs or heap dumps.

The only problem is that sometimes a 24x7 selenium script running in backend stops unexpectedly even when the is no change on the server side, so we are looking into it.

**Comment by yashtandon113** [comment]
It is done and working in my testing environment.

**Comment by yashtandon113** [comment]
Part-1 is completed as it is implemented on AMS scripts repository as well.
