### ISSUE TITLE
No orientation detection in Flutter SDK

### ISSUE THREAD

**Issue by Dgut** [ant-media/Ant-Media-Server#5235]
Aspect ratio of video doesn't change if you rotate device.

### Environment
Flutter Publish example
https://github.com/ant-media/WebRTC-Flutter-SDK/tree/main/example/Publish
iPhone XS iOS 16

### Steps to reproduce
1. Install Publish example on device
2. Connect to your server
3. Start streaming video
4. Check video from your server - it will show constant aspect ration no matter what real device orientation currently is.

### Expected behavior
Dynamic change of width & height depending on recording device orientation.

### Actual behavior
Constant width & height.

**Comment by USAMAWIZARD** [comment]
you will need to turn on auto rotation for this 

https://github.com/ant-media/Ant-Media-Server/assets/47350008/23e74b1c-7d13-4dc6-bca6-a04e292a4488

**Comment by Dgut** [comment]
Hi! Unfortunately, no. As you can see from the video auto rotation is on.

https://github.com/ant-media/Ant-Media-Server/assets/10653405/64db287c-601f-4b81-8fba-d0ad1a4faabe

**Comment by USAMAWIZARD** [comment]
Hi @Dgut
It may only be reproducible on IOS let me check this and get back to you.

**Comment by USAMAWIZARD** [comment]
I have raised a PR Please try out from this branch 

https://github.com/ant-media/WebRTC-Flutter-SDK/pull/34
