### ISSUE TITLE
when the initial index.html - How to set default camera to OBS virtual Camera

### ISSUE THREAD

**Issue by Jamong435** [ant-media/Ant-Media-Server#5241]
If you want to set the default camera to OBS Virtual Camera when the initial index.html file is generated by Ant Media, what code modifications are needed?

**Comment by USAMAWIZARD** [comment]
1. You can use this function to change the device after initializing webRTCAdaptor
```webRTCAdaptor.switchVideoCameraCapture(streamId,DeviceId);```

*To Change Camera to OBS in the publish page*
Edit /usr/local/antmedia/webapps/{APPNAME}/samples/publish_webrtc.html  

for changing the device to obs camera add these lines to the code  it will check if the label name of the camera includes obs and if yes then it will set it as the camera.
```
if(label.toLowerCase().includes("obs")){
      webRTCAdaptor.switchVideoCameraCapture(streamId, device.deviceId);
}
```
It will look some thing like this 

```

if (device.kind == "videoinput") {
	if (typeof label == "undefined" || label == "") {
		label = "Cam-" + cameraIndex;
	}
	if(label.toLowerCase().includes("obs")){
	webRTCAdaptor.switchVideoCameraCapture(streamId, device.deviceId);
	}
	cameraIndex++;
	videoHtmlContent += getCameraRadioButton(label, device.deviceId);
}
```

**Comment by USAMAWIZARD** [comment]
@Jamong435 Did you get a chance to look at my answer ? Thank you.

**Comment by USAMAWIZARD** [comment]
Closing this GitHub issue due to inactivity. Please feel free to reopen it if needed.
