### ISSUE TITLE
cloudformation yaml script still use ubuntu 20.04

### ISSUE THREAD

**Issue by ashrafbendary** [ant-media/Ant-Media-Server#5243]
https://github.com/ant-media/Scripts/blob/master/cloudformation/antmedia-aws-autoscale-template.yaml

cloudformation yaml script still use ubuntu 20.04 while 2.6.1 version support 22.04

**Comment by muratugureminoglu** [comment]
The CI pipelines are currently based on Ubuntu 20.04. We have a planned approach to gradually shift to 22.04 support.

**Comment by muratugureminoglu** [comment]
Hi @ashrafbendary 

I have added Ubuntu 22.04 support to the CloudFormation template, but since our testing processes have not yet transitioned to Ubuntu 22.04, submitted it as a PR here. Fyi.

**Comment by yashtandon113** [comment]
As our AWS marketplace image still runs on Ubuntu 20.04 so instances launched through template is also utilizing Ubuntu 20.04. I will create the custom image with Ubuntu 22.04 to test the same.

**Comment by yashtandon113** [comment]
As tested by building an image with Ubuntu 22.04 and using it with the Cloud formation template, it works as expected.

**Comment by muratugureminoglu** [comment]
Thank you, @yashtandon113. Then let's update the other templates as well.
