### ISSUE TITLE
Merged stream recording is not generating if the server is restarted in between

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5252]
### Short description
The merged stream is generated after joining the conference room in MCU mode, but if recording is enabled and the server restarts unexpectedly, individual participant recordings are generated fine on the server, but the merged stream recording is not generated and hangs in the **mp4.tmp_extension** under the streams directory.

### Environment
* Ant Media Server version: v2.6.1

### Steps to reproduce
1. Enable mp4 recording in application settings
2. Create conference room with "mcu" mode using Rest API
3. Join the room using multitrack-conference.html
4. Restart the server in between

### Expected behavior
After the server is restarted, recordings of all participants and merged stream should be available.

### Actual behavior
Recordings of participants streams are generated but merged stream recording is not generated and stuck into **mp4.tmp_extension** under streams folder.

**Comment by mekya** [comment]
hi @yashtandon113,
 
I think we're moving away from recording in MCU to Web Page Recording because there are issues/cases in MCU recording.

@mustafaboleken has developed a simple solution for these kinds of recording things.  
Let's put that development into the game.
