### ISSUE TITLE
Add screen size argument to WebpageRecordingPlugin

### ISSUE THREAD

**Issue by mav-git** [ant-media/Ant-Media-Server#5259]
**Is your feature request related to a problem? Please describe.**
We would like to be able to set a desired window size for the WebpageRecordingPlugin

**Describe the solution you'd like**
Screen width and height should be passed in a JSON body together with url parameter, for example
`{ "url": "https://example.com", "width": 1920, "height": 1080 }`

**Describe alternatives you've considered**
We tried to build our own plugin version, but we failed. There are no clear instructions on what dependencies need to be installed

**Comment by yashtandon113** [comment]
As discussed with @mustafaboleken, the width and height parameters are not working as expected.

Here is the sample Rest API call:

`curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "http://localhost:5080/WebRTCAppEE/rest/v1/webpage-recording/start?streamId=your-streamid" -d '{"url": "https://example.com", "width": 1920, "height": 1080}'`

It is as below:

![image](https://github.com/ant-media/Ant-Media-Server/assets/82374739/6f76f532-e55a-4794-a5e3-e2960bbc5023)

**Comment by mustafaboleken** [comment]
To solve this problem I added video constraints into chrome plugin with minimum and maximum width

**Comment by yashtandon113** [comment]
Width and Height parameters are not working after the latest change. As discussed with @mustafaboleken, the chrome plugin has been updated to the most recent version, and the following issue must also be addressed.
https://github.com/ant-media/Ant-Media-Server/issues/5365
