### ISSUE TITLE
Support for external USB camera in the Android SDK

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5263]
**Is your feature request related to a problem? Please describe.**
Currently, in the Android SDK there is no built-in support for choosing an external USB camera. 

**Describe the solution you'd like**
I would like to have the option to select an external USB camera within the Android SDK.

**Comment by mekya** [comment]
Hi @Mohit-3196,

If one user is asking for this feature, I think we can delegate it to one of the partners that can make this implementation. 

Regards

**Comment by thoyyu** [comment]
I also need the External USB Camera support in Android SDK as well. My company uses USB OTG External Camera with Android Devices to Live Stream POV video from External Cameras. External USB Camera support is very important for us. I hope support for External USB Camera will be added to Ant-Media Android SDK soon.

**Comment by mekya** [comment]
I see. Let's start the discussion how we can do this with one of the partner @Mohit-3196 

Btw, shall we have a meeting with you @thoyyu to understand your case and scale to give the correct priority to this issue?

**Comment by thoyyu** [comment]
Hi, sorry for the late reply. I am available next week to discuss our USB Camera Support requirements. Our company develops Police Bodycams that uses Android OS and supports USB OTG External Cameras. The Android App we developed for our BodyCam uses AntMedia Server and AntMedia Android SDK to live stream video from BodyCam to a control center system. Currently, we can only live stream video from the Primary (built-in) Camera of the Android Device using AntMedia Android SDK. The SDK does not allow us to use the connected External USB Camera.

**Comment by thoyyu** [comment]
Hi @mekya , I am available this week. When can we discuss about the USB Camera support for AntMedia Android SDK.

**Comment by mekya** [comment]
Hi @thoyyu,

That's good to hear. Do you mind scheduling a meeting here?
https://calendly.com/mekya/

If timing does not work for you, let us know your availability through contact@antmedia.io and my colleague will schedule the meeting.

Cheers

**Comment by thoyyu** [comment]
Hi @mekya ,

I have already booked your calendar for Friday, Aug 11. Please let me know if you have received my booking

**Comment by timantmedia** [comment]
@mekya another customer is interested in this feature https://github.com/ant-media/Ant-Media-Server/issues/5462

**Comment by thoyyu** [comment]
Hi @mekya,

Thank you for meeting with me last week. Could you please provide the high-level instructions discussed in the meeting?

**Comment by thoyyu** [comment]
@mekya do you have any update on this feature?
