### ISSUE TITLE
Write an internal documentation for customizing cloudformation as a internal document

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5266]

**Comment by muratugureminoglu** [comment]
https://docs.google.com/document/d/1fPVNKMWw8DQJV9fb_tPT7jJxd3gH6iE8f0toEc8nkbM/edit?usp=sharing

**Comment by Mohit-3196** [comment]
https://docs.google.com/document/d/1rh9Lo4If90BB2RKN48JPX6_CWFnbtF-i18fUuvxANpA/edit?usp=sharing
