### ISSUE TITLE
Write Python Script to check new Samples on antmedia.io

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5268]

**Comment by muratugureminoglu** [comment]
If I understood correctly, it varies based on HTML tags, and there may be a situation where it doesn't work when there is a change in those pages.

Example : https://github.com/ant-media/Scripts/blob/d0fcbded688394bd83f165fe8d762c807c6ea75e/Selenium/antmedia-samples.py#L96-L100

**Comment by muratugureminoglu** [comment]
@yashtandon113 We can take a look at this week together if you want.

**Comment by muratugureminoglu** [comment]
Hi @yashtandon113 

I merged this, but as I mentioned in the previous comment, this will likely be a problem in the future. Therefore, it would be nice to find a new solution. Thanks.
