### ISSUE TITLE
Add Multirack Conference to the Samples

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5269]
- [x] WebRTC Test Tool
- [x] Whiteboard 
- [x] Multitrack conference - In Progress
- [x] Embed the circle

**Comment by USAMAWIZARD** [comment]
https://github.com/ant-media/StreamApp/pull/386

**Comment by USAMAWIZARD** [comment]
ADDED [Multitrack Conference Solution](https://antmedia.io/webrtc-samples/multitrack-conference-solution/)

**Comment by USAMAWIZARD** [comment]
Added [Circle Conference Call Application](https://antmedia.io/webrtc-samples/circle-conference-call-application/)
