### ISSUE TITLE
How to get started with GCP - Blogpost

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5293]

**Comment by muratugureminoglu** [comment]
https://antmedia.io/wp-admin/post.php?post=81211&action=edit

**Comment by yashtandon113** [comment]
I tested the AMS on Google Cloud Platform and it launched successfully by following the defined steps in a blog post.

@muratugureminoglu 
FYI please, In default security group rules, UDP ports 50000-60000 rule is not there so WebRTC does not work by default.

**Comment by muratugureminoglu** [comment]
Hi @yashtandon113 

The port range is not allowed in GCP, so I added it as a note it. Fyi.

**Comment by yashtandon113** [comment]
I've added a note to the blog post about adding a UDP port range to the security group for WebRTC.

@timantmedia 
FYI please, you can add this blog post to your timeline for later review and publication.

**Comment by timantmedia** [comment]
I'll add this. Thank you.
