### ISSUE TITLE
Make mongodb installation script do all manual works in the documentation and update documentation

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5296]

**Comment by muratugureminoglu** [comment]
Script PR: https://github.com/ant-media/Scripts/pull/250
Document PR: https://github.com/ant-media/ant-media-documentation/pull/106

**Comment by Mohit-3196** [comment]
Works fine.
I was able to call the script with `sudo ./install_mongodb.sh --auto-create` and it installed MongoDB with username and password.
Calling it without `--auto-create` simply installs MongoDB without security

**Comment by muratugureminoglu** [comment]
@Mohit-3196 If everything is ok, let's merge then

**Comment by Mohit-3196** [comment]
Sure abi.
There are some comments on the document by @timantmedia 
FYI please

**Comment by timantmedia** [comment]
@muratugureminoglu Yes I suggested a couple of wording improvements.

**Comment by Mohit-3196** [comment]
It is merged
