### ISSUE TITLE
Live video recording freezes when we play after live ends

### ISSUE THREAD

**Issue by Vaibhav-Agarwal06** [ant-media/Ant-Media-Server#5302]
We are still facing the same issue in Enterprise Edition 2.6.1 20230602_0921.
Can you please check this issue again. If you need any details from our side then please let us know.

This issue is coming in apple devices only and it's woking fine in Android.

https://github.com/ant-media/Ant-Media-Server/issues/4806#issuecomment-1608813412

**Comment by yashtandon113** [comment]
Hi @Vaibhav-Agarwal06 
Thanks for raising the issue again.
I tried publishing the stream from an iPhone 12 device using Chrome, but the problem did not reproduce. The recording appears to be fine.

Here is the reproduce scenario:

- Stream was published from a mobile browser using a sample web page (https://domain:5443/LiveApp).
- Watch the stream in desktop browser
- Several times switched between front and rear cameras
- Play the recorded stream.

Please let me know if any step is missing.

**Comment by yashtandon113** [comment]
@Vaibhav-Agarwal06 
Thanks for sharing the information.
Could you please share step-by-step reproduce scenario to replicate the issue including app name etc?

**Comment by mekya** [comment]
I've added this to the sprint plan so that my colleague will respond you @Vaibhav-Agarwal06 

Regards
Oz

**Comment by yashtandon113** [comment]
@Vaibhav-Agarwal06 

My email address is yash.tandon@antmedia.io.

If additional information is required, we will schedule the meeting accordingly.

**Comment by yashtandon113** [comment]
@Vaibhav-Agarwal06 
I am closing this issue. You can email me on my shared address and we can follow up there or you can also raise the support ticket on support@antmedia.io.
