### ISSUE TITLE
playback not working after release 2.6.1 on Safari iOS 14.4

### ISSUE THREAD

**Issue by samidalati** [ant-media/Ant-Media-Server#5306]
### Short description
playback not working after release 2.6.1 on Safari iOS 14.4, I have also tested 2.6.2 (Enterprise) and the issue persists. Issue is detected on iPad running iOS 14.4 on both safari and chrome. it cannot play using the index.html or player.html. There is an error on page load 
```
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	promiseReactionJob
```
<img width="736" alt="image" src="https://github.com/ant-media/Ant-Media-Server/assets/4776750/b4fcc5fe-34a9-4937-886b-c424e902c416">

### Environment

* Operating system and version: iOS 14.4
* Java version: 
* Ant Media Server version: 2.6.2, 2.6.1
* Browser name and version: chrome and safari

### Steps to reproduce
1. open the antmediaServer/player.html
2. Observe error on page load
3. Insert stream key
4. The `Start Playing` button is not responsive

Note that even the play button from the antmedia dashboard is not working

### Expected behavior
live stream would play

### Actual behavior
video does not play

 

### Logs

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Thank you @samidalati for the issue. Let us check.

**Comment by haoran965** [comment]
It's seems that Safari can't support new syntax. But I don't know what's the specific grammar.

**Comment by mekya** [comment]
Hi @haoran965 ,
Thank you for the comment. 

Do you have any update @timantmedia ?

**Comment by timantmedia** [comment]
@mekya I tested playback on iOS 16 simulator and there were no issues. I am now setting up the iOS 14.4 simulator to try and reproduce because I did not have that installed.

**Comment by louaiah** [comment]
@timantmedia Hello, I just tested the player on iOS 14.0 and the same issue still persists. It's working as intended on iOS 15.0 and up.

**Comment by mekya** [comment]
Hi @louaiah,
Thank you for confirming. 

I've just checked iOS 14 is pretty old. I'm not clear we need to give support for this case and spend time for this.  
On your end, is it something you have to give support for iOS 14?

**Comment by timantmedia** [comment]
@louaiah Can you help us determine how important iOS 14 is for you? It's 3 years old, do you see the need for significant support for this version?

**Comment by louaiah** [comment]
@timantmedia Hello, let's drop this issue. After a bit of assessment we figured it's probably not worth fixing as phones that don't support ios 15 are really old. Thanks.
