### ISSUE TITLE
Hash-Based Token does not work

### ISSUE THREAD

**Issue by modestfalcon** [ant-media/Ant-Media-Server#5327]
### Short description
When setting parameters:
settings.hashControlPublishEnabled=true
settings.hashControlPlayEnabled=true
tokenHashSecret=SECRET_KEY

Hash-Based Token does not work, I can stream without specifying a token.

### Environment

* Operating system and version: 5.4.0-150-generic 167-Ubuntu (DigitalOcean)
* Java version: openjdk version 11.0.19 2023-04-18 OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1) OpenJDK 64-Bit Server VM (build 11.0.19+7- post -Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
* Ant Media Server version: Community Edition 2.6.2 20230623_0842
* Browser name and version: Brave 1.52.129 Chromium: 114.0.5735.198 (64-bit)

### Steps to reproduce
1. Go to your application to the settings section, click on Advanced
2. Search for parameters: settings.hashControlPublishEnabled and settings.hashControlPlayEnabled set to true, enter 
tokenHashSecret 
3. Save your settings
4. Open OBS Studio, paste Copy Publish URL but do not enter token

### Expected behavior
OBS should not stream if a token has not been provided.

### Actual behavior
Regardless of whether a Hash-Based Token is given or not OBS streams. It is currently not possible to secure the stream using this method. 

 

### Logs
Settings: https://pastebin.com/z9Ui69qS

**Comment by yashtandon113** [comment]
@modestfalcon 
Thanks for reporting the issue.

I have tried to reproduce the issue on my end using AMS v2.6.2 and it seems working fine on my end.
Also token mechanism does not work with Community Edition of AMS. You need to use the Enterprise Edition to use the token security methods.

You can request for the free trial of AMS Enterprise Edition on https://antmedia.io/free-trial/ 

Please let us know if you have any questions.

**Comment by yashtandon113** [comment]
@modestfalcon 
I am closing this issue for now. I hope my above comment answers your question.
Please reopen the issue if you have any further question.
