### ISSUE TITLE
Always getting the Failed resending RTP packet Errors.

### ISSUE THREAD

**Issue by k99IT** [ant-media/Ant-Media-Server#5330]
We're using AMS Enterprise Edition 2.5.3,

(389): Failed resending RTP packet 31084, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31089, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31093, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31076, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31095, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31098, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31112, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31115, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31119, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31122, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31126, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31076, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31140, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(transport_feedback_adapter.cc:275): Failed to lookup send time for 1 packet. Send time history too small?
(rtp_sender.cc:389): Failed resending RTP packet 31076, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31076, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(transport_feedback_adapter.cc:275): Failed to lookup send time for 1 packet. Send time history too small?
(rtp_sender.cc:389): Failed resending RTP packet 31078, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31206, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31078, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31218, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31225, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31078, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31078, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31068, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31073, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31276, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31078, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31279, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31104, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31283, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31285, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31084, Discard rest of packets.
(rtp_sender.cc:389): Failed resending RTP packet 31293, Discard rest of packets.

**Comment by mekya** [comment]
hi @k99IT ,

Thank you for the issue. May I ask you gently explain your experience in much more clear way? 

So that we can reproduce it on our end. Please explain the problem as if you're explaining to a dummy guy.
