### ISSUE TITLE
RTMP Stream getting mixed up In cluster mode

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5341]
### Short description
when in  cluster mode with 2 nodes and  publishing two RTMP streams in two different applications the stream is getting mixed up on playing side.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:2.6.0
* Browser name and version: 
* RTMP Client : OBS

### Steps to reproduce
1. make cluster of two nodes
2. on one node in two different applications create a live stream  with same name (in different applications).
3.publish rtmp to both of the live streams that is created using OBS
4. delete one of the live stream from the server dashboard
5. OBS will reconnect
6. now play the live streams you will see that the streams are getting mixed up

### Expected behavior
streams should not be mixed

### Actual behavior
streams are getting mixed
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Closing this issue because fix for this implementation has been merged to the master. Please feel free to re-open if it does not work for you
