### ISSUE TITLE
WebRTC-Flutter-SDK  change streaming video width and height

### ISSUE THREAD

**Issue by newengine** [ant-media/Ant-Media-Server#5345]
are there any way to change the streaming video width, height,  and video mode of landscape or portrait

i tried the apply the mediaConstraints config to the stream.   it doesn't work.

**Comment by USAMAWIZARD** [comment]
you can set the height and width something like this.
the file should be present at .pub-cache/hosted/pub.dev/ant_media_flutter-1.0.3/lib/src/helpers
```
Future<MediaStream> createStream(media, userScreen) async {
    final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth': '500', // Set the desired width
          'minHeight': '500', // Set the desired height

        },
        'facingMode': 'user',
        'optional': [],
      }
    };
```
and for landscape mode enable auto rotation on the mobile then it will automatically rotate in landscape mode

**Comment by USAMAWIZARD** [comment]
@newengine please let me know if this solution works for you.

**Comment by USAMAWIZARD** [comment]
I am closing the issue for inactivity please reopen it if you are still facing the issue.

**Comment by USAMAWIZARD** [comment]
I am closing the issue for inactivity please reopen it if you are still facing the issue.
