### ISSUE TITLE
Stream stuck in broadcasting state when one of the node cluster gets inaccessible

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5361]
### Short description
In a scenario where there are two nodes in the cluster and client is publishing RTMP stream to one of the node and that node gets inaccessible then the streams will be stuck in broadcasting mode.then we cannot delete that stream as well they are just stuck.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:2.6.0
* Browser name and version:

### Steps to reproduce
1. two nodes in the cluster
2.  streams publishing one  of the node 
3. make that node inaccessible (Crash  the node )
4. streams will be stuck in broadcasting state.and cannot be deleted as well.

### Expected behavior
streams should be offline 

### Actual behavior
streams stuck in broadcasting 
 
When I check the broadcast object using REST API.
the origin IP of the broadcast is the node which was disconnected.

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by sahiljain2497** [comment]
This might be related as well. I am on Enterprise Edition 2.6.2 20230623_0843

https://github.com/ant-media/Ant-Media-Server/assets/28824550/c5fdf5f6-76c0-46f5-87dd-77159a2bac80

**Comment by lastpeony** [comment]
This could be connected to a web panel attempting to send a request to a node that lacks the stream. Addressing this by directing requests to the appropriate cluster nodes can resolve the issue. Further information will be provided shortly.

**Comment by SebastienGautier** [comment]
I updated to 2.6.3 but I still have 2 streams stuck in the broadcasting state that I am unable to stop or delete
Was this fix supposed to handle that or only avoid new streams being stuck ?

**Comment by mekya** [comment]
Hi @SebastienGautier,
Yes, this fix is supposed to handle your case as well. Is there a chance that you can let us take a look at your setup by sharing webpanel credentials and ssh if possible?

You can send it to support@antmedia.io

**Comment by SebastienGautier** [comment]
Hi @mekya 
It's now our production instance, I can't give access to this one
The error I get in the logs when I tried to delete a bugged stream is the following:
`2023-09-19 07:12:59,080 [http-nio2-0.0.0.0-5080-exec-9] ERROR io.antmedia.rest.RestServiceBase - Please send a Delete Broadcast request to the x.x.x.x node or Delete Broadcast in a stopped broadcast.`

**Comment by muratugureminoglu** [comment]
<div>Agent Amarnath Thodupunoori linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/132100">132100</a> for this issue.</div><br/>

**Comment by muratugureminoglu** [comment]
<div>Agent Alper KIZILTOPRAK created comment. </div><br/><div class="mail-track-note">
    <img class="mail-track-device" src="https://backend.growthdot.com/images/mail-tracking/device-phone.svg" title="Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148" alt="" width="24">    <img class="mail-track-identity" src="https://app.growthdot.com/mail-track/icon_nav_bar.svg" alt="Email Tracking" width="16" height="16">
    Email reading has been tracked by <b>Email Tracking</b> app
    <hr>

    <div class="mail-track-note-header">
            Email was read
        3 hours after it was sent
</div>

<div>✉ Sent on 19:19:13 12 August 2024 +02:00</div>

    <div>✔ Read on 23:08:18 12 August 2024 +02:00</div>

    </div>

**Comment by muratugureminoglu** [comment]
<div>Agent Amarnath Thodupunoori unlinked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/132100">132100</a> from this issue.</div>
