### ISSUE TITLE
Migrate Webpage Recording Plugin to Chrome Manifest v3

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5365]
Google started limiting some features of Google Chrome Plugins which uses Manifest v2 starting from v112 and they plan to restrict it completely with v115. We should move to manifest v3 asap.

https://developer.chrome.com/docs/extensions/migrating/
https://developer.chrome.com/blog/more-mv2-transition/

**Comment by mekya** [comment]
Waiting for Chrome 116 update

**Comment by mustafaboleken** [comment]
Moved to https://github.com/ant-media/Plugins/pull/75
