### ISSUE TITLE
Unable to upgrade antmedia server on docker with volumes

### ISSUE THREAD

**Issue by wheelbarrow777** [ant-media/Ant-Media-Server#5379]
### Short description

When attempting to upgrade the antmedia server using the docker files as described [in the documentation](https://antmedia.io/docs/guides/clustering-and-scaling/docker/docker-and-docker-compose-installation/) while using volumes, the server is not upgraded even though the new docker container has been used. The boot logs says `Ant Media Server Enterprise 2.5.3`, even though 2.6.2 is installed. If I boot the same docker image with a fresh volume, it says `Ant Media Server Enterprise 2.6.2` as expected. 

### Environment

* Operating system and version: Amazon Linux aarch64
* Java version: Using docker, not applicable
* Ant Media Server version: 2.5.3, attempting upgrade to 2.6.2
* Browser name and version: Not applicable

### Steps to reproduce

1.  Use .zip file for 2.5.3 to create a docker compose setup with volumes as described [in the documentation](https://antmedia.io/docs/guides/clustering-and-scaling/docker/docker-and-docker-compose-installation/).
2. Boot up the docker compose with volumes.
3. docker compose down the container
4. Create a new docker image with `2.6.2` zip. Use the same volume as used for the `2.5.2` container. (we want to do this to keep our settings and data)
5. On boot, the logs will say `[main] org.red5.server.Launcher - Ant Media Server Enterprise 2.5.3`, and not `[main] org.red5.server.Launcher - Ant Media Server Enterprise 2.6.2` as expected.

### Expected behavior

Expecting version 2.6.2 to boot, still getting 2.5.3.

### Logs
https://pastebin.com/raw/EwPMyf5N

**Comment by mekya** [comment]
Hi @wheelbarrow777

Thank you for creating the issue . Put it to the backlog to assign to one of my colleague

Cheers

**Comment by muratugureminoglu** [comment]
Hi @wheelbarrow777 

The upgrade process doesn't work with our installation script. The best way to handle this is to create an image with version 2.6.2 and then copy the files from version 2.5.3 into the 2.6.2 image. 

Let me share how you can do it (I wrote a bash script for you :) ):

**1.** First, copy the `antmedia` (**/usr/local/antmedia/**) directory from the container you want to upgrade from to your local disk:

```
docker cp aea5933b6436:/usr/local/antmedia/ .  #container ID 'aea5933b6436', please don't forget to change your own image id.
```
**2.** Then stop the container which is version 2.5.3.

**3.** Start the version 2.6.2

Then, after adjusting the variables 'CONTAINER_NAME' and 'BACKUP_DIR' in the script below according to your setup, run the script. Then restart the container. This will ensure that your old data is available in the new Docker version.

```
#!/bin/bash

# Define container name or ID
CONTAINER_NAME=baea92802edf

# Define paths
AMS_BASE=/usr/local/antmedia
BACKUP_DIR=./antmedia

restore_settings() {
  # Copy specific files to the container
  docker cp $BACKUP_DIR/webapps/LiveApp/WEB-INF/red5-web.properties "${CONTAINER_NAME}:${AMS_BASE}/webapps/LiveApp/WEB-INF/red5-web.properties"
  docker cp $BACKUP_DIR/webapps/WebRTCAppEE/WEB-INF/red5-web.properties "${CONTAINER_NAME}:${AMS_BASE}/webapps/WebRTCAppEE/WEB-INF/red5-web.properties"
  docker cp $BACKUP_DIR/server.db "${CONTAINER_NAME}:${AMS_BASE}"
  docker cp $BACKUP_DIR/liveapp.db "${CONTAINER_NAME}:${AMS_BASE}"
  docker cp $BACKUP_DIR/webrtcappee.db "${CONTAINER_NAME}:${AMS_BASE}"
  docker cp $BACKUP_DIR/conf/red5.properties "${CONTAINER_NAME}:${AMS_BASE}/conf"
  docker cp $BACKUP_DIR/conf/jee-container.xml "${CONTAINER_NAME}:${AMS_BASE}/conf"
  docker cp $BACKUP_DIR/conf/instanceId "${CONTAINER_NAME}:${AMS_BASE}/conf"
}

# Call the restore_settings function
restore_settings
```

Please let me know if you have any questions.

**Comment by muratugureminoglu** [comment]
Hi @wheelbarrow777 

I'm currently closing this issue due to its inactivity. Feel free to reopen it if it does not work for you.
