### ISSUE TITLE
Open webrtc adaptor without camera/mic and open video/audio on the fly - Provide live sample on the codepen.io

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5392]
Scenario
1 – First user initially joins the room. That user is in datachannel only mode (dcOnly = true using url parameter ?dcOnly=true).
2 – 2nd user joins the room. The 2nd user is also in datachannel only mode (dcOnly = true).
3 – Then one of the users starts video (Turn on Camera button).
4 – Same for 2nd user, also starts video.

What we want to do is to go from datachannel only mode to normal conference mode without closing the datachannel connection and reconnecting with webrtcadaptor.onlyDataChannel = true, basically dynamically switch from one mode to the other maintaining the connection and the same stream id.

Discussed here
https://github.com/orgs/ant-media/discussions/5367

**Comment by mekya** [comment]
Hi 
SNAPSHOT release is available in npmjs for testing. [Check the live sample on codepen.io: Start WebRTC Publish without Opening Cam/Mic and Open Cam/Mic on the fly](https://codepen.io/mekya/pen/VwVEXNq)
> 
> Let me quick info for the developers:
> 
> 1. Initialize the WebRTC adaptor with dummy audio and video as below
> 
> ```js
> var webRTCAdaptor = new WebRTCAdaptor({
>   websocket_url: "wss://test.antmedia.io:5443/WebRTCAppEE/websocket",
>   localVideoElement: document.getElementById("localVideo"),
>   mediaConstraints: {
>     video:"dummy",
>     audio:"dummy"
>   }
> });
> ```
> 
> 2. Publish the stream
> 
> ```js
> webRTCAdaptor.publish("your_stream_id");
> ```
> 
> 3. Open camera and Mic on the fly
> 
> ```js
> webRTCAdaptor.openStream({video:true, audio:true}, "your_stream_id");
> ```
> 
> Please pay attention that second parameter is critical and it is the stream id of your current active broadcast. `webRTCAdaptor` uses that value to change the tracks of the peer connection on the fly.

**Comment by timantmedia** [comment]
@mekya  I tested this extra method to close the video/audio 

```
closeAudioVideoButton.addEventListener("click", () => {
  console.log("close_audio_video is clicked");
  webRTCAdaptor.openStream({video:"dummy", audio:"dummy"}, streamId);
});
```

 which seems to work shut off the video/audio successfully.

**Comment by mekya** [comment]
Yes, we can also use turnOn/turnOff camera and mute/unmute methods to close it. 
Let me put a close audio/video button to the sample as well
