### ISSUE TITLE
[Flutter SDK] Sample apps not working on iOS

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5394]
We should update pod files for iOS.

**Comment by mekya** [comment]
Hi @mustafaboleken ,
I'm moving to the backlog for this issue. In order to schedule for next sprint, please let us know if an user is waiting for this case or it's just a improvement.

**Comment by mustafaboleken** [comment]
Hi @mekya,
I just found this problem, no customer is waiting for it.
