### ISSUE TITLE
How exactly can I install the Ant Media Server on Ubuntu 18.04 with ARM64? Maybe a detailed guide?

### ISSUE THREAD

**Issue by GrandArth** [ant-media/Ant-Media-Server#5395]
https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-can-i-install-the-ant-media-server-on-ubuntu-1804-with-arm64  did't explain much...

Should i just remove the `if ... fi` line producing:
```
ARM architecture is supported on Ubuntu 20.04. For 18.04 installation, use the link below to install.
https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-can-i-install-the-ant-media-server-on-ubuntu-1804-with-arm64
```
and then follow the insturction on the wiki?

**Comment by GrandArth** [comment]
Yeah... just comment these lines out:
```
      # if [ "$VERSION_ID" == "18.04" ] && [ "aarch64" == $ARCH ]; then
      #   echo -e "ARM architecture is supported on Ubuntu 20.04. For 18.04 installation, use the link below to install.\nhttps://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-can-i-install-the-ant-media-server-on-ubuntu-1804-with-arm64"
      #   exit 1
      # fi
```
They are around line 180.

Then, proceed to installation normally, then follow the wiki to build glibc~

**Comment by mekya** [comment]
Thank you @GrandArth for asking, resolving and closing the issue.

You may encounter some more dependency issues like glibc-. I hope you will not. 

 If there is a chance to update your OS, it will be better.

Cheers
