### ISSUE TITLE
Memory not getting freed for RTMP publishing 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5402]
### Short description
When RTMP streams are sent to Ant Media Server and later stopped,   that the RAM usage does not decrease accordingly

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.6.2
* Browser name and version:

### Steps to reproduce
1. start sending RTMP load to Ant Media Server.
2. stop all the streams.
3. Monitor Ram usage on The Dashboard Panel
4. the Ram usage will not decrease  

### Expected behavior
Ram usage should decrease if we remove all the RTMP load

### Actual behavior
Ram usage is not decreasing  

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by Mohit-3196** [comment]
5388

**Comment by Mohit-3196** [comment]
#5388

**Comment by lastpeony** [comment]
Ram usage sometimes increases due to memory management of the OS/JVM
The JVM crasher memory leak problem fixed on mentioned commit of mekya.
