### ISSUE TITLE
Kick user from playing and publishing streams

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5415]
- Kick user publishing and playing specific to subscriber id or stream id.
- Support time period to block the user
- Pay attention that it should support cluster environment

I think there is a PR related to this or similar feature. 

If user is publishing and/or playing, it will be kicked out when the method is called.

**Comment by lastpeony** [comment]
jwt blacklist can be used for similar behaviour.

**Comment by yashtandon113** [comment]
@lastpeony @burak-58 @mekya 
I have test the subscriber block/allow feature in both standalone and cluster environments and it worked fine as expected.
