### ISSUE TITLE
When joining a room, mic/cameraaccess is required for Android 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5418]
When I join a room, as audience, then we don’t need Mic/Camera access, unless user is trying to publish the stream, but sample app is using these, which is not intended and might be a problem.

**Comment by burak-58** [comment]
If conference is initiated as `playOnlyMode=true`, then camera and microphone is not used.

**Comment by burak-58** [comment]
It is re-implemented on #5416 refactor. Now mic/camera are turned on when you start publishing.
