### ISSUE TITLE
Unable to delete stream

### ISSUE THREAD

**Issue by dmillerhotwire** [ant-media/Ant-Media-Server#5423]
### Short description
I deleted a stream JyGW4xdqMd22FyRy1688127537654, showed me confirmation to Delete it which I pressed OK on.  I navigate away, go to Dashboard, and then return to Live App and it still shows that it’s there Broadcasting. I did it 4x and won’t delete.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1.  I deleted a stream JyGW4xdqMd22FyRy1688127537654, 

2.  showed me confirmation to Delete it which I pressed OK on.  I

3. navigate away, go to Dashboard, and then return to Live App and it still shows that it’s there Broadcasting. 

I did it 4x and won’t delete.

### Expected behavior
__It should delete the stream from console__

### Actual behavior
__Acts like it deleted but does not delete.__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant 

https://github.com/ant-media/Ant-Media-Server/assets/137323849/0e3cbc45-3ce6-44f7-9cf2-2b31470375b4

Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
hi @dmillerhotwire,

Thank you for the issue. If the streamer tries to reconnect and there is no stream security, it will be broadcasting again. 

If this is your case, you may need to use some stream security especially(one time token or time based token) to prevent user to send stream again or force the user to stop publishing.

Please let me know if it helps and I can help you further

Cheers

**Comment by Mohit-3196** [comment]
The same issue was also discussed on the support side and it's about the encoder reconnection only.

FYI please.

**Comment by mekya** [comment]
Thank you @Mohit-3196 for the information. 

So I'm closing the issue. Please feel free to re-open if you think there is a problem @Mohit-3196 @dmillerhotwire 

Cheers
