### ISSUE TITLE
Missing .destroy method in Javascript SDK

### ISSUE THREAD

**Issue by dnish** [ant-media/Ant-Media-Server#5429]
Hey guys,
we currently implementing your Javascript API into our project. We recognized some issues during the initialization. If a visitor switches to another pages and the WebRTCAdaptor "initialize" event hasn't fired yet, the camera will be still active and the object also sends some "pong" messages to the server. We call the useEffect hooks like this:

```
useEffect(() => {
    return () => {
            obj.current.closeWebSocket();
            obj.current.closeStream();
     }; // Unmount
},[]);
```

So the object doesn't get destroyed. Also if a user denies access to his camera, the SDK starts an infinite loop requesting access to the camera. This will not work because some browsers don't show the request dialog again until the user has completely reloaded the page.

**Comment by mekya** [comment]
hi @dnish,
Thank you for raising this issue.

Just to be on the same page and let us do the correct implementation, what exactly do you expect? 

- If we implement `destroy` method like below works for you? 

```js
function destroy() {
   closeWebSocket();
   closeStream();
} 
```
- I've just tested something yesterday about access to the camera that user denies and it was working for me. I don't understand exactly what you mean. Could you please use the [bug template or feature template](https://github.com/ant-media/Ant-Media-Server/issues/new/choose) to explain your issue? In this way, we spend less time for understanding each other. 

Thank you
Cheers

**Comment by lastpeony** [comment]
This is a timing issue.  Here is a quick and dirty workaround fix:
Go to webrtc_adaptor.js closeWebsocket() function
Add this line to beginning of the function:
        `this.closeRequestReceived = true;`
![image](https://github.com/ant-media/Ant-Media-Server/assets/24750845/f6c16509-2367-4fad-b49b-4d3dcb4b593d)
Go to websocket_adaptor.js initWebSocketConnection() function
Add this line to beginning of the function:
 ```
  if(this.webrtcadaptor.closeRequestReceived){
            console.log("WebRTC adaptor is closed. Please recreate webrtc adaptor object.")
            return
        }
```
![image](https://github.com/ant-media/Ant-Media-Server/assets/24750845/b0e43582-a03b-49f2-b65b-7196cd07ceb4)

This way websocket connection timing issue will be solved.

Camera timing issue is a little bit more complex. As a workaround you can do the following:
Go to media_manager.js closeStream() function

Add
setTimeout(()=>this.closeStream(),100)
![image](https://github.com/ant-media/Ant-Media-Server/assets/24750845/d6cc6218-9b7f-4867-883f-c7a790a47b6b)

When you call adaptor.closeStream() after 500 ms inside setTimeout it is called before localStream is created. After localStream gets created and users view is rendered on screen. adaptor.closeStream() should be called after localStream object is created

You can also create an interval after adaptor.closeStream() is called and check whether localStream is null or not. If it is not null you would call closeStream() again and clear the interval.

**Comment by lastpeony** [comment]
Closed due to inactivity

**Comment by mekya** [comment]
Thank you @lastpeony for the solution. 

@dnish, please feel free to re-open the issue if it does not work for you.
