### ISSUE TITLE
Prepare RTSP Server demonstration

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5432]

**Comment by USAMAWIZARD** [comment]
Current status

**Comment by USAMAWIZARD** [comment]
Issues worked on last week

RTSP stream ends randomly.

investigated issue regarding stream not working when using mp4 file (found out that it is not having sps and pps value before every IDR NAL it woks with h264 file but not with (mp4 for flv ) container files when it does not repeat sps and pps )

worked on implementing a annexd-b ffmpeg to support containerized files.

**Comment by mekya** [comment]
New issue has been created for audio support 
https://github.com/ant-media/Ant-Media-Server/issues/5460
