### ISSUE TITLE
Re-connection does not works some time in Android SDK 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5434]
### Short description
when publishing from Android SDK. Re-connection is not working. 

### Environment

* Operating system and version: Ubuntu 22
* Java version: 
* Ant Media Server version: Enterprise Edition 2.6.1 
* Browser name and version:

### Steps to reproduce
1. Publish Video
2. turn off internet 
3. turn on internet 

https://github.com/ant-media/Ant-Media-Server/assets/47350008/d4cd6192-a74f-47ec-be16-498d3e87a253

### Expected behavior
Should reconnect

### Actual behavior

not reconnecting

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by burak-58** [comment]
Hi @USAMAWIZARD,
With this https://github.com/ant-media/WebRTC-Android-SDK/pull/34 we have changed the reconnection mechanism. I have tried with the latest master and reconnection worked for me with the provided scenario. Could you please verify that?

**Comment by USAMAWIZARD** [comment]
Thanks I have tested it and its working fine now. But the small problem is even tho its reconnected it gives logs as disconnected and reconnecting and other logs

https://github.com/ant-media/Ant-Media-Server/assets/47350008/be039ffa-cf1b-4f89-be1e-d93a322e9495
