### ISSUE TITLE
One Time Token Is Consumed Even If Stream Is Not Publishing

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#5440]
The one-time token is consumed when a user attempts to play a stream that is not currently being published. As a result, once the stream is publishing, users are unable to use the token.

* Ant Media Server version: 2.6.3

### Steps to reproduce
1.Create a livestream. Create a one time token. Dont start publishing.
2. Try to watch the livestream with one time token -> wont work since stream is not publishing.
3. Start publishing
4. Try to watch the live stream with one time token ->wont work because one time token is consumed and marked invalid  by the server. at step 2

### Expected behavior
One time token should not be consumed if stream is not publishing(webrtc).

### Actual behavior
One time token is marked as invalid even if stream is not publishing.

**Comment by mekya** [comment]
Thank you for the issue @lastpeony

I've put this to the backlog. Let me know if it's a blocker for any user.

**Comment by lastpeony** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/606

**Comment by mekya** [comment]
Hi @lastpeony, 

Thank you for the fix. I've analyzed the PR and it made me think that it may cause a security vulnerability. A hacker can get one-time tokens for the non-broadcasting stream and distribute them before the stream starts.

So I want to think again about this PR later.

Please let me know if a user is waiting for this feature or if this request is coming from a user.

Regards

**Comment by lastpeony** [comment]
After a thorough review by @mekya, we've merged this into the master branch. Issue resolved and closed!
