### ISSUE TITLE
how to you find out that the user has slow bandwidth connection

### ISSUE THREAD

**Issue by akashvinfinite** [ant-media/Ant-Media-Server#5441]
how to you find out that the user has slow bandwidth connection, because we get only below in the response:-

{videoBitrate: 210453, streamId: "AV8-JuneSim6", targetBitrate: 1951000, audioBitrate : 210453}

**Comment by akashvinfinite** [comment]
any update on this request?

**Comment by mekya** [comment]
Hi @akashvinfinite,

Let me explain to you. If the `videoBitrate` + `audioBitrate` is more than the `targetBitrate`, it means user has slow bandwidth. 

Secondly, `targetBitrate` is just an estimation so recently we've changed the algorithm. We measure RTT, packetlost ratio,  jitter to understand if the network is slow. 

If you're creating a project, may I learn what you would like to achieve and how many broadcasts and viewers will be in your system?

**Comment by shashnakjha09** [comment]
@mekya  How can We get RTT, packetlost ratio, jitter  from antmedia . 
for now we are getting only   {videoBitrate: 210453, streamId: "AV8-JuneSim6", targetBitrate: 1951000, audioBitrate : 210453}

Thnaks

**Comment by akashvinfinite** [comment]
any update on this request?

**Comment by akashvinfinite** [comment]
please update, things are getting escalated now...

**Comment by shashnakjha09** [comment]
Hi @yashtandon113 
I have gone through the player.html, and i can see that in  line number 314 you are using a callback function
callback : function(info, obj){}
in this obj argument you are getting all these below information.
 //obj is the PeerStats which has fields
//averageIncomingBitrate - kbits/sec
//currentIncomingBitrate - kbits/sec
//packetsLost - total number of packet lost
//fractionLost 
//streamHeight
//streamWidth

but here in our case we are not getting all above information.
please check and let us know.

thanks

**Comment by yashtandon113** [comment]
@shashnakjha09 
Can you please let us know how are you implementing this on your side and which function/method are you calling to get this data on your end?

**Comment by shashnakjha09** [comment]
Hi, So we are trying to get All these details but we are not able to as mention previously we went through the code provided by You and show that.
var webRTCAdaptor = new WebRTCAdaptor({
		websocket_url : websocketURL,
		mediaConstraints : mediaConstraints,
		peerconnection_config : pc_config,
		sdp_constraints : sdpConstraints,
		remoteVideoId : "remoteVideo",
		isPlayMode : true,
		debug : true,
		candidateTypes: ["tcp", "udp"],
		callback : function(info, obj) {
			if (info == "initialized") {}

 This is the code of webRTCadaptor.

else if (info == "updated_stats") {
				//obj is the PeerStats which has fields
				 //averageIncomingBitrate - kbits/sec
				//currentIncomingBitrate - kbits/sec
				//packetsLost - total number of packet lost
				//fractionLost - fraction of packet lost

				$("#average_bit_rate").text(obj.averageIncomingBitrate);
				if (obj.averageIncomingBitrate > 0)  {
					$("#average_bit_rate_container").show();
				}
				else {
					$("#average_bit_rate_container").hide();
				}
				$("#latest_bit_rate").text(obj.currentIncomingBitrate);
				if (obj.currentIncomingBitrate > 0) {
					$("#latest_bit_rate_container").show();
				}
				else {
					$("#latest_bit_rate_container").hide();
				}

				var packetLost = parseInt(obj.videoPacketsLost) + parseInt(obj.audioPacketsLost);
				$("#packet_lost_text").text(packetLost);
				if (packetLost > -1) {
					$("#packet_lost_container").show();
				}
				else {
					$("#packet_lost_container").hide();
				}




1. we are not getting info == "updated_stats" and not sure when updated_stats state come , we are only getting bitratemeserment inside info object. as we are not getting info == "updated_stats"  because of that we are not able to calculate all the values
2. please let me know is all these info coming from server or getting calculated on client side.

Thanks

**Comment by mustafaboleken** [comment]
Hi @shashnakjha09,

Getting stats is disabled by default and to be able to receive updated_stats, you have to call [enableStats](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js#L1528) method on WebRTCAdaptor object.

These statistics come from [WebRTC's Statistics Api](https://www.w3.org/TR/webrtc-stats/) and for a better understand of how we get those values, you can check [this link](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/js/webrtc_adaptor.js#L1360).

**Comment by shashnakjha09** [comment]
@mustafaboleken thanks, we will check this

**Comment by yashtandon113** [comment]
@shashnakjha09 
Have you checked the solution/suggestions provided by @mustafaboleken?

**Comment by shashnakjha09** [comment]
Yes, we are working on it.
Thanks

**Comment by yashtandon113** [comment]
@shashnakjha09 
I am closing this issue for the inactivity. Please feel free to reopen it if you have any questions.
