### ISSUE TITLE
different types of error responses possible in case of any failure in the live stream

### ISSUE THREAD

**Issue by akashvinfinite** [ant-media/Ant-Media-Server#5442]
what all error responses are possible in case of any failure in the live stream, as of now we are aware of  only one: -

{"streamId":"AV7-JuneSim5","error_code":"404","definition":"no_stream_exist","command":"error"}

**Comment by akashvinfinite** [comment]
any update on this request?

**Comment by mekya** [comment]
Hi @akashvinfinite

This says that there is not active live stream in the server with the id "AV7-JuneSim5". In order to play a stream, make sure that you're sending that stream to the AMS exactly with the same stream id. 

If the response above does not help you, please let us know more about what you would like to achieve.

Cheers

**Comment by akashvinfinite** [comment]
no no, i'm not asking specifically for that error, i want to know all other error codes or messages you have in your system which we need to handle at our end.

**Comment by akashvinfinite** [comment]
any update on this request?

**Comment by akashvinfinite** [comment]
please reply

**Comment by akashvinfinite** [comment]
please update, things are getting escalated now...

**Comment by yashtandon113** [comment]
@akashvinfinite 
As discussed in a meeting, you can check the different WebSocket Callback errors on a below document link.
https://antmedia.io/docs/guides/publish-live-stream/webrtc/webrtc-websocket-messaging-reference/#websocket-error-callbacks

**Comment by yashtandon113** [comment]
@akashvinfinite 
Please let us know if you have any further questions.

**Comment by shashnakjha09** [comment]
@yashtandon113 Thanks for the clarity, we will check this.

**Comment by yashtandon113** [comment]
@shashnakjha09 
I am closing this issue now. If you have any questions, please feel free to reopen it.
