### ISSUE TITLE
Multiple streams are not publishing using Embedded SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5458]
### Short description
Using [WebRTC Embedded SDK](https://github.com/ant-media/WebRTCEmbeddedSDKReference), the single stream is publishing fine using p2p mode or publishing mode but multiple streams are not getting published at a time.

### Steps to reproduce
1. Clone https://github.com/ant-media/WebRTCEmbeddedSDKReference
2. Edit the main.cpp file as required for multiple streams
3. Build the SDK again as per ARM or x86 architecture
4. Try to run the webrtc_pull_rtsp script

### Expected behavior
Multiple streams should start publishing on the server

### Actual behavior
Only one stream is getting published on the server at a time

**Comment by mekya** [comment]
@yashtandon113 is going to add some insructions

**Comment by yashtandon113** [comment]
According to our investigation, supporting multiple streams in a single webrtc_rtsp_pull executable is not more profitable than running numerous instances of the same executable.

Here is an attached simplified main.cpp that can publish RTSP to a server using WebRTC. You can run it multiple times, like:

```
#include "sdkapi.h"
#include "stdio.h"
//
int main(int argc, char* argv[]) {
    init();
    if(argc > 1) {
        printf("argv 0:%s\n", argv[0]);
        printf("argv 1:%s\n", argv[1]);
        printf("argv 2:%s\n", argv[2]);
        printf("argv 3:%s\n", argv[3]);

        setMode(1);

        start(argv[1], argv[2], argv[3]);
    }
    return 0;
}
```

```
./webrtc_pull_rtsp "ws://127.0.0.1:5080/WebRTCAppEE/websocket" "rtsp://127.0.0.1:6554/test.flv" "stream1" &
./webrtc_pull_rtsp "ws://127.0.0.1:5080/WebRTCAppEE/websocket" "rtsp://127.0.0.1:6554/test.flv" "stream2" &
```

After replacing the main.cpp file on your end, build the webrtc_pull executable file again using the docker command as per your architecture mentioned on below repository.
https://github.com/ant-media/WebRTCEmbeddedSDKReference
