### ISSUE TITLE
Cannot stop SRT stream using API

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5459]
### Short description
If I start a SRT stream using FFMPEG command:

ffmpeg -re -i news.mp4 -vcodec libx264 -profile:v baseline -g 60 -acodec aac -f mpegts "srt://ant-media-server:4200?streamid=LiveApp/{streamid}"

I cannot stop the stream using API request:

`POST https://ant-media-server:5443/LiveApp/rest/v2/broadcasts/{streamid}/stop`

The API respond is:

```
{
    "success": false,
    "message": null,
    "dataId": null,
    "errorId": 0
}
```

### Environment

* Operating system and version: Ubuntu 22.04
* Java version: 
* Ant Media Server version: 2.6.2
* Browser name and version: N/A

### Steps to reproduce
1.  Start a SRT stream using the FFMPEG command from the docs https://antmedia.io/docs/guides/publish-live-stream/srt/#pushing-srt-stream-with-ffmpeg
2. try to stop the live stream using the API request https://antmedia.io/rest/#/BroadcastRestService/stopStreamingV2

### Expected behavior
The stream should stop

### Actual behavior
The stream does not stop. Its necessary to cancel the FFMPEG terminal process. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
This functionality was missing for publish type SRT streams.
Added on mentioned PR
