### ISSUE TITLE
Support Audio in RTSP output plugin

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5460]

**Comment by USAMAWIZARD** [comment]
I have added the audio support for RTSP , Currently audio is working fine , I have added AAC codec for now and  H264 video, I will have to add some more codec support for Audio and Video as well.

I will work on adding more codec support as well as handling few conditions if the audio or Video is not present in the stream

**Comment by USAMAWIZARD** [comment]
Audio done
Codec Support 
Tested and working
SRT  to RTSP  OUT
RTMP to RTSP  OUT 
WebRTC RTSP  OUT
RTSP to RTSP  OUT

**Comment by USAMAWIZARD** [comment]
Added codec support
opus 
h264 
aac
vp8
h265 
tested and working
srt      ---- > rtsp out
rtmp  -----> rtsp out
webrtc----> rtsp out
rtsp     -----> rtsp out

**Comment by yashtandon113** [comment]
I have tested the plugin and audio is working fine.
