### ISSUE TITLE
Laggy stream playback on mobile devices with Adaptive streaming enabled

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5464]
### Short description

Cannot be reproduced on our side, but customer is facing this issue. 

**The issue:**
The live stream and also the recorded hls stream are lagging very badly on a lot of different Android and iPhone devices and on PC. Mac no issue.

Also tried on the phones with Chrome, Firefox, Safari, all have the same result.

**What we tried:**
We tried several scenarios:
RTMP, SRT, WebRTC streaming from Mac and Windows, WebRTC stream and playback with the Ant Media WebRTC tool.
Every scenario resulted with the same laggy streams on most of the phones we tried.

**Adaptive Bitrates:**
1080p 6000 Kbps video bitrate, 128 Kbps audio bitrate
720p 3000 Kbps video bitrate, 128 Kbps audio bitrate

**Devices where the lag always happening:**
Iphone 8
Xiaomi Mi 8
Xiaomi Redmi Note 9 Pro
Xiaomi Mi A2
Samsung Galaxy A52s 5G
OnePlus Nord 5G

**Exceptions:**
iPhone 12 mini
Honor x7a
Samsung Galaxy A21s
Galaxy Tab S

**recorded hls streams for testing:**
WebRTC stream:
https://ant-storage-prd.s3.eu-central-1.amazonaws.com/streams/b6Er8EmErKvD4IAZ1690540806226_adaptive.m3u8
SRT stream:
https://ant-storage-prd.s3.eu-central-1.amazonaws.com/streams/b0OH6opged7sIHnU1690535982614_adaptive.m3u8
https://ant-storage-prd.s3.eu-central-1.amazonaws.com/streams/vUMeTJRwX0TOE9B91690537732757_adaptive.m3u8
RTMP stream:
https://ant-storage-prd.s3.eu-central-1.amazonaws.com/streams/VhfQHcBpHVUsFPQ51690536603767_adaptive.m3u8
https://ant-storage-prd.s3.eu-central-1.amazonaws.com/streams/ejJLD0lF6hofAKgt1690538182940_adaptive.m3u8

### Environment

* Operating system and version: AWS g5.xlarge instance
* Java version: 
* Ant Media Server version: 2.6.2 
* Browser name and version: All mobile browsers and PC

### Steps to reproduce
1. Create the two ABR setting in AMS application
2. Start [this](https://www.youtube.com/watch?v=VukLV0AoeFA) Youtube video on fullscreen
3. Set OBS output as follows - Bitrate: 6000 kbps, Rate control: CBR, Keyframes: 1s, CPU usage: medium, profile: baseline
4. Now live stream the video in OBS as a screen capture
5. Playback the live stream in a mobile browser (HLS or WebRTC)

### Expected behavior
Smooth playback experience

### Actual behavior
Choppy, glitchy playback. Not smooth

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
The application the customer was testing with was found to have encoderPreset set to slower. By changing the preset in the application and in OBS, I could reproduce quality impact and also acheive much better results. 

The optimum setting I've found for the use case is by setting the application encoderPreset to fast and OBS CPU preset to veryfast, I get a decent quality video playback in both WebRTC and HLS. 

Customer is using g5.xlarge and two ABR 1080p at 6000 kbps and 720p at 3000 kbps. Are there any further optimisations that could be done to further improve the quality so no lagging or glitching of playback is experienced.

**Comment by mekya** [comment]
It seems that bitrates are high 6Mbps and 3Mbps for real time communication. If the network QoS is not good(it can only guaranteed in specific networks and it cannot be guaranteed in public internet),  you can reduce the bitrate to a value that does not make differ in the quality for the user.

I've a similar story, user sets adaptive bitrate to 4Mbps for 720p and we show the video with 2.5Mbps for 720p for him, it was also ok for him.  I mean he decreased the bitrate to 2.5 from 4mbps and he's happier in quality, latency and no lagging.

**Comment by timantmedia** [comment]
The customer had the Ant Media Server application encoder speed setting set to "slow" which caused the issue. Once changed to a faster encoder speed, the issue was resolved.
