### ISSUE TITLE
HLS stream is not playing smooth and DVR is not working efficiently

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5465]
### Environment

* Ant Media Server version: 2.6.2

### Steps to reproduce
1. Open an instance g4dn.2xlarge
2. Add adaptive bitrate 4mpbs -> 1080p, 2.7Mbps -> 720p, 1.5Mbps -> 540p 
3. Input is 6Mbps 1080p

### Expected behavior
All Streams play smoothly and playable/seekable with hls.js hlsjs.video-dev.org

### Actual behavior
5-6 streams are ok however 1-2 streams have problem in playback, it's not smooth and it's not seekable in hls.js
 

an example of a broken HLS: https://drive.google.com/file/d/1BXnV9KEKXHEnxzg8OOks5ZSvI2XmXDUP/view?usp=sharing
https://drive.google.com/file/d/1BXnV9KEKXHEnxzg8OOks5ZSvI2XmXDUP/view?usp=sharing

the corresponding ant-media-server.log file: https://49ing.wetransfer.com/downloads/28528023c8ad94a4972194a81da1095320230812142842/3a13f9f48f30fa9e734f5d6e1358330b20230812142900/f1b170
please note that we produce 8 streams in parallel
the broken stream has the name "behindgoal1"

**Comment by yashtandon113** [comment]
**Update:** Fresh installation of the server resolved the issue as confirmed by customer but issue is reproduced again when the server is launched using AWS marketplace GPU image so I will do further investigation.

**Comment by yashtandon113** [comment]
Issue is still under investigation.

**Comment by mekya** [comment]
We've find out that some audio packets are not written to HLS or MP4. After further investigation, it turns out that incoming RTMP packets are not in correct order. In other words, they are not monotonically increasing.  Check the image below. Highlighted section are in correct order and it happens in all cases. 

<img width="1343" alt="Screenshot 2023-09-21 at 16 07 07" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/e584a7f2-5af1-4eab-a70e-5459a5692ab9">

As far as I know, encoder is SimplyLive  and this causes the problem. We're sending a fix for this case to reorder incoming packets when `rtmpIngestBufferTimeMs` is bigger than zero in AppSettings. We'll test it again and see if it works

**Comment by yashtandon113** [comment]
Things appear to be resolved now that we provided the user with the most recent build following the fix.

The user is currently testing it and will provide a final update as soon as possible.
