### ISSUE TITLE
webrtc_adapter 2.6.2 - window.log is undefined

### ISSUE THREAD

**Issue by HadiAghandeh** [ant-media/Ant-Media-Server#5469]
### Short description
webrtc_adapter 2.6.2 recently changed its logging object from console.log to window.log which is supposed to be a custom logging object. However, window.log is not defined in any browsers and they always face an error. 

### Environment
* Browser name and version:
Chrome - Linux

### Steps to reproduce
1. install webrtc_adapter 2.6.2 
2. Try to publish

### Expected behavior
It must start publishing

### Actual behavior
It fires an error in the browser
![image](https://github.com/ant-media/Ant-Media-Server/assets/28506997/b702c55d-ad90-4973-9457-8c2a1443b83b)

**Comment by USAMAWIZARD** [comment]
Can you please try this  
npm i @antmedia/webrtc_adaptor@2.6.3-SNAPSHOT-2023-Jul-27-07-23

**Comment by timantmedia** [comment]
@HadiAghandeh please try using the latest snapshot version of webrtc adaptor with the latest version of Ant Media Server (2.6.2) and let us know if you are still experiencing any issues.

**Comment by webmasterh** [comment]
> npm i @antmedia/webrtc_adaptor@2.6.3-SNAPSHOT-2023-Jul-27-07-23

This fixed the issue.

**Comment by HadiAghandeh** [comment]
> npm i @antmedia/webrtc_adaptor@2.6.3-SNAPSHOT-2023-Jul-27-07-23

I tested this version, it fixed the issue.

**Comment by mekya** [comment]
Thank you for the update. Then I'm closing this issue.

Please feel free to open an issue if you encounter the similar things

Cheers
