### ISSUE TITLE
How to auto scale in GCP

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#5484]

**Comment by timantmedia** [comment]
@muratugureminoglu I'll put this in the queue and review it.

**Comment by timantmedia** [comment]
I couldn't test on GCP because my account requires a billing account. I will not be back until Sept 6, maybe someone else should test this.

**Comment by yashtandon113** [comment]
I have deployed and tested the cluster on GCP. It is working fine.
The blog is ready to publish https://antmedia.io/?p=84461&preview=true
