### ISSUE TITLE
Mobile devices stuck in preparing state or experiencing timeout errors

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5487]
### Short description

The customer is attempting to use AMS 2.6.2 to record video and audio streams of our users, but we have encountered an issue where some streams get stuck in the preparing state and are not fully published.

Firstly We noticed that the behavior differs depending on the version of webrtc_adapter we use, so we decided to use the latest version (2.6.2) from npm to ensure that everything is up to date. This version appears to have a bug in its logging system where the logging object has been changed to `window.log` instead of `console.log`, which is not defined on browsers. Therefore it always face an error. 

We reported the issue here: 
https://github.com/ant-media/Ant-Media-Server/issues/5469

Using 2.6.1 webrtc adaptor we noticed on some devices it can not establish a successful stream. Increasing the timeout also didn't fix the problem and streams get stuck in preparing state on mobile devices.

The issue is reproduced on their side using the sample page and noticed on the mobile devices the stream can not be established successfully. Either they face a timeout error or stuck in preparing state.

Devices the customer tested that faced a timeout error:

- Ipad Air 5th Gen. Simulation
- Ipad IOS 16.4 10th Gen. Simulation
- Galaxy s21 FE Android-13, Chrome -115.0.5790.166

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.6.2
* Browser name and version: iOS Safari and Android Chrome

### Steps to reproduce
1. Start publishing using one of the devices listed above
2. Web panel shows stream stuck in preparing state
3. Publish page shows timeout error.

### Expected behavior
Should be able to publish successfully. 

### Actual behavior
Cannot publish a live stream. 

 FD 102708

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
I've tried reproducing the issue using the following:

1. ​Open the sample publish page in iPad Air 5th Generation simulator
2. Open the sample player.html page in iPad 16.4 10th Generation simulator
3. Start publishing on iPad Air 5th Generation simulator
4. Start playing back on iPad 10th Generation simulator

I did observe some delays playing back the video, but publishing experienced no issues.

**Comment by mekya** [comment]
Hi @timantmedia ,

One user report the same problem(window.log) and then he confirms that it's working with the later version of the JS SDK. Here is the issue that this discussion appears. 
https://github.com/ant-media/Ant-Media-Server/issues/5469

I'm closing this issue that due to duplication and it's already resolved. Please feel free to open if you encounter the problem again. 

Regards
Oz
