### ISSUE TITLE
RTMP Pull not working

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5500]
### Short description
There have been previous reports of this, but I discovered that in version 2.6.1+ RTMP pull is not working. I tested a RTMP stream in version 2.5.3 which broadcast successfully, when used in version 2.6.1+ I see the following error:

`2023-08-24 20:39:44,114 [Thread-34154] ERROR i.a.streamsource.StreamFetcher - cannot open stream: {rtmp stream url} with error:: Cannot assign requested address`

### Environment

* Operating system and version: Ubuntu 20.04+
* Java version: 
* Ant Media Server version: 2.6.1+
* Browser name and version:

### Steps to reproduce
1. Create a new stream source
2. Add the RTMP play URL
3. Observe the logs

### Expected behavior
The RTMP stream should play

### Actual behavior
The stream remains offline and the error is observed.

 Although RTMP play is not supported, I think its relevant to note, that even when enabled, this also does not work. 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
RTMP is working, there was an issue on the RTMP stream side.

**Comment by timantmedia** [comment]
Please can we schedule this on Monday for a priority customer. They need this feature and just upgraded..

**Comment by USAMAWIZARD** [comment]
@timantmedia  can you please share me the RTMP pull url

**Comment by timantmedia** [comment]
> @timantmedia  can you please share me the RTMP pull url 
> 

@USAMAWIZARD  You can configure a rtmp play url on one ant media server and try to play it back in multiple versions to reproduce the issue.

**Comment by lastpeony** [comment]
Fix:
https://github.com/ant-media/Ant-Media-Server/pull/5531

**Comment by algirdas-iterato** [comment]
When it is planned to release this fix?

**Comment by mekya** [comment]
Hi @algirdas-iterato 

It's already in snapshots for community and enterprise editions so that you can try it on your end. 

We plan to have a release in 2 weeks for 2.7.0 if there is no unexpected thing happen

Regards
