### ISSUE TITLE
Problem with ssl certificate

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/Ant-Media-Server#5506]
Hello, there is a problem with the ssl certificate on the admin side.
The server is running through nginx and the certificate works well. broadcast in the format
mysite.com/app/stream/stream-id.m3u8 works well, but if the format is 
mysite.com:5443/app/stream/stream-id.m3u8 the "certificate is not valid" error also shows this error on the login panel.

**Comment by muratugureminoglu** [comment]
Hi @studentAlanMorgan 

This error is due to a mismatch between the certificate or domain used in Nginx and Ant Media Server. Could you please check the domain and certificate on both the Nginx and Ant Media Server sides? If you can share the domain name, I can check it for you.

**Comment by studentAlanMorgan** [comment]
> 

hello, what exactly do you need?
panel data? from the server?

**Comment by studentAlanMorgan** [comment]
> Hi @muratugureminoglu 
hello, what exactly do you need?
panel data? from the server?

**Comment by muratugureminoglu** [comment]
@studentAlanMorgan 

Just domain name.

**Comment by studentAlanMorgan** [comment]
> Just domain name.

@muratugureminoglu 
keeneye.stream
only what is the point of one domain :/

**Comment by muratugureminoglu** [comment]
Hi @studentAlanMorgan 

As you can see in the screenshots, the certificate on keeneye.stream:5443 has expired, but it hasn't expired on the Nginx side. Therefore, you need to renew the certificate.

You can renew it as follows:
```
cd /usr/local/antmedia/
sudo ./enable_ssl.sh -d keeneye.stream
```
![Screenshot at 2023-08-29 09-53-05](https://github.com/ant-media/Ant-Media-Server/assets/6337605/718af75c-584d-4b39-9b99-3e9827908734)
![Screenshot at 2023-08-29 09-53-27](https://github.com/ant-media/Ant-Media-Server/assets/6337605/d8488154-1fbc-4b20-a124-a78bff7956bc)

**Comment by studentAlanMorgan** [comment]
@muratugureminoglu 
sudo ./enable_ssl.sh -d keeneye.stream
domain: keeneye.stream
creating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
archive directory exists for keeneye.stream-0002
There is a problem in installing SSL to Ant Media Server.
 Please take a look at the logs above and try to fix.
 If you do not have any idea, contact@antmedia.io

**Comment by studentAlanMorgan** [comment]
> sudo ./enable_ssl.sh -f /etc/letsencrypt/live/keeneye.stream/fullchain.pem -p /etc/letsencrypt/live/keeneye.stream/privkey.pem -c /etc/letsencrypt/live/keeneye.stream/fullchain.pem -d keeneye.stream
@muratugureminoglu 
Thank you! it worked.

**Comment by muratugureminoglu** [comment]
I m closing the issue, feel free to open it.

**Comment by studentAlanMorgan** [comment]
@muratugureminoglu 
When updating the certificate, an error occurred again: sudo ./enable_ssl.sh -d keeneye.stream
domain: keeneye.stream
creating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for keeneye.stream
Waiting for verification...
Cleaning up challenges
archive directory exists for keeneye.stream-0003
There is a problem in installing SSL to Ant Media Server.
  Please take a look at the logs above and try to fix.
  If you do not have any idea, contact@antmedia.io

command: sudo ./enable_ssl.sh -f /etc/letsencrypt/live/keeneye.stream/fullchain.pem -p /etc/letsencrypt/live/keeneye.stream/privkey.pem -c /etc/letsencrypt/live/keeneye .stream/fullchain.pem -d keeneye.stream does not solve the problem this time

**Comment by studentAlanMorgan** [comment]
log: 2023-11-20 04:31:18,601:DEBUG:acme.client:Storing nonce: SFMYLIQjU0ah-hF1zdqw97wLt_GM7CjnbA7zwlFumyt4pRllN7U
2023-11-20 04:31:18,603:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1382, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1265, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 431, in obtain_and_enroll_certificate
    return storage.RenewableCert.new_lineage(
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 1003, in new_lineage
    raise errors.CertStorageError(
certbot.errors.CertStorageError: archive directory exists for keeneye.stream-0003

**Comment by studentAlanMorgan** [comment]
Problem solved. replacing the folder.
