### ISSUE TITLE
Missing master extension in the vod_transcode.sh script

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5507]
master extension .m3u8 is missing for the vod_transcode.sh script and therefore the generated files with the .m3u extension do not play.

**Comment by Mohit-3196** [comment]
created a new PR https://github.com/ant-media/Scripts/pull/259

**Comment by Mohit-3196** [comment]
Hi @oguzhangokboru ,
I have changed the extension to .m3u8 from .m3u

Also, we discussed these on the support ticket side previously with you and with this minor change, the generated files were playing fine.

So if it's OK, I will close this issue now.

Please let me know if you have any comments.

Thank you

**Comment by mekya** [comment]
Closing this issue. Please feel free to re-open if it does not work for you
