### ISSUE TITLE
Vod hls transcoding for long videos isn’t working

### ISSUE THREAD

**Issue by oguzhangokboru** [ant-media/Ant-Media-Server#5513]
I'm using Ant Media Enterprise Edition. I have an issue with vod transcoding. I installed vod_transcode.sh into the server and set up everything. But transcoding for long videos isn’t working.

For example, if i upload a 1 minute video, the outputs are:
vod_id.mp4
vod_id.m3u8
vod_id_360p
vod_id_360p.m3u8
vod_id_480p
vod_id_480p.m3u8
vod_id_720p
vod_id_720p.m3u8

Everything works fine as you can see.
But if i upload a 30min, one hour or two hours long video, the outputs are:
vod_id.mp4
vod_id_360p
vod_id_480p
vod_id_720p

Here, no m3u8 files are being generated. I tried so so many times but it's not working. Please help me get this issue fixed ASAP. 
Also Ant Media Dashboard doesn’t allow uploading video more than one. How to upload video files in bulk and make ./vod_transcode.sh transcode all the the files automatically?

Kind regards,

_Originally posted by @oguzhangokboru in https://github.com/ant-media/Ant-Media-Server/discussions/5512_

**Comment by Mohit-3196** [comment]
Hi,
If it's fine then, I'm closing this ticket now.
We will continue to optimize the script further here https://github.com/ant-media/Ant-Media-Server/issues/5508

Thank you.

**Comment by Mohit-3196** [comment]
Hello,
I'm closing this issue now @oguzhangokboru 

Thank you

**Comment by mekya** [comment]
Hi @ducquynhnguyeninfo 

I've responded [in this thread](https://github.com/ant-media/Ant-Media-Server/issues/5508). Let's proceed there.

BTW it's great to get connected with you on LinkedIn. If you think the same way, [here is my profile](https://www.linkedin.com/in/ahmetoguzmermerkaya/)

Cheers
Oguz
