### ISSUE TITLE
Confirm that ID3 Tags are added to all bitrates and No synch issue

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5519]
Check these comments
- https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/613#note_1536821919
- https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/613#note_1536821927

**Comment by burak-58** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/617

**Comment by mekya** [comment]
@burak-58 will also provide Ant Media Server PR
