### ISSUE TITLE
hls files not uploading to s3 bucket when setting setting large value for Segment List

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5529]
### Short description
HLS (ts m3u8) files are not uploading to s3 bucket when setting  large value for  Segment List 

### Environment

* Operating system and version: 
* Java version: 
* Ant Media Server version: 2.6.4
* Browser name and version:

Publishing protocol: WebRTC

### Steps to reproduce
Steps to reproduce
1. Go to Application Setting and enable H.264
2. Add few Adaptive Streaming like 360, 480 and 720
3. Check mark on Create HLS Streaming
4. Set Segment List Size to 5400 with 2 seconds of duration.
5. Enable S3 Upload.
6. Go Live

### Expected behavior
All the hls files being generated in WebApp folder should be uploaded to S3 for HLS playback later.

### Actual behavior
if “Delete HLS files after the stream is finished” is unchecked. No hls file gets uploaded on S3. If “Delete HLS files after the stream is finished” is checked then only last 5 to 6 hls files are being uploaded to S3.
 

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by USAMAWIZARD** [comment]
Thanks @mekya for  helping me with this.
This is what we discussed for this issue.

Its not recommended to have Segment List Size to have a such a big value. because server waits for that much amount of segments file to be created and after that it will start the upload please check [ this code here.](https://github.com/ant-media/Ant-Media-Server/blob/f8a9e0b0c059db660453315233395d03082213c7/src/main/java/io/antmedia/muxer/HLSMuxer.java#L270)

if you want your m3u8 file to contain all the TS file the recommended way is setting ` "hlsPlayListType": "event" `
in the application settings.

1. got to application settings.
2. Click on basic and change it to advance 
3. set hlsPlayListType value as event.
4. "hlsPlayListType": "event"

**Comment by USAMAWIZARD** [comment]
I will soon create a New PR on Docs to add these details there

**Comment by USAMAWIZARD** [comment]
https://github.com/ant-media/ant-media-documentation/pull/126

**Comment by USAMAWIZARD** [comment]
PR : https://github.com/ant-media/ant-media-documentation/pull/126

**Comment by Mohit-3196** [comment]
Mered after making some changes.
