### ISSUE TITLE
Ip camera RTMP endpoint not working

### ISSUE THREAD

**Issue by dhsont** [ant-media/Ant-Media-Server#5539]
### Short description
I added ip camera to ant media server, and i can see live stream in ant media server./applications/LiveApp

now i want to see this stream on youtube so i added youtube RTMP endpoints using Add RTMP Endpoint option in antmedia

rtmp://a.rtmp.youtube.com/live2/j857-j6xa-ss1e-youtube-key
But video is not streaming to youtube.

but if i create Playlist in antmedia and upload a video link and  Add RTMP Endpoint of youtube it is showing stream on youtube.

means rtmp streaming is working for playlist but not working for ip camera.

### Environment

* Operating system and version: Linux
* Ant Media Server version: Community Edition 2.5.2 20230105_1947
* Browser name and version: Chrome

### Steps to reproduce
1. add ip camera to antmedia server
2. add rtmp endpoint of youtube

**Comment by Mohit-3196** [comment]
We are following this on GitHub Discussion here https://github.com/orgs/ant-media/discussions/5546

FYI all

**Comment by Mohit-3196** [comment]
Hi @dhsont ,
I have been trying to reach you on the GitHub Discussions so please get back to me in your favourable time.

Also, closing this issue here in order to avoid duplication.

Thank you
