### ISSUE TITLE
Error building Docker image by just passing the license key as argument

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5553]
### Short description
If I follow the installation instructions of Ant Media Server using Docker and choose to just pass the license key, it fails to build the image.

This is the documentation page https://antmedia.io/docs/guides/clustering-and-scaling/docker/docker-and-docker-compose-installation/ and this is command to try and build the image:

`docker build --network=host -t antmediaserver --build-arg LicenseKey=<Your_License_Key> .`

This results in this error:

Reproduced:

<img width="1469" alt="Screenshot 2023-09-12 at 13 27 30" src="https://github.com/ant-media/Ant-Media-Server/assets/121940452/03e5fbd8-40b5-4753-a780-04cbeb781267">

Customer reported:

[antmediaerror.txt](https://github.com/ant-media/Ant-Media-Server/files/12586387/antmediaerror.txt)

### Environment

* Operating system and version: MacOS
* Java version: 
* Ant Media Server version: Latest version
* Browser name and version: n/a

### Steps to reproduce
1.  Run the docker build command to create an image by just passing the license key
2. Watch the terminal process and see it stop at an error
3.

### Expected behavior
The latest version of AMS should download and be used to create a docker image

### Actual behavior
Errors before the image is created. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by muratugureminoglu** [comment]
It's in PR https://github.com/ant-media/Scripts/pull/253

**Comment by timantmedia** [comment]
@muratugureminoglu I tried just manually updating my local Dockerfile with the changes in your PR (attached) and then when running the docker container I got this error:

<img width="1337" alt="Screenshot 2023-09-12 at 14 32 31" src="https://github.com/ant-media/Ant-Media-Server/assets/121940452/528ecf63-60d5-4a12-818a-3899db272f25">

My updated Dockerfile is attached. 

[Dockerfile.txt](https://github.com/ant-media/Ant-Media-Server/files/12586958/Dockerfile.txt)

**Comment by muratugureminoglu** [comment]
Ant Media Server hasn't been built. I can't make a comment without knowing how it was built. 

P.S: The PR has been merged and it's working

**Comment by muratugureminoglu** [comment]
I'm currently closing this issue and feel free to open if it does not work for you.
