### ISSUE TITLE
Get Ant Media Server listed in Softaculous one-click installer in Cpanel

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5555]
**Is your feature request related to a problem? Please describe.**
To enable an easy one-click installation of Ant Media Community edition or Enterprise edition, let's have it listed in Softaculous which comes with all cpanel web panel hosting for virtual servers, etc. 

**Describe the solution you'd like**
A Vulr customer for example orders a VPS or dedicated hosting service with Cpanel. They log in to their Cpanel navigate to the Softaculous section and see Ant Media Server. All they need to do is click install and it installs everything for them. 

It will provide a lot of visibility to new potential customers and also give Ant Media Server much more weight as an open-source project.

**Comment by timantmedia** [comment]
Was discussed here https://antmedia.slack.com/archives/C0346REFG22/p1688809065023649

**Comment by mekya** [comment]
duplication #5355
