### ISSUE TITLE
Error "Type 'AntMediaClient' does not conform to protocol 'WebSocketDelegate'" building WebRTCiOSSDK

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5565]
### Discussed in https://github.com/orgs/ant-media/discussions/5559

<div type='discussions-op-text'>

<sup>Originally posted by **joeAI335** September 16, 2023</sup>
Ran into the below compiling error while trying to build the project. Did nothing but just imported WebRTCiOSSDK
<img width="252" alt="Screenshot 2023-09-15 at 7 17 31 PM" src="https://github.com/ant-media/Ant-Media-Server/assets/5533663/a18169c6-2b17-4af5-87b5-69eef6a666bc">

Swift and XCode version: swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0</div>

**Comment by timantmedia** [comment]
Please refer to the discussion comments where I have reproduced the error.

**Comment by AlbinNewSeed** [comment]
We are also experiencing this issue.

**Comment by mekya** [comment]
Hi @AlbinNewSeed, @timantmedia 

I've sent the fix. It's about Starscream's new version (4.0.6) not being compatible with the older version (4.0.4). It's merged into the master branch.

Please try it and let me know if it works for you.

Cheers

PS: I've also tried giving the exact version, as you see in the commit history of the PR.
Xcode does not accept the `exact` attribute as valid when adding the dependency.
If you have any suggestions, I can apply and test them to avoid encountering the same problem again.

FYI
