### ISSUE TITLE
Test OBS streaming with RTMP on Apple M2 Chip MacBook

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5566]
- Run a RTMP stream with OBS streaming on Apple M2 Chip MacBook.
- Play the stream with WebRTC for an hour and monitor the playback for stability.

**Comment by mustafaboleken** [comment]
We tested it on ovh36 server and after 2 hours of stream, there is no problem on video. Stream health changed between 0.85x - 1.25x

**Comment by mustafaboleken** [comment]
We collected OBS logs from the customer's machine but there is no useful info. When we talked about what is the difference, customer says that ndi plugin force to change some OBS settings to be able to work. Probably, it causes this error. We can just close this issue for now.

**Comment by mekya** [comment]
I'm closing this issue because it's related to the Ant Media Server. Please feel free re-open if you would like to discuss further
