### ISSUE TITLE
Audio not adding in the Conference when adding a new stream using REST API

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5569]
### Short description
when adding a new stream to conference call using REST API only the video gets added into the conference.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:  2.7.0-SNAPSHOT
* Browser name and version:

### Steps to reproduce
1. Create a new room on circle conference call app
2. stream a video from obs with RTMP to conference application 
3. Send REST API Request for adding the stream in conference room 
![image](https://github.com/ant-media/Ant-Media-Server/assets/47350008/82163703-8066-4150-81bf-7a073f1a22b4)
4, stream will be added to room only video will be played 

### Expected behavior
both audio video should be played 
### Actual behavior
only video played
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
This behavior is unique to Circle; however, the multi-track conference is functioning correctly. The issue arises from structural distinctions between the Circle and multi-track conference sample, particularly in how audio tracks are added on the client side.

**Comment by lastpeony** [comment]
Fix: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/639

**Comment by lastpeony** [comment]
After last changes on webrtc client and circle, here is the new fix:
https://github.com/ant-media/conference-call-application/pull/309
