### ISSUE TITLE
Define the missing documentations since last release(2.6.4)

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5572]

**Comment by Mohit-3196** [comment]
I couldn't find many changes for the documentation as per the release logs of 2.6.4
- Adaptive streaming: Provide passthrough options for audio and video in adaptive bitrates for RTMP ingest
https://github.com/ant-media/Ant-Media-Server/issues/3842

- Multitrack conference: Switch from data only channel to video/audio in a multitrack conference
https://github.com/ant-media/Ant-Media-Server/issues/5392

**Comment by Mohit-3196** [comment]
- [ ] Correction in the positioning of enabling SSL from the web panel
- [ ] Update settings from the web panel
- [ ] Upload HLS files in real-time
https://github.com/ant-media/ant-media-documentation/pull/137
