### ISSUE TITLE
Cannot hear the first publisher in multitrack streaming when first joining a room with no A/V

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5574]
### Short description
In multitrack conferences, when participants join without video or audio, and then start to publish their A/V, no all participants are able to hear each other. 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce

create the following streams
- stream1 => main track
- stream2 => publisher 1
- stream3 => publisher 2
 
PUBLISHER 1
- send publish command (streamId = stream2, mainTrack = stream1, video = false, audio = true)
- sending audio level through data channel
- send play command (streamId = stream1, trackList=['!stream2'])
 
PUBLISHER 2
- send publish command (streamId = stream3, mainTrack = stream2, video = false, audio = true)
- sending audio level through data channel
- send play command (streamId = stream1, trackList=['!stream3"])
 
PLAYER
- send play command (streamId = stream1)
 
Depending on timing, when each party joins, the outcome is different

1) publisher 1 starts to publish and then the player starts playing => The player doesn't hear Publisher 1
                -> If publisher 2 joins afterward, the player hears publisher 2 but still doesn't hear publisher 1 (in this scenario, publisher 2 hears publisher 1)
2) publisher 1 and Publisher 2 start publishing and then the player starts playing => player hears both Publisher 1 and Publisher 2

### Expected behavior
All participants should be able to hear each other all the time when they start publishing. 

### Actual behavior
Always the first participant that starts to publish is always lost and cannot be heard once more participants join the room. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
@burak-58 please can you confirm the customer's specific configuration with Multitrack as I believe its a none standard setup from the default sample multitrack conference.  FD107015

**Comment by burak-58** [comment]
Resolved with https://github.com/ant-media/Ant-Media-Server/issues/6094
