### ISSUE TITLE
How do I set the token value for a player?

### ISSUE THREAD

**Issue by Jamong435** [ant-media/Ant-Media-Server#5576]
I have successfully set and transmitted the token value to 'obs.' However, the player does not seem to execute when I set the token value as shown below

http://[IP_Address]/<Application_Name>/play.html?name=streamID&playOrder=hls&token=tokenId

The screen displays only the sentence: 'Stream will start playing automatically when it is live.

thanks!

**Comment by lastpeony** [comment]
Hi,
What type of token do you use? JWT, OTT or time based?
You need to enable token authentication through web panel
Also please send console logs

**Comment by mekya** [comment]
hi @Jamong435 @lastpeony ,

Let me give my shot

The play.html has some information how to give the parameters. [Check this out](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L41)

Secondly, documentation also tells how to do that. [Check this out as well](https://antmedia.io/docs/guides/playing-live-stream/embedded-web-player/)

Please let us know if we can help you or anything is missing in the documentation

Cheers
Oguz

**Comment by lastpeony** [comment]
Greetings,

I am marking this issue as closed due to a lack of activity. Please don't hesitate to reopen it if you have additional questions or if your problem remains unresolved.
