### ISSUE TITLE
Grafana 10.1 + ElasticSearch 5.0.0 not 7.x.x

### ISSUE THREAD

**Issue by makurei** [ant-media/Ant-Media-Server#5594]
Grafana only shows ElasticSearch version 5.0.0

### Environment

Ubuntu 22.04
* Java version:  11.0.20.1
* Ant Media Server version: Community Edition 2.6.4 20230827_1333
* Browser name and version: Edge 117.0.2045.31 

### Steps to reproduce
1. Installed Grafana Monitoring thru the tutorial here
2. Add a Data source with ElasticSearch
3. Will give you no option to select a version

### Expected behavior
Should have shown a Version selector
![image](https://github.com/ant-media/Ant-Media-Server/assets/68965218/20610f9f-7b78-4007-9d31-bfee10dc8199)

### Actual behavior
Does not show version of ES and cannot continue
![image](https://github.com/ant-media/Ant-Media-Server/assets/68965218/0350a9b5-acf2-4977-a917-bd46b19f2ef1)

**Comment by muratugureminoglu** [comment]
Hi @makurei 

I can see in the screenshots you shared that you can select Elasticsearch version 7.0+. Could you please explain exactly what issue you are experiencing? If you provide more details, I'll do my best to assist you.

![269720163-20610f9f-7b78-4007-9d31-bfee10dc8199](https://github.com/ant-media/Ant-Media-Server/assets/6337605/125ec909-b8d6-4b5b-b9aa-afe7b1e1f91c)

**Comment by makurei** [comment]
Hi @muratugureminoglu 

That's the photo from the tutorial. The other photo is the one I am getting.

**Comment by makurei** [comment]
Anyone else having this problem with Grafana?

**Comment by muratugureminoglu** [comment]
Hi @makurei 

In the new version, have removed the ElasticSearch version field, but this is not a problem.

If you see "Data source successfully connected" when you click **Save and Test**, everything is working. But if you get @timestamp error, this indicates that there is no data in Kafka. So don't forget to add the Kafka URL in red5.properties file

https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/server/conf/red5.properties#L23


Example:
```
server.kafka_brokers=your_kafka_server:9092
```

 If you have any other questions, please don't hesitate to ask.

**Comment by makurei** [comment]
Hello @muratugureminoglu 

I have tried that but still gave me this error

![image](https://github.com/ant-media/Ant-Media-Server/assets/68965218/d8c97f1b-3f77-40cd-aab9-9aba6f0353a0)

**Comment by muratugureminoglu** [comment]
The meaning of this is that there might be no data coming into Kafka. You can check if there are topics with the following command[1] and then check if the data is coming in with the other command[2]. When I tried with the script, I was able to see the graphs through Grafana without any issues.

[1] On the Kafka server

```
/opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka_ip:9092
```

[2] On the Kafka server

```
/opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka_sip:9092 --topic ams-instance-stats --from-beginning
```

If there is no data, make sure that Ant Media Server can access Kafka on port 9092.

Example command:

On the Ant Media Server
```
telnet kafka_ip 9092
```

**Comment by muratugureminoglu** [comment]
Hi,

I'm currently closing this issue and feel free to open it if it does not work for you.
