### ISSUE TITLE
Support SRT playback 

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5598]
**Is your feature request related to a problem? Please describe.**
A customer asked about supporting SRT playback. 

Perhaps this method could be supported through the Ant Media/Gstreamer plugin https://antmedia.io/marketplace/gst-ant-fusion/ which already supports RTMP, and WebRTC playback.

**Comment by simonsundgaard** [comment]
Hey Tim, 
I'm the one who requested this. 
To give you some context: We're doing a lot of esports streaming, where the players are sitting at home and they stream us their game feed, so we can use it in our broadcast. 
Mostly they're streaming to us via SRT ingest into antmedia, and then we're including the stream in the broadcast via the webRTC play. 
It would be beneficial for us to also be able to pull the feed via SRT for certain of our products. 
At this moment we're using another service as SRT relay to achieve this, but would rather have it all in AMS.

**Comment by mekya** [comment]
Thank you for the info @simonsundgaard ,

Let's discuss this in the meeting @timantmedia @USAMAWIZARD

**Comment by USAMAWIZARD** [comment]
we have confirmed that its working Please reopen if it does not works for you.
