### ISSUE TITLE
Media Push Api Sound Problem

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5609]
If there is an autoplay video with audio enabled, audio is closed automatically.

**Comment by mustafaboleken** [comment]
@mekya Requested by [Onremote AG](https://antmedia.freshdesk.com/a/contacts/47067118991)

**Comment by mekya** [comment]
ok

**Comment by mustafaboleken** [comment]
It's approved by customer, and we merge it.

**Comment by e-vural** [comment]
Yes problem is solved. No need trigger with javascript. Only add autoplay video element. it works. Thank you @mustafaboleken
