### ISSUE TITLE
Broadcasting drops to 0.01x and stops streaming

### ISSUE THREAD

**Issue by LPLibrarian** [ant-media/Ant-Media-Server#5618]
### Discussed in https://github.com/orgs/ant-media/discussions/5615

<div type='discussions-op-text'>

<sup>Originally posted by **LPLibrarian** September 26, 2023</sup>
Hi all, I'm running some 24/7 livestreams to YouTube, and every couple of days, give or take, one of them will drop off and my stream will shut down. It's excruciating watching weeks of analytical progress be deleted because of this.

Whenever it happens, I check my ant media server and inevitably, the playlist that was being stream will have broadcasting lowered to 0.01x. Stopping the broadcast and starting it again will bring it back to normal.
I have no idea what the cause is, and am very limited in my knowledge of these things, if someone could please assist, I'll be what use I can with a little guidance. Thank you!</div>

**Comment by mustafaboleken** [comment]
I found out that after some time pts and dts values are not increased properly and it causes the broken pipe error. I'm continuing to work on it.

**Comment by LPLibrarian** [comment]
Thanks for the update - pleased to know its being addressed!

**Comment by mustafaboleken** [comment]
Update: I tested the scenario for a couple of days and saw that when the looped VOD file finished and started again this problem happened. I asked for the full logs on Github Discussion and after I validate it, I will go with the solution.

**Comment by mustafaboleken** [comment]
Update: The user says that it happened even the video is not ended. To be able to understand the root cause, the error log improvement https://github.com/ant-media/Ant-Media-Server/pull/5804

**Comment by mustafaboleken** [comment]
Hi @LPLibrarian,

When we try to solve the issue, we detect that the av_read_frame function causes the problem but the log that function produces is not very clear so we added an additional log to understand it better. Can you please install the following snapshot version and whenever you produced it again, please send log files again. https://drive.google.com/file/d/1i4v8Q_S9rhJ88c_hNREo5YDe7CXMxo-h/view?usp=sharing

**Comment by mustafaboleken** [comment]
Other than this log, I see that the mp4 files are so big. Can you please split them into smaller chunks? Because of you can add multiple playlist items, there won't be any trouble.
