### ISSUE TITLE
Video recording getting disturbed 

### ISSUE THREAD

**Issue by Samriddha01** [ant-media/Ant-Media-Server#5622]
I have used the Antmedia WebRTC-Android-SDK source code and built an android app for my use. I just used it to record a video and later play it and save it.
Now, when i am doing that, all the things recording, publishing etc. are working fine but the video gets tilted while being saved and half of the screen area gets blurred. i tried multiple devices and it is happening everywhere. PFA.

https://github.com/ant-media/Ant-Media-Server/assets/83784034/d28ceaca-cf30-48cc-ad63-d03c0c76696d

**Comment by Samriddha01** [comment]
i have solved the green area issue but still unable to solve the problem that the video gets rotated by 90 degree while being saved.

**Comment by yashtandon113** [comment]
@Samriddha01 
I was trying to reproduce this issue on my end, but I have not encountered the 90-degree rotation issue in a recording. Are you using the latest Android SDK build from [here](https://github.com/ant-media/WebRTC-Android-SDK)?

Also, it would be good if you could share the step-by-step reproduction scenario.

**Comment by yashtandon113** [comment]
@Samriddha01 
I am closing this issue for the inactivity. Please feel free to reopen it if you have any questions.
