### ISSUE TITLE
Android SDK - Unexpected behaviour after recovering from short connection loss (5-15 seconds)

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5627]
### Short description

***If the connection is lost for more than 15 seconds (25-30 seconds), there is no issue.*** 

However, if the connection is lost for less than 15 seconds (5-15s), then after connectivity is back and we call `webRTCClient.startStream`, for some time we are receiving `onStreamIdInUse`. 

We try to call `startStream` several times, receiving `onStreamIdInUse`, until finally after maybe 8-10 seconds, we receive `onIceConnected` and the stream resumes, only to receive `onIceDisconnected` and `onPublishFinished` some 40 seconds later.

If we then call `webRTCClient.startStream`, it starts again without any further issues and the stream already runs without interruption.

### So the lifecycle is something like:

onPublishStarted
...
connection lost
onDisconnected
onIceDisconnected
...
connection regained
webRTCClient.startStream (webRTCClient.isStream is false at this moment)
onStreamIdInUse
...
3s later we try again webRTCClient.startStream
onStreamIdInUse
...
3s later webRTCClient.startStream
onStreamIdInUse
...
3s later webRTCClient.startStream
onIceConnected
stream is resumed
...
40s later onIceDisconnected
another 10s later onPublishFinished

now we can call again webwebRTCClient.startStream, and receive 
onIceConnected
onPublishStarted

### Latest version of Android SDK

Behaving even worse with `onPublishFinished` completely missing in our connection loss/regain scenario, preview freezing

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mustafaboleken** [comment]
I'm still working on it

**Comment by DevendraGetkart24** [comment]
Hi, I am facing same issue during low network, my app has been crashed and got the message "ice disconnected".

**Comment by DevendraGetkart24** [comment]
Hi, facing same issue during low network, app is crashing when network is low and getting message "ice disconencted"

**Comment by mustafaboleken** [comment]
Hi @DevendraGetkart24 ,
Can you please share the crash log with us?
