### ISSUE TITLE
Controls keeps showing and hiding during CMAF (Dash) Playback

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5628]
### Short description
During the DASH playback, controls are showing and hiding continuously which is affecting the playback experience. 

### Environment
* Ant Media Server version: v2.6.2 and above
* Browser name and version: Chrome & Edge

### Steps to reproduce
1. Enable the CMAF
2. Publish the stream on a server
3. Play the stream with CMAF (Dash)

### Expected behavior
Stream should be smooth and their should be no disturbance during the playabck.

### Actual behavior
During the Dash playback, video controls keep showing and hiding. The video link has been attached for the reference.
https://drive.google.com/file/d/1VeLRZoS7xbBGZNMH5S1RQd54RtaYdIb_/view?usp=sharing

**Comment by mekya** [comment]
I've moved this to the backlog. 

Please let me know if we need to increase its priority.

**Comment by reiluke** [comment]
We have tried  basic dash videojs player playing mpd files generated by antmedia, it works fine, so problem is likely in antmedia dash player, sample code from here https://videojs.github.io/videojs-contrib-dash/, as an alternative we made separate player for dash

**Comment by mekya** [comment]
Thank you for the update @reiluke 

I'm adding this discussion link for the developer as well. 

https://github.com/orgs/ant-media/discussions/5619#discussioncomment-7244815
