### ISSUE TITLE
Adaptive bitrate makes webrtc live broadcasts laggy; recordings and hls are fine

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#5635]
### Short description
We use a streaming application on AntMedia to stream several 4k cameras. The application has adaptive bitrate turned on with four resolutions: 2160p (original), 1080p, 480p and 240p, and the framerate set to 20. The streams are recorded in MP4 format. 

The camera stream is delivered over RTMP with ffmpeg. When played via WebRTC, the video shows 1 frame per 2-3 seconds independent of the chosen quality. The HLS broadcasts as well as recording is fine, though. However, HLS is not a solution for us due to the latency (we use AntMedia for streaming lectures and exercise classes in a conference mode, with a two-way interaction). We had no issue when using AntMedia 2.4.3 on Ubuntu 20.04.

This issue happens already with 1 stream. Both CPU and GPU usage are very low:
<pre>
> nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 4000                On  | 00000000:00:0A.0 Off |                  N/A |
| 30%   48C    P0              36W / 125W |    942MiB /  8192MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     10084      C   .../jvm/java-11-openjdk-amd64/bin/java      938MiB |
+---------------------------------------------------------------------------------------+

> top
Tasks: 141 total,   1 running, 140 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.4 us,  1.8 sy,  0.0 ni, 93.6 id,  0.1 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :  15985.1 total,   8754.8 free,   5631.4 used,   1598.9 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used.   9960.3 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
  10084 antmedia  20   0   17.3g   5.1g 753452 S  25.5  32.9  52:52.38 java                             
 118381 root      20   0    6700   2504   2208 S   2.0   0.0   0:14.04 less                             
...
</pre>
**Note** Despite CUDA 12.2 shown in the output of nvidia-smi, the actual version is 11.8 as described in https://github.com/ant-media/Ant-Media-Server/issues/5621#issuecomment-1737709934

### Environment

* Operating system and version: Ubuntu 22.04.03
* Java version: openjdk-11-jdk / 11.0.20.1
* Ant Media Server version: Enterprise Edition 2.6.3 20230823_1611 
* Browser name and version: N/A

### Expected behavior
The video stream should have the frame rate of 20 FPS.

### Logs

* No errors or warnings
* Periodic stream statistics shows speed between 0.997x and 1.002x and queue size 0
* A message `[network_thread - 118948] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount` appears every 15sec

I can provide detailed logs when requested.

**Comment by kputyra** [comment]
Thanks to a report from @timantmedia I was able to locate the source of the issue. It appears that the problem is not with AntMedia, but with the browser that was used to play the stream: **Firefox 118.0.1 (64-bit), Ubuntu 22.04 LTS**

Further observations:
* The stream is smooth when played in Chrome: both as WebRTC or HLS
* The stream is laggy in Firefox only when played for the first time - also when played via HLS
* If the player page is opened when the stream is stopped and restarted, then it is smooth when played again (this was perhaps the reason why HLS was smooth for me before)
* the stream was OK in Firefox before the upgrade from Ubuntu 20.04.

I've tested Chrome on Ubuntu 22.04 and Windows 11.
I've tested Firefox only on Ubuntu 22.04 (I don't have it on my Windows laptop).

**Comment by timantmedia** [comment]
I reproduced this issue on Ubuntu. Firefox 118 does not play the stream well (laggy and slow) when using  ABR. When not using any ABR, the stream plays fine.

**Comment by kputyra** [comment]
The problem was a bug in Firefox, see #5659.

**Comment by mekya** [comment]
Thank you or the update @kputyra. You're great 👏
