### ISSUE TITLE
I am streaming from obs but stream on ant media says Your live stream will play automatically as soon as it's available. Get ready to be part of the action!

### ISSUE THREAD

**Issue by gc23485** [ant-media/Ant-Media-Server#5651]
I am just getting the screen whenever I stream.

Ports are open, firewall isn't blocking anything.

It happens on LiveApp and webRTCapp.

If I record the stream, it will playback correctly on VoD, but the stream itself will not load when live.

I have also used the &playOrder=hls with no success!

What could be causing this??

**Comment by Mohit-3196** [comment]
Hi @gc23485,
How are you doing?

It seems you are using the Ant Media Server Community edition.
Can you please check if Create HLS streaming options are enabled or not? 

If it is then please share your Ant Media Server Web Panel login details with me via mohit.dubey@antmedia.io and I can quickly check the issue and help you with it.

Thank you

**Comment by Mohit-3196** [comment]
Hi @gc23485 ,
How are you?

I'm waiting to hear from you.
In case I do not hear from you, I will temporarily close this issue for inactivity.

Thank you.
