### ISSUE TITLE
No audio in RTSP stream publishing using Embedded SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5666]
### Short description
When any normal camera RTSP stream is published using the Embedded SDK, there is no audio on the server side while the audio is working during test in VLC player with RTSP URL.

### Environment
* Ant Media Server version: v2.6.2 and above

### Steps to reproduce
1. Install Embedded SDK: https://github.com/ant-media/WebRTCEmbeddedSDKReference
2. Run the executable it in a publishing mode
3. Play the WebRTC stream on a server

### Expected behavior
Their should be audio in a stream.

### Actual behavior
Their is no audio in a stream on server side while in RTSP URL, audio is playing fine on VLC player.

**Comment by mekya** [comment]
Hi @yashtandon113,

Thank you for creating the issue. Please let us know the priority of the issue in the sprint meeting 

Regards
Oguz
