### ISSUE TITLE
Despite claim Antmedia does not install on Mac OS.

### ISSUE THREAD

**Issue by mooncatventures-group** [ant-media/Ant-Media-Server#5700]
### Discussed in https://github.com/orgs/ant-media/discussions/5699

<div type='discussions-op-text'>

<sup>Originally posted by **mooncatventures-group** October 18, 2023</sup>
The website and ads claims this product can be installed on Mac OS  

After trying several competitors and being disappointed with features , we decided to give AntMeda a try, foolishly we went for the paid trial instead of opting for the community version because we didn't want to waste our time configuring the product. We need a good WebRTC server, 
After many attempts, including making alterations to the script for clearly Linux-specific directories  and functions, We used brew to install Apget for instance, we found we still couldn't get past the incredibly poor information on Red 5 installation.

Frustrating we even put in a support request. The service level agreement says 24 hours max 3 days, its been over 4 and no reply.

We wasted precious hours on a product that simply does not wor as advertised.. And promises non-existent support for paid customers. Very disappointed, unless you are on vanilla Ubuntu Linux stay far away from this product.</div>

**Comment by mekya** [comment]
Hi Guys,
Thank you for the question and answer. 

I'm closing this issue because it's both duplication and answered in the issue link.
Please feel free to re-open if you think I'm making a mistake. 

> Hi @mooncatventures-group
> 
> I already explained [here](https://github.com/ant-media/Ant-Media-Server/issues/1237#issuecomment-1770665261)
> 
> Regards.


Cheers
Oguz
