### ISSUE TITLE
Strange interstitial image when network connection is lost and recovered

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5721]
### Short description

We have a strange issue when we lose the RTMP feed temporarily into our Ant Media server installation.

We output a powerpoint feed, which is captured by an encoder, sent to an NUC running Ant Media Server WebRTC ingest, and 300 or so iPads then open play.html to view the powerpoint output.

When we temporarily lose the feed from the encoder, the play.html displays an odd "old" screen capture of an input from a long time ago - it appears to be a Windows login screen. None of the devices on the network are outputting this image - the encoder is not outputting it, and it's not being served by a local cache. 

I can therefore only assume the image is cached in the Ant Media Server installation on the NUC.

Is there any way I can purge this image from the Ant Media server so it doesn't display?

### Environment

* Operating system and version:
NUC has Ubuntu 22.04.3 LTS
iPads have a mix of iPadOS 16 or 17
* Java version: 
OpenJDK version 11.0.20.1
* Ant Media Server version:
Enterprise Edition 2.6.4 20230827_1351
* Browser name and version:
iPadOS Safari version as shipped with iPadOS

### Steps to reproduce

Refer to the FD111519 and there is a video showing the issue

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by Mohit-3196** [comment]
Hi @timantmedia ,
I checked the ticket and it seems that it's been closed on the FD side after some discussions.
Since the customer is playing with WebRTC, how about using the `&playOrder=webrtc` flag?
It will remove any instance of a player falling to HLS or showing any cached content, etc.

The same can also be verified from the developer inspect tool to see if the playback was falling to HLS at the end.

I think `&playOrder=webrtc` will resolve this issue.

Let me know if it works.

Thank you.

**Comment by Mohit-3196** [comment]
Hi @timantmedia,
Let me know if there are any updates or comments on this.

Thank you

**Comment by timantmedia** [comment]
@Mohit-3196 The customer hasn't had time to implement the changes we recommended to see if it resolves the issue. I also replied with your suggestions, but I closed out the case until he can respond.

**Comment by Mohit-3196** [comment]
Thank you @timantmedia,
Let's close this issue then and it can be reopened when the user replies.

Thank you
