### ISSUE TITLE
Feasibility Cocos Creator Support

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#5728]
Currently I have a project already on live with the H5 version which is developed using Cocos Creator. And we are planning to have it also on the APP version available for both android and iOS. We couldn't seem to find any relevant SDK that are supportive to our development, if possible we would like to have a SDK that can allow us to develop and embed into our application.

**Comment by mekya** [comment]
I think it takes about 5 days for Android and iOS. In total, it takes about 10 days.
