### ISSUE TITLE
Use Live and VOD in playlist creation

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5732]
### Short description
The ability to seamlessly switch between live and vod streaming on the same stream id. 

For example, turn on/off RTMP live streaming and when off, the same stream ID is playing back a VOD asset without any reload necessary. 

Currently, the only way to achieve this is to stop/start the live stream to turn off/on the VOD/Live stream which is not a very good user experience on the playback side. 

FD111494

**Comment by mekya** [comment]
Hi @timantmedia,
Thank you for creating the request. 

Please let us know if we can increase the priority of the issue.

Regards

**Comment by mekya** [comment]
Hi,

I got the idea about the priority. There is also a discussion here: https://github.com/orgs/ant-media/discussions/5599.

Is that solution good enough to proceed? If yes, it's already available

1. Vod01
2. Live01  (Let the Ant Media Server pull Live HLS internally as stream source: http://ant-media-server/WebRTCAppEE/streams/live01.m3u8)
3. Vod02
4. Live02 (Let the Ant Media Server pull Live HLS internally as stream source: http://ant-media-server/WebRTCAppEE/streams/live02.m3u8)


If it's not enough and still a blocker to proceed, we just need one of them or both of them.
- We provide a REST method to skip the items, such as play next item (i.e., switch from Live01 to VoD02) 
- We provide a duration field for the live streams. I mean, it may play Live01 for 5 minutes(configurable) and proceeds to next item after 5 minutes, no matter if live streams continue.

Please let us know how you would like to proceed.

Cheers
Oguz

**Comment by timantmedia** [comment]
@mekya theoretically this does work, although the live stream needs to end before the next VOD in the playlist is live, meaning you couldn't keep the live stream running and move to the next playlist. Furthermore, there is a period of loading with the default loading message before between ending the live stream and starting the VOD playing. I am not sure this is the desired effect, more of a smooth transition between live and VOD without any delay, but I'll ask the customer to confirm expectations.

**Comment by mekya** [comment]
Hi @timantmedia,

As @yashtandon113 mentions, we can merge the PR to skip to the next item in the play list so no need to wait live stream to be finished. Secondly, we can add duration for the streams. Could you please confirm with the user any of this solution works for them?

Regards
Oguz

**Comment by timantmedia** [comment]
Waiting for customer to respond FD111494
