### ISSUE TITLE
Unexpected recording formats getting created - VP8 codec streaming, MP4 recording created

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5734]
### Short description
There is an inconsistency between what codec the browser is using for live streaming vs what recording format is being used. 

For instance, if both VP8 and H264 is selected in the application settings and Chrome (which supports VP8 and H264) is being used to live stream, VP8 is selected as the streaming codec, however, the MP4 is created not the WebM. 

Unless only VP8/WebM is checked, the recording is always as MP4 format. 

### Environment

* Operating system and version: Ubuntu 22
* Java version: 
* Ant Media Server version: 2.7.0 snapshot
* Browser name and version: Chrome 118

### Steps to reproduce
1. Select both VP8/H264 as encoder options
2. Select both WebM/MP4 as recording options
3. Start a live stream and observe the Chrome webrtc internals
4. Acknowledge that VP8 is getting selected
5. Stop the stream and observe only MP4 recording is created

### Expected behavior
MP4 should be created and playable because the server prefers to use H264 if possible. 

### Actual behavior
MP4 is not playable and there is an codec problem in the MP4 file

If VP8/WebM is the only selected codec/format, then WebM is created. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
Reproduced with @mekya last week.

**Comment by mekya** [comment]
Fix is in this [MR 659](https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/659)
