### ISSUE TITLE
YouTube streaming abruptly stops after few days.

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5738]
### Short description

I'm running some 24/7 livestreams to YouTube, and every couple of days, give or take, one of them will drop off and my stream will shut down. It's excruciating watching weeks of analytical progress be deleted because of this.

Whenever it happens, I check my ant media server and inevitably, the playlist that was being stream will have broadcasting lowered to 0.01x. Stopping the broadcast and starting it again will bring it back to normal.
I have no idea what the cause is, and am very limited in my knowledge of these things, if someone could please assist, I'll be what use I can with a little guidance. Thank you!

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Start Live Streaming to youtube
2. wait for couple of days
3. Streaming will stop 

### Logs

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mustafaboleken** [comment]
Duplication of https://github.com/ant-media/Ant-Media-Server/issues/5618
