### ISSUE TITLE
[Mobile SDK] WebSocket Connection is remain after publish stopped

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5748]
Reported by Onremote AG

Expected behavior: When we stop publishing, the WebSocket connection should disconnected completely.
What happened: After we stopped publishing, connection is still continue and because of that we cannot make a second call properly until we restart the application.

**Comment by mustafaboleken** [comment]
This can be a problem of the SDK itself or it can be related to SDK's usage. We should check it first.

**Comment by mekya** [comment]
hi @mustafaboleken,

AFAIK this is the expected behavior. We don't stop connection after user leaves the room.  On the other hand, I think user should make a second call without any problem. 

Regards
Oguz

**Comment by mustafaboleken** [comment]
I talked with them and besides the WebSocket connection remains topic, the real issue is that they have some audio-related issues about the second call. I have found an issue about the audio toggle and fixed it. I will send a snapshot version to them.
