### ISSUE TITLE
I'm trying to stream from obs to Ant Media Server - it gives error: Unable to access the specified channel or stream key, check your stream key.

### ISSUE THREAD

**Issue by FranciscoNetoBr** [ant-media/Ant-Media-Server#5749]
I'm trying to stream from obs to Ant Media Server - rtmp://144.22.195.199/WebRTCApp/HtjZIteFGUE11697042289657 , it gives error: Unable to access the specified channel or stream key, check your stream key. If this is correct, there may be a problem connecting to the server.

I've already checked the ports, etc. I use an Oracle VPN and followed the procedure https://www.minextuts.com/create-24-7-live-streaming-server-free-multistream-enabled/ for configuration.

I did a lot of research before posting here, I hope I can solve the problem.

Thanks in advance.

**Comment by mekya** [comment]
Hi @FranciscoNetoBr,

Thank you for creating the issue. I think the correct location to ask this question is the Discussions.

I've created the question for your convenience here -> https://github.com/orgs/ant-media/discussions/5751 . Someone from the community will answer that

So I'm closing this issue. Please feel free to re-open if you have any objection. 

Regards
Oguz
