### ISSUE TITLE
SRT stream disconnecting when stream is running continuously.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5752]
We have been experiencing issues sending streams to the server.
- We are seeing connection refusal and disconnection errors after 72 hours but often see an increase in disconnection frequency the longer the stream is running, to the point of having to replace the stream name completely after not reconnecting at all to the server.
- When the stream gets refusal of connection, the console often shows a stream is still live when there is not.
 
We have created an SRT endpoint for you to recreate the issue -  srt://****:4200?streamid=****/****
(if you could pls use an actual encoder in addition to OBS to test this as OBS is not broadcast standard in IPTV operations, and we need to make sure ANT media is compatible with industry standard encoders).
The expected behavior for this test is that you would not be able to have a stream running 3 to 7 days consecutively without interruption server side.

**Comment by Mohit-3196** [comment]
I have created a sample ffmpeg script to push a SRT stream to the Ant Media Server and it is currently running in the test environment.

FYI all

**Comment by Mohit-3196** [comment]
I have been running a couple of SRT streams on a test server running Ant Media Server v2.7.0 and the publish/play is working as expected.

So as a next step, I will be updating the customer's AWS cluster to v2.7.0 this Tuesday.

FYI

**Comment by Mohit-3196** [comment]
The cluster was updated on Friday and the SRT streams running fine.
Therefore, this issue can be closed.

**Comment by Mohit-3196** [comment]
Hi @mekya abi,
Actually during our tests, I ran one stream using ffmpeg and the user also sent a stream using his encoder and both the streams ran fine without any issues for a week.
And following that I updated their Cluster environment on Tuesday and the SRT steams are now running fine on the customer server as well.

So, the issue has been resolved.

Thank you

**Comment by mekya** [comment]
Thank you @Mohit-3196,

Good to know.
