### ISSUE TITLE
Add documentation for refactored Android SDK

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5756]

**Comment by yashtandon113** [comment]
Update: I worked with @burak-58 on implementation before writing the document, but their is a blocker. The android framework version on [sonatype](https://oss.sonatype.org/#nexus-search;gav~io.antmedia~webrtc-android-framework~~~~kw,versionexpand) is very old and seems outdated.

**Comment by yashtandon113** [comment]
As the work is in progress for the Android SDK refactor, this task is currently not started.

**Comment by yashtandon113** [comment]
Documentation is complete for the publish and play sample using refactored new Android SDK changes. Here is the PR, which will be merged by @Mohit-3196.

https://github.com/ant-media/ant-media-documentation/pull/182

**Comment by yashtandon113** [comment]
Completed and done.
https://antmedia.io/docs/category/android-sdk/
