### ISSUE TITLE
Screen rotation in landscape, Streaming is stop 

### ISSUE THREAD

**Issue by yogeshkaharmis** [ant-media/Ant-Media-Server#5757]
Hello ,
I am facing the issue in streaming.
when we share device screen in live streaming in portrait mode, it will work fine, but when we change screen rotation streaming will be stop. 

[AbstractSampleSDKActivity.txt](https://github.com/ant-media/Ant-Media-Server/files/13215406/AbstractSampleSDKActivity.txt)
[MainActivity2.txt](https://github.com/ant-media/Ant-Media-Server/files/13215420/MainActivity2.txt)

Above files is the complete code.
Please help me.
Thank you

**Comment by yogeshkaharmis** [comment]
hello @yashtandon113 
can you help me for this issue?

**Comment by yashtandon113** [comment]
@yogeshkaharmis 
Let me investigate this issue tomorrow. I will update you.

**Comment by yashtandon113** [comment]
@yogeshkaharmis 
Today, I tried to reproduce the issue, and when I tried without setting the width and height, I was facing some problems as my device was sending 2400p, but still, I was able to publish with a rotation from portrait to landscape mode. Here are my steps after that:

1. Downloaded latest Android SDK zip
2. Launched and changed the resolution as below in screen capture activity as below:

```
        this.getIntent().putExtra(CallActivity.EXTRA_CAPTURETOTEXTURE_ENABLED, true);
        this.getIntent().putExtra(CallActivity.EXTRA_VIDEO_BITRATE, 2500);
        this.getIntent().putExtra(CallActivity.EXTRA_VIDEO_WIDTH, 1080);
        this.getIntent().putExtra(CallActivity.EXTRA_VIDEO_HEIGHT, 1920);
        //this.getIntent().putExtra(CallActivity.EXTRA_SCREENCAPTURE, true);
        this.getIntent().putExtra(CallActivity.EXTRA_VIDEO_FPS, 30);
```
3. Start the screen sharing activity and rotate it to landscape mode
4. Published the stream
5. I checked the playback, and it was fine. Here is the screenshot:

![image](https://github.com/ant-media/Ant-Media-Server/assets/82374739/aa012cce-76ab-4ffb-93be-c72cb102783e)

Please let me know if I missed any steps or if you have a different scenario than this to reproduce the issue.

**Comment by yogeshkaharmis** [comment]
@mekya 
Thanks you.
it is working fine.

**Comment by yashtandon113** [comment]
@yogeshkaharmis 
Thanks for the confirmation.
Then I am marking this issue as resolved and closing it. Please feel free to reopen it if you have any questions.
