### ISSUE TITLE
HLS files are getting longer to delete after the stream ends.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5768]
- Set the HLS List size to 3600
- Set the Segment duration to 2
- Delete HLS files when ended is enabled

This will give a seek-back duration of 2 hours for the HLS streams.

- When the stream is ended, it takes a couple of hours for the HLS files to get cleared.

**Comment by yashtandon113** [comment]
I think it is expected behavior to make sure that the whole stream is available for the viewers who are watching the stream.
