### ISSUE TITLE
Feature to set the HLS List size and Segment duration per stream basis Programmatically

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5769]
**Is your feature request related to a problem? Please describe.**
A user would like to have the feature to set the HLS list size and HLS segment duration for each stream individually.
Currently, these can be configured Applications wise and therefore it is Application specific but the user would like to have this feature per stream basis.

**Describe alternatives you've considered**
I recommended using different applications to categories the streams with similar settings as a workaround solution but as per the user's use case, they need different seek back time for each stream.

**Comment by mekya** [comment]
Thank you, @Mohit-3196 for the issue.

What's the priority of this issue?

**Comment by Mohit-3196** [comment]
This is coming from an AWS Marketplace cluster user.
They want to have an option in which they can control the seek back time for each stream and provide different timelines to their customers.

They expect to have 100 publishers per meeting and 200 meetings per day with 100 to 10K HLS viewers and use c5.24xlarge instances in their autoscaling cluster.

@muratugureminoglu abi, FYI please

**Comment by burak-58** [comment]
With the PR https://github.com/ant-media/Ant-Media-Server/pull/5824:

You can pass HLS parameters (_hlsTime, hlsListSize, hlsPlayListType_) while creating the live stream.

**Example:**

`curl -X POST -H "Accept: Application/json" -H "Content-Type: application/json" http://localhost:5080/LiveApp/rest/v2/broadcasts/create -d '{"streamId":"test1","name":"test1s","type":"liveStream","hlsParameters":{"hlsTime":"4","hlsListSize":"7","hlsPlayListType":"event"}}'`
