### ISSUE TITLE
Find the documentations need to be updated or created for 2.7.0

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5780]

**Comment by Mohit-3196** [comment]
- [ ]

**Comment by Mohit-3196** [comment]
- [ ] FAQ and publish-play document update about Stereo and High Audio Quality Support in WebRTC Publishing and Playing
- [ ] Support for ID3 tags - New document & FAQ
- [ ] Block subscribers from publishing and playing stream - New document & FAQ
- [ ] FAQ about current WebRTC Stack
- [ ] Flag to enable sending audio level](https://github.com/ant-media/Ant-Media-Server/pull/5543) - FAQ
- [ ] getVideoTrackAssignments call and getBroadcastObject - websocket reference document update https://github.com/ant-media/conference-call-application/issues/156

**Comment by Mohit-3196** [comment]
[Stereo sound for the Ant Media Server v2.7.0 · ant-media · Discussion #5794](https://github.com/orgs/ant-media/discussions/5794)
[ID3 tags for HLS Playback · ant-media · Discussion #5795](https://github.com/orgs/ant-media/discussions/5795)
[How to block Subscribers from Publishing and Playing the streams? · ant-media · Discussion #5796](https://github.com/orgs/ant-media/discussions/5796)
[WebRTC stack upgrade · ant-media · Discussion #5797](https://github.com/orgs/ant-media/discussions/5797)

**Comment by mekya** [comment]
Another one that we provide some documentaiton -> https://github.com/ant-media/Ant-Media-Server/issues/1337

**Comment by MaZZly** [comment]
@mekya @Mohit-3196 

What is the status of documentation on https://github.com/ant-media/Ant-Media-Server/issues/1337 ? 

It is something we need soon so would be good if it could be prioritized :)

**Comment by Mohit-3196** [comment]
Hi @MaZZly,
Thank you for writing back.
I have scheduled this for this weekend to work on. So it'll be available soon :)

Thank you

**Comment by MaZZly** [comment]
@Mohit-3196 any update here? :)

**Comment by Mohit-3196** [comment]
Hi @MaZZly,
Please pardon me for the unwanted delay. I got stuck in some other things, it is on my priority list and I'm surely going to share the instructions very soon.

Thank you so much for your patience and understanding.

**Comment by Mohit-3196** [comment]
Hi @MaZZly,
How are you?

First, accept my apologies for my lack of knowledge on this topic. I was trying to learn about this conference room security and that's why it took so long.
I hope you will forgive me in this festive time :)

Now moving ahead, you can refer to this discussion https://github.com/orgs/ant-media/discussions/5893
Here one of my senior colleagues has described how to use security in a conference.

Please check it and let me know if anything is not clear and I will also update the stream security document.

Thank you and Merry Christmas.
