### ISSUE TITLE
Writing test codes for new changes on conference structure

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5783]
Here is the related pull-request https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/624

**Comment by mustafaboleken** [comment]
I already added some test codes but during tests, we noticed that new changes are not working in the cluster environment. Before finalizing this task, we need to finalize cluster implementation.

**Comment by mustafaboleken** [comment]
It's done

**Comment by mekya** [comment]
This PR is not merged. What's the status here for this issue?

https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/624

**Comment by mustafaboleken** [comment]
@mekya I have check it so many but cannot solve the no files to upload ci issue. (I also checked it with Murat abi too). I just update it to get JDK update. Let's see if ci fixed or not.

**Comment by mustafaboleken** [comment]
It's merged https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/640
