### ISSUE TITLE
Server crashes on stream publish when both H264 and VP8 codecs are chosen

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#5788]
### Short description

I have selected both H264 and VP8 WebRTC codecs. At the moment I started to publish a stream via RTMP (ffmpeg), the server has crashed.

### Environment

* Operating system and version: Ubuntu 22.04.2 LTS
* Java version: 11.0.20.1
* Ant Media Server version: Enterprise Edition 2.6.3 20230823_1611

Hardware:
* CPU: 4 core
* RAM: 16 GB
* GPU: Quadro RTX 4000 (8192 MiB)
* Cuda driver: 535.129.03

### Steps to reproduce
1. Create a streaming app with adaptive bitrate (one resolution is enough)
2. Select WebRTC codecs H246 and VP8
3. Create an RTMP stream

### Expected behavior
The stream is accepted and can be played.

### Actual behavior

* The server crashes within a few seconds when both codecs are selected.
* Everything is fine if only H264 is selected
* There are blocked threads when only VP8 is selected.

Here are the results of my tests in the order I've performed them. Note that the CPU usage was never very high when both encoders were used.

#### ABR settings: 240p, 720p

| Encoders | H264 |  VP8 | H264+VP8 |
|---|---|---|---|
| CPU load |  60% |  90% | 100%     |
| GPU load |   1% |   0% |   0%     |

H264+VP8: crashed after 4sec

#### ABR settings: 720p

| Encoders | H264 |  VP8 | H264+VP8 |
|---|---|---|---|
| CPU load |  40% |  90% |  35%     |
| GPU load |   1% |   0% |   0%     |

H264+VP8: crashed immediately; CPU load never went over 35%

#### ABR settings: 240p, 720p, 1080p, 2160p

| Encoders | H264 |  VP8 | H264+VP8 |
|---|---|---|---|
| CPU load | 105% | 250% |  ---     |
| GPU load |   4% |   0% |  ---     |

VP8: blocked threads, but the server did not crash

**Comment by lastpeony** [comment]
Fix: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/637
