### ISSUE TITLE
Not able to upgrade the server on a mounted directory.

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5800]
### Short description
We have installed Ant Media Server 2.6.2 , and we are trying to upgrade the server with the upgrade script to 2.7.0
We did not have any space left on the server to update the server so we mounted a disk (LVM partition ) to /usr/local/antmedia , but during the update process the script is trying to move the antmedia directory to a backup folder at /usr/local/backup.

but its able to move from the monted disk to /usr/local.

### Environment

Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/appsvg-appslv        100G  2.3G   98G   3% /usr/local/antmedia

* Operating system and version:
* Java version: 
* Ant Media Server version:2.6.2!!

### Logs
[ams_install_logs.log](https://github.com/ant-media/Ant-Media-Server/files/13318722/ams_install_logs.log)

 sudo mv /usr/local/antmedia /usr/local/antmedia-backup-2023-11-10_10-19-58
mv: cannot move '/usr/local/antmedia' to '/usr/local/antmedia-backup-2023-11-10_10-19-58': Device or resource busy
Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

It looks to me that this is a support case. It's not an issue. If you think differently, please let me know what you expect from the installation script. 

Regards
Oguz

**Comment by muratugureminoglu** [comment]
In upgrade processes, the /usr/local/antmedia directory moves into the same directory with the date extension. So the mounted system cannot be moved. That's why you get this error. 

The upgrade can be manually or mount the /usr/local/ directory (not /usr/local/antmedia). This way the /usr/local/antmedia directory can be changed without any issues.

**Comment by USAMAWIZARD** [comment]
Okay I told the user to to mount usr/local/ but they said that usr/local contains system files and they don't want to have system related file as a mounted drive as it can cause issues.

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

If you approach this from the solution perspective,  let's think what  the options are in our hand to resolve the issue?

**Comment by USAMAWIZARD** [comment]
Customer mounted to usr/local and its now able to upgrade.
