### ISSUE TITLE
chrome to safari playback not working.

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5801]
### Short description
We have our Conference call system based on multi track conference example.but one of the client joins from safari and the player joins from chrome the safari one is not able able to play the stream coming from the chrome browser.

### Environment
* JavaScript SDK version : 
* Ant Media Server version:2.6.2
* Chrome  version:  will update.
* Safari version : will update

### Steps to reproduce
1. Will update here.
2. 
3.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__
```

[Error] Failed to load resource: the server responded with a status of 404 () (en.json, line 0)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	playVideo (main.a2b47a1d3f2c74ec.js:1:1161946)
	(anonymous function) (main.a2b47a1d3f2c74ec.js:1:1159150)
	next (main.a2b47a1d3f2c74ec.js:1:540983)
	_next (main.a2b47a1d3f2c74e
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

```
Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

The same problems happens in multitrack sample that we provide? I just want to understand if this is about us or this is about development of another conference solution. 

Regards
Oguz

**Comment by USAMAWIZARD** [comment]
Problem was not reproducible on sample , Issue was something related to their development and its fixed now.
