### ISSUE TITLE
Problem with ssl certificate #5506

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/Ant-Media-Server#5828]
https://github.com/ant-media/Ant-Media-Server/issues/5506

**Comment by studentAlanMorgan** [comment]
Problem solved. replacing the folder.

**Comment by mekya** [comment]
Thank you for the update @studentAlanMorgan.  Then I'm closing this issue. 

It will be great if you share how you resolve the issue with simple explanation so that newer comers may save some time.

**Comment by studentAlanMorgan** [comment]
@mekya 
I changed the folder where the certificate is located.
The site now has a valid certificate, but nginx won't start due to a certificate error. I can't understand anything here :(

**Comment by muratugureminoglu** [comment]
Hi @studentAlanMorgan 

Can you please share the output of the following commands ? Then we can comment 

```
nginx -t 
```

```
journalctl -u
```

**Comment by studentAlanMorgan** [comment]
@muratugureminoglu Thanks, but the problem has already been resolved.

**Comment by muratugureminoglu** [comment]
Thanks for getting back to me. I'm closing this issue. Please feel free to ask if you have further questions.
