### ISSUE TITLE
Upgrade Ant Media Server on the Fly

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5833]
Enterprise & Community
   - [x] Create update.sh on Ant Media Server repository
   - [x] If it's community edition, compare github release and current release
   - [x] If it's enterprise edition, compare the antmedia.io release and current release  
   - [x] If latest release is new then the current release, it downloads install-ant_media_server.sh , community or enterprise edition
   - [x] Run `install-ant_media_server.sh` with `-r true` parameter

CI 
   - [x] Send latest release to the antmedia.io with a json file
    
Enterprise Marketplace
   - [ ] Search on AWS documentation how to upgrade marketplace images

**Comment by muratugureminoglu** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/642

**Comment by muratugureminoglu** [comment]
Unfortunately, As I checked there is no structure to upgrade Marketplace products. It should be upgraded by software
