### ISSUE TITLE
Server Crash Randomly

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5841]
### Short description
The server some time randomly crashes , we are publishing WebRTC stream to AMS 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.7.0
 x86_64CPU op-mode(s): 32-bit

### Steps to reproduce
We are publishing WebRTC and the server unexpectedly crashes some times. 
crash logs are attached in the issue 2023-11-22 03:34:33 is when the crash happens

### Logs
You can download FULL logs [here](https://drive.google.com/file/d/1DVeLTV9XhFddJq_0O-aW7MNDiTZlm-8u/view?usp=sharing) (includes syslog referencing sigint kill/ ABRT , includes ant-media-server.log s as well as antmedia-error-timestampped.log and hs_err_pid* log) 

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by USAMAWIZARD** [comment]
"# Problematic frame:
# C  [libjingle_peerconnection_so.so+0x6f3a80]  webrtc::H264BitstreamParser::ParseNonParameterSetNalu(unsigned char const*, unsigned long, unsigned char)+0x4c0
..
..
Current thread (0x00007f95200d1000):  JavaThread "ForkJoinPool.commonPool-worker-117" daemon [_thread_in_native, id=150201, stack(0x00007f8bd8bde000,0x00007f8bd8cde000)]
"

**Comment by burak-58** [comment]
Let me close this. @USAMAWIZARD please reopen if it doesn't fix your issue.
