### ISSUE TITLE
Ant Media server does't work with Cloudflare when Nginx Reverse Proxy is enabled

### ISSUE THREAD

**Issue by elijahwere** [ant-media/Ant-Media-Server#5877]
### Discussed in https://github.com/orgs/ant-media/discussions/5869

<div type='discussions-op-text'>

<sup>Originally posted by **elijahwere** December  1, 2023</sup>
Hello!

I set up Ant Media server and also configured Nginx reverse proxy to whitelist domains that are allowed to stream HLS & DASH: 
Here is the Nginx configuration file:

```
user nginx;
worker_processes auto;
pid /var/run/nginx.pid;
worker_rlimit_nofile 1048576;

events {
    worker_connections 1048576;
    multi_accept on;
    use epoll;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    server_tokens off;
    keepalive_timeout 300s;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # ssl settings
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # logs settings
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      '"$hostname" "upstream: $upstream_addr"';
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # gzip
    gzip on;
    gzip_disable "msie6";
    gzip_http_version 1.1;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/javascript application/x-javascript text/xml application/xml application/xml+rss application/vnd.ms-fontobject application/x-font-ttf font/opentype font/x-woff image/svg+xml image/x-icon;

   ```
 # proxy settings
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_read_timeout 10s;
    proxy_send_timeout 10s;
    proxy_connect_timeout 10s;
     
    #redirect all http requests to https
    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }  

    #Origin Configuration
    #Change {YOUR_DOMAIN} with your fully qualified domain name. 
    server {
            listen 443 ssl;
            ssl_certificate /etc/ssl/example.com/privatekey.pem;
            ssl_certificate_key /etc/ssl/example.com/publickey.pem;
            server_name example.com;

            location / {
              if ($http_referer !~* "^https?://(www\.)?domain-name\.com"){
              return 403;
        }
                proxy_pass http://127.0.0.1:5080;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }
    
    #Dashboard Configuration (To allow access to your AMS dashboard on different port which should be allowed only for specific IPs)
    #Change {YOUR_DOMAIN} with your fully qualified domain name. 
    server {
            listen 4443 ssl;
            ssl_certificate /etc/ssl/example.com/privatekey.pem;
            ssl_certificate_key /etc/ssl/example.com/publickey.pem;
            server_name example.com;

            location / {
                proxy_pass http://127.0.0.1:5080;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }
    }

```
```

Inside Cloudflare, I generated the Origin SSL Certificates: `privatekey.pem` & `publickey.pem`. I added these keys under the `/etc/ssl` directory. I also added the 755 permission on them. 

But What happens is that I am getting the following errors and Nginx doesn't restart:

`2023/12/01 00:12:07 [emerg] 62135#62135: cannot load certificate "/etc/ssl/lucky-wheels.online/privatekey.pem": BIO>2023/12/01 00:13:21 [emerg] 62187#62187: cannot load certificate "/etc/ssl/lucky-wheels.online/privatekey.pem": BIO>2023/12/01 00:22:09 [emerg] 62450#62450: cannot load certificate "/etc/ssl/lucky-wheels.online/privatekey.pem": BIO>`

I requesting anybody with the knowledge on this issue to help me understand how to use how to use Ant Media server with Nginx reverse Proxy with Cloudflare configured.

Thanks 

</div>

**Comment by elijahwere** [comment]
> @elijahwere There's no way you can do it. ant won't let you do this. this is due to license checks.

Would you mind elaborating on this?

**Comment by studentAlanMorgan** [comment]
@elijahwere Ant does not allow proxying and this is written in the installation instructions. The developers can give you a more detailed answer.

**Comment by elijahwere** [comment]
> @elijahwere Ant does not allow proxying and this is written in the installation instructions. The developers can give you a more detailed answer.

You mean Ant Media does not allow Cloudflare? Would you mind sharing a link to this?
Thanks
