### ISSUE TITLE
Refactor the PR related to VIDEO_TRACK_ASSIGNMENT_LIST, GET_BROADCAST

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5878]
Check the code changes on the new conference approach and refactor it with respect to the following item:

- There are some breaking changes, update related documentation, announce them, and update affected sample pages.
    - Changes in sendVideoTrackAssignments function
    -  sending sendRoomInfo callback removed
    -   VIDEO_TRACK_ASSIGNMENT_LIST added
    - VIDEO_TRACK_ASSIGNMENT_CHANGE is not sended anymore
- VIDEO_TRACK_ASSIGNMENT_CHANGE is not used anymore, remove it
- Add null chuck for the broadcast object in processGetBroadcastCommand
- Why  synchronized used inside processGetBroadcastCommand (Add comment or remove it)
- It's not a good idea to call processGetBroadcastCommand if participants are more than hundreds. Optimize this approach.
- Add streamId inside sendTrackListUpdatedMessage
- Add comment why sendVideoTrackAssignments added/used
- Send command field with the messages inside sendTrackListUpdatedMessage function

Source pull-request: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/640

**Comment by burak-58** [comment]
Closed. The related branch is merged.
