### ISSUE TITLE
ONVIF error while connecting ip camera

### ISSUE THREAD

**Issue by ivanmviveros** [ant-media/Ant-Media-Server#5879]
### Short description
My ip camera is not connecting and the server is generating an onvif related error

### Environment

* Operating system and version: ubuntu 20.04
* Java version: 11.0.21
* Ant Media Server version: Ant Media Server Community 2.7.0
* Browser name and version: not related

### Steps to reproduce
1. Add data for new ip camera
2. Click on add

### Expected behavior
Ip Camera connected to ant media server

### Actual behavior
I´m trying to connect the following camera to the ant media server: 
![image](https://github.com/ant-media/Ant-Media-Server/assets/27828058/a5a21124-1232-45c8-8335-e7bafa327f86)

The connection is failing and it is generating the attached logs. I followed the log error and it's generated at:
![image](https://github.com/ant-media/Ant-Media-Server/assets/27828058/f4c6915b-7b6b-4270-961b-f6fe1cfa7be4)

### Logs
https://pastebin.com/bqDNxXHU

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by ivanmviveros** [comment]
Hi @mekya 

Yes, I can help you with connecting to the camera, what should I do?

Error log: [error.log.txt](https://github.com/ant-media/Ant-Media-Server/files/13559564/error.log.txt)

**Comment by ivanmviveros** [comment]
This issue seems to have been reported in #5880, the error log looks the same

**Comment by Mohit-3196** [comment]
Hi @ivanmviveros,
How are you?

I was checking the logs you shared. Can you please also share the complete ant-media-server.log file?
Also, Is this camera available on a Public IP address so that I can reach it? If yes, you can share the access details with me at mohit.dubey@antmedia.io

Let me know when you are available.

Thank you.

**Comment by Mohit-3196** [comment]
Hi @ivanmviveros,
How are you?

Can you please get back to me if you had a chance to see my mail?
Please let me know when you are available.

Thank you

**Comment by Mohit-3196** [comment]
I'm closing this issue now for inactivity.
Please feel free to reopen it if you have any comments or updates.

Thank you.
