### ISSUE TITLE
Android SDK cannot receive data channel when rest method is called with android user streamId  

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5896]
### Short description
User would like to send a message to all users in the conference. This problem is happening in Android.  Alternative approach can be provided to achieve the goal.  

### Environment
* Java version:  17
* Ant Media Server version: 2.8.0-SNAPSHOT

### Steps to reproduce
1.  Web browser joins the conference (Participant A)
2.  Android user joins the conference with Android App (Participant B) - streamId: androidUser
3.  Call [REST API to send data message](https://antmedia.io/rest/#/BroadcastRestService/sendMessage) with streamId: androidUser

### Expected behavior
Participant B(androidUser) should receive the data channel message

### Actual behavior
androidUser does not receive the data channel message. The problem is not happening in iOS.

**Comment by lastpeony** [comment]
I conducted testing on Enterprise Edition 2.8.2 20240201_1142 (test.antmedia.io), as specified in the issue report, and I was unable to reproduce the problem. The Android client (master branch) successfully received data channel messages without any issues.

**Comment by mekya** [comment]
Then I'm closing this issue for now. We can re-open if it does not work for anyone
