### ISSUE TITLE
AMS seems not to detect our GPUs

### ISSUE THREAD

**Issue by yogeshJain0727** [ant-media/Ant-Media-Server#5898]
Short description
AMS seems not to detect our GPUs anymore. nvidi-smi does not show the AMS java process any longer. We see no CUDA errors or init messages in /var/log/ams-server.log.

Environment

Operating system and version: Ubuntu 22.04.03
Ant Media Server version: 2.6.4

Steps to reproduce
We had a running Ubuntu 22.04 installation
Server provider already install NVIDIA driver.
we start streaming but no process show on GPU
Output from nvidia-smi:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A30                     Off | 00000000:84:00.0 Off |                   On |
| N/A   50C    P0              33W / 165W |      0MiB / 24576MiB |     N/A      Default |
|                                         |                      |              Enabled |
+-----------------------------------------+----------------------+----------------------+
| MIG devices:                                                                          |
+------------------+--------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                   Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                     BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                  |                                |        ECC|                       |
|==================+================================+===========+=======================|
|  No MIG devices found                                                                 |
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

dpkg --list | grep cuda
ii  cuda-compat-11-8                           520.61.05-1                             amd64        CUDA Compatibility Platform
ii  cuda-cudart-11-8                           11.8.89-1                               amd64        CUDA Runtime native Libraries
ii  cuda-keyring                               1.0-1                                   all          GPG keyring for the CUDA repository
ii  cuda-toolkit-11-8-config-common            11.8.89-1                               all          Common config package for CUDA Toolkit 11.8.
ii  cuda-toolkit-11-config-common              11.8.89-1                               all          Common config package for CUDA Toolkit 11.
ii  cuda-toolkit-12-2-config-common            12.2.140-1                              all          Common config package for CUDA Toolkit 12.2.
ii  cuda-toolkit-12-config-common              12.3.101-1                              all          Common config package for CUDA Toolkit 12.
ii  cuda-toolkit-config-common                 12.3.101-1                              all          Common config package for CUDA Toolkit.
ii  libcudart11.0:amd64                        11.5.117~11.5.1-1ubuntu1                amd64        NVIDIA CUDA Runtime Library
ii  nvidia-cuda-dev:amd64                      11.5.1-1ubuntu1                         amd64        NVIDIA CUDA development files
ii  nvidia-cuda-gdb                            11.5.114~11.5.1-1ubuntu1                amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                        11.5.1-1ubuntu1                         amd64        NVIDIA CUDA development toolkit
ii  nvidia-cuda-toolkit-doc                    11.5.1-1ubuntu1                         all          NVIDIA CUDA and OpenCL documentation

Expected behavior
AMS uses the GPU

Actual behavior
Even with one stream, we have no GPU usage, but CPU used.

**Comment by yogeshJain0727** [comment]
Did you help us resolve this issue? After downgrading to Driver Version: 515.105.01 and CUDA Version: 11.7, it's still not working. When we start streaming, the GPU usage is still at zero and we are experiencing lagging issues.

**Comment by lastpeony** [comment]
I conducted testing on AWS using the g3.8xlarge instance with CUDA 12.3, and the GPU was utilized successfully. However, after upgrading the machine to g3.16xlarge, the GPUs were not utilized by AMS for some unknown reason.

**Comment by yogeshJain0727** [comment]
@lastpeony  We are facing this issue using Rackbank cloud provider.

Configuration:
- Processor: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
- RAM: 128 GB
- GPU: NVIDIA Corporation GA100GL [A30 PCIe]
- Disk: 480 GB
- OS: Ubuntu 22.04
- Port Speed: 1 Gbps

**Comment by lastpeony** [comment]
This seems like a cuda version issue.
I tested on ubuntu 20.04 cuda 11.8 on 4 gpu amazon instance and it works as expected.
![image](https://github.com/ant-media/Ant-Media-Server/assets/24750845/1480d6eb-6a1b-41d4-8d6e-0511ab66dabf)
(nvidia smi shows differenet cuda version but its 11.8)


Could you please try on a clean instance with 11.8 installed as stated on documentation:
https://antmedia.io/docs/guides/advanced-usage/using-nvidia-gpu/#install-the-cuda-toolkit

**Comment by yogeshJain0727** [comment]
we are now using Ubuntu 22.04.3 LTS with Cuda version 11.7 and Driver Version: 515.105.01
![image](https://github.com/ant-media/Ant-Media-Server/assets/91123237/b07ac662-8f2b-4e99-8566-ac816f8d6eb2)
still, AMS is not connected to GPU.

**Comment by yogeshJain0727** [comment]
any update @lastpeony @burak-58

**Comment by lastpeony** [comment]
@yogeshJain0727 
Can you please install cuda to your instance according to this guide?
https://antmedia.io/docs/guides/advanced-usage/using-nvidia-gpu/#installation-on-ubuntu-1804-2004-and-2204
There should be no problem with correct cuda version on A30

**Comment by lastpeony** [comment]
@yogeshJain0727 

Please let me know if it doesnt work when you test with cuda 11.8
I am closing this issue. Feel free to re-open.

**Comment by yogeshJain0727** [comment]
we try with cuda 11.8. still facing the same issue
