### ISSUE TITLE
Reconnection not working on Multitrack Conference Android SDK 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5899]
### Short description
Reconnection not working on Multitrack Conference Android SDK

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.7.0
* Browser name and version:

### Steps to reproduce
1. With two android devices, using the same roomId and join the conference.
2. Disconnect from the network, wait for 10 seconds and enable internet connectivity.

Application does not respond and gets out of the activity. 

### Expected behavior
Stream should reconnect.

### Actual behavior
Not reconnecting 
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

[Error Logs(Reconnection Tag_ WebSocketHandler).log](https://github.com/ant-media/Ant-Media-Server/files/13577675/Error.Logs.Reconnection.Tag_.WebSocketHandler.log)

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by burak-58** [comment]
It is fixed in v2.10.0. I am closing the issue.
