### ISSUE TITLE
Update the Java Script SDK, WebRTC Publish and Play page creation tutorial document

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5908]
- [ ] [Review and update Java Script SDK](https://antmedia.io/docs/guides/developer-sdk-and-api/sdk-integration/javascript-sdk/) as per the latest improvements in v2.8.0 #5421 
- [ ] [Review and update WebRTC Publish Page Creation tutorial document](https://antmedia.io/docs/guides/developing-antmedia-server/webrtc-publish-page-creation-tutorial/)
- [ ] [Review and update WebRTC Play Page Creation tutorial document](https://antmedia.io/docs/guides/developing-antmedia-server/webrtc-play-page-creation-tutorial/)

**Comment by mustafaboleken** [comment]
It will be handled here: https://github.com/ant-media/ant-media-documentation/issues/250
