### ISSUE TITLE
Live stream recording is out of sync with audio

### ISSUE THREAD

**Issue by farawaysouthwest** [ant-media/Ant-Media-Server#5918]
### Short description
Live stream recordings in `.mp4` are sometimes out of sync with audio to video.

This only happens sometimes with no noticeable patterns. We have roughly 20 live event recordings, and only 2-3 of those are out of sync.

The live stream (with the default liveapp) are always synced just fine, and we also simulcast to YouTube from AMS; the Youtube stream and recording are always in sync as well.

This appears to be the exact issue as reported here: #5134

I can provide video examples if that would help, but we are using all default settings for rtmp streaming and mp4 recording on Community v2.70

### Environment

* Operating system and version: Ubuntu 22.04.3 
* Java version: openjdk version "11.0.21" 2023-10-17
* Ant Media Server version: Community Edition 2.7.0 20231031_0625

 

### Logs
No errors in logs when files are out of sync

**Comment by burak-58** [comment]
Thank you @farawaysouthwest for reporting the issue. Could you please provide some details about the RTMP streaming? For example which tool you are using and provide the settings.

**Comment by farawaysouthwest** [comment]
> Thank you @farawaysouthwest for reporting the issue. Could you please provide some details about the RTMP streaming? For example which tool you are using and provide the settings.

Hi, thank you for the reply! We are using Wirecast following the low latency settings mentioned in your docs.

My org will be streaming tonight and I can get exact settings if that would be helpful?

**Comment by farawaysouthwest** [comment]
I do want to stress, the audio sync is always perfect on the live stream, and only sporadically an issue on the mp4 recording, which would make me think that it is not an issue with the RTMP client/encoder?

**Comment by mekya** [comment]
Hi @farawaysouthwest,

I've update for this issue here

Check this out -> https://github.com/ant-media/Ant-Media-Server/issues/5134#issuecomment-1976224921

PS: Faraway is my other nickname that I use time to time :)

**Comment by burak-58** [comment]
It is fixed with https://github.com/ant-media/Ant-Media-Server/pull/6150

If you encounter the same issue, please feel free to reopen it.

**Comment by green-cats** [comment]
@burak-58 still, same issue, when stream from browser webrtc

**Comment by burak-58** [comment]
Hi @green-cats,
This issue was related to RTMP streaming. Please create a github discussion and provide the details and let our support team help you.
