### ISSUE TITLE
TOTP is not generating for the pre added subscriber

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#5930]
### Short description
The token issue comes when any user wants to add the subscriber in advance before creating a token. The purpose of adding a subscriber in advance is to restrict the undefined streams so only added subscribers would be able to publish the stream.

### Environment
* Ant Media Server version: v2.7.0 and above

### Steps to reproduce
1. Generate a secret key from the web panel by enabling TOTP for publish and play
2. Now use that secret key to add the subscriber using [this API](https://antmedia.io/rest/#/BroadcastRestService/addSubscriber)
3. After adding a subscriber, generate the [TOTP token](https://antmedia.io/rest/#/BroadcastRestService/getTOTP).

### Expected behavior
The token should be generated

### Actual behavior
The token is not generating and giving the below error

```
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Request failed.</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>jakarta.servlet.ServletException: java.lang.IllegalArgumentException: Input is expected to be encoded in multiple of 8 bytes but found: 6
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:409)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1192)
	io.antmedia.filter.IPFilter.doFilter(IPFilter.java:34)
	io.antmedia.filter.ContentSecurityPolicyHeaderFilter.doFilter(ContentSecurityPolicyHeaderFilter.java:32)
	io.antmedia.filter.JWTFilter.doFilter(JWTFilter.java:46)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:331)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158)
	io.antmedia.filter.RestProxyFilter.doFilter(RestProxyFilter.java:134)
```

**Comment by lastpeony** [comment]
The B32 subscriber secret must consist of 8 characters, as outlined in the following link: https://antmedia.io/time-based-one-time-password-totp-makes-streams-secure/. It's important to note that the secret generated through the web panel is 6 characters and serves as a time token secret. It is crucial to distinguish between these two secrets, as they are distinct.

While an internal server error is not typical, it has been fixed with the provided pull request. However, it's worth mentioning that the server's behavior remains as expected behaviour.

https://github.com/ant-media/Ant-Media-Server/pull/5937
