### ISSUE TITLE
Update samples on landing page

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5943]
In the 2.8.0 version, multitrack-conference.html is removed and we should replace all iFrames which uses  multitrack-conference.html to conference.html

**Comment by mekya** [comment]
Hi @mustafaboleken ,

We link multitrack-conference.html  to conference.html. Then, no need to update any iframes. 

Then I'm closing this issue. Please feel free to re-open if you think this is a mistake

Cheers
Oguz
