### ISSUE TITLE
Livestream Livenow application has black screen error from phone (Only sound no picture)

### ISSUE THREAD

**Issue by nhatvuong2504** [ant-media/Ant-Media-Server#5948]
### Short description
Livestream Livenow application has black screen error from phone (Only sound no picture)
I contacted livenow software and was informed that Antmedia's server mechanism was disconnected too quickly, so it was disconnected before receiving data sent from livenow.

### Environment

* Operating system and version: Ubuntu-18.04_64bit
* Java version:
* Ant Media Server version: Community version 2.7.0 20231031_0625
* Browser name and version: All

### Copy steps
I have to use software to prime the stream to trigger images for the video
1. I use the Livenow application on iOS (Software link attached below) to stream Rtmp on Liveapp from the phone's camera but cannot view it (Only hear the sound, no image).
2. Play Rtmp stream on Liveapp from your phone's camera via another app like Streamlab and you can watch normally
3. Go back to using livenow to stream the Rtmp stream on Liveapp from the phone's camera via another app like Streamlab and it can be viewed normally (sometimes flickering, sometimes not).

### Expected behavior
Just want to use livenow for streaming
Stream video m3u8 to view both images and audio

### Actual behavior
- There is sound but sometimes there is no picture? If you use Live and stream first on OBS from your computer, then use Livenow to broadcast, you can watch.

 

### Diary
Livenow software link: https://apps.apple.com/us/app/live-now-live-stream/id1097020890?l=vi?l=vi
__Put the log on [pastebin](http://pastebin.com/) or elsewhere and put the link here: https://pastebin.com/aM1T42mQ

**Comment by burak-58** [comment]
Hi @nhatvuong2504 ,
I have tested with Android version of the application and it works for me. I will try on iPhone. Then I will update.

**Comment by burak-58** [comment]
We have already tried on iPhone 13 and iOS 17.2.1, it worked for us. 
Can you give more details?

**Comment by nhatvuong2504** [comment]
Livenow has updated the new version and resolved the above error.
