### ISSUE TITLE
Larix Grove: dostarczaj ustawienia Larix do wielu urządzeń

### ISSUE THREAD

**Issue by EMIL23GRA** [ant-media/Ant-Media-Server#5963]
https://softvelum.com/larix/grove/

**Comment by EMIL23GRA** [comment]
> https://softvelum.com/larix/grove/

wss://test.antmedia.io:5443/LiveApp/websocket

**Comment by burak-58** [comment]
Hi @EMIL23GRA,
Could you please tell us your issue? How can we help you?

**Comment by mekya** [comment]
Hi @burak-58 and @EMIL23GRA 
I'm closing this issue for the inactivity. Please feel free to re-open.

Cheers
