### ISSUE TITLE
Pick a username

### ISSUE THREAD

**Issue by EMIL23GRA** [ant-media/Ant-Media-Server#5978]
https://bitbucket.org/atlassianid/bb-signup/

**Comment by Mohit-3196** [comment]
Hi @EMIL23GRA 
How are you?

Can you please explain the issue that you are facing?

Thank you.

**Comment by mekya** [comment]
Hi Guys,
Closing this issue for the inactivity. 

Please free free to re-open if there is a problem. 

Regards
Oguz
