### ISSUE TITLE
Scheduling and Handling Playlist

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5984]
A user wants to be able to achieve the below functions in a playlist on the FLY via a UI or script
- [ ] Insert Items in Playlist, 
- [ ] Delete items in the playlist
- [ ] Inquire where in the playlist the current file is playing
- [ ] schedule based on the time when a video file plays

**Comment by burak-58** [comment]
Thank you @Mohit-3196. These are good features to improve playlist feature. I am taking it to the project.

**Comment by Mohit-3196** [comment]
Thank you @burak-58

**Comment by burak-58** [comment]
Merged with this issue:
https://github.com/ant-media/Ant-Media-Server/issues/6125
