### ISSUE TITLE
[Multitrack Arch] Sub-tracks are not cleaned properly.

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5995]
### Short description
When we add someone into another room as sub-track and after sometime we leave the room, sub-track is not cleanup properly.

### Environment

* Operating system and version: Ubuntu 22
* Java version: 17
* Ant Media Server version: v2.8.0-Snapshot

### Steps to reproduce
1. Join the Room1 (multitrack conference room) as Participant A
2. Join the Room2 (multitrack conference room) as Participant B
3. Add Participant A as a sub-track into Room2 using [Rest API](https://antmedia.io/rest/#/BroadcastRestService/addSubTrack).
4. Validate that you see Participant A in both rooms.
5. Participant A clicks the leave button.
6. Check sub-tracks of the Room1 and Room2 using [Rest API](https://antmedia.io/rest/#/BroadcastRestService/getBroadcast).
7. You will see that sub-track of the Participant A is still in the Room1's sub-track list.

### Expected behavior
Sub-tracks must removed as soon as publishers stop publishing.
### Actual behavior
Sub-tracks are not cleaned properly.

**Comment by burak-58** [comment]
We are not using 2 rooms scenario any more. So closed.
