### ISSUE TITLE
Audio is not clear (jerky) when playing the stream on YouTube after pushing a WebRTC stream to the YouTube endpoint while there's no issue with RTMP publish. 

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#5998]
### Short description
When publishing a WebRTC stream and then simulcasting to YouTube by using the YouTube rtmp endpoint, there is a clear jerk in the audio when playing on YouTube.
There's no issue when publishing a stream with RTMP.

### Environment
* Java version: 11 and 17
* Ant Media Server version: v2.7.0 and v2.8.0 snapshot
* When using v2.6.4, sound is fine

### Steps to reproduce
1. Publish a WebRTC stream using the sample WebRTC publish page.
2. Add YouTube rtmp endpoint to the stream for simulcating.
3. Play the stream on YouTube

### Expected behavior
The audio on YouTube should be clear.
### Actual behavior
The audio when playing stream on YouTube is not clear and there is some jerkiness in the audio.

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by Matt95** [comment]
Any update or workaround for this issue other than downgrading to prior versions?

**Comment by lastpeony** [comment]
@Matt95 
I confirmed the problem on 2.8.3 and fixed it. After discussing it with the tech team probably there will be a PR.
