### ISSUE TITLE
Speaker Name Is Not Received Properly

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6013]
From time to time, some of the participant's name is not set until another participant joins into the room

Reproduced scenario:

- Set the maximum number of video track assignments to 20 on the server side and the client side.
- Join Room 1 as Participant 1, Participant 2, Participant 3, Participant 4, Participant 5.
- Participant 1 is pinned by Participant 2.
- Participant 6 joins into the Room 1.
- Participant 2 unpinning the Participant 1.
- Participant 2 can see the video and hear the audio of the Participant 2 but cannot see the name.

**Comment by mekya** [comment]
Hi @mustafaboleken ,

I think this issue has been resolved. If so, could you please close it?

Cheers
Oguz

**Comment by mustafaboleken** [comment]
It's resolved after the circle version 2.9.0
