### ISSUE TITLE
Stream Start Failed with IP camera RTSP link

### ISSUE THREAD

**Issue by JaiSaro** [ant-media/Ant-Media-Server#6028]
rtsp://192.168.144.25:8554/main.264

I have mentioned the RTSP link above, but I can't broadcast my IP camera RTSP link to the ant media server and I am getting the below-mentioned error. When I have tried with VLC the above link is working fine.

Stream Start Failed.
Error: Stream is already active. It's already streaming or trying to connect

I have checked with the test RTSP link from https://rtsp.stream/ it working fine.

Could anyone help with this issue

https://github.com/orgs/ant-media/discussions/6027

**Comment by burak-58** [comment]
Thank you for the report. Lets discuss the issue on the [discussions ](https://github.com/orgs/ant-media/discussions/6027) first. My friend has responded it. If we decide that there is a software issue, we can convert that discussion to a github issue. So I am closing this one now.
