### ISSUE TITLE
Stream with extension .m3u8 or .mp4 does not work directly with JWT token

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6043]
### Short description
The HLS stream with the.m3u8 and MP4 file with the.mp4 extension does not play directly using the JWT token, while it works fine using other token types like the one-time token, etc.

### Environment
* Ant Media Server version: v2.7.0 and above

### Steps to reproduce
1. Enable Play with JWT token
2. Enable HLS streaming
3. Publish stream on the server
4. Generate the JWT token
5. Play the HLS stream using m3u8 URL and JWT token, like (http://IP-address-or-domain:port/Application_Name/streams/stream_id.m3u8?token=tokenId)

### Expected behavior
The stream should work fine

### Actual behavior
Stream does not work

**Comment by lastpeony** [comment]
I tested this on my end and for mp4 files on {webapp}/streams directory JWT token security works as expected and i was able to download the mp4 file.

For m3u8 files JWT security also works but jwt should be passed to the each .ts request.
If the player is not configured to pass token on each .ts request it wont work. It will only download the m3u8 file.
So the player used should be configured to pass JWT to each request.
