### ISSUE TITLE
Write script to publish and play streams 24x7 in staging environment - Part 2

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6049]
Publish and Play Intermittent 
Start:
   - Open headless browser publish live stream with random streamId
   - Open another tab and play the stream 
   - Check that stream is alive and there is one player
   - After 1 minute 
       - Stop playing
       - Stop publishing
   - Check that there is no crash log and there is no heapdump. If there is a crash or any error, send message to "alert" channel in slack
   - Goto 'Start' and repeat the again

**Comment by yashtandon113** [comment]
It is completed, and I am currently testing it on [my repository](https://github.com/yasht0105/24-7-staging/actions
) with GitHub Actions. The selenium script is running on the development server.

Some suggestions would be required to make it more efficient.
