### ISSUE TITLE
service inactive/dead after install?

### ISSUE THREAD

**Issue by petarb1988** [ant-media/Ant-Media-Server#6054]
I have installed antmedia community edition on an Ubuntu 20.04.6 server.
I used this quick start guide:
https://antmedia.io/docs/quick-start/

I am stuck immediately after the installation which seemingly went well, except the service status is inactive/dead.
I've tried starting/restarting it but the outcome is always the same:

● antmedia.service - Ant Media Server
     Loaded: loaded (/etc/systemd/system/antmedia.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2024-01-24 11:15:57 UTC; 286ms ago
    Process: 3370134 ExecStart=/usr/bin/env ${JAVA_HOME}/bin/java -Dlogback.ContextSelector=org.red5.logging.LoggingContextSelector -cp ${ANTMEDIA_HOME}/ant-media-server-service.jar:${ANTMEDIA_HOME}/conf -Djava.security.debug=failure -D>
   Main PID: 3370134 (code=exited, status=0/SUCCESS)

Jan 24 11:15:56 flom-dev2 systemd[1]: Started Ant Media Server.
Jan 24 11:15:57 flom-dev2 systemd[1]: antmedia.service: Succeeded.

**Comment by mustafaboleken** [comment]
Hi @petarb1988 

Please upload server logs which is located under /usr/local/antmedia/log Then we can find what is the problem.

**Comment by petarb1988** [comment]
@mustafaboleken here is a zip file with the logs:
https://mega.nz/file/kBs3XADD#j8QBqdz7y55LXBL7eZh82wPwLPVRiOSOR1qEzQhQyiE

**Comment by petarb1988** [comment]
it was an issue with folder permissions, I had to set the /tmp folder to 777 so antmedia could create the /tmp/vertx-cache folder and use it

**Comment by mustafaboleken** [comment]
Hi @petarb1988,

I saw the folder permission in logs and checking our installation script to be sure why script cannot cover the permission. It's good to hear that it's solved. Btw, we publish version 2.8.0 today, you can take a look it. It uses Java 17, if you consider to install don't forget to update Java version, btw.
