### ISSUE TITLE
Android ant media SDK is not not working

### ISSUE THREAD

**Issue by yogeshkaharmis** [ant-media/Ant-Media-Server#6055]
hello
when I build sample ant media android sdk project, it is install but when I am using screen share feature it is not publish the screen and showing me "you need permissions before" but I have given all required permission.
please help me, what I am doing wrong. 
you can see image.
![Screenshot_20240124-165611_Ant Media WebRTC Sample App](https://github.com/ant-media/Ant-Media-Server/assets/138681998/7cbb8d61-f7a8-4362-8f57-0c1bc66769f0)

thanks you.

**Comment by yashtandon113** [comment]
Hi @yogeshkaharmis 
Please make sure that you are using the latest Android SDK from [here](https://github.com/ant-media/WebRTC-Android-SDK).

I checked the screen share sample on my end and it seems to be working for me. Please make sure that you allow all permissions like Camera, microphones, phones, and Nearby devices.

**Comment by yogeshkaharmis** [comment]
thank you 
It work but there are one permission (Bluetooth permission) it is not ask but it is required for streaming.
please check it.

**Comment by burak-58** [comment]
Thank you let us check.

**Comment by yogeshkaharmis** [comment]
hello
you check and solve the issue.
please tell me.
thank you

**Comment by yashtandon113** [comment]
@yogeshkaharmis 
I checked by deploying the SDK on my mobile device but I did not see any Bluetooth permission required. The only permissions that were required on my device were cameras, microphones, phones, and nearby devices.

Could you please share a screenshot where you see the option for Bluetooth permission?
