### ISSUE TITLE
Null Pointer Exception on Concurrent Hash Map

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6066]
It occurred by six enterprise users.

It's reported by New Relic

Version: 2.8.0 EE

Stack Trace:

`{
  "errorDetail": "java.lang.NullPointerException: Cannot invoke \"Object.hashCode()\" because \"key\" is null\n\tat java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)\n\tat java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)\n\tat io.antmedia.enterprise.webrtc.WebRTCAdaptor.tryToChangeQualityMuxer(WebRTCAdaptor.java:280)\n\tat io.antmedia.enterprise.webrtc.WebRTCAdaptor.applyStatBasedABR(WebRTCAdaptor.java:268)\n\tat io.antmedia.enterprise.webrtc.WebRTCAdaptor.adaptStreamingQuality(WebRTCAdaptor.java:250)\n\tat io.antmedia.enterprise.webrtc.WebRTCClient.lambda$startStreaming$16(WebRTCClient.java:1763)\n\tat io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1040)\n\tat io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1016)\n\tat io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:335)\n\tat io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:328)\n\tat io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:206)\n\tat io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:1034)\n\tat io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)\n\tat io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n",
  "instanceId": "6e511a11-2b80-43f3-90a1-6588e3716b95",
  "instanceType": "Enterprise",
  "instanceVersion": "2.8.0",
  "newrelic.source": "api.logs",
  "timestamp": 1706451445335
}`

**Comment by burak-58** [comment]
Resolved with https://github.com/ant-media/Ant-Media-Server/issues/6094.
