### ISSUE TITLE
Upgrade from 2.7.0 Community to 2.8.1 Community

### ISSUE THREAD

**Issue by NightHawkATL** [ant-media/Ant-Media-Server#6073]
### Short description
Trying to update using standard practice of downloading current version and running install script (Update with keeping settings). Update completes and says that the server is up and running but I am no longer able to access the server through the standard ports and the existing IP.

### Environment

* Operating system and version: Proxmox LXC Ubuntu 20.04
* Java version: whatever is provided with 2.7.0
* Ant Media Server version: 2/7.0 community
* Browser name and version: Firefox 122.0

### Steps to reproduce
1. Download ant-media-server-2.8.1-community.zip
2. extract and run install.sh file (sudo ./install_ant-media-server.sh -i ant-media-server-community-2.7.0.zip -r true)
3. Wait for install to finish and see completion message
4. Try to access server using local IP and port (my case, it is http://10.0.2.3:5080 or http://ams.home.arpa:5080)
5. Get message from browser as if the server is not running and is not accessible.

### Expected behavior
Update to complete and server to be accessible.

### Actual behavior
install/update completes but server does not restart correctly and is not accessible.

 

### Logs
https://drive.google.com/file/d/1W4HzzhKXDuFVUHx0DVfIi-mfREEqOVA5/view?usp=sharing

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by muratugureminoglu** [comment]
HI @NightHawkATL 

When I investigated your log file, everything seems fine. Could you please run the following commands and share the output? 

1. ```ps -aux |grep antmedia```
2. ```netstatl -tpln``` or ```sudo lsof -i -P -n | grep LISTEN``` 

It would also be great if you could share the log files under /var/log/antmedia/

**Comment by NightHawkATL** [comment]
I will do this tomorrow and report back. Thanks for looking into this for me.

**Comment by NightHawkATL** [comment]
> 1. ps -aux |grep antmedia

Sorry for taking so long to reply. Here are my results from the commands that you wanted me to run.

1. chris@AMS:~$ ps -aux |grep antmedia
   chris       2093  0.0  0.0   3312  1152 pts/3    S+   11:05   0:00 grep --color=auto antmedia

2a. chris@AMS:~$ netstat -tpln
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -
tcp6       0      0 ::1:25                  :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -

2b. chris@AMS:~$ sudo lsof -i -P -n | grep LISTEN
systemd      1            root   43u  IPv6  5587077      0t0  TCP *:22 (LISTEN)
systemd-r   89 systemd-resolve   13u  IPv4  5586977      0t0  TCP 127.0.0.53:53 (LISTEN)
master     334            root   13u  IPv4  5587604      0t0  TCP 127.0.0.1:25 (LISTEN)
master     334            root   14u  IPv6  5587605      0t0  TCP [::1]:25 (LISTEN)

It seems as if the update is disabling the port it should listen on. Before the update, I am able to access the WebUI without issue. Even a reboot doesn't change the access issue.

Here is a link to all the logs in the specified folder: https://drive.google.com/file/d/1--oE9LNYKcIfDpgH12VQANromuG45VbF/view?usp=sharing

**Comment by muratugureminoglu** [comment]
Hi @NightHawkATL 

As far as I can see from the logs, Java17 (Ant Media Server version 2.8.* now uses Java 17) is not installed on your system. 

The following items can occur this issue.

- Used old installation script while upgrading the Ant Media Server
- If your source.lists are broken, Java may not have downloaded and installed.

Could you please first download the latest installation script from here: https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh and try to install with it?

**Comment by NightHawkATL** [comment]
Ok, I just completed the update to 2.8.2 CE and I did use the new installer script. It was my fault for not getting the new script. Could I suggest that on the release page that you link to the updated installer script and mention to download it so that people don't have to jump to your website to follow the update/upgrade steps? Just a friendly reminder kind of thing.

**Comment by muratugureminoglu** [comment]
Hi @NightHawkATL 

Thank you very much for your feedback. Actually, when you call the installation script with the `-u` parameter [1], it automatically downloads the latest install script. Maybe we should make this feature a bit more visible. If you have any other feedback, we'd be happy to hear it. :)

[1] https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L52

Cheers.

**Comment by mekya** [comment]
Hi @muratugureminoglu,
When I read the following comment, i don't understand what it means. Could you please make it easy to understand?

  echo "  -u -> Update Ant Media Server new installation script. Default value is false"
 https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh#L52

**Comment by muratugureminoglu** [comment]
Hi @NightHawkATL 

Yes, it is absolutely true.
