### ISSUE TITLE
Webrtc stream published and played from iPhone is rotated by 90 degrees.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6099]
### Short description
When publishing a stream with WebRTC and playing with WebRTC using an iPhone device with adaptive streaming enabled, the playback is rotated by 90 degrees.

### Environment
* Ant Media Server version: AMS v2.7.0, AMS v2.8.2
* Browser name and version: Chrome on iOS

### Steps to reproduce
1. Enable adaptive streaming
2. Start a WebRTC stream using the sample WebRTC publish page
3. Play the stream with WebRTC

### Expected behavior
The stream should play in the same orientation.

### Actual behavior
The stream is rotated by 90 degrees. 

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
I've sent a PR to the enterprise side to fix the problem in all cases
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/674

I figure out that the number`13` can be changed `a=extmap:13 urn:3gpp:video-orientation` so I've provided more generic solution that removes the line that contains `urn:3gpp:video-orientation`.

I think no need to provide fix on the SDK side anymore. 

FYI
