### ISSUE TITLE
Android SDK APP not responding on reconnection

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6100]
### Short description
When the re connection is triggered or network is switched application does not respond and eventually leads to crash

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Publish in Conference using Android sdk
2. turn of wifi
3. turn on wifi
4. wait for re connection and it will crash

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by burak-58** [comment]
https://github.com/ant-media/WebRTC-Android-SDK/pull/74
