### ISSUE TITLE
Composite layout not working in media push 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6109]
### Short description
Composite layout not working in media push 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
Start the Composite Layout
Call the REST Method below to let Ant Media Server with the stream id you specified in the start method. You should pass the url, width and height in the body.

curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "https://<ant-media-server-domain>/<your-webapp-name>/rest/v1/media-push/start"  -d '{"url": "https://<ant-media-server-domain>/<your-webapp-name>/composite_layout.html?roomId=<room-name>&publisherId=<composite-layout-publisher-id>", "width": 1280, "height": 720}'

Call the REST Method below to update the layout on the fly.

curl -i -X POST -H "Accept: Application/json" -H "Content-Type: application/json" "https://<ant-media-server-domain>/<your-webapp-name>/rest/v2/broadcasts/<composite-layout-publisher-id>/data"  -d '{"streamId":"streamId1","layoutOptions": {"canvas": {"width": 640,"height": 640},"layout": [{"streamId": "<room-participant-id>","region": {"xPos": 20,"yPos": 0,"zIndex": 1,"width": 200,"height": 200},"fillMode": "fill","placeholderImageUrl": "https://cdn-icons-png.flaticon.com/512/149/149071.png"}]}}' 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @mustafaboleken,
Composite Layout problem has been resolved or about to be resolved?  Then this is duplicate issue. If so, could you please close this issue?

Cheers
Oguz

**Comment by mustafaboleken** [comment]
Hi @mekya,

Although it's not clear what is not working in the issue description, the composite layout is working right now and the only know issue is about audio tracks.
It's in [pull request](https://github.com/ant-media/Plugins/pull/102).

So, I'm closing this one.
