### ISSUE TITLE
The streams takes longer to load on the dashboard and some time does not even load 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6116]
### Short description
when trying to play a stream from dashboard  some time streams takes long time to load and does not even load some times. 

### Environment

* Ant Media Server version: 2.8.3

### Steps to reproduce
1.  publish a stream 
2. play from dashboard

https://github.com/ant-media/Ant-Media-Server/assets/47350008/58d48df7-74cd-42a1-b1eb-d5db7b0b6b08

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

I cannot watch the mp4 file you've uploaded 

It is generally related to the key frame interval. If there is something happens all the time, we can investigage.

I'm closing this issue. Feel free to re-open if you think it's a general problem.
