### ISSUE TITLE
when i set videoCallEnabled false I cannot connect

### ISSUE THREAD

**Issue by nguyenquynh201** [ant-media/Ant-Media-Server#6129]
Because I don't use a camera, I set videoCallEnabled = false , but I have the problem of being disconnected, I tried it in my program and in your example, they all have the same problem, you can see the image below. i am using WebRTC-Sdk-Android
<img width="1324" alt="image" src="https://github.com/ant-media/Ant-Media-Server/assets/80728170/9cd4dd09-a60f-4baf-b9a1-ffd6e1a992a5">

**Comment by burak-58** [comment]
Resolved as mentioned here:
https://github.com/orgs/ant-media/discussions/6142
