### ISSUE TITLE
Check the latest image/installation file for vulnerabilities and fix.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6134]
- Create a docker image with the latest AMS EE using Ubuntu 22.04
- Check and fix the major and critical vulnerabilities

**Comment by mekya** [comment]
Hi @lastpeony ,

About the jackson-databind 2.9.6 vulnerability

https://github.com/ant-media/Ant-Media-Server/issues/6122#issuecomment-2011956864

FYI

**Comment by lastpeony** [comment]
I updated some packages and fixed most of the vulnerabilities.
Before mentioned PRs:
134 vulnerabilities found in 30 packages
  UNSPECIFIED  1   
  LOW          18  
  MEDIUM       43  
  HIGH         53  
  CRITICAL     19  
After the PRs:
49 vulnerabilities found in 24 packages
  LOW       17  
  MEDIUM    28  
  HIGH      4   
  CRITICAL  0
