### ISSUE TITLE
Re streaming to RTMP endpoint not working 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6137]
### Short description
when trying to re stream to any rtmp endpoint like youtube the  server does not send data to the endpoint 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:2.8.2
* Browser name and version:

### Steps to reproduce
1. create stream on the server 
2.  edit rtmp endpoint for the stream and add youtube rtmp endpoint 
3. stream will not start  on youtube 

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
I have tested the scenario using version 2.8.3 with SRT, RTMP publish streams from OBS and WebRTC publish through browser. In all publishing scenarios, AMS successfully relayed the stream to the YouTube RTMP endpoint, and the stream was viewable on YouTube without any issues.

**Comment by burak-58** [comment]
It seems that, issue is solved with version v2.8.3. So, I am closing this. If you encounter with the same issue, feel free to reopen it.
