### ISSUE TITLE
ERROR logs when publishing RTMP from obs on Windows

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6138]
### Short description
when publishing an rtmp stream from  ( OBS  version > 30.0.2 ) on windows , I am able to see a a lots of repeating error messages on error logs on server , These messages are filling up the storage and eventually crashing the server.  
This issue is not reproducible on Linux environment 

(h264_bitstream_parser.cc:187): Streams with pred_weight_table unsupported.
(h264_bitstream_parser.cc:187): Streams with pred_weight_table unsupported.
(h264_bitstream_parser.cc:187): Streams with pred_weight_table unsupported.
(h264_bitstream_parser.cc:187): Streams with pred_weight_table unsupported.

### Environment

* Operating system and version: Windows 10
* Java version: 
* Ant Media Server version: 2.8.2
* OBS VERSION : 30.0.2
* Browser name and version:

### Steps to reproduce
1. install OBS version  30.0.2 on windows machine
2. add a new video source as a browser source and load a youtube video in it. 
3. add rtmp endpoint of AMS and start streaming.
4. open the antmedia-error.logs and see the repeating error logs 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

It's about encoder settings, use `baseline` and set `tune`to `zerolatency`, then this log will be removed. 

WebRTC does not support `pred_weight_table` in bitrate. 

So I'm closing this issue

Cheers
Oguz
