### ISSUE TITLE
Android SDK issues

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6149]
### Issue 1
In the Android SDK publish sample, a default random streamId is generated, but even if you put a custom streamId like **test**, etc., it does not work as expected. The stream is still published with a random stream ID.

### Steps to reproduce
1. Deploy the Android SDK on your device
2. Open the publish sample and put your own streamId, like "test."
3. Start publishing the stream

### Expected behavior
On server, the stream should be published with **test** streamId

### Actual behavior
The stream is still publishing with an auto-generated streamId.

### Issue 2
The resolution of stream publishing with an Android SDK is not as expected. For example, in general, the resolution should be like 480x640 or as per device resolution but currently the resolution is like 544x544.

[{"videoHeight":544,"videoWidth":544,"videoBitrate":0,"audioBitrate":96000,"videoCodec":"H264"}]

### Steps to reproduce
1. Deploy the Android SDK on your device
2. Open the published sample
3. Start publishing the stream

### Expected behavior
The resolution should be as per the device's resolution.

### Actual behavior
The resolution is a 1:1 aspect ratio, like 544x544.

###Suggestion
It would be great if Max resolution, framerate, Max bit rate, etc. types of properties could be set directly in the Android SDK settings activity for ease of testing.

**Comment by burak-58** [comment]
Here is the PR for Issue1:
https://github.com/ant-media/WebRTC-Android-SDK/pull/64

**Comment by burak-58** [comment]
Issue2 cannot be veirfied. It seems that it is working as expected:



![Image](https://github.com/ant-media/Ant-Media-Server/assets/39169933/bfca1b34-54f4-416e-aa90-cc4437c2a114)
