### ISSUE TITLE
React Native SDK Referance Doc & Developer Guide

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6151]
Add missing function and general refactor of the React Native SDK documentation.

**Comment by yashtandon113** [comment]
Previously, samples were not working with npm package 1.0.6 after new changes. After that, me and @mustafaboleken had a meeting together and uploaded the new version 1.7.0 to NPM. Now all samples are working as expected.

I will further work on improving the document.
