### ISSUE TITLE
useOriginalWebRTCEnabled property doesn't work.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6159]
### Short description
When setting `useOriginalWebRTCEnabled=true` and using ABR, the server only produces the adaptive streams and not the original bitrate.

### Environment
* Ant Media Server version: v2.8.2 and 2.8.3 snapshot

### Steps to reproduce
1. Set useOriginalWebRTCEnabled=true
![Screenshot 2024-03-05 222522](https://github.com/ant-media/Ant-Media-Server/assets/86982446/f8d8ea9c-a83b-40e9-a8fe-48088b4de4a0)

2. Enable Adaptive streaming
![Screenshot 2024-03-05 222540](https://github.com/ant-media/Ant-Media-Server/assets/86982446/4a419389-9129-4f30-ac4f-89ca47b48dbd)

3. Publish a WebRTC stream using the sample WebRTC publish page.

### Expected behavior
When playing the stream there should be two bitrates and resolution available to play. One original resolution of 480p and another with 720p.
### Actual behavior
Only 720p resolution is available to play.
![Screenshot 2024-03-05 222650](https://github.com/ant-media/Ant-Media-Server/assets/86982446/93664fd2-3ffd-4534-8adc-fab81565747a)

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
hi @Mohit-3196 ,
This is duplication for the following issue https://github.com/ant-media/Ant-Media-Server/issues/2587
