### ISSUE TITLE
HLS Viewers Count showing incorrect results

### ISSUE THREAD

**Issue by KristianColville1** [ant-media/Ant-Media-Server#6162]
### Short description
We recently updated our server from version 2.7.0 to 2.8.2
We were testing creating filtered streams so we could build a feature to toggle between cameras for customers with multiple cameras on our server. We simply tested it on a stream on our server and that was fine. The next day we viewed incorrect hls and web rtc stats on our origin server for the stream which was used when we were testing a filtered stream.
![image](https://github.com/ant-media/Ant-Media-Server/assets/95403588/44f9cb57-ecae-44ce-8294-6baa5f6b6264)

### Environment

* Operating system and version: Linux ubuntu 22.04.4 LTS
* Java version: Java 17
* Ant Media Server version: version 2.8.2
* Browser name and version: firefox, chrome etc

### Steps to reproduce
1. pick a random RTMP stream
2. create a filtered stream using this as the output only 1 is needed
3. delete the filtered stream after 12 hours and the RTMP stream will slowly increase viewer count for

**Comment by Mohit-3196** [comment]
Hi @KristianColville1 ,
How are you?

May I know how you play the HLS streams?
Is it via the embedded player, play.html, or do you play the .m3u8 files directly?

Thank you.

**Comment by mekya** [comment]
Hi Guys,
I'm closing this issue for the inactivity. 

Please feel free to re-open if you encounter the problem

Cheers
Oguz
