### ISSUE TITLE
Time taken between `publishStarted` and `Track is added` is high for iOS SDK.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6164]
The time taken between `publishStarted` and `Track is added` is high for iOS SDK.
e.g., 
27.02.2024 13:26:00.4930 AntCallLog publishStarted 63dce956c30542684f1b7b63
27.02.2024 13:26:08.0910 AntCallLog Track is added with id:ARDAMSv63dceca0c30542684f1b7b68

Steps 
1. Let the first attendee join the conference room from web panel
2. Let the second attendee join the conference room from iOS 

Expectation:
Second attendee should see the first attendee in a couple of seconds

Actual:
It takes about 8 secs that second attendee sees the first attendee

**Comment by mekya** [comment]
Hi @Mohit-3196 ,
Could you please update the issue to give more information about the issue? Because I don't understand if it's the first time I see this problem. 

Cheers
Oguz

**Comment by mekya** [comment]
Hi @Mohit-3196,
I've sent another PR to make it stable even if the user joins subsequently. Please let the user know about it and test it. 

TBH, there is another opportunity on the server side to let it start faster. I mean, it decreases the start time for all clients(js, android, ios, etc.). 
You can create an issue for that. The title can be "Improve/Replace SubTrackPoller to attach subtracts to WebRTCClients faster"
