### ISSUE TITLE
[React Native SDK] Error in WebRTC Play

### ISSUE THREAD

**Issue by vincemavill** [ant-media/Ant-Media-Server#6167]
React native error in WebRTC Play where says "Cannot read property 'toURL' of undefined"
line 55 from https://github.com/ant-media/WebRTC-React-Native-SDK/blob/main/example/src/Play.tsx

i am using WebRTC Multitrack Conference for publishing stream.
"@antmedia/react-native-ant-media": "^1.0.6",
"react-native": "0.73.4",

JDK: 17
NODEJS: 18.17.1

![image (8)](https://github.com/ant-media/Ant-Media-Server/assets/18587242/1556a3c4-bfa3-45ad-bc8d-5b7566d33171)

**Comment by mustafaboleken** [comment]
Hi @vincemavill 

Thank you for the report. I'm adding it to the project so we schedule it to check and fix the issue.

**Comment by vincemavill** [comment]
hi @mustafaboleken it turns out that the 1.0.6 is not compatible with the example components in the github.
i switch to 1.0.5 and its all working fine.

**Comment by mustafaboleken** [comment]
Thanks for letting me know. Then, we will update the examples with 1.0.6

**Comment by mustafaboleken** [comment]
Hi @vincemavill 

We just release version 1.0.7 It contains multitrack conference and fix for playback issue. You can take a look at it.

**Comment by vincemavill** [comment]
@mustafaboleken maybe you can help me to this matter sir
https://github.com/ant-media/Ant-Media-Server/issues/6194

**Comment by mustafaboleken** [comment]
Hi @vincemavill,

I'm just assigning it to myself. I will add the feature this week.

**Comment by mekya** [comment]
Hi @mustafaboleken ,
I think you already fix this issue. So I've assigned it to you and we'll close it in the meeting.

If it's a mistake, let us know in the meeting

**Comment by mustafaboleken** [comment]
Hi @mekya,

Yes, It's solved. We can close during the meeting.
