### ISSUE TITLE
Attaching Transcription text into VoD file via FFMPEG

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#6187]
As discussed, we need to enable VoD files with closed captions.
Transcription files are already available externally and the only thing is required to use FFMPEG externally as Workaround to attach those files to the VoD file.

**Comment by yashtandon113** [comment]
The below FFMPEG command can be used to map the **Webvtt** transcription file to the VOD file.

`ffmpeg -i input.mp4 -vf subtitles=captions.vtt output.mp4`
