### ISSUE TITLE
Stop function does not work as expected in React Native SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6190]
### Short description
Despite calling the **adaptor.stop** function to terminate the connection, I am still encountering errors in the callback error handler.

Steps to reproduce
1. Start publishing by calling adaptor.publish(roomId)
2. Stop publishing by calling adaptor.stop(roomId)
3. But after stopping, the callback error keeps throwing errors for that room.

###Expected behavior
Once the host stops the broadcast, the callback should also stop. 

###Actual behavior
Once the app starts the broadcast, then the host stops the broadcast, and then we use the below code: 
adaptor.stop(roomId);

But after this, the callback always throws an error:

callbackError >>  no_active_streams_in_room {"command": "error", "definition": "no_active_streams_in_room", "room": "65f1a02a1980acedde5e4721"}

It uses a lot of memory and batteries. It is also causing app crashes.

**Comment by MaZZly** [comment]
This might be related to "Problem 2" from https://github.com/ant-media/Ant-Media-Server/issues/4071#issuecomment-2012348181

**Comment by mustafaboleken** [comment]
Hi @MaZZly 
It can be. I will work on React Native at the weekend. I hope these issues will solved until Monday :)
