### ISSUE TITLE
AntMedia Flutter SDK >= 1.3.0  Cannot Play Live Stream with Token

### ISSUE THREAD

**Issue by zinminoo298** [ant-media/Ant-Media-Server#6196]
# Play Live Stream failed after updating to AntMedia Flutter SDK >= 1.3.0

### Short description
After updating to SDK 1.3.0 and 1.3.1, I cannot play live stream with token anymore.

### Environment

* Dart SDK 3.0.0
* AntMedia Flutter SDK  >=1.3.0

Previously I used SDK 1.2.1 and tested play method with stream id and token. It works perfectly fine. In SDK >= 1.3.0, I cannot play live stream with token anymore. I found out that there is no token parameter set for play method in SDK >= 1.3.0. 

I'm curious if there's a method to include a token parameter in the play function, or if there are plans for an update that would resolve this matter.

![image](https://github.com/ant-media/Ant-Media-Server/assets/31659954/7ef74fd3-d8b0-4b3e-8410-84a1b49591ba)

**Comment by burak-58** [comment]
Thank you @zinminoo298 for the report. I will add this to plan. We will fix it soon.

**Comment by mustafaboleken** [comment]
Hi @zinminoo298 

Thanks for the report. We are planning to remove the auto-connect inside sdk approach actually. So you can easily pass any parameter you wanted. I will create a new pull request today.

**Comment by zinminoo298** [comment]
I am glad to hear that. I am looking forward to future changes.

**Comment by mustafaboleken** [comment]
Hi @zinminoo298,

When I checked the old version, I realized that the token is passed as room id parameter, that why I override it unintentionally. I added a separate parameter instead of the old approach. 

https://github.com/ant-media/WebRTC-Flutter-SDK/pull/47/files

I will create a separate pull request for the new usage of the SDK.

**Comment by zinminoo298** [comment]
Hi @mustafaboleken , Thank you so much.
