### ISSUE TITLE
is facebook streaming availabe on the free community ???

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6201]
is facebook streaming availabe on the free community ???
cause when i add facebook RTMP it wont connect , can you advice please

**Comment by yashtandon113** [comment]
@brixxnatt 
Yes, re-streaming to Facebook is available in the community edition of Ant Media Server as well. But right now, there is an issue streaming to Facebook in the current version. Here is the related GitHub issue: https://github.com/ant-media/Ant-Media-Server/issues/5961

**Comment by brixxnatt** [comment]
is there any fix soon ?

**Comment by burak-58** [comment]
Hi @brixxnatt,
It is in our plan. We will provide a fix soon. You can follow the issue state in github. Let me close this issue.
