### ISSUE TITLE
Conference sample not working in flutter SDK.

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6205]
### Short description
Conference sample not working in flutter SDK.

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. build a conference sample and join the room
2. join room from another device 
3. flutter client cannot see other participants . ( other participants can see the flutter client )

### Expected behavior
flutter client should also be able to see the other participants. 

### Actual behavior
flutter client cannot see other participants
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mustafaboleken** [comment]
Hi @USAMAWIZARD,

Which Ant Media Server version that you tested and in which platform(Android, iOS or Web)?
Burak abi and I tested last week and everything works fine at that time.

**Comment by USAMAWIZARD** [comment]
I have tested it with android , 2.8.3 ( both with multitrack an stream based ) , I tested it today again.

**Comment by lpickford-pixelbeard** [comment]
Just commenting to say that the PR for this also fixes an issue we're having with playing a stream normally, where on `1.2.1` there's no issue, and on `^1.3.x` the video stream won't play.

**Comment by mustafaboleken** [comment]
Hi @lpickford-pixelbeard,

Thank you very much for letting us know. I will raise this PR to be reviewed and merged asap.
