### ISSUE TITLE
Bluetooth speaker while conference and broadcast not working in React Native 

### ISSUE THREAD

**Issue by Nardeep** [ant-media/Ant-Media-Server#6206]
In conference , when we are connecting Bluetooth speaker to phone at that time  bluetooth mic and speaker is not working

**Comment by yashtandon113** [comment]
@Nardeep 
Thanks for creating the issue. We have already created the below issue for the Bluetooth audio issue with the React Native SDK.
https://github.com/ant-media/Ant-Media-Server/issues/6146

So we are closing this issue by marking it as a duplicate.
