### ISSUE TITLE
Streams from iOS devices are rotated 90° when viewed on Firefox

### ISSUE THREAD

**Issue by MaZZly** [ant-media/Ant-Media-Server#6208]
### Short description

When an iOS stream (browser doesn't matter) streams to Firefox browser (OS doesn't matter) it shows up rotated 90° 

### Steps to reproduce
1. Create a conference room (WebRTC)
2. Start a stream from iOS
3. View the stream from a Firefox browser

### Expected behavior
Video orientation to be correct

### Actual behavior
Video is rotated 90°

 ### Possibly related issues ###
https://github.com/ant-media/Ant-Media-Server/issues/5044
https://github.com/ant-media/Ant-Media-Server/issues/4024

**Comment by MaZZly** [comment]
Just out of curiosity, I tested the same thing with another WebRTC room (LiveKit Meet), and there the image is the correct orientation when streaming from iOS to Firefox

@mustafaboleken can you get this prioritized for the next sprint as well? Seems like a thing that should work out of the box. I'm guessing some metadata about rotation is not handled correctly when videostream is passed on? :thinking:

**Comment by mustafaboleken** [comment]
Hi @MaZZly 

We already have an active pr for this issue. The problem is video rotation information inside sdp (`a=extmap:13 urn:3gpp:video-orientation\r\n'`). If you remove rotation inside sdp then Ant Media Server handle the rotation problem but if you have send it, it looks rotated. 

We are working on a premenant fix on the server side but until that time, we remove that information in sdk level. https://github.com/ant-media/StreamApp/pull/445/files

**Comment by MaZZly** [comment]
@mustafaboleken which version/tag of `webrtc_adaptor` should we install to get this temporary workaround until the fixed server is released? :)

**Comment by mustafaboleken** [comment]
Hi @MaZZly,

mekya fixed it on the server side and it will included in next week's release but, let me deploy a test version on npm for you. I will send it in 2 hours.

**Comment by mustafaboleken** [comment]
Hi @MaZZly,

I had to work on some work so, I couldn't send version to you earlier, sorry about that. You can use [2.8.3-SNAPSHOT-2024-Apr-02-17-56](https://www.npmjs.com/package/@antmedia/webrtc_adaptor/v/2.8.3-SNAPSHOT-2024-Apr-02-17-56) until we release the v2.9.0

**Comment by MaZZly** [comment]
@mustafaboleken, that tagged version doesn't seem to be working; iOS videos are still rotated when viewed on Firefox.

When is the server release with the fix coming? :)

**Comment by mustafaboleken** [comment]
Your dependency should look like this `"@antmedia/webrtc_adaptor": "2.8.3-SNAPSHOT-2024-Apr-02-17-56",` If there is `^ `character, if uses the latest version, not the exact version, maybe it is the issue. 
Anyway, we are planning to release it in 1 week.

**Comment by mustafaboleken** [comment]
Hi @MaZZly 

Ant Media Server v2.9.0 is just released. You can install and test it.
