### ISSUE TITLE
RTCPeerConnection has audio tracks added (and enabled) even when initialized with audio:false

### ISSUE THREAD

**Issue by MaZZly** [ant-media/Ant-Media-Server#6209]
### Short description

We initialize the JS SDK like:
```typescript
this.webRTCAdaptor = new WebRTCAdaptor({
    websocket_url: antWSUrl,
    mediaConstraints: {
        video: videoConstraints,
        audio: false,
    },
    ....
})
```

When inspecting `this.webRTCAdaptor.remotePeerConnection` senders and receivers we see `MediaStreamTrack` of type `kind: audio` that are  `enabled: true`... 

### Steps to reproduce
1. Initialize SDK with `audio: false`
2. start publishing & subscribing to video streams
3. Check the RTCPeerConnection

### Expected behavior
The `RTCPeerConnection`s should not have any  `MediaTrack` where `kind: audio` when we have explicitly disabled it in the beginning.

### Actual behavior

The `RTCPeerConnection`s have `MediaTrack`s where `kind: audio` and `enabled: true` are added..

**Comment by MaZZly** [comment]
@mustafaboleken can you clarify if this is the intended behavior due to e.g. WebRTC, or if it is a bug?

**Comment by mustafaboleken** [comment]
As far as I know, it's not an intended behavior but let me discuss with my collegues. I will let you know.

**Comment by MaZZly** [comment]
@mustafaboleken, thanks; I'm thinking this is quite a critical bug if audio/video tracks are still being sent even when not initialized to be...

**Comment by MaZZly** [comment]
@mustafaboleken has there been any progress on this one?

**Comment by mustafaboleken** [comment]
Hi @MaZZly,

I hope you are doing well.
I have some findings that I wanted to discuss with you in order to discuss a couple of things related to React Native and this issue. 
Do you have some time next week for a meeting? After the discussion, I wanted to create pull requests.

**Comment by MaZZly** [comment]
Yeah sure, still quite open for next week. Send an invite to my email I'll let you know if it works :)

**Comment by mekya** [comment]
Hi @mustafaboleken,

What's the current status of this issue?

Cheers
Oguz

**Comment by MaZZly** [comment]
This also happens in the multitrack conference where we are listening to `obj.stream.onremovetrack` to handle streams stopping..

```typescript
if (info === 'newTrackAvailable') {
    obj.stream.onremovetrack = (event: MediaStreamTrackEvent) => {
        console.log(event.track.type);
    }
}
```

**Comment by mustafaboleken** [comment]
Hi MaZZly,

I hope you are doing well. Let me explain how the multitrack conference works. Whenever you join a room with more than 1 participant, you will have 2 RTCPeerConnection. One is for publishing to the server, and the other is for playing the room (main track). I tested the scenario that you raised and saw that, if I make the audio false, then I don't have an audio track for publishing but I have audio tracks for the peer connection which is used by play functionality even if all the participants are video-only participants. So, it's an expected behavior.

**Comment by mustafaboleken** [comment]
I'm closing this issue due to the inactivity. If you need to discuss it in the future, feel free to reopen the issue.
