### ISSUE TITLE
Maximum number of keepalive connections?

### ISSUE THREAD

**Issue by ozgurkazancci** [ant-media/Ant-Media-Server#6210]
Optimizing nginx for Reverse TLS proxy for owncast - I'd like to ask;

What's the maximum number of keepalive connections the Ant-Media-Server web server can maintain?

Thanks.

**Comment by burak-58** [comment]
Hi @ozgurkazancci,
Thank you for your question. Let me convert this to a github discussion so that community can follow the discussion.
