### ISSUE TITLE
Bad Recording Quality

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6227]
### Short description
It seems that in some cases, live streams are poorly recorded, with missing packets or bad encoding

Attached samples.  
short.mp4 is a 30 second sample, with no reencoding involved, as captured by the antmedia regular recording process
short_reencodedh264.mp4 is the same video passed through an ffmpeg command to reencode in h264 ( command used was "ffmpeg -i short.mp4 -vcodec libx264 shortreencoded.mp4") 

Notice that the original recording displays green artifacts and pixelation, overall very bad quality. 
The reencoded version is no longer displaying green artifacts, but very strong pixelation and no quality improvement.

What is very important to note here is that the livestream itself looked perfect while it was running, as we actively watched it and these artefacts or pixelation issues were not visible then, but the resulting recording is completely different. 

We are using antmedia enterprise edition 2.7.0, webrtc publish and play, and this pixelation/artefacts issue was present when we were using older versions too. This particular stream was published from the following user agent, in case that might be important for you to debug
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
and with the following media constraints
let mediaConstraints = {
    video : {
        width: { min: 320, ideal: 1280, max: 1280 },
        height: { min: 180, ideal: 720, max: 720 },
        aspectRatio: { ideal: 1.7777777778 },
    },
    audio : true
};

Running "FFPROBE" on the 30 second original video we get the following info:
"ffprobe short.mp4"
ffprobe version 2.8.15 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.1

  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'short.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:30.00, start: 0.000000, bitrate: 1095 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x720, 1043 kb/s, 41.26 fps, 50 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

The video quality issues are visible when videos are played in a browser player or in a local player like VLC
Videos available here https://antmedia.freshdesk.com/a/tickets/120291

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.7.0
* Browser name and version:

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

I see the point. If there is packet drop and network is bad, AMS cannot do anything to increase the quality of the recording. 

What I recommend is to make sure there is no problem in WiFi connection where computer is connected. Secondly, if there is still a problem, user can use some service like [AWS Global Accelerator](https://aws.amazon.com/global-accelerator/) to connect to the backend in the fastest way if they use AWS.  

PS: We can help/configure the AWS Global Accelerator for the user

FYI

**Comment by mekya** [comment]
I think this issue may be related to this one https://github.com/ant-media/Ant-Media-Server/issues/6246

**Comment by mekya** [comment]
Duplicate https://github.com/ant-media/Ant-Media-Server/issues/6246
