### ISSUE TITLE
Audio does not outputs from Bluetooth for Android SDK.

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#6232]
### Short description
sound does not comes from Bluetooth device even if the Bluetooth is connected 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.8.2
* Browser name and version:

### Steps to reproduce
1. build a play example and try to play the stream
2. connect the Bluetooth headphones 
3. audio does not route through Bluetooth headphones  it comes from android

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
See this pr for fix:
https://github.com/ant-media/WebRTC-Android-SDK/pull/102
