### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring 

### ISSUE THREAD

**Issue by mdsohelmia** [ant-media/Ant-Media-Server#6233]
W: http://installrepo.kaltura.org/repo/apt/debian/dists/naos/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://installrepo.origin.kaltura.org/repo/apt/debian naos InRelease: The following signatures were invalid: AD4200615722734CBBE6C52FE7EEDECAA1174D5E

**Comment by muratugureminoglu** [comment]
Hi @mdsohelmia 

This is not an issue on the Ant Media Server side. It says that the GPG signature of the repository you installed earlier in the Ubuntu/Debian operating system you are using is invalid. I suggest you comment/remove the lines related to kaltura.org in /etc/apt/sources.list. 

Regards.
