### ISSUE TITLE
Write doc for load testing

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#625]

**Comment by arnoldcui** [comment]
https://github.com/ant-media/Ant-Media-Server/wiki/Preparation-of-Test-Server-and-Running-Tests
In step 4.
The command should be 
sudo docker run -p:8090 -w "/home/antmedia/test/TestScriptAndTools-master/Tools/" antmedia/test java -jar loadtester-0.0.1-SNAPSHOT-spring-boot.jar
