### ISSUE TITLE
Release new version 2.9.0

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#6250]

**Comment by brixxnatt** [comment]
No desciption ?? is it Released ?

**Comment by brixxnatt** [comment]
mekya is this a release ?

**Comment by mustafaboleken** [comment]
Hi @brixxnatt,

Yes, it's a new release and we are currently working on it. If everything goes well, it will released in 1 week.

**Comment by brixxnatt** [comment]
nice , mostafa thank you , any elease note of what changle log please
thanks

**Comment by mustafaboleken** [comment]
It will be automatically generated after we tag the release. So, I also don't know :D

**Comment by mustafaboleken** [comment]
Hi @brixxnatt 

Version 2.9.0 just released. You can check the changelogs from https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.9.0

**Comment by brixxnatt** [comment]
thanks , how can i update , just will run the command again right , it will not delete my old settings and files ?
