### ISSUE TITLE
Memory leak on Ant Media Server

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6258]
It's reported through the unexpected shutdown logs.

Ticket URL: https://antmedia.freshdesk.com/a/tickets/124063

Stack trace: `WARNING: The web application [WebRTCApp] appears to have started a thread named [vert.x-worker-thread-7] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
 java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
 java.base@17.0.10/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
 java.base@17.0.10/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
 java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
 java.base@17.0.10/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
Mar 29, 2024 2:36:36 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
`

**Comment by mekya** [comment]
Hi @mustafaboleken 
It's a false alarm. These thread pools are managed by the core of the server.

Please re-open the issue if you think there is a bug there.

Cheers
Oguz
