### ISSUE TITLE
Fit To Screen

### ISSUE THREAD

**Issue by vincemavill** [ant-media/Ant-Media-Server#6266]
Unable to find a fit to screen or full screen camera configuration for the rtc_view of @antmedia/react-native-ant-media

**Comment by vincemavill** [comment]
@mustafaboleken hello sir, maybe you can help me again with this matter. I appreciate your support.

**Comment by mustafaboleken** [comment]
Hi @vincemavill

Our development team is on vacation this week due to the Ramadan Fest. I will check the configuration next week and let you know.

**Comment by vincemavill** [comment]
@mustafaboleken good day sir, any updates?

**Comment by mustafaboleken** [comment]
Thanks for the reminder, let me check and get back to you today. @vincemavill

**Comment by mustafaboleken** [comment]
Hi @vincemavill 

I just created a PR for it. To be honest, I cannot reproduce it with my own devices. If you test it before the review, it would be great.

**Comment by vincemavill** [comment]
@mustafaboleken i already review the code, works good. thank you

**Comment by mustafaboleken** [comment]
@vincemavill thanks for checking, I will talk with my teammates and after. their review, we will release a new release.
