### ISSUE TITLE
Add ID3 parse feature to embedded player

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#6278]

**Comment by lastpeony** [comment]
Seems like videojs does not support parsing id3 data.
see this issue:
https://github.com/videojs/http-streaming/issues/1421

**Comment by lastpeony** [comment]
Found the solution. PR sent.

**Comment by mekya** [comment]
Thank you for the fix @lastpeony 

This issue can be closeable in the sprint meeting @burak-58
