### ISSUE TITLE
[Fakeehcare] Data Channel Messages not delivered properly

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6290]
Server start buffering the data channel messages and deliver them around 1.5 mins

Server Logs: https://antmedia.freshdesk.com/a/tickets/125425

**Comment by mustafaboleken** [comment]
The reason was founded. The fix is in the work in progress status.

**Comment by burak-58** [comment]
We have a design change so this is not an issue anymore.
