### ISSUE TITLE
Failed to stop thread

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6298]
It's reported by unexpected shutdown logs.

Version: Ant Media Server 2.9.0 Community Edition
Ticket URL: https://antmedia.freshdesk.com/a/tickets/124728 and https://antmedia.freshdesk.com/a/tickets/125145

Stacktrace: 

`WARNING: The web application [live] appears to have started a thread named [vert.x-eventloop-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.10/sun.nio.ch.EPoll.wait(Native Method)
 java.base@17.0.10/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
 java.base@17.0.10/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
 java.base@17.0.10/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
 io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
 io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:883)
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
 io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
 io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
Apr 10, 2024 12:08:33 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads`

`WARNING: The web application [live] appears to have started a thread named [vert.x-worker-thread-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
 java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
 java.base@17.0.10/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
 java.base@17.0.10/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
 java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
 java.base@17.0.10/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
Apr 10, 2024 12:08:33 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
`

**Comment by mekya** [comment]
Hi @mustafaboleken ,

These are false alarms because these thread pools are managed across the core of the server.

I'm closing this issue and feel free to re-open if you think it's a bug. 

Cheers
Oguz
