### ISSUE TITLE
Multiaccess to the applications

### ISSUE THREAD

**Issue by VideoEditismyLife** [ant-media/Ant-Media-Server#6302]
**Is your feature request related to a problem? Please describe.**

I cant add users more than 1 application. I can give full access or just 1 app.

**Describe the solution you'd like**

I can add 2-3-4 apps to one user with a different access level

**Describe alternatives you've considered**

no

**Additional context**

https://drive.google.com/uc?id=1-rf7yyc5-WGqxkCJwThThYiGWG29lLi9

**Comment by burak-58** [comment]
Thank you @VideoEditismyLife. I add the feature request in plan. We will implement it in an appropriate time.

**Comment by mekya** [comment]
Hi @VideoEditismyLife,

Thank you for the query. I'd just want to add something. If this is something important for you, let's reach out to us contact@antmedia.io so we can understand your needs better and set the priority of this issue correctly.

Cheers
Oguz
