### ISSUE TITLE
Adaptive bitrate m3u8 file missing from the subfolder while uploading HLS files to the bucket in real time

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6304]
### Short description
The adaptive.m3u8 file is missing from the subfolder (if using the subFolder in broadcast) when using the HTTP endpoint feature to upload the HLS files simultaneously to the S3 bucket.

### Environment
* Ant Media Server version: v2.9.0

### Steps to reproduce
1. Enable adaptive bit rate in the application settings
2. Enable the [s3 upload via HTTP end point settings](https://antmedia.io/docs/guides/recording-live-streams/s3-integration-http-forwarding/#uploading-hls-files-to-the-s3-bucket-in-real-time)
3. Create stream using API and define the subFolder
4. Publish the stream on the server

### Expected behavior
The subfolder (under streams folder) created on the S3 bucket should have the **streamId_adaptive.m3u8** file as well.

### Actual behavior
In actuality, the streamId_adaptive.m3u8 file generates outside of the subfolder

**NOTE:** This behavior seems to be working fine when HLS files are uploaded to the bucket after the stream stops following the standard S3 upload feature.

**Comment by lastpeony** [comment]
Fix:
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/691
