### ISSUE TITLE
Conference room related GET API calls are not working as expected

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6315]
### Short description
The conference-related APIs are not working with the latest version 2.9.0 of Ant Media Server.

### Environment
* Ant Media Server version: v2.9.0

### Steps to reproduce
1. Join the conference room1 using the conference.html page
2. Try calling APIs like [get conference room object](https://antmedia.io/rest/#/default/getConferenceRoom), [get conference list](https://antmedia.io/rest/#/default/getConferenceRoomList), [get room info](https://antmedia.io/rest/#/default/getRoomInfo) etc. 
3. Also, try to [get the broadcast object](https://antmedia.io/rest/#/default/getBroadcast) for the generated conference room ID (room1); it gives incomplete data like no start time, duration, etc.

### Expected behavior
The APIs should work fine to get conference related details.

### Actual behavior
Currently, APIs are not giving the required data.

**Comment by mekya** [comment]
Hi @yashtandon113 

Partially, It's related to this one
https://github.com/ant-media/Ant-Media-Server/issues/5755

>Also, try to [get the broadcast object](https://antmedia.io/rest/#/default/getBroadcast) for the generated conference room ID (room1); it gives incomplete data like no start time, duration, etc.

I think it's a design decision. Please let me know if I'm wrong. @burak-58 @mustafaboleken 

Cheers
Oguz

**Comment by mustafaboleken** [comment]
Hi @mekya,

After we moved to the main broadcast conference room and removed the old conference-room approach, it's an expected issue. You are right, we need to decide how we can provide such statistics.

**Comment by burak-58** [comment]
I have also added some implementation to set start time into the main track Broadcast Object.
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/689

**Comment by mekya** [comment]
Hi @burak-58 ,

The PR is merged. I'm closing the issue and keeping it "In Progress". We can move it to "Done" in the meeting to let everyone see it's closed.
