### ISSUE TITLE
Feature to Add logo to a  a LIVE EVENT

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6322]
Feature to Add logo to a  a LIVE EVENT
PNG logo , with  size cuttomization and to tell where to put it , what corner

**Comment by burak-58** [comment]
Thank you @brixxnatt for the suggestion. I think you can do it filter plugin. Please check this blogpost. There is also a logo adding filter example.

https://antmedia.io/discover-the-filter-plugin/

**Comment by brixxnatt** [comment]
when I run the Curl command in the given folter plugin i get this  
<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not allowed IP</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/10.1.19</h3></body></html>r

**Comment by burak-58** [comment]
It is because of REST security. Please check this documentation.
https://antmedia.io/docs/guides/developer-sdk-and-api/rest-api-guide/securing-rest-apis/
