### ISSUE TITLE
Make SSL Install Easily in Auto-Managed Solution

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#6329]

**Comment by mekya** [comment]
Hi @muratugureminoglu ,

I've tried this implementation in the PR. It gives syntax error in template file when I try to use in AWS CloudFormation. 

Please check it out.

Cheers

**Comment by mekya** [comment]
I've moved this review task to this issue -> https://github.com/ant-media/Ant-Media-Server/issues/6089 because they are related. So I think this issue becomes duplicate and it is closable
