### ISSUE TITLE
Save MP4 files to a separate directory

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#6334]
If “Record Live Streams as Mp4” is enabled in the Application settings, It would be nice if there be an option to record to a different directory

![Screenshot from 2024-05-20 13-52-49](https://github.com/ant-media/Ant-Media-Server/assets/6337605/ac74d767-ce75-4403-b43a-9697e43ddee3)

Example:

./streams/stream_id/*.ts files
./streams/vod/stream_id/*.mp4

**Comment by mekya** [comment]
Hi @muratugureminoglu,

Could you please make it clear? 

Cheers
Oguz
