### ISSUE TITLE
Why logs errors  is accumilating RAM  , 

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6339]
Why logs errors  is accumilating RAM  ,

**Comment by brixxnatt** [comment]
each error is adding 100MB to RAM , accumilating

**Comment by burak-58** [comment]
Hi @brixxnatt,
Thank you for reporting. Can you give me some more info? Which logs causes RAM usage? Please provide me a step by step reproduce scenario.

**Comment by brixxnatt** [comment]
if for example 2 people send  stream to the same RTMP , in case of error , it happen when 2 people send rtmp stream at the same time to the same rtmp , 1 is connected and the other is trying always to connect , i know this should not happen then 2 people send rtmp to the same place at the same time , but in anyway it should give error , not acccumilating the RAM with the error untill server crash full of RAM .

**Comment by lastpeony** [comment]
@brixxnatt 
Hello, Do you observe increase on JVM Heap Memory on web panel dashboard which leads to crash, or only system memory?

**Comment by lastpeony** [comment]
> if for example 2 people send stream to the same RTMP , in case of error , it happen when 2 people send rtmp stream at the same time to the same rtmp , 1 is connected and the other is trying always to connect , i know this should not happen then 2 people send rtmp to the same place at the same time , but in anyway it should give error , not acccumilating the RAM with the error untill server crash full of RAM .

Hello,
I am trying to reproduce this problem on a clean cloud instance but i could not manage to reproduce. I am using ffmpeg and publishing a mp4 file repeatedly to the same streamId with RTMP and getting 
I/O error from ffmpeg.
I do not observe 100 MB ram increase.
This is how i publish:
```
import subprocess
import time

def run_ffmpeg_stream(command):
    process = subprocess.Popen(command, shell=True)
    return process

def stop_ffmpeg_stream(process):
    # Terminate the FFmpeg process
    process.terminate()
    process.wait()

def main():
    ffmpeg_command = "ffmpeg -re -i mysync.mp4 -codec copy -f flv rtmp://myIp/LiveApp/teststream"

    for i in range(1000):
        print(f"Starting stream {i + 1}/10")
        
        process = run_ffmpeg_stream(ffmpeg_command)
        print("Streaming started")

        time.sleep(5)

        stop_ffmpeg_stream(process)
        print("Streaming stopped")

        time.sleep(1)

    print("Completed 1000 streaming cycles")

if __name__ == "__main__":
    main()
```
Can you please share your exact instance specs and how you exactly publish?

I need to reproduce this on clean AMS installation.

**Comment by lastpeony** [comment]
Hello @brixxnatt 
We could not reproduce this problem on our end. 
Due to inactivity i am closing the issue.
Feel free to re-open the issue. We can also schedule a meeting and check this issue in your env together.
emre.guney@antmedia.io
