### ISSUE TITLE
 av_interleaved_write_frame(): Broken pipe

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6346]
[2024-05-20 18:17:28.85612] [ERROR] [Encoder] av_interleaved_write_frame(): Broken pipe
[2024-05-20 18:17:28.85645] [ERROR] [Encoder] Error writing trailer of rtmp://stream.s1sream.me/stream1/stream: Broken pipe
[2024-05-20 18:17:28.86162] [ERROR] Encoder write error: broken pipe
[2024-05-20 18:17:28.86174] [DEBUG] Out of source loop
[2024-05-20 18:17:28.86188] [ERROR] [Decoder] av_interleaved_write_frame(): Broken pipe
[2024-05-20 18:17:28.86637] [ERROR] [Decoder] Error writing trailer of pipe:: Broken pipe

i can stream from another platfrom to any rtmp , even restreamer.io and youtube and facebook , but when i try to stream to AMS , it gives the above error

**Comment by burak-58** [comment]
Thank you for the report. We will check it soon.

**Comment by mustafaboleken** [comment]
Hi @brixxnatt 

I'm trying to reproduce the issue. Can you answer the following questions?

- What is your Ant Media Server version?
- How you are sending the RTMP stream? Which platform you are using?

**Comment by brixxnatt** [comment]
Since ant media server dont have 24/7 playlist that we can also stream to , I am using ffplayout to send RTMP to AMS , I am using lastest Comunity edition .

**Comment by mustafaboleken** [comment]
Thanks for the information, I will test with the ffplayout.

**Comment by mustafaboleken** [comment]
Hi @brixxnatt,

I just can run it. Can you please try with the following configuration?

`-c:v:0 libx264        -crf 23        -x264-params keyint=50:min-keyint=25:scenecut=-1        -maxrate:0 1300k        -bufsize:0 2600k        -preset faster        -tune zerolatency        -profile:v Main        -level 3.1        -c:a:0 aac        -ar:0 44100        -b:a:0 128k        -flags +global_header        -f flv  rtmp://xxx.antmedia.io/LiveApp/xxx`

**Comment by brixxnatt** [comment]
ok , i wish ant media server have its own user based playout like ffplayout  , i will try your parameters  ,

**Comment by brixxnatt** [comment]
you config works fine , thank a lot , now idea what you did or added ,  this is mine original  

-c:v libx264 -crf 19 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 3000k -bufsize 3000k -preset faster -tune zerolatency -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -f hls -hls_time 10 -hls_list_size 4 -hls_flags append_list+delete_segments+omit_endlist -hls_segment_filename /usr/share/ffplayout/public/live/stream2-%d.ts /usr/share/ffplayout/public/live/stream2.m3u8

**Comment by mustafaboleken** [comment]
Thank you for providing the parameters. I will test them and inform you about which parameter is causing the problem and why it is happening.

**Comment by mustafaboleken** [comment]
I checked the non-working script and the problem is getting 2 outputs simultaneously causes the issue. If we use the FFplayout with single output and with the following script, it will work as expected.

`-c:v:0 libx264        -crf 23        -x264-params keyint=50:min-keyint=25:scenecut=-1        -maxrate:0 1300k        -bufsize:0 2600k        -preset faster        -tune zerolatency        -profile:v Main        -level 3.1        -c:a:0 aac        -ar:0 44100        -b:a:0 128k        -flags +global_header        -f flv  rtmp://xxx.antmedia.io/LiveApp/xxx`
