### ISSUE TITLE
Compilation fails when using ant_media_flutter ^1.4.0 after upgrading dependencies

### ISSUE THREAD

**Issue by mikkomcmenamin** [ant-media/Ant-Media-Server#6366]
### Short description
Compilation fails when running the Flutter sample app after upgrading dependencies 

### Environment

* ant_media_flutter: ^1.4.0
* Dart version:  Dart 3.4.0  
* Flutter version:  Flutter 3.22.0 • channel stable
* Operating system and version: MacOS 14.0
* Browser name: Chrome 

### Steps to reproduce
1. Clone Flutter conference sample https://github.com/ant-media/WebRTC-Flutter-SDK/tree/main/example/Conference 
2. Run flutter pub upgrade
3. Build & Run on Chrome 

### Expected behavior
Sample app should compile 

### Actual behavior

Compilation fails because of:
JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>

### Logs

../../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:119:50: Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Iterable' is from 'dart:core'.
        for (final track in _srcObject!.jsStream.getVideoTracks()) {
                                                 ^
../../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:125:50: Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Iterable' is from 'dart:core'.
        for (final track in _srcObject!.jsStream.getAudioTracks()) {
                                                 ^
../../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:167:50: Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Iterable' is from 'dart:core'.
        for (final track in _srcObject!.jsStream.getVideoTracks()) {
                                                 ^
../../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:175:50: Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Iterable' is from 'dart:core'.
        for (final track in _srcObject!.jsStream.getAudioTracks()) {
                                                 ^
Failed to compile application.

**Comment by neetable-mahira** [comment]
facing same issue

**Comment by mustafaboleken** [comment]
Hi @mikkomcmenamin and @neetable-mahira 

Thanks for the report. We will schedule it according to teams availability.

**Comment by lastpeony** [comment]
Fix:
https://github.com/ant-media/WebRTC-Flutter-SDK/pull/52
You can test the fix after flutter pub get
Run example/SampleProject because it points to the SDK

Other examples will get the ams sdk from repo.

**Comment by mustafaboleken** [comment]
Hi @mikkomcmenamin and @neetable-mahira 

I just merged @lastpeony's pull request. You can use version 1.4.1 to test it. You can let us know if it works for you or not.

**Comment by mekya** [comment]
A new version is available 1.4.2. 

Please try and feel free to re-open the issue if it does not work for you.
