### ISSUE TITLE
WebRTC adaptor does not use the turn server passed to it's constructor from embedded web player

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6370]
### Short description
When we pass a TURN server to the embedded-player.js it does not use the turn server passed to its constructor and uses the default STUN server.

### Environment
* Java version: 17
* Ant Media Server version: 2.9.0

### Steps to reproduce
1. Pass the TURN server to the embedded-player.js
2. Play the stream using the play.html
3. Check the webrtc internals

### Expected behavior
The webrtc adaptor should use the ice server passed to its constructor.

### Actual behavior
The webrtc adaptor does not use the ice server passed to its constructor but continues to use the default STUN server.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
Fix:
https://github.com/ant-media/videojs-webrtc-plugin/pull/25

**Comment by mekya** [comment]
Hi @lastpeony,

Thank you for the fix. 

To make this fix available in the Ant Media Server, we need the following things as well. 

1. Update the Web-Player for the version in videojs-webrtc-plugin. 
2. Update the StreamApp for the new version of Web-Player

At this time, I'm going ahead and creating the versions and PRs to let you see it. If you already know, then accept this as a reminder.  
Next time, I expect you to make it ;)

Thank you again for your contributions. 

Let me know if you have any questions or want to add some things

Cheers
Oguz

**Comment by mekya** [comment]
Just want to add one thing, I've also added test codes for the fix. 
Check it out
https://github.com/ant-media/videojs-webrtc-plugin/pull/25/files#diff-dbd99cd221621a3bab7c898fb51a53d2bfbf88eb6bb495ccaea81222837cf18d

**Comment by mekya** [comment]
This issue can be closeable in the sprint meeting @burak-58
