### ISSUE TITLE
interval in javascript webplayer

### ISSUE THREAD

**Issue by impactotecnologico** [ant-media/Ant-Media-Server#6373]
### Short description

When I set the start and end parameters in javascript webplayer it works but only reproducing video for realtime, is not using "start" and "end" parameters

### Environment

* Operating system and version: Ubuntu 20
* Java version: openjdk version "17.0.10" 2024-01-16
* Ant Media Server version: Enterprise Edition 2.9.0 20240405_1755
* Browser name and version: Chrome 124.0.6367.208 (Build oficial) (arm64)

### Steps to reproduce
1. Add to some web project https://www.npmjs.com/package/@antmedia/web_player
2. Use webplayer by following standart configuration
3. Configure webplayer setting start and end parameters with values previous than current timestamp

```

const playerOptions = {
        httpBaseURL: streamingUrl,
        streamId: streamId,
        autoPlay: autoPlay,
        mute: true, 
        is360: false, 
        token: token,
        start: 1716998828,
        end: 1716999428,
      };

      const embeddedPlayer = new WebPlayer(playerOptions, videoContainerRef.current);

      embeddedPlayer
        .initialize()
        .then(() => {
          embeddedPlayer.play();
          onLoad?.(true);
        })
        .catch((error) => {
          console.error('Error while initializing embedded player: ' + error);
          onLoad?.(false);
        });
```

### Expected behavior

Playing video stream for specific start and end interval

### Actual behavior

Playing video stream for current timestamp instead given interval

When I inspect network in browser, I see at websocket at wss://[MY SERVER]:5443/LiveApp/websocket?target=edge

```
{
    "command": "play",
    "streamId": "MY ID HERE",
    "token": "MY TOKEN HERE",
    "room": "",
    "trackList": [],
    "subscriberId": "",
    "subscriberCode": "",
    "viewerInfo": ""
}
```

So, is not sending the start and end parameters, I think this is why the player is reproducing only current live stream instead interval

**Comment by mekya** [comment]
Hi @impactotecnologico 

I think there is a misunderstanding about this issue. I mean embeddedplayer cannot work in this way. 

We may provide an alternative solution for you for HLS playback. I'll put it to the plan to ask help from one of my colleague to give you the instructions. 

Cheers
Oz

**Comment by yashtandon113** [comment]
Hi @impactotecnologico

Check out the below documentation to play the HLS stream for the defined interval.
https://antmedia.io/docs/guides/playing-live-stream/hls-playing/#hls-play-for-a-given-time-interval

Please feel free to ask if you have any questions.

**Comment by yashtandon113** [comment]
@impactotecnologico 
I am closing this issue for the inactivity. Please feel free to reopen the issue if you have any questions.
