### ISSUE TITLE
getStats is not usable/useful in multitrack conference..

### ISSUE THREAD

**Issue by MaZZly** [ant-media/Ant-Media-Server#6375]
### Short description

If we want to e.g. track the bitrate of a streamer, this is not possible with the multitrack since all tracks bitrates seem to be summed up into one combined value.

### Steps to reproduce
1. In a multitrack conference room, join with 2 people and start streams on both
2. enable stats for the room
3. Try to figure out if one of the streamers is not currently streaming (e.g. when mobile phone goes to home screen, or bad network)

### Expected behavior
Some way to get the stats for individual tracks and not the combined stream

### Actual behavior
getStats() returns the stats for the combined stream, not for individual tracks,

**Comment by MaZZly** [comment]
I also noticed when testing a bit around this:

When a track is removed (i.e., the streamer closes down their tab), the `currentIncomingBitrate` temporarily goes to the negative, even if there are other streamers in the room. (with 1000ms polling of stats, haven't tested others).

It should probably not go into negative values...

**Comment by burak-58** [comment]
Hi @MaZZly,
You are right. I also need the same. I am adding this to plan.

**Comment by mustafaboleken** [comment]
Hi @MaZZly,

I made some changes in the getStats method. Now you match the stream id with track id and match stats with the track id. You can check the following screenshot.

<img width="784" alt="Screenshot 2024-07-10 at 13 10 03" src="https://github.com/ant-media/Ant-Media-Server/assets/23143596/f0e191b6-b516-4f79-9d40-29e6cf9cfc85">
<img width="784" alt="Screenshot 2024-07-10 at 13 10 09" src="https://github.com/ant-media/Ant-Media-Server/assets/23143596/3a948835-ed34-4740-b92f-31b6f578e739">

**Comment by MaZZly** [comment]
@mustafaboleken is it possible to also get `currentIncomingBitrate` property/functionality on the items under `inboundRtpList` ?

**Comment by mustafaboleken** [comment]
Hi @MaZZly,

currentIncomingBitrate function cannot be called directly but you can copy the calculation here and use it with inboundRtpList all you need to do is storing the total byte and the last timestamp, we provide both of them.

https://github.com/ant-media/StreamApp/blob/master/src/main/js/peer_stats.js#L242
