### ISSUE TITLE
ABR: only 5 simultaneous streams despite free resources

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#6389]
### Short description
We have two GPUs installed (16GB + 8GB), which was enough to run ~10 simultaneous streams with ABR in version 2.4.3. Currently, with v2.9.0, we can have only 4-5 simultaneous streams:
* adding a 5th stream causes plenty of _blocked thread_ messages in the log file and a progressive memory build-up
* adding a 6th streams causes even more _blocked thread_ logs and increases the speed of the memory build-up
   * log file contains reports of big queues of unprocessed frames (over 2000 frames)
* after a few minutes over 40% of RAM is used and an attempt to add a 6th stream ends with an error `failed: system resources not enough`; the other streams can no longer be fetched at this moment.

This problem _might_ be related to #5831.
We have observed exactly the same behavior on our dev instance, but this was then expected due to limited resources (only one Quadro 8GB GPU card).

### Environment

* Operating system and version: Ubuntu 22.04 LTS
* Ant Media Server version: 2.9.0 Enterprise Edition (licence by carsten.rose@math.uzh.ch)
* Server resources:
   * 256 GB RAM
   * 32 CPU cores
   * 1st GPU: Tesla T4, 16GB
   * 2nd GPU: Quadro RTX 4000, 8GB

### Test details

* Input stream: 3840x2160 FPS 20, H264, delivered with FFmpeg over RTSP
* ABR settings: 2160p, 1080p, 480p, 240p
* HLS and Dash settings: both enabled or disabled (two series of tests) - this did not affect the outcome
* streams are not recorded
* Streams added one-by-one with a 30sec distance (first test) or with a few seconds distance (second test)
   * in the first test only six streams were created
   * in the second test ten stream were created, but none could've been played

Resources status:
* memory usage with no streams: 0.2% by `top`, 47% (119 GB) in web panel
* memory build-up with 6 streams: ~40% by `top`, 97% (250 GB) in web panel
* detailed usage reported by `top` and `nvidia-smi` (the three numbers for a GPU are memory in MB, power in W, usage in %) in the first test
<pre>
+--------+------+-------------------+---------------------+
| Stream | CPU  |       Quadro      |        Tesla        |
+--------+------+-------------------+---------------------+
|    1   |  66% |  191 MB / 4W / 0% | 1397 MB / 29W / 13% |
|    2   | 150% |  379 MB / 4W / 0% | 2791 MB / 34W / 27% |
|    3   | 220% |  567 MB / 5W / 0% | 4185 MB / 43W / 37% |
|    4   | 330% |  757 MB / 5W / 0% | 5578 MB / 52W / 50% |
|    5   | 350% |  410 MB / 5W / 0% | 6972 MB / 59W / 52% |
|    6   | 450% | 1133 MB / 5W / 0% | 8366 MB / 60W / 55% |
+--------+------+-------------------+---------------------+
</pre>
* the usage in the second test followed the same pattern; with 10 streams the memory usage of the Tesla GPU was ~15 MB and CPU below 1000%.

### Expected behavior

We expect the server to handle 10 simultaneous streams as it was in the case of v2.4.3.

### Final remark

The on-going problems with ABR since an forced upgrade to version 2.6.3 (due to an upgrade of Ubuntu from 20.04 to 22.04) are very disturbing for us, because since the upgrade we cannot offer reliable high quality streams of lectures to our students (not every one has a connection good enough to handle a steady 4k stream without breaks). In general we are very satisfied with the server, but it was **the smooth ABR experience together with WebRTC that convinced us to use AntMedia as our streaming server in the first place.**

**Comment by burak-58** [comment]
Thank you @kputyra for the report. We will check this.

**Comment by kputyra** [comment]
Hi @lastpeony 

Thanks for taking a look on this issue.

The application had `hwScalingEnabled=true`. I've learned only recently about this parameter. Setting it to `false` seemed to improved the situation at first, but eventually the problem did not disappear. Here are my observations.

1. GPU memory usage of Tesla T4 has dropped to 800 MB per stream with a slight increase of the usage of Quadro.
2. CPU usage was higher, about 120% per stream during the test.
3. This time I was able to run 5 streams with no problems.
4. After starting the 6th stream I've noticed my old friend - _blocked thread_ warnings. Also the RAM usage start to build up
5. After several seconds I've added 7th and 8th stream. This time the memory build up was much quicker - in a few seconds the usage went up from 30 GB to 50 GB; at that moment I've stopped the streams.

Currently the lectures are over, and we do not expect a lot of usage of the server. Perhaps it would make sense to run a test directly on our instance?

**Comment by lastpeony** [comment]
> Hi @lastpeony
> 
> Thanks for taking a look on this issue.
> 
> The application had `hwScalingEnabled=true`. I've learned only recently about this parameter. Setting it to `false` seemed to improved the situation at first, but eventually the problem did not disappear. Here are my observations.
> 
> 1. GPU memory usage of Tesla T4 has dropped to 800 MB per stream with a slight increase of the usage of Quadro.
> 2. CPU usage was higher, about 120% per stream during the test.
> 3. This time I was able to run 5 streams with no problems.
> 4. After starting the 6th stream I've noticed my old friend - _blocked thread_ warnings. Also the RAM usage start to build up
> 5. After several seconds I've added 7th and 8th stream. This time the memory build up was much quicker - in a few seconds the usage went up from 30 GB to 50 GB; at that moment I've stopped the streams.
> 
> Currently the lectures are over, and we do not expect a lot of usage of the server. Perhaps it would make sense to run a test directly on our instance?

Hello thank you for your report.
Please contact me via
emre.guney@antmedia.io
Please share web panel and ssh credentials so i can check the server and perform tests.

**Comment by lastpeony** [comment]
Hello @kputyra 
Looking forward to hear back from you.

**Comment by kputyra** [comment]
Hi @lastpeony 
Thanks, I've sent you details how to access our servers.

**Comment by lastpeony** [comment]
I have performed some tests on @kputyra servers and had some findings. It looks like this issue only occurs when 2K abr is enabled on server side. Created an issue:
https://github.com/ant-media/Ant-Media-Server/issues/6507

**Comment by burak-58** [comment]
I am closing this issue. We will have [this ](https://github.com/ant-media/Ant-Media-Server/issues/6507).
