### ISSUE TITLE
Nearby devices permission for Android SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6417]
### Short description
I see that the Android SDK asks for the nearby devices permission to run the app. If the nearby device's permission is not allowed, then the app crashes.

### Steps to reproduce
1. Launch the Android SDK on your device
2. Allow all permissions other then nearby devices permission
3. Try to run any sample inside the app

### Expected behavior
The sample should work fine

### Actual behavior
sample app does not work and crashes

**Comment by lastpeony** [comment]
Fix:
https://github.com/ant-media/WebRTC-Android-SDK/pull/75
