### ISSUE TITLE
Stream pixelation in playback when switching resolution for Adaptive streaming.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6424]
When ABR is enabled with different resolutions, during playback it often shows some stream pixelation at the time of the resolution switch.

- Enable a couple of ABRs with different resolutions.
- Publish a rtmp/webrtc stream.
- Play the stream with WebRTC and switch the resolutions.
- During the switch, it often shows some stream pixelation.
- It is tested with AMS v2.9.0

Sample:
https://drive.google.com/file/d/1Brc9N0H__6ca4h6ygTIXyYUe7k0OBDkz/view?usp=sharing

**Comment by mekya** [comment]
Hi @Mohit-3196,

Let me know if I need to know anything to increase the priority. 

AFAIK, we've resolved this issue in earlier versions. Could you please tell me the problem is happening on the play.html?

Cheers
Oz

**Comment by rjtoledo** [comment]
hello just want to ask if theres any update on this?

**Comment by burak-58** [comment]
Hi @rjtoledo,
We couldn't have time to work on it. I will try to prioritize this in the following weeks.

**Comment by mekya** [comment]
I've moved the inprogress because 
- Webplayer test is not passing 
- StreamApp (embedded player) should be updated with latest web player version
