### ISSUE TITLE
Media Push recording not working with k8s

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#6430]
Scheme is "http" even iff calling REST method with https in the following line of RestService class in Media Push Plugin.

`String websocketScheme = ("https".equals(uriInfo.getBaseUri().getScheme())) ? "wss" : "ws";
`

**Comment by burak-58** [comment]
Also for k8s we need to increase shared memory size for pods. We should document this. @mustafaboleken
