### ISSUE TITLE
Issue with Flutter example

### ISSUE THREAD

**Issue by amarantmeida** [ant-media/Ant-Media-Server#6438]
### Short description
__I'm starting to finally get to test the Flutter Flow integration and I'm seeing that. If I start the Data channel or Conference on the with the Web Interface and then try to join it with the SDK Flutter Example. I'm unable to join it. It gives me an error that the stream is already started.
So, in short, I could only start one session of the Flutter Data Channel or session.  I guess there is something missing that says to join if the session is already started?__

Reported by https://antmedia.freshdesk.com/a/tickets/128992
### Environment

* Operating system and version: 
* Java version: 
* Ant Media Server version: 2.9.0
* Android SDK version: 1.4.0
* Browser name and version:

### Steps to reproduce
1. Start the Data channel or Conference on the with the Web Interface
2. Join it with the SDK Flutter Example

### Expected behavior
__You should be able to join__

### Actual behavior
__Unable to join, gives me an error that the stream is already started.__

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by OrbysSocialMediaLLC** [comment]
Any updates? Moved to Backlog? what is the meaning of that?

**Comment by burak-58** [comment]
Hi @OrbysSocialMediaLLC,
Thanks for asking. Let me clarify the development process.
We put new issues to backlog after checking and assigning priority and work estimation.
The next step for such isssues are putting them Next Sprint. Then according to the priorities we assign issues to development team.

AMS has very active community and there are good amount of issues. So, we have to prioritize them.

If you have urgency with any issue please contact with contact@antmedia.io

**Comment by OrbysSocialMediaLLC** [comment]
So,

I have to wait until then to be able to use the Flutter SDK? To finish my Application?

The Flutter SDK is not working as it supposed to. Period. This is not even a bug. Is not working and I have a release of an app on hold because of it.

Okay I think I have to start looking at another product that works.

**Comment by burak-58** [comment]
Hi @OrbysSocialMediaLLC,
I can totally understand you. You want us to fix the issue you have as soon as possible. Beside this, we have a limitted resource and everyone wants the same with you. So we have to prioritize the issues. I tried to tell the development process transparently. 
Related to your issue we have created 2 issues: #6524 and #6525 

We will work on the #6524 this week. After that at least we can tell if there is an issue with the SDK or not. Then according to the workload on the team and the priorities we will work on the issue.

Thanks for your patience. Please try to understand us.

**Comment by OrbysSocialMediaLLC** [comment]
Let me understand this correctly. You are saying that I'm the only person using the Flutter SDK? I'm the only customer that is not able to connect to the Stream once is open with the Flutter SDK? It makes no sense; this should be a big Red Flag to anyone that is planning to use AntMedia in PROD with any client is this will be the response that we will be getting when there are actual issues of using the normal features of Antimedia like just connecting to a stream.

**Comment by mekya** [comment]
Hi Guys,
It seems to me that the conversation has led to some places where we cannot find a solution. Let's come back to a solution if you're still interested @OrbysSocialMediaLLC 

I agree with you(@OrbysSocialMediaLLC ) that this is not even a bug. It is not working. I must accept that Flutter SDK has several revisions and his maturity level is not good. This is the thing we'll have CI/CD and it will resolve these issues forever. 

Anyway, let's proceed in a win-win way.  Let me know what you're building and how many active broadcasts and viewers will be simultaneously at the same time? Then we'll do our best to fix this issue quickly and make you succeed.

I understand if you switch to another product. For this scenario, I hope we can work in a win-win situation next time. 

You have all my best wishes.

Cheers
Oguz

**Comment by OrbysSocialMediaLLC** [comment]
Oguz,

My videos currently have between 50-100 Active viewers in Rumble I will love to have them in my own server with all the features. That is only my videos. I have over 10 other creator that are not happy with the fact that I can’t integrate all the features each of this creator have their own audience.

It seems that is not clear that what I’m trying to do has the potential to bring 100’s of licenses even more of AntMedia. This could be the biggest implementation of your software. But how can I get there if we can’t get a client to work?

Regards,

Alberto

**Comment by mekya** [comment]
Hi Alberto,

Thank you for the update. I appreciate your response.

It turns out that you have an estimation of 10 creators and 1K viewers. I got the point

>It seems that is not clear that what I’m trying to do has the potential to bring 100’s of licenses even more of AntMedia. This could be the biggest implementation of your software. But how can I get there if we can’t get a client to work?

I agree with you that you can't get there if we can't get a client to work. Then anyway, I dream that we resolve this issue and you'll have a successful project and you'll have thousands of creators and hundreds of thousands viewers 🚀  Let me know if you need discount when you use 100s of licenses for the Ant Media Server ;) This is the manifest coming from my heart for your success ❤️ 

Anyway, we need to start somewhere. We'll do our best to schedule this issue next week to get you proceed.  

Is there any other blocker besides this issue on the Ant Media side to proceed?


Have a great weekend

Cheers
Oguz
PS: I'd like to connect with you on LinkedIn. [Could you add me to your network?](https://www.linkedin.com/in/ahmetoguzmermerkaya/)

**Comment by mustafaboleken** [comment]
Hi @OrbysSocialMediaLLC 

I hope you are doing well.
We just fixed the issue and published a new version. You can use version 1.4.4 + to get the fix, for your information.

**Comment by OrbysSocialMediaLLC** [comment]
Thanks. Will try it this week.

**Comment by mustafaboleken** [comment]
I'm closing this issue. If there is an issue, feel free to reopen it.
