### ISSUE TITLE
Well you removed the ABLITY to stream CIRCLE app meeting

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/Ant-Media-Server#6443]
no idea why you removed the ability to stream/ restream to endpoint the Circle app/plugin , do idea why you removed this feature .. 
someone please explain
thanks

**Comment by burak-58** [comment]
Hi @brixxnatt,
I couldn't understand which feature you mean. We didn't remove restream feature.

**Comment by mekya** [comment]
I'm closing this issue for the inactivity. 

Feel free to re-open if you think it is required.
