### ISSUE TITLE
Hero Angle in Multitrack playback - Android SDK

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6470]
The requirement here is that the player can set or make any angel/stream a hero angel (bigger frame) so that the selected stream will always be in the main frame of the app. Please refer to the screen shot.

For lower bandwidth consumption:

- The stream in main/big frame should be with higher quality, like 720p
- The other smaller frame streams should be with 480p quality during the playback

![image](https://github.com/ant-media/Ant-Media-Server/assets/82374739/20ed376d-1352-436f-a21e-f4cc9164de7a)

**Comment by lastpeony** [comment]
Feature required to make this functionality possible:
https://github.com/ant-media/Ant-Media-Server/issues/6481
