### ISSUE TITLE
Check Azure Redis database combability for k8 cluster

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6494]

**Comment by Mohit-3196** [comment]
- [ ] Redis Open Source
- [ ] Azure Redis Cache

I tried utilizing both for running the Ant Media Server in cluster mode but couldn't make them work.

**Comment by muratugureminoglu** [comment]
Hi @Mohit-3196 


If your Redis configuration is set up correctly, you can establish a connection as follows. For example, you can speed up the debugging process by trying to connect to the Redis server using redis-cli (make sure the username, password, and bind interface settings are correct).

```
redis://username:password@your-redis-ip-address:6379
```

If you use Redis Cache on Azure, and if the Redis Cache and Ant Media Server are on the same VPC, SSL should be disabled and you can establish a connection as follows. However, if the Ant Media Server is in an environment outside of Azure, you will need to set up a tunnel to connect to the Redis Cache.

```
redis://default:redis-password@redis-k8s.redis.cache.windows.net:6379
```

**Comment by Mohit-3196** [comment]
Thank you @muratugureminoglu
