### ISSUE TITLE
Web RTC Load test give a empty picture

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#651]
# Issue

### Short description
Load test give a empty picture

### Environment

* Operating system and version:max osx
* Ant Media Server version:1.5.5 enterprise
* Browser name and version:chrome 70
![image](https://user-images.githubusercontent.com/40977489/49434392-11a3ec00-f7ef-11e8-9ffa-34d36985c096.png)
![image](https://user-images.githubusercontent.com/40977489/49502728-ade1f780-f8b0-11e8-9ce5-48e52d1bf44d.png)

**Comment by SelimEmre** [comment]
Hi @arnoldcui,
Thank you for your great question. Sorry for the delay. It seems like test tool doesn't connect in AMS. Please check this. If the problem persists, can you re-open this issue?  If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Good Luck!

Best Regards,
Selim
