### ISSUE TITLE
Stream does not disconnect when their is no audio/video data for sometime

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6512]
### Short description
When the user is streaming using the JS SDK and the computer sleeps and locked, then their are no video/audio frames in a stream due to which nothing plays and it looks like a stuck stream.

### Environment
* Ant Media Server version: v2.9.0 and above

### Steps to reproduce
1. Publish the stream using sample page
2. After few seconds, lock your system manually and wait for few seconds to let the system sleep or leave it until it sleeps itself 
3. Try to play the stream with WebRTC on different device

### Expected and Actual behavior
In current scenario, it is expected that the stream will not play because their is no audio or video data.

### Requested Feature

Their should be some sort of timeout during which the stream should disconnect if their is no audio or video data for some time.

**Comment by brixxnatt** [comment]
yes we have this problem

**Comment by lastpeony** [comment]
What is this OS? I tested on 2 windows machines. In one of them when it goes sleep mode it disconnects the internet and everything thus stream goes offline.
Other machine it continues to publish normally in sleep mode
