### ISSUE TITLE
Restart Causes Application Turns Into StreamApp

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6513]
Reproduced scenario:
- Create a cluster environment with 1 pod on the Kubernetes.
- Install the Circle as Conference.
- Check if the Circle works as expected.
- Delete the pod and wait for recreation automatically.
- Check the Conference app.
- It returns into the StreamApp.

**Comment by muratugureminoglu** [comment]
Let me explain a little bit for general information.

A directory called /temp-data is created on each node. This directory is mounted as /tmp for each pod. Even if the pod terminates, the WAR file will always remain in the /temp-data directory on the node.
