### ISSUE TITLE
On video conference participants side-bar does not show the related people - (Speaker is not appearing in the visible tiles after he start to speak)

### ISSUE THREAD

**Issue by golgetahir** [ant-media/Ant-Media-Server#6518]
### Short description
The right side participant bar does changes time to time but it does not make sense as most of the time the speaker and people who are having their camera open does not show there, especially when someone is presenting their screen I believe their video ( their video was open ) should be visible on the right bar instead of a participant who is muted and the camera is turned off.

<img width="1493" alt="Screenshot 2024-07-25 at 16 15 33" src="https://github.com/user-attachments/assets/d521bde2-bc6d-4a43-a031-aed594c72602">

For example here Oğuz is presenting and streaming camera but I don't see him on the right bar, in this I see people who open their camera but sometimes I saw people with no camera etc.
### Environment

* Operating system and version: macos latest
* Java version:
* Ant Media Server version: 
* Browser name and version: Chrome 126.0.6478.61

### Steps to reproduce
1. Enter a crowded meeting
2. Screen share with open camera and talk continuosly
3. Check out if participants can see on the right video side bar

### Expected behavior
Presenter and speaker should be prioritized on right sidebar, next priority should be on people whose camera is on.

### Actual behavior
Feels random

**Comment by burak-58** [comment]
Thank yo @golgetahir. While assigning video players we consider last talking time. I aggree with you with that people whose cameras are opened should have some priority while getting the video players.

**Comment by mekya** [comment]
The problem here is about the UI and backend are not aligned. This is the issue I sent you @burak-58 that I cannot see Nur when she's speaking
