### ISSUE TITLE
playing VOD video on the player.html page

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/Ant-Media-Server#6522]
on the player.html page, at the moment you can only play the stream ID, add the ability to play VOD files via a link or ID.

**Comment by burak-58** [comment]
Hi @studentAlanMorgan,
player.html is only WebRTC player and focussed on WebRTC playback debugging. The main player page is play.html. You can also use it for VoD playback.

**Comment by studentAlanMorgan** [comment]
@burak-58 The point is to synchronize video for all connected devices.
When watching a broadcast via ID, the video is synchronized.
If this functionality can be implemented differently, I would be grateful for the advice. priority playback of VOD files with synchronization on all devices.

**Comment by mekya** [comment]
Hi @studentAlanMorgan,

Thank you for the response. I want to understand what the blocker is for you to use play.html? It both supports vod, webrtc, hls, etc. 

Cheers
Oguz
