### ISSUE TITLE
Check the Flutter sample applications and verify if they work

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6524]

**Comment by mustafaboleken** [comment]
I tested all the scenarios manually, here are the results:

- Android:

    -[] Play
    -[] Publish Camera
    -[] Publish Screen Share
    -[] P2P
    -[] Conference
    -[] DataChannel

- iOS:

    -[] Play
    -[] Publish Camera
    -[] Publish Screen Share
    -[] P2P
    -[] Conference
    -[] DataChannel

- Web:

    -[] Play
    -[] Publish Camera
    -[] Publish Screen Share
    -[] P2P
    -[] Conference
    -[] DataChannel

**Comment by mustafaboleken** [comment]
I created issues and closing this issue.

- https://github.com/ant-media/Ant-Media-Server/issues/6556
- https://github.com/ant-media/Ant-Media-Server/issues/6557
- https://github.com/ant-media/Ant-Media-Server/issues/6558

**Comment by mustafaboleken** [comment]
After the version 1.4.4 we solved the data channel issues
