### ISSUE TITLE
Circle recording issue after 30 minutes

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6529]

**Comment by mustafaboleken** [comment]
While we are using the media push for recording, after some time we get the error below and the browser will crash in kubernetes. To solve this, I opened a pr to reduce the memory usage and if you are using the kubernetes, you can make the changes below.

`ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)`

**Comment by mustafaboleken** [comment]
Set the empty dir to increase the shared memory size

`spec:
  containers:
    - name: your-container
      image: your-image
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
`

And set the shared memory size to min 2 GB

`--shm-size=2g`

**Comment by mekya** [comment]
Hi @mustafaboleken 
I don't understand where to add --shm-size=2g. Could you just explain a little further?

**Comment by mustafaboleken** [comment]
Hi @mekya 

I just updated the comment with more explanation.

**Comment by mekya** [comment]
Thank you @mustafaboleken

**Comment by mustafaboleken** [comment]
I tested the scenario with rooms where recording was enabled and there were 4 participants. From now on, when I refer to a 'room,' this is what I mean:

- 2 GB of shared memory can handle up to 2 rooms.
- 4 GB of shared memory can handle up to 3 rooms.
- 10 GB of shared memory can handle up to 10 rooms.

**Comment by burak-58** [comment]
In Kubernetes deployment please add as suggested [here](https://stackoverflow.com/a/46434614).

containers:  
    volumeMounts:
        - mountPath: /dev/shm
           name: dshm
....
    volumes:
        - emptyDir:
             medium: Memory
          name: dshm
