### ISSUE TITLE
Webhook is not working

### ISSUE THREAD

**Issue by ntnahn** [ant-media/Ant-Media-Server#654]
# Issue

### Short description
I was setting as this link https://github.com/ant-media/Ant-Media-Server/wiki/Webhook-Integration:-No-worry,-We'll-call-you but the AntMedia is not call to my API

### Environment

* Operating system and version: ubuntu 16.04
* Java version: 
* Ant Media Server version: 1.5.1.1
* Browser name and version: Chrome 70

### Expected behavior
I want receive the event VodReady from webhook

### Actual behavior
I already have the API for webhook call to but it is not call to my API

### Steps to reproduce
1. Enable Recording MP4
2. Setting webhook url
3. Stream and end to ant store stream video
4. The ant is not call to my webhook

**Comment by jiantongc** [comment]
Same here with https://aws.amazon.com/marketplace/pp/B07569Y9SJ?qid=1548234572387&sr=0-2&ref_=srh_res_product_title
Events do fire in Community Version installed locally

**Comment by SelimEmre** [comment]
Hi @ntnahn,
Thank you for your interest. Sorry for the delay. In our latest version, we've added several fixes about the webhook feature. Please test our latest version. If the problem persists, can you re-open this issue?

Best Regards,
Selim
