### ISSUE TITLE
viewer counter and token security

### ISSUE THREAD

**Issue by perfectwebtech** [ant-media/Ant-Media-Server#655]
hello

is there where i can deploy or configure ? 

1) token security in websocket or streaming engine ? people can not capture my stream public ? 

2) where i can see counter how many viewers in this stream something like that ? 

2) recording features is there available ?  streaming source and ip camera  ?

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please reopen if it's not resolved for you.
