### ISSUE TITLE
Latest versions (2.9 and 2.10) on REST API Reference missing endpoints

### ISSUE THREAD

**Issue by amarantmeida** [ant-media/Ant-Media-Server#6571]
### Short description
__The REST API Reference ( https://antmedia.io/rest/?urls.primaryName=2.10.0 ) and noticed that the latest few versions seem to be missing some endpoints.
For example, it looks like the ManagementRestService section is missing from 2.10.0 and 2.9.0, but it is visible in versions 2.7.0 and below.__

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Open the link https://antmedia.io/rest/#/ManagementRestService 
2. Select 2.9 and 2.10 and you will see some endpoints are missing. 

### Expected behavior
__We need to see the APIs of all endpoints__
We can have a different page for ManagementRestService APIs.

### Actual behavior
__Some endpoints missing__

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by muratugureminoglu** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/720
