### ISSUE TITLE
Unable to Join Conference Room from Android app after disabling the video.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6576]
### Short description
Unable to Join the Conference Room from the Android app after disabling the video.

### Environment
* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. Get the WebRTC Android Webrtc master app from GitHub.
2. Go to the ConferenceActivity
3. Programmatically/Manually disable the video. i.e. setVideoEnabled to false.
4. Click on the Join the Room Button.

### Expected behavior
The Android app should connect to the conference room

### Actual behavior
It keeps on reconnecting, unable to join the room.

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by sanidhya09** [comment]
Video for your reference:
https://drive.google.com/file/d/1NpW072BgiHA3ZA4e0z8L97p0Y0zpTsim/view?usp=sharing

**Comment by muratugureminoglu** [comment]
<div>Agent Mohit Dubey linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/132011">132011</a> for this issue.</div><br/>

**Comment by sanidhya09** [comment]
@muratugureminoglu  @Mohit-3196 is this issue fixed? Please tell us the tentative time.

**Comment by lastpeony** [comment]
There is a temporary workaround fix for this problem but we are working on a whole solution. 
Related:
https://github.com/ant-media/Ant-Media-Server/issues/6599
