### ISSUE TITLE
Issue with Android SDK post upgrade

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6597]
I have installed the 2.10.1 Server and see some issues with the Android SDK.

The android receives the `onPublishStarted` callback and begins streaming and I can view about 10 seconds worth of video through the Management Console.
Then the Android receives an error of `noPacketReceivedForTimeoutDuration` and the WebSocket disconnects on the Android and the reconnect process starts over.

I'm running Android SDK version 2.4.3

**Comment by lastpeony** [comment]
I believe this should not occur with latest sdk+ams

should be related to
https://github.com/ant-media/Ant-Media-Server/issues/6605

**Comment by lastpeony** [comment]
This issue was actually related to a bug on server side:
https://github.com/ant-media/Ant-Media-Server/issues/6605
It is hotfixed. Please use 2.11.2 ant media server.
It should not occur with any android sdk version.

 Feel free to re-open.
