### ISSUE TITLE
Change Video Source Does Not Work In Android Conference

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#6599]
The changeVideoSource method in the WebRTC client Android SDK does not function correctly during an ongoing conference if the user tries to play the room. When changeVideoSource called with any type of source video freezes and after few seconds it disconnects. 

However, it works fine during when only publishing. Additionally, the method works if its called before call begins in both conference and only publish.

Reproduce:
After conference begins try to switch from front camera to back camera by using changeVideoSource 
Comment out play in conference scenario and try again, observe it work this time.

Expected Behavior:
The changeVideoSource method should work on air in conference , just as it does during only publishing.

**Comment by burak-58** [comment]
Fixed in https://github.com/ant-media/WebRTC-Android-SDK/pull/98
