### ISSUE TITLE
Broadcast failing if port (5443/5080) is not specified in a playlist URL. 

### ISSUE THREAD

**Issue by amarantmeida** [ant-media/Ant-Media-Server#6607]
### Short description
Broadcast failing to start if port (5443/5080) is not specified in a playlist video URL. 

### Environment

* Operating system and version: 
* Java version: 
* Ant Media Server version: 2.10.1
* Browser name and version:

### Steps to reproduce
1.Create a Playlist
2.Add a video via id/link 
url- https://test.antmedia.io/test/streams/163420825925063644478233.mp4
3.Start Broadcast

### Expected behavior
__Playlist should be able to broadcast__

### Actual behavior
__We are encountering an error in broadcast__

 
### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
We had a discussion about this with @muratugureminoglu 

This problem can be solved by running those 2 commands in corresponding server:
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 5443
iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to-port 5443
```
As you see after above configuration server can access the local files without port
![image](https://github.com/user-attachments/assets/daafa158-8ab8-46be-affe-5d966a99c307)

We will discuss further to integrate this to installation script to make this default behaviour or not.
