### ISSUE TITLE
Latest 3  releases are identical

### ISSUE THREAD

**Issue by xvalen** [ant-media/Ant-Media-Server#6614]
### Short description
I have tried to upgrade Ant Media Server Community from version 2.10.0 to 2.11.0 but after upgrade I have still version 2.10.0.

So I have compared md5 checksum of downloaded files and versions 2.10.0, 2.10.1 and 2.11.0 have same md5sum. So all versions above are actually 2.10.0.

### Steps to reproduce
1.  wget https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.11.0/ant-media-server-community-2.11.0.zip
2.  wget https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.10.1/ant-media-server-community-2.10.1.zip
3.  wget https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.10.0/ant-media-server-community-2.10.0.zip
4. md5sum ant-media-server-community-2.11.0.zip 
    46c658cf457b6752e64b004724e3cf67  ant-media-server-community-2.11.0.zip
5. md5sum ant-media-server-community-2.10.1.zip 
    46c658cf457b6752e64b004724e3cf67  ant-media-server-community-2.10.1.zip
6. md5sum ant-media-server-community-2.10.0.zip 
    46c658cf457b6752e64b004724e3cf67  ant-media-server-community-2.10.0.zip

**Comment by mekya** [comment]
Hi @xvalen ,

Yes, you're right. It's my bad. 

We've migrated to github actions and I've missed some parts. 
Additionally, another automation just pulls the latest from sonatype and pushes to github releases. This is why we see the same release for the last 3 releases.

Thank you for the report. 

I hope you also join some of our online events and we can meet there. 

Have a great weekend

**Comment by xvalen** [comment]
Thank you very much.
