### ISSUE TITLE
Add suffix to the mp4 file name to make a custom name format

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6650]
The feature request is to save MP4 files with a custom name format such as **filename_1080p_converted.mp4**.

Removing `%b` from the file name format removes the bit rate from the recorded file name. 

  “fileNameFormat”: “%r%b”,
  
After that, the recording will be in this format, `filename_1080p.mp4` but the user wants to add the suffix as well to make it customized.

**Comment by JaswanthBandi2428** [comment]
Hello can I make custom filename for my recorded file Mp4 initiated from API, If yes how can I do that.

**Comment by lastpeony** [comment]
> Hello can I make custom filename for my recorded file Mp4 initiated from API, If yes how can I do that.

Mentioned PR allows you to add a custom text to recording file names through app settings.
what kind of customization do you need?
