### ISSUE TITLE
Create integration test for recording issue

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6651]
https://github.com/ant-media/Ant-Media-Server/issues/5601#issuecomment-2331472407

**Comment by burak-58** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/732

**Comment by mekya** [comment]
Hi @burak-58 ,

I've merged the PR. It can be closable. 

Thank you
