### ISSUE TITLE
SERVER CRASH

### ISSUE THREAD

**Issue by IVEN2024** [ant-media/Ant-Media-Server#6658]
### Short description
Server crash after 3 days of working

### Environment

* Operating system and version:ubuntu 22.4
* Java version: 
* Ant Media Server version:  Enterprise latest
* Browser name and version:

the system atomatically sent you the logs on crash

I need respond on this please ASAP

**Comment by muratugureminoglu** [comment]
Hi @IVEN2024 

If you can share the email address associated with your Enterprise License , we can check the crash logs from you. 

Thanks.

**Comment by IVEN2024** [comment]
the email address start with vmix*****@gmail.com

**Comment by muratugureminoglu** [comment]
Hi @IVEN2024 

We have reported that the crash logs for the email address you provided via the ticket system are missing and we have tried to contact you twice but we have not received any messages. Therefore, I am closing this issue as well. Please feel free to open it again. We will be here.

Regards.
