### ISSUE TITLE
Configure SRT Receive Latency through application settings

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#6665]
**Is your feature request related to a problem? Please describe.**
User would like to configure SRT ingest latency so that he'll let the SRT handle the packet loss and other things better. I think the parameter we need to set is this one.
https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_RCVLATENCY

We need to find and use it in the proper java function.

sporttotal

**Comment by burak-58** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/734

**Comment by mekya** [comment]
Hi @burak-58 
Both community and enterprise side have been merged. It can be closable. 

Thank you for the work. 

FYI
