### ISSUE TITLE
code snippet to get progress events

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#6702]
Can you share a code snippet to get progress events? We want events when:
1. The video starts buffering
2. The video plays/pauses/stops
3. The video progresses (progress events, e.g. we played 1 sec of video)
It seems Web Player doesn't support this, nor are we able to get it working with video.js APIs. Has event propagation been blocked / modified by Web Player?
We tried a lot of things, including attached pictures
Please share a code snippet for getting these events. We need play / pause / error events at the very least.
![image (13)](https://github.com/user-attachments/assets/f9892941-f24f-49de-a709-2e7f4b666a57)
![image (12)](https://github.com/user-attachments/assets/05ce8ee8-7c57-4274-9084-ccd78486300d)

**Comment by lastpeony** [comment]
PR is here:
https://github.com/ant-media/Web-Player/pull/30
I also added a custom code snippet to show how to get events from application side.
If its urgent customer can pull it and start using it.
FYI @akiziltoprak
