### ISSUE TITLE
Memory increase with ABR

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6705]
I tried it on a pod with 8-cores (I believe it is not related to Kubernetes)

1. Add 2 ABR settings (1080p, 480p)
2. Create 4-5 RTMP streams
3. Observe the memory

Expected: Memory doesn't increase
Actual: It is increasing

**Comment by burak-58** [comment]
When we create streams in a short time interval, CPU consumption peeks for a transient time. In that time interval encoders cannot handle processing in time. So the frame buffer sizes start to increase and that causes high memory usage. Then if you stop the streams or transient time overs it seems that memory usage for AMS thread remains high. This is not a leak. Actually Java reservers that memory but not release it again. When you start a new stream that reserved memory is used and not a new memory allocation is performed.

This is an expected behavior. You may read more on Java Native memory management [here](http://www.trevorsimonton.com/blog/2020/09/09/java-native-memory.html).

Some possible workarounds are using a computer with enough memory to handle your transient time or you may create streams sequentially. If you observe high memory usage and cannot create a new stream because of the above effect, you may increase memory threashold in conf/red5.properties file.

**Comment by burak-58** [comment]
For a permanent solution I will update here.

**Comment by muratugureminoglu** [comment]
<div>Agent Murat Ugur linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/134265">134265</a> for this issue.</div><br/>

**Comment by muratugureminoglu** [comment]
<div>Agent Amarnath Thodupunoori linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/128488">128488</a> for this issue.</div><br/>
