### ISSUE TITLE
Immediate Server Crash With WHIP Publish on VP8 Only

### ISSUE THREAD

**Issue by lastpeony** [ant-media/Ant-Media-Server#6723]
### Short description
Server crashes immediately if you only enable VP8 through app settings and publish from OBS Whip.

2.11.3

Steps to reproduce
1. Disable H264 and enable VP8 from application settings.
2. Publish with WHIP through OBS h264
3. Server crashes

Expected behavior
Server should not crash, proceed publish or reject gracefuly
Actual behavior
Server crashes

**Comment by lastpeony** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/739

**Comment by mekya** [comment]
Hi @lastpeony ,

CI has not passed the tests so I'm moving back to 'In Progress'

**Comment by lastpeony** [comment]
> Hi @lastpeony ,
> 
> CI has not passed the tests so I'm moving back to 'In Progress'

This actually passed but failed on deployed staging for some reason. I am restarting it

**Comment by mekya** [comment]
It's merged and I'm closing this issue
