### ISSUE TITLE
Swagger has wrong values for enum fields in Broadcast definition

### ISSUE THREAD

**Issue by Himpoke** [ant-media/Ant-Media-Server#6740]
### Short description
The generated swagger lists a single value for these fields, instead of an enum of those values.
Broadcast.status
Broadcast.playListStatus
Broadcast.type
Broadcast.publishType

This is due to the allowed values for these are set as a single string with commas in.

The effect of this is that we can't do correct code generation on the generated swagger file. We first must do some regex magic to make the file usable.

I actually already opened a pull request for this, but I didn't know if that's an acceptable way to request changes
https://github.com/ant-media/Ant-Media-Server/pull/6739

### Environment

* Operating system and version: at build time
* Java version: 17
* Ant Media Server version: latest, but also in versions before
* Browser name and version:

### Steps to reproduce
1. Download the swagger file
2. Find: enum, the Broadcast properties should be the first you find.
3. See the enum array in the fields listed.

### Expected behavior
```json
            "enum": [
              "finished","broadcasting","created","preparing","error","failed"
            ]
```
### Actual behavior
```json
            "enum": [
              "finished,broadcasting,created,preparing,error,failed"
            ]
```

### Logs
no relevant logs

**Comment by burak-58** [comment]
Thank you @Himpoke for the report and pull request. Let us check it and merge.
Also personally I want to thank for the contribution.
