### ISSUE TITLE
Rest API accepts any token type

### ISSUE THREAD

**Issue by aminrd** [ant-media/Ant-Media-Server#6744]
### Short description
There's an API to create a one time token to play/publish a stream: 
```
GET [/v2/broadcasts/{id}/token](https://antmedia.io/rest/#/default/getTokenV2)
```
in our system, we were sending `Publish/Play` instead of `publish/play` and it took a while to figure out that's the issue, because the `/token` API was actually responding ( didn't raise `HTTP 400` ). We noticed that endpoint actually accepts anything. Example respond when `type=any-random-type`:

```
{
    "tokenId": "803744123715293436876927",
    "streamId": "AminTest",
    "expireDate": 1760639107000,
    "type": "any-random-type",
    "roomId": null
}
```

Should this API return `HTTP 400` when type is not valid?

**Comment by lastpeony** [comment]
Well yes, i had a look through the code and it creates the token with any type without checking it. 
Thank you for the issue, it will be fixed as soon as possible.
