### ISSUE TITLE
viewerInfo argument of .play() Not Included in WebHook Play Authentication Payload

### ISSUE THREAD

**Issue by filip-ams** [ant-media/Ant-Media-Server#6746]
**Is your feature request related to a problem? Please describe.**
When receiving playStarted webhook event I only get these fields:

timestamp, action, id, I don't receive the metadata, category, streamName

It's not clear how to use metadata field mentioned in the documentation:
![image](https://github.com/user-attachments/assets/5e4cf373-ee61-4d25-9087-669e33ac3253)

**Describe the solution you'd like**
Explain how to use the metadata field and add a way to customize it (Send custom text on webhook events)

**Comment by burak-58** [comment]
@filip-ams please create the issue with our report format.

**Comment by lastpeony** [comment]
As far as i know the main point of this issue was about playing, play websocket calls viewerInfo is not passed to play started webhook message as metadata. If this is the case, please confirm and update the issue accordingly by following the template.
@filip-ams

**Comment by rajender-wohler** [comment]
Hi there, not sure if the description mentioned above covers our problem. But I'll try to explain what we are trying to do
Referring to https://antmedia.io/docs/guides/publish-live-stream/webrtc/webrtc-websocket-messaging-reference/ to issue play commands for playing WebRTCStream, here's what we are trying to do

1. Publisher
Here you can just publish a stream in WebRTCAppEE 

2. Player
In order for us to identify valid or authentic applications , the applications will proved some metadata 
i.e wss://SERVER_NAME:5443/WebRTCAppEE/websocket
Client sends play command to the server with streamId parameter and also viewerInfo
Example
{
  command : "play",
  streamId : "stream1",
  **viewerInfo : "{'id1':'value1','id2':'value2'}",**
}

3.  Webhook handlers

In the webhook registered for 'webhookPlayAuthUrl', we are running a custom application to process some metadata which is in the form of json. 
Reference: https://antmedia.io/docs/guides/stream-security/webhook-stream-authorization/
Example
{
  "streamId": "stream1",
  "mode": "play",
  "appName": "WebRTCAppEE",
  "origin":"[domain_of_request_origin]",
  "token": "token_if_passed",
  "subscriberCode": "subscriber_code_if_passed",
  "subscriberId":"subscriberId_if_passed",
  **"metaData":{"id1":"value1","id2":"value2"}**
}
Based on these metadata fields, we would want to decide and appropriately send either 200 OK or any other response codes.

In case of a non-200 OK response, we want a custom message in response text.


In the current webhook ,  I believe we don't see the metaData fields sent by the player as part of the viewerInfo . This is specifically what we wanted to receive as part of the webhook 'play request' events payload

**Comment by lastpeony** [comment]
I edited the title according to the description provided by @rajender-wohler 

Please check and update issue content @filip-ams

**Comment by lastpeony** [comment]
Hello @rajender-wohler 
Your request is implemented. ViewerInfo passed to the .play() will be now included in webhook auth play payload in "viewerInfo" field. "metadata" field of webhook auth payload is metadata of the related broadcast.

Implementation:
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/751

**Comment by rajender-wohler** [comment]
Can you please share details of the version of ant media since when this feature is made available?
Haven't been able to verify it in 2.12 version.
