### ISSUE TITLE
Negative HLS viewer count

### ISSUE THREAD

**Issue by SebastienGautier** [ant-media/Ant-Media-Server#6761]
### Short description
We have some streams that have a negative HLS viewer count

### Environment

* Operating system and version: Ubuntu 22.04
* Java version: openjdk 17.0.12
* Ant Media Server version: 2.12.0
* Browser name and version: unrelated

### Steps to reproduce
![image](https://github.com/user-attachments/assets/893af199-27a6-4409-bc4b-dc6b0655e3d9)

### Expected behavior
HLS viewer count should never be negative

### Actual behavior
HLS viewer count is negative for some streams

We had writeStatsToDatastore set to false for some time if that could be related

### Logs
Nothing that looks related

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by burak-58** [comment]
I am putting this to the next sprint plan.
