### ISSUE TITLE
RTMP publish issue

### ISSUE THREAD

**Issue by rumanmaharjan** [ant-media/Ant-Media-Server#6779]
### Short description
__Brief description of what happened__

Issue while publishing RTMP stream of IP camera from community edition to enterprise edition for CamOS application. Here IP camera and AMS community edition on connected on private LAN and AMS Enterprise RTMP link connected via internet.
If any connectivity issue between RTMP publisher and RTMP server or stream restart due to some reason, it goes offline till we restart antmedia service on RTMP server and restart stream on client end.

### Environment

Server:
* Operating system and version: Ubuntu 22.04.2 LTS
* Java version: openjdk version "17.0.12" 2024-07-16
* Ant Media Server version: Enterprise Edition 2.11.3 20240906_0602
* Browser name and version: Google Chrome Version 130.0.6723.117

Client:
* Operating system and version: 20.04.6 LTS (Focal Fossa)
* Java version: openjdk version "17.0.12" 2024-07-16
* Ant Media Server version: Community Edition 2.11.3 20240906_1141

### Steps to reproduce
1. Generate RTMP link on server and start IP Camera stream publish from client with on that RTMP link.
2. Disconnect and reconnect the client from internet connection or stop & start stream

### Expected behavior
__Put as much detail here as possible__

It should start publishing RTMP once the client internet connectivity is up.

### Actual behavior
__Put as much detail here as possible__

 It's offline until we restart antmedia service on server and restart stream on client end.

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

https://pastebin.com/2xs0VpNp

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
Correct me if I'm wrong: Your client's internet connection intermittently cuts off and reconnects, and in this case, you expect the RTMP publish to automatically reconnect, but it doesn't. Is that correct?

If so, this functionality should be configurable on the client side. For example, upon disconnection, the system could attempt to republish every 5 seconds, with a maximum of 5 attempts.

**Comment by burak-58** [comment]
I am closing the issue for now. If you encounter please feel free to reopen it.
