### ISSUE TITLE
Can't run antMedia in docker.

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/Ant-Media-Server#678]
# Issue

### Short description
Build a antmedia server image,that can't run it on ubuntu.

### Environment

* Operating system and version:ubuntu 16.04
* Ant Media Server version:1.5.1.1-181012_1548
*Docker version:18.09.0

### Expected behavior
access antmedia login page.

### Actual behavior
antmedia service doesn't run.

### Steps to reproduce
1. build docker container with ubuntu 16.04 and copy antmedia server zip in.
2. run image with -it param.
3. install antmedia server.
4. run command `service antmedia restart`

install antmedia server with this command
```
apt-get update
apt-get install -y libx11-dev
apt-get install -y wget
cd home
wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh
chmod 755 install_ant-media-server.sh
./install_ant-media-server.sh ant-media-server-enterprise-1.5.1.1-181012_1548.zip
```

### Logs
![image](https://user-images.githubusercontent.com/40977489/49791826-3ad2f800-fd6c-11e8-8d2f-534f04ada2de.png)
![image](https://user-images.githubusercontent.com/40977489/49794394-6953d180-fd72-11e8-9785-76b1e0cdf318.png)

**Comment by Keyreach** [comment]
I have same issue, it looks like that problem is rather in /usr/local/antmedia/antmedia script or tools used in it, because launching start.sh/shutdown.sh manually is working as supposed.
There are some messages found in antmedia-error.log that probably related to this issue
```
failed setting default capabilities.
set_caps(CAPS) failed for user 'antmedia'
Service exit with a return value of 4
```

**Comment by arnoldcui** [comment]
> I have same issue, it looks like that problem is rather in /usr/local/antmedia/antmedia script or tools used in it, because launching start.sh/shutdown.sh manually is working as supposed.
> There are some messages found in antmedia-error.log that probably related to this issue
> 
> ```
> failed setting default capabilities.
> set_caps(CAPS) failed for user 'antmedia'
> Service exit with a return value of 4
> ```

Hi,just now I have try run start.sh in /usr/local/antmedia,I can access the management page.
Thank you

**Comment by arnoldcui** [comment]
> I have same issue, it looks like that problem is rather in /usr/local/antmedia/antmedia script or tools used in it, because launching start.sh/shutdown.sh manually is working as supposed.
> There are some messages found in antmedia-error.log that probably related to this issue
> 
> ```
> failed setting default capabilities.
> set_caps(CAPS) failed for user 'antmedia'
> Service exit with a return value of 4
> ```

But if I build docker image with
`ENTRYPOINT ./usr/local/antmedia/start.sh`
It will give me 
![image](https://user-images.githubusercontent.com/40977489/49851349-cd7ea000-fe1b-11e8-8985-18e36f97f282.png)
Is there any way to build the docker image?

**Comment by mekya** [comment]
@Keyreach is right. It's about system capabilities. Just start docker in privilege mode so that it can run. 

@arnoldcui you build from source code? It seems that there is a kind of compatibility or install issue.

**Comment by arnoldcui** [comment]
![image](https://user-images.githubusercontent.com/40977489/49855541-8945cc80-fe28-11e8-804b-d9d6e1e2a5e5.png)
This is my new Dockerfile
```
FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y wget

COPY ant-media-server-enterprise-1.5.1.1-181012_1548.zip /home/ant-media-server-enterprise-1.5.1.1-181012_1548.zip

RUN cd home \
    && pwd \
    && wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh \
    && chmod 755 install_ant-media-server.sh

RUN apt-get install openjdk-8-jdk unzip jsvc -y

RUN cd home \
    && pwd \
    && ./install_ant-media-server.sh ant-media-server-enterprise-1.5.1.1-181012_1548.zip

ENTRYPOINT /usr/local/antmedia/start.sh
```
after i built it.It alway tell me 
![image](https://user-images.githubusercontent.com/40977489/49855676-e80b4600-fe28-11e8-899f-fe0c62a2087f.png)
If i get into /usr/local/antmedia .and run start.sh it will be ok.

**Comment by Keyreach** [comment]
Hope it'll helps, I've investigated original issue and it seems to be caused by jsvc which, according to [code](https://github.com/apache/commons-daemon/blob/trunk/src/native/unix/native/jsvc-unix.c#L216), requests `NET_BIND_SERVICE`, `SETUID`, `SETGID` (allowed in docker by default) and `DAC_READ_SEARCH` (not allowed in docker by default) capabilities. So it's enough to add `--cap-add DAC_READ_SEARCH` in `docker run` command instead of going full privileged mode to avoid this problem.

**Comment by mekya** [comment]
@arnoldcui, you may need to change the working directory to /usr/local/anmedia and run ./start.sh
Alternatively, you may try to start service with `service antmedia start`

@Keyreach is right. Thank you @Keyreach

**Comment by arnoldcui** [comment]
Thanks for  all @mekya @Keyreach 
After I turn ** ENTRYPOINT** from `service antmedia restart && bash` to `service antmedia start && bash`.I can run the docker image.
It still need some args. @Keyreach The `--cap-add DAC_READ_SEARCH` is useful here and `--privileged=true `Equally effective.
Thank you

**Comment by tohqecom** [comment]
Let's change:
From: FROM ubuntu:16.04
To: FROM ubuntu:18.04

**Comment by mekya** [comment]
Please use the dockerFile in here

https://github.com/ant-media/Scripts/blob/master/docker/Dockerfile_Process

We use the file above in our integration tests so that it's always up to date and working.
