### ISSUE TITLE
Immediate reconnection request on webSocket disconnection

### ISSUE THREAD

**Issue by muratugureminoglu** [ant-media/Ant-Media-Server#6786]
### Short description
In Java Script side, immediate reconnection request when webSocket connection is lost

### Environment

* Operating system and version: Ubuntu 22.04 on K8s 
* Java version: 17
* Ant Media Server version: 2.11.3
* Browser name and version: Chrome/Firefox

### Steps to reproduce
1. Create a K8s cluster
2. Generate 2 origin pods
3. Publish a stream
4. Terminate the pod you send a stream
5. Observe how many seconds it takes to connect to the alive pod

### Expected behavior
A client should forward to the alive pod in 3-5 seconds.

### Actual behavior
A client is forwarded to the alive pod in 10-13 seconds.

 
### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by mekya** [comment]
It's merged and I'm closing this issue
