### ISSUE TITLE
Make the installation script download the latest version from S3

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#6801]
This is the follow-up job of this issue https://github.com/ant-media/Ant-Media-Server/issues/6377

Here are things to complete
1. Make the installation script download latest version from S3
2. Please don't upload marketplace version to S3
3. $TMP_VERSION_NAME is used in uploads to S3. $TMP_VERSION_NAME is like "ant-media-server-enterprise-tmp.zip". I think something exact version or "ant-media-server-enterprise-latest-version.zip" maybe more meaningful. Let me know if you think differently

**Comment by muratugureminoglu** [comment]
1.  https://github.com/ant-media/Scripts/pull/321
2. Removed
3.  I think [$TMP_VERSION_NAME](https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/blob/master/yml/deploy_staging.yml?ref_type=heads#L181
) tag condition creates the same file, but I changed it to $VERSION_EXACT_NAME.

https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/754

FYI: It was configured on the spaceport account, now it works on [our side](https://eu-west-2.console.aws.amazon.com/lambda/home?region=eu-west-2#/functions/s3DownloadFunction?subtab=triggers&tab=code).

**Comment by mekya** [comment]
Hi @burak-58,

I've merged the PRs and check the repo.  This issue is closeable. 

Regards
