### ISSUE TITLE
Custom CloudMetric settings for Scale down (Self-Managed system)

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#6806]
At 15 minutes Scale-Down starts, so custom cloudwatch metrics can be a bit more helpful.

**Comment by amarantmeida** [comment]
@muratugureminoglu Tested the script and it works as per our expectation. 15min for the first termination and with in next 5min other instances were all down.

**Comment by muratugureminoglu** [comment]
This value is good for now. We can close it.
