### ISSUE TITLE
Live Stream latency issue- On Apple M4 Mac and Safari 18.1.1

### ISSUE THREAD

**Issue by amarantmeida** [ant-media/Ant-Media-Server#6881]
### Short description
__When I try to view a video from either our website or directly from AntMedia server I see the issue. I go to the AMS dashboard and try to view a live stream from it,  A window loads with a spinning loader.  This lasts for about 14 seconds.  After that,  a “The streaming will begin shortly” message appears.  About 8 seconds after that,  the video appears but it has about 7 seconds of latency. 
When I do the same test above but using Google Chrome,  everything is really fast, on both PC’s and Macs. The video loads in less than 1 second, and there is virtually no latency.__

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.11.3
* Browser name and version:

### Steps to reproduce
1. Publish a stream via webrtc.
2. View the steam on AMS via latest safari(18.1.1)
3. You will see the latency. 

### Expected behavior
__There shouldnt be any latency >1sec. Behaviour should be same as Chrome browser__

### Actual behavior
__Failing to load and then huge latency before it starts to play. __

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by muratugureminoglu** [comment]
<div>Agent Amarnath Thodupunoori linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/138254">138254</a> for this issue.</div><br/>

**Comment by burak-58** [comment]
Hi @amarantmeida,
This seems to be a WebRTC Connectivity issue. After Player cannot play with WebRTC it switches to HLS. So in your scenario you are playing with HLS instead of WebRTC so the latency is about 8 seconds.

We should investigate the connectivity issue. It may be because of firewall behind which you try to play the stream. If this is the case a TURN server will be required.

Lets check it together.

**Comment by amarantmeida** [comment]
@burak-58 Sure, I can schedule a call with the customer. 
Since Chrome on the same PC and network is working fine, I thought this couldn't be an issue with network.

**Comment by amarantmeida** [comment]
@burak-58 We can close this out. Apparently, the issue was only happening on customers MAC and Safari alone. Different MAC's from the same network didnt have the issue as well. They will check this from their side. Thank you.
