### ISSUE TITLE
WebRTC ports range configuration issue

### ISSUE THREAD

**Issue by nazar-pc** [ant-media/Ant-Media-Server#692]
I'm trying to run Ant Media Server under Docker, which naturally raises issues with mapping large numbers of ports from container to the host (I do not run it in privileged mode or with host networking).

However, I don't see a way to reduce UDP ports range for WebRTC from `5000..65000` to something like `5000..6000` or even less than that for testing purposes. Coturn TURN server allows such control for instance.

Can you add an option so that such configuration is possible like with RTMP and other ports or maybe it is just not documented?

**Comment by SelimEmre** [comment]
Hi @nazar-pc,
Thank you for your question. We fixed this issue in #852 PR. This feature will be in our new version. If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Also you can review our [Google Group](https://groups.google.com/forum/#!forum/ant-media-server)

Best Regards,
Selim
