### ISSUE TITLE
Using Third Party RTMP Publishers With Ant

### ISSUE THREAD

**Issue by ozankonur** [ant-media/Ant-Media-Server#7]
I am getting error when I try to stream to ant server ;

[flv @ 00000000006eea80] subtitle stream discovered after head already parsed
[flv @ 00000000006eea80] audio stream discovered after head already parsed
[flv @ 00000000006eea80] video stream discovered after head already parsed
[WARN] [Red5_Scheduler_Worker-30] io.antmedia.muxer.Mp4Muxer - before writing he
ader
[INFO] [Red5_Scheduler_Worker-30] io.antmedia.muxer.MuxAdaptor - after prepare
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[mpegts @ 0000000058df34e0] H.264 bitstream malformed, no startcode found, use t
he video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb
' option with ffmpeg)
[INFO] [Red5_Scheduler_Worker-1] io.antmedia.muxer.HLSMuxer - cannot write frame
 to muxer
[ERROR] [Red5_Scheduler_Worker-1] org.red5.server.scheduling.QuartzSchedulingSer
viceJob - Job io.antmedia.muxer.MuxAdaptor@72917aef execution failed
java.lang.NullPointerException: null
        at io.antmedia.muxer.Mp4Muxer.writePacket(Mp4Muxer.java:300)
        at io.antmedia.muxer.MuxAdaptor.execute(MuxAdaptor.java:261)
        at org.red5.server.scheduling.QuartzSchedulingServiceJob.executeInternal
(QuartzSchedulingServiceJob.java:89)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJob
Bean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.j
ava:573)
[INFO] [RTMPConnectionExecutor-3] org.red5.server.stream.StreamService - closeSt
ream  stream id: 1 connection: RYD8WZVQBQPX1

**Comment by mekya** [comment]
Hi @ozankonur ,

Is it possible to let us know which rtmp publisher you use? So that we can try it. 

Generally it works perfectly with OBS.

Btw, if you wish, we can make a phone call. Just drop an email to mekya@antmedia.io

Sorry for late  reply 

Regards,
A. Oguz

**Comment by mekya** [comment]
I think this issue has already been closed so that I am closing.  

If I am wrong, please reopen the issue.
