### ISSUE TITLE
Websocket signaling ping/pong request

### ISSUE THREAD

**Issue by Stinkie** [ant-media/Ant-Media-Server#718]
In order to avoid websocket connection drop by network devices and to have a better check if connection is really alive we'd like to introduce 'ping' request. Simple response to it should be 'pong'

**Comment by mekya** [comment]
This is a simple client side to check connection is alive

**Comment by Stinkie** [comment]
currently if we send it - respose is smth like 'not supported method'. This is fine for now as it's basically the same. Reponding 'pong' is just more logical

**Comment by The-Code-Monkey** [comment]
@Stinkie how did you get it to do this as im getting the ws dropping out but it wont respond to me sending ping to it

**Comment by SelimEmre** [comment]
Hi @The-Code-Monkey,
Could you please check this documentation, https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Details#check-webrtc-connected-with-pingpong
Thanks, Selim

**Comment by The-Code-Monkey** [comment]
I am sending the ping command through @SelimEmre and its not returning the pong command has this feature been removed??
