### ISSUE TITLE
cPanel Intergration

### ISSUE THREAD

**Issue by BackyardVoyager** [ant-media/Ant-Media-Server#724]
Hello,
I am using Ant Media Server and I would like to run a cPanel or Vesta CP instance on the same server.

How can I do this without conflicting? I don't run to use virtulization, but will if it will be the only way to work.

**Comment by SelimEmre** [comment]
Hi @BackyardVoyager,
Thank you for your question. Ant Media Server is compatitible for Cpanel and Vesta CP. Normally you should not have any conflict. If you have any problem please re-open this issue. If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Also you can review our [Google Group](https://groups.google.com/forum/#!forum/ant-media-server)

Best Regards,
Selim
