### ISSUE TITLE
Sudden raise in RAM usage

### ISSUE THREAD

**Issue by BackyardVoyager** [ant-media/Ant-Media-Server#728]
I am curious as to why the node for Ant Media is raising like such.

The only thing running on this VPS is AntMedia. I even installed UFW, but that is it. It is on a fresh official ISO of Ubuntu 16.04

https://i.postimg.cc/BvwZ6M1L/graph.png
![graph](https://user-images.githubusercontent.com/45982355/50305189-1c51b880-0460-11e9-9a97-62881c67f794.png)

**Comment by BackyardVoyager** [comment]
![1-mem-b65805940353ee6a8915fe0c35008680e5c063e02676e0fb9aca350f28d1d8ad0a0ff8d544b71d4909ffc4d23e053140bb4a17585e31994f5aeeb328-86400](https://user-images.githubusercontent.com/45982355/50325202-7b8be900-04b1-11e9-8c4d-2e6bc650e51b.png)

**Comment by ntnahn** [comment]
I have same problem, when i turn on Recording mp4 the ant always use a lot of RAM (~ 8GB) and it cause the error:

`
Exception in thread "https-jsse-nio-0.0.0.0-5443-exec-12" java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 8G > maxPhysicalBytes = 7G
`

I cannot create new stream. I must to restart ant service to get it back to use.
I'm using the ant version 1.4.1, don't know the new version is fixed it yet?

**Comment by BackyardVoyager** [comment]
Any response or idea as to why this is happening? I maxed out today... thank god I am using virtualization on my node.

**Comment by SelimEmre** [comment]
Hi @BackyardVoyager,
Thank you for your feedback. Sorry for the delay. We are hard working these days. We solved this problem in the new version(1.6.1). Can you please update to the new version? If the ram problem persists, please reopen this issue.

**Comment by BackyardVoyager** [comment]
> Hi @BackyardVoyager,
> Thank you for your feedback. Sorry for the delay. We are hard working these days. We solved this problem in the new version(1.6.1). Can you please update to the new version? If the ram problem persists, please reopen this issue.

Hello,
How do I update the version without reinstalling?

**Comment by SelimEmre** [comment]
Hi @BackyardVoyager,
Can you look at this documentation >> https://github.com/ant-media/Ant-Media-Server/wiki/Getting-Started#41-update-over-older-version
