### ISSUE TITLE
Memory Leak 16.04

### ISSUE THREAD

**Issue by svonian** [ant-media/Ant-Media-Server#772]
# Issue

Memory Leak - Gradually increases and never freed

### Short description

When you stream to the antmedia server the memory gradually increases and does not ever get freed. As you start multiple streams or consecutive ones the memory goes up infinitely until you eventually reach out of resources.

### Environment

* Ubuntu 16.04
* Java 1.8.0_191
* Ant Media Server Community 1.6.0 (Dec 17, 2018)

### Expected behavior

Memory to free up so that we don't reach a situation where we are out of memory

### Steps to reproduce
1. Stream to antmedia server with any video
2. View system resources with a memory management tool, let it increase a few mb so it's noticeable
3. Terminate the streams
4. Witness that the memory does not free up (regardless of how long you wait or any consecutive streams)
5. Shut down the server and witness all memory get freed up

**Comment by burak-58** [comment]
Hi @svonian,
Thanks for your issue notification.
I have checked the issue with VisualVM but I didn't encounter with issue. Here is a screenshot:
![screenshot from 2019-01-09 16-42-24](https://user-images.githubusercontent.com/39169933/50906098-6a415700-1435-11e9-8b58-b944ae63de5e.png)
 
Can you give me more information about your use case. How many publishers and viewers did you start and which protocol did you use?

**Comment by svonian** [comment]
@burak-58 I've attached a few screenshots to (what I hope) helps illustrate the problem.

The visualvm shows the heap size and used heap properly collecting but when you use htop you'll see something else going on.

VisualVM
![screenshot 2019-01-10 at 15 37 15](https://user-images.githubusercontent.com/251562/50975419-d2537400-14ed-11e9-8b1a-18291845c4d7.png)

htop:
![screenshot 2019-01-10 at 15 37 00](https://user-images.githubusercontent.com/251562/50975424-d5e6fb00-14ed-11e9-926d-c1c130f64312.png)

htop after few seconds
![screenshot 2019-01-10 at 15 37 30](https://user-images.githubusercontent.com/251562/50975428-d8e1eb80-14ed-11e9-9f1d-bd7b472fa698.png)

Unless I close the server the memory stays occupied (even when closing connections)

[INFO] [vert.x-eventloop-thread-0] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_10 is finished with true
[INFO] [vert.x-eventloop-thread-8] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_3 is finished with true
[INFO] [vert.x-eventloop-thread-7] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_4 is finished with true
[INFO] [vert.x-eventloop-thread-6] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_2 is finished with true
[INFO] [vert.x-eventloop-thread-5] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_7 is finished with true
[INFO] [vert.x-eventloop-thread-4] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_6 is finished with true
[INFO] [vert.x-eventloop-thread-3] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_5 is finished with true
[INFO] [vert.x-eventloop-thread-2] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_1 is finished with true
[INFO] [vert.x-eventloop-thread-1] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_9 is finished with true
[INFO] [vert.x-eventloop-thread-9] io.antmedia.AntMediaApplicationAdapter - close broadcast operation for thirty_8 is finished with true

htop after closing the connections (server still running)
![screenshot 2019-01-10 at 15 41 09](https://user-images.githubusercontent.com/251562/50975586-3ece7300-14ee-11e9-9872-b2d597d8c80f.png)

Finally I run into this when I rerun the 20 publishers:

[INFO] [NioProcessor-2] org.red5.server.net.rtmp.RTMPConnection - Queue threshold reached. Discarding packet: session=[Z1BLPLIMCOYI3], msgType=[TYPE_AUDIO_DATA], packetNum=[433]
[INFO] [NioProcessor-1] org.red5.server.net.rtmp.RTMPConnection - Queue threshold reached. Discarding packet: session=[ZFENQBXBMBWPI], msgType=[TYPE_AUDIO_DATA], packetNum=[559]
[INFO] [NioProcessor-1] org.red5.server.net.rtmp.RTMPConnection - Queue threshold reached. Discarding packet: session=[ZFENQBXBMBWPI], msgType=[TYPE_AUDIO_DATA], packetNum=[621]
[INFO] [NioProcessor-14] org.red5.server.net.rtmp.RTMPConnection - Queue threshold reached. Discarding packet: session=[PXTCDUQPMMDSH], msgType=[TYPE_AUDIO_DATA], packetNum=[983]
[WARN] [NioProcessor-5] org.red5.server.net.rtmp.InboundHandshake - Client not compatible

The antmedia server eventually kills and frees up all the memory

**Comment by svonian** [comment]
hi @burak-58 

Thank you for responding.

I've executed as you say attached are some screenshots:

I wait a little longer and again side by side comparison of top and htop:

![image](https://user-images.githubusercontent.com/251562/51176153-7d807680-18bc-11e9-98ec-8fc01874c978.png)

I then kill the connections 

![image](https://user-images.githubusercontent.com/251562/51176181-91c47380-18bc-11e9-9564-0ab7f7053f07.png)

You can see the memory has not been freed and so I go live again

![image](https://user-images.githubusercontent.com/251562/51176289-d4864b80-18bc-11e9-97f2-c11a8988c67f.png)

and I kill the connections again

![image](https://user-images.githubusercontent.com/251562/51176315-e831b200-18bc-11e9-9688-29b7eb155fdd.png)

if you look at the available memory it's dropping and the used memory increases

I'm wondering if maybe you're using a mac as it is not reproducible on mac only ubuntu 16.04

**Comment by projectxmaker** [comment]
I found the same issue on Ubuntu 22.04 and this seems a big issue of Ant Media Server that has been existing till 2024!
