### ISSUE TITLE
simulate frame record exception

### ISSUE THREAD

**Issue by davutcavdar** [ant-media/Ant-Media-Server#785]
Bu konuda aldigimiz ikinci hata, ben virtual makinada ubuntuda CE denicem hatayi tekrar etmeyi ama webcami gormedi. Webcami gosterip tekrar etmeye caliscam : Your message: Hello, I'd like to experiment WebRTC broadcasting with
Antmedia Enterprise edition. Is it possible to have a free trial? The final
goal is to evaluate if I can use AntMedia for my business. Also, I've tried
running Community Edition but the WebRTC example doesn't work. I'm getting
server side errors such as: - No audio output stream (Is audioChannels > 0
and has start() been called?) - FrameRecorder$Exception: No video output
stream (Is imageWidth > 0 && imageHeight > 0 and has start() been called?)
Although publishing seems to work (from the browser) I can't play the
stream from anywhere.. I'm following this tutorial:

**Comment by maydin** [comment]
Ubuntu 18.04 icin bir musteri bu hatayi iletmisti, hatayi ubuntu 18.04'te tekrar edemedim,duzgun calisti.
