### ISSUE TITLE
Low quality streaming

### ISSUE THREAD

**Issue by BackyardVoyager** [ant-media/Ant-Media-Server#797]
Hello folks!

I know Ant Media is based around Red5, and that RTMP is not the professional protocol that TV news use (they use RTSP) but, it seems like when we stream video to our Ant Media server, the video quality doesn't look as sharp as it should be. It's like downscaling the quality to lesser HD. 

What I mean by this is for like high-quality graphics, they seem almost "blended" into the video. I'm not sure exactly how to say it, but if you watch a TV news broadcast, the quality is crisp and clear. With Ant Media, it's not that way.

Is this something we can configure or not? I want to do as crisp and clear as possible, not this 720p/540p video quality when we are able to output 1080p at 12-20 Mbps bitrate.

**Comment by SelimEmre** [comment]
Hi @BackyardVoyager,
Thank you for the great question. Sorry for the delay. We are hard working these days. How is your adaptive bitrate configuration ? If the Adaptive Bitrate settings are high, the broadcasting quality may decrease when the viewer's Internet is slow. 3 mbps enough for 1080p quality.  Can you try adaptive setting clear ? 

Best Regards,
Selim
