### ISSUE TITLE
Panel redesign implementation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#808]

**Comment by khanhonney** [comment]
* Menu changes
- Remove App Menu Item
- Add WebRTCAppEE as the second main menu item to the menu
- Add LiveApp as the second main menu item to the menu
- Add Live Streams, VoD, Setting sub-menu items to WebRTCAppEE and LiveApp

**Comment by khanhonney** [comment]
Body changes
- Remove TAB structure from Body (main section of the dashboard)
- Implement the first 4 group of settings in accordance with the attached design

![Screenshot from 2019-01-29 13-19-29.png](https://images.zenhubusercontent.com/5b067c484b5806bc2bd46f4a/e18cb5b2-5874-4bb6-95ac-a35d6e398243)
