### ISSUE TITLE
Mongo replica set support

### ISSUE THREAD

**Issue by Stinkie** [ant-media/Ant-Media-Server#821]
In order to make a reliable service we need to eliminate SPOF in cluster mode which is mongo db. 

https://docs.mongodb.com/manual/replication/

According to https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/datastore/db/MongoStore.java

it is possible to modify code to add replica set support as java mongo driver supports everything by itself.

replica set should be configurable by config files

**Comment by mekya** [comment]
Adding two sub items for this task. Is it ok @Stinkie ?

- [ ] Make changes in settings file and source to adapt replication [6] 1 day
- [ ] Add new test to automatic cluster testing environment [6] 1 day

Btw, we need to install mongo cluster. If it's ok for you, we can add a new issue for installing mongo cluster?

**Comment by Stinkie** [comment]
totally fine with sub items.  What do you mean by install? we will install by ourselves. so maybe you should add some options to install scripts so it does not install mongo cluster automatically because we will install mongo in containers aside from ams

**Comment by mekya** [comment]
If you install yourself, ok everything is good. We don't install by default  in our install script.
