### ISSUE TITLE
Uninstall script for Community and/or Enterprise

### ISSUE THREAD

**Issue by hakanbali68** [ant-media/Ant-Media-Server#823]

**Comment by MinhHungTrinh** [comment]
I installed the community edition. Now, I wanna install the new enterprise edition. How to uninstall this Community?

**Comment by neosepelios** [comment]
I installed the community edition. Now, I wanna install the new enterprise edition. How to uninstall this Community?

**Comment by SelimEmre** [comment]
Hi @neosepelios You can check this answer -> https://stackoverflow.com/questions/61969334/how-can-i-uninstall-ant-media-server-from-ubuntu-19-10
