### ISSUE TITLE
Make encoder settings configurable 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#826]
Parameters to configure via properties file
Generic
- encoder : Name of the encoder. X264, openh264, h264_nvenc.  If it's unset, use hardware encoder if available by default. 
- preset
- profile
- level
- rc
- encoder_specific: encoder specific parameter. It will be used if encoder supports like x264params

**Comment by The-Code-Monkey** [comment]
@mekya how would i change the encoder settings if i wanted to do it manually for the WebRTCApp, because in the red5-web.properties file there is a settings.encoderSettingsString how do i change that and what will it do if i do
