### ISSUE TITLE
Feature request: support EC2 instance profiles in AmazonS3StorageClient

### ISSUE THREAD

**Issue by sjauld** [ant-media/Ant-Media-Server#849]
# Issue

### Short description

Currently the AmazonS3StorageClient only supports authentication via the config file. Supporting auth via the EC2 instance profile would remove the need to have keys on the Ant server.

**Comment by SelimEmre** [comment]
Hi @sjauld,
Thank you for your interest. We will consider this feature in new versions. If you need further assistance, please feel free to send an email to contact[at]antmedia.io. 

Best Regards,
Selim

**Comment by sjauld** [comment]
Hi Selim,

I put together a PR at
https://github.com/ant-media/Ant-Media-Server-Common/pull/57 but didn't
properly link it here!

Cheers,

**Comment by SelimEmre** [comment]
Hi @sjauld,
Sorry for the delay. For security reasons, we don't receive a pull request from the outside. I have added your [PR 57](https://github.com/ant-media/Ant-Media-Server-Common/pull/57) into [PR 61](https://github.com/ant-media/Ant-Media-Server-Common/pull/61) Thank you for your interest.  If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Also you can review our [Google Group](https://groups.google.com/forum/#!forum/ant-media-server)

Best Regards,
Selim
