### ISSUE TITLE
Some cases ICE Connection Fails 

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#869]
It seems that when tcp candidates are gathered, ICE connections seems to failed?

Investigate this case.

**Comment by mekya** [comment]
What I figure out in the test logs.

Whenever it fails, I see that received ice candidates have tcptype candidates

Take confiugration received...
received message: {"candidate":"candidate:4112619227 1 udp 2122260223 172.17.0.2 47796 typ host generation 0 ufrag cl5R network-id 1","streamId":"stream_8762","label":1,"id":"video","command":"takeCandidate"}
Ice candidate received...
received message: {"candidate":"candidate:1510613869 1 udp 2122194687 127.0.0.1 52302 typ host generation 0 ufrag cl5R network-id 2","streamId":"stream_8762","label":1,"id":"video","command":"takeCandidate"}
Ice candidate received...
received message: {"candidate":"candidate:369102903 1 udp 1686052607 54.36.113.133 55886 typ srflx raddr 172.17.0.2 rport 55886 generation 0 ufrag cl5R network-id 1","streamId":"stream_8762","label":0,"id":"audio","command":"takeCandidate"}
Ice candidate received...
received message: {"candidate":"candidate:369102903 1 udp 1686052607 54.36.113.133 47796 typ srflx raddr 172.17.0.2 rport 47796 generation 0 ufrag cl5R network-id 1","streamId":"stream_8762","label":1,"id":"video","command":"takeCandidate"}
Ice candidate received...
[INFO] [<noname> - ] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - onAddTrack for streamId stream_8762
[INFO] [<noname> - ] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - onAddTrack for streamId stream_8762
[INFO] [<noname> - ] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - onAddStream for streamId stream_8762
[INFO] [<noname> - ] org.webrtc.audio.WebRtcAudioTrack - initPlayout(sampleRate=16000, channels=1)
[INFO] [<noname> - ] org.webrtc.audio.WebRtcAudioTrack - WebRTCAudioTrack initPlayout: org.webrtc.audio.WebRtcAudioTrack@41490af6
[INFO] [<noname> - ] org.webrtc.audio.WebRtcAudioTrack - byteBuffer.capacity:320 
[INFO] [<noname> - ] org.webrtc.audio.WebRtcAudioTrack - start playout org.webrtc.audio.WebRtcAudioTrack@41490af6
[INFO] [<noname> - ] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - starting playout for stream stream_8762
[INFO] [<noname> - ] io.antmedia.enterprise.adaptive.WebRTCEncoderAdaptor - onIceConnectionChange CHECKING
received message: {"candidate":"candidate:3147983403 1 tcp 1518280447 172.17.0.2 49177 typ host tcptype passive generation 0 ufrag cl5R network-id 1","streamId":"stream_8762","label":0,"id":"audio","command":"takeCandidate"}
Ice candidate received...
received message: {"candidate":"candidate:344579997 1 tcp 1518214911 127.0.0.1 52743 typ host tcptype passive generation 0 ufrag cl5R network-id 2","streamId":"stream_8762","label":0,"id":"audio","command":"takeCandidate"}
Ice candidate received...

**Comment by cooljser** [comment]
I meet the same problem.
Version: 1.9.1 community
Os: Ubuntu
