### ISSUE TITLE
Not able to delete VOD recordings from dashboard

### ISSUE THREAD

**Issue by krishnapsarthi** [ant-media/Ant-Media-Server#875]
Hello @SelimEmre ,

we are not able to delete recording from Ant Media dashboard. Specifically recording names having space in it.
Its throwing error :-

> HTTP Status 500 - Rewritten targetUri is invalid: http://localhost:5080/WebRTCAppEE/rest/broadcast/deleteVoDFile/videoTagshyam s0831161_13.mp4/432060709878940016731169/streamVod

We have deleted files from server but not able to delete them from db.

Is there a way to remove all recordings?

Thanks,

**Comment by SelimEmre** [comment]
Hi @krishnapsarthi,
Thank you for your interest. Firstly, do you use the latest version ?  You must be able to delete it from the dashboard. Please let me know if you have any problem. If you need further assistance, please feel free to send an email to contact[at]antmedia.io. Also you can review our `[Google Group](https://groups.google.com/forum/#!forum/ant-media-server)`

Best Regards,
Selim

**Comment by SelimEmre** [comment]
Hi @krishnapsarthi,
Sorry for the delay. We've fixed this in the last SNAPSHOT. Please contact us by email contact@antmedia.io  

Best Regards,
Selim
