### ISSUE TITLE
WebRTCAppEE not working on https://test.antmedia.io:5443/WebRTCAppEE

### ISSUE THREAD

**Issue by webdeveloper001** [ant-media/Ant-Media-Server#879]
# Issue

### Short description
__Brief description of what happened__
I am using https://test.antmedia.io:5443/WebRTCAppEE for testing Enterprise version of server and on my end I see that the stream is not started. 
I have inspected the console and I see the WebSocket request is sent with following message.
{"command":"publish","streamId":"stream1","token":"null","video":true,"audio":true}
After the message sent no response is recorded on my chrome inspector > Network > WS and also the button on UI remains "Start Publishing".

### Environment

* OS Version:  Ubuntu 18.04
* Java version:   10.0.2  (may be I am not sure my local Java version matters here)
* Ant Media Server version:  Enterprise Edition 1.6.0
* Browser name and version:  Google Chrome 72.0.3626.81 (Official Build) (64-bit)

### Expected behavior
On https://test.antmedia.io:5443/WebRTCAppEE/ page once I click Start publishing button it should start publish and button name should change to Stop publishing.

### Actual behavior
I see video captured on the screen and click Start publishing button but nothing happens.

### Steps to reproduce
1. goto https://test.antmedia.io:5443/WebRTCAppEE/  and allow camera / mic permission.
2. confirm that you see you face on page via camera and click start button.

### Logs
(index):273 screen share extension available
webrtc_adaptor.js:698 websocket connected
(index):256 initialized
webrtc_adaptor.js:712 sent message:{"command":"publish","streamId":"stream1","token":"null","video":true,"audio":true}

Above log is copied from my browser console.

**Comment by SelimEmre** [comment]
Hi @webdeveloper001,
Thank you for your interest. We are sorry for this situation. Now its working. Thanks.

Best Regards,
Selim
