### ISSUE TITLE
New AWS instance type: g3s.xlarge

### ISSUE THREAD

**Issue by sjauld** [ant-media/Ant-Media-Server#902]
# Issue

### Short description
__Brief description of what happened__
I tried to launch your AWS AMI on a g3s.xlarge but it's not supported. The available instance types seem to be a little out of date - could you review?

**Comment by sjauld** [comment]
Thanks for the info Ahmet! Is there another issue open for the driver
problem? I'd be keen to look at it since I'm about to do some load testing!

**Comment by mekya** [comment]
There is no other issue. We encounter this problem in this some specific instance types. 
I think a trick may help running on g3 instances. If you know or find out this trick, let us know. We would be happy to apply :)

**Comment by mekya** [comment]
The issue is that

Ant Media Server right now uses cuda 10.0 so that you need to specify the install the 10.0 runtime
```
sudo apt install cuda-runtime-10.0
```
If you already install the latest version like 10.1, then you can install following packets for compatibility
```
sudo apt install cuda-cudart-10.0
sudo apt install cuda-compat-10.0
```
