### ISSUE TITLE
Cannot stream: v1.6.1 enterprise

### ISSUE THREAD

**Issue by sjauld** [ant-media/Ant-Media-Server#904]
# Issue

### Short description
__Brief description of what happened__
When attempting to stream, connection is cut by the server.

### Environment

* Operating system and version: Using your AMI: AMS_Enterprise_1.6.1_GPU_AWS_Marketplace-90b66b3f-4a0f-43e0-a1ee-3bfdca56ba33-ami-065a5bbbe4da19018.4 (ami-0f0771346831e858d) on a g2.2xlarge
* Java version: 
* Ant Media Server version: v1.6.1
* Browser name and version: 

### Expected behavior
__Put as much detail here as possible__
We can stream

### Actual behavior
__Put as much detail here as possible__
We can't stream - the server seems to wait for an encoder (INFO  i.a.e.adaptive.WebRTCEncoderAdaptor - Waiting for encoder to be ready for bf8fc1e8-d681-46da-8704-a83400b44db2-ls-np81f3s) and then cuts the connection (INFO  i.a.e.adaptive.WebRTCEncoderAdaptor - onIceConnectionChange FAILED). Full logs below.

The last working version we were using was v1.4.1

### Steps to reproduce
1. Launch the AMI
2. Attempt to stream

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

https://pastebin.com/tkPd4t4z

**Comment by mekya** [comment]
Hi,

Ports are open for udp 5000-65000?

Regards,
A. Oguz

**Comment by sjauld** [comment]
You beauty! Thanks for the rapid response!

**Comment by mekya** [comment]
Glad to hear that. Enjoy ;)
