### ISSUE TITLE
Question : Can I install on CentOS 6?

### ISSUE THREAD

**Issue by aman811** [ant-media/Ant-Media-Server#910]
Our Linux server is not Ubuntu but CentOS. Will Ant Media Server run on it or does it specifically needs Ubuntu (and not RedHat) packages.

Also our website already has a COMODO SSL installed, so how to use that instead of LetsEncrypt SSL as mentioned in documentation?

**Comment by SelimEmre** [comment]
Hi @aman811,
Thank you for your interest. Your answers in below:

1- Yes, Ant Media Server supports Centos. Here is the script for installing to centos: https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server_redhat_beta.sh

2- Ant Media Server enable_ssl.sh script has 2 modes. In this case, you should choose 2. mode.
`sudo ./enable_ssl.sh -f {FULL_CHAIN_FILE} -p {PRIVATE_KEY_FILE} -d {DOMAIN_NAME}` 
Click Detail in: [Wiki ](https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Enable-SSL-for-Ant-Media-Server-%3F#v15-enable_sslsh-script-supports-external-fullchainpem-and-privkeypem-files-its-usage-has-been-changed-to)

But you need FULL_CHAIN_FILE and PRIVATE_KEY_FILE to implement the above script.

Run the following code to convert the .CRT file to the full chain file.
openssl x509 -inform PEM -in {path to crt.crt} > fullchain.pem

Run the following code to convert the SSL Key file to the Private Key file.
openssl rsa -in {path to ssl key} -text > privkey.pem

Once these 2 files are ready, you can use the enable_ssl script.

I hope, I could hepl you. Please inform us, if you have any question. Good Luck!

Best Regards,
Selim

**Comment by aman811** [comment]
Hi,

Thanks for your reply. I have another question.

One of the docs says that I should run the install-ant-media-server.sh   command on the zip file.

Another doc (for the android app - https://github.com/ant-media/LiveVideoBroadcaster)  says that I should extract the zip folder and run start.sh  command. 

Can you tell the difference between the two? Or Do I need to do both as in  run start.sh after the install command?

My end aim is Android only, so I don't care about streaming on web browser. So if these two are different things, should I do the 2nd one for my project?

**Comment by SelimEmre** [comment]
Hi @aman811,
Thank you for your question. Install script and start.sh difference is Install script check java version, add service, update version etc. But start.sh script is only start Ant Media Server. It's not control java version and other requirements. So we recommend use install script. If you use install script, it's fulfills all requirements. Also antmedia service auto start every reboot. You don't have to restart start.sh every reboot. 

Please feel free to ask question. Good Luck! 

Best Regards,
Selim

**Comment by fusionstream** [comment]
Just want to say URL seems to now be at:
https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server_centos.sh

**Comment by aksthelion** [comment]
The install script is not located at above url. Where is it now?

**Comment by mekya** [comment]
We merge the install scripts into a single one. 

Below script supports installing to Centos 8

https://github.com/ant-media/Scripts/blob/master/install_ant-media-server.sh
