### ISSUE TITLE
If we send audio only stream to ant media server it could not start recording

### ISSUE THREAD

**Issue by avinashlakhera** [ant-media/Ant-Media-Server#915]
If we send audio only stream to ant media server it could not start recording

**Comment by SelimEmre** [comment]
Hi @avinashlakhera,
Thank you for great feedback. We added this problem to the to-do list. Thanks.

Best Regards,
Selim

**Comment by krishnasarthi** [comment]
Has this bug been fixed in latest version?

**Comment by kalradivyanshu** [comment]
I am facing the same issue. Can anyone help me out?

**Comment by mekya** [comment]
Hi, 

Could you please provide reproduce scenario?

**Comment by mekya** [comment]
I'm reopening the case. 

Could you please provide reproduce scenario?  @kalradivyanshu @krishnasarthi

**Comment by mekya** [comment]
Sorry you already created this issue #2549 . Closing this one again
