### ISSUE TITLE
Nonmatching transport in server reply

### ISSUE THREAD

**Issue by henriqueng** [ant-media/Ant-Media-Server#961]
# Issue

### Short description
Error "Nonmatching transport in server reply" when I try to register a stream.

### Environment

* Operating system and version: Ubuntu 18.04.2 LTS
* Java version: 1.8.0_201
* Ant Media Server version: 1.6.1 CE (190108_1656)
* Browser: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
* IP Cam: Luatek LKW-1310

### Expected behavior
Status: Online

### Actual behavior
Status in Web Interface: Offline
Error in console: "Nonmatching transport in server reply"

Obs. 1: In wireshark, it seems like the IP Camera is trying to stream to ant media server.
Obs. 2: "Stream URL" is right (I have tested it using "Open Network Stream" of VLC)

### Steps to reproduce
1. New Live Stream
2. Stream Source
3. Name: MyCam
4. Stream URL: rtsp://admin:PassworD1@10.26.6.37:554/onvif1
5. Create

### Logs
https://pastebin.com/raw/kJvRrsJN
https://pastebin.com/raw/HxDnwFfT
Console: https://pastebin.com/raw/KJgJ4SKK
Wireshark file: http://s000.tinyupload.com/index.php?file_id=01213974717368851438
(Ant Media Server: 10.26.6.127; IP Camera: 10.26.6.37)

**Comment by mekya** [comment]
Closing this issue. Please try with newer versions. 

If the problem still exists, please re-open this issue.
