### ISSUE TITLE
Got 403 forbidden on VoD Delete

### ISSUE THREAD

**Issue by code76kb** [ant-media/Ant-Media-Server#992]
# Issue

### Short description
__Faild to delete VoD file when api is called from postman __

### Environment

* Operating system and version: ubuntu
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Expected behavior
__video should be deleted__

### Actual behavior
__Got 403 forbidden__

### Steps to reproduce
http://localhost:5080/ConsoleApp/rest/request?_path=LiveApp/rest/broadcast/deleteVoD/210250160387090747333460

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Closing this issue for the inactivity. This issue is probably fixed in new versions. 

Please check the new version and re-open the issue if it still exists.
